const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Cloud & DevOps",
  slug: "cloud-devops",
  description: "AWS, Azure, Docker, Kubernetes, CI/CD, deployment",
  theme: {
    accent: "#2563eb",
    hubFill: "#2563eb",
    hubText: "#ffffff",
    centerFill: "#dbeafe",
    centerStroke: "#2563eb",
    label: "Cloud",
  },
  beginner: [
    Q(
      "What is the difference between IaaS, PaaS, and SaaS?",
      "IaaS rents VMs, disks, and networks — you patch the OS. PaaS rents a runtime (app service, Cloud Run) — you ship code. SaaS is the finished product (email, CRM) — you just use it.",
      "The shared responsibility line moves up the stack. Interviews want one example each: EC2/Azure VM, Heroku/App Service, Gmail/Office 365. Serverless functions sit near PaaS with a different billing shape.",
      layers("Who runs which layer", [["SaaS", "Vendor runs the app"], ["PaaS", "You bring code"], ["IaaS", "You bring the OS"], ["On-prem", "You bring the building"]], "The acronym is about where your responsibility stops"),
    ),
    Q(
      "How do AWS and Azure compare at a basics level?",
      "Both sell regions, VMs, object storage, managed databases, IAM, and load balancers. Names differ: S3 vs Blob, EC2 vs Virtual Machines, IAM vs Entra ID plus RBAC, VPC vs VNet.",
      "Interviews do not need a catalog. Map the problem to compute, store, network, identity. Multi-cloud “for safety” without a team that can run two platforms is usually extra cost.",
      compare("Same jobs, different names", ["AWS", "EC2, S3, IAM, VPC", "Largest ecosystem", "Accounts + orgs"], ["Azure", "VM, Blob, Entra, VNet", "Strong Microsoft shops", "Subscriptions + tenants"], "Learn the primitives — the logo is not the architecture"),
    ),
    Q(
      "What is a Docker image vs a container?",
      "An image is an immutable template (layers of filesystem + a start command). A container is a running (or stopped) instance of that image with its own writable layer and process tree.",
      "Build once, run many. Registries store images. Containers share the host kernel — they are not a full VM. Interviews: “docker run” creates a container from an image.",
      compare("Recipe vs running copy", ["Image", "Immutable layers", "Tagged in a registry", "No running process", "docker build"], ["Container", "Instance of an image", "Writable layer on top", "Has a PID namespace", "docker run"], "The image is the artifact; the container is the process"),
    ),
    Q(
      "What is a Kubernetes pod?",
      "A pod is the smallest deployable unit: one or more containers that share network namespace and volumes, scheduled together on a node.",
      "Usually one app container plus optional sidecars. Pods are mortal — controllers (Deployment) recreate them. Do not treat a pod IP as a stable address; use a Service.",
      hub("Smallest k8s unit", "Pod", [["Containers", "Share localhost"], ["IP", "One address in the pod"], ["Volume", "Shared disk mounts"], ["Node", "Where it is scheduled"], ["Mortal", "Controllers replace it"]], "A pod is a wrapper for containers that must be together"),
    ),
    Q(
      "What is a Kubernetes Service?",
      "A Service is a stable virtual IP (and DNS name) that load-balances to a set of pods selected by labels. Pods come and go; the Service name stays.",
      "ClusterIP is internal. NodePort opens a port on nodes. LoadBalancer asks the cloud for an external LB. Ingress (or Gateway) routes HTTP by host and path. Interviews: Services are discovery plus LB, not “just a port.”",
      steps("Find healthy pods", [["Label", "Select the pods"], ["VIP", "Stable ClusterIP"], ["Kube-proxy", "Route to endpoints"], ["DNS", "my-svc.my-ns"]], "Clients talk to the Service, never to a random pod IP"),
    ),
    Q(
      "What is CI/CD?",
      "CI (continuous integration) builds and tests every change. CD (continuous delivery or deployment) ships that artifact to an environment, either with a button or automatically.",
      "A pipeline is stages: lint, test, build image, scan, deploy. The artifact should be the same binary that was tested. “We deploy from a laptop” is the anti-pattern.",
      timeline("Commit to running app", [["Commit", "Open a PR"], ["CI", "Test and build"], ["Artifact", "Image or package"], ["CD", "Deploy to env"], ["Verify", "Smoke / health"]], "CI proves the change; CD puts the proven artifact in production"),
    ),
    Q(
      "What is blue-green deployment?",
      "You run two production environments: blue (live) and green (new). After green is healthy, you flip the load balancer. Rollback is flipping back.",
      "You pay for two stacks during the cut. Database migrations still need a plan — the flip does not make schema compatible. Canary is a different strategy (a slice of traffic).",
      compare("Two stacks, one live", ["Blue-green", "Full parallel env", "Instant switch", "Double cost briefly", "Rollback = flip"], ["In-place", "Replace on the same set", "Cheaper", "Harder rollback", "Partial mix of versions"], "Blue-green is a traffic switch, not a magic migration"),
    ),
    Q(
      "What is Infrastructure as Code?",
      "IaC means the cloud resources are declared in files (Terraform, Bicep, CloudFormation) and applied by a tool, not clicked in a console.",
      "You get review, repeatability, and drift detection. State (Terraform) records what exists. Interviews: never leave production as a pile of manual clicks. Policy as code is the next step.",
      steps("Declare, then apply", [["Write", "Resources in git"], ["Plan", "Diff vs live"], ["Apply", "Create/update/delete"], ["Review", "PR on the change"]], "If it is not in git, it is not your real infrastructure"),
    ),
    Q(
      "What is IAM?",
      "Identity and Access Management answers who can do what on which resource. Users, roles/service principals, and policies (allow/deny) are the building blocks.",
      "Least privilege: grant the action and resource needed, not AdministratorAccess. Prefer roles for apps over long-lived access keys. Root/global admin is for break-glass only.",
      hub("Who may do what", "IAM", [["Identity", "User or role"], ["Policy", "Allow or deny actions"], ["Resource", "Which ARN / scope"], ["Assume", "Apps use roles"], ["Audit", "CloudTrail / logs"]], "IAM is the lock on the cloud account — misconfig is a breach"),
    ),
    Q(
      "What is a VPC (or VNet)?",
      "A virtual network is your isolated slice of the cloud: IP ranges, subnets, route tables, and gateways. Public subnets can reach the internet; private ones go out through NAT if at all.",
      "Security groups (AWS) / NSGs (Azure) are stateful firewalls on NICs. Do not put databases on a public IP. Peering and PrivateLink connect networks without the public internet.",
      layers("Your private network", [["Region", "Where it lives"], ["VPC / VNet", "CIDR you own"], ["Subnet", "Public or private"], ["NIC / VM", "Gets an IP"]], "If it has a public IP, the internet can find it — plan for that"),
    ),
    Q(
      "What are health checks?",
      "A health check is a probe the platform uses to decide if an instance should receive traffic or be restarted. Failed checks remove the node from the pool.",
      "Load balancers and Kubernetes both use them. A check that only returns 200 while the database is down will serve errors. Deep vs shallow checks is a design choice.",
      steps("Ask if it can work", [["Probe", "HTTP or TCP"], ["Pass", "Keep in the pool"], ["Fail", "Stop sending traffic"], ["Restart", "If it stays dead"]], "Health checks are how the platform notices you are down"),
    ),
    Q(
      "What is a rolling deploy?",
      "A rolling deploy replaces instances in batches: start new, wait until healthy, stop old. Users see a mix of versions until the roll finishes.",
      "Kubernetes Deployment does this with maxSurge and maxUnavailable. Rollback is a roll forward to the previous ReplicaSet. Incompatible API changes need two-phase deploys.",
      timeline("Replace a few at a time", [["Surge", "Add new pods"], ["Ready", "Pass probes"], ["Shift", "Service sends them traffic"], ["Remove", "Terminate old pods"]], "Rolling means mixed versions — design for that window"),
    ),
    Q(
      "How should secrets be handled?",
      "Secrets are passwords, tokens, and keys. Store them in a manager (AWS Secrets Manager, Azure Key Vault, Kubernetes Secrets with encryption), inject at runtime, never commit them to git.",
      "Rotate on leak and on a schedule. Apps should use IAM roles where possible instead of static keys. .env files in the repo are a finding, not a strategy.",
      hub("Keep keys out of git", "Secret", [["Store", "Vault / manager"], ["Inject", "Env or file at run"], ["Rotate", "New value, old dies"], ["Audit", "Who read it"], ["IAM", "Prefer roles over keys"]], "A secret in the Dockerfile or chat log is already leaked"),
    ),
    Q(
      "What does observability mean in cloud and DevOps?",
      "You need metrics, logs, and traces from apps and from the platform (LB, kube, cloud APIs) so you can see why a deploy or a region failed.",
      "Wire request ids through the gateway. Alert on user SLOs, not on “CPU high” alone. Cloud vendor consoles are a start; they do not replace structured app logs.",
      layers("App plus platform", [["User SLO", "Did checkout work?"], ["App", "Metrics, logs, traces"], ["Platform", "K8s, LB, queue depth"], ["Cloud", "API errors, quotas"]], "If you only watch VM CPU, you will miss the bad deploy"),
    ),
    Q(
      "What is GitOps?",
      "GitOps means git is the desired state: a controller (Argo CD, Flux) continuously compares the cluster to the repo and reconciles. You ship by merging, not by running kubectl from a laptop.",
      "The repo is auditable and the cluster self-heals drift. Secrets still need a sealed or external pattern. GitOps is CD with pull-based reconcile, not a new YAML dialect.",
      cycle("Git is the source of truth", "GitOps", [["Commit", "Desired YAML"], ["Sync", "Controller diffs"], ["Apply", "Cluster matches git"], ["Drift", "Revert or alert"]], "If kubectl apply is the real source of truth, you are not doing GitOps"),
    ),
  ],
  intermediate: [
    Q(
      "When do you pick IaaS vs PaaS vs serverless?",
      "IaaS when you need custom OS, networking, or licensed software. PaaS when the unit is an app and you want patches handled. Serverless (functions, managed queues) when load is spiky and you can live with cold starts and limits.",
      "Portability, vendor lock, and local-dev fidelity all get worse as you go up the stack. Cost models flip: idle VMs waste money; functions waste money on chatty high-QPS if you are not careful.",
      compare("Control vs ops load", ["IaaS / VMs", "Full OS control", "You patch and scale", "Steady 24/7 loads"], ["PaaS / functions", "Less OS work", "Limits and cold start", "Spiky or product teams"], "Pick the layer that matches ops skill and traffic shape"),
    ),
    Q(
      "Which AWS and Azure services map for a typical web app?",
      "Compute: ECS/EKS or App Service/AKS. Objects: S3 or Blob. DB: RDS or Azure SQL / Flexible Server. Secrets: Secrets Manager or Key Vault. CDN: CloudFront or Front Door/CDN. Identity: IAM plus Cognito vs Entra ID.",
      "The interview is the architecture, not trivia. Know one managed Kubernetes, one object store, one IAM story. “We will use 40 services” is a smell.",
      hub("A boring production map", "Stack", [["Compute", "VM, kube, or PaaS"], ["Store", "Object + DB"], ["Edge", "CDN + WAF"], ["Id", "IAM / Entra"], ["Observe", "Logs + metrics"]], "Name five primitives — not the entire marketplace"),
    ),
    Q(
      "How do Docker image layers and multi-stage builds work?",
      "Each Dockerfile instruction adds a layer. Unchanged layers cache. Multi-stage builds compile in a fat image and copy only the binary into a slim runtime image so production is smaller and has fewer tools.",
      "Order COPY so dependency layers change less often. Do not bake secrets into layers — they stay in history. Pin tags or digests; latest is not reproducible.",
      code("Build fat, ship slim", "Dockerfile", ["FROM golang:1.22 AS build", "RUN go build -o app", "FROM gcr.io/distroless/static", "COPY --from=build /app /app"], [["Cache", "Deps layer before source"], ["Runtime", "No compiler in prod"]], "The image you scan and run should not contain the toolchain"),
    ),
    Q(
      "How do Deployments and ReplicaSets keep desired state?",
      "You declare replicas and a pod template. A ReplicaSet keeps that many pods alive. A Deployment owns ReplicaSets to roll out a new template and to roll back.",
      "Kubernetes is a reconcile loop: observe, diff, act. If you delete a pod, it comes back. If you kubectl edit live and GitOps is on, git will fight you. That is intended.",
      cycle("Declare, then reconcile", "k8s", [["Desire", "replicas: 3"], ["Observe", "Two pods live"], ["Diff", "Need one more"], ["Act", "Create a pod"]], "Desired state is a loop — not a one-shot create"),
    ),
    Q(
      "ClusterIP vs NodePort vs LoadBalancer vs Ingress?",
      "ClusterIP is in-cluster only. NodePort publishes on every node’s port (awkward, often a building block). LoadBalancer provisions a cloud LB per Service. Ingress (or Gateway API) is one HTTP router for many services.",
      "On AWS, LoadBalancer Services used to spawn extra ELBs; Ingress with ALB/NGINX is the usual HTTP pattern. Internal vs internet-facing is an annotation / SKU choice.",
      compare("Internal VIP vs HTTP edge", ["Service types", "ClusterIP / NodePort / LB", "L4, one SVC"], ["Ingress / Gateway", "Host and path rules", "TLS, one edge", "Many backends"], "HTTP routing belongs at Ingress, not a NodePort per microservice"),
    ),
    Q(
      "What belongs in a CI/CD pipeline besides “build and deploy”?",
      "Unit/integration tests, image build, vulnerability scan, SBOMs, signed artifacts, deploy to a staging env, smoke tests, then prod with an approval or auto if the SLO allows.",
      "Promote the same image digest — do not rebuild for prod. Separate credentials per environment. A pipeline that can reach prod from a fork PR is a supply-chain bug.",
      timeline("Gates on the way to prod", [["Test", "Fail the merge"], ["Scan", "CVE policy"], ["Sign", "Provenance"], ["Stage", "Same digest"], ["Prod", "Approve or auto"]], "CD ships the artifact CI already proved — not a new build"),
    ),
    Q(
      "Blue-green vs canary vs rolling — how do you choose?",
      "Rolling is cheap and native in Kubernetes. Blue-green is a fast rollback with double capacity. Canary sends a small percent (or a user cohort) and watches error/latency before continuing.",
      "Canary needs good metrics and a way to pin users. All three still need backward-compatible schema. Feature flags can decouple “code live” from “feature on.”",
      compare("How traffic meets the new version", ["Rolling / BG", "Batches or a flip", "Simple to reason", "Coarse rollback"], ["Canary", "1% then 10% then 100%", "Needs SLOs", "Best blast-radius"], "If you cannot measure the canary, you are just doing a slow roll"),
    ),
    Q(
      "What is Terraform state and why does drift matter?",
      "State is Terraform’s map from your config to real resource IDs. Without remote state locking, two applies corrupt the map. Drift is the cloud changed outside Terraform (console click, another tool).",
      "terraform plan is the review artifact. Import brings orphans under management. Never commit state with secrets; use a backend with encryption. Refresh before you apply in a shared account.",
      steps("Keep config and cloud aligned", [["Remote state", "S3 / Azure blob + lock"], ["Plan", "Show the diff"], ["Apply", "One executor"], ["Drift", "Plan detects clicks"]], "Two applies without a lock is how you duplicate a database"),
    ),
    Q(
      "How do roles, policies, and least privilege fit together?",
      "A policy lists actions and resources. You attach it to a user or (better) a role. Apps assume a role via instance profile, IRSA, or workload identity — no access keys in env if you can avoid it.",
      "Deny on the wildcard resource is not least privilege. Condition keys (source VPC, MFA, tags) tighten further. Regular access reviews beat a perfect policy written once.",
      hub("Grant the smallest action", "RBAC", [["Role", "What the job needs"], ["Policy", "Action + resource"], ["Assume", "Short-lived creds"], ["Condition", "MFA, VPC, tags"], ["Review", "Remove unused"]], "Long-lived access keys in a pod are a finding"),
    ),
    Q(
      "How do subnets, NAT, and security groups differ from NACLs?",
      "Subnets carve the VPC. NAT lets private subnets start outbound internet without being inbound-public. Security groups are stateful per NIC. NACLs are stateless subnet firewalls — you must allow return traffic explicitly.",
      "Most app isolation is security groups plus private subnets. NACLs are extra hardening or an emergency block. Route tables decide whether a subnet is public (IGW) or private.",
      layers("Packets leaving a private app", [["SG", "Allow 443 out"], ["NACL", "Subnet allow"], ["NAT", "Shared egress IP"], ["IGW", "Only for public subnets"]], "Stateful SG vs stateless NACL is the usual trick question"),
    ),
    Q(
      "Liveness vs readiness vs startup probes?",
      "Liveness: if it fails, kill and restart the container (deadlock). Readiness: if it fails, leave it running but stop sending traffic (warmup, dependency blip). Startup: give slow boots a window before liveness starts.",
      "A liveness probe that hits the database will restart everyone in an outage and make it worse. Readiness should include critical deps if you must not take traffic without them.",
      compare("Restart vs unready", ["Liveness", "Kill the container", "For stuck processes", "Must be cheap and local"], ["Readiness", "Remove from Service", "For warmup and deps", "Can be stricter"], "Wrong liveness is an outage amplifier"),
    ),
    Q(
      "What do maxUnavailable, maxSurge, and PodDisruptionBudgets do?",
      "maxSurge is extra pods allowed during a roll. maxUnavailable is how many can be down. A PDB says the cluster (and you) must keep minAvailable during voluntary disruption (drains, upgrades).",
      "Cloud node upgrades drain nodes; without a PDB, you can evict too many. surge=0 and unavailable=0 cannot roll. Interviews: connect this to capacity and disruption, not just YAML fields.",
      hub("How a roll is allowed to look", "Roll", [["Surge", "Extra new pods"], ["Unavailable", "How many may be down"], ["PDB", "Floor during drains"], ["Quota", "Must fit the extra"], ["Budget", "Error SLO during mix"]], "A roll that cannot surge still needs spare capacity on nodes"),
    ),
    Q(
      "How do you inject secrets without putting them in git?",
      "External stores (Key Vault, Secrets Manager) plus CSI drivers or runtime fetch. Sealed Secrets / SOPS encrypt for git if you must. Short-lived tokens from workload identity beat static passwords.",
      "Kubernetes Secrets are base64, not encryption, unless you enable encryption at rest. Rotate by changing the store and bouncing pods that cache env vars (env is not live-reload).",
      compare("Where the value lives", ["Vault / CSI", "Source of truth outside git", "Rotate centrally", "Needs IAM to read"], ["Sealed / SOPS", "Encrypted in git", "PR-reviewable", "Key management is the hard part"], "Git may hold ciphertext — the plaintext key still needs a home"),
    ),
    Q(
      "How do you observe a Kubernetes app in AWS or Azure?",
      "Use a metrics backend (CloudWatch, Azure Monitor, Prometheus), ship logs (Fluent Bit, Container Insights), and trace with OpenTelemetry to X-Ray or App Insights / Tempo.",
      "Label metrics with deployment and version. Alert on error rate and latency of the Service, not only pod restarts. kubectl logs is not the production strategy.",
      layers("From pod to pager", [["Probe", "Local health"], ["Metrics", "RED on the Service"], ["Logs", "Structured + trace_id"], ["Trace", "Gateway to DB"], ["Alert", "SLO burn"]], "Platform metrics without app RED will miss a 500 that uses little CPU"),
    ),
    Q(
      "GitOps pull vs pipeline push — what is the difference?",
      "Push CD: the pipeline’s last step kubectl/helm applies (needs cluster creds in CI). Pull GitOps: the cluster agent reads git and applies (creds stay in-cluster). Both need the same artifact digest.",
      "Pull is better for drift and multi-cluster. Push is simpler for a first app. Mix: CI builds and tags; GitOps only changes the tag in git. Never let both fight the same object without a rule.",
      compare("Who talks to the API server", ["Push CD", "CI has kube creds", "Easy to start", "Drift until next job"], ["Pull GitOps", "Agent in cluster", "Reconcile forever", "Git is the API"], "CI should produce the image; GitOps should select the tag"),
    ),
  ],
  expert: [
    Q(
      "How does the shared responsibility model change by service type?",
      "IaaS: vendor secures the building and hypervisor; you secure OS, network, data, IAM. PaaS: vendor patches the runtime; you still own app code, identities, and data classification. SaaS: you own accounts, sharing, and what you upload.",
      "Misconfigured S3/Blob public access is still on you. Encryption keys (CMK vs platform) are a data-residency decision. Expert interviews: name what you still patch after “we moved to the cloud.”",
      layers("The line you still own", [["Vendor", "Hardware, hypervisor, sometimes runtime"], ["Config", "IAM, SG, public access"], ["App", "Code and deps"], ["Data", "Classify, encrypt, backup"]], "The cloud is not your IAM policy and not your public bucket"),
    ),
    Q(
      "When is multi-cloud worth it vs a well-built landing zone?",
      "A landing zone (org/accounts or management groups, baseline IAM, network hub, logging) gives blast-radius and audit inside one vendor. Multi-cloud is insurance against outage or procurement — it doubles platform skill and IAM stories.",
      "Portable apps (containers, Terraform) help; data gravity and managed DB features do not. Expert answer: active-active multi-cloud is rare; standby or SaaS-escape is more honest.",
      compare("One vendor done well vs two", ["Landing zone", "Account vending", "Org-wide guardrails", "One IAM brain"], ["Multi-cloud", "Two networks and IAM", "Portable subset only", "Real cost in people"], "Portability is a product constraint, not a checkbox on the RFP"),
    ),
    Q(
      "How do you secure the container supply chain?",
      "Pin digests, scan in CI, generate SBOM, sign (cosign) and verify at admit time (Kyverno/OPA/admission). Distroless or minimal base reduces CVE noise. Only CI can push to prod registries.",
      "latest tags and docker build on a laptop are supply-chain holes. Rebuilds for prod break provenance. Expert: attestations (SLSA) bind commit, builder, and digest.",
      steps("From commit to admit", [["Build", "Hermetic CI"], ["SBOM", "What is inside"], ["Sign", "Key or identity"], ["Verify", "Admission policy"]], "If the cluster will run any tag from the registry, signing did nothing"),
    ),
    Q(
      "What is the Kubernetes control plane vs data plane?",
      "Control plane (API server, etcd, scheduler, controllers) stores desired state and assigns pods. Data plane is kubelet, kube-proxy/CNI, and your workloads on nodes. etcd loss is a restore problem; node loss is a reschedule problem.",
      "Managed Kubernetes hides etcd but not your app. Scheduler predicates (taints, affinity, topology) decide packing. Expert: API server is not on the request path of ClusterIP traffic.",
      layers("Who decides vs who runs", [["etcd", "Cluster state"], ["API / controllers", "Reconcile"], ["Scheduler", "Bind pod to node"], ["Kubelet", "Run the containers"], ["CNI", "Pod network"]], "Control plane outage blocks change; data plane keeps serving until pods die"),
    ),
    Q(
      "How do NetworkPolicy, DNS, and a service mesh change cluster traffic?",
      "Without NetworkPolicy, many CNIs allow all pod-to-pod. Policies are default-deny plus allow. CoreDNS implements Service names. A mesh (Istio, Linkerd) adds mTLS, retries, and telemetry in sidecars or ztunnel — it is not a substitute for NetworkPolicy everywhere.",
      "Mesh retries can amplify outages (retry storms). mTLS identity is SPIFFE, not just a network ACL. Expert interviews want “defense in layers,” not “we installed Istio so we are secure.”",
      hub("East-west traffic", "Path", [["DNS", "Service name to VIP"], ["Kube-proxy", "To endpoints"], ["NetPol", "Who may connect"], ["Mesh", "mTLS + retries"], ["App", "Still authn/z"]], "A mesh without retry budgets can DDoS yourself"),
    ),
    Q(
      "How do you do progressive delivery with feature flags?",
      "Ship the binary dark, enable the flag for 1% of users, watch SLO, then widen. Flags decouple deploy risk from product risk. Kill switches beat rollback when the badness is a config.",
      "Flag debt is real — remove them. Server-side evaluation avoids leaking unfinished UI. Combine with canary so a bad binary still has a small blast radius even if the flag is on.",
      timeline("Deploy dark, then open", [["Ship", "Code off by default"], ["Canary", "Small replica share"], ["Flag", "Cohort of users"], ["Watch", "Error budget"], ["Cleanup", "Delete the flag"]], "A flag that never dies is a second configuration plane"),
    ),
    Q(
      "How do you cut over databases in a blue-green world?",
      "Expand/contract schema: add backward-compatible columns, dual-write or dual-read if needed, then drop old. The traffic flip cannot move an incompatible schema. Long-running jobs must drain.",
      "Blue and green sharing one DB is common and means the DB is not blue-green. True two-database cut needs replication lag and a freeze. Expert: the data plane is the hard part of “zero downtime.”",
      steps("Schema before the flip", [["Expand", "Compatible change"], ["Deploy", "Code that reads both"], ["Migrate", "Backfill"], ["Flip", "Traffic or writes"], ["Contract", "Remove the old"]], "Blue-green the app only after the schema can live on both"),
    ),
    Q(
      "How do Terraform modules and policy as code fit a landing zone?",
      "Modules encode blessed patterns (VPC, EKS, logging). Policy as code (OPA, Sentinel, Azure Policy) blocks public buckets and missing tags at plan or at the cloud control plane. CI runs fmt, validate, plan, and policy before apply.",
      "A module is not a platform if teams still copy-paste state. Account vending plus a pipeline that only applies through code review is the real control. Drift from ClickOps should fail a nightly plan.",
      hub("Guardrails on apply", "Policy", [["Module", "Blessed defaults"], ["OPA / Sentinel", "Reject the plan"], ["Azure Policy", "Deny at ARM"], ["SCPs", "Org-level AWS deny"], ["CI", "Only path to prod"]], "A wiki saying “no public S3” is not a control"),
    ),
    Q(
      "What is IRSA / workload identity and the confused deputy problem?",
      "The pod assumes a cloud role via a projected OIDC token bound to its ServiceAccount — no static keys. Confused deputy: a role that trusts too many subjects or a webhook that calls AWS with the caller’s power. Scope the trust policy to the exact SA and cluster issuer.",
      "Instance profiles on nodes are too wide if every pod can reach the metadata IP — block it and use IRSA. Azure equivalent is federated workload identity. Expert: name the audience and subject in the trust policy.",
      compare("Keys vs federation", ["Access keys", "Long-lived", "Leak in logs", "Hard to rotate"], ["IRSA / OIDC", "Short token", "Bound to SA", "Trust policy must be tight"], "A role that trusts every ServiceAccount is still a master key"),
    ),
    Q(
      "How do you design private connectivity: hub-spoke, endpoints, zero trust?",
      "Hub-spoke: shared services (DNS, inspection) in a hub, apps in spokes, peering or transit gateway. Private endpoints (PrivateLink / Private Endpoint) expose PaaS on a private IP so you disable public data-plane. Zero trust: identity plus device plus least privilege, not a fat VPN as the only control.",
      "Hairpinning all traffic through a single firewall is a latency and scale trap. Expert: public load balancers plus WAF vs internal-only plus bastion/SSM — pick from data classification.",
      layers("No public data plane", [["Spoke", "App subnets private"], ["Endpoint", "PaaS on private IP"], ["Hub", "Shared DNS / inspect"], ["Identity", "IAM over flat VPN"]], "A peered mesh of every VPC is not a network design"),
    ),
    Q(
      "How do bad probes and bad PDBs cause production outages?",
      "Liveness on a shared dependency restarts the fleet together. Readiness that never goes ready after a config error removes all pods from the Service (zero endpoints). A PDB that forbids all evictions blocks node upgrades and patches.",
      "Fix: shallow liveness, dependency-aware readiness, PDB minAvailable that still allows a roll, and pod anti-affinity so one node death is not all replicas. Chaos and a staging drain rehearsal catch this.",
      cycle("Probe-induced outage", "Fail", [["Dep down", "Liveness fails"], ["Restart", "All pods at once"], ["Thundering", "Retry the dep"], ["Worse", "Longer outage"]], "Probes are production traffic — treat them like a feature"),
    ),
    Q(
      "Recreate, rolling, blue-green, canary — expert tradeoffs?",
      "Recreate: downtime, simple, OK for workers. Rolling: default, mixed versions, needs compatible APIs. Blue-green: extra cost, clean flip, DB still shared. Canary: best science, needs automation and SLOs; slow if you wait on rare bugs.",
      "StatefulSets and jobs do not follow Deployment semantics. Session stickiness fights canaries. The expert move is matching strategy to blast radius and to whether two versions can coexist.",
      compare("Downtime vs mixed versions", ["Recreate / BG", "Clear version cut", "Cost or downtime"], ["Rolling / canary", "Coexistence window", "Need compatible APIs"], "If v1 and v2 cannot talk to the same schema, do not roll"),
    ),
    Q(
      "How do you kill secret sprawl at scale?",
      "One vault per environment, short-lived creds, no secrets in CI logs, detect (gitleaks) on push, rotate on a calendar and on incident. CSI refresh plus app support for SIGHUP or re-read. Break-glass credentials in a sealed envelope with dual control.",
      "Env vars leak via /proc and crash dumps. Sidecar injectors still need RBAC so not every SA can read every secret. Expert: prefer identity (IAM) over a password to the database when the engine supports it.",
      steps("Fewer, shorter, detected", [["Inventory", "Where secrets live"], ["Move", "Vault + IAM"], ["Detect", "Git and image scan"], ["Rotate", "Automate TTL"], ["Drill", "Revoke and still boot"]], "Sprawl is every extra copy — logs, tickets, and old pods count"),
    ),
    Q(
      "How do you keep observability cheap and useful in Kubernetes?",
      "Bounded cardinality (no user-id on every metric), tail sampling, log levels by default warn in prod, exemplars from RED metrics to traces. Resource metrics (USE) on nodes plus RED on Services. SLO burn alerts, not “pod restarted.”",
      "DaemonSet log shippers can starve nodes — cap CPU. Sidecar-per-pod meshes add RAM; know the tax. Multi-cluster: one trace backend, consistent labels (cluster, env, version).",
      hub("Signal that pays rent", "Observe", [["RED", "Service SLOs"], ["USE", "Node saturation"], ["Sample", "Traces on error/slow"], ["Bound", "Metric labels"], ["Cost", "Cap shippers"]], "High-cardinality labels are a bill that looks like a dashboard"),
    ),
    Q(
      "How does GitOps work across many clusters and promotions?",
      "App-of-apps or root app per cluster. Promote by merging a tag into staging then prod folders (or Kustomize overlays), never by applying from CI to prod. Drift detection pages. Progressive sync waves order CRDs before workloads.",
      "Multi-tenancy: AppProjects limit who can sync what. Secrets: external operator, not plaintext. Expert failure mode: two GitOps tools, or humans with cluster-admin plus GitOps, fighting. One writer to the API for that namespace.",
      timeline("Promote a digest", [["CI", "Build and sign"], ["Dev", "PR sets tag"], ["Stage", "Merge overlay"], ["Prod", "Second merge"], ["Sync", "Controller applies"]], "Promotion is a git merge of a digest — not a second docker build"),
    ),
  ],
};
