const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Database & SQL",
  slug: "database-sql",
  description: "Queries, joins, indexes, normalization, transactions, stored procedures",
  theme: {
    accent: "#0369a1",
    hubFill: "#0369a1",
    hubText: "#fff",
    centerFill: "#e0f2fe",
    centerStroke: "#0369a1",
    label: "SQL",
  },
  beginner: [
    Q(
      "What is a relational database?",
      "A relational database stores data in tables (relations) of rows and columns, with keys that link tables. You query it with SQL rather than walking files yourself.",
      "Interviews want tables + keys + SQL, not a vendor name. Spreadsheets are not a database: no real constraints, transactions, or concurrent access control. NoSQL is a different model — say when you would still pick relational (joins, integrity).",
      hub("Tables you can query", "DB", [["Table", "Rows of one kind"], ["Column", "A field + type"], ["Row", "One record"], ["Key", "How rows link"], ["SQL", "The language"]], "Relational means related tables — not a single sheet"),
    ),
    Q(
      "What is SQL?",
      "SQL is the language for defining and querying relational data: SELECT to read, INSERT/UPDATE/DELETE to change, and DDL (CREATE TABLE) to define shape.",
      "SQL is declarative: you say what you want, the engine picks a plan. Dialects differ (Postgres, SQL Server, MySQL) but the core SELECT-FROM-WHERE is shared. Interviews write SQL on a whiteboard more than they quote theory.",
      steps("Talk to the engine", [["FROM", "Which tables"], ["WHERE", "Which rows"], ["SELECT", "Which columns"], ["ORDER", "How to sort"]], "SQL describes the result — the optimizer chooses the path"),
    ),
    Q(
      "What does SELECT do?",
      "SELECT lists the columns (or expressions) you want in the result. FROM names the table. Without WHERE you get every row. * means all columns — fine for exploring, sloppy in production.",
      "SELECT is not a loop you wrote; the engine may use an index or a scan. DISTINCT removes duplicate result rows. Aliases (AS) rename columns for the output.",
      code("Pick columns and rows", "select.sql", ["SELECT name, age", "FROM employees", "WHERE age > 30"], [["SELECT", "Output columns"], ["FROM", "Source table"], ["WHERE", "Row filter"]], "Read as: from this table, keep these rows, return these columns"),
    ),
    Q(
      "How does WHERE work?",
      "WHERE filters rows before grouping. Each row is kept if the condition is true. Combine tests with AND / OR, and use parentheses. Comparisons on the column let the optimizer use an index.",
      "WHERE is not HAVING — HAVING filters groups after GROUP BY. Wrapping a column in a function (YEAR(date) = 2024) often kills index use. NULL never equals anything; use IS NULL.",
      steps("Keep or drop a row", [["Read", "A candidate row"], ["Test", "WHERE condition"], ["True", "Row can appear"], ["False", "Row is gone"]], "WHERE answers which rows — SELECT answers which columns"),
    ),
    Q(
      "What is a primary key?",
      "A primary key uniquely identifies each row. It cannot be NULL. The table has at most one primary key, which may be one column or several (composite).",
      "Surrogate keys (id identity/uuid) vs natural keys (email, ISBN) is a design choice. The PK is the default clustering key in SQL Server. Child tables point at it with foreign keys.",
      hub("One row, one identity", "PK", [["Unique", "No duplicates"], ["Not null", "Always present"], ["One per table", "The official identity"], ["Lookup", "Fast by key"], ["Target", "What FKs reference"]], "If you cannot point at a row, you do not have a key"),
    ),
    Q(
      "What is a foreign key, and how does it differ from a primary key?",
      "A foreign key is a column (or set) that must match an existing primary (or unique) key in another table — or be NULL if allowed. The PK identifies a row; the FK points at that row.",
      "FKs enforce referential integrity: you cannot orphan a child, or you define CASCADE/SET NULL. Interviews fail people who say FK means indexed — it should be indexed, but the constraint is about validity, not speed.",
      compare("Identify vs point", ["Primary key", "Unique in this table", "Not null", "One official identity", "What others reference"], ["Foreign key", "Values from another PK", "May be null", "Many rows can share it", "Protects relationships"], "PK is who you are — FK is who you belong to"),
    ),
    Q(
      "What is the difference between a table, a row, and a column?",
      "A table is the relation (employees). A column is an attribute with a type (salary INT). A row is one tuple — one employee. The cell is the value at that row and column.",
      "Result sets are also tables in SQL's head. Wide tables (too many columns) and entity-attribute-value dumps are design smells. Normalize repeating groups into rows, not extra columns.",
      layers("The relational grid", [["Table", "The entity set"], ["Column", "One attribute + type"], ["Row", "One instance"], ["Cell", "A single value"]], "Design tables around things — columns around facts about them"),
    ),
    Q(
      "What do INSERT, UPDATE, and DELETE do?",
      "INSERT adds rows. UPDATE changes columns on rows that match WHERE. DELETE removes matching rows. All three should almost always have a precise WHERE (except a true insert of new data).",
      "UPDATE/DELETE without WHERE hits the whole table — a production incident. MERGE/UPSERT is insert-or-update. Transactions wrap these so a failure does not leave a half-write.",
      timeline("Change the data", [["INSERT", "New rows"], ["UPDATE", "Existing rows"], ["DELETE", "Remove rows"], ["COMMIT", "Make it durable"]], "DML changes rows — DDL changes the table shape"),
    ),
    Q(
      "How is NULL different from 0 or an empty string?",
      "NULL means unknown or missing. It is not 0, not '', and not false. Comparisons with NULL yield UNKNOWN, so WHERE col = NULL matches nothing — use IS NULL / IS NOT NULL.",
      "Aggregates skip NULL (SUM of 1, NULL, 2 is 3). UNIQUE in some engines allows multiple NULLs. COALESCE(col, 0) fills a default. Interviews love this because it breaks naive WHERE logic.",
      compare("Missing vs a real value", ["NULL", "Unknown / absent", "IS NULL to test", "Kills = comparisons", "Not in most aggregates"], ["0 or ''", "A known value", "= 0 works", "Empty is still there", "Counts as a row value"], "NULL is not a value — it is the absence of one"),
    ),
    Q(
      "What is a JOIN at a beginner level?",
      "A JOIN combines rows from two tables using a match condition, usually PK = FK. INNER JOIN keeps only matches. You list columns from both sides in SELECT.",
      "Without a join condition you get a cartesian product (every pair) — usually a bug. Table aliases (e, d) keep column names clear. Start with INNER JOIN before LEFT JOIN.",
      steps("Combine two tables", [["Pick", "Left table and right table"], ["On", "How rows match"], ["Keep", "Rows that qualify"], ["Project", "Columns from both"]], "A join is a match rule — not a loop you wrote by hand"),
    ),
    Q(
      "How do you write a simple INNER JOIN?",
      "FROM employees e INNER JOIN departments d ON e.dept_id = d.id returns only employees who have a matching department. Columns can come from e and d.",
      "INNER JOIN and JOIN are the same in most dialects. If dept_id is NULL or missing, the employee disappears from an inner join — that is the LEFT JOIN follow-up.",
      code("Match employees to departments", "join.sql", ["SELECT e.name, d.name", "FROM employees e", "INNER JOIN departments d", "  ON e.dept_id = d.id"], [["ON", "The match rule"], ["INNER", "Drop non-matches"]], "Inner join means both sides must exist"),
    ),
    Q(
      "What is an index, in one sentence an interviewer wants?",
      "An index is a separate sorted (or hashed) structure that lets the engine find rows without scanning the whole table — like a book index. Lookups and joins get faster; writes get a bit slower because the index must update too.",
      "Primary keys are indexed. An index on the WHERE/JOIN column is the usual fix for a slow query. Too many indexes hurt INSERT/UPDATE. This is the beginner version; covering indexes come later.",
      compare("Scan vs seek", ["No index", "Read every row", "Fine for tiny tables", "O(n) to find one key", "Writes stay simple"], ["With index", "Jump near the row", "Needs extra storage", "Log-ish lookup typical", "Writes maintain it"], "An index is extra data for faster reads — not a second table you query by hand"),
    ),
    Q(
      "What do ORDER BY and LIMIT (or TOP) do?",
      "ORDER BY sorts the result. LIMIT/TOP/OFFSET-FETCH keeps only some rows after that sort. Without ORDER BY, LIMIT is not a stable page — the engine may return any rows.",
      "Sorting a huge result is expensive unless it matches an index. Pagination should use a key (keyset) for large offsets. Interviews: never assume a table has an order until you ORDER BY.",
      hub("Shape the result list", "Sort", [["ORDER BY", "Define the order"], ["ASC/DESC", "Direction"], ["TOP/LIMIT", "Cut the list"], ["OFFSET", "Skip for pages"], ["Index", "May avoid a sort"]], "No ORDER BY means no promised order"),
    ),
    Q(
      "What is GROUP BY used for?",
      "GROUP BY collapses rows that share the same key and lets you run aggregates: COUNT, SUM, AVG, MIN, MAX. Every selected column must be grouped or aggregated.",
      "WHERE filters rows before grouping; HAVING filters groups after. COUNT(*) counts rows; COUNT(col) skips NULL col. This is the door to reporting queries.",
      cycle("Rows into buckets", "Group", [["Filter", "WHERE first"], ["Bucket", "Same GROUP BY key"], ["Aggregate", "One number per bucket"], ["Having", "Keep some groups"]], "GROUP BY is one row per group — not one row per original row"),
    ),
    Q(
      "Why do we use constraints like UNIQUE and NOT NULL?",
      "Constraints are rules the database enforces so bad data cannot land. NOT NULL means the column must have a value. UNIQUE means no duplicate values (NULLs handled per engine).",
      "Check constraints and foreign keys are the same idea. Application validation is not enough under concurrency. Interviews: integrity belongs in the database if multiple apps write it.",
      steps("Reject bad rows", [["Declare", "NOT NULL, UNIQUE, FK"], ["Write", "INSERT/UPDATE tried"], ["Check", "Engine tests the rule"], ["Fail", "Statement errors"]], "A constraint is a guarantee — not a suggestion"),
    ),
  ],
  intermediate: [
    Q(
      "What are the main SQL JOIN types?",
      "INNER: only matches. LEFT (outer): all left rows, NULLs on the right if no match. RIGHT: the mirror. FULL outer: all rows from both, NULLs where a side is missing. CROSS: cartesian product.",
      "Draw two circles in an interview. Filtering a LEFT JOIN in WHERE on a right-side column turns it into an INNER JOIN — a classic bug. Prefer LEFT over RIGHT for readability.",
      hub("Which rows survive", "Join", [["INNER", "Matches only"], ["LEFT", "All left + matches"], ["RIGHT", "All right + matches"], ["FULL", "Everything, pad NULLs"], ["CROSS", "Every pair"]], "Name the join by which unmatched rows you still want"),
    ),
    Q(
      "When do you use LEFT JOIN instead of INNER JOIN?",
      "Use LEFT JOIN when you must keep every row from the left table even if the right side has no match — e.g. all customers, including those with no orders. Use INNER when a match is required.",
      "SELECT COUNT of a left-joined 1-to-many can duplicate left rows — count distinct or aggregate in a subquery. COALESCE right columns to show defaults. This is one of the most common SQL interview questions.",
      compare("Must match vs keep left", ["INNER JOIN", "Drop non-matches", "Employees with a dept", "Both sides exist", "Smaller result"], ["LEFT JOIN", "Keep all left rows", "Customers with 0 orders", "Right side may be NULL", "Watch row duplication"], "If the business cares about the zeros, it is a left join"),
    ),
    Q(
      "How does a B-tree index actually help a query?",
      "Most relational indexes are B-trees: sorted keys that point at rows (or at the clustered index key). A seek walks the tree in O(log n) pages instead of reading every row. Range predicates (BETWEEN, >) can scan a slice of the leaf level.",
      "Equality on the leading column of a composite index is the happy path. Functions on the column, leading wildcards (LIKE '%x'), and type mismatches often force a scan. Hash indexes (some engines) are equality-only.",
      layers("From root to row", [["Root", "Pick a branch"], ["Branch", "Narrow the range"], ["Leaf", "Keys in order"], ["Bookmark", "Find the heap/cluster row"]], "An index is a sorted map — not a magic skip button"),
    ),
    Q(
      "What are 1NF, 2NF, and 3NF?",
      "1NF: atomic cells, no repeating groups. 2NF: 1NF plus no partial dependency on part of a composite key. 3NF: 2NF plus no non-key column depending on another non-key column (no transitive dependency).",
      "The interview version: one fact, one place. 2NF only matters with composite keys. Boyce-Codd (BCNF) is a stricter 3NF. You denormalize later for read performance — after you can name the anomaly you just reintroduced.",
      layers("Normal forms", [["1NF", "Atomic values, repeating groups become rows"], ["2NF", "Non-keys depend on the whole key"], ["3NF", "Non-keys depend only on the key"], ["Goal", "Update a fact in one place"]], "If changing a department name needs ten row edits, you are not in 3NF"),
    ),
    Q(
      "When would you denormalize after reaching 3NF?",
      "When a read path is too expensive (many joins) and you accept duplicated data plus extra write work. Caches, summary tables, and star schemas are planned denormalization — not accidents.",
      "Say the anomaly: updates can drift. Use triggers, jobs, or the application to keep copies in sync. Interviews want you to normalize first, then denormalize with a reason — not skip 3NF because joins feel hard.",
      compare("One fact vs fast reads", ["3NF", "No redundant facts", "More joins", "Safer writes", "OLTP default"], ["Denormalized", "Copy columns / aggregates", "Fewer joins", "Write amplification", "OLAP / hot paths"], "Denormalize with a measured query — not a vibe"),
    ),
    Q(
      "What is a transaction?",
      "A transaction is a unit of work that commits (all changes become durable and visible per isolation) or rolls back (as if it never happened). BEGIN, statements, then COMMIT or ROLLBACK.",
      "Autocommit means each statement is its own transaction — easy to forget. Keep transactions short to reduce lock time. Nested transactions in SQL Server are not what people think (@@TRANCOUNT).",
      steps("All or nothing", [["Begin", "Start the unit"], ["Write", "Change rows"], ["Fail?", "ROLLBACK"], ["OK", "COMMIT"]], "A transaction is a promise about a set of writes — not a single SQL file"),
    ),
    Q(
      "What does ACID mean?",
      "Atomicity: all or nothing. Consistency: constraints hold after commit. Isolation: concurrent transactions do not see each other's dirty work (to the isolation level). Durability: after commit, a crash does not undo it (WAL/log).",
      "Consistency here is integrity constraints, not CAP consistency. Isolation is a spectrum (read committed vs serializable). Durability depends on flush of the log — delayed durability exists and is a tradeoff.",
      hub("Four guarantees", "ACID", [["A", "All or nothing"], ["C", "Constraints hold"], ["I", "Controlled visibility"], ["D", "Commit survives crash"], ["Log", "How D is implemented"]], "Name all four — then isolation as the tunable one"),
    ),
    Q(
      "What is a stored procedure, and when do you use one?",
      "A stored procedure is named SQL (plus control flow) stored in the database, called with parameters. Use it for a stable API close to the data, permissions, and a cached plan — not for hiding all business logic.",
      "Pros: fewer round trips, grant EXECUTE without table rights. Cons: versioning, testing, and vendor lock-in. ORMs vs procedures is a team choice; interviews want both sides.",
      compare("In the database vs in the app", ["Stored proc", "One round trip", "Plan reuse", "DB permissions", "Harder to test in git"], ["App SQL", "Easier CI", "Portable-ish", "More chatter", "Logic lives with code"], "A proc is an API boundary — not automatically faster"),
    ),
    Q(
      "How do UNIQUE constraints differ from a primary key?",
      "A table can have many UNIQUE constraints; only one PRIMARY KEY. PK columns are NOT NULL. UNIQUE may allow NULL depending on the engine (one NULL vs many).",
      "Alternate keys (email UNIQUE) are the usual UNIQUE use. Foreign keys can reference a UNIQUE column, not only the PK. Clustered vs nonclustered is a storage choice on top of uniqueness.",
      compare("The identity vs extra uniqueness", ["PRIMARY KEY", "One per table", "NOT NULL", "Default cluster in SQL Server", "The main lookup"], ["UNIQUE", "Many allowed", "NULL rules vary", "Alternate keys", "Also index-backed"], "PK is the official row id — UNIQUE is any other no-duplicates rule"),
    ),
    Q(
      "What is the difference between a subquery and a JOIN for the same result?",
      "A JOIN combines rows set-wise. A subquery (IN, EXISTS, scalar) nests a query. EXISTS often beats IN for large nullable lists. The optimizer may rewrite one into the other — you still pick the readable form and check the plan.",
      "Correlated subqueries run per outer row if not decorrelated — a performance trap. Aggregates from another table often read clearer as JOIN plus GROUP BY or a derived table.",
      code("EXISTS vs join", "exists.sql", ["SELECT *", "FROM orders o", "WHERE EXISTS (", "  SELECT 1 FROM payments p", "  WHERE p.order_id = o.id", ")"], [["EXISTS", "Stop at first match"], ["Join", "Can duplicate orders"]], "If you only need yes/no, EXISTS states that intent"),
    ),
    Q(
      "What are isolation levels at an intermediate level?",
      "Isolation levels trade consistency for concurrency. Read uncommitted can see dirty data. Read committed (common default) sees only committed rows. Repeatable read keeps your read rows stable. Serializable makes the outcome match some serial order.",
      "You do not need every anomaly name yet, but you should know defaults: Postgres read committed, SQL Server read committed, MySQL InnoDB repeatable read. Snapshot / MVCC is how some engines avoid many lock waits.",
      timeline("Stricter means more waiting (or more versions)", [["Read uncommitted", "Dirty reads possible"], ["Read committed", "No dirty reads"], ["Repeatable read", "Same row, same value"], ["Serializable", "As if one at a time"]], "Pick a level on purpose — the default is a product choice"),
    ),
    Q(
      "How do you create a useful index without over-indexing?",
      "Index columns used for high-selectivity equality and joins, leading-edge ranges, and foreign keys. Skip indexes on low-cardinality flags unless queries always filter them. Measure with the actual query, not guesses.",
      "Composite order is leftmost prefix. INCLUDE (covering) comes at expert level. Write-heavy tables pay for every extra index. Filtered indexes and partial indexes exist in some engines.",
      steps("Add an index with intent", [["Query", "Capture the slow SQL"], ["Filter", "Equality columns first"], ["Create", "Matching composite"], ["Verify", "Seek not scan"], ["Watch", "Write cost"]], "An unused index is a tax on every INSERT"),
    ),
    Q(
      "What is a view?",
      "A view is a stored SELECT presented as a table. It hides joins and column lists. Simple views may be updatable; complex ones are read-only. Indexed/materialized views store the result for speed at write cost.",
      "Views are not automatically faster — they still run the query unless materialized. Security: grant SELECT on the view without granting base tables. Recursion and nesting make plans harder to read.",
      hub("A named query", "View", [["SELECT", "The definition"], ["Hide", "Joins and columns"], ["Grant", "Permission surface"], ["Materialize", "Stored result"], ["Plan", "Still optimized"]], "A view is a contract — not a cache unless you materialize it"),
    ),
    Q(
      "How do aggregate queries go wrong in interviews?",
      "Selecting a non-grouped column (only_full_group_by), mixing WHERE and HAVING, and joining 1-to-many before COUNT so you double-count. COUNT(*) vs COUNT(col) vs COUNT(DISTINCT) are different questions.",
      "Fix double-count by aggregating in a subquery then joining. SUM of a left-joined NULL is NULL unless COALESCE. Window functions (ROW_NUMBER, SUM OVER) are the next step after GROUP BY.",
      cycle("Aggregate without lying", "Agg", [["Grain", "What is one row?"], ["Join", "Does it multiply?"], ["Group", "Collapse to grain"], ["Check", "COUNT vs SUM"]], "If COUNT is bigger than the table, your join changed the grain"),
    ),
    Q(
      "What is referential action on a foreign key (CASCADE, SET NULL, RESTRICT)?",
      "ON DELETE/UPDATE CASCADE copies the change to children. SET NULL clears the FK. RESTRICT/NO ACTION rejects the parent change while children exist. Pick the one that matches the domain (orders vs optional assignment).",
      "CASCADE can delete a huge subtree — dangerous in production without a review. Soft deletes in the app plus RESTRICT in the DB is a common mix. Always index the FK columns or parent deletes scan the child table.",
      compare("Propagate vs block", ["CASCADE", "Children follow", "Easy cleanup", "Can wipe trees", "Use when owned"], ["RESTRICT", "Parent stays if kids exist", "Safe default", "App must delete kids first", "Use when referenced"], "The FK action is a product decision — not a default to memorize"),
    ),
  ],
  expert: [
    Q(
      "How do you read EXPLAIN / a query plan?",
      "Read from the operator that actually accesses data (scan vs seek) up to the root. Look at estimated vs actual rows, join type (nested loop, hash, merge), and the expensive sort or spill. The goal is: why this plan, and which index or rewrite would change it.",
      "A Seq Scan is not always bad on a small table. Parameter sniffing (SQL Server) and stale stats cause surprises. EXPLAIN ANALYZE runs the query — do not use it on an unscoped UPDATE in prod. Interviewers want operators + cardinality, not a screenshot dump.",
      steps("Interrogate the plan", [["Shape", "Scan, seek, join, sort"], ["Rows", "Estimate vs actual"], ["Join", "Nested loop / hash / merge"], ["Fix", "Index, stats, rewrite"]], "The plan is the engine's alibi — argue with the operators"),
    ),
    Q(
      "What is the N+1 query problem?",
      "You run one query for a list of parents, then one query per parent for children — N+1 round trips. Fix with a JOIN, an IN/ANY list, or a batched loader (DataLoader). ORMs cause this when lazy relations are touched in a loop.",
      "It shows up as hundreds of identical SELECTs in logs. SELECT * in a loop is the same smell. Prefetch/include in ORMs is the framework name for the join. This is an expert SQL-plus-app question.",
      code("The loop that explodes", "nplus1.js", ["const users = db.all('SELECT * FROM users')", "for (const u of users) {", "  u.orders = db.all(", "    'SELECT * FROM orders WHERE user_id=?',", "    u.id)", "}"], [["1", "Load users"], ["N", "One query each"]], "One list query plus a loop of child queries is N+1"),
    ),
    Q(
      "What is a covering index?",
      "A covering index includes every column the query needs, so the engine never visits the base table (index-only scan). Key columns handle seek/filter/order; INCLUDE (SQL Server) or extra leaf columns add payload without changing sort order.",
      "SELECT * rarely covers. Wide covering indexes slow writes and bloat storage. Postgres index-only scans still need a visible map / vacuum. Quote the query, then the index that matches it.",
      compare("Key lookup vs index-only", ["Non-covering", "Seek then lookup", "Bookmark / heap fetch", "Fine if few rows", "Extra IO per row"], ["Covering", "All columns in the index", "No table visit", "INCLUDE for extras", "Write and size cost"], "Covering means the index answered the SELECT by itself"),
    ),
    Q(
      "What is a deadlock, and how do you handle one?",
      "A deadlock is two (or more) transactions each holding a lock the other needs — a cycle. The engine picks a victim and rolls it back. The app should retry the aborted transaction. Prevention: lock the same objects in the same order, keep transactions short, index so you lock fewer rows.",
      "SQL Server error 1205, Postgres deadlock detected. READ vs write lock conversion can deadlock too. Snapshot isolation reduces some lock deadlocks but not all write-write conflicts. Never hold a transaction open while waiting on a user.",
      cycle("Lock cycle", "Deadlock", [["T1", "Holds A, wants B"], ["T2", "Holds B, wants A"], ["Victim", "Engine aborts one"], ["Retry", "App runs it again"]], "Deadlock is a cycle of waits — retry is part of the contract"),
    ),
    Q(
      "How does MVCC work?",
      "Multi-version concurrency control keeps older row versions so readers do not block writers (and often vice versa). Each transaction sees a snapshot. Writers create a new version; garbage collection / vacuum / ghost cleanup removes versions no snapshot needs.",
      "Postgres MVCC is the textbook. SQL Server row versioning (RCSI, snapshot) uses tempdb version store. Readers can still conflict with DDL. Long-running snapshots delay cleanup and bloat. Expert answer: snapshot vs locks, then bloat.",
      layers("Readers see a snapshot", [["Start", "Take a snapshot id"], ["Read", "Visible versions only"], ["Write", "New version, old stays"], ["Commit", "New version published"], ["GC", "Drop unseen versions"]], "MVCC trades version storage for fewer read/write lock waits"),
    ),
    Q(
      "What anomalies do isolation levels actually prevent?",
      "Dirty read: see uncommitted data. Non-repeatable read: a row you read changes on a second read. Phantom: a new row appears in a range you already queried. Serializable (or true serial snapshot) prevents all three; weaker levels allow some.",
      "Postgres repeatable read is snapshot-based and prevents phantoms that classic lock-based RR might not in the SQL standard story — know your engine. Write skew is the snapshot isolation expert follow-up (two transactions each valid, together invalid).",
      hub("The named bugs", "Anomaly", [["Dirty", "Uncommitted data"], ["Non-repeatable", "Row changed under you"], ["Phantom", "New row in a range"], ["Write skew", "Snapshot SI issue"], ["Fix", "Stricter isolation or locks"]], "Name the anomaly, then which level still allows it"),
    ),
    Q(
      "Clustered vs nonclustered indexes — what is the storage difference?",
      "A clustered index is the table: rows stored in key order (one clustered index per table typical). A nonclustered index is a separate B-tree whose leaf points at the cluster key (or heap RID). Lookups from nonclustered to clustered are key lookups.",
      "SQL Server: PK is clustered by default. Heap plus nonclustered is valid. MySQL InnoDB tables are clustered on the PK. Postgres has no clustered index in that sense (CLUSTER is a one-time rewrite). Do not say clustered means unique — it usually is, but the point is row order.",
      compare("The table itself vs a copy of keys", ["Clustered", "Rows in key order", "One per table typical", "Range scans on the key", "PK often this"], ["Nonclustered", "Extra B-tree", "Many allowed", "Points at cluster/heap", "Covering if INCLUDE"], "Clustered is how the table is laid out — not a faster kind of uniqueness"),
    ),
    Q(
      "What is index selectivity (cardinality), and why does the optimizer care?",
      "Selectivity is how well a predicate cuts the table: unique email is high; boolean is_active is low. The optimizer uses stats (histograms) to estimate rows. A low-selectivity index may be ignored in favor of a scan.",
      "Composite indexes put the most selective equality column first unless a range needs to lead. Skew (one value is 99%) fools average density. UPDATE STATISTICS / ANALYZE is how you feed the optimizer. Expert interviews: estimates vs actuals in the plan.",
      hub("Will this index be used?", "Stats", [["Cardinality", "How many distinct"], ["Histogram", "Value distribution"], ["Skew", "Hot values"], ["Estimate", "Rows the planner thinks"], ["Scan", "When the index loses"]], "An index on a boolean is often a scan with extra write cost"),
    ),
    Q(
      "How do you choose snapshot isolation vs serializable?",
      "Snapshot (and RCSI) gives each transaction a consistent view without many shared locks — great for read-heavy OLTP. Serializable (Postgres SSI, or stricter locking) prevents write skew and other anomalies snapshot still allows.",
      "Postgres SERIALIZABLE can abort with a serialization failure — the app must retry. SQL Server SERIALIZABLE uses range locks and can block more. If the invariant is two-row (account transfer style), snapshot may be wrong without extra constraints.",
      compare("Versions vs a serial story", ["Snapshot / RCSI", "Readers do not block writers", "Write skew possible", "Retry less often", "Default-ish for scale"], ["Serializable", "Looks like one-at-a-time", "Fewer anomalies", "More aborts or locks", "When invariants span rows"], "If two transactions can each look valid and together break a rule, you need stronger than snapshot"),
    ),
    Q(
      "What does the write-ahead log do for durability?",
      "Before a commit returns, the engine writes log records describing the change. On crash, redo brings data files up to the last committed LSN; undo drops in-flight work. Checkpoints flush dirty pages so recovery stays bounded.",
      "This is ACID D. Group commit batches flushes. Synchronous replica wait is another durability knob. Turning off fsync is faster and not durable — not an interview joke if you name the risk.",
      timeline("Commit is a log flush", [["Change", "In memory + log buffer"], ["WAL", "Append log records"], ["Fsync", "Durable on disk"], ["Ack", "COMMIT returns"], ["Replay", "Crash recovery"]], "If it is not in the log, it did not commit"),
    ),
    Q(
      "How would you approach a slow query besides adding an index?",
      "Confirm the plan and actual rows, update statistics, rewrite (sargable predicates, EXISTS vs JOIN grain), reduce SELECT list, paginate without huge OFFSET, and check locks/waits. Sometimes the model is wrong (N+1, missing summary table).",
      "Parameter sniffing: option recompile or optimize for unknown. Implicit conversions block indexes. Parallelism and spills to tempdb/disk are plan smells. Index is step one — not the only step.",
      steps("After the obvious index", [["Plan", "Actual vs estimate"], ["Stats", "Fresh histograms"], ["Rewrite", "Sargable, right grain"], ["Runtime", "Locks, IO, spills"]], "A seek on the wrong estimate is still a bad plan"),
    ),
    Q(
      "How do covering indexes and included columns interact with writes?",
      "Every extra leaf column is updated on INSERT/UPDATE/DELETE of those columns. INCLUDE avoids changing the sort key (so you do not split uniqueness) but still widens the leaf. Too many covering indexes duplicate the table.",
      "Hot columns that change often are poor INCLUDE candidates. A narrow PK clustered index keeps nonclustered leaves small (SQL Server). This is the expert follow-up to covering indexes: they are not free.",
      layers("Pay on the write path", [["Key cols", "Seek and order"], ["INCLUDE", "Payload for covering"], ["Update", "Maintain every leaf"], ["Split", "Page splits if keys move"], ["Budget", "Few wide indexes"]], "Covering is a read win you fund with write IO"),
    ),
    Q(
      "What is a stored procedure plan cache issue you should mention?",
      "The first parameter set can sniff a plan that is terrible for later values (skew). SQL Server: parameter sniffing, OPTIMIZE FOR, RECOMPILE, or local variables as a blunt fix. Procedures also hide per-statement stats unless you look at the plan cache.",
      "Dynamic SQL inside procs can be injection if you concatenate — use sp_executesql with parameters. SET NOCOUNT ON is a trivia bonus. Expert: procs are not a substitute for indexing and sargable SQL.",
      hub("Cached plans are sticky", "Plan", [["Sniff", "First params win"], ["Skew", "One plan, two distributions"], ["Recompile", "Fresh plan, CPU cost"], ["Locals", "Guessed density"], ["Grant", "EXECUTE without tables"]], "A cached plan is a bet that tomorrow looks like sniff day"),
    ),
    Q(
      "When do you partition a table, and what does it not replace?",
      "Partitioning splits a large table by a key (usually date) so maintenance (drop old partition, compress) and some scans touch less data. It is not a substitute for a good index, and a bad partition key makes every query hit all partitions.",
      "Postgres declarative partitions, SQL Server partition functions/schemes. Unique indexes must include the partition key. Cross-partition uniqueness is hard. Interviews: partition for lifecycle and pruning — not for a 2 GB table.",
      compare("Split storage vs index", ["Partition", "Drop/archive a slice", "Prune by key", "Ops win on huge tables", "Wrong key = all scans"], ["Index", "Find rows fast", "Works at any size", "Does not drop old data", "First tool"], "Partition when the table is huge and the key is in the WHERE"),
    ),
    Q(
      "How do you explain locking vs MVCC in one interview answer?",
      "Locking engines serialize access to the same row with shared/exclusive locks — readers can block writers. MVCC lets readers use old versions so they do not take those locks; writers still conflict with writers. Hybrids (SQL Server RCSI) add versioning on top of locks.",
      "Deadlocks are lock-graph problems. Serialization failures are MVCC/SSI problems. Pick the vocabulary of the product you claim. The expert close: isolation level chooses how much of each you pay.",
      hub("Two ways to isolate", "Concur", [["Lock", "Wait for the row"], ["Version", "Read an old copy"], ["Writer", "Still conflicts"], ["Deadlock", "Lock cycle"], ["SSI abort", "Retry instead"]], "Locks wait — versions copy — isolation picks the mix"),
    ),
  ],
};
