const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Data Structures & Algorithms",
  slug: "data-structures-algorithms",
  description: "Arrays, linked lists, stacks, queues, trees, graphs, sorting, searching",
  theme: {
    accent: "#0d9488",
    hubFill: "#0d9488",
    hubText: "#ffffff",
    centerFill: "#ccfbf1",
    centerStroke: "#0d9488",
    label: "DSA",
  },
  beginner: [
    Q(
      "What is an array?",
      "An array is a contiguous block of slots you address by index, usually from 0. Lookup by index is O(1); shifting elements to insert or delete in the middle is O(n).",
      "Interviews want: contiguous memory, random access, and the cost of insert/delete. Dynamic arrays (vectors, Python lists) grow by allocating a bigger block and copying — append is amortized O(1), not worst-case O(1).",
      steps("Use an array", [["Allocate", "n slots in a row"], ["Index", "arr[i] in O(1)"], ["Scan", "Walk 0 to n-1"], ["Shift", "Insert/delete moves neighbors"]], "Index is cheap — moving items is not"),
    ),
    Q(
      "What is a linked list?",
      "A linked list is nodes on the heap, each holding a value and a pointer to the next (and maybe previous). You walk from the head; there is no cheap random index.",
      "Singly linked: next only. Doubly linked: next and prev, so reverse walks are easy. Insert or delete at a known node is O(1) pointer changes; finding that node is still O(n).",
      hub("Nodes and pointers", "List", [["Head", "First node"], ["Node", "Value + next"], ["Tail", "Last node"], ["Null", "End of the chain"], ["Walk", "Follow next"]], "A list is a chain — not a block of indexes"),
    ),
    Q(
      "When would you pick an array over a linked list?",
      "Pick an array when you need index access, scans, or cache-friendly memory. Pick a linked list when you insert or delete often at a known position and rarely jump by index.",
      "Real CPUs love arrays because sequential memory prefetches. Linked lists chase pointers and miss cache. Python list and Java ArrayList are arrays; Java LinkedList is nodes — do not mix the words.",
      compare("Block vs chain", ["Array", "Index in O(1)", "Contiguous RAM", "Insert middle is O(n)", "Great for scans"], ["Linked list", "No cheap index", "Nodes on the heap", "Insert at cursor is O(1)", "Pointer chasing"], "Name the access pattern before you pick the structure"),
    ),
    Q(
      "What is a stack?",
      "A stack is LIFO: last in, first out. You push on top and pop from the top. Peek/top reads without removing.",
      "Call stacks, undo, matching brackets, and DFS with an explicit stack are the usual interview examples. Overflow means you pushed past capacity; underflow means you popped an empty stack.",
      steps("Last in, first out", [["Push", "Put on top"], ["Top", "Only the top is visible"], ["Pop", "Remove the top"], ["Empty", "Nothing to pop"]], "A stack is a plate pile — you only touch the top"),
    ),
    Q(
      "What is a queue?",
      "A queue is FIFO: first in, first out. Enqueue at the back, dequeue at the front.",
      "BFS, printers, request handling, and message buffers are queues. A deque allows both ends. A circular buffer implements a bounded queue on an array without shifting.",
      cycle("First in, first out", "Queue", [["Arrive", "Enqueue at back"], ["Wait", "Order is preserved"], ["Serve", "Dequeue at front"], ["Repeat", "Next in line"]], "A queue is a line — the first arrival is served first"),
    ),
    Q(
      "What is the difference between a stack and a queue?",
      "A stack removes the most recent item (LIFO). A queue removes the oldest item (FIFO). Same insert/remove operations, opposite order.",
      "DFS (recursive or explicit stack) vs BFS (queue) is the algorithm-level version of this question. Deques and priority queues are different tools — do not call a heap a queue without saying priority.",
      compare("Newest vs oldest", ["Stack LIFO", "Push / pop top", "Undo, call frames", "DFS flavor", "See only the top"], ["Queue FIFO", "Enq back / deq front", "BFS, workers", "Fair order", "See the front"], "Order of removal is the whole difference"),
    ),
    Q(
      "What is a tree?",
      "A tree is a connected acyclic graph with a root. Each node has children; there is exactly one path from the root to any node.",
      "Binary tree: at most two children. BST: left < node < right (or a consistent order). Height matters for cost. A tree with n nodes has n-1 edges. Cycles would make it a graph, not a tree.",
      layers("Root down to leaves", [["Root", "No parent"], ["Internal", "Has children"], ["Leaf", "No children"], ["Height", "Longest root-to-leaf path"]], "One path from the root — that is what makes it a tree"),
    ),
    Q(
      "What is a graph?",
      "A graph is vertices (nodes) plus edges (links). Edges may be directed or undirected, weighted or unweighted. Unlike a tree, graphs may have cycles and more than one path.",
      "Social networks, maps, dependencies, and state machines are graphs. Representation is adjacency list (usual) or adjacency matrix (dense). Interviews always ask: directed? weighted? connected?",
      hub("Vertices and edges", "Graph", [["Vertex", "A node"], ["Edge", "A link"], ["Directed", "One-way"], ["Weighted", "Cost on the edge"], ["Cycle", "A loop of edges"]], "If there can be two paths, think graph — not tree"),
    ),
    Q(
      "What is a hash table?",
      "A hash table maps keys to values using a hash function that turns the key into a bucket index. Average insert, lookup, and delete are O(1); worst case can degrade to O(n).",
      "Collisions (two keys, same bucket) are handled by chaining or open addressing. Load factor too high means slow lookups. Hash maps do not keep sorted order unless you use a tree map.",
      steps("Key to bucket", [["Hash", "key -> integer"], ["Mod", "Pick a bucket"], ["Place", "Store the pair"], ["Lookup", "Hash again and search the bucket"]], "Average O(1) assumes a good hash and a reasonable load"),
    ),
    Q(
      "What is Big-O in a DSA interview?",
      "Big-O is an upper bound on how time or extra memory grows as n grows, ignoring constants. Say O(1), O(log n), O(n), O(n log n), O(n^2) and why — usually by counting loops and recursion depth.",
      "Interviewers want the dominant term and the input you are measuring (n = array length, v+e for graphs). Best / average / worst case are different sentences. Do not say O(n/2) — that is still O(n).",
      hub("Growth, not milliseconds", "Big-O", [["O(1)", "Index, hash typical"], ["O(log n)", "Binary search, balanced tree"], ["O(n)", "Single pass"], ["O(n log n)", "Good comparison sorts"], ["O(n^2)", "Nested n by n"]], "Count the work as n grows — skip the constants"),
    ),
    Q(
      "What is the difference between linear search and binary search?",
      "Linear search checks items one by one: O(n), works on any list. Binary search needs a sorted array (or a BST): compare the middle, drop half, O(log n).",
      "Binary search fails if the data is unsorted. Off-by-one on low/high is the classic bug. On a linked list, binary search is a poor fit because you cannot jump to the middle in O(1).",
      compare("Scan vs cut in half", ["Linear", "Any order", "O(n) time", "O(1) extra space", "Simple and robust"], ["Binary", "Must be sorted", "O(log n) time", "Array or tree", "Easy off-by-one"], "Sorted plus random access is what makes binary search pay off"),
    ),
    Q(
      "What does sorting actually do, and why do interviews care?",
      "Sorting puts items into order so later work can be binary search, two pointers, or greedy. Comparison sorts need at least O(n log n) in the worst case; counting/radix can be faster with constraints.",
      "Know one O(n log n) sort (merge or heap) and that quicksort is average O(n log n) but worst O(n^2) without care. Stability means equal keys keep their original order — needed for some multi-key sorts.",
      timeline("From chaos to order", [["Unsorted", "No position meaning"], ["Compare", "Or count keys"], ["Partition", "Smaller / bigger"], ["Done", "Binary search is legal"]], "Sorting is often setup — not the whole problem"),
    ),
    Q(
      "How do recursion and iteration differ for DSA problems?",
      "Recursion solves a problem by calling itself on a smaller piece plus a base case. Iteration uses a loop and your own stack/queue if needed. Same power; different memory and readability.",
      "Trees and divide-and-conquer read naturally as recursion. Linear scans should usually be loops. Recursion uses the call stack — depth n can overflow. Tail recursion is not reliable in most interview languages.",
      compare("Self-call vs loop", ["Recursion", "Base + smaller call", "Matches trees", "Frame per call", "Watch the stack"], ["Iteration", "Loop + state", "Great for arrays", "One frame", "You own the stack/queue"], "If the data is a tree, recursion (or an explicit stack) matches the shape"),
    ),
    Q(
      "What is a node in a linked structure?",
      "A node is a small record: a value plus pointers to other nodes (next, prev, left, right, children). The structure is the pattern of those pointers.",
      "Drawing nodes in interviews is expected. Null pointers end the structure. A cycle means some pointer points back — lists and graphs can have them; trees must not.",
      code("A list node", "node.js", ["function Node(val) {", "  this.val = val", "  this.next = null", "}", "a.next = b"], [["val", "The payload"], ["next", "Pointer to another node"]], "The value is data — the pointer is the structure"),
    ),
    Q(
      "What is the difference between time complexity and space complexity?",
      "Time complexity is how the number of steps grows with n. Space complexity is extra memory besides the input: recursion frames, copies, hash sets, and so on.",
      "In-place usually means O(1) extra (maybe a few variables). Recursion costs stack space. Interviews often ask you to trade extra O(n) space for faster lookups (hash set for two-sum).",
      layers("Two axes to quote", [["Time", "Steps as n grows"], ["Aux space", "What you allocate"], ["Input", "Usually not counted"], ["Stack", "Recursion counts"]], "Always say both — O(n) time and O(1) extra is a full answer"),
    ),
  ],
  intermediate: [
    Q(
      "How does the two-pointer technique work?",
      "Two pointers walk an array (or a string) from ends or at different speeds so you avoid nested loops. Common patterns: opposite ends for pair sums on a sorted array, and slow/fast for cycles or the middle of a list.",
      "You usually need sorted data or a linked-list structure. If you sort first, add that cost. Interviews want you to say why it is O(n) after sort, not O(n^2).",
      steps("Two indexes, one pass", [["Place", "i and j on the array"], ["Test", "Compare a[i], a[j]"], ["Move", "Advance the one that cannot work"], ["Stop", "They meet or cross"]], "Each pointer only moves forward — that is why it is linear"),
    ),
    Q(
      "What is a sliding window?",
      "A sliding window maintains a contiguous subarray (or substring) while you expand the right edge and shrink the left when a constraint breaks. Typical cost is O(n) instead of O(n^2) subarray checks.",
      "Fixed window: size k. Variable window: longest/shortest with a property (unique chars, sum <= k). A hash map or counter inside the window is the usual helper. Do not shrink more than you expand.",
      hub("A moving subarray", "Window", [["Right", "Include a[r]"], ["State", "Sum, counts, set"], ["Left", "Drop a[l] if invalid"], ["Best", "Track max/min length"], ["O(n)", "Each index enters once"]], "If the answer is a contiguous range, think window"),
    ),
    Q(
      "How does BFS work?",
      "Breadth-first search uses a queue: visit a node, enqueue its unvisited neighbors, mark visited. You explore level by level, so the first time you reach a node in an unweighted graph is a shortest path in hops.",
      "Visited set is mandatory or you loop forever on cycles. BFS on a tree is level order. Grid problems (shortest path in a maze) are BFS on an implicit graph. Space can be O(width of the frontier).",
      steps("Level by level", [["Start", "Enqueue the source"], ["Dequeue", "Take the front"], ["Neighbors", "Enqueue unseen ones"], ["Mark", "Visited so you do not repeat"]], "Queue plus visited is the whole pattern"),
    ),
    Q(
      "How does DFS differ from BFS?",
      "DFS goes deep first (recursion or an explicit stack). BFS goes wide first (queue). DFS is natural for path existence, topological ideas, and tree recursion; BFS is the default for unweighted shortest path.",
      "Both are O(v+e) with an adjacency list if you mark visited. Recursive DFS can blow the stack on a long chain — use iterative DFS or BFS then. Do not claim DFS finds shortest paths in unweighted graphs.",
      compare("Deep vs wide", ["DFS", "Stack / recursion", "Path / components", "Pre/post order", "Not shortest hops"], ["BFS", "Queue", "Levels, shortest hops", "More memory on bushy graphs", "Unweighted shortest"], "Pick BFS for distance in hops — DFS for structure"),
    ),
    Q(
      "How do you implement binary search without off-by-one bugs?",
      "Keep a half-open or closed invariant and stick to it. A common closed form: while (lo <= hi), mid = lo + (hi-lo)//2, then move lo or hi so the answer stays in range.",
      "lo + (hi-lo)//2 avoids overflow in fixed-width ints. Decide whether you want any match, leftmost, or rightmost — those change the hi/lo updates. Test empty, one element, and missing key.",
      code("Closed interval", "bsearch.js", ["while (lo <= hi) {", "  const m = lo + ((hi-lo)>>1)", "  if (a[m] === t) return m", "  if (a[m] < t) lo = m+1", "  else hi = m-1", "}"], [["Invariant", "answer in [lo, hi]"], ["mid", "Avoid lo+hi overflow"]], "The loop condition must match how you shrink the range"),
    ),
    Q(
      "How do hash collisions work, and why do they matter?",
      "A collision is two keys hashing to the same bucket. Chaining stores a list per bucket. Open addressing probes other slots (linear, quadratic, double hash). Bad hashes or high load make operations O(n).",
      "Interviewers may ask load factor, rehashing, and that Java 8+ treeifies long chains. Never use a mutable object as a key if its hash can change. Security: hash flooding is a real attack on naive maps.",
      hub("Same bucket, two keys", "Collide", [["Chain", "List in the bucket"], ["Probe", "Try another slot"], ["Load", "n / capacity"], ["Rehash", "Grow and copy"], ["Worst", "All keys one bucket"]], "O(1) is an average story — collisions are the fine print"),
    ),
    Q(
      "What is a heap (priority queue)?",
      "A heap is a complete binary tree stored in an array where each parent is ordered vs its children (min-heap: parent <= children). Insert and pop-root are O(log n); peek is O(1).",
      "Heapsort, Dijkstra, and top-k are the usual uses. A heap is not sorted overall — only the root is extreme. Building a heap from n items is O(n), not O(n log n), if you heapify bottom-up.",
      layers("Array as a tree", [["Index 0", "Root"], ["Parent i", "Children 2i+1, 2i+2"], ["Sift up", "After insert"], ["Sift down", "After pop"]], "Complete tree in an array — that is why heaps are simple"),
    ),
    Q(
      "What makes a binary search tree useful?",
      "In a BST, every left descendant is < node and every right descendant is > node (or a consistent total order). Balanced, search/insert/delete are O(log n); a skewed tree is O(n) like a list.",
      "Inorder traversal of a BST yields sorted order. Interviews distinguish BST from a plain binary tree. Self-balancing trees (AVL, red-black) keep the height logarithmic.",
      hub("Order in the shape", "BST", [["Left", "All smaller"], ["Right", "All larger"], ["Search", "Drop a side"], ["Inorder", "Sorted sequence"], ["Skew", "Becomes a list"]], "The invariant is the point — without it, binary search on a tree is a lie"),
    ),
    Q(
      "How do merge sort and quicksort compare?",
      "Merge sort always O(n log n), stable, needs O(n) extra space (typical). Quicksort is in-place average O(n log n), not stable, worst O(n^2) on bad pivots unless you randomize or use median-of-three / introsort.",
      "Linked lists merge well. Arrays often use tuned quicksort/introsort or timsort (Python, Java objects). Interviews want stability, extra memory, and worst-case — not just the names.",
      compare("Guaranteed vs average", ["Merge sort", "Always n log n", "Stable", "O(n) extra", "Good on lists"], ["Quicksort", "Avg n log n", "Usually in-place", "Worst n^2", "Cache-friendly"], "Quote worst case for quicksort or they will follow up"),
    ),
    Q(
      "When should you convert recursion to iteration?",
      "Convert when depth can be large (linked list of length n, deep left spine), when the language has no TCO, or when a profiler shows stack frames as the cost. Keep recursion when the call tree matches the data (trees, DAG DFS).",
      "The mechanical move is an explicit stack. Tail-recursive loops become a while. Interviewers like seeing you know the stack is memory — recursion is not free.",
      cycle("Same algorithm, new control", "Convert", [["Base", "Loop exit"], ["Frame", "Push state"], ["Body", "Do the work"], ["Next", "Pop or advance"]], "If n can be a million, do not recurse down the list"),
    ),
    Q(
      "Adjacency list vs adjacency matrix — which graph representation?",
      "Adjacency list: for each vertex, a list of neighbors. Space O(v+e), iterate neighbors in degree time. Matrix: v by v bits/weights. Space O(v^2), edge check O(1), iterate neighbors O(v).",
      "Sparse graphs (most interviews) use lists. Dense graphs or all-pairs Floyd-Warshall use matrices. Weighted directed graphs store (neighbor, weight) pairs in the list.",
      compare("Sparse vs dense", ["Adj list", "O(v+e) space", "Neighbors are cheap", "Edge test can be O(degree)", "Default choice"], ["Adj matrix", "O(v^2) space", "Edge test O(1)", "Neighbors cost O(v)", "Dense / all-pairs"], "v and e decide — not a matter of taste"),
    ),
    Q(
      "What are preorder, inorder, and postorder traversals?",
      "For a binary tree: preorder is node, left, right. Inorder is left, node, right. Postorder is left, right, node. Level order is BFS.",
      "Inorder on a BST is sorted. Preorder is useful to serialize. Postorder is useful to delete nodes or compute child-first values (height, subtree sums). Know the recursive template cold.",
      timeline("When you visit the node", [["Pre", "Root first"], ["In", "Root between children"], ["Post", "Root last"], ["Level", "Top down, left to right"]], "The name is when the node itself is processed"),
    ),
    Q(
      "Why is appending to a dynamic array amortized O(1)?",
      "When the buffer is full, you allocate a larger array (often 2x), copy n items once, then the next n inserts are cheap. Averaged over a sequence of appends, copy cost is O(1) per insert. A single append can still be O(n).",
      "Amortized is not worst-case. Real-time systems may need a pre-sized array. Geometric growth is required — growing by +1 each time would make append O(n) amortized.",
      steps("Pay copies rarely", [["Fill", "n cheap appends"], ["Grow", "Allocate 2n, copy n"], ["Resume", "n more cheap appends"], ["Average", "Copy cost / n is constant"]], "Amortized O(1) still allows a slow resize in the middle"),
    ),
    Q(
      "How can you implement a queue, and what are the tradeoffs?",
      "Linked-list queue: O(1) enqueue/dequeue with head and tail pointers. Array circular buffer: O(1) with modulo indexes, bounded or resizable. Two stacks can make a queue with amortized O(1).",
      "Shifting an array on every dequeue is O(n) — a common beginner mistake. Concurrent queues are a different question (locks, lock-free). Interviews like the two-stack trick as a follow-up.",
      compare("Nodes vs ring buffer", ["Linked queue", "O(1) both ends", "Pointer overhead", "No fixed cap", "Poor cache"], ["Circular array", "O(1) with modulo", "Tight memory", "Must handle wrap", "Bounded unless you grow"], "Never dequeue by shifting the whole array"),
    ),
    Q(
      "What complexity tradeoffs do interviewers expect you to name?",
      "Time vs extra memory (hash set vs sort), preprocessing vs query (sort then binary search), and worst-case vs average (quicksort, hash tables). Also: simpler O(n log n) vs clever O(n) that is harder to get right.",
      "Say the constraints: n up to 1e5 usually cannot be O(n^2). If they want O(1) lookup they should accept O(n) space. Expert-looking answers pick a tradeoff and defend it.",
      hub("You cannot maximize everything", "Trade", [["Time", "Fewer steps"], ["Space", "Fewer allocations"], ["Worst", "Guarantees"], ["Simple", "Fewer bugs"], ["Cache", "Real runtime"]], "State the constraint, then pick the axis you optimize"),
    ),
  ],
  expert: [
    Q(
      "Why is a hash table not always O(1)?",
      "Average O(1) needs a uniform hash, a bounded load factor, and collision handling that stays short. Adversarial keys, a bad hash, or a load factor near 1 make lookup O(n). Rehashing is O(n) when it happens.",
      "Integer keys with identity hashes can clump. String hashes cost O(length). Memory hierarchy: a huge table is not O(1) in wall-clock if every lookup misses cache. Say average vs worst, then load factor.",
      layers("The O(1) assumptions", [["Hash quality", "Spreads keys"], ["Load factor", "Buckets stay short"], ["Collisions", "Chain or probe cost"], ["Rehash", "Occasional O(n)"], ["Key size", "Hashing is not free"]], "Quote average O(1) — then the conditions"),
    ),
    Q(
      "How do AVL trees and red-black trees differ as balanced BSTs?",
      "Both keep height O(log n) with rotations. AVL is more strictly balanced (height difference at most 1), so lookups are slightly faster; inserts/deletes may rotate more. Red-black trees allow a bit more imbalance and typically mutate faster — used in many library maps.",
      "You do not need to code rotations in most interviews, but you should know why a raw BST is unsafe and that TreeMap / std::map are red-black. B-trees/B+ trees are the disk/page version of the same idea.",
      compare("Stricter vs cheaper updates", ["AVL", "Height-balanced", "More rotations", "Faster lookup", "Less common in std libs"], ["Red-black", "Color invariant", "Fewer rotations", "Java TreeMap, C++ map", "Slightly taller"], "Both are O(log n) — the product choice is insert vs lookup mix"),
    ),
    Q(
      "How does Dijkstra's algorithm find shortest paths?",
      "Dijkstra greedily pops the closest unsettled vertex from a min-heap and relaxes outgoing edges. With a binary heap it is O((v+e) log v). It needs non-negative weights. The first time a node is popped, its distance is final.",
      "Negative edges need Bellman-Ford. Unweighted graphs should use BFS, not Dijkstra. Decrease-key vs insert-again are implementation details. A* is Dijkstra with a heuristic on the priority.",
      steps("Greedy on non-negative weights", [["Dist", "0 at source, inf else"], ["Pop", "Smallest tentative"], ["Relax", "Try neighbors"], ["Repeat", "Until heap empty"]], "Non-negative weights are the contract — not optional"),
    ),
    Q(
      "What is a topological sort, and when is it possible?",
      "A topological order of a DAG lists every node before the nodes that depend on it. Kahn's algorithm: queue of indegree 0, peel edges. DFS postorder reversed is the other classic. If a cycle exists, no topo order exists.",
      "Build systems, course prerequisites, and compilation order are the stories. Detecting a cycle is the same pass (nodes remain with indegree > 0, or a gray node in DFS).",
      timeline("Peel independent nodes", [["Count", "Indegree per node"], ["Queue", "Indegree 0"], ["Emit", "Remove outgoing edges"], ["Fail", "Leftovers mean a cycle"]], "Topo sort is DAG-only — cycles are the error case"),
    ),
    Q(
      "How does Union-Find (DSU) work?",
      "Each element starts in its own set. find(x) returns the root; union(a,b) merges sets. Path compression plus union by rank/size makes almost O(1) per op (inverse Ackermann). Used for connected components and Kruskal.",
      "Without the two optimizations it can be O(n). Interviews like cycle detection in an undirected graph: union endpoints of each edge; if they already share a root, that edge closes a cycle.",
      steps("Merge disjoint sets", [["Find", "Walk to root"], ["Compress", "Point along the path to root"], ["Rank", "Attach smaller to larger"], ["Union", "One root remains"]], "Path compression + rank is the whole performance story"),
    ),
    Q(
      "How is dynamic programming different from plain recursion?",
      "DP is recursion plus memory of subproblems (memo) or an equivalent bottom-up table. You need overlapping subproblems and optimal substructure. Without memo, Fibonacci recursion is exponential; with it, O(n).",
      "Not every recursive problem is DP (trees without overlap may just be DFS). State design is the skill: what is the tuple that uniquely identifies a subproblem. Space can often drop if you only need the previous row.",
      compare("Recompute vs remember", ["Naive recursion", "Tree of calls", "Repeats work", "Exponential risk", "Easy to write wrong"], ["DP", "Each state once", "Memo or table", "Polynomial if states are few", "Define the state"], "If the same subproblem shows up twice, you are in DP territory"),
    ),
    Q(
      "What is a trie and when do you use one?",
      "A trie (prefix tree) stores strings by sharing character paths from the root. Insert/search are O(length). Prefix queries and autocomplete are the natural fit. Extra memory is the cost vs a hash set of words.",
      "Compressed tries (radix, Patricia) save space. Aho-Corasick extends tries for multi-pattern search. Interviews: implement insert/search/startsWith on a word dictionary.",
      hub("Shared prefixes", "Trie", [["Root", "Empty prefix"], ["Edge", "A character"], ["Node", "Is-word flag"], ["Search", "Walk letters"], ["Prefix", "Stop mid-path"]], "If the query is a prefix, a hash set is the wrong default"),
    ),
    Q(
      "How does heapify / sift-down keep the heap invariant?",
      "After you replace the root with the last leaf, sift-down swaps the node with its more-extreme child until order is restored. Insert sifts up. Both are O(log n) because the tree is complete and height is log n.",
      "Floyd's build-heap sifts down from the last parent: O(n). Swapping two elements in a heap without sifting breaks the invariant — a common bug when people treat the array as sorted.",
      cycle("Restore parent vs child", "Sift", [["Compare", "Parent and kids"], ["Swap", "With the extreme child"], ["Drop", "Index follows the swap"], ["Stop", "Order holds"]], "The array is a heap only while the parent rule holds"),
    ),
    Q(
      "How does Floyd's cycle-finding algorithm work on a linked list?",
      "Slow pointer moves one step, fast moves two. If there is a cycle they meet; if fast hits null there is no cycle. After a meet, one pointer at head and one at the meet, both speed 1, meet at cycle start.",
      "O(1) extra space is the point versus a hash set of nodes. The second phase is the part people forget. This is also the template for finding the middle (fast at end, slow at mid) when there is no cycle.",
      code("Tortoise and hare", "cycle.js", ["let s = head, f = head", "while (f && f.next) {", "  s = s.next", "  f = f.next.next", "  if (s === f) return true", "}", "return false"], [["s", "One step"], ["f", "Two steps"]], "They only meet if a pointer can loop — that is the cycle"),
    ),
    Q(
      "How do fast and slow pointers solve more than cycle detection?",
      "Same two speeds: middle of a list, palindrome check (reverse second half), and kth from end (lead by k). The invariant is a distance between pointers, not a hash table of indices.",
      "On arrays, opposite-end two pointers are a different pattern. Do not mix the names in an interview — say slow/fast vs left/right. Deleting the nth-from-end node uses a dummy plus a gap of n.",
      steps("Distance as the trick", [["Lead", "Fast ahead by k"], ["Walk", "Both move together"], ["Stop", "Fast at the end"], ["Slow", "Now at the target"]], "The gap between pointers is the algorithm"),
    ),
    Q(
      "How should you talk about best, average, and worst case?",
      "Best is the easiest input of size n (often unrealistic). Average needs a distribution (random pivots, random keys). Worst is the adversary — what you quote for guarantees. Hash and quicksort are the usual examples.",
      "Big-O is often used loosely for worst case. Theta is tight bound; Omega is lower bound. Interviews rarely need the notation police, but they do need you not to call quicksort O(n log n) without average.",
      hub("Three different sentences", "Cases", [["Best", "Already lucky"], ["Average", "Typical input"], ["Worst", "Adversary"], ["Amortized", "Sequence of ops"], ["Expected", "Randomized algos"]], "O(n log n) quicksort is average — say the word"),
    ),
    Q(
      "How does an LRU cache use DSA under the hood?",
      "A hash map from key to node gives O(1) lookup. A doubly linked list (or equivalent) keeps recency: move a node to the front on access, evict the tail. Capacity is bounded; both get and put are O(1) average.",
      "This is the classic combine-two-structures question. A heap by timestamp is O(log n) and the wrong default. Thread safety is a follow-up: one lock, or concurrent maps with care.",
      layers("Map plus recency list", [["Hash", "key -> node"], ["Head", "Most recent"], ["Tail", "Least recent"], ["Hit", "Move node to head"], ["Miss full", "Drop tail, insert head"]], "O(1) LRU is not a heap — it is a dict plus a linked list"),
    ),
    Q(
      "How do you find the lowest common ancestor in a binary tree?",
      "If the tree is a BST, walk from the root until the nodes split left/right. On a general binary tree, recurse: if the current node is p or q, return it; combine left/right hits. Parent pointers or Euler tour + RMQ are the advanced variants.",
      "Clarify BST vs binary tree first. Recursive LCA is O(n) time, O(h) stack. Interviews fail people who assume parent pointers when the node type has none.",
      steps("Split or return", [["BST", "Walk until p and q diverge"], ["General", "Search both subtrees"], ["Both sides", "This node is LCA"], ["One side", "Pass that result up"]], "The LCA is the first node that covers both"),
    ),
    Q(
      "Give a concrete time-space tradeoff you would defend in an interview.",
      "Two-sum: sort plus two pointers is O(n log n) time and O(1) extra if you may mutate; a hash map is O(n) time and O(n) space. Graph shortest path: store all pairs vs compute on demand. String search: KMP automaton vs scan.",
      "Pick one and name n. If n is tiny, O(n^2) is fine and simpler. If they constrain memory, you cannot keep a huge memo table. The expert move is stating the constraint before the algorithm.",
      compare("Pay memory or pay time", ["Hash / memo", "Faster queries", "O(n) extra typical", "Two-sum, DP", "Cache locality varies"], ["Sort / recompute", "Less extra RAM", "Pay n log n or repeat work", "Two pointers", "Mutates or copies"], "Constraints first — then the structure"),
    ),
    Q(
      "How do you detect a cycle in a directed graph, and why does it matter?",
      "DFS colors: white/gray/black. A gray neighbor is a back edge — a cycle. Kahn's algorithm: if you cannot emit all nodes, there is a cycle. Undirected graphs use Union-Find or parent-aware DFS (ignore the edge you came from).",
      "Deadlock detection, module imports, and topo sort all need this. Do not use undirected cycle tricks on a directed graph. Weakly connected plus a cycle is still not a DAG.",
      hub("Directed cycles", "Cycle", [["Gray", "On the DFS stack"], ["Back edge", "To a gray node"], ["Kahn", "Leftover indegrees"], ["DAG", "No directed cycle"], ["Use", "Topo / deadlock"]], "A back edge to an in-progress node is the directed cycle"),
    ),
  ],
};
