const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Frameworks & Libraries",
  slug: "frameworks-libraries",
  description: "React, Angular, Vue, Next.js, Spring Boot, .NET, Django, etc.",
  theme: {
    accent: "#06b6d4",
    hubFill: "#06b6d4",
    hubText: "#0b1f3a",
    centerFill: "#cffafe",
    centerStroke: "#06b6d4",
    label: "Libs",
  },
  beginner: [
    Q(
      "What is the difference between a library and a framework?",
      "You call a library from your code. A framework calls your code: it owns the lifecycle, routing, and where your files go. That inversion of control is the interview line.",
      "React started as a UI library (you still own the app shell). Angular and Django are frameworks: they dictate structure. Next.js and Spring Boot sit on top and take more control. Neither word means 'better.'",
      compare("Who is in charge?", ["Library", "You call it", "Pick and mix", "lodash, React core", "You own main()"], ["Framework", "It calls you", "Conventions and slots", "Angular, Django, Rails", "It owns the loop"], "If you cannot skip the folder layout, you are in a framework"),
    ),
    Q(
      "What is a component in UI libraries like React?",
      "A component is a reusable piece of UI with its own markup, optional state, and a public input surface (props). You compose pages from components instead of one giant template.",
      "Interviews want: inputs in, UI out, and that nesting is how apps scale. Class vs function is a later detail. Angular uses components plus templates; Vue has SFCs — same idea.",
      hub("A reusable UI piece", "Comp", [["Props", "Data from the parent"], ["State", "Data it owns"], ["Render", "What the user sees"], ["Events", "Tell the parent"], ["Compose", "Build larger views"]], "A component is a function from data to UI — plus events"),
    ),
    Q(
      "What are props?",
      "Props are inputs passed from parent to child. In React they are read-only from the child's point of view; to change them, the parent updates state and passes new props.",
      "Mutating props in the child is a smell. Default props and typing (PropTypes, TypeScript) document the contract. Vue props and Angular @Input are the same idea with different syntax.",
      steps("Data flows down", [["Parent", "Holds the value"], ["Pass", "Attribute or binding"], ["Child", "Reads props"], ["Ask up", "Callback or emit"]], "Props in — events out is the beginner mental model"),
    ),
    Q(
      "What is component state?",
      "State is data the component owns and can update. When state changes, the library re-renders that component (and usually its children) so the UI matches.",
      "Props come from outside; state lives inside. Lifting state up means moving it to a common parent. Local UI state (isOpen) vs server data (user) is a later split.",
      compare("Owned inside vs passed in", ["State", "This component writes it", "useState / data()", "Triggers re-render", "Form draft, toggle"], ["Props", "Parent writes it", "Arguments", "Child should not mutate", "Title, user id"], "If two siblings need the same value, it is not local state"),
    ),
    Q(
      "What is React, in one interview answer?",
      "React is a JavaScript library for building UIs from components. You describe what the UI should look like for the current state; React updates the DOM to match.",
      "It does not include routing, HTTP, or a global store — those are extra libraries or Next.js. JSX is syntax for calling React.createElement. Interviews: declarative UI, not 'a framework that does everything.'",
      hub("What React actually is", "React", [["Components", "UI functions"], ["State", "Triggers render"], ["Virtual DOM", "Diff then patch"], ["One way", "Data down"], ["Ecosystem", "Router, data libs"]], "React renders UI — your app still needs a backbone"),
    ),
    Q(
      "What is the virtual DOM?",
      "The virtual DOM is a lightweight tree in memory that describes the UI. The library diffs it against the previous tree and applies a small set of real DOM updates.",
      "The real DOM is slow to touch in bulk; grouping updates helps. It is not magic faster than 'good DOM code.' Vue and React both reconcile; Svelte often compiles away a vDOM. Beginner bar: describe, diff, patch.",
      layers("Describe, then patch", [["Render", "New virtual tree"], ["Diff", "Compare to last"], ["Patch", "Touch real DOM"], ["Paint", "Browser draws"]], "Virtual DOM is a strategy — not a second browser"),
    ),
    Q(
      "How do Angular, Vue, and React differ at a high level?",
      "React is a UI library with a huge ecosystem. Angular is a full framework (TypeScript, DI, RxJS, router). Vue sits in between: approachable SFCs, official router and store, less battery-included than Angular.",
      "Jobs often pick one. Do not trash the others. Templates (Angular/Vue) vs JSX (React) is a style choice. All three solve components, state, and DOM updates.",
      hub("Batteries vs library", "Pick", [["React", "UI core + you choose"], ["Vue", "SFC + official addons"], ["Angular", "Full platform + DI"], ["JSX vs templates", "Style, not superiority"], ["Jobs", "Hiring often decides"]], "Name the tradeoff — not a winner"),
    ),
    Q(
      "What is Next.js used for?",
      "Next.js is a React framework for production apps: routing, server rendering, bundling, and conventions for data fetching so you are not wiring webpack and an Express server by hand.",
      "It can SSR, SSG, or mix. API routes and the App Router add a backend next to the UI. Interviews: Next is not 'React but faster' — it is React plus a server and a router.",
      steps("React plus a server", [["Pages/App", "File-based routes"], ["Render", "SSR or static"], ["Data", "Fetch on server or client"], ["Ship", "Bundled JS + HTML"]], "Next.js is a framework on top of the React library"),
    ),
    Q(
      "What is Spring Boot?",
      "Spring Boot is a Java framework that stands up a Spring application with defaults: embedded server, auto-configuration, and starters so you write business code instead of XML for every bean.",
      "It is for APIs and server apps, not the browser. REST controllers, dependency injection, and Spring Data are the usual interview cluster. Boot is opinionated Spring — not a different language.",
      hub("Java services quickly", "Boot", [["Starters", "Deps that fit together"], ["Auto-config", "Beans from the classpath"], ["Tomcat", "Embedded HTTP"], ["Actuator", "Health and metrics"], ["Spring", "DI and AOP underneath"]], "Spring Boot is conventions on top of Spring"),
    ),
    Q(
      "What is .NET in interview conversations?",
      ".NET is Microsoft's runtime and library stack. ASP.NET Core is the web framework: Kestrel, middleware, MVC or minimal APIs, and C# as the usual language.",
      "People say '.NET' when they mean ASP.NET Core Web API. Entity Framework is the common ORM. It is not only Windows anymore. Compare it to Spring Boot or Django as a server framework.",
      layers("Stack names", [["C# / F#", "Languages"], [".NET runtime", "CLR, GC, BCL"], ["ASP.NET Core", "HTTP pipeline"], ["EF Core", "Talk to SQL"]], "Say ASP.NET Core when you mean the web framework"),
    ),
    Q(
      "What is Django?",
      "Django is a Python web framework that includes an ORM, admin, auth, and URL routing — batteries included for server-rendered sites and APIs (Django REST Framework is the usual API layer).",
      "MTV: model, template, view (the view is the request handler). Interviews: migrate models, do not put business logic only in templates, and CSRF is on by default for forms.",
      hub("Python, batteries included", "Django", [["ORM", "Models to tables"], ["Admin", "CRUD for free"], ["URLs", "path() routing"], ["Views", "Handle the request"], ["Templates", "Render HTML"]], "Django owns the request — you fill in models and views"),
    ),
    Q(
      "Why do teams use a framework at all?",
      "Frameworks give structure, shared solutions for routing, auth, and rendering, and a hiring pool that already knows the conventions. You spend less time on glue and more on the product.",
      "The cost is lock-in, upgrades, and magic. Beginners should say both sides. A small widget may only need a library. A bank's portal may need the rails.",
      steps("What you buy", [["Structure", "Where code lives"], ["Defaults", "Auth, CSRF, bundling"], ["Ecosystem", "Plugins and jobs"], ["Cost", "Upgrades and magic"]], "A framework is a bet that conventions will outrun custom glue"),
    ),
    Q(
      "When should you not use a heavy framework?",
      "Skip it for a static page, a tiny widget, a script, or when the team does not know the framework and the deadline is a weekend. A few files of HTML/CSS/JS or a single library can be enough.",
      "Interviews love this as a judgment question. Next.js for a marketing page of three screens is often overkill. Spring Boot for a 20-line cron may be. Prefer the smallest tool that you can operate.",
      compare("Reach for it vs not", ["Use a framework", "Many screens, auth, team", "SEO or SSR needed", "Hiring the skill", "Long-lived product"], ["Skip it", "One page, no auth", "Tiny widget or script", "You would fight the magic", "Deadline is a weekend"], "The best framework is sometimes none"),
    ),
    Q(
      "What is routing in a SPA or web framework?",
      "Routing maps a URL to a screen or handler. In the browser, the router updates the view without a full reload. On the server, the framework picks a controller or page for that path.",
      "Beginners mix client routers (React Router, Vue Router, Angular Router) with server routes (Django urls, ASP.NET, Next.js). Next.js file routing is both: the server knows the path too.",
      timeline("URL to UI", [["Change URL", "Link or navigate()"], ["Match", "Router finds a route"], ["Load", "Maybe fetch data"], ["Render", "Component or template"]], "A router is a lookup table from path to code"),
    ),
    Q(
      "What is a template or view in server frameworks?",
      "A template is HTML with holes for data (Django templates, Razor, Thymeleaf). The view or page handler fetches data, picks a template, and returns HTML. In SPAs the 'view' is a component tree.",
      "Keep logic in the handler/service, not a forest of template ifs. XSS: templates that auto-escape are safer. Interviews: MVC/MTV names differ but the split is the same — data, presentation, request.",
      code("Fill HTML on the server", "hello.html", ["<h1>{{ user.name }}</h1>", "<p>{{ order.total }}</p>"], [["Data", "Passed in from the view"], ["Escape", "Do not pipe raw HTML"]], "A template is a string recipe — the view supplies the ingredients"),
    ),
  ],
  intermediate: [
    Q(
      "What does inversion of control mean for frameworks?",
      "IoC means the framework owns the main loop and calls your callbacks, components, or controllers at the right time. You plug in; you do not drive every step.",
      "Hollywood principle: don't call us, we'll call you. DI is one IoC tool (Spring, Angular). React still IoC at render time even if you call ReactDOM.createRoot. Library code you invoke from main() is not IoC.",
      layers("Who calls whom", [["Your main()", "You orchestrate"], ["Library", "You call functions"], ["Framework", "It calls your classes"], ["DI container", "It constructs deps"]], "If you lost main(), you accepted IoC"),
    ),
    Q(
      "How should React state and props work together?",
      "Keep state in the nearest common owner. Pass data down as props and pass setters or callbacks down so children can request changes. Do not duplicate the same fact in two useState hooks.",
      "Derived data should be computed, not stored. Context avoids prop drilling for rare, stable values (theme, current user) — it is not a replacement for all props. Lifting state is the classic refactor.",
      steps("One source of truth", [["Find", "Who needs the data?"], ["Lift", "Put state in that parent"], ["Pass", "Props to children"], ["Notify", "Callbacks up"]], "If two states can disagree, you have a bug waiting"),
    ),
    Q(
      "How does virtual DOM reconciliation actually work?",
      "Each render produces a new tree of elements. React (and Vue) walk it, match children by position or key, and update, insert, or delete real nodes. Keys tell the diff which item is which in a list.",
      "Missing keys remount items and reset state. Index keys break on reorder. The vDOM is not always faster than compiling (Svelte) or targeted updates. Interviews: keys, batching, and that setState is async/batched.",
      code("Keys identify list items", "List.jsx", ["items.map((item) => (", "  <Row key={item.id} row={item} />", "))"], [["key", "Stable id, not index"], ["Diff", "Move vs destroy"]], "A key is identity — the index is a position"),
    ),
    Q(
      "Angular vs Vue vs React — what do you actually trade?",
      "Angular: TypeScript-first, DI, RxJS, heavy CLI, one way to do most things. React: flexible, JSX, you assemble routing and data. Vue: gentle curve, SFCs, official Pinia/Router, templates by default.",
      "Change detection: Angular zones or signals, React pull-based render, Vue proxies. Hiring and existing code usually decide. Intermediate interviews want a tradeoff table, not a Twitter take.",
      hub("Pick for the team", "Choice", [["Angular", "Enterprise structure"], ["React", "Ecosystem and jobs"], ["Vue", "Approachable SFCs"], ["Lock-in", "Angular highest"], ["Glue", "React highest"]], "The second framework you learn is easier — the first is politics"),
    ),
    Q(
      "How does Next.js server-side rendering work?",
      "On a request, Next runs your page or server component on the server, produces HTML, sends it, then the browser hydrates client components so clicks work. Data fetching can run on the server before HTML is sent.",
      "getServerSideProps (Pages Router) runs every request. App Router server components do not ship their code to the client. Static generation is the cousin that runs at build time. Know which router the job uses.",
      timeline("Request to HTML", [["Hit route", "URL matches a page"], ["Server run", "Fetch + render"], ["HTML", "First bytes to browser"], ["JS", "Hydrate client bits"]], "SSR is HTML now — hydration is interactivity later"),
    ),
    Q(
      "What does Spring Boot auto-configuration actually do?",
      "It looks at the classpath and your properties, then registers beans you would have written by hand — a DataSource if a driver is present, a DispatcherServlet, JSON converters, and so on. You override by defining your own bean.",
      "spring.factories / AutoConfiguration.imports is the mechanism. Debug with --debug or the conditions report. Interviews: starters pull deps; auto-config wires them; @SpringBootApplication turns it on.",
      steps("Classpath to beans", [["Starter", "Adds jars"], ["Condition", "If class X present"], ["Bean", "Framework registers it"], ["Override", "Your @Bean wins"]], "Auto-config is conventions with an escape hatch"),
    ),
    Q(
      "How is an ASP.NET Core request processed?",
      "The request enters a middleware pipeline (exception handler, HTTPS, auth, routing, endpoints). MVC or minimal APIs then run your action. You add middleware with UseX in Program.cs — order matters.",
      "Compare to Express or Spring filters. Authentication vs authorization are different middleware. Interviews: Kestrel is the server; IIS or a reverse proxy may sit in front. Dependency injection is built in.",
      layers("Pipeline order is behavior", [["Host", "Kestrel / reverse proxy"], ["Middleware", "Cross-cutting"], ["Routing", "Pick the endpoint"], ["Action", "Your C# method"], ["Result", "JSON or view"]], "If auth runs after the endpoint, you already ran too much"),
    ),
    Q(
      "How does a Django request reach a template?",
      "URL conf matches a path to a view function or class. The view uses the ORM, builds a context dict, and returns render() with a template — or JsonResponse for an API.",
      "Middleware wraps the view (CSRF, auth, sessions). Fat views are a smell; push logic to models or services. DRF replaces templates with serializers for JSON APIs.",
      cycle("MTV in motion", "Django", [["URL", "path() match"], ["View", "Python handler"], ["Model", "ORM query"], ["Template", "HTML out"]], "The view is the conductor — the template should stay dumb"),
    ),
    Q(
      "What problem do React hooks solve, and what are the rules?",
      "Hooks let function components have state and side effects (useState, useEffect, useRef) without classes. Rules: only call them at the top level, only from React functions, same order every render.",
      "useEffect runs after paint; dependency arrays decide when. Stale closures are the classic bug. Custom hooks share stateful logic. Interviews: why not if (x) useState() — the order would break.",
      compare("Classes vs hooks", ["Class", "this.state, lifecycle", "this binding pain", "Hard to reuse logic", "componentDidMount"], ["Hooks", "Functions + calls", "Compose with custom hooks", "Rules of Hooks", "useEffect syncs the world"], "Hooks are a protocol — breaking the order breaks the fiber"),
    ),
    Q(
      "What is dependency injection?",
      "DI means a class does not construct its collaborators; something else passes them in (constructor injection). A container (Spring, Angular, ASP.NET) can create the graph from types and annotations.",
      "Benefits: test with fakes, swap implementations, single place for lifetimes (singleton vs request). Service locator (asking a global get(Service)) is the smell. New Foo() inside a controller is the beginner trap.",
      hub("Pass deps in, do not new them", "DI", [["Constructor", "Required deps"], ["Interface", "Swap in tests"], ["Scope", "Singleton, request"], ["Container", "Wires the graph"], ["Locator", "Usually avoid"]], "If a class news its database, you cannot unit test it cleanly"),
    ),
    Q(
      "How do you think about state management as the app grows?",
      "Local state first, then lift, then context for low-frequency global data, then a store (Redux, Zustand, Pinia, NgRx) when many distant components write the same domain data or you need time-travel/debug traces.",
      "Server state (React Query, RTK Query) is not the same as client UI state — cache it with a library that knows fetching. Putting everything in Redux is an intermediate anti-pattern.",
      layers("Reach for the next layer when it hurts", [["Local", "useState / data"], ["Lifted", "Parent owns it"], ["Context", "Avoid drilling"], ["Store", "Shared domain"], ["Server cache", "Async data"]], "A store is not a database — it is a client model"),
    ),
    Q(
      "What is hydration in a SSR framework?",
      "Hydration attaches event listeners and component state to HTML the server already sent, so the page becomes an interactive app without throwing away the markup.",
      "The client must render the same tree or you get mismatch warnings. Extra JS cost is the downside of 'fast HTML.' Partial or island hydration (Astro, some Next patterns) hydrates less of the page.",
      steps("HTML first, then JS", [["SSR", "Send markup"], ["Download", "Client bundle"], ["Hydrate", "Attach fibers/events"], ["Interact", "Clicks work"]], "Hydration assumes the server HTML was a preview of the same app"),
    ),
    Q(
      "Controlled versus uncontrolled inputs — why do React interviews ask?",
      "A controlled input takes value from state and onChange updates state — React is the source of truth. Uncontrolled inputs use the DOM (ref, defaultValue) until you read them on submit.",
      "Forms with validation usually want controlled or a form library. File inputs stay uncontrolled. Fighting the DOM (cursor jumps) means you are half-controlling. Vue v-model is controlled-by-default sugar.",
      compare("Who owns the keystrokes?", ["Controlled", "State is the value", "Easy to validate", "Re-render per key", "Form libraries like this"], ["Uncontrolled", "DOM is the value", "Less React code", "Read on submit", "File inputs stay here"], "Pick one owner for the string in the box"),
    ),
    Q(
      "What does an ORM like Django's or EF Core give you?",
      "An ORM maps classes to tables so you query in the language instead of raw SQL for the common path. You still need to know SQL for N+1, transactions, and migrations.",
      "N+1 queries are the interview follow-up (select_related, prefetch, Include). Leaky abstractions: generated SQL can be worse than a handwritten query. Use the ORM until it hurts, then explain why you dropped to SQL.",
      hub("Objects in, SQL out", "ORM", [["Model", "Class ~ table"], ["Queryset", "Lazy until eval"], ["Migrate", "Schema changes"], ["N+1", "Loop of queries"], ["Escape", "Raw SQL"]], "An ORM is a translator — you are still responsible for the query count"),
    ),
    Q(
      "How is client-side SPA routing different from server routing?",
      "SPA routing changes the URL and the component tree in the browser; the server may only serve index.html for all paths. Server routing runs code on the host for that path and can return HTML or JSON.",
      "Deep links need the host configured to fall back to the SPA. SSR frameworks do both: the server knows the route and the client hydrates. 404s must exist on both sides or refresh breaks.",
      compare("Who handles the path?", ["SPA router", "JS after load", "Need history fallback", "Fast tab switches", "Refresh can 404"], ["Server / hybrid", "Every request can SSR", "Real 404 at the edge", "Next knows both sides", "Deep links just work"], "If refresh 404s, your server does not know the SPA routes"),
    ),
  ],
  expert: [
    Q(
      "What are React Server Components and how do they differ from SSR of client components?",
      "RSCs run on the server (or at build time), can await data, and send a serialized UI payload. They do not ship their JS to the client and cannot use hooks or browser APIs. Client components hydrate as before and may be children of RSC with a serializable boundary.",
      "SSR of a client component still sends its JS for hydration. RSC is a split in the module graph ('use client'). Expert Next interviews: no useState in RSC, secrets stay on the server, and you pass serializable props across the boundary — not functions.",
      compare("Where the component runs", ["RSC", "Server only", "Can read DB/files", "Zero client JS for itself", "No hooks"], ["Client component", "Ships JS", "Hooks and events", "May still SSR HTML", "Hydrates"], "RSC is not 'SSR with a new name' — it is a different bundle"),
    ),
    Q(
      "What causes hydration mismatches and how do you prevent them?",
      "Mismatch means the client's first render HTML does not equal the server HTML: Date.now(), random IDs, invalid nested tags, browser-only APIs, or locale/timezone differences. React may detach and rebuild, losing the SSR benefit.",
      "suppressHydrationWarning is a last resort for text like timestamps. Render device-specific UI after mount. Valid HTML (p cannot contain div) matters. Expert: streaming and Suspense change when pieces hydrate.",
      hub("Why the trees disagree", "Hydrate", [["Time", "now() differs"], ["Random", "IDs per machine"], ["HTML", "Browser 'fixes' tags"], ["Locale", "en-US vs server"], ["Extension", "DOM mutated"]], "If it only breaks with an ad blocker, the DOM was not what you serialized"),
    ),
    Q(
      "When should you refuse a framework on an expert team?",
      "Refuse when the problem is a library-sized widget, when the framework's rendering model fights the product (canvas games, extreme low-latency), when upgrade cost exceeds feature value, or when you cannot hire or operate it.",
      "Expert answer names lock-in, CVE surface, and bundle size. Also refuse a second framework in one app without a hard boundary. Prefer boring: the language's HTTP server plus a UI library can beat a mega-stack for a CRUD API.",
      steps("A framework is a liability too", [["Size", "Is the problem small?"], ["Team", "Can we operate upgrades?"], ["Fit", "Does the model match?"], ["Exit", "Can we extract later?"]], "Choosing none is a design decision — document it"),
    ),
    Q(
      "How do hook closures and concurrent rendering bite you?",
      "An effect or callback captures props/state from the render that created it. If you omit deps, you see stale values. Concurrent React may render twice in dev and interrupt renders — side effects belong in useEffect, not in render.",
      "useEffectEvent (or refs) for stable event handlers is the modern pattern. Abort fetches on cleanup. Expert: purity of render, and why setState in render is a restart, not a loop you invent.",
      code("Stale closure", "Search.jsx", ["useEffect(() => {", "  fetch('/q?s=' + query)", "}, [])"], [["[]", "Ignores query changes"], ["Fix", "Depend on query + abort"]], "The function you remember is from an old render"),
    ),
    Q(
      "Dependency injection versus service locator — why do architects care?",
      "Constructor DI makes dependencies explicit in the type. A locator (static GetService, Angular inject() in random places, Spring's ApplicationContext.getBean) hides them and makes tests and cycles harder to see.",
      "Frameworks still use a locator internally. Your application code should take interfaces in constructors. Expert Spring: @Autowired fields are convenient and painful. Composition root is where new is allowed.",
      compare("Visible vs ambient", ["Constructor DI", "Deps in the signature", "Easy fakes", "Cycles show up", "Preferred in app code"], ["Service locator", "Ask a global bag", "Hidden deps", "Harder to see lifetimes", "inject() in leaves sparingly"], "If you cannot list collaborators from the constructor, they are hidden"),
    ),
    Q(
      "How would you design state management for a large SPA?",
      "Split server cache (query library) from UI/session state. Normalize entities. Put write flows in explicit mutations with rollback. Avoid a single god store. Use selectors so components subscribe narrowly.",
      "Redux Toolkit, Zustand, Pinia, NgRx, Signals — pick one model and consistency. Expert: undo, optimistic updates, and multi-tab. Context for theme is fine; context for a ticking store will re-render the world.",
      layers("Not one bucket", [["Server cache", "Keys, stale time"], ["Entities", "Normalized maps"], ["Session", "Auth, prefs"], ["Ephemeral UI", "Modals, drafts"], ["URL", "Shareable filters"]], "If everything is global, nothing is local — and everything re-renders"),
    ),
    Q(
      "Virtual DOM versus compiled UI (Svelte, Solid, Angular Ivy) — what is the real difference?",
      "vDOM re-runs a render function and diffs. Compilers emit fine-grained updates or incrementally update bindings when a signal changes, skipping a full tree walk. Neither wins on every benchmark; DX and team skill matter.",
      "React Compiler and Vue Vapor blur the line. Expert interviews: keys and list diffing still exist; fine-grained systems can over-subscribe. Know when a canvas or WebGL leaves all of them.",
      compare("Diff a tree vs update a binding", ["Virtual DOM", "Render then diff", "Predictable model", "Work scales with tree", "React, Vue default"], ["Compiled / signals", "Update what changed", "Less runtime", "Mental model of graphs", "Svelte, Solid, Ivy"], "The DOM was never the only bottleneck — JS and layout still are"),
    ),
    Q(
      "How do Next.js App Router streaming and Suspense change SSR?",
      "You wrap slow server fetches in Suspense; the framework streams a shell then later HTML (and RSC payload) for the hole. TTFB drops; LCP may still wait on the slow piece unless you design the shell well.",
      "Client Suspense needs a fallback and a cache. Waterfalls on the server still hurt — fetch in parallel. Expert: cached vs dynamic rendering, cookies() opting into dynamic, and not blocking the whole page on one query.",
      timeline("Shell, then holes", [["Shell", "Fast HTML out"], ["Suspend", "Wait on data"], ["Stream", "More HTML later"], ["Hydrate", "Client islands"]], "Streaming SSR is progressive HTML — not a faster database"),
    ),
    Q(
      "How do Spring bean scopes and proxies show up in production bugs?",
      "Singleton is the default — one instance, injected everywhere. Request/session scopes need proxies so a singleton can depend on a request-scoped bean. Prototype creates a new instance when asked, not on every method call unless you look it up again.",
      "Capturing HttpServletRequest in a singleton field is a leak across users. @Transactional proxies mean self-invocation skips the proxy. Expert Boot: know AOP, circular deps, and why constructor injection plus final fields is the default advice.",
      hub("Lifetime bugs", "Bean", [["Singleton", "Shared, watch state"], ["Request", "Per HTTP call"], ["Proxy", "Lazy to the real one"], ["Self-call", "No proxy, no txn"], ["Circular", "Redesign the graph"]], "A singleton that caches a user is a security incident"),
    ),
    Q(
      "How does the ASP.NET Core DI lifetime model fail when misused?",
      "Singleton, scoped (usually per request), and transient. Capturing a scoped DbContext in a singleton is a classic failure. Background services are singletons — they must create a scope to use EF.",
      "Dispose is tied to the container scope. Expert: IHostedService, IServiceScopeFactory, and that transient services which own IDisposable can leak if resolved from root. Same story as Spring, different names.",
      hub("How long does it live?", "DI", [["Singleton", "App lifetime, immutable"], ["Scoped", "One request, DbContext"], ["Transient", "New each resolve"], ["Dispose", "Tied to the scope"], ["Hosted", "Needs its own scope"]], "Never store a scoped service on a singleton field"),
    ),
    Q(
      "What happens on one Django request at the ORM and middleware layer?",
      "Middleware stack in, URL resolve, view, template or DRF, middleware out. The ORM is lazy; a template that touches relations can explode into N+1 after you thought the view was cheap. Transactions and select_for_update are explicit.",
      "ATOMIC_REQUESTS is a footgun for long views. Connection-per-request and CONN_MAX_AGE matter under gunicorn. Expert: QuerySet caching, iterator(), and why printing a queryset in logging evaluates it.",
      cycle("Until the response leaves", "Request", [["MW in", "Auth, locale"], ["View", "Build queryset"], ["Template/DRF", "Evaluate queries"], ["MW out", "Cookies, cache"]], "The view returning a QuerySet is not the same as the SQL having run"),
    ),
    Q(
      "How do you keep a framework from owning your domain?",
      "Put business rules in plain modules/classes that do not import React, Django, or Spring. Adapters at the edge: controllers, components, and ORM entities translate in and out. Test the domain without starting the framework.",
      "Hexagonal / clean architecture in modest form. Expert: you will still leak a little; the goal is extractability. When not to: a 4-screen CRUD app does not need four layers of ports.",
      layers("Framework at the edge", [["UI / HTTP", "Controllers, pages"], ["Application", "Use cases"], ["Domain", "Rules, no imports"], ["Infra", "SQL, queues"]], "If your entity class subclasses a framework Model, the framework owns you"),
    ),
    Q(
      "Micro-frontends versus a modular monolith — when is a framework split worth it?",
      "Split when independent teams, deploy cadences, or tech stacks truly diverge and you can pay for duplicated design systems, routing, and performance. Otherwise a modular monolith (packages, boundaries) is cheaper.",
      "Module federation and iframes have operational cost. Shared auth and CSS become politics. Expert: organizational Conway, not a resume-driven architecture. Most products should not be micro-frontends.",
      compare("Team topology vs tech fashion", ["Modular monolith", "One deploy", "Shared UI kit", "Cheaper contracts", "Default for most products"], ["Micro-frontends", "Independent ship", "Isolation", "Duplicate cost", "Only with real team split"], "A framework per team is an org chart — not a default"),
    ),
    Q(
      "What is concurrent React (Suspense, transitions) trying to solve?",
      "It lets React prepare an update in the background and keep showing the old UI until ready, so typing stays responsive. startTransition marks updates as interruptible. Suspense shows fallbacks for async reads.",
      "It is not parallelism of JS. Expert: tearing with external stores (use sync external store), why you cannot read a promise in render without a cache, and that Suspense for data still needs a library convention.",
      steps("Keep the last good frame", [["Urgent", "Input, click"], ["Transition", "Filter the list"], ["Suspend", "Wait for data"], ["Commit", "Swap when ready"]], "Concurrent means interruptible render — not two threads of your code"),
    ),
    Q(
      "How would you explain a framework choice to a staff-level interviewer?",
      "State the product constraints (SEO, latency, team skill, hiring, ops), name 2–3 viable stacks, pick one with an explicit cost (lock-in, SSR complexity, JVM ops), and say what would make you change your mind.",
      "This is the expert communication question. 'We use React because everyone does' is weak. 'We use Django because the domain is form-heavy CRUD and the team is Python' is strong. Mention when you would not use it.",
      timeline("A decision you can defend", [["Constraints", "Users, team, ops"], ["Options", "Two or three"], ["Pick", "One bet"], ["Review", "What would change it"]], "Staff level is judgment — not a longer feature list"),
    ),
  ],
};
