const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Programming Fundamentals",
  slug: "programming-fundamentals",
  description: "Variables, data types, operators, conditions, loops, functions",
  theme: {
    accent: "#2563eb",
    hubFill: "#2563eb",
    hubText: "#ffffff",
    centerFill: "#dbeafe",
    centerStroke: "#2563eb",
    label: "Code",
  },
  beginner: [
    Q(
      "What is a variable?",
      "A variable is a named slot that holds a value your program can read and update later.",
      "Names should describe the data. Some languages let you rebind the name; others treat assignment as mutating a box. Interviews want: name + value + type, not “a box in RAM” as the whole answer.",
      steps("Name, then value", [["Declare", "Pick a name"], ["Assign", "Put a value in"], ["Use", "Read it later"], ["Update", "Replace the value"]], "A variable is a labeled place to keep data"),
    ),
    Q(
      "What is a data type?",
      "A data type says what kind of value you have and which operations are legal — number, text, boolean, list, and so on.",
      "Types catch mistakes early (you cannot add a string to a date unless the language defines it). Static types are checked before run; dynamic types are checked when the code runs.",
      hub("What a type decides", "Type", [["Shape", "Number vs text"], ["Ops", "What + means"], ["Size", "How it is stored"], ["Null", "Can it be empty"], ["Safety", "Illegal mixes fail"]], "Types are rules for values — not just labels"),
    ),
    Q(
      "What is the difference between a primitive type and a composite type?",
      "Primitives are single values (int, bool, char). Composite types group values (arrays, objects, records).",
      "Interviews use this to see if you can talk about memory and APIs. Primitives copy by value in many languages; composites often copy a reference to the same object.",
      compare("One value vs a group", ["Primitive", "int, bool, char", "Single slot", "Usually copied", "No fields"], ["Composite", "array, object, map", "Several values", "Often shared", "Has structure"], "Know whether assignment copies data or a pointer"),
    ),
    Q(
      "What are operators?",
      "Operators are built-in symbols or keywords that compute a new value from one or more operands — +, -, *, /, ==, &&, and so on.",
      "Unary operators take one operand (!x). Binary take two (a + b). Precedence and associativity decide order. Overloading can change meaning per type.",
      hub("Common operator families", "Ops", [["Arithmetic", "+ − * / %"], ["Compare", "== != < >"], ["Logic", "&& || !"], ["Assign", "= += -="], ["Bitwise", "& | ^ <<"], ["Other", "ternary ?. "]], "An operator is syntax for a function the language already knows"),
    ),
    Q(
      "What is the difference between = and ==?",
      "= assigns a value to a variable. == (or === in some languages) tests whether two values are equal and yields a boolean.",
      "A classic bug is writing if (x = 1) which assigns and may be truthy. Prefer === in JavaScript to avoid coercion surprises.",
      compare("Write vs ask", ["Assignment =", "Changes the variable", "Result is the value", "Used in statements", "x = 3"], ["Equality ==", "Does not change x", "Result is true/false", "Used in conditions", "x == 3"], "One writes a value — the other asks a yes/no question"),
    ),
    Q(
      "How do if / else conditions work?",
      "An if checks a boolean condition. If it is true, that block runs. Else (and else-if) covers the remaining cases.",
      "Conditions should be booleans, not assignments. Keep branches small. Nested ifs often become clearer as early returns or a switch/match.",
      steps("A decision", [["Test", "Is it true?"], ["Then", "Run the if body"], ["Else-if", "Try the next test"], ["Else", "Fallback path"]], "Only one branch of a chain should run"),
    ),
    Q(
      "When would you use a switch or match instead of if/else?",
      "Use switch/match when one value is compared against several known cases. It reads as a table of options.",
      "Fall-through in C-style switch is a footgun — most modern match forms do not fall through. Exhaustiveness (covering every case) is an expert-level plus.",
      compare("Chain vs table", ["if / else", "Any boolean tests", "Good for ranges", "Easy to nest badly", "Order matters"], ["switch / match", "One value, many cases", "Good for enums", "Clearer lists", "Can require default"], "Pick the shape that matches the decision"),
    ),
    Q(
      "What is a loop?",
      "A loop repeats a block while a condition holds, or once per item in a collection.",
      "for is usually counting or iterating a known set. while is “until something becomes true.” Infinite loops need a clear exit (break, return, or condition).",
      cycle("Repeat until done", "Loop", [["Init", "Set start state"], ["Test", "Should we continue?"], ["Body", "Do the work"], ["Update", "Move to next"]], "A loop is controlled repetition — not copy-paste"),
    ),
    Q(
      "What is the difference between for and while?",
      "for packages init, condition, and update in one header — great for indexes and iterators. while only has a condition, so you manage the rest in the body.",
      "for-each / for-of hides the index when you only need items. while fits “read until EOF” and retry loops. do-while runs the body at least once.",
      compare("Known count vs unknown", ["for", "Index or iterator", "Header holds the clock", "Harder to forget update", "for (i = 0; i < n; i++)"], ["while", "Condition only", "You update inside", "Easy infinite loop", "while (!done)"], "Use for when the steps are regular"),
    ),
    Q(
      "What is a function?",
      "A function is a named (or anonymous) block you can call with inputs to get a result or a side effect.",
      "Functions hide detail, let you test one idea, and avoid copy-paste. Interviews want parameters, return, and that a call jumps to the body then comes back.",
      steps("Define then call", [["Name", "What it does"], ["Params", "What it needs"], ["Body", "The steps"], ["Return", "What it gives back"]], "A function is a reusable recipe"),
    ),
    Q(
      "What is the difference between a parameter and an argument?",
      "A parameter is the name in the function definition. An argument is the actual value you pass when you call it.",
      "People mix the words. Be precise: function greet(name) — name is the parameter; greet(\"Ada\") — \"Ada\" is the argument.",
      code("Parameter vs argument", "greet.js", ["function greet(name) {", "  return 'Hi ' + name", "}", "greet('Ada')"], [["Param", "name in the definition"], ["Arg", "'Ada' at the call"]], "Definition names slots — the call fills them"),
    ),
    Q(
      "What does return do?",
      "return exits the function and hands a value back to the caller. Code after return in that path does not run.",
      "A function can return nothing (undefined/void) and still be useful for side effects. Multiple return points are fine if each path is obvious.",
      steps("Give a result back", [["Call", "Jump into the function"], ["Work", "Compute in the body"], ["Return", "Send a value out"], ["Resume", "Caller uses it"]], "return is how a function answers"),
    ),
    Q(
      "What is scope?",
      "Scope is where a name is visible. Local names live inside a function or block; globals are visible more widely.",
      "Shadowing happens when an inner name hides an outer one. Prefer small scopes — fewer surprises. Closures keep inner functions tied to the scope where they were created.",
      layers("Where names live", [["Global", "Visible across the file / program"], ["Function", "Parameters and locals"], ["Block", "let/const inside { }"], ["Inner", "Nested functions see outer lets"]], "If you cannot see the name, you are outside its scope"),
    ),
    Q(
      "What is the difference between a constant and a variable?",
      "A constant’s binding should not be reassigned. A variable may be reassigned. In some languages const still allows mutating an object’s fields.",
      "JavaScript const prevents rebinding, not deep freeze. Immutability of the value is a separate idea from const. Interviews like that distinction.",
      compare("Rebind vs freeze", ["Constant", "Name stays bound", "Signals “do not replace”", "const / final / val", "Object fields may still change"], ["Variable", "Name can be rebound", "Signals “this will change”", "let / var", "Use when the slot updates"], "const is about the name — immutability is about the data"),
    ),
    Q(
      "Why do comments and naming matter in interviews?",
      "Clear names reduce the need for comments. Comments should explain why, not restate the code. Interviewers read your intent from both.",
      "Bad: // increment i. Good: // skip the header row. Functions named calculate() without a noun are a smell. This is a fundamentals question about communication.",
      steps("Make code readable", [["Name", "Say what the value is"], ["Function", "Say what it does"], ["Comment", "Say why, if needed"], ["Delete", "Drop comments that lie"]], "The next reader is often you in six months"),
    ),
  ],
  intermediate: [
    Q(
      "What is pass-by-value vs pass-by-reference?",
      "Pass-by-value copies the argument. Pass-by-reference lets the callee change the caller’s variable. Many languages pass object references by value — you can mutate the object but not rebind the caller’s name.",
      "Java is pass-by-value of the reference. C++ has real references and pointers. Python names are bindings; mutating a list is visible, rebinding a name is not. Say which layer you mean.",
      compare("Copy the slot vs share it", ["By value", "Callee has a copy", "Rebind is local", "Cheap for small types", "Safe from aliasing"], ["By reference", "Same variable", "Rebind shows up", "Used for out-params", "Alias bugs possible"], "“I passed the object” is not enough — say if the name or the heap changed"),
    ),
    Q(
      "What is a stack vs heap in typical runtimes?",
      "The call stack holds frames for active functions (locals, return address). The heap holds objects whose lifetime is not tied to one frame.",
      "Stack allocation is fast and automatic. Heap needs GC or free(). Recursion depth is a stack limit. Closures and objects outlive the frame, so they live on the heap.",
      layers("Where data sits", [["CPU / registers", "Hottest values"], ["Call stack", "Frames, locals, return"], ["Heap", "Objects, arrays, closures"], ["Static / data", "Globals, constants"]], "Stack is “now”; heap is “until we drop the last reference”"),
    ),
    Q(
      "What is recursion?",
      "Recursion is a function calling itself (directly or indirectly) with a smaller subproblem, plus a base case that stops.",
      "Every recursive solution needs a base case and progress toward it. Tail recursion can be optimized in some languages. Stack overflow is the usual failure mode.",
      steps("Shrink until you stop", [["Base", "Trivial answer"], ["Smaller", "Call with less work"], ["Combine", "Use the sub-result"], ["Return", "Answer the original"]], "No base case means infinite recursion"),
    ),
    Q(
      "When is iteration better than recursion?",
      "Iteration is usually better for simple loops, better control of memory, and languages without tail-call optimization. Recursion shines on trees and divide-and-conquer.",
      "Interviewers want you to convert a linear recursion to a loop. For trees, recursion (or an explicit stack) matches the structure.",
      compare("Loop vs self-call", ["Iteration", "One frame", "Easy to profile", "Great for arrays", "You manage the index"], ["Recursion", "Frames per call", "Matches trees", "Elegant divide/conquer", "Watch the stack"], "Pick the tool that matches the data shape"),
    ),
    Q(
      "What is short-circuit evaluation?",
      "&& and || may skip the right operand: false && x never runs x; true || x never runs x.",
      "This is used for null checks: obj && obj.method(). Side effects on the right may not run — a common interview trap. ?? (nullish) is a different operator.",
      code("Right side may not run", "short.js", ["if (user && user.id) {", "  load(user.id)", "}", "flag || save()"], [["&&", "Stop if left is falsy"], ["||", "Stop if left is truthy"]], "Do not put required side effects only on the right"),
    ),
    Q(
      "What is type coercion?",
      "Coercion is automatic conversion between types, e.g. \"3\" + 1 becoming \"31\" in JavaScript or 1 == \"1\" being true.",
      "Implicit coercion causes bugs. Prefer explicit conversions (Number(), parseInt, int()). Strict equality avoids many JS traps. Statically typed languages coerce less.",
      hub("Conversions you did not write", "Coerce", [["String +", "Turns numbers into text"], ["==", "May convert before compare"], ["If (x)", "Truthy / falsy"], ["Math", "Strings to numbers"], ["Boolean()", "Explicit is clearer"]], "If the language converts for you, say so out loud"),
    ),
    Q(
      "What are truthy and falsy values?",
      "In languages with implicit booleans, some values count as false in if (x): 0, empty string, null, undefined, NaN (JS). Everything else is truthy.",
      "Empty arrays and objects are truthy in JS — a frequent trick. Prefer explicit checks (x == null, x.length === 0) in production code.",
      compare("Looks true vs is true", ["Falsy (JS)", "false, 0, ''", "null, undefined", "NaN", "if (x) skips"], ["Truthy", "{}, []", "'0', 'false'", "Most objects", "if (x) runs"], "Never assume [] is falsy"),
    ),
    Q(
      "What is immutability and why do people use it?",
      "An immutable value is not changed in place; you produce a new value instead. It makes reasoning, undo, and concurrent reads easier.",
      "Strings are immutable in many languages. Arrays/objects often are not unless you copy. Persistent data structures share structure so copies stay cheap.",
      steps("Change by replacing", [["Read", "Old value stays"], ["Compute", "Build a new one"], ["Swap", "Point the name at it"], ["GC", "Old value can die"]], "Immutable means no silent alias updates"),
    ),
    Q(
      "What is an expression vs a statement?",
      "An expression produces a value (1 + 2, call(), x). A statement does work (if, for, assignment in some languages) and may not yield a value.",
      "Expression-oriented languages (Rust, Scala, Kotlin if) let if return a value. Statement-oriented languages need a variable plus assignment. Ternary is an expression form of if.",
      compare("Value vs action", ["Expression", "Has a result", "Can nest", "1 + foo()", "Used as an argument"], ["Statement", "Control flow", "May be void", "if / for / return", "Cannot always nest"], "If you can put it on the right of =, it is an expression"),
    ),
    Q(
      "What is a side effect?",
      "A side effect is any change besides returning a value: writing a file, updating a global, printing, mutating an argument.",
      "Pure functions are easier to test. Interviews like “this function is not pure because it logs / writes DB.” Isolate effects at the edges of a program.",
      hub("Beyond the return value", "Effect", [["I/O", "Disk, network"], ["Mutate", "Change an object"], ["Global", "Update shared state"], ["Time", "Date.now()"], ["Random", "Math.random()"]], "If two calls with the same args can differ, there is an effect"),
    ),
    Q(
      "What is an exception vs a returned error?",
      "Exceptions abort the normal path until a catch/rescue. Returned errors (Result, errno, nil+err) stay in the type of the function.",
      "Use exceptions for rare, exceptional failure. Use result types when failure is expected (parse, lookup). Swallowing exceptions silently is a red flag.",
      compare("Jump vs value", ["Exception", "Unwinds the stack", "try / catch", "Easy to miss a handler", "Good for bugs / panics"], ["Returned error", "Caller must check", "Result / errno", "Visible in the signature", "Good for expected fail"], "Pick one style and be consistent in a codebase"),
    ),
    Q(
      "How do you debug a failing function?",
      "Reproduce it, shrink the input, check assumptions with logs or a debugger, form a hypothesis, change one thing, re-run.",
      "Print-debugging is valid. Breakpoints show state. Bisect git if it used to work. Read the error — stack traces point at the call chain, not always the root cause.",
      timeline("A simple debug loop", [["Reproduce", "Make it fail on purpose"], ["Isolate", "Smallest input"], ["Observe", "Log or break"], ["Fix", "One change"], ["Verify", "Test still fails?"]], "Guessing without a repro wastes the interview"),
    ),
    Q(
      "What is Big-O at a fundamentals level?",
      "Big-O describes how time or memory grows as input size n grows — ignoring constants. O(1) is bounded work; O(n) scales linearly; O(n²) nested loops over n.",
      "You do not need a proof in a fundamentals round. Count loops and allocations. “This is O(n) because we visit each element once” is the expected sentence.",
      hub("Growth, not exact ms", "Big-O", [["O(1)", "Hash lookup typical"], ["O(log n)", "Binary search"], ["O(n)", "Single pass"], ["O(n log n)", "Good sorts"], ["O(n²)", "Nested n×n"]], "Interviewers want the trend, not a stopwatch"),
    ),
    Q(
      "What is an array vs a list in conversation?",
      "People say “list” loosely. An array is usually a contiguous, indexable block with fixed or resizable length. A linked list is nodes and pointers.",
      "In Python list is a dynamic array. In Java List is an interface (ArrayList vs LinkedList). Ask which structure they mean before quoting complexities.",
      compare("Index block vs nodes", ["Array / vector", "Index in O(1)", "Contiguous memory", "Insert middle is costly", "Great for scans"], ["Linked list", "No cheap random index", "Nodes on the heap", "Insert at cursor is cheap", "Pointer chasing"], "Name the structure — “list” is ambiguous"),
    ),
    Q(
      "What is an API in programming fundamentals?",
      "An API is the set of names, parameters, and promises a module exposes so callers do not need the internals.",
      "A function signature is a tiny API. HTTP APIs are the same idea over the network. Good APIs are small, consistent, and hard to misuse.",
      layers("Contract, not internals", [["Caller", "Uses the names"], ["Signature", "Inputs and outputs"], ["Invariants", "What stays true"], ["Hiding", "Implementation can change"]], "If you can swap the body without breaking callers, you have an API"),
    ),
  ],
  expert: [
    Q(
      "How do lexical scope and dynamic scope differ?",
      "Lexical (static) scope means a name refers to the binding where the function was written. Dynamic scope means it refers to the caller’s environment at run time.",
      "Almost all mainstream languages are lexical. Bash and early Lisp dialects used dynamic scope. Closures only make sense with lexical scope. This is an expert “do you know why closures work” question.",
      compare("Written where vs called from", ["Lexical", "Look at source nesting", "Closures capture locals", "JS, Python, Java, C#", "Predictable"], ["Dynamic", "Look at the call stack", "Callee sees caller locals", "Rare in apps", "Hard to reason"], "If nested functions see outer lets, you are in lexical scope"),
    ),
    Q(
      "What is a closure and what does it capture?",
      "A closure is a function plus the lexical environment it needs. It can use variables from the outer function after that function has returned.",
      "Captured variables live on the heap. Loop-variable capture (var vs let in JS) is a classic bug. Closures keep memory alive — a leak if they hold a huge graph.",
      code("Function that remembers", "make.js", ["function make(n) {", "  return () => n + 1", "}", "const f = make(3)", "f() // 4"], [["Capture", "n outlives make()"], ["Heap", "n is not on the stack"]], "A closure is code + the data it closed over"),
    ),
    Q(
      "What is tail-call optimization and when does it matter?",
      "If the last action of a function is returning a call, a TCO runtime can reuse the frame (constant stack). Without TCO, deep recursion blows the stack.",
      "Scheme requires TCO. Most JS engines do not reliably TCO. Convert tail recursion to a loop when stack depth is unbounded. “Tail position” means nothing after the call.",
      steps("Reuse the frame", [["Last action", "return foo()"], ["No extra work", "After the call"], ["Reuse", "Overwrite this frame"], ["Loop", "Same as iteration"]], "If you need the result to compute more, it is not a tail call"),
    ),
    Q(
      "How do you reason about aliasing and mutation?",
      "Aliasing means two names point at the same mutable object. A write through one is visible through the other. That breaks local reasoning.",
      "Defensive copy, immutability, or exclusive ownership (Rust) control aliasing. Interviews: “after foo(list), is my list changed?” depends on whether foo mutates.",
      hub("Two names, one object", "Alias", [["Share", "Same heap object"], ["Mutate", "Both see it"], ["Copy", "Break the alias"], ["Freeze", "Disallow writes"], ["Own", "Only one writer"]], "If you cannot name the aliases, you cannot debug the write"),
    ),
    Q(
      "What is referential transparency?",
      "An expression is referentially transparent if you can replace it with its value without changing the program. Pure functions enable that.",
      "Logging, time, and mutation break it. It is the foundation of equational reasoning and easy caching. Expert interviews use the term; you can also say “pure and deterministic.”",
      compare("Replace with the value?", ["Transparent", "Same inputs → same out", "No hidden state", "Safe to cache", "Easy to test"], ["Opaque", "Depends on time/IO", "Hidden mutation", "Order matters", "Harder proofs"], "If print(f()) twice can differ, f is not transparent"),
    ),
    Q(
      "How do integer overflow and floating-point surprise you?",
      "Fixed-width integers wrap or throw. IEEE floats cannot represent most decimals exactly; 0.1 + 0.2 !== 0.3 in binary float. Integers above 2^53 are not exact in JS number.",
      "Money should use decimals or integers of cents. Check language rules: wrapping (C), checked (C#), bigint (JS), arbitrary int (Python). NaN infects float math.",
      layers("Number pitfalls", [["Width", "int32 vs int64 vs bigint"], ["Wrap vs throw", "Language-defined"], ["Float", "Binary fractions"], ["NaN / Inf", "Poison values"], ["Money", "Do not use binary float"]], "Say how your language fails — not that “computers are bad at math”"),
    ),
    Q(
      "What is undefined behavior vs implementation-defined?",
      "Undefined behavior (C/C++) means the standard gives no requirements — anything can happen. Implementation-defined means the compiler/runtime must document a choice.",
      "Signed overflow in C is UB; shifting too far is UB. Expert candidates do not say “it wraps” unless they name the language rules. Memory unsafety often starts as UB.",
      compare("No rules vs documented choice", ["Undefined", "Standard is silent", "Optimizers assume it never happens", "Bugs can be time bombs", "Avoid it"], ["Implementation-defined", "Must pick and document", "Varies by compiler", "Still portable with care", "Read the manual"], "UB is not “random” — it is a license for the optimizer"),
    ),
    Q(
      "How do you design a function API that is hard to misuse?",
      "Make illegal states unrepresentable (types, enums). Put units in names or types. Avoid boolean soup. Return results the caller cannot ignore. Keep the happy path obvious.",
      "Examples: Duration instead of int millis; parse() returns Result not a thrown string. Too many optional flags is a smell. This is fundamentals at the design level.",
      steps("Make the right call easy", [["Types", "Ban illegal combos"], ["Names", "Say units and intent"], ["Defaults", "Safe if omitted"], ["Errors", "Visible in the signature"]], "A good API makes the wrong call ugly"),
    ),
    Q(
      "What is the difference between concurrency and parallelism?",
      "Concurrency is structuring a program to deal with many tasks at once (interleaving). Parallelism is running those tasks at the same physical time on multiple cores.",
      "One thread with async I/O is concurrent, not parallel. Four threads on four cores can be both. Interviews fail people who treat the words as synonyms.",
      compare("Structure vs hardware", ["Concurrency", "Many tasks in flight", "Async, threads, events", "Can be 1 core", "About coordination"], ["Parallelism", "Same instant", "Needs extra cores/HW", "Speedup goal", "About execution"], "You can have concurrency without parallelism"),
    ),
    Q(
      "What is a race condition in simple terms?",
      "A race is when the result depends on timing of unsynchronized access to shared mutable state. Two threads incrementing a counter without atomicity can drop updates.",
      "Fix with atomics, locks, or by not sharing. Data races (C++/Java memory model) are a specific undefined/unsafe class. Expert answer names shared + mutable + unsynchronized.",
      hub("The three ingredients", "Race", [["Shared", "Same location"], ["Mutable", "Someone writes"], ["No sync", "No happens-before"], ["Timing", "Scheduler decides"], ["Fix", "Lock, atomic, or copy"]], "If it only fails on Tuesdays, suspect a race"),
    ),
    Q(
      "How does a garbage collector change how you think about memory?",
      "GC reclaims objects with no remaining references. You still manage lifetimes logically (caches, listeners, closures) or you leak. Pause times and generations matter at scale.",
      "RAII/manual free is the other world. Expert: cyclic references with refcounts, finalizers are unreliable, and “GC means no leaks” is false.",
      layers("Reachability, not magic", [["Roots", "Stacks, statics, registers"], ["Trace", "Follow references"], ["Unreachable", "Can collect"], ["Caches", "Can pin forever"], ["Tuning", "Pause vs throughput"]], "GC collects garbage — it does not fix unbounded caches"),
    ),
    Q(
      "What is a type system doing for you at runtime vs compile time?",
      "A static type system rejects some programs before they run. A dynamic system checks when the instruction executes. Gradual typing mixes both (TypeScript erase, Python hints).",
      "Types are not tests. They cannot prove your business logic. They do shrink the state space. Expert: soundness, erasure, and that TS types do not exist at runtime.",
      compare("When the check happens", ["Static", "Compiler / checker", "Refactor confidence", "Zero cost if erased", "May be incomplete"], ["Dynamic", "At the call", "Flexible, late binding", "Runtime cost", "Errors in prod paths"], "Know whether your types survive to production"),
    ),
    Q(
      "How would you explain evaluation strategies: eager vs lazy?",
      "Eager (strict) evaluates arguments before the call. Lazy evaluates them when the value is needed (thunks, generators, Haskell).",
      "Lazy can skip unused work and express infinite streams; it can also hide time/memory costs and repeat work without memoization. Python generators are a practical lazy form.",
      compare("Now vs later", ["Eager", "Args first, then body", "Predictable", "C, Java, JS calls", "Wastes unused work"], ["Lazy", "Wait until needed", "Infinite structures", "Generators, streams", "Harder to profile"], "If the arg is a function you call inside, you invented lazy"),
    ),
    Q(
      "What is idempotence and why do APIs care?",
      "An operation is idempotent if doing it N times has the same effect as doing it once (after the first success). PUT and DELETE in HTTP are designed that way; POST often is not.",
      "Retries need idempotency keys for payments. In code, f(f(x)) = f(x) for functions on a set. Expert fundamentals: retries, at-least-once delivery, and side effects.",
      steps("Safe to retry", [["Send", "Request may drop"], ["Retry", "Client tries again"], ["Same effect", "No double charge"], ["Key", "Dedupe on the server"]], "If a timeout happens, you must know whether retrying is safe"),
    ),
    Q(
      "How do you teach a junior to decompose a problem?",
      "Name the inputs and outputs, write an example, split into functions with one job, pick data structures, then implement and test the seams.",
      "This is an expert communication question. Avoid jumping to code. Make the invariant explicit. If they cannot explain the steps, they cannot debug them.",
      timeline("From prompt to functions", [["Example", "Concrete input/output"], ["Parts", "Name the pieces"], ["Contracts", "Each function’s job"], ["Data", "What you store"], ["Test", "Check the seams"]], "Decomposition is a skill — not a personality trait"),
    ),
  ],
};
