const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Object-Oriented Programming (OOP)",
  slug: "object-oriented-programming-oop",
  description: "Classes, objects, inheritance, polymorphism, abstraction, encapsulation",
  theme: {
    accent: "#ea580c",
    hubFill: "#ea580c",
    hubText: "#ffffff",
    centerFill: "#ffedd5",
    centerStroke: "#ea580c",
    label: "OOP",
  },
  beginner: [
    Q(
      "What is a class?",
      "A class is a blueprint that names a type and defines the fields and methods every instance of that type will have. It is the shared shape, not the live data.",
      "Interviews want fields (state), methods (behavior), and a constructor that builds an instance. Think Dog the type, not Fido the pet. The class is written once; many objects can be made from it.",
      steps("Blueprint, then instances", [["Define", "Name the type"], ["Fields", "What each one stores"], ["Methods", "What each one can do"], ["New", "Build an object from it"]], "A class is the plan — objects are the products"),
    ),
    Q(
      "What is an object?",
      "An object is a live instance of a class: its own field values plus the methods defined on that class. Two objects of the same class can hold different data.",
      "Identity (this exact instance) is not the same as equal values. Interviews: object = state + behavior + identity. The class is shared; each object has its own data.",
      hub("A live instance", "Object", [["State", "Field values now"], ["Behavior", "Methods it can run"], ["Identity", "This instance, not a copy"], ["Type", "Which class it is"], ["Lifetime", "Until nothing refers to it"]], "The class is shared — each object has its own data"),
    ),
    Q(
      "What is a constructor?",
      "A constructor is special setup code that runs when you create an object. It initializes fields so the instance starts in a valid state.",
      "If you skip initialization, fields are defaults (0, null, undefined) and bugs follow. Overloads let you construct with different argument lists. Interviews want: runs at new, sets invariants.",
      steps("Build a valid instance", [["Allocate", "Make the object"], ["Call", "Run the constructor"], ["Init", "Set fields / invariants"], ["Return", "Hand the instance back"]], "A constructor's job is a legal starting state"),
    ),
    Q(
      "What is the difference between a class and an object?",
      "A class is the definition (type, fields, methods). An object is one concrete instance created from that class.",
      "You usually have one class and many objects. Static members belong to the class; instance members belong to each object. Saying \"the class holds the name Fido\" is the classic mix-up.",
      compare("Plan vs product", ["Class", "One blueprint", "Defines the shape", "Shared by instances", "Dog, User, Invoice"], ["Object", "One instance", "Holds real values", "Own copy of fields", "fido, currentUser"], "Class is the cookie cutter — object is the cookie"),
    ),
    Q(
      "What is a method?",
      "A method is a function defined on a class that runs in the context of an object (or the class, if static). Instance methods can read and update this or self.",
      "Interviews distinguish methods from free functions: the receiver is an extra implicit argument. Keep methods focused on one job. Static methods are the exception that skip the instance.",
      code("Behavior on a type", "Dog.js", ["class Dog {", "  bark() {", "    return this.name + ' woofs'", "  }", "}"], [["Receiver", "this is the dog"], ["Call", "fido.bark()"]], "A method is a function that belongs to a type"),
    ),
    Q(
      "What is a field (instance variable)?",
      "A field is named storage on each object — the data that makes one instance different from another. Fields are state; methods are behavior.",
      "Public fields break encapsulation. Prefer private fields plus methods that preserve invariants (balance never negative, name never null). Two objects share field names, not field values.",
      layers("State on the instance", [["Class", "Declares the field names"], ["Object A", "Its own values"], ["Object B", "Different values, same shape"], ["Methods", "Read and update those fields"]], "Fields are per-object data, not the class itself"),
    ),
    Q(
      "What is encapsulation?",
      "Encapsulation hides internal data and exposes a small, safe API so callers cannot break the object's rules. Private fields plus public methods is the usual form.",
      "It is not just \"use getters.\" The point is protecting invariants and letting you change internals later. Interviews fail \"hiding for hiding's sake.\"",
      hub("Hide internals, expose a contract", "Hide", [["Private", "Fields stay inside"], ["API", "Few public methods"], ["Invariant", "Rules always hold"], ["Change", "Internals can move"], ["Misuse", "Illegal states are hard"]], "Encapsulation is control of who can touch what"),
    ),
    Q(
      "What is inheritance?",
      "Inheritance lets a class reuse and extend another class's fields and methods — a subclass is a more specific kind of the parent. Use it for true is-a relationships.",
      "Square is a Rectangle is often a lie. Subclasses should not fight the parent's invariants. Prefer composition when you only want to reuse code.",
      layers("Specialize a type", [["Base", "Shared fields and methods"], ["Derived", "Adds or overrides"], ["Is-a", "Can be used as the parent"], ["Reuse", "Do not copy-paste the parent"]], "Inheritance is \"a kind of,\" not \"I needed those methods\""),
    ),
    Q(
      "What is polymorphism?",
      "Polymorphism means the same call (same method name on a parent type) can run different code depending on the actual object's class. A list of Shape can each draw() as Circle or Square.",
      "Subtype polymorphism is the OOP interview meaning. Overloading is ad-hoc polymorphism — related word, different mechanism. Dynamic dispatch picks the override at run time.",
      compare("One call, many bodies", ["Same name", "draw() on Shape", "Caller uses the parent type", "No giant if/else on type", "Add a new subclass later"], ["Different code", "Circle.draw vs Square.draw", "Picked from the real class", "Virtual / override", "The object decides"], "Callers program to the interface — instances pick the implementation"),
    ),
    Q(
      "What is abstraction?",
      "Abstraction shows the essential operations and hides the messy details — a Shape that can draw() without exposing pixels and buffers. Abstract classes and interfaces are tools for it.",
      "Too much abstraction (interfaces for every class) is noise. Encapsulation hides data; abstraction hides complexity behind a simpler idea. Interviews want that distinction out loud.",
      hub("Essential idea, fewer details", "Idea", [["Name", "Shape, not pixels"], ["Ops", "draw, area, bounds"], ["Hide", "How paint works"], ["Many", "Circle, Square, ..."], ["Stable", "Callers stay simple"]], "Abstraction is a useful lie about complexity"),
    ),
    Q(
      "What does this (or self) refer to?",
      "this (self in Python) is the object the method was called on — the receiver of the current call. In constructors it is the instance being built.",
      "Arrow functions in JS do not bind their own this. Interviews: this is not \"the class\"; it is one object. Losing this in callbacks is a classic bug.",
      code("The receiver of the call", "user.js", ["class User {", "  hi() {", "    return this.name", "  }", "}", "u.hi()"], [["this", "The object u"], ["Call", "u.hi() sets the receiver"]], "this is the instance, not the class definition"),
    ),
    Q(
      "What is the difference between a static method and an instance method?",
      "An instance method needs an object and can use this. A static method belongs to the class and has no instance fields unless you pass an object in.",
      "Use static for factories, helpers, and operations that do not need per-object state. Math.max is static-shaped. Interviews flag static that secretly uses globals — that is not OO, that is a namespace.",
      compare("Needs an instance?", ["Instance", "Called on an object", "Can read this.fields", "user.save()", "Default for behavior"], ["Static", "Called on the class", "No this (usually)", "User.find(id)", "Good for factories"], "If it needs the object's data, it is not static"),
    ),
    Q(
      "What do public, private, and protected mean?",
      "Public is callable from anywhere; private is only inside the class. Protected is the class plus subclasses (and sometimes the package).",
      "Languages differ: Python uses a naming convention; JS has hash-private fields; Java has package-private as the default. Interviews want: pick the tightest visibility that still works. Private by default is the safe habit.",
      layers("Who can touch it", [["Public", "Any caller"], ["Protected", "This class and subclasses"], ["Package", "Same module / package (some languages)"], ["Private", "Only this class's code"]], "Visibility is encapsulation you can enforce"),
    ),
    Q(
      "What is method overloading?",
      "Overloading is several methods with the same name and different parameter lists, resolved at compile time from the call's argument types. It is not polymorphism of subclasses.",
      "Java and C# overload; Python and JS typically do not (one name, one function). Return type alone usually cannot distinguish overloads. Keep overload sets small and obvious.",
      steps("Same name, different args", [["Name", "print, of, from"], ["Sigs", "Different params"], ["Call", "Compiler picks a match"], ["Not override", "No subclass required"]], "Overload is compile-time choice — override is run-time"),
    ),
    Q(
      "What happens when you create an object with new?",
      "The runtime allocates the instance, runs constructors from the base class down to yours, then returns the object. If construction throws, you do not get a usable instance.",
      "Fields get default values first, then initializers, then constructor bodies — order matters in Java and C#. If a constructor calls an overridable method, a subclass override can run before the subclass is initialized — a famous footgun.",
      cycle("From new to a live object", "new", [["Allocate", "Empty instance"], ["Base ctor", "Parents first"], ["Init", "Fields and body"], ["Ready", "Return the object"]], "Construction is a sequence — not a single assignment"),
    ),
  ],
  intermediate: [
    Q(
      "What is the difference between an interface and an abstract class?",
      "An interface is a contract of operations (and sometimes defaults) with no instance state. An abstract class can hold fields, constructors, and partial implementation.",
      "A class can implement many interfaces but usually extend only one class. Use an abstract class when subclasses share state or a template algorithm. Use an interface when you only need a capability (Comparable, Drawable).",
      compare("Contract vs partial type", ["Interface", "No (or little) state", "Many per class", "Capability: can-do", "Stable for callers"], ["Abstract class", "Can have fields", "Single parent", "Shared algorithm / state", "Heavier coupling"], "Interface = can; abstract class = is, with some code filled in"),
    ),
    Q(
      "When do you choose composition over inheritance?",
      "Prefer composition (has-a: hold a helper object) when you want reuse without being a subtype. Prefer inheritance only for a true is-a that will honor the parent's contract.",
      "Inheritance couples you to the parent's internals and fragile overrides. Composition lets you swap strategies and test with fakes. \"I subclassed to get logging\" is the wrong reason — wrap instead.",
      compare("Has-a vs is-a", ["Composition", "Hold a collaborator", "Swap at runtime", "No LSP duty to a parent", "Easier tests"], ["Inheritance", "You are that type", "Fixed at compile time", "Must keep parent promises", "Reuse + substitution"], "Reuse code with a field — reuse type with a subclass"),
    ),
    Q(
      "What is the difference between overriding and overloading?",
      "Overriding replaces a parent method in a subclass; the call is chosen at run time from the actual type. Overloading is same name, different parameters, chosen at compile time.",
      "Override needs the same signature (or a compatible one) and is polymorphism. Hide or shadow is not override. Interviews love: which method runs if the variable is typed as the parent.",
      compare("When is the body chosen?", ["Override", "Subclass replaces parent", "Same signature", "Run-time type", "virtual / override"], ["Overload", "Same class (usually)", "Different params", "Compile-time types", "No subclass needed"], "If the variable type changes which overload, it is not virtual dispatch"),
    ),
    Q(
      "What is an abstract class for?",
      "An abstract class cannot be constructed itself. It exists to share fields and methods and to force subclasses to fill in abstract methods.",
      "Template Method lives here: the base class owns the algorithm, subclasses supply steps. If you have no shared code or state, an interface is usually enough. Abstract plus new AbstractFoo() is a compile error by design.",
      hub("Shared core, holes to fill", "Abstract", [["No new", "Cannot instantiate"], ["Fields", "Shared state OK"], ["Concrete", "Methods with bodies"], ["Abstract", "Subclass must implement"], ["Template", "Algorithm in the base"]], "Abstract means \"incomplete type on purpose\""),
    ),
    Q(
      "What is an interface in OOP?",
      "An interface names a set of methods a type must provide so callers can depend on the capability, not a concrete class. It enables polymorphism without a shared parent class.",
      "Default methods (Java) blur the line with abstract classes — still avoid putting state in interfaces. Interviews: program to an interface, inject the implementation. The interface is the plug shape; classes are the plugs.",
      layers("A capability others implement", [["Caller", "Depends on the interface"], ["Contract", "Method names and meaning"], ["Impl A", "One class fulfills it"], ["Impl B", "Another class, same calls"]], "The interface is the plug shape — classes are the plugs"),
    ),
    Q(
      "What does super do in a constructor or method?",
      "In a constructor, super(...) runs the parent constructor first so inherited fields exist. In a method, super.foo() calls the parent version you overrode.",
      "Languages often require super() as the first constructor statement. Forgetting it (when the parent has no no-arg constructor) fails to compile. Calling overridable methods from a constructor still bypasses the subclass's own setup.",
      steps("Parent first, then you", [["Child new", "Subclass constructor starts"], ["super()", "Parent constructor runs"], ["Fields", "Your fields initialize"], ["Body", "Rest of your constructor"]], "super is the explicit link to the parent's setup or method"),
    ),
    Q(
      "What is dynamic (virtual) dispatch?",
      "Dynamic dispatch picks which override to run using the object's real class at run time, not the type of the variable you called through. Shape s = new Circle(); s.draw() runs Circle.draw.",
      "Static methods, privates, and overloads are not dispatched this way. This is the mechanism behind subtype polymorphism in Java, C#, and C++ virtual. The object's class wins, not the reference's declared type.",
      cycle("Call site to real method", "Call", [["Static type", "What the variable is"], ["Real class", "What the object is"], ["Lookup", "Find the override"], ["Run", "That body executes"]], "The object's class wins — not the reference's declared type"),
    ),
    Q(
      "Are getters and setters the same as encapsulation?",
      "No — a public get/set pair for every field is still a leaky data bag. Encapsulation means you expose operations that keep invariants, not every field.",
      "Setters that accept anything are public fields with extra typing. Prefer behavior: withdraw(amount) instead of setBalance. Immutable objects often have getters only, or none if you only need methods.",
      code("Behavior, not a field dump", "account.js", ["class Account {", "  withdraw(n) {", "    if (n > this.bal) throw", "    this.bal -= n", "  }", "}"], [["Not", "setBalance(any)"], ["Yes", "Rules live in the method"]], "Encapsulation is a policy — getters are just accessors"),
    ),
    Q(
      "What is the difference between is-a and has-a?",
      "Is-a is inheritance or subtyping: a Circle is a Shape. Has-a is composition: a Car has an Engine.",
      "If you cannot honestly say the subclass is substitutable for the parent, it is not is-a. \"Stack is-a Vector\" was a famous Java mistake — a stack is not a vector. Prefer has-a when the relationship is ownership or use, not kind.",
      compare("Kind of vs contains", ["Is-a", "Subtype / extends", "Must honor LSP", "Circle is a Shape", "Use inheritance"], ["Has-a", "Field / collaborator", "No subtype duty", "Car has Engine", "Use composition"], "If it \"has\" a part, do not extend the part"),
    ),
    Q(
      "Why do many languages forbid multiple class inheritance?",
      "Two parents can define the same method or field, so the compiler cannot pick a unique meaning. The diamond problem is the usual example.",
      "Interfaces (or traits and mixins with rules) give multiple capabilities without two full implementation hierarchies. C++ allows multiple inheritance and pays with complexity. Interviews: name the ambiguity, then say how your language avoids it.",
      hub("Two parents, one child", "Clash", [["Names", "Same method twice"], ["State", "Whose field?"], ["Ctor", "Which parent first?"], ["Diamond", "Shared grandparent twice"], ["Fix", "One class parent"]], "Multiple capabilities: yes. Two implementation parents: usually no"),
    ),
    Q(
      "How does immutability show up in OOP?",
      "An immutable object never changes its fields after construction; \"updates\" return a new instance. Callers can share it without defensive copies.",
      "Final or readonly fields, no setters, and constructors that copy incoming collections are the usual recipe. Strings and value objects work this way. Interviews: immutability is a design choice, not the opposite of OOP.",
      steps("Freeze after new", [["Construct", "Set all fields"], ["No setters", "Cannot reassign"], ["Copy in", "Do not keep caller lists"], ["Share", "Safe to alias"]], "If two names point at it, neither can surprise the other"),
    ),
    Q(
      "What is association vs aggregation vs composition?",
      "Association is objects that know each other. Aggregation is a whole-part that can live apart; composition is a whole-part whose part dies with the whole.",
      "These UML words are fuzzy in interviews — say ownership and lifetime. A university aggregates students (students exist anyway); a house composes rooms (rooms are not independent). Prefer code: who constructs, who stores, who disposes.",
      layers("How tightly are they tied?", [["Association", "Uses / knows, no ownership"], ["Aggregation", "Part can outlive the whole"], ["Composition", "Part lifetime tied to whole"], ["Code", "Who news and who nulls"]], "Talk lifetime and ownership — the three nouns are optional"),
    ),
    Q(
      "What is object identity vs equality?",
      "Identity asks whether this is the same instance (reference compare). Equality asks whether these count as the same value (equals, or a value compare).",
      "Override equals and hashCode together or maps break. Mutable objects as hash keys are a trap. Interviews: == vs equals in Java; === vs value compare in others; value objects usually equal by fields.",
      compare("Same pointer vs same meaning", ["Identity", "Same instance", "=== / reference", "Fast, unique", "this == other"], ["Equality", "Same value", "equals / value ==", "Must define it", "Two $10 bills"], "Sets and maps care which one you meant"),
    ),
    Q(
      "How does class-based OOP differ from prototype-based OOP?",
      "Class-based languages (Java, C#) create objects from a class. Prototype-based languages (JS historically) clone and link to another object as the prototype.",
      "JS now has class syntax, but it still uses prototypes under the hood. Interviews: instanceof vs prototype chain; Object.create. You can do OOP without a class keyword — the chain of delegation is the model.",
      timeline("Two ways to share behavior", [["Class", "Type is declared first"], ["Instance", "new fills the shape"], ["Prototype", "Object links to another object"], ["Delegate", "Missing names walk the chain"], ["class in JS", "Sugar over prototypes"]], "Classes are types; prototypes are objects that other objects consult"),
    ),
    Q(
      "What is a factory method compared with a public constructor?",
      "A constructor always returns a new instance of that exact class. A factory is a method (often static) that can choose a subclass, cache, or fail more clearly.",
      "Examples: Color.rgb(...), List.of(...), parse that returns Optional. Named factories beat constructor overloads that only differ by int vs int. Hide constructors when you need control of creation.",
      code("Create without new at the call site", "shape.js", ["static from(kind) {", "  if (kind === 'c') return new Circle()", "  return new Square()", "}"], [["Choice", "Which subclass"], ["Hide", "new stays inside"]], "Factories return a type — constructors return this class only"),
    ),
  ],
  expert: [
    Q(
      "What does SOLID mean in OOP design?",
      "SOLID is five design heuristics: single responsibility, open-closed, Liskov substitution, interface segregation, and dependency inversion. They aim at change without breaking callers.",
      "They are guidelines, not laws. Interviews want a one-line each and a concrete example, not the acronym only. Over-applying SOLID produces a forest of one-method classes — that is not expert, that is cargo cult.",
      hub("Five change-friendly habits", "SOLID", [["S", "One reason to change"], ["O", "Extend, do not edit"], ["L", "Subtypes keep promises"], ["I", "Small interfaces"], ["D", "Depend on abstractions"]], "SOLID is about safe change — not more classes for their own sake"),
    ),
    Q(
      "What is the Single Responsibility Principle?",
      "A class should have one reason to change: one job or one actor it serves, not a one-method count. A User class that persists, emails, and validates tax IDs will churn for three unrelated reasons.",
      "Split persistence, notifications, and rules. Expert interviews: SRP is about cohesion and who requests the change, not method count. If two teams keep colliding in one file, SRP is already broken.",
      steps("One reason to change", [["Name the actor", "Who asks for edits?"], ["List jobs", "Persist, email, tax"], ["Split", "One class per job"], ["Wire", "Compose them"]], "If two teams keep colliding in one file, SRP is already broken"),
    ),
    Q(
      "What is the Open-Closed Principle?",
      "Software entities should be open for extension and closed for modification. Add a new subtype or strategy without editing the old switch.",
      "Polymorphism and Strategy are the usual tools. You still change code when the abstraction is wrong — OCP is not \"never touch a file.\" Plugins, new Shape subclasses, and new Discount rules are the examples interviewers want.",
      compare("Add vs edit the old module", ["Open", "New subclass / strategy", "New behavior plugs in", "Old callers unchanged", "Seams: interface, hook"], ["Closed", "Do not rewrite the switch", "Stable published API", "Less regression risk", "Not \"never refactor\""], "Extend at a seam — do not keep grafting ifs onto a core module"),
    ),
    Q(
      "What is the Liskov Substitution Principle?",
      "Subtypes must be usable wherever the parent is expected. They keep preconditions no stronger, postconditions no weaker, and invariants intact.",
      "Square extending Rectangle fails if setters let width and height differ. Throwing Unsupporteds in a subclass that the parent allowed is an LSP break. Expert: behavioral subtyping, not \"it compiles as a child.\"",
      compare("Compiles vs substitutable", ["Looks like a subtype", "extends / implements", "Same method names", "Type checker is happy", "Not enough"], ["LSP holds", "Callers not surprised", "No extra throws", "Invariants kept", "History: Square/Rectangle"], "If the parent's tests fail on the child, it is not a subtype"),
    ),
    Q(
      "What is the Interface Segregation Principle?",
      "Clients should not be forced to depend on methods they do not use. Split fat interfaces so callers see only what they need.",
      "A Worker interface with work() and eat() forces robots to stub eat(). Split Workable and Eatable. ISP is about the caller's view — a large interface is fine if every client uses all of it.",
      hub("Small surfaces for callers", "ISP", [["Fat", "One huge interface"], ["Stub", "Empty / throw methods"], ["Split", "Role interfaces"], ["Caller", "Depends on less"], ["Change", "Fewer accidental breaks"]], "Do not make a robot implement lunch"),
    ),
    Q(
      "What is Dependency Inversion?",
      "High-level policy should depend on abstractions, not on concrete low-level details. Both sides depend on the interface; the concrete class is plugged in.",
      "A ReportService should depend on a Store interface, not MysqlStore. DI containers are optional — the principle is the direction of the dependency. Expert: invert ownership of the interface toward the consumer.",
      layers("Who depends on whom", [["Policy", "Report, checkout, game rules"], ["Abstraction", "Interface the policy owns"], ["Detail", "SQL, SMTP, file"], ["Wiring", "Compose at the edge"]], "The business rule does not import the database class"),
    ),
    Q(
      "How does virtual dispatch work at the machine level?",
      "Each object carries a type pointer (vtable or class pointer). A virtual call loads that table and jumps to the function pointer for that method slot.",
      "Direct calls can be inlined; virtual calls need the real type (or a guarded devirtualization). Multiple interfaces may use extra itables. Expert interviews: this is why private, static, and final are not polymorphic, and why constructors plus virtuals are dangerous.",
      steps("From call to jump", [["Object", "Has a type pointer"], ["Vtable", "Per-class method list"], ["Slot", "Index for draw()"], ["Jump", "Run that function"]], "Virtual means \"look up the function on the object's class\""),
    ),
    Q(
      "What is the diamond problem?",
      "If D inherits from B and C, and both inherit from A, D can inherit two copies of A's state or two versions of the same method. The compiler cannot pick uniquely.",
      "C++ needs virtual inheritance to share one A. Java and C# avoid it for classes; interfaces with defaults reintroduce a milder form (must override the clash). Name the two paths and the ambiguity — that is the answer.",
      hub("A at the top, D at the bottom", "A", [["B", "Inherits A"], ["C", "Inherits A"], ["D", "Inherits B and C"], ["State", "One A or two?"], ["Method", "Which override?"]], "Two paths to the same ancestor is the diamond"),
    ),
    Q(
      "What is the fragile base class problem?",
      "A change in a parent class (even a \"safe\" bugfix) can break subclasses that overrode methods or relied on call order the parent never promised. Inheritance leaks implementation, not just types.",
      "Prefer composition, final methods, or documented extension points. Expert: this is why libraries seal classes and why \"open for override\" is a published API. If subclasses depend on how, not just what, the base is fragile.",
      layers("Parent change, child surprise", [["Base edit", "New call in a method"], ["Override", "Child assumed old flow"], ["Invariant", "Child breaks silently"], ["Seal", "Limit who can extend"], ["Compose", "Avoid the coupling"]], "If subclasses depend on how, not just what, the base is fragile"),
    ),
    Q(
      "What are covariance and contravariance in OOP APIs?",
      "Covariance lets a subtype appear where a wider type was expected (return a more specific type). Contravariance lets a consumer accept a wider argument than the parent's method.",
      "Java arrays are covariant and unsound (an Animal array that is really Cats). Generics need wildcards (extends vs super). Function types: returns are covariant, parameters contravariant — PECS: producer extends, consumer super.",
      compare("Direction of the type", ["Covariant", "Narrower is OK out", "Return Circle as Shape", "List of cats as animals? careful", "Producers"], ["Contravariant", "Wider is OK in", "Compare Animals, use on Cats", "Consumers of values", "Parameters"], "Out positions want subclasses — in positions want superclasses"),
    ),
    Q(
      "How do you design immutable objects in an OOP language?",
      "All fields final or readonly, no mutator methods, defensive copies of mutable inputs and outputs, and equals/hashCode based on values. A change means return a copy.",
      "Share freely across threads, but watch hidden mutation (lists you stored from the caller). Records, case classes, and value objects are the pattern. Expert: identity is irrelevant; two value objects with the same fields are interchangeable.",
      code("Copy, do not mutate", "money.js", ["class Money {", "  constructor(cents) {", "    this.cents = cents", "  }", "  add(n) {", "    return new Money(this.cents + n)", "  }", "}"], [["No set", "cents never changes"], ["New", "add returns another Money"]], "Immutable OOP is still OOP — the methods return new objects"),
    ),
    Q(
      "How do mixins, traits, and interfaces differ?",
      "Interfaces are contracts (plus optional defaults). Mixins and traits both reuse methods, but mixins often paste state and clash, while traits compose with explicit conflict rules.",
      "JS mixins mutate prototypes; that is brittle. Java default methods are a limited mixin. Expert: say how conflicts resolve and whether state is allowed — that is the real distinction, not the buzzword.",
      hub("Reuse without a single parent", "Reuse", [["Interface", "Can-do contract"], ["Default", "Shared body, little state"], ["Mixin", "Paste behavior in"], ["Trait", "Compose + resolve clashes"], ["Risk", "Name collisions"]], "Multiple behavior sources need a conflict story"),
    ),
    Q(
      "How should you think about object lifetime in OOP?",
      "Who creates the object, who owns it, and who releases it (GC, RAII, dispose). Leaks are leftover graphs: listeners, caches, static maps, closures.",
      "RAII (C++) ties cleanup to a destructor on the stack; IDisposable/using is the explicit cousin. GC does not replace unsubscribe. Expert interviews: composition's \"dies with the whole\" is a lifetime rule, not a UML decoration.",
      timeline("From new to gone", [["Create", "Who calls new / factory"], ["Own", "Who stores the reference"], ["Use", "Who may call methods"], ["Release", "Drop refs / dispose"], ["Collect", "GC or destructor"]], "If you cannot name the owner, you cannot name the leak"),
    ),
    Q(
      "When is OOP the wrong tool?",
      "When the problem is data transformation, a pipeline, or a closed set of operations on many types, a functional or procedural style is often clearer. Tiny scripts and numeric kernels do not need class hierarchies.",
      "Expression problem: OOP makes adding types easy and adding operations hard; FP is the reverse. Expert: pick the axis of change, then pick the paradigm. If every class is a bag of fields, you gained ceremony, not OOP.",
      compare("What will change later?", ["OOP shines", "New types, same ops", "Shape.draw, new Circle", "State + identity matter", "Plugin subtypes"], ["OOP hurts", "New ops, fixed types", "Deep fragile trees", "Anemic get/set bags", "A function would do"], "If every class is a bag of fields, you did not gain OOP — you gained ceremony"),
    ),
    Q(
      "How do Template Method and Strategy differ?",
      "Template Method puts the algorithm in a base class and lets subclasses fill steps (inheritance). Strategy puts the varying step in a separate object you compose (has-a).",
      "Strategy is easier to swap at runtime and to test. Template Method is fine for a small closed family. Expert: this is composition vs inheritance applied to algorithms — name the coupling.",
      cycle("Who owns the algorithm?", "Algo", [["Template", "Base class skeleton"], ["Hook", "Subclass fills a step"], ["Strategy", "Object in a field"], ["Swap", "Inject a different strategy"]], "Inheritance for the skeleton — composition for the interchangeable part"),
    ),
  ],
};
