const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Security & Authentication",
  slug: "security-authentication",
  description: "JWT, OAuth, HTTPS, authentication, authorization, common vulnerabilities",
  theme: {
    accent: "#dc2626",
    hubFill: "#dc2626",
    hubText: "#ffffff",
    centerFill: "#fee2e2",
    centerStroke: "#dc2626",
    label: "Sec",
  },
  beginner: [
    Q(
      "What is the difference between authentication and authorization?",
      "Authentication proves who you are. Authorization decides what you are allowed to do after that.",
      "Login is authentication. Can this user delete invoice 44? is authorization. Interviews fail people who treat them as one word. You can be authenticated and still forbidden.",
      compare("Who vs what", ["Authentication", "Prove identity", "Password, OTP, passkey", "Session or token issued", "401 if missing / wrong"], ["Authorization", "Check permission", "Roles, policies, ACLs", "After you are known", "403 if known but denied"], "401 is who — 403 is what"),
    ),
    Q(
      "What does HTTPS / TLS do?",
      "TLS encrypts the bytes on the wire, authenticates the server (via certificates), and detects tampering. HTTPS is HTTP over TLS.",
      "Without TLS, passwords and cookies are readable on the path. Interviewers want confidentiality, integrity, and server authenticity — not HTTPS makes it secure as the whole answer.",
      layers("What TLS gives you", [["Encrypt", "Snoopers see ciphertext"], ["Integrity", "Tamper is detected"], ["Server auth", "Cert matches the host"], ["Not", "Your app bugs stay"]], "TLS protects the pipe — not the business logic"),
    ),
    Q(
      "What is a JWT?",
      "A JSON Web Token is a signed (sometimes encrypted) string with a header, payload, and signature. The receiver can verify it without calling the issuer every time.",
      "Typical claims: sub, exp, iat, roles. Anyone can read a signed JWT payload — do not put secrets in it. Interviews want: signed claims, expiry, and verify the signature with the right key.",
      hub("Three parts", "JWT", [["Header", "alg and typ"], ["Payload", "Claims (sub, exp)"], ["Signature", "Proves issuer"], ["Verify", "Key plus alg"], ["Exp", "Reject when stale"]], "A JWT is a signed postcard — readable, not secret"),
    ),
    Q(
      "What is a session?",
      "A session is server-side state that remembers a logged-in user. The browser holds a session id, usually in a cookie, and sends it on later requests.",
      "The id must be random and unguessable. The server looks up the session store. Contrast with stateless JWTs. Interviews: steal the cookie, steal the session.",
      steps("Cookie points at state", [["Login", "Check credentials"], ["Create", "Store session server-side"], ["Send", "Set-Cookie with the id"], ["Reuse", "Browser sends it back"]], "The cookie is a pointer — the truth lives on the server"),
    ),
    Q(
      "Why hash passwords instead of encrypting or storing them plain?",
      "Hashing is one-way: you store a hash and compare hashes at login. Encryption is two-way — if the key leaks, every password is readable.",
      "Use a slow password hash (Argon2, bcrypt, scrypt) with a unique salt. Never SHA-256 alone for passwords. Plain text is an instant fail in interviews.",
      compare("One-way vs reversible", ["Password hash", "Cannot get the password back", "Slow on purpose", "Salt per user", "Compare hashes"], ["Encryption", "Key decrypts it", "Fine for secrets at rest", "Wrong for passwords", "Key leak = all users"], "If you can email me my password, you stored it wrong"),
    ),
    Q(
      "What is XSS?",
      "Cross-site scripting is when an attacker injects script into a page that other users' browsers will run, usually by storing or reflecting untrusted HTML.",
      "Stored XSS sits in the database. Reflected XSS rides on a URL. DOM XSS writes into the page in JavaScript. Fix: encode output, avoid innerHTML, use a CSP. Interviews: cookie theft via document.cookie.",
      code("Untrusted string in HTML", "page.js", ["el.innerHTML = user.name", "// name is <script>...", "steal(document.cookie)"], [["Sink", "innerHTML"], ["Fix", "textContent or encode"]], "The browser trusts your HTML — do not feed it the user"),
    ),
    Q(
      "What is CSRF?",
      "Cross-site request forgery tricks a logged-in browser into sending a state-changing request to your site using the user's cookies.",
      "The victim is already authenticated. The attacker did not steal the password — they borrowed the cookie. Defenses: SameSite cookies, anti-CSRF tokens, and not using cookies for APIs that accept bearer tokens.",
      timeline("Forged click", [["Login", "User has your cookie"], ["Visit", "Evil page in another tab"], ["Forge", "Form or fetch to your API"], ["Browser", "Sends the cookie"], ["Damage", "Transfer, email change"]], "CSRF rides the cookie — it does not need the password"),
    ),
    Q(
      "What is SQL injection?",
      "SQL injection is when untrusted input is concatenated into a query so the attacker can change the SQL — read rows, skip auth, or drop tables.",
      "Classic: ' OR 1=1 --. Fix: parameterized queries / bind variables, never string-build SQL. ORMs still need care with raw(). Interviews want a one-line exploit plus the parameterized fix.",
      code("String-built SQL", "login.sql", ["q = \"SELECT * FROM users WHERE name='\"", " + name + \"'\""], [["Concat", "name becomes SQL"], ["Fix", "Parameters / bind"]], "If the user can change the query, they own the database"),
    ),
    Q(
      "What is the OWASP Top 10?",
      "The OWASP Top 10 is a widely used list of the most critical web application risks — a design and review checklist, not a law.",
      "It includes injection, broken access control, cryptographic failures, XSS-related issues, and more; the list updates. Interviews: name a few and how you would prevent them, not recite all ten from memory.",
      hub("Risks to design against", "OWASP", [["Access", "IDOR / missing checks"], ["Crypto", "Bad hashing / TLS"], ["Inject", "SQL, OS, LDAP"], ["Design", "No threat model"], ["Config", "Defaults and secrets"]], "Top 10 is a map — not a score"),
    ),
    Q(
      "What is least privilege?",
      "Least privilege means each user, service, and token gets only the permissions it needs to do its job — nothing extra.",
      "Admin for everyone is the opposite. Apply it to DB accounts, cloud IAM, API scopes, and file permissions. Interviews: if this token leaks, what can it still do?",
      layers("Shrink what a leak can do", [["Human", "Role matches the job"], ["Service", "One task, one identity"], ["Token", "Narrow scopes, short life"], ["Data", "Row- and field-level where needed"]], "If it does not need it, it must not have it"),
    ),
    Q(
      "What is a secret in an application?",
      "A secret is a credential the app must not put in source control or logs: API keys, private keys, DB passwords, signing keys, tokens.",
      "Store in a vault or platform secret store, inject at runtime, rotate. Git history counts as leaked. Interviews: .env in the repo is a fail.",
      hub("Things that must not ship", "Secret", [["Keys", "JWT / TLS private"], ["Passwords", "DB and admin"], ["Tokens", "Third-party APIs"], ["Where", "Vault, not git"], ["Logs", "Redact them"]], "If it is in the repo, treat it as public"),
    ),
    Q(
      "What is CORS?",
      "Cross-Origin Resource Sharing is a browser rule: a page on origin A may call origin B only if B's response allows it with CORS headers.",
      "CORS is enforced by the browser, not by curl. It is not an access-control system for your API. Interviews mix CORS with CSRF constantly — they solve different problems.",
      compare("Browser gate vs auth", ["CORS", "Which sites may read the response", "Access-Control-* headers", "Bypassed by non-browsers", "Stops JS on other origins"], ["Auth", "Who is this caller", "Tokens or cookies", "Must exist on the server", "Stops everyone"], "CORS is not a lock on the API — it is a browser courtesy"),
    ),
    Q(
      "What is the difference between session cookies and tokens at a beginner level?",
      "A session cookie is an id the server looks up. A token (often a JWT) carries claims the server can verify locally. Both prove a login; they store state in different places.",
      "Cookies are sent automatically by the browser (CSRF risk). Bearer tokens are sent on purpose (XSS risk if stored in JS). Interviews want that tradeoff, not JWT is more secure.",
      compare("Where the login lives", ["Session cookie", "Id in cookie", "State on the server", "Easy to revoke", "CSRF if cookie auto-sent"], ["Token", "Claims in the string", "Often stateless verify", "Revoke is harder", "XSS if JS can read it"], "Revocation and theft path matter more than the acronym"),
    ),
    Q(
      "What is OAuth 2.0 in one sentence?",
      "OAuth 2.0 is a way for a user to grant an application limited access to another service without giving that application the user's password.",
      "Login with Google is often OAuth plus OpenID Connect. OAuth is authorization (access tokens); OIDC adds identity (ID token). Interviews: do not say OAuth is encryption.",
      steps("Grant access, not the password", [["User", "Wants app A to use B"], ["Consent", "B asks the user"], ["Code", "A receives a grant"], ["Token", "A calls B's API"]], "OAuth shares a token — never the password"),
    ),
    Q(
      "Why is HTTP without TLS a problem for login?",
      "On plain HTTP, anyone on the path can read or change the request, including passwords, cookies, and JWT headers.",
      "Public Wi-Fi is the usual story. Mixed content (HTTPS page, HTTP API) is also a fail. HSTS tells browsers to refuse HTTP next time. Interviews: TLS first, then app auth.",
      compare("Clear vs wrapped", ["HTTP", "Readable on the wire", "Cookies stealable", "Easy to tamper", "No server proof"], ["HTTPS", "Encrypted in transit", "Harder to sniff", "Integrity checks", "Cert for the host"], "Auth over HTTP is a postcard with a password on it"),
    ),
  ],
  intermediate: [
    Q(
      "How does JWT authentication work end to end?",
      "The client sends credentials, the issuer signs a JWT, the client stores it, then each request sends Authorization: Bearer. The API verifies signature, issuer, audience, and expiry, then trusts the claims.",
      "Access tokens stay short-lived. Put identity in claims, not secrets. Clock skew and alg confusion are classic bugs. Interviews walk this flow on a whiteboard.",
      timeline("Issue then verify", [["Login", "Check password / IdP"], ["Sign", "Access JWT (short TTL)"], ["Send", "Bearer on each API call"], ["Verify", "Sig, iss, aud, exp"], ["Allow", "Claims drive authz"]], "If you skip verify, a forged token is a login"),
    ),
    Q(
      "When do you pick sessions versus tokens?",
      "Pick server sessions when you need instant revoke, traditional web apps, and cookie controls. Pick tokens when APIs are split, mobile clients, or you want stateless verify at the edge.",
      "Hybrids exist: opaque session ids as bearer tokens, or JWT access plus server-side blocklist. Interviews: SPA plus cookie with SameSite versus JWT in memory.",
      compare("Revoke vs scale", ["Sessions", "Kill one row, user out", "Sticky store or Redis", "CSRF if cookie", "Great for classic web"], ["Tokens", "Verify without a DB hit", "Revoke needs extra work", "XSS if in localStorage", "Great for APIs / mobile"], "Choose the theft and revoke story — not the hype"),
    ),
    Q(
      "What is the difference between OAuth 2.0 and OpenID Connect?",
      "OAuth 2.0 is about access tokens to call APIs. OpenID Connect (OIDC) is a layer on OAuth that issues an ID token so the client knows who logged in.",
      "Use OIDC for login. Use OAuth scopes for API access. Implicit flow is legacy. Authorization code plus PKCE is the modern default for public clients.",
      compare("Access vs identity", ["OAuth 2.0", "Authorization framework", "Access token for APIs", "Scopes", "Not a login protocol alone"], ["OIDC", "Identity layer", "ID token (JWT)", "UserInfo endpoint", "Login with Google-style"], "OAuth lets you call — OIDC tells you who"),
    ),
    Q(
      "How does TLS protect data in practice?",
      "The handshake agrees keys using the server certificate (and optionally the client). Records are then encrypted with those keys. Browsers check the hostname and trust chain.",
      "TLS 1.3 is simpler and faster. Certificate expiry and weak ciphers still bite. Interviews: HTTPS is not a VPN; the server still sees plaintext after decrypt.",
      layers("Handshake then records", [["Cert", "Public key plus identity"], ["Trust", "CA or pin"], ["Keys", "Ephemeral session keys"], ["Records", "Encrypted HTTP"], ["App", "Sees plaintext after TLS"]], "TLS ends at your process — then your code must behave"),
    ),
    Q(
      "How should you hash passwords in production?",
      "Use Argon2id or bcrypt/scrypt with a unique salt per password, a work factor you can afford, and constant-time compare. Never roll your own mix of SHA and a pepper-only scheme.",
      "Pepper (app-wide secret) is optional extra, not a salt replacement. Migrate old hashes on login. Interviews: salt stops rainbow tables; slowness stops brute force.",
      steps("Store a slow hash", [["Salt", "Unique random per user"], ["KDF", "Argon2id / bcrypt"], ["Work", "Cost you can pay at login"], ["Compare", "Constant-time"], ["Migrate", "Rehash on success"]], "Fast hashes are for files — slow hashes are for passwords"),
    ),
    Q(
      "How do you prevent XSS in practice?",
      "Encode on output for the context (HTML, attr, JS, URL), prefer textContent over innerHTML, use a strict CSP, HttpOnly cookies, and sanitize only with a proven library when HTML is required.",
      "React's default escaping helps but dangerouslySetInnerHTML does not. Markdown and rich text are XSS factories. Interviews: context-aware encoding beats a single regex.",
      hub("Defense in layers", "XSS", [["Encode", "Right context"], ["CSP", "Block inline script"], ["HttpOnly", "JS cannot read cookie"], ["Sanitize", "When HTML is needed"], ["Sinks", "Avoid innerHTML"]], "One encoder and a CSP beat a homemade filter"),
    ),
    Q(
      "How do you prevent CSRF?",
      "Use SameSite=Lax or Strict cookies, plus anti-CSRF tokens (double-submit or synchronizer) on state-changing cookie-auth requests. APIs that use Authorization headers are not auto-sent by foreign sites.",
      "GET must stay safe. SameSite is not enough for all old browsers or all cross-site embeds. Interviews: CORS is not CSRF protection.",
      steps("Stop the forged cookie ride", [["Safe methods", "No state change on GET"], ["SameSite", "Lax or Strict"], ["Token", "Hidden field or header"], ["Custom header", "Not set cross-site easily"], ["Prefer", "Bearer for SPAs"]], "If the browser will attach the cookie, you need a CSRF plan"),
    ),
    Q(
      "How do parameterized queries stop SQL injection?",
      "The SQL structure is fixed; user values go as bound parameters, so they cannot change keywords or add clauses.",
      "This is the real fix. Escaping strings by hand will miss an encoding. Stored procedures are not safe if they concatenate inside. Show a ? or $1 placeholder in the interview.",
      code("Bind, do not concat", "user.js", ["db.query(", "  'SELECT * FROM users WHERE id = $1',", "  [id]", ")"], [["SQL", "Shape is fixed"], ["Value", "id is data only"]], "Parameters make input data — not syntax"),
    ),
    Q(
      "How is CORS different from CSRF?",
      "CORS decides whether JavaScript on another origin may read a response. CSRF is an attack that causes the browser to send the victim's cookies on a write. You can have CSRF with no CORS bypass.",
      "A simple form POST does not need CORS and can still CSRF. Access-Control-Allow-Origin: * with credentials is a misconfig. Interviews love this mix-up.",
      compare("Read vs ride", ["CORS", "Can JS read the response?", "Preflight for some calls", "Server ACAO headers", "Not a CSRF token"], ["CSRF", "Can evil site trigger a write?", "Uses victim cookies", "Tokens / SameSite", "Does not need to read JSON"], "CORS is about reading — CSRF is about causing"),
    ),
    Q(
      "What is a refresh token versus an access token?",
      "An access token is short-lived and sent to APIs. A refresh token is longer-lived, stored more carefully, and used only at the auth server to mint new access tokens.",
      "Refresh tokens need rotation and reuse detection. Do not put refresh tokens in localStorage on a web app if you can use an HttpOnly cookie to the auth endpoint. Interviews: why two tokens at all — blast radius.",
      compare("Short vs long", ["Access token", "Minutes", "Sent to every API", "Leak = brief window", "JWT or opaque"], ["Refresh token", "Hours to days", "Auth server only", "Leak = lasting access", "Must be rotatable"], "Short access — guarded refresh"),
    ),
    Q(
      "What is RBAC versus ABAC?",
      "RBAC grants permissions through roles (admin, editor). ABAC grants them through attributes and policies (user.dept == resource.dept and action == read).",
      "RBAC is simpler to explain and audit. ABAC scales to messy real rules. Many systems mix: roles plus a few attributes. Interviews: role explosion is the RBAC failure mode.",
      compare("Role vs attributes", ["RBAC", "User has roles", "Role has permissions", "Easy to draw", "Role explosion"], ["ABAC", "Policy on attributes", "User, resource, env", "Flexible", "Harder to debug"], "Roles for coarse gates — attributes when roles multiply"),
    ),
    Q(
      "How should an app store and use secrets?",
      "Keep secrets out of git and images. Load from a vault or cloud secret manager at runtime, restrict IAM to the service, rotate, and never log the values.",
      "K8s secrets are base64, not encryption, unless you add encryption at rest. Build-time ENV in Dockerfiles leaks. Interviews: secret zero — how the app first authenticates to the vault.",
      layers("From vault to process", [["Store", "Vault / SM, encrypted"], ["IAM", "Only that workload"], ["Inject", "Env or mounted file"], ["Use", "In memory, short lived"], ["Rotate", "New value, old dies"]], "If the deploy role can read every secret, least privilege already failed"),
    ),
    Q(
      "What cookie flags matter for security?",
      "Secure (HTTPS only), HttpOnly (no document.cookie), SameSite (CSRF), and a tight Path/Domain. Session cookies should be random and expire.",
      "Missing Secure on a login cookie is a classic finding. SameSite=None requires Secure. Interviews: prefix __Host- is a plus. Domain=.example.com widens theft.",
      hub("Flags on Set-Cookie", "Cookie", [["Secure", "HTTPS only"], ["HttpOnly", "Not readable in JS"], ["SameSite", "Lax / Strict / None"], ["Path", "Narrow where it sends"], ["Expires", "Finite life"]], "A cookie is a credential — flag it like one"),
    ),
    Q(
      "How do you authorize at the API layer?",
      "After you authenticate, load the principal, then check every object: not just a role, but this user may act on this resource. Deny by default. Return 401 vs 403 correctly.",
      "Broken object-level authorization (IDOR / BOLA) is OWASP number one for a reason. Middleware that only checks is logged in is not authorization. Interviews: /users/123 when you are user 456.",
      steps("Every request, every object", [["Authn", "Who is calling"], ["Parse", "Which resource id"], ["Load", "Owner / ACL / policy"], ["Decide", "Allow or 403"], ["Log", "Denies for review"]], "A role check without an object check is how IDOR ships"),
    ),
    Q(
      "How do you rotate secrets and signing keys?",
      "Issue a new secret, dual-run (accept old and new) until all clients switch, then revoke the old. For JWT, kid in the header points at the current key.",
      "Leaked secrets need immediate revoke plus audit. Access-token TTL limits blast radius during rotation. Interviews: rotation without downtime is the senior part.",
      timeline("Dual-run then cut", [["Mint", "New key or password"], ["Publish", "Both valid briefly"], ["Move", "Clients and workers"], ["Revoke", "Drop the old"], ["Audit", "Was the old used?"]], "Rotation is a process — not a reboot"),
    ),
  ],
  expert: [
    Q(
      "What JWT pitfalls show up in real systems?",
      "alg=none or accepting HS256 with an RSA public key, huge unvalidated payloads, tokens in localStorage, no exp/aud/iss checks, and treating JWT as encrypted.",
      "Use a well-tested library, pin algorithms, keep access tokens short, and prefer opaque tokens if you need instant revoke. Expert interviews: none algorithm and key confusion are the classics.",
      hub("Ways JWT bites", "JWT", [["alg none", "Accept unsigned"], ["Confusion", "HMAC with public key"], ["Storage", "XSS steals JS tokens"], ["Claims", "Skip exp / aud"], ["Size", "PII in the payload"]], "Verify with the right alg and key — then still do authz"),
    ),
    Q(
      "Why is authorization code plus PKCE the default OAuth flow for public clients?",
      "The code flow keeps tokens off the URL. PKCE proves the same client that started login is the one exchanging the code, so a stolen intercept of the code is not enough.",
      "SPAs and mobile apps cannot hide a client secret. Implicit flow leaked tokens in the hash. Expert: confidential servers still use code; they add a secret. State/nonce stop CSRF/replay on the login.",
      steps("Code, then token", [["Start", "code_challenge (PKCE)"], ["Login", "User at the IdP"], ["Back", "Authorization code"], ["Exchange", "code_verifier"], ["Use", "Access / ID tokens"]], "PKCE binds the code to the client that asked"),
    ),
    Q(
      "How does refresh-token rotation and reuse detection work?",
      "Each refresh issues a new refresh token and invalidates the old one. If the old one is used again, assume theft, kill the family, and force re-login.",
      "This is how you detect a stolen refresh token that the thief and the real client both try to use. Store hashes of refresh tokens. Expert OAuth/OIDC round staple.",
      cycle("Rotate or kill", "RT", [["Use", "Refresh once"], ["Mint", "New RT + AT"], ["Retire", "Old RT dead"], ["Reuse", "Alarm + revoke family"]], "A reused refresh token is a stolen session"),
    ),
    Q(
      "How do SameSite cookies change CSRF in modern browsers?",
      "SameSite=Lax blocks most cross-site POSTs with cookies, which kills a lot of classic CSRF. Cross-site embeds, OAuth callbacks, and old browsers still need tokens. SameSite=None; Secure is required for intentional cross-site cookies.",
      "Lax still sends cookies on top-level GET navigations — so GET must not change state. Expert: third-party cookie death also changes SSO. Do not drop CSRF tokens only because Lax exists.",
      compare("Browser help vs complete", ["SameSite Lax/Strict", "Stops many forged POSTs", "Easy default", "GET top-level still sends Lax", "Not universal"], ["CSRF token", "Proves intent from your page", "Works with cookies", "Needed for None / old clients", "Pairs with SameSite"], "SameSite is a seatbelt — tokens are still the harness for cookie auth"),
    ),
    Q(
      "How do you apply defense in depth for XSS, SQLi, and SSRF?",
      "Assume one control fails. For XSS: encode plus CSP plus HttpOnly. For SQLi: parameters plus least-privilege DB user plus WAF as extra. For SSRF: allowlist URLs, block link-local, and do not fetch user URLs from the metadata network.",
      "SSRF to cloud metadata is a modern interview favorite. Depth means independent controls, not the same check twice.",
      layers("Independent controls", [["Prevent", "Encode / bind / allowlist"], ["Contain", "Least privilege"], ["Detect", "WAF, logs, IDS"], ["Recover", "Rotate, patch, audit"]], "One filter is a hope — two independent controls are a design"),
    ),
    Q(
      "How do you implement least privilege in cloud IAM?",
      "One identity per workload, scoped roles not AdministratorAccess, condition keys (source IP, VPC, tags), short-lived credentials, and no long-lived keys on laptops if SSO can issue them.",
      "Human vs machine identities differ. Privilege escalation paths (iam:PassRole, lambda:CreateFunction) are the expert follow-up. Review unused permissions with Access Analyzer-style tools.",
      steps("Narrow the blast radius", [["Identity", "Workload, not a shared user"], ["Role", "Only needed actions"], ["Condition", "Resource tags / network"], ["Time", "Temporary creds"], ["Review", "Drop unused"]], "If every service uses the same powerful role, you have one identity"),
    ),
    Q(
      "What is threat modeling (STRIDE) in an interview?",
      "Threat modeling lists what can go wrong before you write controls. STRIDE is a mnemonic: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege.",
      "Walk a diagram: trust boundaries, data stores, processes. Expert answers name assets and attackers, not a tool. DREAD is a scoring cousin; many teams just use likelihood times impact.",
      hub("STRIDE on a whiteboard", "STRIDE", [["S", "Spoof identity"], ["T", "Tamper data"], ["R", "Deny you did it"], ["I", "Leak"], ["D", "Flood / crash"], ["E", "Gain extra power"]], "Name the threat before you name the control"),
    ),
    Q(
      "When would you use certificate pinning versus public CA TLS?",
      "Public CAs plus HTTPS is the default. Pinning (or public-key pinning in an app) trusts only a specific cert or SPKI so a rogue CA or MITM proxy cannot impersonate you — at the cost of breakage on rotation.",
      "Mobile apps sometimes pin. Browsers killed HPKP as too dangerous. Expert: backup pins, short pin sets, and a kill switch. For most APIs, CAA records and CT monitoring are enough.",
      compare("Default vs extra lock", ["Public CA TLS", "Works everywhere", "Rotate certs freely", "Trust the CA ecosystem", "Right for most apps"], ["Pinning", "Stops extra CAs", "Breaks if you forget rotation", "App-owned trust", "High-risk clients"], "Pin only if you can rotate without bricking clients"),
    ),
    Q(
      "What is a timing attack on authentication?",
      "A timing attack infers secrets from how long a compare or lookup takes — for example failing faster on the first wrong byte of a token.",
      "Use constant-time compares for MACs, API keys, and password hashes (the KDF already dominates time; still compare hashes in constant time). Expert: also watch early-exit user-not-found versus bad-password messages and delays.",
      code("Do not early-exit bytes", "mac.js", ["// bad: if (a[i] !== b[i]) return false", "crypto.timingSafeEqual(a, b)"], [["Leak", "Time ~ matching prefix"], ["Fix", "Fixed-time compare"]], "If time depends on the secret, the secret leaks"),
    ),
    Q(
      "How do you use OWASP (Top 10 / ASVS) in a design review?",
      "Treat Top 10 as a conversation starter and ASVS as a requirement checklist by assurance level. Map each user story to controls: authn, authz, crypto, validation, logging.",
      "Expert: do not paste the PDF into Jira. Pick the ASVS level for the data class (L1 vs L2). Pair with a threat model so you do not miss issues that are not in the current Top 10.",
      timeline("From list to tickets", [["Class", "Data sensitivity"], ["Level", "ASVS L1 / L2"], ["Stories", "Controls per flow"], ["Test", "Abuse cases"], ["Signoff", "Residual risk"]], "OWASP is input to design — not a sticker on the wiki"),
    ),
    Q(
      "What is IDOR / BOLA and how do you stop it?",
      "Insecure Direct Object Reference (BOLA in API terms) is changing an id in the URL or body to another user's object and being allowed. Stop it with an authorization check on every object, every time.",
      "UUIDs are not authz. Sequential ids make scanning easy but hiding ids is not the fix. Expert: test as two users in CI. This is the most common API finding.",
      compare("Hide vs check", ["Obscure the id", "UUID / hashids", "Still guessable or leaked", "Fails when logs leak", "Not authorization"], ["Check ownership", "Load resource + principal", "Deny by default", "Works with sequential ids", "Real authorization"], "If user A can fetch user B's id, you have BOLA"),
    ),
    Q(
      "How does envelope encryption protect secrets at rest?",
      "A data key encrypts the blob; a KMS master key encrypts the data key. You store ciphertext plus the wrapped key. Rotating the master rewraps keys without rewriting all data.",
      "This is how S3 SSE-KMS and vault transit work. Expert: never put the plaintext DEK on disk; IAM on kms:Decrypt is the real lock. Pair with least privilege on who can decrypt.",
      layers("Two keys", [["DEK", "Encrypts the data"], ["KEK / CMK", "Wraps the DEK"], ["Store", "Ciphertext + wrapped DEK"], ["IAM", "Who may unwrap"], ["Rotate", "Rewrap, not always rewrite"]], "The KMS call is the authorization check for decrypt"),
    ),
    Q(
      "How do you stop session fixation and session hijacking?",
      "Issue a new session id after login (fixation). Use Secure, HttpOnly, SameSite cookies, short idle timeout, regenerate on privilege change, and bind optionally to user-agent or a fingerprint with care.",
      "Fixation: attacker plants an id, victim logs in, attacker reuses it. Hijacking: steal the id. Expert: TLS plus cookie flags first; IP binding breaks mobile networks — use with caution.",
      steps("New id after login", [["Anon", "Pre-login id is untrusted"], ["Authn", "Verify credentials"], ["Rotate", "Brand-new session id"], ["Flags", "Secure HttpOnly SameSite"], ["Expire", "Idle and absolute"]], "The id you had before login must not be the id you keep"),
    ),
    Q(
      "How does zero trust differ from a network perimeter?",
      "Perimeter models trust anyone on the LAN. Zero trust authenticates and authorizes every request, assumes the network is hostile, and uses short-lived identities and device posture.",
      "It is a strategy, not a product. Microsegmentation, mTLS between services, and no flat VPN-as-admin are the usual pieces. Expert: still need a perimeter for DDoS; zero trust is identity-centric.",
      compare("Castle vs every hop", ["Perimeter", "Trust inside the firewall", "VPN = full access", "Lateral movement is easy", "Classic datacenter"], ["Zero trust", "Never trust the network", "Authn/authz per request", "Least privilege paths", "Identity is the edge"], "Being on the VPN is not a role"),
    ),
    Q(
      "How do you get observability without leaking secrets in logs?",
      "Log request ids, user ids, error codes, and timings — never tokens, passwords, card numbers, or raw Authorization headers. Redact at the logger; sample traces; encrypt log stores.",
      "Debug-level dumps of request bodies are how JWTs hit Splunk. Expert: structured logs plus allowlists beat regex redaction. Access to prod logs is a privilege — treat it like prod data.",
      hub("Signal vs secret", "Logs", [["Keep", "Trace id, status, latency"], ["Drop", "Password, cookie, JWT"], ["Redact", "PAN, SSN, email if needed"], ["Who", "Least privilege on log ACL"], ["Test", "CI scanner for key patterns"]], "A stack trace that prints the bearer token is an incident"),
    ),
  ],
};
