const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "System Design",
  slug: "system-design",
  description: "Scalability, caching, load balancing, microservices, architecture",
  theme: {
    accent: "#4f46e5",
    hubFill: "#4f46e5",
    hubText: "#ffffff",
    centerFill: "#e0e7ff",
    centerStroke: "#4f46e5",
    label: "Design",
  },
  beginner: [
    Q(
      "What does scalability mean?",
      "Scalability is the ability of a system to handle more load by adding resources, without a redesign of the core architecture.",
      "Load is usually requests, data, or concurrent users. Vertical scaling adds a bigger machine; horizontal scaling adds more machines. Interviews want you to name the bottleneck first (CPU, disk, network, lock) before proposing scale.",
      steps("Grow without rewriting", [["Measure", "What is the load?"], ["Find", "Which resource saturates?"], ["Add", "Bigger box or more boxes"], ["Check", "Latency and errors still OK"]], "Scale the bottleneck — not the whole diagram"),
    ),
    Q(
      "What is caching?",
      "A cache stores a copy of expensive-to-fetch data so later reads are faster. It trades freshness and memory for latency.",
      "Put caches near the caller (browser, CDN, app memory, Redis). Always name TTL, invalidation, and what happens on a miss. “We will cache it” is incomplete without eviction and stampede talk.",
      hub("Where copies live", "Cache", [["Browser", "HTTP cache headers"], ["CDN", "Edge copies"], ["App", "In-process memory"], ["Redis", "Shared hot keys"], ["DB", "Buffer pool"]], "A cache is a faster, possibly stale, copy"),
    ),
    Q(
      "What is load balancing?",
      "A load balancer spreads incoming traffic across several healthy backends so no single instance is the hot spot and one failure does not take the site down.",
      "It also does health checks and TLS termination in many setups. Algorithms: round robin, least connections, consistent hash. Interviews expect “health + distribution,” not just “split traffic.”",
      steps("Spread the work", [["Arrive", "Client hits the LB"], ["Pick", "Choose a healthy node"], ["Forward", "Proxy the request"], ["Retry", "Skip failed nodes"]], "A load balancer is traffic plus health, not a random splitter"),
    ),
    Q(
      "When do you choose a monolith vs microservices?",
      "A monolith is one deployable unit — simpler to build and debug early. Microservices split by bounded context so teams and scale axes can move independently, at the cost of network and ops.",
      "Start monolith unless you already have clear domain boundaries and team scale. Microservices without ownership and observability become a distributed monolith. Interviews punish “microservices because Netflix.”",
      compare("One unit vs many", ["Monolith", "One deploy", "In-process calls", "Simple transactions", "Hard to scale one part"], ["Microservices", "Many deploys", "Network calls", "Per-service scale", "Ops and tracing cost"], "Split on domain and team, not on folder count"),
    ),
    Q(
      "What is the CAP theorem?",
      "On a network partition, a distributed store cannot be both fully consistent and fully available. You pick CP (consistent, may refuse) or AP (available, may serve stale).",
      "P is not optional on real networks — partitions happen. CAP is about a partition window, not “we never have all three in the office.” Name the system: ZooKeeper is CP; Dynamo-style stores lean AP.",
      hub("When the network splits", "CAP", [["C", "Same read everywhere"], ["A", "Every request gets an answer"], ["P", "Survive a network cut"], ["CP", "Refuse rather than lie"], ["AP", "Serve, maybe stale"]], "During a partition you choose C or A — not both"),
    ),
    Q(
      "Why use a message queue?",
      "A queue decouples a producer from a consumer: the producer writes a message and returns; workers pull when they can. That absorbs spikes and lets you retry work.",
      "Use queues for emails, image jobs, and fan-out. Do not use a queue as a database. Say at-least-once delivery and that consumers must be idempotent.",
      cycle("Produce, store, consume", "Queue", [["Produce", "Write the message"], ["Buffer", "Broker holds it"], ["Consume", "Worker pulls"], ["Ack", "Delete after success"]], "A queue buys time — it does not shrink the work"),
    ),
    Q(
      "What is a CDN?",
      "A content delivery network caches static (and sometimes dynamic) content on edge servers close to users so origin load and latency drop.",
      "HTML, JS, images, and video are the usual wins. Cache-Control and purge APIs control freshness. A CDN does not fix a slow uncacheable API by itself.",
      layers("Closer copies of bytes", [["User", "Hits a nearby POP"], ["Edge", "Cached object or miss"], ["Mid-tier", "Regional shield"], ["Origin", "Your app or bucket"]], "A CDN is geography plus cache policy"),
    ),
    Q(
      "What is sharding?",
      "Sharding splits data across machines by a key so each node owns a slice. Total capacity grows with shard count; a query that needs every shard gets harder.",
      "Pick a shard key that spreads load and matches query patterns. UserId works for “my data”; a hot celebrity id can melt one shard. Resharding is the expensive part.",
      steps("Split the dataset", [["Key", "Choose a shard key"], ["Hash / range", "Map key to a node"], ["Route", "Send reads/writes there"], ["Rebalance", "Move slices when full"]], "Sharding is partitioning — the key is the design"),
    ),
    Q(
      "What is replication?",
      "Replication copies the same data to more than one node for durability and extra read capacity. One node is often the leader for writes.",
      "Sync replication waits for replicas (safer, slower). Async is faster and can lose the last writes on failover. Read replicas help reads, not write throughput, unless you shard too.",
      compare("Copies of the same data", ["Sync replica", "Wait for ack", "Less data loss", "Higher write latency", "Stronger durability"], ["Async replica", "Leader returns first", "Replica can lag", "Fast writes", "Failover may drop tail"], "Replication is copies — sharding is slices"),
    ),
    Q(
      "What is rate limiting?",
      "Rate limiting caps how often a client can call an API so one user or bot cannot starve everyone else or blow the bill.",
      "Return 429 with Retry-After. Limits can be per IP, per API key, or per user. Token bucket and sliding window are the usual algorithms. Protect login and expensive endpoints first.",
      hub("Cap the request rate", "Limit", [["Who", "IP, key, user"], ["How many", "N per window"], ["Where", "Gateway or app"], ["Signal", "HTTP 429"], ["Retry", "Backoff header"]], "Rate limits are a product decision, not only a firewall rule"),
    ),
    Q(
      "What is idempotency?",
      "An operation is idempotent if doing it several times has the same effect as doing it once. Clients can retry timeouts without double charges or double inserts.",
      "HTTP GET, PUT, DELETE are designed that way; POST often is not unless you add an Idempotency-Key. Interviews: payments, Kafka consumers, and “at-least-once” all need this word.",
      code("Retry the same intent", "pay.js", ["headers['Idempotency-Key'] = id", "POST /charges", "{ amount: 50 }", "// replay uses the same id"], [["Key", "Client-generated unique id"], ["Store", "Server remembers the result"]], "If a timeout happens, retry only if the effect will not double"),
    ),
    Q(
      "What is backpressure?",
      "Backpressure is a slower consumer telling a faster producer to slow down (or drop) so queues do not grow without bound and take down memory.",
      "Without it you buffer until OOM. Patterns: bounded queues, HTTP 429, TCP window, reactive pull. “We will add more consumers” is scaling; backpressure is flow control.",
      cycle("Do not drown the worker", "Flow", [["Produce", "Work arrives"], ["Buffer", "Bounded queue"], ["Signal", "Slow or reject"], ["Consume", "Worker catches up"]], "Unbounded buffers are a crash with extra steps"),
    ),
    Q(
      "What is consistent hashing?",
      "Consistent hashing maps keys onto a ring so when a node is added or removed, only a small fraction of keys move. Modulo hashing remaps almost everything when N changes.",
      "Used for caches, shard routing, and some load balancers. Virtual nodes spread load so one physical host is not a huge arc. Interviewers want “minimal remapping,” not a proof.",
      compare("When N changes", ["Modulo N", "hash % N", "Most keys jump", "Painful reshard", "Fine if N is fixed"], ["Consistent hash", "Key on a ring", "Few keys move", "Add/remove nodes", "Needs vnodes for balance"], "Consistent hashing is about churn, not about crypto"),
    ),
    Q(
      "What is observability?",
      "Observability is whether you can explain the system’s state from its outputs: metrics, logs, and traces. Monitoring is watching known dashboards; observability is asking new questions in production.",
      "RED (rate, errors, duration) and USE (utilization, saturation, errors) are starter frameworks. Without correlation ids, microservices are a black box. SLOs make the data actionable.",
      layers("See why it broke", [["Metrics", "Aggregates and alerts"], ["Logs", "What this request did"], ["Traces", "Path across services"], ["Context", "User, version, region"]], "If you cannot debug a new failure, you are not observable"),
    ),
    Q(
      "What does “everything is a tradeoff” mean in system design?",
      "Every extra guarantee (consistency, latency, cost, operability) is paid for somewhere else. A good design names what you give up, not only what you gain.",
      "Interviews score the conversation: requirements, constraints, then options with costs. “We will use Kafka and Kubernetes” without a bottleneck is not a design.",
      timeline("How to talk tradeoffs", [["Goal", "Latency, cost, or correctness?"], ["Load", "Read/write shape"], ["Options", "Two or three designs"], ["Cost", "Ops, money, risk"], ["Pick", "And say what you skipped"]], "The answer is a choice with a price, not a product list"),
    ),
  ],
  intermediate: [
    Q(
      "How do you choose vertical vs horizontal scaling?",
      "Vertical scaling is simpler until you hit hardware, cost, or HA limits. Horizontal scaling needs stateless app nodes (or sticky sessions done carefully) and a data plane that can split.",
      "Stateful stores do not “just add instances.” Session in memory, local disk, and leader-only writes are the usual traps. Scale reads with replicas; scale writes with shards or queues.",
      compare("Bigger box vs more boxes", ["Vertical", "One machine grows", "Simple ops", "Hard ceiling", "Failover is a bigger blast"], ["Horizontal", "Many machines", "Need a balancer", "Commodity HW", "Must share almost no local state"], "Stateless frontends scale out; databases need a plan"),
    ),
    Q(
      "How do you pick a cache eviction policy?",
      "TTL expires stale data. LRU keeps recently used keys. LFU keeps frequent keys. Size caps prevent Redis from eating the host. The policy must match access patterns.",
      "Cache stampede: many misses on one hot key after expiry — use locking, jittered TTL, or serve stale. Write-through vs write-around vs write-back changes miss rates and durability.",
      hub("When the cache is full", "Evict", [["TTL", "Time-based stale"], ["LRU", "Least recently used"], ["LPU/LFU", "Cold frequent keys"], ["Jitter", "Avoid thundering herd"], ["Cap", "Max memory"]], "Eviction is a product of traffic shape, not a default Redis setting"),
    ),
    Q(
      "What is the difference between L4 and L7 load balancing?",
      "L4 (TCP/UDP) routes by IP and port — cheap, fast, opaque payload. L7 (HTTP) can route by path, header, cookie, and do retries, auth, and WAF.",
      "gRPC and HTTP/2 need L7 awareness for streams. Sticky sessions at L7 are easier but hurt even load. Health checks should match the protocol you terminate.",
      compare("Packet vs request", ["L4", "IP + port", "Low latency", "TLS often pass-through", "No URL routing"], ["L7", "HTTP/gRPC aware", "Path and header rules", "Retries, auth, canary", "More CPU per request"], "Pick L7 when the request content must decide the backend"),
    ),
    Q(
      "When is it time to split a monolith?",
      "Split when a bounded context has a different scale, reliability, or release cadence, and the team can own the resulting API and data.",
      "Extract along domain lines with a clear interface, not by copying folders into new repos. Shared databases between “services” keep the coupling. Strangler fig is the usual migration.",
      timeline("Strangle, do not explode", [["Find", "Hot module or team boundary"], ["API", "Hide the old internals"], ["Move", "One context at a time"], ["Data", "Own the tables"], ["Delete", "Retire the old path"]], "A split without data ownership is still a monolith"),
    ),
    Q(
      "How do you apply CAP to a real database choice?",
      "Ask what the product does during a partition: block writes (CP) or keep taking writes that may conflict (AP). Then pick the store that matches, plus a conflict story.",
      "Postgres primary + sync standby leans CP. Cassandra/Dynamo with sloppy quorum lean AP. Many systems are tunable (R + W vs N). PACELC adds: if no partition, you still trade latency vs consistency.",
      compare("Refuse vs serve stale", ["CP-ish", "ZooKeeper, etcd", "Strong config / locks", "Unavailable on split", "Correct over uptime"], ["AP-ish", "Dynamo-style", "Shopping carts, feeds", "Always take the write", "Repair later"], "Name the failure mode the business will accept"),
    ),
    Q(
      "What delivery guarantees do queues actually give?",
      "At-most-once can drop messages. At-least-once can duplicate. Exactly-once is usually “at-least-once plus idempotent processing plus dedupe,” not magic.",
      "Kafka commits, visibility timeouts, and ack/nack decide retries. Poison messages need a DLQ. The outbox pattern keeps DB writes and “message sent” in one transaction story.",
      hub("What the broker promises", "Delivery", [["At most once", "May lose"], ["At least once", "May duplicate"], ["Dedupe", "Idempotent consumer"], ["DLQ", "Poison after N fails"], ["Outbox", "DB and bus agree"]], "Design for duplicates — “exactly once” is a pipeline, not a checkbox"),
    ),
    Q(
      "How does a CDN miss path work, and why does origin shielding matter?",
      "On miss, the edge fetches origin (or a shield POP). Without a shield, a viral miss can DDoS your origin. Cache key design (query strings, cookies, headers) decides hit ratio.",
      "Stale-while-revalidate keeps serving while refreshing. Purge/ban is for bad deploys. Signed URLs protect private assets. Dynamic HTML is often a poor CDN candidate.",
      layers("Miss without melting origin", [["Edge", "Serve if fresh"], ["Shield", "Collapse thundering herd"], ["Origin", "App or object store"], ["Policy", "TTL, vary, purge"]], "The cache key is the product — Vary: * means almost no hits"),
    ),
    Q(
      "How do you choose a shard key?",
      "The key must spread writes, match the hottest queries (so you hit one shard), and stay stable. Cardinality too low means hot shards; too random means scatter-gather reads.",
      "Avoid monotonically increasing keys (all writes to the newest shard). Compound keys (tenant + id) isolate noisy neighbors. Plan resharding before you need it.",
      steps("A key that will not melt", [["Queries", "What is the lookup?"], ["Cardinality", "Enough distinct values"], ["Skew", "No celebrity hotspot"], ["Growth", "How you split later"]], "If every query is “order by created_at global,” sharding will hurt"),
    ),
    Q(
      "Leader vs leaderless replication — what changes for the app?",
      "Leader-based: all writes go to one node, replicas follow. Simple conflicts, failover is the hard part. Leaderless: write to a quorum, read from a quorum, resolve siblings.",
      "Read-your-writes after a user save often needs sticky to leader or session causal. Replication lag makes “read replica for the page you just posted” a classic bug.",
      compare("Who takes the write", ["Leader", "One writer", "Ordered log", "Failover election", "Replicas for reads"], ["Leaderless", "Any node", "Quorum R/W", "Vector clocks / CRDT", "Conflict on the client"], "If the UI must see its own write, design the read path"),
    ),
    Q(
      "Token bucket vs leaky bucket vs sliding window?",
      "Token bucket allows bursts up to bucket size, then refills at a rate. Leaky bucket emits at a constant rate (smooths bursts). Sliding window counts requests in a rolling time span — fairer than a fixed minute reset.",
      "Fixed windows let a client burst 2x at the boundary. Sliding log is accurate and memory-heavy. Pick burst if UX needs it (page load); pick smooth if downstream is fragile.",
      compare("Burst vs smooth", ["Token bucket", "Burst then pace", "Good for UX spikes", "Need refill rate"], ["Leaky / strict", "Constant outflow", "Protects downstream", "May 429 during burst"], "The algorithm is how you treat bursts — say which the API needs"),
    ),
    Q(
      "How do idempotency keys work in an API?",
      "The client sends a unique key with the mutating request. The server stores the key plus the response (or a fingerprint of the body). Replays return the same result without a second side effect.",
      "Keys need a TTL and a scope (user + route). Mismatched bodies with the same key should 409. This is how Stripe and many payment APIs survive mobile retries.",
      code("Store the first success", "idempotency.js", ["const prev = await get(key)", "if (prev) return prev.body", "const result = await charge()", "await save(key, result)", "return result"], [["Replay", "Same key, same body"], ["Conflict", "Same key, different body"]], "The key is part of the protocol — not a cache of convenience"),
    ),
    Q(
      "How do you implement backpressure in a pipeline?",
      "Use a bounded buffer and a policy: block the producer, reject new work, drop oldest, or shed load. Pull-based consumers (reactive streams, Kafka max.poll) only take what they can.",
      "HTTP: 429 or 503 with Retry-After. gRPC has flow control. Thread pools with unbounded queues hide the problem until latency explodes. Measure queue depth as a first-class SLO.",
      steps("Bound then decide", [["Cap", "Finite queue / inflight"], ["Signal", "Block, 429, or nack"], ["Shed", "Drop low-priority"], ["Scale", "Add consumers if still behind"]], "If the queue is unbounded, you do not have backpressure"),
    ),
    Q(
      "Why add virtual nodes to consistent hashing?",
      "One physical node gets many positions on the ring so its share of keys is even. Without vnodes, a new node can steal a huge contiguous arc and become hot, and small rings look lumpy.",
      "When a node dies, its vnodes’ keys spread across many peers instead of dumping onto the clockwise neighbor. Jump hashing and rendezvous hashing are alternatives with different movement math.",
      hub("Smooth the ring", "vnodes", [["Many hashes", "One host, many points"], ["Balance", "Even key share"], ["Fail", "Spread the orphans"], ["Weight", "Bigger hosts, more vnodes"], ["Move", "Still O(K/N) keys"]], "Virtual nodes are load insurance on the ring"),
    ),
    Q(
      "How do metrics, logs, and traces work together?",
      "Metrics tell you something is wrong (p99, error rate). Traces show which hop. Logs show the payload and branch for that request. You need a correlation id on all three.",
      "High-cardinality labels explode metric backends. Sample traces, keep errors. Structured logs beat string soup. Exemplars link a metric spike to a trace.",
      layers("Three signals, one request", [["Alert", "Metric crosses SLO"], ["Trace", "Which service is slow"], ["Log", "Why this call failed"], ["Id", "trace_id on every line"]], "A dashboard without a request id is a screenshot, not a debug path"),
    ),
    Q(
      "How do you trade latency, consistency, and cost in a design?",
      "Tighter consistency usually means more coordination (quorum, sync replica) and higher tail latency. Caches and async pipelines cut latency and cost but add staleness and complexity.",
      "Put numbers on the table: p99 target, RPO/RTO, monthly spend. Multi-region active-active is a consistency and conflict problem, not a checkbox. Interviews want you to drop a requirement on purpose.",
      hub("You cannot max all three", "Pick", [["Latency", "Cache, async, nearer region"], ["Consistency", "Quorum, single leader"], ["Cost", "Fewer replicas, TTL"], ["Ops", "Simpler topology"], ["Risk", "What failure is OK"]], "State the SLO, then spend consistency or money to hit it"),
    ),
  ],
  expert: [
    Q(
      "How do you scale writes when a single leader is the ceiling?",
      "Shard so each leader owns a partition, or go leaderless with conflict resolution, or move hot writes to an append-only log and derive views (CQRS). Pure read replicas will not save write QPS.",
      "CQRS: writes hit a store optimized for ingest; reads hit projections. You accept lag. Hot partitions still need key redesign or local buffering. Cross-shard transactions are the tax.",
      compare("More write throughput", ["Shard + leaders", "Partition the write set", "Key design is everything", "Cross-shard is hard"], ["CQRS / log", "Append then project", "Reads can lag", "Great for event history"], "Write scale is partition or conflict — replicas only scale reads"),
    ),
    Q(
      "Write-through vs write-back vs write-around — which cache coherence story?",
      "Write-through updates cache and store together (simple, extra write latency). Write-back updates cache first and flushes later (fast, data loss on crash). Write-around writes the store and fills cache on read (avoids filling with one-time writes).",
      "Distributed caches plus multiple writers need a coherence story: TTL, pub/sub invalidation, or version numbers. “Redis as source of truth” is a durability interview fail unless you mean it.",
      hub("Where the write lands", "Write", [["Through", "Cache + DB now"], ["Back", "Cache first, flush later"], ["Around", "DB first, cache on read"], ["Invalidate", "Drop key on mutate"], ["Version", "CAS / etag"]], "Name who is source of truth after a crash"),
    ),
    Q(
      "How do you drain and rebalance a load-balanced fleet without dropping in-flight work?",
      "Stop sending new connections (or mark the instance unhealthy), wait for in-flight requests up to a timeout, then terminate. Connection draining and graceful SIGTERM are the mechanism.",
      "Long-lived websockets and gRPC streams need explicit close. Consistent hashing at L7 keeps cache locality when the pool changes. Health checks that hit a cheap /health but not the dependency lie during deploys.",
      steps("Leave without dropping", [["Unready", "Fail readiness, keep liveness"], ["Drain", "LB stops new work"], ["Finish", "In-flight to deadline"], ["Kill", "Then replace the process"]], "Readiness is for the balancer; liveness is for the orchestrator"),
    ),
    Q(
      "Sagas vs two-phase commit for a business workflow?",
      "2PC tries to lock all participants and commit atomically — poor for latency, availability, and heterogeneous services. A saga is a sequence of local transactions plus compensations if a later step fails.",
      "Sagas are eventually consistent; you design compensating actions (refund, unlock). Orchestration (a coordinator) vs choreography (events) is the structure choice. Idempotent steps are mandatory.",
      compare("Lock the world vs compensate", ["2PC", "Prepare then commit", "Blocking, chatty", "DB-centric", "Fails across HTTP"], ["Saga", "Step + compensate", "Available, async", "Fits microservices", "Need a recovery story"], "If the participants are HTTP services, you are in saga land"),
    ),
    Q(
      "What does PACELC add on top of CAP?",
      "PACELC: if Partition, trade Availability vs Consistency; Else (normal operation) trade Latency vs Consistency. Even with a healthy network, a sync quorum costs RTT.",
      "This is why people run async replicas in one region and argue about “strong” vs “session” consistency. Linearizability is the strongest client-visible spec; eventual is the weakest commonly named. Expert interviews want the client guarantee, not the logo on the database.",
      compare("Partition vs healthy path", ["P: A vs C", "Split brain window", "CP refuse vs AP diverge"], ["EL: L vs C", "Quorum RTT", "Stale replica reads"], "CAP is the outage; PACELC is also the everyday latency tax"),
    ),
    Q(
      "How do you handle poison messages and dual-write bugs?",
      "After N failures, move the message to a DLQ with the error, alert, and a replay tool. Dual-write (DB then queue, or the reverse, without a transaction) loses or duplicates on crash — use outbox or CDC from the WAL.",
      "Ordering vs concurrency: per-key partitioning preserves order; global order does not scale. Schema evolution on the payload needs a contract (version field, compatible JSON).",
      hub("When the pipeline lies", "Safety", [["DLQ", "Stop retry storms"], ["Outbox", "One DB commit"], ["CDC", "Log is the bus"], ["Key", "Order per entity"], ["Schema", "Version the payload"]], "The scary bug is “DB committed, message never sent”"),
    ),
    Q(
      "How do you invalidate a CDN without creating an origin stampede?",
      "Prefer short TTL plus stale-while-revalidate over mass purge. Soft purge (mark stale) lets the edge revalidate once. Surge shielding and request coalescing collapse parallel misses.",
      "Versioned URLs (content hash in the path) make invalidation a non-event. Purge-all is an incident tool. Cookie-based cache keys destroy hit ratio — that is often the real bug.",
      timeline("Ship a new asset safely", [["Hash", "filename.abc123.js"], ["TTL", "Long for hashed URLs"], ["HTML", "Short TTL for the shell"], ["Purge", "Only if you must"], ["Shield", "Collapse origin misses"]], "Immutable URLs beat a clever purge API"),
    ),
    Q(
      "How do you reshard a live store?",
      "Add capacity with consistent hashing / range splits, migrate slices in the background, dual-write or proxy reads during cutover, then drop the old location. Dual-running both mappings is the usual tax.",
      "Hot-spot splits: split the range, or add a salt to the key. Live migration must bound extra load (rate-limit the copier). Some systems (Vitess, Cosmos, DynamoDB) hide this; rolling your own is a year-long project.",
      steps("Move data while serving", [["Plan", "New ring or split ranges"], ["Copy", "Background migrate"], ["Dual", "Read new, fall back old"], ["Cut", "Writes only to new"], ["GC", "Delete the leftovers"]], "Resharding is a migration product, not a hash function change"),
    ),
    Q(
      "How do you give read-your-writes under replication lag?",
      "Send the user’s subsequent reads to the leader, or wait for a replica to reach a write timestamp (session token), or return a version the client must pass back.",
      "Quorum reads (R + W > N) reduce staleness but cost latency. Causal consistency is the usual product sweet spot: you see your own writes and the writes you observed. Full linearizability is rarer and pricier.",
      layers("After the user hits save", [["Write", "Leader (or quorum)"], ["Token", "LSN / vector / cookie"], ["Read", "Block until caught up"], ["Fallback", "Sticky to writer"]], "“Read replica for everything” breaks the page you just posted"),
    ),
    Q(
      "How do you rate-limit across many gateway instances?",
      "Local counters disagree. Use a shared store (Redis INCR + TTL, or a sliding window of timestamps) or a centralized limiter service. Approximate algorithms (leaky at the edge plus a global budget) cut Redis QPS.",
      "Sliding window log is exact and heavy. Sliding window counter is cheaper and slightly fuzzy. Fail-open vs fail-closed when Redis is down is a security vs availability choice — say it out loud.",
      code("Shared sliding window", "limit.lua", ["n = INCR key", "if n == 1 then EXPIRE key w", "if n > max then 429", "else allow"], [["Atomic", "Lua / MULTI vs race"], ["Fail", "Open or closed on Redis down"]], "A local token bucket is not a fleet-wide quota"),
    ),
    Q(
      "Is “exactly-once” processing real?",
      "End-to-end exactly-once means the side effect happens once despite retries. Brokers give you building blocks (idempotent producers, transactional consume-produce). The consumer still needs an idempotency store for non-Kafka effects (email, charge, HTTP).",
      "Kafka transactions do not make your Stripe call exactly-once. Effectively-once is: at-least-once delivery + unique key + persistent dedupe. Experts who say “Kafka is exactly-once” get follow-up questions about the database.",
      compare("Broker vs side effect", ["Inside the log", "Idempotent produce", "Txn read-process-write", "Offsets + output atomic"], ["Outside world", "HTTP, email, card", "Need your own key", "Dedupe table / upsert"], "Exactly-once stops at the system boundary you control"),
    ),
    Q(
      "When do you drop, block, or degrade under overload?",
      "Blocking (backpressure) protects the consumer if the producer can wait. Rejecting (429/503) protects the server if the client can retry later. Dropping or serving stale protects latency for everyone else (load shedding, feature kill switches).",
      "Priority: shed batch and non-critical reads first. Watch queue age, not only CPU. Reactive streams’ request(n) is pull-based backpressure. Expert answer names the user-visible degradation, not only the queue.",
      cycle("Overload policy", "Shed", [["Detect", "Queue age / p99"], ["Degrade", "Stale or fewer features"], ["Reject", "429 the excess"], ["Recover", "Raise limits slowly"]], "An unbounded retry from the client is how a blip becomes an outage"),
    ),
    Q(
      "Consistent hashing vs rendezvous vs jump hashing — when?",
      "Consistent hashing with vnodes is the operational default for caches and many data rings. Rendezvous (HRW) hashing picks the highest hash(node, key) and moves few keys with simpler math. Jump hashing needs a compact 0..N-1 node list and cheap lookups, not arbitrary node ids.",
      "Maglev is Google’s consensus table for L4/L7 with almost-even load and small disruption. The interview is whether you know why modulo fails on churn, not which paper to cite first.",
      hub("Minimal movement, even load", "Hash", [["Modulo", "Breaks on N+/-1"], ["Consistent", "Ring + vnodes"], ["Rendezvous", "Highest hash wins"], ["Jump", "Dense 0..N-1"], ["Maglev", "Lookup table for LB"]], "Pick the scheme that matches how nodes appear and disappear"),
    ),
    Q(
      "How do you set SLOs and use traces without drowning in data?",
      "SLOs are user-facing targets (availability, latency) with an error budget that decides how hard you ship. Trace everything in the critical path at low sample rates; always sample errors and slow traces.",
      "Tail sampling keeps interesting traces after the fact. High-cardinality (user id on every metric) will page the bill. Exemplars and trace_id in logs close the loop. Observability that cannot answer “why this checkout” is vanity dashboards.",
      layers("Budget, then sample", [["SLO", "User journey target"], ["Budget", "How much miss is OK"], ["Trace", "Sample + keep errors"], ["Link", "Metrics to trace_id"], ["Act", "Halt launches if burning"]], "An SLO without a budget is a wish; a trace without sampling is a bill"),
    ),
    Q(
      "How should you run a system design interview as the candidate?",
      "Clarify users, QPS, data size, latency, and consistency. Sketch one path, then iterate bottlenecks. Offer two options with tradeoffs. Do not jump to Kafka. Finish with failure modes and how you would see them.",
      "Numbers: 1M users is not a design; 100 writes/s vs 100k reads/s is. Call out SPOFs, data lifetime, and multi-region only if asked. Timebox: requirements, API, data, scale, risks.",
      timeline("Forty-five minutes", [["Ask", "Load and constraints"], ["API", "Core operations"], ["Store", "Data model + size"], ["Scale", "Cache, shard, queue"], ["Break", "Failure and observe"]], "The whiteboard is a conversation about bottlenecks, not a logo collage"),
    ),
  ],
};
