const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Testing & Debugging",
  slug: "testing-debugging",
  description: "Unit testing, integration testing, API testing, debugging, test automation",
  theme: {
    accent: "#16a34a",
    hubFill: "#16a34a",
    hubText: "#ffffff",
    centerFill: "#dcfce7",
    centerStroke: "#16a34a",
    label: "QA",
  },
  beginner: [
    Q(
      "What is a unit test?",
      "A unit test checks one small piece of code in isolation — usually a function or method — with fast, deterministic results.",
      "Interviewers want isolation plus speed. If the test hits a real database or network, it is already an integration test. Name the unit, the input, and the expected output.",
      steps("One piece, one check", [["Pick", "One function or method"], ["Isolate", "Fake slow neighbors"], ["Call", "Known input"], ["Assert", "Expected output"]], "If it needs the whole app, it is not a unit test"),
    ),
    Q(
      "What is the difference between unit, integration, and end-to-end tests?",
      "Unit tests a single piece in isolation. Integration tests several real pieces together. End-to-end tests the product the way a user would, through the UI or full stack.",
      "Cost and flake risk go up as you climb. Use many unit tests, fewer integration tests, and a thin E2E slice. Interviews fail people who call every test a unit test.",
      layers("Scope of a test", [["Unit", "One function, fakes for the rest"], ["Integration", "Two or more real parts talk"], ["E2E / UI", "Browser or full user path"], ["Cost", "Slower and flakier as you go up"]], "Match the test to the risk — not to a buzzword"),
    ),
    Q(
      "What is the AAA pattern in tests?",
      "Arrange sets up data and doubles. Act calls the code under test once. Assert checks the result. One act per test keeps failures easy to read.",
      "Also called Given-When-Then. Mixing setup into the assert makes tests brittle. Interviewers look for a clean three-part shape on the whiteboard.",
      steps("Arrange, Act, Assert", [["Arrange", "Build input and doubles"], ["Act", "Call the unit once"], ["Assert", "Check one outcome"], ["Stop", "Do not add a second act"]], "One action per test — one reason to fail"),
    ),
    Q(
      "What is an assertion?",
      "An assertion is a check that fails the test if the actual value is not what you expected.",
      "expect(x).toBe(3) or assertEqual are assertions. A test with no assertion always passes — a common interview trap. Prefer a specific matcher over a bare boolean true.",
      code("A test is a claim", "sum.test.js", ["test('adds two numbers', () => {", "  const got = add(2, 3)", "  expect(got).toBe(5)", "})"], [["Act", "add(2, 3)"], ["Assert", "toBe(5) fails if not"]], "No assertion means you never proved anything"),
    ),
    Q(
      "What is the difference between a mock and a stub?",
      "A stub returns canned data so the unit can run. A mock also verifies how it was called — arguments, count, or order.",
      "People say mock for every test double. Be precise: stubs supply; mocks expect interactions. Over-mocking makes tests brittle when you refactor internals.",
      compare("Supply vs verify", ["Stub", "Returns a canned value", "No call checks", "Focus on output", "Simple and stable"], ["Mock", "Expects calls too", "Fails if unused", "Focus on interaction", "Easy to over-specify"], "Stub the data — mock only when the call itself is the contract"),
    ),
    Q(
      "What is TDD?",
      "Test-driven development writes a failing test first, then the smallest code to pass, then refactor — red, green, refactor.",
      "The test is a spec. Interviews want the cycle, not I write tests after. TDD shines on clear units; it is awkward for exploratory UI. You can still think test-first without being dogmatic.",
      cycle("Red, green, refactor", "TDD", [["Red", "Write a failing test"], ["Green", "Make it pass, ugly OK"], ["Refactor", "Clean without new behavior"], ["Repeat", "Next tiny behavior"]], "The failing test is the requirement"),
    ),
    Q(
      "What is API testing?",
      "API testing sends HTTP or RPC requests to endpoints and checks status, body, headers, and side effects — without driving a browser.",
      "You test the contract: auth, validation, error codes, idempotency. Tools include REST clients, Postman, pytest, and SuperTest. It sits between unit and E2E on the pyramid.",
      hub("What an API test checks", "API", [["Status", "200 vs 4xx / 5xx"], ["Body", "Shape and values"], ["Auth", "Token or cookie"], ["Headers", "Content-Type, cache"], ["Side", "DB row actually changed"]], "Hit the contract — skip the CSS"),
    ),
    Q(
      "How do you debug a failing test?",
      "Reproduce it locally, read the assertion diff, shrink the input, add a log or breakpoint in the unit, fix one thing, then re-run.",
      "Do not rewrite the test to match a bug. Confirm whether the test or the product is wrong. Flakes need a different hunt: timing, order, or shared state.",
      timeline("From red to green", [["Read", "Assertion message and stack"], ["Reproduce", "Run that test alone"], ["Isolate", "Smallest input"], ["Watch", "Debugger or log"], ["Fix", "One change, re-run"]], "The diff tells you expected vs actual — start there"),
    ),
    Q(
      "What is code coverage?",
      "Coverage is the share of lines, branches, or functions that ran during tests. It maps what you never executed — it is not a score of quality.",
      "100% coverage can still miss bugs: wrong assertions or untested combinations. Interviews like: coverage finds holes; it does not prove correctness.",
      hub("What coverage can say", "Cover", [["Line", "This line ran"], ["Branch", "Both if/else?"], ["Function", "Was it called?"], ["Gap", "Untested path"], ["Not", "The logic is right"]], "A green bar is not a proof"),
    ),
    Q(
      "What is a test runner?",
      "A test runner discovers test files, executes them, reports pass or fail, and often watches or filters by name.",
      "Jest, pytest, JUnit, NUnit, and go test are runners plus assertion libraries. CI calls the same runner. Know how to run one test — that is a live-coding skill.",
      layers("From file to report", [["Discover", "Find test files"], ["Load", "Setup and fixtures"], ["Run", "Each test function"], ["Report", "Pass, fail, skip, time"]], "The runner is the engine — not the assertions"),
    ),
    Q(
      "What is a regression test?",
      "A regression test locks in behavior so a bug you already fixed, or a feature you already shipped, does not come back unnoticed.",
      "The best regression is the smallest test that failed when the bug was live. Interviewers want: write the test first, then fix, so CI catches repeats.",
      compare("New vs back", ["Feature test", "Specifies new behavior", "Written with the change", "May be broad", "Documents intent"], ["Regression test", "Guards a past bug", "Often a tiny repro", "Stays forever", "Documents a scar"], "If it failed once in prod, keep the test"),
    ),
    Q(
      "What is a test double?",
      "A test double is a stand-in for a dependency: dummy, stub, spy, mock, or fake.",
      "A dummy is unused filler. A fake is a working lightweight stand-in, like an in-memory database. Use the weakest double that lets you test the behavior. This is the vocabulary interviewers expect.",
      hub("Stand-ins for neighbors", "Double", [["Dummy", "Unused argument"], ["Stub", "Canned return"], ["Spy", "Records calls"], ["Mock", "Expects calls"], ["Fake", "Simplified real impl"]], "Name the double — do not say mock for all of them"),
    ),
    Q(
      "Why isolate the system under test?",
      "Isolation keeps failures pointing at one unit and keeps tests fast and deterministic.",
      "Shared databases, clocks, and networks cause flakes. If five modules can fail the same test, you cannot localize the bug. Isolation is a design choice — seams and injection — not only a mock library.",
      compare("Alone vs tangled", ["Isolated", "One reason to fail", "Milliseconds", "Deterministic", "Safe in parallel"], ["Coupled", "Many suspects", "Slow I/O", "Env-dependent", "Order bugs"], "If the test needs the universe, it will lie to you"),
    ),
    Q(
      "What makes a good test name?",
      "A good name says the scenario and the expected outcome so a failure is readable in CI without opening the file.",
      "returns_404_when_user_missing beats test1. Interviews read names as documentation. Avoid names that only repeat the method name.",
      steps("Name the claim", [["Unit", "What you call"], ["When", "The situation"], ["Then", "What should happen"], ["Read", "CI line should make sense"]], "The name is the first assertion the human sees"),
    ),
    Q(
      "What is a smoke test?",
      "A smoke test is a tiny suite that checks the build still starts and a few critical paths work — not deep correctness.",
      "Run smoke after deploy. If smoke fails, skip the long suite. Do not confuse smoke with full regression.",
      layers("How far you look", [["Smoke", "Boot plus one happy path"], ["Sanity", "A few key features"], ["Regression", "Broad old behavior"], ["Full", "Pyramid plus E2E"]], "Smoke answers: is it on fire?"),
    ),
  ],
  intermediate: [
    Q(
      "What is the test pyramid?",
      "The pyramid says many fast unit tests at the base, fewer integration tests in the middle, and few E2E tests at the top — because higher tests are slower and flakier.",
      "Mike Cohn popularized the shape. An ice-cream cone (lots of UI tests, few units) is a smell. Interviews want the cost versus confidence tradeoff, not a drawing.",
      layers("Cheap confidence first", [["Many units", "Fast, precise failures"], ["Some integration", "Real seams, still focused"], ["Few E2E", "Critical user journeys"], ["Avoid cone", "UI-only suites melt CI"]], "Width is count — height is cost"),
    ),
    Q(
      "Why are flaky tests dangerous?",
      "A flaky test sometimes fails without a product change. Teams start ignoring red CI, so real failures hide.",
      "Causes include time, order, shared state, network, animation, and retries. Fix or quarantine with an owner — never run it three times until green. Interviewers watch if you treat flakes as a process bug.",
      hub("Why red stops meaning bug", "Flake", [["Time", "Sleep and clocks"], ["Order", "Shared leftover state"], ["Net", "Real HTTP in unit tests"], ["UI", "Animation / race"], ["Retry", "Hides the bug"]], "A flake trains the team to ignore CI"),
    ),
    Q(
      "When should you mock a dependency versus use the real one?",
      "Mock slow, flaky, or expensive neighbors such as network, mail, and clock. Use the real thing when the interaction is the point — SQL dialect, serializer, or framework wiring.",
      "Over-mocking tests your mocks. Under-mocking makes CI slow. Contract tests sit in between: real protocol, fake other side.",
      compare("Fake vs real", ["Mock / stub", "Speed and isolation", "Control error paths", "Can drift from reality", "Good for units"], ["Real collaborator", "True behavior", "Catches wiring bugs", "Needs env and cleanup", "Good for integration"], "Mock the weather — not your own domain logic"),
    ),
    Q(
      "How do you test an HTTP API well?",
      "Cover the happy path, auth failures, validation errors, idempotency, and status codes. Assert the contract shape, not incidental fields.",
      "Seed data, isolate the database, never point at production. Check Content-Type and error shape. Interviews love 401 versus 403 versus 404.",
      steps("An API test loop", [["Auth", "Missing vs bad vs good token"], ["Valid", "Happy body"], ["Invalid", "4xx and message shape"], ["Side", "Persist or not"], ["Idempotent", "Retry the write"]], "Status plus body plus side effect — all three"),
    ),
    Q(
      "What is a contract test?",
      "A contract test checks that a provider still matches what a consumer expects — paths, types, required fields — without running the full E2E stack.",
      "Consumer-driven contracts (Pact-style) publish expectations; the provider verifies them in CI. That catches breaking API changes before the UI team finds them.",
      compare("Full stack vs contract", ["E2E", "Both apps up", "Slow and wide", "Good for journeys", "Hard to localize"], ["Contract", "Schema and examples", "Fast per endpoint", "Good for breaks", "Not a UX test"], "Agree the JSON — do not wait for the browser"),
    ),
    Q(
      "What does CI do for tests?",
      "Continuous integration runs the suite on every change so broken tests block merge instead of surprising production.",
      "Fast jobs first (unit), slower jobs later (integration, E2E). Fail the build on flakes you have not quarantined. Keep artifacts: logs, coverage, screenshots.",
      timeline("Push to signal", [["Push", "Branch or PR"], ["Fast", "Unit and lint"], ["Slow", "Integration / E2E"], ["Gate", "Merge only if green"], ["Report", "Logs and coverage"]], "CI is the always-on interviewer"),
    ),
    Q(
      "How can coverage numbers lie?",
      "Coverage counts execution, not assertion quality. You can hit a line and never check the result. Branch coverage still misses combinations and concurrency.",
      "Gaming 100% with empty tests is worse than an honest 70% on critical paths. Prefer covering risk — auth, money, parsers — over vanity percentages.",
      hub("Green lines, weak tests", "Lie", [["No assert", "Line ran, nothing checked"], ["Happy only", "Error path skipped"], ["Combo", "A and B never together"], ["UI skip", "JS branches unhit"], ["Mutants", "Would still pass"]], "Ask what a test proves — not what it touched"),
    ),
    Q(
      "What is black-box versus white-box testing?",
      "Black-box tests public behavior without looking at internals. White-box uses knowledge of branches and structure to pick cases.",
      "Unit tests often mix both. Equivalence classes and boundaries are black-box techniques; covering an if is white-box. Neither replaces the other.",
      compare("Outside vs inside", ["Black-box", "Public API only", "Boundaries and classes", "Stable to refactors", "May miss a branch"], ["White-box", "Reads the code", "Forces every path", "Brittle if tied to impl", "Good for tricky logic"], "Test what callers need — use internals only to find cases"),
    ),
    Q(
      "How do you debug a bug that only happens in production?",
      "Capture reproduction data (request id, inputs, version), use observability, replay in staging, then bisect with a test that locks the fix.",
      "You cannot attach a debugger to every production box. Feature flags and sampling help. The interview answer is: evidence first, then a regression test, then the patch.",
      steps("Prod-only failure", [["IDs", "Trace, request, user"], ["Logs", "What happened around it"], ["Replay", "Same input in staging"], ["Test", "Write the missing case"], ["Ship", "Fix plus dashboard"]], "If you cannot replay it, you cannot prove the fix"),
    ),
    Q(
      "Why does test isolation and order matter?",
      "Tests that share mutable state — database rows, files, statics — pass alone and fail in the suite, or the reverse, depending on order.",
      "Reset between tests. Parallel workers make this worse. Randomizing order in CI is a feature: it finds hidden coupling.",
      cycle("Clean between tests", "Iso", [["Setup", "Known starting state"], ["Run", "One test"], ["Teardown", "Drop leftovers"], ["Shuffle", "Order must not matter"]], "If test B needs test A, they are not tests — they are a script"),
    ),
    Q(
      "What is a spy versus a mock?",
      "A spy wraps a real or stubbed collaborator and records calls. A mock is usually pre-programmed with expectations that fail if unmet.",
      "Spies are great to assert we sent this email once after a real-ish path. Mocks fail fast on extra calls. Libraries blur the words — say what you verify.",
      compare("Record vs expect", ["Spy", "Mostly real", "After-the-fact checks", "Fewer surprises", "Good for side effects"], ["Mock", "Preset expectations", "Fails extra calls", "Strict collaboration", "Easy to over-mock"], "Spy watches — mock insists"),
    ),
    Q(
      "How do you test error paths and edge cases?",
      "List invalid inputs, empty collections, timeouts, 4xx/5xx from neighbors, and resource exhaustion. Assert the error type or message your callers rely on.",
      "Happy-path-only suites are a senior red flag. Boundary values (0, -1, max int, empty string) still catch bugs. Table-driven cases keep this readable.",
      hub("Where bugs hide", "Edge", [["Empty", "[] and null"], ["Bound", "0, max, off-by-one"], ["Timeout", "Neighbor hung"], ["Auth", "Expired token"], ["Parse", "Malformed body"]], "If you only test the demo input, you tested the demo"),
    ),
    Q(
      "What is a fixture versus a factory?",
      "A fixture is canned data — a file, SQL dump, or object graph. A factory builds instances in code with overrides so each test sets only what it cares about.",
      "Huge shared fixtures become unreadable and couple tests. Factories plus a thin seed scale better. Interviews ask who owns cleanup.",
      compare("Dump vs builder", ["Fixture", "Saved snapshot", "Fast to load", "Opaque fields", "Goes stale"], ["Factory", "Code that builds", "Override per test", "Explicit intent", "Needs a helper"], "Prefer factories when the data shape keeps changing"),
    ),
    Q(
      "How do you structure integration tests against a database?",
      "Use a throwaway schema or container, migrate once, wrap each test in a transaction rollback or truncate, and never point at shared production-like data.",
      "Unique keys per test help parallelism. Assert SQL you care about — constraints and isolation. If tests need a human-restored dump, they will flake.",
      layers("A safe DB test", [["Engine", "Container or local engine"], ["Migrate", "Same as prod path"], ["Per test", "Txn rollback or truncate"], ["Assert", "Rows and constraints"], ["Drop", "Nothing leaks to the next"]], "The database is a collaborator — treat it like one"),
    ),
    Q(
      "What is parameterized or table-driven testing?",
      "One test body, many input/output rows. Failures name the row so you see which case broke.",
      "pytest parametrize, JUnit Params, and Go table tests beat copy-paste. Keep rows independent — no row should need another.",
      code("Many cases, one body", "parse_test.go", ["cases := []struct{ in, want string }{", "  {\"a\", \"A\"},", "  {\"\", \"\"},", "}", "for _, c := range cases { ... }"], [["Row", "One input and want"], ["Loop", "Same asserts"]], "Add a row before you add a branch"),
    ),
  ],
  expert: [
    Q(
      "What is property-based testing?",
      "Property tests generate many random inputs and check invariants that should always hold — for example decode(encode(x)) equals x — instead of a few hand-picked examples.",
      "Hypothesis, QuickCheck, and fast-check are the usual tools. You still need shrinking to a minimal failing input. Combine properties with example tests that pin regressions.",
      steps("From example to property", [["Invariant", "What must always be true"], ["Generate", "Random valid inputs"], ["Check", "Property holds"], ["Shrink", "Smallest counterexample"]], "Examples teach — properties hunt"),
    ),
    Q(
      "How do consumer-driven contract tests work?",
      "The consumer records expected requests and responses. The provider replays those interactions in its CI and fails if it cannot satisfy them.",
      "Pact is the common name. Version the contract. This is how services avoid works in my E2E lab. Provider states set up data for each interaction.",
      timeline("Consumer first", [["Consumer", "Writes an interaction"], ["Publish", "Contract to a broker"], ["Provider", "Verifies against it"], ["Gate", "Break the provider PR"], ["Deploy", "Compatible pairs only"]], "The consumer owns the expectation — the provider proves it"),
    ),
    Q(
      "How do you hunt flaky tests systematically?",
      "Quantify fail rate and which job, reproduce with shuffle and repeats, remove sleeps, freeze time, isolate state, then quarantine only with an owner and an expiry.",
      "Re-running until green is not a fix. Root causes cluster: clock, I/O, order, retry. Expert interviews want a process, not add wait.",
      cycle("Measure then kill", "Flake", [["Detect", "Count and tag"], ["Repro", "Repeat plus random order"], ["Cause", "Time, I/O, shared"], ["Fix", "Determinism"], ["Guard", "No silent retry"]], "A quarantine without an owner is how flakes live forever"),
    ),
    Q(
      "How does observability complement automated tests?",
      "Tests check known cases before release. Observability — logs, metrics, traces — shows unknown failures in production so you can add the missing test.",
      "SLOs, error budgets, and traces are the production suite. You cannot E2E the whole internet. Correlate a trace id from a failing user to a new regression test.",
      layers("Before and after ship", [["Unit / contract", "Known examples"], ["Staging E2E", "Critical journeys"], ["Metrics", "Is it healthy?"], ["Traces", "Where did it stall?"], ["New test", "Lock the prod lesson"]], "Tests are hypotheses — telemetry is the rest of the world"),
    ),
    Q(
      "What is mutation testing?",
      "Mutation testing changes the product code slightly (mutants) and checks that at least one test fails. Survivors mean weak tests.",
      "PIT and Stryker are common tools. Slow, so run on critical modules. Coverage says the line ran; mutation says the test noticed. Equivalent mutants can survive without a real gap.",
      compare("Ran vs noticed", ["Coverage", "Line executed", "Cheap", "No quality of assert", "Easy to game"], ["Mutation", "Would a bug be caught?", "Expensive", "Finds weak tests", "Use on cores"], "If a mutant lives, your suite is polite, not strict"),
    ),
    Q(
      "How do you test distributed systems — timeouts, retries, idempotency?",
      "Inject faults: delay, drop, duplicate, reorder. Assert timeouts fire, retries backoff, and side effects stay idempotent under at-least-once delivery.",
      "Chaos at small scale (proxies, fault flags) beats hoping. Exactly-once is usually at-least-once plus idempotency keys. Interviews love what if the response is lost.",
      hub("Faults you must inject", "Net", [["Delay", "Timeouts fire"], ["Drop", "Client retries"], ["Dup", "No double charge"], ["Reorder", "Version vectors"], ["Clock", "Skew and TTL"]], "If you did not test the timeout, you did not test the system"),
    ),
    Q(
      "What is the testing trophy versus the test pyramid?",
      "The trophy puts more weight on integration tests in a realistic environment and fewer brittle E2E tests and trivial units. The pyramid still puts most count in isolated units.",
      "Kent C. Dodds popularized the trophy as a reaction to over-mocked units and slow Selenium. Pick based on your stack. Both fight an ice-cream cone of UI-only tests.",
      compare("Shape of the suite", ["Pyramid", "Many isolated units", "Thin integration", "Tiny E2E", "Classic backend"], ["Trophy", "Static analysis", "Integration heavy", "Few E2E, few tiny units", "Common in component UI"], "Costly tests stay rare — confidence stays high"),
    ),
    Q(
      "How do you test concurrency and race conditions?",
      "Stress shared mutable state with many threads or async tasks, use thread sanitizers or deterministic schedulers, and assert invariants — not sleeps.",
      "Sleeping 50ms is not a race test. Repeat under load. Design to avoid sharing. Tools and ideas include TSan, JCStress-style suites, and model checkers.",
      steps("Make the race loud", [["Share", "Name the mutable bit"], ["Hammer", "Many concurrent callers"], ["Invariant", "Count or uniqueness"], ["Tool", "Sanitizer or checker"], ["Fix", "Lock, atomic, or do not share"]], "If it needs sleep to pass, it is still racy"),
    ),
    Q(
      "How should CI gates be layered — fast versus slow?",
      "Pre-merge: lint, unit, and cheap contracts in minutes. Post-merge or nightly: full integration, E2E, mutation, performance. Block release on the slow gate, not every push.",
      "The developer feedback loop is a product. Talk required checks versus optional, flake budgets, and sharding. Do not make every PR wait for a 40-minute browser grid.",
      layers("Feedback time vs depth", [["Seconds", "Typecheck / lint"], ["Minutes", "Unit plus contracts"], ["Tens of min", "Integration"], ["Nightly", "E2E, perf, chaos"], ["Release", "All must be green"]], "The slower the job, the later the gate"),
    ),
    Q(
      "What is characterization testing for legacy code?",
      "Characterization (golden) tests lock current behavior — even ugly behavior — so you can refactor with a safety net, then replace them with intent-based tests.",
      "Michael Feathers described this. Capture outputs for known inputs or record HTTP. You are documenting what it does, not what it should. Approval and snapshot tests are cousins — review the snapshot or it rots.",
      steps("Pin, then change", [["Record", "Today's outputs"], ["Pin", "Fail on drift"], ["Refactor", "Structure only"], ["Replace", "Real specs later"]], "Legacy has no spec until you write one from behavior"),
    ),
    Q(
      "How do you test time, randomness, and clocks?",
      "Inject a clock and RNG, or freeze them. Never call Date.now() or Math.random() deep in domain code if you need deterministic tests.",
      "Fake timers, a Clock type, or a timekeeper library. Property tests need a seeded generator. TTL, cron, and token expiry are where hidden now() lives.",
      code("Inject the clock", "tokens.js", ["function isExpired(exp, now) {", "  return now >= exp", "}", "isExpired(100, 100) // true"], [["Seam", "now is an argument"], ["Test", "No real wall clock"]], "If time is global, every expiry test is a flake"),
    ),
    Q(
      "What is the test oracle problem?",
      "An oracle is how you know the correct output. The oracle problem is knowing the right result for generated or complex inputs without a second implementation you trust.",
      "Metamorphic testing (compare f(x) to f(transform(x))) and properties sidestep a full oracle. This research term shows up in senior QA interviews when examples are not enough.",
      hub("How do you know it is right?", "Oracle", [["Example", "Hand-written want"], ["Inverse", "decode(encode(x))"], ["Diff", "Old vs new impl"], ["Human", "Approval / snapshot"], ["Meta", "Relation, not value"]], "Without an oracle, a generator only produces noise"),
    ),
    Q(
      "How do you balance E2E cost versus confidence?",
      "Keep a handful of journey tests for money, auth, and the primary funnel. Push detail down to API and unit tests. Parallelize, stub third parties, and accept that E2E will never be complete.",
      "Talk flake budget, selective browsers, and trace-based debugging of E2E. If E2E is your only suite, you will ship scared or ship late.",
      compare("Journey vs detail", ["E2E", "User-shaped confidence", "High flake and cost", "Few critical paths", "Slow signal"], ["Lower layers", "Precise failures", "Cheap to run", "Most of the spec", "Miss real wiring"], "E2E is a spotlight — not the lighting grid"),
    ),
    Q(
      "How do logs, traces, and metrics help when tests pass locally?",
      "Local green means your examples passed. Production failures need correlation: metrics detect, traces locate, logs explain, then you add a test for that case.",
      "Watch cardinality and PII. OpenTelemetry, exemplars, and careful production testing (dark reads) show up in expert debugging rounds. A passing laptop is not a passing fleet.",
      layers("Three pillars plus a test", [["Metrics", "Something is wrong"], ["Traces", "Which hop"], ["Logs", "Why that hop"], ["Repro", "Smallest input"], ["Test", "Never again"]], "A passing laptop is not a passing fleet"),
    ),
    Q(
      "How do you design code for testability?",
      "Introduce seams: inject collaborators, return values instead of hiding I/O, keep pure domain logic, and avoid singletons and hidden clocks.",
      "Hexagonal / ports-and-adapters is the architecture name. If you cannot test it without the whole framework, the design is the bug. Dependency injection is a means, not a religion.",
      steps("Make a seam", [["I/O at edge", "HTTP, disk, clock"], ["Ports", "Interfaces for neighbors"], ["Pure core", "Easy unit tests"], ["Adapters", "Integration tests here"]], "Testability is a design property — not a library"),
    ),
  ],
};
