const { Q, steps, compare, hub, layers, timeline, cycle, code } = require("../../lib/catVisuals");

module.exports = {
  name: "Web Development",
  slug: "web-development",
  description: "HTML, CSS, HTTP, APIs, authentication, browser concepts",
  theme: {
    accent: "#e34f26",
    hubFill: "#e34f26",
    hubText: "#ffffff",
    centerFill: "#ffedd5",
    centerStroke: "#e34f26",
    label: "Web",
  },
  beginner: [
    Q(
      "What is HTML?",
      "HTML is the markup language that describes the structure of a web page: headings, paragraphs, links, forms, and other elements the browser turns into a document.",
      "Interviews want structure, not styling. CSS paints it; JavaScript behaves. A page without HTML has nothing to render. Semantic tags tell browsers and assistive tech what each piece is.",
      hub("What HTML gives the browser", "HTML", [["Structure", "Headings, lists, forms"], ["Meaning", "Semantic tags"], ["Links", "Navigate the web"], ["Media", "Images, video"], ["Hooks", "ids and classes"]], "HTML is the skeleton — not the paint"),
    ),
    Q(
      "What is the difference between a tag and an element?",
      "A tag is the markup syntax, like <p> and </p>. An element is the whole node in the document: the tags plus the content and nested children.",
      "People say tag when they mean element. Be precise: the p element includes opening tag, text, and closing tag. Void elements like img have no closing tag and no children.",
      compare("Syntax vs the node", ["Tag", "The <p> markup", "Opening or closing", "Written in the file", "<img> is a tag"], ["Element", "The live node", "Tags plus content", "Lives in the DOM", "The whole paragraph"], "The DOM stores elements — source files contain tags"),
    ),
    Q(
      "What is semantic HTML?",
      "Semantic HTML uses tags that describe meaning — header, nav, main, article, button — instead of a soup of divs with the same look.",
      "Screen readers, search engines, and keyboard users get a map of the page. A div styled as a button is not a button: it may miss focus, Enter/Space, and the button role unless you rebuild all of that.",
      steps("Say what it is", [["Pick", "Choose the matching tag"], ["Nest", "Landmarks wrap content"], ["Label", "Headings form an outline"], ["Test", "Tab and a screen reader"]], "If a div can be a real tag, use the real tag"),
    ),
    Q(
      "What is CSS?",
      "CSS is the language that styles HTML: colors, layout, type, and how the page looks at different sizes.",
      "Selectors pick elements; properties set values; cascade and specificity decide which rule wins. Interviews separate structure (HTML) from presentation (CSS) from behavior (JS).",
      hub("What CSS controls", "CSS", [["Color", "Text and backgrounds"], ["Type", "Font, size, line"], ["Layout", "Flex, grid, flow"], ["Space", "Margin and padding"], ["Breakpoints", "Different screens"]], "CSS paints and lays out — it does not fetch data"),
    ),
    Q(
      "What is the CSS box model?",
      "Every element is a box: content, then padding, then border, then margin outside the border. Width and height usually refer to the content box unless you change box-sizing.",
      "Beginners mix padding and margin. Padding is inside the border (space around content). Margin is outside (gap between boxes). box-sizing: border-box is the common reset so width includes padding and border.",
      layers("Inside to outside", [["Content", "Text and children"], ["Padding", "Space inside the border"], ["Border", "The visible edge"], ["Margin", "Gap outside the box"]], "Margin collapses; padding does not"),
    ),
    Q(
      "What is HTTP?",
      "HTTP is the request/response protocol the browser uses to talk to servers: a method, a URL, headers, and often a body — then a status and a body back.",
      "HTTPS is HTTP over TLS. Interviews want: client sends a request, server answers. Cookies, caching, and auth all ride on headers. It is stateless unless you add cookies or tokens.",
      steps("One round trip", [["Request", "Method + URL + headers"], ["Route", "Server picks a handler"], ["Work", "Read DB, build HTML"], ["Response", "Status + headers + body"]], "HTTP is a conversation with a status code at the end"),
    ),
    Q(
      "What is the difference between GET and POST?",
      "GET asks for a resource and should not change server state. POST submits data and may create or trigger work. GET puts params in the URL; POST usually puts them in the body.",
      "Never use GET to delete or charge a card — crawlers and prefetch can fire it. POST is not a security feature by itself. Idempotency is a later question; at beginner level: GET reads, POST sends.",
      compare("Read vs send", ["GET", "Safe to refetch", "No body typically", "Bookmarkable URL", "Cacheable"], ["POST", "May change data", "Body holds payload", "Not a link", "Not cached by default"], "If repeating it should be harmless, it is probably GET"),
    ),
    Q(
      "What do status codes 200, 404, and 500 mean?",
      "200 means success. 404 means the server could not find that resource. 500 means the server hit an unexpected error while handling the request.",
      "2xx success, 3xx redirect, 4xx client problem, 5xx server problem. 401 is unauthenticated; 403 is forbidden. Do not return 200 with an error JSON unless the API already does that — say so if you inherit it.",
      hub("The first digit is the class", "Status", [["2xx", "It worked"], ["3xx", "Go somewhere else"], ["4xx", "Your request is wrong"], ["5xx", "Our server failed"], ["404", "No such resource"]], "Read the class before memorizing every code"),
    ),
    Q(
      "What is the DOM?",
      "The DOM is the browser's live tree of nodes for the page. JavaScript reads and updates it; the renderer turns those nodes into pixels.",
      "HTML is the source. The DOM is the object model after parse (and after scripts mutate it). document.querySelector talks to the DOM, not the original file. Interviews: tree of nodes, not a screenshot.",
      layers("From file to tree", [["HTML file", "Bytes on the wire"], ["Parse", "Tokenizer and tree builder"], ["DOM", "Live node tree"], ["Script", "Can add, remove, change"]], "If JS changed it, View Source may lie"),
    ),
    Q(
      "What is a cookie?",
      "A cookie is a small name/value the server (or a script) stores on the client and the browser sends back on later requests to that site — used for sessions and preferences.",
      "Cookies are scoped by domain and path. HttpOnly stops JS from reading them (helps against XSS stealing sessions). Secure means HTTPS only. They are not a database; size and count are limited.",
      steps("Set, then send", [["Response", "Set-Cookie from the server"], ["Store", "Browser keeps it"], ["Later request", "Cookie header goes out"], ["Server", "Recognizes the session"]], "A cookie is a note the browser carries back"),
    ),
    Q(
      "What is HTTPS and why do we use it?",
      "HTTPS is HTTP over TLS. It encrypts the connection, authenticates the server via certificates, and stops casual tampering of requests and responses.",
      "HTTP on a coffee-shop Wi-Fi can be read and altered. HTTPS does not make your app logic safe — XSS and bad auth still exist. Mixed content (HTTPS page loading HTTP scripts) is a common footgun.",
      compare("In the clear vs wrapped", ["HTTP", "Anyone on the path can read", "Easy to tamper", "No server identity check", "Port 80"], ["HTTPS", "TLS encrypts the bytes", "Certificate names the host", "Required for Secure cookies", "Port 443"], "HTTPS protects the pipe — not your SQL queries"),
    ),
    Q(
      "What is a web API?",
      "A web API is a contract over HTTP: URLs, methods, headers, and body shapes a client can call to read or change data without using the HTML page.",
      "REST JSON APIs are the usual interview example. Same idea as a function signature, but across the network: status codes, versioning, and auth headers. GraphQL and gRPC are other shapes of the same idea.",
      hub("Contract over the network", "API", [["URL", "Which resource"], ["Method", "GET POST PUT DELETE"], ["Headers", "Auth, content type"], ["Body", "JSON payload"], ["Status", "How it went"]], "If a mobile app can call it, you have a web API"),
    ),
    Q(
      "What is the difference between a client and a server?",
      "The client (browser, mobile app) initiates requests and renders UI. The server listens, runs business logic, talks to databases, and sends responses.",
      "JavaScript in the browser is still the client. Node can be a server. Interviews fail people who say 'JavaScript is the backend.' Say where the code runs.",
      compare("Who starts the call", ["Client", "Browser or app", "Renders UI", "Holds user secrets badly", "Can go offline"], ["Server", "Listens on a port", "Enforces rules", "Holds the database", "Must be reachable"], "Trust the server for security — the client can be edited"),
    ),
    Q(
      "What is a CSS selector?",
      "A selector is the pattern that picks which elements a rule applies to — by tag, class, id, attribute, or relationship (child, descendant, sibling).",
      "Specificity decides the winner when rules clash: inline > id > class/attr > tag. !important is a last resort. Keep selectors short so refactors do not break styling.",
      code("Pick nodes, then style", "card.css", [".card { padding: 1rem; }", ".card h2 { margin: 0; }", "button.primary { color: white; }"], [["Class", ".card matches class=card"], ["Descendant", ".card h2 is h2 inside"]], "A selector is a query over the DOM tree"),
    ),
    Q(
      "How do HTML forms submit data?",
      "A form has fields, a method (GET or POST), and an action URL. Submit sends the named fields to that URL; the server reads them and responds with a new page or redirect.",
      "GET forms put fields in the query string (search). POST forms put them in the body (login, create). name attributes matter — unlabeled inputs are dropped. Prevent default in JS if you submit via fetch instead.",
      timeline("From click to response", [["Fill", "User edits inputs"], ["Submit", "Browser builds the payload"], ["Request", "GET query or POST body"], ["Response", "New HTML or redirect"]], "No name on an input means it never leaves the page"),
    ),
  ],
  intermediate: [
    Q(
      "How do width, padding, and box-sizing interact?",
      "By default width is the content box, so padding and border add extra pixels. box-sizing: border-box makes width include content, padding, and border — margin still sits outside.",
      "This is the box-model interview. Horizontal margin does not collapse; vertical margin often does between siblings. 100% width plus padding overflows unless border-box or you subtract padding.",
      layers("What width actually means", [["content-box", "width = content only"], ["+ padding", "Grows the used size"], ["+ border", "Grows again"], ["border-box", "width includes those"], ["+ margin", "Never inside width"]], "border-box is how most design tools think"),
    ),
    Q(
      "When do you use PUT, PATCH, and DELETE?",
      "PUT replaces a resource at a URL (idempotent). PATCH applies a partial update. DELETE removes it. POST creates or triggers an action when you do not have a stable URL yet.",
      "PUT of the same body twice should leave the same state. PATCH may or may not be idempotent — say so. Do not bike-shed REST purity; be consistent and document it.",
      hub("Methods that change data", "HTTP", [["POST", "Create or action"], ["PUT", "Replace the whole"], ["PATCH", "Change some fields"], ["DELETE", "Remove it"], ["Idempotent", "Same result if retried"]], "Interviews want idempotency, not dogma"),
    ),
    Q(
      "How do cookies differ from localStorage?",
      "Cookies are sent on matching HTTP requests (with size and count limits). localStorage stays in the browser, is not sent automatically, and is larger. sessionStorage is like localStorage but per tab.",
      "Do not store secrets in localStorage — any XSS can read it. Session ids belong in HttpOnly Secure cookies. localStorage is fine for theme or a cache of public data. Cookies can be SameSite-restricted.",
      compare("Sent vs local only", ["Cookie", "Goes to the server", "~4 KB each", "HttpOnly possible", "CSRF risk if sent"], ["localStorage", "JS origin only", "A few MB", "Any script can read", "Survives the tab"], "If the server must see it, use a cookie — if not, do not send it"),
    ),
    Q(
      "What is CORS and why does the browser block some requests?",
      "CORS is a browser rule: a page on origin A may not read a response from origin B unless B opts in with Access-Control-Allow-Origin (and friends). The server may still receive the request.",
      "It protects users, not your API from curl. Simple GET/POST may skip preflight; custom headers and JSON POST often trigger OPTIONS. Credentials need Allow-Credentials and a specific origin, not *.",
      steps("Cross-origin read", [["Page", "https://app.example"], ["Call", "https://api.other"], ["Browser", "Checks ACAO headers"], ["Allow", "JS may read the body"]], "CORS is a read gate in the browser — Postman is not a browser"),
    ),
    Q(
      "What makes an HTTP API RESTful in interview terms?",
      "Resources have URLs, methods mean something (GET read, POST create), representations are JSON or similar, and status codes reflect the outcome. Clients do not call random RPC names as the only design.",
      "True REST includes hypermedia; most teams mean resource-oriented JSON. Versioning, pagination, and error shapes matter more than whether you say REST or HTTP API. Be honest about RPC-style endpoints.",
      hub("Practical REST", "REST", [["Nouns", "/orders/12"], ["Verbs", "HTTP methods"], ["Status", "201, 404, 409"], ["JSON", "Shared shape"], ["Stateless", "Auth on each call"]], "REST is a style — consistency beats slogans"),
    ),
    Q(
      "Session cookies versus tokens for authentication — how do you choose?",
      "A session cookie stores an id; the server looks up the session. A token (often JWT in Authorization: Bearer) is sent by the client and verified without a server lookup if it is self-contained.",
      "Cookies with HttpOnly + Secure + SameSite fit first-party web apps and fight XSS theft. Tokens in localStorage are easy to steal with XSS. JWTs still need revocation or short TTL. Same-site vs cross-site APIs change the answer.",
      compare("Server session vs bearer", ["Cookie session", "Id in HttpOnly cookie", "Revoke in the DB", "CSRF to consider", "Great for same-site web"], ["Bearer token", "Client stores and sends", "Scales if stateless", "XSS can steal it", "Great for mobile/APIs"], "Where you store the secret matters more than JWT vs opaque"),
    ),
    Q(
      "How does the browser turn HTML and CSS into pixels?",
      "Parse HTML to the DOM, parse CSS to the CSSOM, combine into a render tree, layout (reflow) sizes and positions, then paint and composite layers to the screen.",
      "Scripts can block parsing. Images do not block HTML parse the same way. Changing layout properties is costlier than compositor-only changes (transform, opacity). This is the rendering pipeline interview.",
      timeline("Critical rendering path", [["Parse", "DOM + CSSOM"], ["Render tree", "Visible nodes only"], ["Layout", "Geometry"], ["Paint", "Fill pixels"], ["Composite", "Layers to screen"]], "Reflow is layout — paint is drawing — they are not the same cost"),
    ),
    Q(
      "What is web accessibility (a11y) in practice?",
      "Accessibility means people can use the page with keyboards, screen readers, zoom, and other assistive tech — correct semantics, labels, contrast, and focus management.",
      "alt on images, label tied to input, visible focus, heading order, do not rely on color alone. ARIA is for gaps, not a replacement for HTML. Interviews: name, role, value — can a screen reader announce the control?",
      steps("Can a keyboard user finish the task?", [["Semantics", "Real buttons and inputs"], ["Names", "Labels and alt"], ["Focus", "Visible and logical"], ["Contrast", "Text still readable"]], "If you cannot tab to it, many users cannot use it"),
    ),
    Q(
      "What do Cache-Control and ETag do?",
      "Cache-Control tells browsers and CDNs whether to store a response and for how long (max-age, no-store, private). ETag (and Last-Modified) lets the client revalidate with If-None-Match and get 304 Not Modified.",
      "HTML often no-cache or short TTL; hashed JS/CSS can be immutable max-age=31536000. Authorization responses are usually private. Wrong caching serves stale personalized pages — a classic outage.",
      hub("Caching headers", "Cache", [["max-age", "Fresh for N seconds"], ["no-store", "Do not write it"], ["private", "Browser, not CDN"], ["ETag", "Revalidate cheaply"], ["304", "Use what you have"]], "Cache what is public and versioned — not the user's cart"),
    ),
    Q(
      "What is client-side rendering versus server-side rendering?",
      "CSR sends a shell and JS builds the DOM in the browser. SSR sends HTML already filled in; JS may hydrate to attach events. SSR is faster for first paint and crawlers; CSR can feel snappier after load.",
      "SPAs are often CSR. Next.js and similar can SSR or hybrid. SEO and LCP usually favor SSR or static HTML. Time-to-interactive can still be slow if the JS bundle is huge.",
      compare("Where the HTML is born", ["CSR", "JS builds the tree", "One API-ish page", "Weaker first paint", "Needs JS on"], ["SSR", "Server sends HTML", "Faster first content", "Hydrate after", "More server CPU"], "First meaningful paint vs interactivity — name which you optimize"),
    ),
    Q(
      "What is the same-origin policy?",
      "An origin is scheme + host + port. Scripts from origin A cannot read another origin's DOM or responses unless CORS or a cooperating API allows it. Cookies are also origin-scoped with extra site rules.",
      "https://a.com and https://a.com:443 are the same; http vs https is not. Subdomains are different origins. SOP is why CORS exists. document.domain tricks are legacy — do not rely on them.",
      layers("What counts as origin", [["Scheme", "http vs https"], ["Host", "www vs api"], ["Port", ":3000 vs :443"], ["SOP", "No silent cross-read"]], "Same site is not the same as same origin — cookies taught us that"),
    ),
    Q(
      "Why do Content-Type and Accept headers matter?",
      "Content-Type says what the body is (application/json, application/x-www-form-urlencoded). Accept says what the client wants back. Servers branch on these for JSON vs HTML vs XML.",
      "A JSON API that forgets Content-Type confuses clients. CSRF used to exploit form POSTs because simple content types skip CORS preflight. Sending JSON often triggers preflight — that is a feature.",
      compare("What you send vs what you want", ["Content-Type", "Describes the body", "Set on requests with a body", "Server parses accordingly", "Wrong type = 415"], ["Accept", "Client preference", "Drives content negotiation", "Accept: application/json", "Server may still ignore"], "Never guess JSON — declare it"),
    ),
    Q(
      "When do query parameters belong versus a request body?",
      "Query strings are for filters, pagination, and idempotent reads — they show in logs and history. Bodies carry larger or sensitive payloads and writes (POST/PUT/PATCH).",
      "Do not put passwords in the query string. GET with a body is not portable. Arrays in query strings need a convention. Interviews: cache keys include the query; bodies are not cached the same way.",
      compare("URL vs payload", ["Query", "Visible, shareable", "Great for GET filters", "Length limits", "Logged everywhere"], ["Body", "Not in the URL", "JSON objects", "POST/PUT/PATCH", "Not a cache key"], "If it must not leak in a screenshot, keep it out of the URL"),
    ),
    Q(
      "How do HTTP redirects work?",
      "The server answers with 3xx and a Location URL. 301/308 are permanent; 302/307 are temporary. 307/308 keep the method; older 301/302 may turn POST into GET in some clients.",
      "Login flows use 302 to the app after setting a cookie. APIs should rarely redirect POST. Open redirects (Location from user input) are a phishing hole. HSTS is a different redirect story (HTTP to HTTPS).",
      steps("Follow Location", [["Request", "Original URL"], ["3xx", "Status + Location"], ["New request", "Browser fetches that"], ["Final", "2xx or another hop"]], "Know whether the method stays PUT or becomes GET"),
    ),
    Q(
      "How do you reduce XSS risk on a typical site?",
      "Encode untrusted text when inserting into HTML, use textContent over innerHTML, set a Content-Security-Policy, and keep secrets out of JS-readable storage.",
      "XSS means attacker script runs as the user. Templating that auto-escapes helps. dangerouslySetInnerHTML is a smell. HttpOnly cookies limit session theft but not in-page actions. CSP is defense in depth.",
      hub("Stop attacker HTML from becoming script", "XSS", [["Escape", "On output, not input"], ["CSP", "Block inline script"], ["HttpOnly", "Hide session cookie"], ["Sanitize", "If you must allow HTML"], ["No eval", "Do not run strings"]], "Treat every user string as data until it is encoded"),
    ),
  ],
  expert: [
    Q(
      "How does a CORS preflight work?",
      "For non-simple requests the browser sends OPTIONS with Access-Control-Request-Method and Request-Headers. The server must reply with Allow-Origin, Allow-Methods, Allow-Headers (and Max-Age). Only then does the real request go.",
      "Simple requests (GET/POST form types, few headers) skip preflight — which is why cookie-based CSRF existed. JSON + Authorization almost always preflights. * cannot pair with credentials. Debug with the OPTIONS response, not only the POST.",
      timeline("Preflight then the real call", [["JS fetch", "JSON or custom header"], ["OPTIONS", "Ask permission"], ["Allow-*", "Server opts in"], ["Actual", "GET/POST/PUT..."], ["Read", "JS gets the body"]], "If OPTIONS 404s, the POST never happens"),
    ),
    Q(
      "Cookies versus tokens at the CSRF and XSS layer — what actually fails?",
      "Cookies are sent automatically, so CSRF tricks the browser into a state-changing request unless you use SameSite, CSRF tokens, or custom headers. Bearer tokens are not sent automatically, so CSRF is weaker, but XSS can steal tokens from JS storage.",
      "Expert answer: first-party cookie sessions + SameSite=Lax/Strict + CSRF token for old browsers. SPA + public API often uses Authorization header and must crush XSS. JWT in localStorage is an XSS time bomb. HttpOnly cookie cannot be stolen by script but CSRF remains.",
      compare("Automatic send vs explicit header", ["Cookie", "Browser attaches it", "CSRF is the threat", "HttpOnly hides from JS", "SameSite helps"], ["Token in JS", "You set Authorization", "XSS steals it", "No automatic CSRF", "Needs short TTL / rotate"], "Pick the threat model — XSS vs CSRF — then pick storage"),
    ),
    Q(
      "How does the browser event loop work?",
      "JavaScript is single-threaded. The event loop takes a macrotask (timer, I/O, event), runs it to completion, then drains the microtask queue (promises, queueMicrotask) before painting and the next macrotask.",
      "Promise.then runs before setTimeout(0). A tight microtask loop starves rendering. async/await is promises. Web APIs sit outside the call stack. This is the expert web question that separates 'I used React' from 'I know the runtime.'",
      cycle("Stack, then queues", "Loop", [["Stack", "Run JS to empty"], ["Microtasks", "Promises first"], ["Render", "Maybe paint"], ["Macrotask", "Next timer/event"]], "Never await in a hot loop without yielding — you will freeze the tab"),
    ),
    Q(
      "How would you design caching with Cache-Control, ETags, and a CDN?",
      "Put long-lived immutable assets on a CDN with hashed filenames. HTML and JSON that can change get short max-age plus ETag revalidation, or stale-while-revalidate. Personalized responses are private or uncached at the edge.",
      "s-maxage talks to shared caches. Vary: Accept-Encoding/Cookie can explode cache keys. PURGE on deploy. 304 saves bandwidth but not always TTFB if origin is hit. Expert: cache poisoning via unsigned headers.",
      layers("Who may store the bytes", [["Browser", "private, max-age"], ["CDN", "s-maxage, public"], ["Revalidate", "ETag / 304"], ["Stale", "SWR serves old, fetches new"], ["Bypass", "no-store for secrets"]], "A CDN that caches Set-Cookie pages will leak users"),
    ),
    Q(
      "CSR, SSR, and hydration — what goes wrong in production?",
      "SSR HTML must match what the client renders on hydrate or React (and others) warn and detach. CSR-only apps hurt LCP and SEO. Heavy hydration blocks the main thread even when HTML arrived fast.",
      "Streaming SSR and selective hydration reduce TTI. Islands / server components send less client JS. Expert interviews want: mismatch causes (Date.now, random ids, invalid HTML), and when static generation beats per-request SSR.",
      hub("First HTML vs attach JS", "SSR", [["HTML", "Fast content, SEO"], ["Hydrate", "Replay events on that HTML"], ["Mismatch", "IDs, dates, locale"], ["Cost", "Download and run JS"], ["CSR only", "Blank until JS"]], "Hydration is not free — it is a second render you hope matches"),
    ),
    Q(
      "What does TLS actually guarantee for HTTPS?",
      "TLS authenticates the server (certificate chain to a trusted CA), encrypts the stream, and provides integrity so a middlebox cannot silently edit bytes. It does not authenticate your user until your app does.",
      "Certificate pinning is rare on the web. MITM with a corporate CA is real on managed devices. HSTS stops SSL stripping. TLS 1.3 dropped old ciphers. HTTPS is necessary and not sufficient for 'secure.'",
      steps("Trust the host, then encrypt", [["DNS", "You still need the right IP"], ["Cert", "Name matches, chain valid"], ["Handshake", "Keys agreed"], ["HTTP", "Now encrypted"], ["App auth", "Still your job"]], "A green padlock means the pipe is private — not that the site is honest"),
    ),
    Q(
      "How do SameSite cookies change CSRF?",
      "SameSite=Lax sends cookies on top-level GET navigations but not on most cross-site POSTs. Strict withholds even those. None requires Secure and is for true cross-site (embedded) use.",
      "Lax is the modern default in Chrome. Cross-site APIs that need cookies must use SameSite=None; Secure and CORS credentials. CSRF tokens still matter for same-site subdomains and older browsers. CHIPS / partitioned cookies are the next chapter.",
      hub("Cookie attachment rules", "Site", [["Strict", "Almost never cross-site"], ["Lax", "Top-level GET only"], ["None", "Cross-site if Secure"], ["CSRF", "Still think about POST"], ["CORS", "Credentials mode"]], "SameSite is CSRF mitigation — not an XSS fix"),
    ),
    Q(
      "What is the critical rendering path and how do you shorten it?",
      "It is the work from first byte to first paint: download HTML, CSS (render-blocking), fonts, and often JS. Shrink it with fewer blocking CSS, defer/async scripts, preload of the hero font/image, and server-timing budgets.",
      "CSS in the head blocks first paint to avoid FOUC. Huge CSS = late FCP. JS in the head without defer blocks parse. Expert: measure LCP element, TTFB vs download vs render, and do not guess.",
      timeline("Bytes to first paint", [["TTFB", "Server + network"], ["HTML", "Discover CSS/JS"], ["CSS", "Blocks paint"], ["Layout/paint", "CPU"], ["LCP", "Largest element shown"]], "If CSS is late, the user stares at white — not at your JS"),
    ),
    Q(
      "What is Content-Security-Policy doing for you?",
      "CSP is a allowlist of where scripts, styles, images, and connections may come from. A strict policy (no unsafe-inline, nonces or hashes) makes XSS much harder to turn into running code.",
      "unsafe-inline undoes the main win. report-uri/report-to help you roll out. CSP does not replace encoding. frame-ancestors fights clickjacking. Expert: nonce per response, strict-dynamic, and that CSS injection is still a thing.",
      layers("Policy layers", [["default-src", "Fallback allowlist"], ["script-src", "Who may run JS"], ["nonce/hash", "Allow this exact script"], ["connect-src", "Who fetch may call"], ["Report", "See violations"]], "CSP is defense in depth — a nonce does not fix innerHTML habits"),
    ),
    Q(
      "How is HTTP/2 different from HTTP/1.1 for a web app?",
      "HTTP/1.1 is one response per TCP connection at a time (plus a few parallel sockets). HTTP/2 multiplexes many streams on one connection, compresses headers, and can server-push (rarely useful now). HTTP/3 uses QUIC/UDP.",
      "You no longer concatenate files just to beat six-connection limits — hashing and HTTP/2 is enough. Head-of-line blocking still exists at TCP for HTTP/2; HTTP/3 reduces that. Interviews: multiplexing, HPACK, and that HTTPS is assumed.",
      compare("One file at a time vs streams", ["HTTP/1.1", "Head-of-line on the socket", "Many connections", "Verbose headers", "Sprite/concat tricks"], ["HTTP/2", "Multiplexed streams", "One connection typical", "HPACK headers", "Still TLS + TCP"], "Stop concatenating JS for connection limits — measure instead"),
    ),
    Q(
      "How do microtasks interact with rendering and requestAnimationFrame?",
      "After a task, microtasks run to completion before the browser paints. rAF callbacks run before the next paint. Infinite Promise.resolve().then chains can delay rAF and make the UI jank.",
      "Use setTimeout or scheduler.yield to break work. await in a loop still queues microtasks per iteration. This is the expert event-loop follow-up: not just 'promises vs timeouts,' but frames.",
      cycle("Before the next frame", "Frame", [["Task", "Click handler"], ["Microtasks", "All then()"], ["rAF", "Read/write DOM"], ["Paint", "Pixels"], ["Idle", "requestIdleCallback"]], "If you never empty the microtask queue, you never paint"),
    ),
    Q(
      "What does good accessibility look like beyond alt text?",
      "Correct name, role, and value for every control; focus order matches the visual flow; live regions for async updates; no keyboard traps; WCAG contrast; respect prefers-reduced-motion.",
      "ARIA overrides native semantics — wrong role is worse than none. aria-label on a div is not a button. Dialogs need focus trap and restore. Expert: testing with a screen reader, not only an axe scan.",
      hub("Name, role, value", "A11y", [["Name", "What to speak"], ["Role", "What it is"], ["Value", "Checked, expanded"], ["Focus", "Where am I?"], ["Live", "What just changed"]], "If VoiceOver lies, your semantics are wrong — not the user"),
    ),
    Q(
      "Which HTTP methods are idempotent and why do retries care?",
      "GET, PUT, DELETE, HEAD, OPTIONS are idempotent by spec: repeating them should not change the result after the first success. POST is not. PATCH is not required to be. 409/412 help you reject stale writes.",
      "Timeouts happen; clients retry. Without idempotency keys, POST creates two orders. PUT with If-Match ETag is a safe upsert. Expert web + API design: at-least-once delivery is the default on the internet.",
      compare("Safe to send twice?", ["Idempotent", "GET PUT DELETE", "Same state after N calls", "Retry on timeout", "Use ETags for races"], ["Not (usually)", "POST, many PATCH", "Two calls, two creates", "Need Idempotency-Key", "Webhooks too"], "If the client might retry, the server must survive a duplicate"),
    ),
    Q(
      "How do service workers change caching and HTTPS?",
      "A service worker is a programmable network proxy in the browser. It can cache responses, serve offline, and intercept fetch. It only registers on HTTPS (or localhost).",
      "You now have two caches: HTTP Cache-Control and the Cache Storage API. Stale SW can brick a deploy — version and skipWaiting carefully. Expert: cache-first vs network-first vs stale-while-revalidate, and never cache personalized HTML blindly.",
      steps("Install, then intercept", [["Register", "HTTPS page loads SW"], ["Install", "Precache shell"], ["Activate", "Take control"], ["Fetch", "Your strategy runs"]], "A service worker is a second origin of truth — treat deploys as cache invalidation"),
    ),
    Q(
      "How would you debug mixed content, CORS, and a 'it works in Postman' report?",
      "Reproduce in the browser Network tab: scheme, preflight, ACAO vs origin, credentials, and whether JS is blocked from reading. Mixed content is HTTP assets on an HTTPS page — upgrade or CSP. Postman has no SOP.",
      "Expert path: copy as fetch, check OPTIONS, Vary, redirect stripping Authorization, and wildcard origin plus cookies. Console mixed-content warnings are not CORS. Fix the server headers or the calling origin — not by disabling the browser.",
      timeline("Browser is the real client", [["Reproduce", "Same origin and cookies"], ["OPTIONS", "Preflight status"], ["Headers", "ACAO, credentials"], ["Scheme", "HTTPS vs HTTP"], ["Fix", "Server or call site"]], "Postman success only proves the TCP path — not the browser policy"),
    ),
  ],
};
