module.exports = {
  name: "C++",
  description:
    "C++ interview questions — RAII, value categories, templates, undefined behavior, and concurrency.",
  match: /^\s*c\+\+\s*$/i,
  theme: {
    accent: "#00599C",
    hubFill: "#00599C",
    hubText: "#ffffff",
    centerFill: "#dbeafe",
    centerStroke: "#00599C",
    label: "C++",
  },
  beginner: [
    {
      q: "How does C++ relate to C?",
      a: "C++ started as C with classes and remains a multi-paradigm language: you can write C-like procedural code, RAII classes, generics (templates), and some functional style. It is not a strict superset of modern C.",
      e: "Valid C is not always valid C++ (C99 VLAs, designated init differences, implicit void* casts). Interviews want you to say you compile as C++, use the standard library, and avoid treating C++ as “C plus classes.”",
      visual: {
        title: "C++ as more than C",
        kind: "hub",
        hub: "C++",
        nodes: [
          { h: "C subset", lines: ["Mostly, not fully"] },
          { h: "Classes", lines: ["RAII · ctors"] },
          { h: "Templates", lines: ["Compile-time gen"] },
          { h: "STL", lines: ["Containers · algos"] },
          { h: "Overload", lines: ["Names + operators"] },
          { h: "UB", lines: ["Stricter pitfalls"] },
        ],
        footer: "Compile C++ as C++ — do not mix dialects in one TU casually",
      },
    },
    {
      q: "What are the stages of translating a C++ program?",
      a: "The preprocessor runs macros and includes. The compiler parses each translation unit into object code. The linker resolves symbols across units and libraries into an executable or library.",
      e: "Templates and inline functions are instantiated per translation unit, which is why ODR matters. Precompiled headers and modules (C++20) exist to cut this cost. Most “it compiles but won’t link” bugs are missing definitions or ABI mismatch.",
      visual: {
        title: "Preprocess, compile, link",
        kind: "compare",
        left: {
          h: "Compile (per .cpp)",
          lines: ["Preprocessor first", "One translation unit", "Templates instantiate", "Emits .o / .obj"],
        },
        right: {
          h: "Link (whole program)",
          lines: ["Resolve symbols", "Merge duplicates (COMDAT)", "Pull in libraries", "Fail on ODR / missing defs"],
        },
        footer: "Headers are copied into TUs — they are not a linking unit",
      },
    },
    {
      q: "How should you initialize built-in types and objects?",
      a: "Uninitialized automatic scalars have indeterminate values (reading them is UB). Prefer brace initialization: int n{0}; and T obj{args}. Direct, copy, and list initialization have different rules for narrowing and explicit constructors.",
      e: "int n; in a function is not zero. Static storage duration objects are zero-initialized first. {} can call an initializer_list constructor when you did not mean to. Know value-init vs default-init for interviews.",
      visual: {
        title: "Initialize before you read",
        kind: "steps",
        steps: [
          { h: "Declare local", lines: ["int n; is junk"] },
          { h: "Brace-init", lines: ["int n{0};"] },
          { h: "Objects", lines: ["T t{args};"] },
          { h: "Avoid narrowing", lines: ["{} rejects int from 1.2"] },
        ],
        footer: "Reading an uninitialized automatic scalar is undefined behavior",
      },
    },
    {
      q: "What is the difference between a pointer and a reference?",
      a: "A pointer is an object that holds an address; it can be reseated and can be null. A reference is an alias for an existing object; it must be bound at initialization and cannot be null in well-formed code.",
      e: "Prefer references in function parameters when null is not allowed. Pointers model optional or reseatable addresses. References are not reseatable, so they do not have their own identity in the abstract machine the way pointers do.",
      visual: {
        title: "Pointer vs reference",
        kind: "code",
        code: {
          file: "alias.cpp",
          code: [
            "int x = 3;",
            "int* p = &x;",
            "int& r = x;",
            "p = nullptr; // ok",
            "r = 4;       // assigns x",
          ],
          notes: [
            { h: "Pointer", text: "Object that stores an address, maybe null" },
            { h: "Reference", text: "Another name for x — must bind immediately" },
            { h: "Assign", text: "r = 4 writes through to x, does not rebind" },
          ],
        },
        footer: "You cannot reseat a reference — assignment writes the referent",
      },
    },
    {
      q: "Where do stack and free-store (heap) objects live?",
      a: "Automatic objects live in the current function’s stack frame and die when the frame unwinds. new allocates on the free store and lives until delete (or until a smart pointer destroys it).",
      e: "Stack is fast and exception-safe via destructors. Heap is for variable lifetime and size. Forgetting delete is a leak; double delete is UB. Prefer containers and unique_ptr over raw new. Stack overflow is a real limit for huge locals.",
      visual: {
        title: "Lifetime by storage",
        kind: "layers",
        layers: [
          { h: "Automatic (stack)", lines: ["Locals · destroyed on scope exit"] },
          { h: "Static / thread", lines: ["Live for the program or the thread"] },
          { h: "Free store", lines: ["new / malloc — you own the lifetime"] },
        ],
        footer: "RAII ties free-store lifetime to a stack object’s destructor",
      },
    },
    {
      q: "What is the difference between class and struct in C++?",
      a: "The only language difference is default access: class members and bases are private by default; struct members and bases are public by default. Both can have methods, constructors, and virtual functions.",
      e: "Teams use struct for aggregates and class for encapsulated types — that is convention, not a compiler rule. Aggregate initialization requires public members and other constraints that evolved across standards.",
      visual: {
        title: "Default access is the real difference",
        kind: "timeline",
        events: [
          { h: "struct S", lines: ["public: is implied"] },
          { h: "class C", lines: ["private: is implied"] },
          { h: "Add members", lines: ["Methods and ctors on either"] },
          { h: "Convention", lines: ["struct = data, class = API"] },
        ],
        footer: "Compilers do not treat struct as “POD” just because of the keyword",
      },
    },
    {
      q: "What do constructors and destructors do?",
      a: "A constructor initializes an object as it comes to life. A destructor runs when the object’s lifetime ends and should release what the object owns.",
      e: "Initialization order is bases then members in declaration order, not the member-initializer-list order. Never throw from a destructor (or mark it noexcept and keep that promise). If you define one of the special members, consider all five.",
      visual: {
        title: "Construct, use, destroy",
        kind: "cycle",
        center: "object",
        items: [
          { h: "allocate", lines: ["Storage exists"] },
          { h: "constructor", lines: ["Lifetime starts"] },
          { h: "use", lines: ["Invariants hold"] },
          { h: "destructor", lines: ["Release owners"] },
        ],
        footer: "Members construct in declaration order — list them that way",
      },
    },
    {
      q: "What does const mean on variables and member functions?",
      a: "const on an object means you will not modify it through that name. A const member function cannot mutate non-mutable members and is the overload used on const objects.",
      e: "const is a compiler-enforced documentation of intent and enables more overloads (begin() const). It is not deep: a const pointer to non-const data can still mutate. mutable is the escape hatch for caches. Prefer const references for read-only parameters.",
      visual: {
        title: "const as a contract",
        kind: "hub",
        hub: "const",
        nodes: [
          { h: "const T", lines: ["Object not mutated"] },
          { h: "T const*", lines: ["Pointer to const"] },
          { h: "T* const", lines: ["Const pointer"] },
          { h: "method const", lines: ["this is const T*"] },
          { h: "mutable", lines: ["Logical const cache"] },
          { h: "refs", lines: ["const T& params"] },
        ],
        footer: "Read declarations right-to-left: pointer const vs pointee const",
      },
    },
    {
      q: "Why do headers, source files, and include guards exist?",
      a: "Declarations live in headers so many translation units can see a type or function. Definitions usually live in one .cpp. Include guards or #pragma once stop a header from exploding when included twice.",
      e: "Putting a non-inline definition in a header violates the ODR if included twice. Templates and inline functions are the usual header definitions. Forward-declare when a pointer/reference is enough to cut include graphs.",
      visual: {
        title: "Header vs translation unit",
        kind: "compare",
        left: {
          h: "Header (.h / .hpp)",
          lines: ["Declarations", "inline / templates", "Include guards", "Minimal includes"],
        },
        right: {
          h: "Source (.cpp)",
          lines: ["One definition", "Heavy includes OK", "Hidden helpers", "The actual TU"],
        },
        footer: "Include what you use — forward-declare what you only point to",
      },
    },
    {
      q: "How do namespaces work?",
      a: "A namespace groups names to avoid collisions (std, your company prefix). Nested namespaces and namespace aliases are common. using-declarations import selected names; using-directives (using namespace) import them all.",
      e: "Never put using namespace std; in a header — it pollutes every consumer. Argument-dependent lookup (ADL) finds operators in associated namespaces. Inline namespaces are an ABI versioning trick.",
      visual: {
        title: "Qualify, then maybe import",
        kind: "steps",
        steps: [
          { h: "Declare", lines: ["namespace acme { }"] },
          { h: "Qualify", lines: ["acme::Widget"] },
          { h: "using-decl", lines: ["using acme::Widget"] },
          { h: "Avoid in headers", lines: ["using namespace std"] },
        ],
        footer: "Headers must keep the global namespace clean for their clients",
      },
    },
    {
      q: "What is function overloading?",
      a: "Multiple functions may share a name if their parameter lists differ. The compiler picks the best viable overload. Name mangling encodes the signature so the linker can tell them apart.",
      e: "Return type alone does not overload. Implicit conversions create surprising winners — too many overloads are a maintenance trap. Templates participate and can be more greedy than you want; use constraints or deleted overloads.",
      visual: {
        title: "One name, several signatures",
        kind: "code",
        code: {
          file: "over.cpp",
          code: [
            "void print(int);",
            "void print(const char*);",
            "print(3);",
            "print(\"hi\");",
          ],
          notes: [
            { h: "Rules", text: "Best viable function after conversions" },
            { h: "Mangling", text: "Linker sees different symbol names" },
            { h: "Trap", text: "Return type is not part of the overload key" },
          ],
        },
        footer: "Overload on parameters — not on return type alone",
      },
    },
    {
      q: "Why prefer RAII over naked new and delete?",
      a: "RAII binds a resource to an object whose destructor releases it. Stack unwinding then frees memory, files, and locks even when an exception fires. unique_ptr and containers are RAII; new/delete pairs are not.",
      e: "Every new needs a matching delete on every path, including exceptions and early returns — humans miss those. Never mix new[] with delete. If you must use new, immediately hand the pointer to a smart pointer.",
      visual: {
        title: "Resource tied to a destructor",
        kind: "layers",
        layers: [
          { h: "Acquire", lines: ["Constructor takes the resource"] },
          { h: "Use", lines: ["Object in scope — exception-safe"] },
          { h: "Release", lines: ["Destructor always runs on unwind"] },
          { h: "Avoid", lines: ["Bare new/delete across a function"] },
        ],
        footer: "If a destructor owns it, exceptions cannot leak it",
      },
    },
    {
      q: "When do you use a C array versus std::vector?",
      a: "A C array has a compile-time size and decays to a pointer. std::vector is a resizable contiguous buffer that owns its memory and carries a size.",
      e: "Prefer std::array for fixed-size stack buffers and vector for dynamic lists. Passing a raw array loses length. vector::operator[] is unchecked; at() throws. Small-vector optimizations exist in some libraries, not in std::vector’s spec.",
      visual: {
        title: "Fixed buffer vs owning vector",
        kind: "timeline",
        events: [
          { h: "Need N known", lines: ["std::array<T, N>"] },
          { h: "Need grow", lines: ["std::vector<T>"] },
          { h: "Pass around", lines: ["span or const vector&"] },
          { h: "Avoid decay", lines: ["Do not pass T[] as T*"] },
        ],
        footer: "vector knows its size — a decayed pointer does not",
      },
    },
    {
      q: "How should you pass arguments: value, reference, or pointer?",
      a: "Pass cheap types by value. Pass read-only large objects as const T&. Pass optional or reseatable addresses as T* or optional<T>. Pass ownership with unique_ptr<T> by value.",
      e: "Copying a vector by value is expensive unless you meant to sink it (std::move). Non-const T& is an out-parameter — make that obvious. C++17 guaranteed copy elision helps returns; still write return local; not return std::move(local) for locals.",
      visual: {
        title: "Choose a passing convention",
        kind: "cycle",
        center: "pass",
        items: [
          { h: "by value", lines: ["Cheap or sink"] },
          { h: "const T&", lines: ["Read large"] },
          { h: "T&", lines: ["Out-param"] },
          { h: "T*", lines: ["Optional addr"] },
          { h: "unique_ptr", lines: ["Transfer own"] },
        ],
        footer: "Signatures are contracts — encode nullability and ownership",
      },
    },
    {
      q: "What is the difference between enum and enum class?",
      a: "A classic enum dumps enumerators into the surrounding scope and implicitly converts to integers. enum class (scoped enum) keeps names inside the enum and does not convert to int without a cast.",
      e: "Prefer enum class to avoid name clashes and accidental arithmetic. You can specify the underlying type (enum class Color : uint8_t). Switch on scoped enums needs the qualifier or a using-enum (C++20).",
      visual: {
        title: "Unscoped vs scoped enumerations",
        kind: "hub",
        hub: "enum",
        nodes: [
          { h: "Classic", lines: ["Leaks names"] },
          { h: "To int", lines: ["Implicit convert"] },
          { h: "enum class", lines: ["Scoped names"] },
          { h: "No convert", lines: ["Cast if needed"] },
          { h: ": uint8_t", lines: ["Underlying type"] },
          { h: "switch", lines: ["Qualify cases"] },
        ],
        footer: "enum class is the default choice in modern C++",
      },
    },
  ],
  intermediate: [
    {
      q: "What is RAII and why is it the C++ resource model?",
      a: "Resource Acquisition Is Initialization: every resource (memory, file, mutex, socket) is owned by an object whose destructor releases it. Scope exit and stack unwinding become your cleanup path.",
      e: "This is why C++ can use exceptions without finally. unique_ptr, lock_guard, fstream, and vector are RAII. A class that is not RAII-correct cannot be put in containers safely. Custom deleters extend the pattern to C APIs.",
      visual: {
        title: "Acquire in ctor, release in dtor",
        kind: "steps",
        steps: [
          { h: "Construct", lines: ["Grab the resource"] },
          { h: "Invariant", lines: ["Object is usable"] },
          { h: "Exception", lines: ["Unwinding still dtors"] },
          { h: "Destroy", lines: ["Release exactly once"] },
        ],
        footer: "If every resource has an owner object, leaks become type errors",
      },
    },
    {
      q: "When do you use unique_ptr, shared_ptr, and weak_ptr?",
      a: "unique_ptr is exclusive ownership, movable, zero overhead. shared_ptr is shared ownership via a control block. weak_ptr breaks cycles and observes without keeping the object alive.",
      e: "Default to unique_ptr. shared_ptr is not free: atomic refcounts and a separate control block. Never construct two shared_ptrs from the same raw pointer. enable_shared_from_this needs an existing shared_ptr owner. Aliasing constructors exist for subobjects.",
      visual: {
        title: "Smart pointer choice",
        kind: "code",
        code: {
          file: "own.cpp",
          code: [
            "auto u = std::make_unique<T>();",
            "auto s = std::make_shared<T>();",
            "std::weak_ptr<T> w = s;",
            "if (auto p = w.lock()) {",
            "  p->use();",
            "}",
          ],
          notes: [
            { h: "unique", text: "One owner — move it, do not copy it" },
            { h: "shared", text: "Last shared_ptr runs the deleter" },
            { h: "weak", text: "lock() fails if the object already died" },
          ],
        },
        footer: "make_unique / make_shared beat raw new for exception safety",
      },
    },
    {
      q: "What are the Rule of Zero and the Rule of Five?",
      a: "Rule of Zero: design types so the compiler’s default special members are correct (members already manage resources). Rule of Five: if you write one of destructor, copy ctor, copy assign, move ctor, move assign, you must consider all five.",
      e: "A user-declared destructor suppresses implicit move in older rules of thumb — define or =default the moves. =delete copies to make a type move-only (like unique_ptr). Prefer composition of RAII members over hand-written copy logic.",
      visual: {
        title: "Special members as a set",
        kind: "cycle",
        center: "Rule 5",
        items: [
          { h: "dtor", lines: ["Release"] },
          { h: "copy ctor", lines: ["Deep copy"] },
          { h: "copy assign", lines: ["Copy-swap"] },
          { h: "move ctor", lines: ["Steal"] },
          { h: "move assign", lines: ["Steal + free"] },
        ],
        footer: "If members already RAII, write none of them — Rule of Zero",
      },
    },
    {
      q: "What is a move constructor for?",
      a: "A move constructor builds a new object by stealing resources from a source that will not be used again (an rvalue). The source is left in a valid but unspecified state that is still destructible.",
      e: "Moves make returning vector cheap and unique_ptr transferable. Moved-from objects may be empty; do not assume their old contents. If a type’s move can throw, many STL operations cannot use it. Mark non-throwing moves noexcept.",
      visual: {
        title: "Copy vs move",
        kind: "compare",
        left: {
          h: "Copy",
          lines: ["Duplicate the resource", "Source unchanged", "May allocate", "T(const T&)"],
        },
        right: {
          h: "Move",
          lines: ["Steal the resource", "Source emptied", "Usually noexcept", "T(T&&)"],
        },
        footer: "After a move, only assign or destroy the source unless documented",
      },
    },
    {
      q: "What are lvalues and rvalues at a practical level?",
      a: "An lvalue is a named object you can take the address of. An rvalue is a temporary or a value you are done with. T&& in a function parameter is an lvalue inside the function unless you std::move it.",
      e: "std::move is a cast to rvalue reference — it does not move by itself. std::forward preserves value category in templates (universal/forwarding references). Returning a local as std::move can block elision.",
      visual: {
        title: "Names are lvalues",
        kind: "hub",
        hub: "value",
        nodes: [
          { h: "lvalue", lines: ["Has a name"] },
          { h: "prvalue", lines: ["Temporary init"] },
          { h: "xvalue", lines: ["Expiring — move"] },
          { h: "std::move", lines: ["Cast to &&"] },
          { h: "T&& param", lines: ["Named → lvalue"] },
          { h: "forward", lines: ["Keep category"] },
        ],
        footer: "A named T&& is an lvalue — you still need std::move / forward",
      },
    },
    {
      q: "How do function and class templates work in practice?",
      a: "A template is a blueprint the compiler instantiates for each set of arguments. Function templates deduce arguments; class templates usually need them (CTAD can infer). Definitions typically live in headers.",
      e: "Each instantiation is a separate type or function. Error messages are long because they instantiate a chain. Prefer concepts (C++20) or static_assert for constraints. Explicit instantiation can cut compile times in libraries.",
      visual: {
        title: "Instantiate per argument set",
        kind: "layers",
        layers: [
          { h: "Primary template", lines: ["template<class T> void f(T);"] },
          { h: "Deduce / supply", lines: ["f(3) → f<int>"] },
          { h: "Instantiate", lines: ["A real function in this TU"] },
          { h: "Link", lines: ["COMDAT merges identical copies"] },
        ],
        footer: "Templates compile where they are used — hence header definitions",
      },
    },
    {
      q: "Why prefer STL algorithms over raw loops?",
      a: "Algorithms name intent (find, transform, partition), avoid off-by-one bugs, and work on any iterator range. With execution policies they can parallelize. Ranges (C++20) compose without iterator pairs.",
      e: "A hand-rolled loop that mutates while iterating is a classic UB source. Know iterator categories: random-access vs forward changes complexity. Prefer std::ranges:: over std:: when you have C++20. Do not ignore return values of algorithms that report failure.",
      visual: {
        title: "Name the algorithm",
        kind: "timeline",
        events: [
          { h: "Have a range", lines: ["vector / span / views"] },
          { h: "State intent", lines: ["find · copy_if · sort"] },
          { h: "Iterator pair", lines: ["Or a C++20 range"] },
          { h: "Result", lines: ["Iterator or output"] },
        ],
        footer: "sort is not a for-loop with swaps — it states the postcondition",
      },
    },
    {
      q: "What is the difference between const, constexpr, and consteval?",
      a: "const is runtime immutability of an object through that name. constexpr means the function or variable can be evaluated at compile time when the context requires it. consteval must be evaluated at compile time (immediate function).",
      e: "constexpr functions can still be called at runtime. constinit (C++20) forces static initialization, avoiding the static init order fiasco. A constexpr allocator-unaware container story improved over standards — know your dialect.",
      visual: {
        title: "When the computation happens",
        kind: "steps",
        steps: [
          { h: "const", lines: ["Do not mutate"] },
          { h: "constexpr", lines: ["Can be compile-time"] },
          { h: "consteval", lines: ["Must be compile-time"] },
          { h: "constinit", lines: ["Static init only"] },
        ],
        footer: "constexpr is allowed at compile time — consteval is required",
      },
    },
    {
      q: "What are the exception-safety levels?",
      a: "No-throw: operation never throws. Strong: on throw, state is unchanged (commit-or-rollback). Basic: invariants hold and no leaks, but state may have changed. No guarantee is a bug.",
      e: "Copy-and-swap is the usual strong-guarantee assign. Destructors should be noexcept. A throwing move constructor forces copies in STL. noexcept is part of the function type for deallocators and move opts.",
      visual: {
        title: "Safety ladder",
        kind: "code",
        code: {
          file: "assign.hpp",
          code: [
            "T& operator=(T other) noexcept {",
            "  swap(*this, other);",
            "  return *this;",
            "}",
          ],
          notes: [
            { h: "By value", text: "other is a copy or move — work is off to the side" },
            { h: "swap", text: "Commit; if copy threw, *this is untouched" },
            { h: "dtor", text: "other releases the old resource" },
          ],
        },
        footer: "Strong guarantee usually means do the work on the side, then swap",
      },
    },
    {
      q: "How do virtual functions and vtables work at a practical level?",
      a: "A virtual function is dispatched through the dynamic type. Typical ABIs store a vptr in the object that points at a vtable of function pointers. Override in the derived class; call via base pointer/reference uses the derived body.",
      e: "Mark overrides override. A non-virtual destructor in a polymorphic base is a delete-through-base UB trap. Pure virtual makes a class abstract. Multiple inheritance means multiple vptrs and thunks. final stops further overrides and can help devirtualize.",
      visual: {
        title: "Dynamic dispatch",
        kind: "cycle",
        center: "vptr",
        items: [
          { h: "Base*", lines: ["Static type"] },
          { h: "load vptr", lines: ["From the object"] },
          { h: "vtable slot", lines: ["Which function"] },
          { h: "call derived", lines: ["Actual body"] },
        ],
        footer: "Delete a derived object through a non-virtual base dtor is UB",
      },
    },
    {
      q: "When do you use std::optional and std::variant?",
      a: "optional<T> is a value that may be absent without a heap or a sentinel. variant<Ts...> is a type-safe union: one of a closed set of types, visited with std::visit.",
      e: "optional has no heap; T must be destructible. Do not use optional<T&> (not standard until later proposals — use a pointer). variant is valueless_by_exception on some throwing assignments. Prefer variant over union for non-trivial types.",
      visual: {
        title: "Maybe a T vs one of many Ts",
        kind: "compare",
        left: {
          h: "optional<T>",
          lines: ["Present or empty", "No extra heap", "value() may throw", "Better than T* for values"],
        },
        right: {
          h: "variant<A,B>",
          lines: ["Closed set of types", "std::visit to unpack", "No C-union UB", "Watch throwing assign"],
        },
        footer: "optional is maybe-one-type — variant is which-type",
      },
    },
    {
      q: "How do lambda captures work?",
      a: "[] captures nothing, [=] copies used locals, [&] references them, and you can list captures explicitly. The lambda is a unique unnamed class with operator() and capture members.",
      e: "[&] in a returned lambda dangles. mutable allows operator() to mutate by-value captures. Generic lambdas are templates (auto params). Init-captures [p = std::move(p)] are how you move into a lambda. Keep captures explicit in production.",
      visual: {
        title: "Lambda as a closure object",
        kind: "hub",
        hub: "[]()",
        nodes: [
          { h: "[]", lines: ["No capture"] },
          { h: "[=]", lines: ["Copy used"] },
          { h: "[&]", lines: ["Ref used"] },
          { h: "[=, this]", lines: ["Copy + this"] },
          { h: "init", lines: ["[x = move(x)]"] },
          { h: "mutable", lines: ["Mutate copies"] },
        ],
        footer: "A [&] lambda that outlives the stack frame is a dangling reference",
      },
    },
    {
      q: "How do you lock a mutex safely?",
      a: "std::lock_guard locks for a scope. std::unique_lock can defer, try_lock, and unlock early. std::scoped_lock locks many mutexes without deadlock using a deadlock-avoidance protocol.",
      e: "Never lock/unlock by hand. Hold locks for the shortest time. Do not call unknown code (callbacks) under a lock. recursive_mutex usually papers over a design bug. Condition variables need unique_lock and a predicate loop.",
      visual: {
        title: "RAII locking",
        kind: "layers",
        layers: [
          { h: "mutex", lines: ["The actual exclusion"] },
          { h: "lock_guard", lines: ["Simple scope lock"] },
          { h: "unique_lock", lines: ["Deferred / condvar"] },
          { h: "scoped_lock", lines: ["Multiple mutexes, no deadlock"] },
        ],
        footer: "The lock object owns the lock — not your matching unlock() calls",
      },
    },
    {
      q: "What is the One Definition Rule in day-to-day work?",
      a: "The ODR says there must be exactly one definition of each non-inline function and global object in the program, and all definitions of an inline/template entity must be identical token-wise in meaning.",
      e: "Violations can link, then crash: two TUs inlined different versions of an inline function after an ABI change. Fix: inline in headers consistently, or define once in a .cpp. Anonymous namespaces give internal linkage per TU.",
      visual: {
        title: "One definition, many includes",
        kind: "timeline",
        events: [
          { h: "Declare in header", lines: ["Many TUs may see it"] },
          { h: "Define once", lines: ["Non-inline in one .cpp"] },
          { h: "Or inline/template", lines: ["Identical in every TU"] },
          { h: "Linker / LTO", lines: ["Mismatch is silent UB"] },
        ],
        footer: "ODR bugs often survive the linker and show up as heisenbugs",
      },
    },
    {
      q: "What are the pitfalls of std::string_view?",
      a: "string_view is a non-owning (pointer, length) over character data. It is cheap to pass but does not extend lifetime. Constructing a string_view from a temporary string dangles at the end of the full expression.",
      e: "Do not store string_view in objects unless you control the buffer’s lifetime. It is not required to be null-terminated — passing .data() to a C API that wants a C string is UB. Prefer string for ownership, string_view for read parameters.",
      visual: {
        title: "View is not a string",
        kind: "steps",
        steps: [
          { h: "Own the data", lines: ["std::string s"] },
          { h: "Pass a view", lines: ["void f(string_view)"] },
          { h: "Do not store", lines: ["Unless buffer outlives"] },
          { h: "C APIs", lines: ["Need a real C string"] },
        ],
        footer: "string_view from a temporary is a dangling view after the statement",
      },
    },
  ],
  expert: [
    {
      q: "Explain C++ value categories (glvalue, prvalue, xvalue).",
      a: "Since C++11, expressions are glvalues (have identity) or rvalues (can be moved from / initialize). glvalues split into lvalues and xvalues (expiring). prvalues are pure rvalues used to initialize objects; C++17 made them the engine of guaranteed elision.",
      e: "std::move produces an xvalue. A temporary materialization conversion turns a prvalue into an xvalue. Interviews want: you cannot take the address of a prvalue; you can of an lvalue. This taxonomy explains overload resolution of T&& vs const T&.",
      visual: {
        title: "Identity vs movability",
        kind: "layers",
        layers: [
          { h: "glvalue", lines: ["Has identity — lvalue or xvalue"] },
          { h: "lvalue", lines: ["Named object, can take address"] },
          { h: "xvalue", lines: ["Identity + about to expire (move)"] },
          { h: "prvalue", lines: ["Initializes an object — elision"] },
        ],
        footer: "std::move is an xvalue cast — prvalues are how elision works",
      },
    },
    {
      q: "What is undefined behavior and why is it worse than a crash?",
      a: "UB is a program state the standard does not constrain. The compiler may assume it never happens and delete checks, reorder code, or format your disk in theory. A crash is lucky; silent wrong results are common.",
      e: "Classics: use-after-free, data races, signed overflow, out-of-bounds, type punning via illegal aliasing, uninitialized reads. Sanitizers (ASan, UBSan, TSan) are how you find it. There is no “it worked in debug so it is defined.”",
      visual: {
        title: "UB is a contract you broke",
        kind: "timeline",
        events: [
          { h: "Write UB", lines: ["OOB · race · dangling"] },
          { h: "Compiler assumes", lines: ["That path never happens"] },
          { h: "Optimize", lines: ["Delete your “safety” check"] },
          { h: "Ship", lines: ["Works until it does not"] },
        ],
        footer: "Sanitizers in CI are not optional for C++ services",
      },
    },
    {
      q: "How do move semantics, noexcept, and trivial relocation interact?",
      a: "A noexcept move lets vector grow by moving instead of copying. If move can throw, vector must copy to preserve the strong guarantee. Some types are trivially relocatable (memcpy the bytes); the standard is still catching up (P1144-style ideas, vendor traits).",
      e: "Never throw from a move if you can avoid it. A moved-from object must still be destroyable and typically assignable. Swap should be noexcept. Small-string optimization makes moving std::string not always a pointer steal — know your library.",
      visual: {
        title: "Why noexcept on move matters",
        kind: "hub",
        hub: "move",
        nodes: [
          { h: "noexcept", lines: ["vector can steal"] },
          { h: "throwing", lines: ["vector must copy"] },
          { h: "relocatable", lines: ["memcpy the object"] },
          { h: "SSO", lines: ["string may copy"] },
          { h: "moved-from", lines: ["Still valid"] },
          { h: "swap", lines: ["Should not throw"] },
        ],
        footer: "A throwing move constructor silently kills vector performance",
      },
    },
    {
      q: "How do SFINAE and concepts differ?",
      a: "SFINAE: substitution failure in a template is not an error — that overload is dropped. enable_if and void_t are the old tools. Concepts (C++20) name requirements, constrain overloads, and give readable diagnostics.",
      e: "requires clauses participate in overload ranking. Concepts do not replace all metaprogramming (you still specialize). requires { expr; } is a validity check, not an evaluation. Mixing unconstrained templates with concepts can still surprise ranking.",
      visual: {
        title: "Constrain the template",
        kind: "code",
        code: {
          file: "add.hpp",
          code: [
            "template<class T>",
            "  requires std::integral<T>",
            "T twice(T x) {",
            "  return x + x;",
            "}",
          ],
          notes: [
            { h: "Concept", text: "integral<T> is a named predicate on T" },
            { h: "requires", text: "Drops this overload if T fails" },
            { h: "SFINAE", text: "The old way: enable_if on the return type" },
          ],
        },
        footer: "Concepts are SFINAE you can read — still mind overload ranking",
      },
    },
    {
      q: "What does the C++ memory model say about atomics and data races?",
      a: "A data race (conflicting non-atomic accesses, at least one write, no happens-before) is UB. std::atomic with memory orders builds happens-before. seq_cst is the default; acquire/release is the usual performance step down; relaxed is for counters.",
      e: "mutex lock/unlock also creates happens-before. volatile is not atomic and does not prevent data races. A correctly locked program can still have race conditions (logic). Know that tearing and reordering are real on ARM even when x86 hid them.",
      visual: {
        title: "Atomic vs mutex vs volatile",
        kind: "compare",
        left: {
          h: "std::atomic",
          lines: ["No data race on that object", "Memory orders matter", "One location", "Lock-free often"],
        },
        right: {
          h: "mutex / lock",
          lines: ["HB for a whole section", "Many locations", "Exclusion + visibility", "Can block"],
        },
        footer: "volatile is for MMIO — it is not a concurrency tool in C++",
      },
    },
    {
      q: "How do ODR-use, inline, and template instantiation interact?",
      a: "An entity is ODR-used when the program needs its definition (take address, call a non-inline, etc.). inline functions and variables may be defined in many TUs if identical. Templates instantiate on demand unless you explicitly instantiate.",
      e: "A static data member of a class template still needs a definition unless it is inline/constexpr. header-only libraries live on inline + templates. Changing an inline function without rebuilding all TUs is an ODR time bomb. extern template delays instantiation.",
      visual: {
        title: "When a definition is required",
        kind: "cycle",
        center: "ODR",
        items: [
          { h: "declare", lines: ["Header sees it"] },
          { h: "ODR-use", lines: ["Need a body"] },
          { h: "inline", lines: ["Many identical"] },
          { h: "template", lines: ["Instantiate"] },
          { h: "mismatch", lines: ["IFNDR / UB"] },
        ],
        footer: "IFNDR — ill-formed, no diagnostic required — is the scary ODR case",
      },
    },
    {
      q: "What are the limits of constexpr evaluation?",
      a: "constexpr evaluation is an interpreter in the compiler with step limits, no UB, and a restricted set of operations (no reinterpret_cast, no undefined overflow). C++20 expanded allocation in constexpr; C++23 continues that trend.",
      e: "If evaluation hits a limit or UB, the expression is not a constant expression and fails in a const context. consteval forces that path. Do not hide heavy work in constexpr just because you can — compile time is a budget. constinit does not require constexpr values, only static init.",
      visual: {
        title: "Compile-time interpreter",
        kind: "steps",
        steps: [
          { h: "Constant context", lines: ["array size · NTTP"] },
          { h: "Evaluate", lines: ["No UB allowed"] },
          { h: "Limits", lines: ["Steps · alloc rules"] },
          { h: "Fallback", lines: ["Runtime call if allowed"] },
        ],
        footer: "constexpr that is not in a constant context still runs at runtime",
      },
    },
    {
      q: "How does the allocator model and pmr work?",
      a: "An Allocator is a compile-time protocol for obtaining typed memory (allocate/deallocate, propagate traits). std::pmr::memory_resource is a runtime polymorphic source; polymorphic_allocator lets containers share a resource without changing the element type’s template too much.",
      e: "std::vector<T, A> with different A are different types — they do not mix. pmr::vector is vector<T, polymorphic_allocator<T>> so the type is stable and the resource is runtime. Arena/monotonic resources shine for request lifetime. Do not free across resources.",
      visual: {
        title: "Where the bytes come from",
        kind: "layers",
        layers: [
          { h: "Container", lines: ["vector asks its allocator"] },
          { h: "Allocator / pmr", lines: ["Typed interface vs memory_resource"] },
          { h: "Resource", lines: ["new · mmap · arena · pool"] },
        ],
        footer: "Different Allocators mean different container types — pmr keeps the type",
      },
    },
    {
      q: "How does virtual inheritance solve the diamond problem?",
      a: "If D inherits B1 and B2 which both inherit A, D contains two A subobjects unless A is a virtual base. Virtual inheritance shares one A, constructed by the most-derived class.",
      e: "The most-derived constructor must initialize virtual bases. Layout uses extra pointers (vbptr). Casting and member offsets get more expensive. Prefer composition or interfaces unless you truly need shared base state (iostream’s ios_base is the classic).",
      visual: {
        title: "Diamond with a shared base",
        kind: "timeline",
        events: [
          { h: "A", lines: ["Common ancestor"] },
          { h: "B1 and B2", lines: ["virtual public A"] },
          { h: "D", lines: ["Most-derived inits A"] },
          { h: "One A", lines: ["Not two copies"] },
        ],
        footer: "Virtual bases are a layout tax — do not use them as a default",
      },
    },
    {
      q: "Why is C++ ABI stability so hard (std::string across compilers)?",
      a: "The ABI is the layout of types, mangling, exception tables, and calling conventions. libstdc++, libc++, and MSVC STL are different ABIs. An inline std::string may use SSO with different internal layouts, so you cannot pass it across a compiler/STL boundary.",
      e: "Stable C APIs or an explicit versioned C++ ABI (opaque pointers) are how plugins survive. -D_GLIBCXX_USE_CXX11_ABI was a famous break. Never dlopen a plugin built with another STL and pass std:: objects. COM/C ABI is still the lingua franca.",
      visual: {
        title: "Your type is not a wire format",
        kind: "hub",
        hub: "ABI",
        nodes: [
          { h: "layout", lines: ["SSO · pointers"] },
          { h: "mangle", lines: ["Symbol names"] },
          { h: "exceptions", lines: ["Unwind tables"] },
          { h: "STL flavor", lines: ["libstdc++ vs libc++"] },
          { h: "flags", lines: ["ABI macros"] },
          { h: "safe API", lines: ["extern C / opaque"] },
        ],
        footer: "std::string in a public .so is a promise you probably cannot keep",
      },
    },
    {
      q: "What is the difference between a data race and a race condition?",
      a: "A data race is a C++ memory-model UB: concurrent conflicting non-atomic accesses. A race condition is a logic bug where timing changes the outcome even if every access is synchronized (TOCTOU, check-then-act).",
      e: "TSan finds data races, not all race conditions. Fixing a data race with atomics can still leave a race condition if two atomics do not compose. Mutexes remove data races on the guarded state; they do not make your business logic atomic across multiple operations unless you hold the lock for the whole invariant.",
      visual: {
        title: "UB vs logic timing bugs",
        kind: "compare",
        left: {
          h: "Data race",
          lines: ["Memory model UB", "Non-atomic conflict", "Sanitizer: TSan", "Any result is allowed"],
        },
        right: {
          h: "Race condition",
          lines: ["Defined but wrong", "TOCTOU · ordering", "Needs design", "Locks must cover invariant"],
        },
        footer: "No data race is necessary, not sufficient, for concurrent correctness",
      },
    },
    {
      q: "How do copy elision and RVO work?",
      a: "Return Value Optimization constructs the return value directly in the caller’s storage. C++17 made elision guaranteed for prvalues (return T{}; unnamed temporary). Named RVO is still allowed but not always guaranteed.",
      e: "return std::move(local); on a local blocks elision and can turn a copy into a move — usually worse. A type with only a private copy and no move can still return by value thanks to elision. Treat elision as a spec feature, not a compiler kindness.",
      visual: {
        title: "Build in the caller’s slot",
        kind: "cycle",
        center: "RVO",
        items: [
          { h: "return T{}", lines: ["prvalue"] },
          { h: "no temp", lines: ["C++17 guaranteed"] },
          { h: "named local", lines: ["NRVO maybe"] },
          { h: "std::move", lines: ["Blocks elision"] },
        ],
        footer: "Do not std::move a local you are returning — you can forbid RVO",
      },
    },
    {
      q: "What is CRTP and when do you use it?",
      a: "The Curiously Recurring Template Pattern is class Derived : public Base<Derived>. Base can static_cast to Derived and call its interface at compile time — static polymorphism without a vtable.",
      e: "Used for mixins, enable_shared_from_this-style helpers, and expression templates. There is no runtime dispatch, so no cross-TU plugin replacement. You must not use the Derived part in Base’s constructor (it is not yet constructed). Concepts and requires can replace some CRTP mixins.",
      visual: {
        title: "Base knows the derived type",
        kind: "steps",
        steps: [
          { h: "Declare", lines: ["Base<Derived>"] },
          { h: "Inherit", lines: ["Derived : Base<Derived>"] },
          { h: "static_cast", lines: ["To Derived&"] },
          { h: "Call", lines: ["No vtable"] },
        ],
        footer: "CRTP is compile-time polymorphism — plugins still need virtuals or type erasure",
      },
    },
    {
      q: "What are object lifetime and std::launder about?",
      a: "An object’s lifetime starts when its constructor finishes (or when a trivial object’s storage is obtained under rules) and ends when the destructor starts. Using a pointer to storage as the wrong type, or after lifetime ended, is UB. std::launder is a hint that a new object exists at an address the compiler thought was dead.",
      e: "Placement new over a buffer, allocator reuse, and const/reference members that are overwritten are the classic launder cases. memcpy of non-trivially-copyable types is UB. std::start_lifetime_as (C++23) and implicit-lifetime types are the modern tools. Pointer provenance matters more than people think.",
      visual: {
        title: "Storage vs object",
        kind: "code",
        code: {
          file: "life.cpp",
          code: [
            "alignas(T) char buf[sizeof(T)];",
            "T* p = new (buf) T{};",
            "// ...",
            "p->~T();",
            "p = new (buf) T{};",
          ],
          notes: [
            { h: "Placement new", text: "Starts a new lifetime in existing storage" },
            { h: "Destroy", text: "End lifetime before you reuse the bytes" },
            { h: "launder", text: "Needed when the compiler cannot see the new object" },
          ],
        },
        footer: "A buffer of bytes is not a T until a T’s lifetime has started",
      },
    },
    {
      q: "How do C++20 coroutines work at a high level?",
      a: "A coroutine is a function with co_await, co_yield, or co_return. The compiler splits it into a state machine heap object (unless heap elision applies). The promise type controls return_object, suspend points, and exceptions.",
      e: "You write the awaiter (await_ready/suspend/resume) and the promise; the language does not give you Go-style tasks. Destroying a suspended coroutine without resuming leaks or UB depending on the type. Allocation, symmetric transfer, and final_suspend are production footguns. Prefer a well-tested task type over rolling one.",
      visual: {
        title: "Coroutine state machine",
        kind: "layers",
        layers: [
          { h: "Caller", lines: ["Gets a return_object (task/future)"] },
          { h: "Promise", lines: ["Policy: suspend, return, exceptions"] },
          { h: "Frame", lines: ["Locals live across suspend points"] },
          { h: "Awaiter", lines: ["Whether to suspend and how to resume"] },
        ],
        footer: "co_await is not magic async — it is a protocol you or a library implement",
      },
    },
  ],
};
