module.exports = {
  name: "C#",
  description:
    "C# interview questions — CLR, records, spans, async, LINQ, nullable types, and the type system.",
  match: /^c#$|^csharp$/i,
  theme: {
    accent: "#68217a",
    hubFill: "#68217a",
    hubText: "#ffffff",
    centerFill: "#f3e8ff",
    centerStroke: "#68217a",
    label: "C#",
  },
  beginner: [
    {
      q: "What is C# and how does it run?",
      a: "C# is a statically typed language that compiles to IL (Intermediate Language). The CLR loads assemblies, JIT-compiles IL to native code, and provides GC, type safety, and a security/type system.",
      e: "C# the language, the CLR/runtime, and the BCL (libraries) are separate layers. NativeAOT and interpreters exist, but interviews still want IL + JIT as the default model. Types are erased only in the sense of generics sharing IL — the CLR still has rich runtime types.",
      visual: {
        title: "From C# to native on the CLR",
        kind: "hub",
        hub: "CLR",
        nodes: [
          { h: "C# source", lines: ["Language syntax"] },
          { h: "Roslyn", lines: ["Emits IL"] },
          { h: "Assembly", lines: [".dll metadata"] },
          { h: "JIT / AOT", lines: ["Native code"] },
          { h: "GC", lines: ["Manages heap"] },
          { h: "BCL", lines: ["Base libraries"] },
        ],
        footer: "C# compiles to IL — the runtime executes it, not the .cs files",
      },
    },
    {
      q: "What is the difference between value types and reference types?",
      a: "Value types (struct, enum, built-in numerics) store their data in place. Reference types (class, interface, delegate, array) store a reference to an object on the GC heap.",
      e: "Copying a struct copies fields; copying a class variable copies the reference. Large structs are expensive to copy — pass them by in/ref or keep them small. Boxing wraps a value type in a heap object when it must be treated as object or an interface.",
      visual: {
        title: "In-place data vs a heap object",
        kind: "compare",
        left: {
          h: "Value type",
          lines: ["struct · enum · int", "Copied by value", "No null unless Nullable", "Stack or inline in objects"],
        },
        right: {
          h: "Reference type",
          lines: ["class · array · delegate", "Copy the reference", "null is possible", "Object lives on the GC heap"],
        },
        footer: "A struct field inside a class still sits in that heap object",
      },
    },
    {
      q: "When do you choose a class versus a struct?",
      a: "Use a class for identity, inheritance, and most domain objects. Use a struct for small, immutable-ish values with value semantics (coordinates, dates, tokens) that should copy.",
      e: "Mutable structs in readonly fields and collections are a classic pitfall (you mutate a copy). Do not put huge data in structs. Records can be class or struct (record vs record struct). Default struct construction zeros fields even if you wrote constructors.",
      visual: {
        title: "Pick the type kind",
        kind: "steps",
        steps: [
          { h: "Need identity", lines: ["class"] },
          { h: "Small value", lines: ["struct / record struct"] },
          { h: "Inherit", lines: ["class only"] },
          { h: "Keep structs tiny", lines: ["Copies are real"] },
        ],
        footer: "A mutable struct in a List is usually a bug waiting to happen",
      },
    },
    {
      q: "What are properties in C#?",
      a: "Properties are members that look like fields but run get/set accessors. Auto-properties hide a backing field. They are the usual public surface instead of exposed fields.",
      e: "init setters allow setting only during construction. required members force initialization. A property is not a field: you cannot pass it as a ref without a backing field, and it is a method call in IL. Do not put heavy work in getters.",
      visual: {
        title: "Property as a pair of accessors",
        kind: "code",
        code: {
          file: "User.cs",
          code: [
            "public class User {",
            "  public string Name { get; init; }",
            "  public required string Id { get; init; }",
            "}",
          ],
          notes: [
            { h: "get/set", text: "Methods that look like a field at the call site" },
            { h: "init", text: "Set only in an object initializer or constructor" },
            { h: "required", text: "Compiler demands the member is set" },
          ],
        },
        footer: "Callers write user.Name — IL still calls get_Name / set_Name",
      },
    },
    {
      q: "What is null and why does NullReferenceException happen?",
      a: "null means a reference points at no object. Calling a member on it throws NullReferenceException. Value types cannot be null unless wrapped in Nullable<T> (T?).",
      e: "Nullable reference types (string vs string?) are a compiler annotation layer, not a runtime non-null guarantee. ?. and ?? help. The forgiving operator ! silences the compiler — it does not check at runtime.",
      visual: {
        title: "Missing object, then a throw",
        kind: "layers",
        layers: [
          { h: "Reference variable", lines: ["May hold null"] },
          { h: "Member access", lines: ["Needs a live object"] },
          { h: "NRE", lines: ["Runtime throws if the reference is null"] },
        ],
        footer: "NRT warnings are compile-time — NRE is still a runtime exception",
      },
    },
    {
      q: "How do namespaces and assemblies organize C# code?",
      a: "A namespace is a logical name prefix for types. An assembly (.dll / .exe) is the deployment and version unit the CLR loads. using imports namespaces; it does not load assemblies.",
      e: "Project references and NuGet pull assemblies. InternalsVisibleTo shares internal types with a friend assembly (tests). File-scoped namespaces cut nesting. Two types with the same full name in different assemblies are different types.",
      visual: {
        title: "Names vs loadable units",
        kind: "timeline",
        events: [
          { h: "namespace", lines: ["Logical type names"] },
          { h: "using", lines: ["Import for this file"] },
          { h: "assembly", lines: ["The DLL the CLR loads"] },
          { h: "reference", lines: ["Build + runtime bind"] },
        ],
        footer: "using is compile-time sugar — assemblies are what the CLR loads",
      },
    },
    {
      q: "How do constructors and object initializers work?",
      a: "A constructor runs when you new a type and must establish invariants. Object initializers set public properties after the constructor: new User { Name = \"Ada\" }. Field/property initializers run before the constructor body.",
      e: "If you write any constructor, the implicit public parameterless one disappears for classes. Structs always have a default zeroing path. primary constructors (modern C#) declare parameters for the whole type. Avoid calling virtual methods in constructors.",
      visual: {
        title: "Create, then initialize",
        kind: "cycle",
        center: "new",
        items: [
          { h: "allocate", lines: ["CLR creates object"] },
          { h: "field inits", lines: ["Then base ctor"] },
          { h: "ctor body", lines: ["Your invariants"] },
          { h: "initializer", lines: ["Set properties"] },
        ],
        footer: "Object initializers run after the constructor returns",
      },
    },
    {
      q: "What do C# access modifiers mean?",
      a: "public, private, protected, internal, protected internal, and private protected control who can see a member. internal is “this assembly.” private is the default for class members.",
      e: "Types themselves default to internal. protected internal is union (subclass or same assembly); private protected is intersection (subclass in this assembly). file types (C# 11) are visible only in that source file. Encapsulation is a compile-time check; reflection can still peek.",
      visual: {
        title: "Who can see the member",
        kind: "hub",
        hub: "access",
        nodes: [
          { h: "private", lines: ["Same type"] },
          { h: "internal", lines: ["Same assembly"] },
          { h: "protected", lines: ["Subclasses"] },
          { h: "prot. internal", lines: ["Subclass or assembly"] },
          { h: "priv. protected", lines: ["Subclass in assembly"] },
          { h: "public", lines: ["Everyone"] },
        ],
        footer: "internal is the assembly boundary — not the namespace",
      },
    },
    {
      q: "Why are strings immutable in C#?",
      a: "System.String never changes its characters after creation. Concatenation and Replace return new strings. This makes sharing and interning safe and keeps strings usable as dictionary keys.",
      e: "Use StringBuilder for loops. ReadOnlySpan<char> avoids allocations when slicing. The intern pool can pin memory if you intern unbounded input. string == uses value equality (operator overload), unlike Java’s default reference ==.",
      visual: {
        title: "String vs StringBuilder",
        kind: "compare",
        left: {
          h: "string",
          lines: ["Immutable", "Safe to share", "== is value equality", "Concat allocates"],
        },
        right: {
          h: "StringBuilder",
          lines: ["Mutable buffer", "Local building", "Not a dictionary key", "ToString() when done"],
        },
        footer: "C# == on string is content — still prefer Equals when you mean it",
      },
    },
    {
      q: "When do you use an array versus List<T>?",
      a: "Arrays have a fixed Length and can be multidimensional. List<T> is a resizable wrapper over a T[] with Count, Add, and a richer API. Prefer IList<T> / IReadOnlyList<T> on public surfaces.",
      e: "List grows by allocating a larger array and copying. For primitives, arrays and List<T> store values inline (no per-element objects). Span<T> can sit over either. Collection expressions (C# 12) can create both.",
      visual: {
        title: "Fixed length vs resizable list",
        kind: "steps",
        steps: [
          { h: "Fixed N", lines: ["T[] or array"] },
          { h: "Grow", lines: ["new List<T>()"] },
          { h: "Add", lines: ["list.Add(x)"] },
          { h: "Expose", lines: ["IReadOnlyList<T>"] },
        ],
        footer: "List<T> is not a linked list — it is a growable array",
      },
    },
    {
      q: "How do virtual, override, and new (hiding) differ?",
      a: "virtual marks a method as overridable. override replaces that slot for the runtime type. new hides a member and is chosen by the compile-time type, not polymorphic dispatch.",
      e: "Forgetting override when you meant polymorphism silently hides if the signatures match with new-or-warning. abstract methods must be overridden. sealed override stops further overrides. Call the base with base.Method().",
      visual: {
        title: "Dispatch vs hide",
        kind: "code",
        code: {
          file: "Shape.cs",
          code: [
            "class Shape {",
            "  public virtual void Draw() {}",
            "}",
            "class Circle : Shape {",
            "  public override void Draw() {}",
            "}",
            "Shape s = new Circle();",
            "s.Draw(); // Circle",
          ],
          notes: [
            { h: "virtual", text: "Creates a slot the runtime can replace" },
            { h: "override", text: "Fills that slot in the derived type" },
            { h: "new", text: "Different slot — static type wins" },
          ],
        },
        footer: "new hides — override dispatches — interviews love this distinction",
      },
    },
    {
      q: "What can an interface contain in modern C#?",
      a: "Interfaces declare capabilities: methods, properties, events, indexers. They may include default implementations, static abstract members (generics math), and private helpers. A class can implement many interfaces.",
      e: "Default interface methods let you evolve APIs without breaking implementers, but they complicate diamond inheritance and COM-like scenarios. Explicit interface implementation hides a member from the class’s public surface. Interfaces are still reference types.",
      visual: {
        title: "Interface surface over time",
        kind: "layers",
        layers: [
          { h: "Abstract members", lines: ["Must be implemented by the type"] },
          { h: "Default bodies", lines: ["Optional override — API evolution"] },
          { h: "static abstract", lines: ["Generic math · factories on T"] },
        ],
        footer: "A class has one base class and many interfaces",
      },
    },
    {
      q: "How should you use exceptions in C#?",
      a: "throw signals a failure you cannot handle locally. catch handles specific types; finally / using still runs cleanup. Exception is the usual base; prefer derived types that callers can catch selectively.",
      e: "Do not use exceptions for normal control flow. Catch the specific type, not Exception, at boundaries. Exception filters (when) avoid catching then rethrowing. Re-throw with throw; not throw ex; to keep the stack. IDisposable is for cleanup, not for errors.",
      visual: {
        title: "Throw, catch, clean up",
        kind: "timeline",
        events: [
          { h: "throw", lines: ["Unwind the stack"] },
          { h: "catch when", lines: ["Filter without eating"] },
          { h: "catch", lines: ["Handle or wrap"] },
          { h: "finally / using", lines: ["Always dispose"] },
        ],
        footer: "throw; keeps the stack — throw ex; resets it",
      },
    },
    {
      q: "What is boxing and unboxing?",
      a: "Boxing copies a value type into a heap object (often as object or an interface). Unboxing extracts it back with a type check. It allocates and can throw InvalidCastException.",
      e: "Non-generic collections (ArrayList) boxed everything — that is why List<T> exists. Calling an interface method on a struct may box unless the JIT devirtualizes. readonly struct and ref structs reduce accidental copies; they do not magically stop all boxing.",
      visual: {
        title: "Value on the heap",
        kind: "cycle",
        center: "box",
        items: [
          { h: "int n", lines: ["Value slot"] },
          { h: "object o = n", lines: ["Allocate wrapper"] },
          { h: "use as object", lines: ["Heap identity"] },
          { h: "int m = (int)o", lines: ["Unbox + copy"] },
        ],
        footer: "List<int> does not box — ArrayList of ints does",
      },
    },
    {
      q: "What is IDisposable and the using statement?",
      a: "IDisposable.Dispose releases unmanaged resources and owned disposables. using (or a using declaration) calls Dispose in a finally, even when an exception flies.",
      e: "Implement the full pattern if you have a finalizer (rare — prefer SafeHandle). Dispose must be idempotent. async uses await using / IAsyncDisposable. Do not rely on the GC to close files promptly — finalizers are last-resort.",
      visual: {
        title: "Deterministic cleanup",
        kind: "hub",
        hub: "using",
        nodes: [
          { h: "Acquire", lines: ["File · conn · lock"] },
          { h: "use", lines: ["Work in scope"] },
          { h: "Dispose", lines: ["finally path"] },
          { h: "SafeHandle", lines: ["Better than finalizer"] },
          { h: "async", lines: ["await using"] },
          { h: "idempotent", lines: ["Dispose twice OK"] },
        ],
        footer: "GC is not a substitute for Dispose on files and sockets",
      },
    },
  ],
  intermediate: [
    {
      q: "How do records differ from classes?",
      a: "A record (class) is a reference type with value-based equality, a Deconstruct, and a compiler-generated clone for with-expressions. It is meant for immutable data, not for entities with identity.",
      e: "record struct is a value type with similar sugar. Inheritance of records uses with and copy constructors — surprising if you treat them like ORMs. Prefer records for DTOs and messages; prefer classes when identity and mutation are the point.",
      visual: {
        title: "with-expression copies a record",
        kind: "steps",
        steps: [
          { h: "Create", lines: ["var a = new Point(1, 2)"] },
          { h: "with", lines: ["var b = a with { X = 3 }"] },
          { h: "Clone", lines: ["New instance, rest copied"] },
          { h: "Equals", lines: ["By component values"] },
        ],
        footer: "with is a copy — it does not mutate the original record",
      },
    },
    {
      q: "How does LINQ deferred execution work?",
      a: "Most LINQ to Objects operators return an iterator that does not run until you enumerate (foreach, ToList, Count). Each enumeration re-runs the query against the current source.",
      e: "ToList/ToArray snap a result. Modifying the source while it is deferred is a gotcha. LINQ to Entities translates expression trees to SQL — IQueryable is not IEnumerable. Side effects inside Select are a smell. Multiple enumeration can hit a database twice.",
      visual: {
        title: "Build a query, then run it",
        kind: "code",
        code: {
          file: "q.cs",
          code: [
            "var q = xs.Where(x => x > 0)",
            "          .Select(x => x * 2);",
            "foreach (var n in q) { }",
            "var snap = q.ToList();",
          ],
          notes: [
            { h: "Where/Select", text: "Compose iterators — no loop yet" },
            { h: "foreach", text: "Pulls the pipeline for the first time" },
            { h: "ToList", text: "Enumerates once and stores the result" },
          ],
        },
        footer: "Deferred queries re-run — snapshot when you need stability",
      },
    },
    {
      q: "What are the practical rules of async/await?",
      a: "async methods return Task/Task<T>/ValueTask and may await awaitables. await yields so the thread can do other work; continuation usually resumes on a captured context unless you ConfigureAwait(false).",
      e: "Never .Result/.Wait() on the UI or ASP.NET request context — deadlock. async void is only for event handlers. Pass CancellationToken. Prefer await over continue-with chains. Exceptions are stored on the Task and thrown at await.",
      visual: {
        title: "Yield, then continue",
        kind: "cycle",
        center: "await",
        items: [
          { h: "start", lines: ["Return a Task"] },
          { h: "await I/O", lines: ["Release the thread"] },
          { h: "complete", lines: ["I/O finishes"] },
          { h: "resume", lines: ["Continuation runs"] },
          { h: "fault", lines: ["Exception on Task"] },
        ],
        footer: "async void cannot be awaited — exceptions can crash the process",
      },
    },
    {
      q: "What are nullable reference types?",
      a: "In an NRT context, string means “should not be null” and string? means “may be null.” The compiler flows null-state and warns on dereferences. At runtime the CLR still allows null.",
      e: "Annotations are metadata ([MaybeNull], [NotNullWhen]). The null-forgiving operator ! is an assertion, not a check. Generics need T? constraints care (class vs struct). Treat warnings as errors in new projects or the whole feature is theater.",
      visual: {
        title: "Annotations vs runtime null",
        kind: "compare",
        left: {
          h: "string (NRT on)",
          lines: ["Should not be null", "Warnings on misuse", "Still a class", "No CLR non-null"],
        },
        right: {
          h: "string?",
          lines: ["May be null", "Must ?./??", "Same IL type", "Intent for callers"],
        },
        footer: "NRT is a compiler feature — it does not change the CLR type",
      },
    },
    {
      q: "How do delegates and events work?",
      a: "A delegate is a type-safe method pointer (multicast possible). An event is a restricted delegate: outsiders can only += / -=, not invoke or assign, protecting the invocation list.",
      e: "Events typically use EventHandler<TEventArgs>. Unsubscribing matters or you leak publishers. Thread-safe raise copies the delegate locally. Func/Action are generic delegates; do not replace events with public Action fields on APIs.",
      visual: {
        title: "Delegate vs event",
        kind: "hub",
        hub: "event",
        nodes: [
          { h: "delegate", lines: ["Invoke + combine"] },
          { h: "multicast", lines: ["Invocation list"] },
          { h: "+= / -=", lines: ["Subscribe"] },
          { h: "add/remove", lines: ["Custom accessors"] },
          { h: "raise", lines: ["Owner invokes"] },
          { h: "unsubscribe", lines: ["Avoid leaks"] },
        ],
        footer: "A public Action field is not an event — callers can wipe it",
      },
    },
    {
      q: "How do generics and constraints work in C#?",
      a: "Generics parameterize types and methods (List<T>, void Swap<T>). Constraints (where T : class, new(), IDisposable, notnull) tell the compiler what you can do with T. The CLR reifies generics: List<int> is not List<string>.",
      e: "Unlike Java, the runtime keeps type arguments (for references, code is shared; for primitives, JIT specializes). You cannot use operators on T without interfaces/generic math. default(T) is null for classes and zero for structs.",
      visual: {
        title: "Constrain then use T",
        kind: "layers",
        layers: [
          { h: "Open generic", lines: ["List<T> in source"] },
          { h: "Constraints", lines: ["where T : IComparable<T>"] },
          { h: "Closed constructed", lines: ["List<int> is a real runtime type"] },
          { h: "JIT", lines: ["Share ref code · specialize primitives"] },
        ],
        footer: "C# generics are reified — you can ask typeof(T) at runtime",
      },
    },
    {
      q: "What is the difference between IEnumerable<T> and IQueryable<T>?",
      a: "IEnumerable<T> is in-memory pull iteration. IQueryable<T> holds an expression tree that a provider (EF Core) can translate to SQL. The same LINQ method names mean different execution models.",
      e: "Calling AsEnumerable() switches to in-memory and can accidentally pull a whole table. Providers cannot translate arbitrary C#. IAsyncEnumerable is the async stream analog. Never assume IQueryable is cheap — log the SQL.",
      visual: {
        title: "Where the query runs",
        kind: "timeline",
        events: [
          { h: "Compose LINQ", lines: ["Same syntax"] },
          { h: "IQueryable", lines: ["Expression tree"] },
          { h: "Provider", lines: ["SQL / other backend"] },
          { h: "IEnumerable", lines: ["Delegates in-process"] },
        ],
        footer: "AsEnumerable is the cliff where SQL stops and RAM starts",
      },
    },
    {
      q: "When do you use Span<T> and Memory<T>?",
      a: "Span<T> is a ref struct view over contiguous memory (array, stackalloc, unmanaged). It cannot live on the heap, so it cannot be a field of a class or be used across await. Memory<T> is a heap-friendly sibling you can store and await, then .Span.",
      e: "They cut allocations in parsers and high-throughput I/O. ReadOnlySpan<char> slices strings without substring. Do not return a Span to stackalloc from the method that allocated it. pipeline/Kestrel code is full of these types for a reason.",
      visual: {
        title: "View, do not copy",
        kind: "steps",
        steps: [
          { h: "Own buffer", lines: ["array / native / stack"] },
          { h: "Span", lines: ["Slice in a method"] },
          { h: "Need store", lines: ["Memory<T> instead"] },
          { h: "await then Span", lines: ["m.Span in the resume"] },
        ],
        footer: "Span is a ref struct — it cannot cross await or sit on a class",
      },
    },
    {
      q: "How does pattern matching work in C#?",
      a: "Patterns appear in is, switch expressions, and property/list patterns. They test type, shape, and values and can bind variables. Switch expressions can be exhaustive with the compiler’s help.",
      e: "relational and logical patterns (and/or/not) replace nested ifs. Discard _ is not a variable. List patterns (C# 11) match sequences. Exhaustiveness is only as good as the type’s closed set — classes are open unless you control them.",
      visual: {
        title: "Match shape, bind, return",
        kind: "code",
        code: {
          file: "shape.cs",
          code: [
            "var area = s switch {",
            "  Circle { R: var r } =>",
            "      Math.PI * r * r,",
            "  Rect { W: var w, H: var h }",
            "      => w * h,",
            "  _ => 0",
            "};",
          ],
          notes: [
            { h: "Type + property", text: "Circle { R: var r } binds r" },
            { h: "switch expr", text: "Must return a value on every path" },
            { h: "_", text: "Discard — the open-world fallback" },
          ],
        },
        footer: "Patterns replace many as-casts and nested ifs — keep a discard honest",
      },
    },
    {
      q: "What are extension methods?",
      a: "An extension method is a static method with this on the first parameter, visible as an instance method when the namespace is in scope. LINQ is built on them.",
      e: "They do not get private access. Instance methods win over extensions. Extending a type you own is usually worse than a real method. Null this is allowed to enter the method — you must still null-check. Do not abuse them to build a god-utility class.",
      visual: {
        title: "Static method, instance syntax",
        kind: "cycle",
        center: "this",
        items: [
          { h: "static class", lines: ["Holder type"] },
          { h: "this T", lines: ["First parameter"] },
          { h: "using NS", lines: ["Brings it in"] },
          { h: "call", lines: ["x.Foo() sugar"] },
        ],
        footer: "Extensions are compile-time sugar — no new runtime slot on T",
      },
    },
    {
      q: "What do init setters and required members change?",
      a: "init-only properties can be set in constructors and object initializers, then become effectively readonly. required members must be set by the caller or a constructor marked SetsRequiredMembers.",
      e: "This is how you get immutable objects without a 12-parameter constructor. Records use init under the hood. The compiler enforces required; reflection can still skip it. with-expressions on records set init properties on the clone.",
      visual: {
        title: "Immutable after construction",
        kind: "compare",
        left: {
          h: "set",
          lines: ["Mutable anytime", "Hard to reason", "Classic beans", "Thread races"],
        },
        right: {
          h: "init + required",
          lines: ["Set at creation", "Then frozen", "Object initializers", "Records love this"],
        },
        footer: "required is a compiler rule — not a runtime guarantee under reflection",
      },
    },
    {
      q: "When do you use tuples versus records?",
      a: "ValueTuple (int, string) is a lightweight ad-hoc product type with Item1 names or element names. Anonymous types are compiler-generated classes. Records are named, reusable, and better at APIs.",
      e: "Do not return unnamed tuples from public APIs. Tuple equality is structural. Nested tuples get messy. records document the domain; tuples are glue inside a method. System.Tuple is a reference type leftover — prefer ValueTuple syntax.",
      visual: {
        title: "Ad-hoc pair vs named type",
        kind: "hub",
        hub: "(T,U)",
        nodes: [
          { h: "ValueTuple", lines: ["struct pair"] },
          { h: "names", lines: ["(int x, int y)"] },
          { h: "anonymous", lines: ["new { x, y }"] },
          { h: "record", lines: ["Named API type"] },
          { h: "public API", lines: ["Prefer record"] },
          { h: "locals", lines: ["Tuples are fine"] },
        ],
        footer: "Tuples are glue — records are types you can talk about",
      },
    },
    {
      q: "How does the lock statement work?",
      a: "lock (obj) is Monitor.Enter/Exit in a try/finally. It serializes threads on a reference identity. Use a private object (or a dedicated lock type) — never lock(this), a string, or a Type.",
      e: "lock does not make compound operations on other objects atomic unless they are inside the same lock. Async code cannot hold lock across await. Prefer SemaphoreSlim or channels for async mutual exclusion. ReaderWriterLockSlim is easy to deadlock.",
      visual: {
        title: "Monitor enter and exit",
        kind: "layers",
        layers: [
          { h: "private gate", lines: ["object _gate = new()"] },
          { h: "lock (_gate)", lines: ["Enter the monitor"] },
          { h: "critical section", lines: ["Invariants hold"] },
          { h: "finally Exit", lines: ["Even on throw"] },
        ],
        footer: "Never lock on this or on interned strings — you do not own them",
      },
    },
    {
      q: "How does the GC organize generations in practice?",
      a: "The GC is generational: gen0 is new objects, gen1 is survivors, gen2 is long-lived. Collections in gen0 are frequent and cheap; gen2 is expensive. The Large Object Heap holds big arrays and is collected less often.",
      e: "Allocating is usually a bump pointer — cheap until you survive. Pinning (fixed, GCHandle) fragments heaps. IDisposable still matters for native resources the GC does not track. Workstation vs server GC changes pause and throughput. Measure with EventPipe, not folklore.",
      visual: {
        title: "Survive, then get expensive",
        kind: "timeline",
        events: [
          { h: "Allocate", lines: ["Usually gen0"] },
          { h: "Survive", lines: ["Promote to gen1"] },
          { h: "Live long", lines: ["gen2 / LOH"] },
          { h: "Collect", lines: ["Pause cost grows"] },
        ],
        footer: "Short-lived objects are the GC’s happy path — caches are not",
      },
    },
    {
      q: "What is generic covariance (IEnumerable<out T>)?",
      a: "out T marks a type parameter as covariant: IEnumerable<string> can be used as IEnumerable<object> because you only produce T. in T is contravariant for consumers (Action<object> can act as Action<string>).",
      e: "Variance only works on reference types, not on struct type arguments. List<T> is invariant because you both get and set T. Arrays are covariant at runtime and can throw ArrayTypeMismatchException — a historical trap.",
      visual: {
        title: "Producer out, consumer in",
        kind: "steps",
        steps: [
          { h: "Produce T", lines: ["out T · IEnumerable"] },
          { h: "Consume T", lines: ["in T · Action"] },
          { h: "Both", lines: ["List<T> invariant"] },
          { h: "Arrays", lines: ["Covariant + runtime check"] },
        ],
        footer: "Variance is a compile-time substitution rule — arrays still cheat",
      },
    },
  ],
  expert: [
    {
      q: "How do C#, the CLR, and the BCL differ?",
      a: "C# is the language (Roslyn). The CLR/runtime is the VM: GC, JIT/AOT, loader, type system, exceptions. The BCL (CoreLib and friends) is the library you call (String, Task, Span). Other languages (F#, VB) share the same runtime.",
      e: "Language features sometimes need runtime support (async, generics, byref) and sometimes are pure compiler sugar (foreach, using, records). NativeAOT trims and compiles ahead — reflection-heavy BCL usage breaks. An expert answer names which layer a bug lives in.",
      visual: {
        title: "Three layers of the stack",
        kind: "layers",
        layers: [
          { h: "C# language", lines: ["Syntax · Roslyn · sugar"] },
          { h: "BCL", lines: ["Types you new and call"] },
          { h: "CLR / runtime", lines: ["IL · GC · JIT · loader"] },
        ],
        footer: "await is language + BCL Task + runtime thread pool — not one box",
      },
    },
    {
      q: "Why are ref structs like Span<T> forbidden on the heap?",
      a: "ref struct can hold byrefs (interior pointers). The GC moves objects; a byref stored on the heap would dangle. The compiler bans capturing Span in classes, async state machines, iterators, and lambdas that hoist.",
      e: "scoped and ref fields (C# 11) refine lifetimes. stackalloc produces a Span that must not escape. Memory<T> / IMemoryOwner are the heap story. This is why high-perf APIs split sync Span methods from async Memory methods.",
      visual: {
        title: "Byrefs cannot be fields of objects",
        kind: "timeline",
        events: [
          { h: "Span points", lines: ["Interior of an array"] },
          { h: "GC moves", lines: ["Array address changes"] },
          { h: "If Span were on heap", lines: ["Stale interior pointer"] },
          { h: "Language ban", lines: ["ref struct stays on stack"] },
        ],
        footer: "The Span heap ban is a GC correctness rule, not a style rule",
      },
    },
    {
      q: "How does the compiler turn async methods into state machines?",
      a: "Roslyn rewrites an async method into a struct state machine implementing IAsyncStateMachine. Locals that live across await become fields. await calls OnCompleted; the continuation calls MoveNext with the next state.",
      e: "That is why you cannot await in a lock, catch a ref struct across await, or assume the same thread. Allocation: the machine is a struct until it needs to box onto the heap when it actually suspends. ValueTask can avoid Task allocations on the fast path.",
      visual: {
        title: "MoveNext as a state machine",
        kind: "hub",
        hub: "async",
        nodes: [
          { h: "rewrite", lines: ["Roslyn struct"] },
          { h: "hoist locals", lines: ["Fields across await"] },
          { h: "suspend", lines: ["OnCompleted"] },
          { h: "resume", lines: ["MoveNext"] },
          { h: "box", lines: ["If it really waits"] },
          { h: "Task", lines: ["Result / exception"] },
        ],
        footer: "Your locals across await are fields — that is why types are constrained",
      },
    },
    {
      q: "What are the limits of nullable reference type flow analysis?",
      a: "The compiler tracks null-state per local and applies attributes ([NotNullWhen(true)], [MaybeNull]). It does not understand arbitrary methods, concurrent mutation, or reflection. Generics and inherited APIs are often under-annotated.",
      e: "The ! operator is a lie you tell the compiler. Public APIs still need runtime checks at boundaries. [MemberNotNull] helps helpers that initialize fields. Expert teams treat NRT as necessary but not sufficient — they still test null paths.",
      visual: {
        title: "What the checker can see",
        kind: "code",
        code: {
          file: "nrt.cs",
          code: [
            "string? s = Get();",
            "if (s is not null) {",
            "  Use(s.Length);",
            "}",
            "Use(s!.Length); // you swore",
          ],
          notes: [
            { h: "is not null", text: "Flow analysis narrows s to string" },
            { h: "!", text: "Suppresses the warning — no runtime check" },
            { h: "Get()", text: "Only as good as Get’s annotations" },
          ],
        },
        footer: "NRT is a local theorem prover — not a proof over your whole heap",
      },
    },
    {
      q: "How do GC modes, the SOH, and the LOH differ in production?",
      a: "Workstation GC minimizes pauses on desktops; server GC uses more heaps/threads for throughput. The Small Object Heap is generational. The Large Object Heap (typically ≥85KB) is not compacted by default (unless you enable it), so it fragments.",
      e: "Pinned handles and LOH allocations are the usual fragmentation story. GC.Collect is almost never the fix. DATAS / dynamic adaptation and regions (newer runtimes) change the old lore. Measure gen2 pause, allocation rate, and pinned object counts.",
      visual: {
        title: "Heaps you actually pay for",
        kind: "compare",
        left: {
          h: "SOH",
          lines: ["Generational", "Frequent gen0", "Compacts", "Small objects"],
        },
        right: {
          h: "LOH",
          lines: ["Big arrays", "Rare collections", "Fragments if pinned", "Pool or avoid"],
        },
        footer: "Pooling huge arrays is an LOH strategy — not a gen0 trick",
      },
    },
    {
      q: "What are source generators and when do they beat reflection?",
      a: "A source generator is a Roslyn component that adds C# at compile time from your syntax/attributes. You get typed, AOT-friendly code instead of runtime reflection and runtime codegen.",
      e: "System.Text.Json, regex, and logging use generators. They increase compile time and can surprise with hidden files. They must be deterministic. Reflection still wins for truly dynamic plugins. NativeAOT makes generators almost mandatory for serializers.",
      visual: {
        title: "Generate at compile time",
        kind: "cycle",
        center: "Roslyn",
        items: [
          { h: "parse", lines: ["Your syntax"] },
          { h: "generate", lines: ["Extra .cs"] },
          { h: "compile", lines: ["Together"] },
          { h: "run", lines: ["No reflect tax"] },
          { h: "AOT", lines: ["Nothing to trim"] },
        ],
        footer: "Generators move cost to compile time so NativeAOT has code to compile",
      },
    },
    {
      q: "How does generic variance interact with the CLR type system?",
      a: "The CLR supports covariant and contravariant generic interfaces and delegates on reference type arguments. IEnumerable<out T> is the poster child. The JIT and verifier enforce that you only produce (out) or only consume (in) T.",
      e: "Casting List<string> to List<object> is illegal and would break type safety on Add. Arrays remain a hole with runtime checks. Value types are invariant because List<int> is a different layout than List<object>. Variance annotations are part of the public contract — changing them is a breaking change.",
      visual: {
        title: "Why List<T> cannot be covariant",
        kind: "steps",
        steps: [
          { h: "If List<string> were List<object>", lines: ["Unsafe Add"] },
          { h: "Add a Cat", lines: ["Into a string list"] },
          { h: "Read as string", lines: ["Would explode"] },
          { h: "So List is invariant", lines: ["IEnumerable is out"] },
        ],
        footer: "out is safe for producers — mutability forces invariance",
      },
    },
    {
      q: "When do you choose ValueTask over Task?",
      a: "Task is a reference type that always allocates when you create a new incomplete one. ValueTask/ValueTask<T> is a struct that can wrap a completed result or a pooled IValueTaskSource, avoiding allocations on hot synchronous completions.",
      e: "A ValueTask may be awaited only once. Do not store it, call GetAwaiter().GetResult() after await, or block on it. If you need to fan-out, use .AsTask(). Libraries returning ValueTask should document this. Default to Task until a profiler shows allocation pressure.",
      visual: {
        title: "Task vs ValueTask",
        kind: "compare",
        left: {
          h: "Task / Task<T>",
          lines: ["Always a heap object", "Await many times", "Easy to cache", "Default public API"],
        },
        right: {
          h: "ValueTask",
          lines: ["Struct fast path", "Await once", "IValueTaskSource pool", "Hot completed I/O"],
        },
        footer: "Await a ValueTask once — then it may be a recycled source",
      },
    },
    {
      q: "What does SynchronizationContext and ConfigureAwait actually do?",
      a: "await captures SynchronizationContext (UI, ASP.NET Classic) or TaskScheduler and posts the continuation there. ConfigureAwait(false) skips that capture so the continuation may run on a pool thread.",
      e: "ASP.NET Core has no request SyncContext — ConfigureAwait(false) is less critical but still a library habit. Blocking on a task that needs the captured context deadlocks. ConfigureAwait(true) is the default. Know which host you are in before quoting folklore.",
      visual: {
        title: "Where the continuation runs",
        kind: "layers",
        layers: [
          { h: "Host context", lines: ["UI message pump · legacy ASP.NET"] },
          { h: "await (default)", lines: ["Post back to that context"] },
          { h: "ConfigureAwait(false)", lines: ["Stay on the completing thread / pool"] },
          { h: "ASP.NET Core", lines: ["No request SyncContext — pool by default"] },
        ],
        footer: "Deadlock is await + .Wait() on a context that has only one thread",
      },
    },
    {
      q: "How does string interning interact with Span-based parsing?",
      a: "The intern pool is a process-wide dictionary of strings the runtime (and String.Intern) can reuse. It is not a cache you should stuff with unbounded user input. Span/ReadOnlySpan parsing avoids allocating strings until you decide to materialize one.",
      e: "string.Intern of request IDs is a memory leak. utf8 spans and Utf8Parser/IUtf8SpanParsable are the allocation-free path. Compare spans with SequenceEqual / MemoryExtensions, not by creating strings. Interned strings are pinned for the process lifetime.",
      visual: {
        title: "Parse without allocating",
        kind: "timeline",
        events: [
          { h: "Bytes / chars", lines: ["ReadOnlySpan"] },
          { h: "Parse", lines: ["Utf8Parser · int.Parse"] },
          { h: "Maybe intern", lines: ["Only tiny fixed sets"] },
          { h: "Materialize", lines: ["new string only if stored"] },
        ],
        footer: "Interning unbounded input pins those strings until process exit",
      },
    },
    {
      q: "What are ref returns, ref fields, and scoped?",
      a: "A method can return ref T to alias an existing location (array slot, field). C# 11 allows ref fields inside ref structs. scoped tells the compiler a byref does not escape the current method.",
      e: "You cannot return a ref to a local. ref readonly documents no mutation. These features power Span and high-perf collections. Misuse is lifetime UB the compiler tries to ban. Interviews want: this is safe aliasing, not C++ references with silent dangling — the compiler is stricter.",
      visual: {
        title: "Alias a location, do not copy",
        kind: "hub",
        hub: "ref",
        nodes: [
          { h: "ref return", lines: ["Alias a slot"] },
          { h: "ref field", lines: ["Inside ref struct"] },
          { h: "scoped", lines: ["Must not escape"] },
          { h: "ref readonly", lines: ["No write"] },
          { h: "local ban", lines: ["Cannot return"] },
          { h: "Span", lines: ["Built on this"] },
        ],
        footer: "The compiler tracks lifetimes — that is the whole point of scoped",
      },
    },
    {
      q: "How do default interface methods create diamond problems?",
      a: "If two interfaces provide a default for the same method and a class implements both, C# requires the class to re-implement the method. The runtime has its own slot rules for DIM that differ slightly from Java’s.",
      e: "Adding a default to a published interface can still break implementers that already had a conflicting member. COM and AOT have extra constraints. Explicit implementations pick a slot. Prefer abstract new members on interfaces you do not own the ecosystem for.",
      visual: {
        title: "Two defaults, one class",
        kind: "compare",
        left: {
          h: "Single default",
          lines: ["Implementers inherit it", "Can override", "API evolution", "Works like a mixin"],
        },
        right: {
          h: "Diamond defaults",
          lines: ["Class must choose", "Re-implement the method", "Versioning hazard", "Runtime slot rules"],
        },
        footer: "Default interface methods are not free mixins — diamonds force a choice",
      },
    },
    {
      q: "How do JIT, ReadyToRun, and NativeAOT differ?",
      a: "JIT compiles IL on first use (plus tiered compilation). ReadyToRun ships precompiled code with IL fallback for better startup. NativeAOT compiles to a native binary, trims unused IL, and largely forbids leftover runtime codegen.",
      e: "Reflection, MakeGenericType, and runtime emit break or need hints under AOT/trimming. Tiered JIT starts with a quick compile then re-JITs hot methods. Expert answers mention DynamicPGO and why microbenchmarks need [MemoryDiagnoser] and a warmup.",
      visual: {
        title: "When IL becomes native",
        kind: "cycle",
        center: "IL",
        items: [
          { h: "JIT", lines: ["First call"] },
          { h: "Tiered", lines: ["Recompile hot"] },
          { h: "R2R", lines: ["Prejit + fallback"] },
          { h: "NativeAOT", lines: ["No IL left"] },
          { h: "trim", lines: ["Drop unused"] },
        ],
        footer: "AOT shifts every reflection trick from “works” to “must be published”",
      },
    },
    {
      q: "When do you use volatile, Interlocked, and memory barriers in C#?",
      a: "volatile in C# inserts acquire/release-style fences on reads/writes (stronger than C++ volatile). Interlocked provides atomic RMW (Increment, CompareExchange). Thread.MemoryBarrier is a full fence. Most code should use locks, channels, or concurrent collections instead.",
      e: "volatile does not make ++ atomic. The ECMA vs .NET memory model story is a known interview rabbit hole — .NET’s practical model is relatively strong, but you still need Interlocked for counters. Do not invent lock-free structures in app code without a proven algorithm.",
      visual: {
        title: "Pick a primitive, rarely",
        kind: "steps",
        steps: [
          { h: "Flag publish", lines: ["volatile or Volatile.Write"] },
          { h: "Counter", lines: ["Interlocked"] },
          { h: "Invariant on many fields", lines: ["lock"] },
          { h: "Pipeline", lines: ["Channel / ConcurrentQueue"] },
        ],
        footer: "volatile++ is still a race — Interlocked.Increment is the counter",
      },
    },
    {
      q: "How do IAsyncEnumerable and Channel<T> model async streams?",
      a: "IAsyncEnumerable<T> is pull-based async iteration (await foreach). Channel<T> is a producer/consumer queue with backpressure, used to implement those streams or to decouple pipelines. Cancellation tokens must flow or the loop never stops.",
      e: "Do not mix blocking Channel.Writer.TryWrite loops with unbounded channels in services — you will OOM. await foreach disposes the enumerator. IAsyncEnumerable over IQueryable is provider-specific (EF ToAsyncEnumerable). Prefer channels at process boundaries over a homemade Task queue.",
      visual: {
        title: "Push into a channel, pull with await foreach",
        kind: "layers",
        layers: [
          { h: "Producer", lines: ["ChannelWriter — backpressure"] },
          { h: "Channel", lines: ["Bounded queue of T"] },
          { h: "IAsyncEnumerable", lines: ["await foreach pull"] },
          { h: "Cancellation", lines: ["Token stops both sides"] },
        ],
        footer: "Unbounded channels are a memory leak with extra steps",
      },
    },
  ],
};
