module.exports = {
  name: "Dart",
  description:
    "Dart interview questions — null safety, isolates, Future/Stream, mixins, and sound typing.",
  match: /^dart$/i,
  theme: {
    accent: "#0175C2",
    hubFill: "#0175C2",
    hubText: "#ffffff",
    centerFill: "#e0f2fe",
    centerStroke: "#0175C2",
    label: "Dart",
  },
  beginner: [
    {
      q: "What is Dart and why use it?",
      a: "Dart is a sound, garbage-collected language with AOT and JIT compilers. It is the language of Flutter and also runs on the VM and as compiled JS/Wasm.",
      e: "Interviews want null safety, isolates (not shared-memory threads), Future/Stream, and that Dart is not “just Flutter.” Mention sound typing and the C-like, class-based syntax.",
      visual: {
        title: "Where Dart shows up",
        kind: "hub",
        hub: "Dart",
        nodes: [
          { h: "Flutter", lines: ["UI toolkit"] },
          { h: "Null safety", lines: ["Sound by default"] },
          { h: "Isolates", lines: ["No shared memory"] },
          { h: "Future", lines: ["Async values"] },
          { h: "AOT / JIT", lines: ["Release vs hot reload"] },
          { h: "VM / JS", lines: ["More than mobile"] },
        ],
        footer: "A client language with isolates instead of shared threads",
      },
    },
    {
      q: "How does Dart null safety work?",
      a: "T cannot be null. T? can. The analyzer requires a null check, ??, or ! before using a nullable as T. This is sound: at runtime those checks hold (with a few legacy holes).",
      e: "late defers non-null assignment. required on named params is part of the same story. ! is an assertion — prefer promotion. legacy JavaScript interop and old packages were the migration pain.",
      visual: {
        title: "T vs T?",
        kind: "compare",
        left: {
          h: "String",
          lines: ["Never null", "No ! needed", "Default for fields", "Sound non-null"],
        },
        right: {
          h: "String?",
          lines: ["String or null", "Promote or ??", "Models missing data", "Use at boundaries"],
        },
        footer: "Null safety is sound — the runtime agrees with the analyzer",
      },
    },
    {
      q: "What do ?, ??, and ! mean?",
      a: "T? is nullable. ?? provides a default if the left side is null. ! asserts non-null and throws if it was null. ?. is a null-aware method/field access.",
      e: "??= assigns only if the variable is null. ?[] is null-aware index. Prefer if (x != null) promotion on locals over !. Never use ! to silence the analyzer on a field that can race.",
      visual: {
        title: "Null-aware operators",
        kind: "timeline",
        events: [
          { h: "Maybe null", lines: ["String? s"] },
          { h: "?. access", lines: ["s?.length"] },
          { h: "?? default", lines: ["s ?? \"\""] },
          { h: "! assert", lines: ["s!.length"] },
        ],
        footer: "?? is a default — ! is a bet you must be able to prove",
      },
    },
    {
      q: "What is the difference between var, final, and const?",
      a: "var infers a mutable binding. final infers (or takes) a single-assignment binding. const is a compile-time constant; the object is canonicalized and deeply immutable.",
      e: "const constructors create canonical instances (identical(a, b) can be true). final is runtime one-shot; const must be known at compile time. Flutter widgets lean on const to skip rebuild work — that is a language rule, not a widget API.",
      visual: {
        title: "Binding layers",
        kind: "layers",
        layers: [
          { h: "var", lines: ["Infer type, can rebind"] },
          { h: "final", lines: ["One assignment, runtime ok"] },
          { h: "const", lines: ["Compile-time, canonical"] },
          { h: "const constructor", lines: ["Deeply immutable instance"] },
        ],
        footer: "final locks the variable — const locks the value at compile time",
      },
    },
    {
      q: "How do you declare functions in Dart?",
      a: "Functions are first-class: they can be top-level, methods, or anonymous closures. Optional positional params use [ ], named params use { } and often required.",
      e: "=> is a single-expression body. Function types are written T Function(A, B) or typedefs. Closures capture variables. There is no overloading — use optional/named params instead.",
      visual: {
        title: "A small function",
        kind: "code",
        code: {
          file: "greet.dart",
          code: [
            "String greet(",
            "  String name, {",
            "  String hi = 'Hi',",
            "}) => '$hi, $name';",
            "greet('Ada', hi: 'Yo');",
          ],
          notes: [
            { h: "Named", text: "{ } params at the call site" },
            { h: "Default", text: "hi = 'Hi' if omitted" },
            { h: "=>", text: "Expression body, return implied" },
          ],
        },
        footer: "No overloads — optional and named parameters replace them",
      },
    },
    {
      q: "How do classes work in Dart?",
      a: "Dart is class-based with single inheritance, implicit interfaces (every class is an interface), and mixins for reused implementation. Constructors can be generative, named, or factory.",
      e: "There is no private keyword — a leading _ is library-private. this.field in constructors is initializing formals. cascade (..) chains calls on one object.",
      visual: {
        title: "From class to instance",
        kind: "steps",
        steps: [
          { h: "class User", lines: ["Fields · methods"] },
          { h: "Constructor", lines: ["User(this.name)"] },
          { h: "new is optional", lines: ["User('Ada')"] },
          { h: "_private", lines: ["Library, not class"] },
        ],
        footer: "Every class is also an interface — implements needs no extra type",
      },
    },
    {
      q: "Named vs positional parameters?",
      a: "Positional args are ordered; optional ones sit in [ ]. Named args are {name: value} and can be required. You can mix: required positional first, then named.",
      e: "Flutter-style APIs prefer named for readability (color:, child:). required is a null-safety keyword, not just documentation. Don’t make everything named — positional is fine for 1–2 obvious args.",
      visual: {
        title: "Two calling styles",
        kind: "compare",
        left: {
          h: "Positional",
          lines: ["Order matters", "[optional]", "Short APIs", "f(1, 2)"],
        },
        right: {
          h: "Named",
          lines: ["Labels at call site", "required available", "Self-documenting", "f(x: 1, y: 2)"],
        },
        footer: "Named + required is the modern Dart public-API default",
      },
    },
    {
      q: "How do List, Set, and Map work?",
      a: "They are generic collections: List<T>, Set<T>, Map<K,V>. Literals are [ ], { } for sets/maps (a map needs key: value). growable lists are the default.",
      e: "collection-if and spreads (... , ...?) build lists declaratively. Unmodifiable views exist. Prefer final list = <int>[]; typed literals over var list = [].",
      visual: {
        title: "Core collections",
        kind: "hub",
        hub: "Collections",
        nodes: [
          { h: "List", lines: ["Ordered"] },
          { h: "Set", lines: ["Unique"] },
          { h: "Map", lines: ["Key → value"] },
          { h: "Spread", lines: ["...other"] },
          { h: "collection-if", lines: ["if in literals"] },
          { h: "Generics", lines: ["List<int>"] },
        ],
        footer: "Typed literals beat untyped var x = [] in interviews",
      },
    },
    {
      q: "What is a Future at a beginner level?",
      a: "A Future<T> is a value that will be available later (success T or error). async functions return Futures. await pauses the async function until the Future completes — without blocking the isolate’s event loop.",
      e: "then/catchError is the older API; prefer async/await. Unawaited futures can hide errors — use unawaited() only when you mean it. Future.value / Future.error create already-completed futures.",
      visual: {
        title: "Wait without blocking",
        kind: "timeline",
        events: [
          { h: "Start work", lines: ["Future<T>"] },
          { h: "Event loop", lines: ["Other events run"] },
          { h: "Complete", lines: ["T or error"] },
          { h: "await resumes", lines: ["Use T"] },
        ],
        footer: "await is not a thread join — it is an event-loop pause",
      },
    },
    {
      q: "What is a mixin?",
      a: "A mixin is a type you with onto a class to reuse implementation without inheriting a full superclass. mixin M on Super can require a superclass.",
      e: "with order is linearization (last mixin wins conflicts). Mixins cannot declare constructors. Prefer mixin for capability chunks; extends for is-a. mixin class (Dart 3) can be both.",
      visual: {
        title: "Reuse without a base class",
        kind: "layers",
        layers: [
          { h: "mixin Log", lines: ["Reusable methods"] },
          { h: "class S with Log", lines: ["Implementation mixed in"] },
          { h: "on Super", lines: ["Optional superclass bound"] },
          { h: "No constructor", lines: ["Cannot new a mixin"] },
        ],
        footer: "with is implementation reuse — implements is a contract only",
      },
    },
    {
      q: "What kinds of constructors does Dart have?",
      a: "Generative constructors create the instance. Named constructors (User.guest()) are extra entry points. factory constructors may return an existing instance or a subtype. const constructors enable compile-time instances.",
      e: "Redirecting constructors call another (: this.other()). Initializer lists run before the body. factory is how caches and singletons stay typed.",
      visual: {
        title: "Constructor forms",
        kind: "code",
        code: {
          file: "user.dart",
          code: [
            "class User {",
            "  final String name;",
            "  const User(this.name);",
            "  factory User.anon() =>",
            "    const User('anon');",
            "}",
          ],
          notes: [
            { h: "Generative", text: "User(this.name) builds a new object" },
            { h: "const", text: "Canonical instance at compile time" },
            { h: "factory", text: "May return cached or other type" },
          ],
        },
        footer: "factory is not a second class — it is a constructor that can choose",
      },
    },
    {
      q: "What does the cascade operator do?",
      a: ".. (and ?..) sends multiple operations to the same object and then yields that object. It is for configuring instances without a temporary variable.",
      e: "Common in builder-style setup. Don’t use cascades where a constructor or copyWith is clearer. ?.. stops if the receiver is null. Cascades are not related to inheritance.",
      visual: {
        title: "Configure then keep",
        kind: "steps",
        steps: [
          { h: "Have object", lines: ["var p = Paint()"] },
          { h: "Cascade", lines: ["..color = red"] },
          { h: "More", lines: ["..strokeWidth = 2"] },
          { h: "Result", lines: ["Still the Paint"] },
        ],
        footer: "Cascade returns the receiver — not the last method’s value",
      },
    },
    {
      q: "How do isolates differ from threads (beginner)?",
      a: "An isolate is a Dart isolate: its own memory and event loop. Isolates do not share objects. They talk by passing messages (usually via ports), not by locking shared memory.",
      e: "The main isolate runs your app. Heavy CPU should go to another isolate (Isolate.run / compute in Flutter). This is why most Dart code is single-threaded in practice but still concurrent via the event loop.",
      visual: {
        title: "Separate heaps",
        kind: "cycle",
        center: "process",
        items: [
          { h: "Isolate A", lines: ["Own memory"] },
          { h: "Messages", lines: ["Copy / transfer"] },
          { h: "Isolate B", lines: ["Own memory"] },
          { h: "No shared objects", lines: ["No data races"] },
        ],
        footer: "Think actors with copies — not pthreads with a mutex",
      },
    },
    {
      q: "What does sound typing mean in Dart?",
      a: "If the static type says a value is T, the runtime is T (including null-safety). Generics are reified: List<int> is not List<String> at runtime.",
      e: "That is stronger than Java erasure. dynamic opts out of static checks. Object is the non-null root; you still cannot call arbitrary methods without a cast. Soundness is why AOT can specialize.",
      visual: {
        title: "Types that stay true",
        kind: "cycle",
        center: "sound",
        items: [
          { h: "Static T", lines: ["Analyzer"] },
          { h: "Runtime T", lines: ["VM agrees"] },
          { h: "Reified generics", lines: ["List<int> is real"] },
          { h: "dynamic", lines: ["Escape hatch"] },
        ],
        footer: "Sound + reified generics — a frequent Dart vs Java contrast",
      },
    },
    {
      q: "What does late mean?",
      a: "late T x; is a non-nullable field or local that you promise to assign before reading. late final is a lazy one-shot; the first read may run an initializer.",
      e: "Reading before assignment throws LateInitializationError. late is not nullable. Don’t use late to dodge null safety on fields that might never be set — use T? instead.",
      visual: {
        title: "Assign then read",
        kind: "steps",
        steps: [
          { h: "Declare late", lines: ["Non-null, not yet set"] },
          { h: "Assign", lines: ["Before first read"] },
          { h: "Read", lines: ["Value as T"] },
          { h: "Too early", lines: ["LateInitializationError"] },
        ],
        footer: "late is a promise — T? is honesty when the value may be missing",
      },
    },
  ],
  intermediate: [
    {
      q: "How do Future and Stream differ?",
      a: "A Future is one result (or error). A Stream is a sequence of events over time (zero or more data events, optionally an error, then done).",
      e: "async* + yield produces a Stream. await for consumes it. Single-subscription vs broadcast is the next question. Don’t use a Stream for one HTTP call — that is a Future.",
      visual: {
        title: "One shot vs many events",
        kind: "compare",
        left: {
          h: "Future<T>",
          lines: ["One value or error", "async / await", "HTTP · disk read", "Completes once"],
        },
        right: {
          h: "Stream<T>",
          lines: ["Many events", "await for / listen", "Clicks · ticks", "Single or broadcast"],
        },
        footer: "Future = one letter — Stream = a conversation",
      },
    },
    {
      q: "How does async/await schedule work?",
      a: "async functions return a Future immediately. await registers a completion callback and returns to the event loop. When the Future completes, the function resumes in a later microtask/event.",
      e: "await Future(() {}) vs scheduleMicrotask vs Future.delayed are different queues. Deadlocks happen if you block the isolate (sync I/O, Isolate.pause) — not because await “locks a thread.”",
      visual: {
        title: "Pause on the event loop",
        kind: "steps",
        steps: [
          { h: "Call async", lines: ["Get a Future"] },
          { h: "await", lines: ["Yield the isolate"] },
          { h: "Loop runs", lines: ["Other events"] },
          { h: "Resume", lines: ["Continue the function"] },
        ],
        footer: "await never blocks the isolate — blocking APIs do",
      },
    },
    {
      q: "How do SendPort and ReceivePort work?",
      a: "A ReceivePort listens for messages in this isolate. Its sendPort can be sent to another isolate, which uses SendPort.send to deliver messages (copied or transferred).",
      e: "You typically spawn an isolate with a SendPort argument so it can reply. Messages must be sendable (primitives, lists/maps of sendables, transferables). Errors need their own protocol — they don’t auto-cross.",
      visual: {
        title: "Ports between isolates",
        kind: "hub",
        hub: "message",
        nodes: [
          { h: "ReceivePort", lines: ["This isolate"] },
          { h: "sendPort", lines: ["Capability to send"] },
          { h: "spawn", lines: ["Pass the port"] },
          { h: "send", lines: ["Copy / transfer"] },
          { h: "listen", lines: ["Handle messages"] },
          { h: "close", lines: ["Shut the port"] },
        ],
        footer: "The port is the address — objects do not cross as references",
      },
    },
    {
      q: "When do you use a mixin vs extends vs implements?",
      a: "extends is single inheritance (is-a + implementation). implements is a contract only — you rewrite every member. with mixes in implementation from one or more mixins.",
      e: "implements a class uses its interface, ignoring its body. mixin on Foo requires the host to be a Foo. Interviews like: “Flutter’s State with TickerProvider” as a mixin example without becoming a widget lecture.",
      visual: {
        title: "Three reuse knobs",
        kind: "compare",
        left: {
          h: "extends / with",
          lines: ["Get implementation", "One superclass", "Many mixins", "Linearization order"],
        },
        right: {
          h: "implements",
          lines: ["Interface only", "You write the body", "Many types", "No super call"],
        },
        footer: "with reuses code — implements reuses a shape",
      },
    },
    {
      q: "What is a const constructor?",
      a: "A const constructor requires all fields to be final and all arguments to be compile-time constants. const Foo(1) canonicalizes: two const Foo(1) are identical.",
      e: "You can still call Foo(1) without const — that allocates a new object. In a const context the constructor is implicitly const. This is the language feature Flutter’s const widgets depend on.",
      visual: {
        title: "Canonical instances",
        kind: "code",
        code: {
          file: "point.dart",
          code: [
            "class P {",
            "  final int x;",
            "  const P(this.x);",
            "}",
            "const a = P(1);",
            "const b = P(1);",
            "// identical(a, b) == true",
          ],
          notes: [
            { h: "final fields", text: "Required for const constructors" },
            { h: "const call", text: "Canonicalized by the compiler" },
            { h: "New P(1)", text: "Without const, a fresh instance" },
          ],
        },
        footer: "const is identity at compile time — not a runtime intern cache you call",
      },
    },
    {
      q: "What is a factory constructor for?",
      a: "factory T(...) does not automatically allocate T. It can return a cached instance, a subtype, or throw. It is still invoked as T().",
      e: "Classic patterns: intern caches, FromJson returning a subtype, or returning a const. You cannot use this in the body the same way; you return an instance. Redirecting factories exist too.",
      visual: {
        title: "Constructor that chooses",
        kind: "layers",
        layers: [
          { h: "Call Color(0)", lines: ["Looks like new"] },
          { h: "factory body", lines: ["Lookup cache / subtype"] },
          { h: "Return instance", lines: ["May be existing"] },
          { h: "Caller", lines: ["Typed as Color"] },
        ],
        footer: "factory is Dart’s typed singleton/cache hook",
      },
    },
    {
      q: "How do generics work in Dart?",
      a: "Classes, functions, and typedefs take type parameters. Constraints use extends (T extends num). Generics are reified: you can test is List<int> at runtime.",
      e: "Unlike Java, List<int> and List<String> are different runtime types. Type arguments can be inferred. void as a type argument is allowed. Prefer explicit <T> on empty literals.",
      visual: {
        title: "Reified type argument",
        kind: "code",
        code: {
          file: "box.dart",
          code: [
            "class Box<T> {",
            "  T value;",
            "  Box(this.value);",
            "}",
            "var b = Box<int>(3);",
            "print(b is Box<int>); // true",
          ],
          notes: [
            { h: "Parameter", text: "T is part of the runtime type" },
            { h: "is test", text: "Works — not erased" },
            { h: "Infer", text: "Box(3) often infers Box<int>" },
          ],
        },
        footer: "Reified generics are a Dart/Java interview differentiator",
      },
    },
    {
      q: "What is a Zone?",
      a: "A Zone is an execution context that intercepts async callbacks: print, errors, timers, and scheduling. runZoned and runZonedGuarded fork a child zone.",
      e: "Flutter’s binding uses zones for error handling. Zone.current and zoneValues store context (like a thread-local, but for the event loop). Don’t use zones for DI in app code if you can pass arguments.",
      visual: {
        title: "Fork the async context",
        kind: "cycle",
        center: "Zone",
        items: [
          { h: "Parent zone", lines: ["Default"] },
          { h: "runZoned", lines: ["Fork"] },
          { h: "Callbacks", lines: ["Stay in child"] },
          { h: "Errors", lines: ["Guarded handler"] },
          { h: "Values", lines: ["zoneValues"] },
        ],
        footer: "A zone follows async callbacks — it is not a thread-local map you forget",
      },
    },
    {
      q: "How do you listen to and transform a Stream?",
      a: "listen registers callbacks (or await for in async). Transform with map, where, expand, asyncMap, and StreamTransformer. Always handle onError and cancel subscriptions you own.",
      e: "Single-subscription streams throw if listened twice; broadcast allows many. pause/resume is backpressure for some streams. StreamController is how you create a custom stream.",
      visual: {
        title: "Subscribe then transform",
        kind: "timeline",
        events: [
          { h: "Source", lines: ["Stream<T>"] },
          { h: "map / where", lines: ["New stream"] },
          { h: "listen", lines: ["Subscription"] },
          { h: "cancel", lines: ["Stop work"] },
        ],
        footer: "If you call listen, you own the StreamSubscription",
      },
    },
    {
      q: "What are extension methods?",
      a: "extension Name on Type { } adds methods/getters as if they were on the type. They are static sugar: resolved at compile time from the static type and imports.",
      e: "Dart 3 also has extension types (different feature — wrapping). Extensions do not change the runtime type. Name clashes are resolved by hiding/show on imports or explicit extension.method.",
      visual: {
        title: "Add API without a subclass",
        kind: "timeline",
        events: [
          { h: "extension on String", lines: ["Declare"] },
          { h: "Import", lines: ["Bring into scope"] },
          { h: "Call", lines: ["s.words"] },
          { h: "Compile", lines: ["Static target"] },
        ],
        footer: "Extensions are not mixins — there is no runtime slot on the object",
      },
    },
    {
      q: "What is a typedef?",
      a: "typedef names a function type or (in modern Dart) any type alias, including generics: typedef Json = Map<String, dynamic>;",
      e: "Classic: typedef Compare = int Function(T, T). Use them for callback-heavy APIs. They do not create new nominal types — two typedefs to the same function type are interchangeable.",
      visual: {
        title: "Name a type",
        kind: "layers",
        layers: [
          { h: "Function typedef", lines: ["Callback signatures"] },
          { h: "Type alias", lines: ["Json = Map<…>"] },
          { h: "Generics", lines: ["typedef Box<T> = …"] },
          { h: "Not nominal", lines: ["Same structure = same type"] },
        ],
        footer: "typedef is a name — not a new class",
      },
    },
    {
      q: "What are collection-if, collection-for, and spreads?",
      a: "Inside list/set/map literals you can write if, for, and ... / ...? to build elements declaratively. They are sugar for inserting zero or more elements.",
      e: "Very common in Flutter widget lists — still a Dart language feature. ...? skips null. They are not loops with breaks; keep them shallow.",
      visual: {
        title: "Build a list in place",
        kind: "steps",
        steps: [
          { h: "Literal", lines: ["["] },
          { h: "Spread", lines: ["...items"] },
          { h: "if", lines: ["if (ok) widget"] },
          { h: "Close", lines: ["]"] },
        ],
        footer: "Declarative inserts — not a replacement for a real loop",
      },
    },
    {
      q: "What are records and patterns (Dart 3)?",
      a: "Records are anonymous, typed tuples: (int, String) or (x: 1, y: 2). Patterns destructure records, lists, maps, and objects in switch and declarations.",
      e: "Records are values (== by fields) and can be records in lists. Pattern switch can be exhaustive. This replaced a lot of custom DTO classes for small returns. Not JSON — still need serialization.",
      visual: {
        title: "Tuple then destructure",
        kind: "hub",
        hub: "records",
        nodes: [
          { h: "Positional", lines: ["(1, 'a')"] },
          { h: "Named", lines: ["(x: 1, y: 2)"] },
          { h: "Type", lines: ["(int, String)"] },
          { h: "Pattern", lines: ["var (n, s) = r"] },
          { h: "switch", lines: ["Exhaustive cases"] },
          { h: "==", lines: ["Field-wise"] },
        ],
        footer: "Records are language tuples — patterns are how you unpack them",
      },
    },
    {
      q: "How did Dart 3 change enums?",
      a: "Enums can have fields, methods, constructors, and implement interfaces. They are still a closed set of instances. Enhanced enums replaced many small sealed-like hierarchies.",
      e: "You can mix in on enums. switch on enums is exhaustive. For payloads that differ per case, sealed classes + subclasses still win. Know both.",
      visual: {
        title: "Enums with behavior",
        kind: "cycle",
        center: "enum",
        items: [
          { h: "Fixed instances", lines: ["Closed set"] },
          { h: "Fields / methods", lines: ["Dart 3"] },
          { h: "switch", lines: ["Exhaustive"] },
          { h: "sealed classes", lines: ["When payloads differ"] },
          { h: "interfaces", lines: ["implements"] },
        ],
        footer: "Enhanced enums are types — not just integer names",
      },
    },
    {
      q: "What is a Completer?",
      a: "Completer<T> lets you create a Future and complete it later from a callback (complete / completeError). It is the bridge from callback APIs to async/await.",
      e: "Complete only once. Prefer async/await when you control the source. Completer.sync completes in the same event — know the re-entrancy trap. Timeout wrappers often use Completer.",
      visual: {
        title: "Callback to Future",
        kind: "timeline",
        events: [
          { h: "Completer()", lines: ["Make future"] },
          { h: "Return .future", lines: ["To awaiters"] },
          { h: "Callback fires", lines: ["complete(value)"] },
          { h: "Awaiters resume", lines: ["T is ready"] },
        ],
        footer: "Completer is for wrapping — not for ordinary async functions",
      },
    },
  ],
  expert: [
    {
      q: "How do isolates differ from OS threads in depth?",
      a: "Each isolate has its own heap, JIT/AOT code, and event loop. There is no shared mutable memory, so no need for locks on Dart objects. Communication copies (or transfers) messages; threads would share addresses.",
      e: "The VM may use a thread pool under isolates, but that is an implementation detail. Native FFI code can still race if it shares C memory. Isolate.run is the modern one-shot API; spawn is for long workers.",
      visual: {
        title: "Isolate vs thread",
        kind: "compare",
        left: {
          h: "Isolate",
          lines: ["Own heap", "Message passing", "No Dart data races", "Event loop each"],
        },
        right: {
          h: "OS thread",
          lines: ["Shared process heap", "Mutex / atomics", "Data races possible", "Same objects"],
        },
        footer: "Dart concurrency is isolation first — threads exist under the VM",
      },
    },
    {
      q: "How do you wire SendPort/ReceivePort for a worker isolate?",
      a: "Main creates a ReceivePort, spawns the worker with that sendPort, and the worker creates its own ReceivePort and sends it back. After the handshake, both sides have a two-way channel.",
      e: "TransferableTypedData / IsolateNameServer appear in advanced designs. Kill/exit must close ports or you leak. Errors should be a message type, not an uncaught throw in the worker.",
      visual: {
        title: "Handshake then chat",
        kind: "steps",
        steps: [
          { h: "Main ReceivePort", lines: ["Keep sendPort"] },
          { h: "spawn(worker, sp)", lines: ["Pass main’s port"] },
          { h: "Worker sends back", lines: ["Its SendPort"] },
          { h: "Two-way send", lines: ["Typed messages"] },
        ],
        footer: "First message is usually “here is my SendPort”",
      },
    },
    {
      q: "What is Never and how does sound null safety use it?",
      a: "Never is the bottom type: a function that always throws (or loops) returns Never. Null promotion and exhaustive switches rely on the type becoming Never in impossible branches.",
      e: "return throw e; is Never. Object? minus null is Object. The null-safety spec uses Never for the type of throw. Don’t confuse Never with void (void is a type you “don’t use,” not empty).",
      visual: {
        title: "Impossible values",
        kind: "layers",
        layers: [
          { h: "T?", lines: ["T or null"] },
          { h: "Promote away null", lines: ["Remaining is T"] },
          { h: "throw / return Never", lines: ["Branch cannot continue"] },
          { h: "Exhaustive switch", lines: ["Leftover is Never"] },
        ],
        footer: "Never means no value — void means ignore the value",
      },
    },
    {
      q: "How do you fork a Zone and why is it tricky?",
      a: "runZonedGuarded(body, onError, zoneValues: …, zoneSpecification: …) intercepts uncaught async errors and overrides print/schedule. Child async work stays in that zone unless it captures another.",
      e: "Timer and Future callbacks inherit the zone. Binding a listener in zone A then firing from zone B is a classic bug. Flutter tests use fake async zones. Overriding scheduleMicrotask can reorder the world — do it carefully.",
      visual: {
        title: "Zone intercepts",
        kind: "cycle",
        center: "fork",
        items: [
          { h: "Specification", lines: ["Override print"] },
          { h: "Values", lines: ["Token map"] },
          { h: "Body", lines: ["Your code"] },
          { h: "Async hop", lines: ["Stay in zone"] },
          { h: "onError", lines: ["Uncaught"] },
        ],
        footer: "Zones are powerful — they are also how async errors go missing",
      },
    },
    {
      q: "Single-subscription vs broadcast streams?",
      a: "A single-subscription stream allows one listener and buffers until listen (or is a true push after that). A broadcast stream allows many listeners and typically drops events when nobody is listening.",
      e: "asBroadcastStream() converts with caveats (late listeners miss prior events). StreamController.broadcast(sync: true) has re-entrancy rules. Using the wrong kind is a frequent production bug.",
      visual: {
        title: "Who may listen",
        kind: "compare",
        left: {
          h: "Single-subscription",
          lines: ["One listen()", "May buffer until then", "File / HTTP bodies", "Listen twice → error"],
        },
        right: {
          h: "Broadcast",
          lines: ["Many listeners", "Often no backlog", "Click buses", "Late listeners miss events"],
        },
        footer: "Pick the kind at construction — converting later loses history",
      },
    },
    {
      q: "Which Flutter-adjacent features are really Dart language features?",
      a: "const constructors (canonical widgets), collection-if in widget lists, mixins (TickerProvider), extension methods, and records for small returns. Widget itself is just a class — the framework is not the language.",
      e: "A strong answer separates Dart (const, isolates, sound types) from Flutter (Element tree, BuildContext). Interviewers ding people who can only explain setState.",
      visual: {
        title: "Language under the UI",
        kind: "layers",
        layers: [
          { h: "const constructor", lines: ["Canonical, skip work"] },
          { h: "mixins", lines: ["Ticker / Restoration"] },
          { h: "collection-if", lines: ["Child lists"] },
          { h: "Framework", lines: ["Widget / Element — not Dart"] },
        ],
        footer: "Answer in Dart first — then mention Flutter as a client",
      },
    },
    {
      q: "What is an extension type?",
      a: "An extension type (Dart 3) is a zero-cost wrapper: extension type Id(int v). It is a new static type that erases to the representation at runtime, with its own members.",
      e: "Unlike a class wrapper, no extra allocation. Unlike a typedef, it is nominal for static checking (you cannot pass int where Id is required, unless you allow implicit from the representation — design choice). Distinct from extension methods.",
      visual: {
        title: "Zero-cost nominal wrap",
        kind: "code",
        code: {
          file: "id.dart",
          code: [
            "extension type Id(int v) {",
            "  int get raw => v;",
            "}",
            "void f(Id id) {}",
            "f(Id(3));",
          ],
          notes: [
            { h: "Static", text: "Id is not int to the analyzer" },
            { h: "Runtime", text: "Still an int — no wrapper object" },
            { h: "vs class", text: "A class UserId would allocate" },
          ],
        },
        footer: "Extension types are brands — extension methods are extra API",
      },
    },
    {
      q: "How do pattern matching and sealed classes work together?",
      a: "sealed class hierarchies are exhaustive in switch. Patterns destructure fields (Ok(:var data)). The compiler proves you handled every subtype — adding a subtype is a compile error.",
      e: "This is Dart’s ADT story (like Kotlin sealed + when). Object patterns, list/map patterns, and logical patterns (&& / || / guard when) compose. Prefer sealed over enum when cases have different fields.",
      visual: {
        title: "Sealed plus switch",
        kind: "code",
        code: {
          file: "result.dart",
          code: [
            "sealed class R {}",
            "class Ok extends R {",
            "  final int v; Ok(this.v);",
            "}",
            "class Err extends R {}",
            "String msg(R r) => switch (r) {",
            "  Ok(:var v) => '$v',",
            "  Err() => 'err',",
            "};",
          ],
          notes: [
            { h: "sealed", text: "All subtypes known in this library" },
            { h: "Ok(:var v)", text: "Object pattern destructure" },
            { h: "Exhaustive", text: "No default — compiler checks" },
          ],
        },
        footer: "Sealed + patterns = compiler-checked variants",
      },
    },
    {
      q: "How does Isolate.run (and Flutter compute) move work off the UI isolate?",
      a: "Isolate.run(fn, message) spawns a short-lived isolate, sends the argument, runs fn, and returns a Future of the result. Flutter’s compute is a thin wrapper with the same idea.",
      e: "fn must be a top-level or static function (no closures capturing the main heap). Arguments/results must be sendable. Spawn cost is real — batch work. Errors complete the Future with an error.",
      visual: {
        title: "One-shot worker",
        kind: "timeline",
        events: [
          { h: "Main isolate", lines: ["UI / event loop"] },
          { h: "Isolate.run", lines: ["Spawn + send args"] },
          { h: "Worker fn", lines: ["Own heap"] },
          { h: "Result Future", lines: ["Copy back"] },
        ],
        footer: "Top-level function + sendable data — that is the contract",
      },
    },
    {
      q: "How does const canonicalization interact with identical()?",
      a: "Compile-time constants with the same structure are interned: identical(const [1], const [1]) is true. Runtime-created lists with the same contents are not identical and may not be == unless the type defines it.",
      e: "This is why const widgets can be skipped: the Element can use identical. Don’t rely on identical for user-created objects. Canonicalization is a compiler/VM rule, not something you intern() yourself.",
      visual: {
        title: "Same bits, one object",
        kind: "hub",
        hub: "const",
        nodes: [
          { h: "Compile-time", lines: ["Known value"] },
          { h: "Canonicalize", lines: ["Intern"] },
          { h: "identical", lines: ["true"] },
          { h: "New List", lines: ["Fresh heap"] },
          { h: "==", lines: ["Deep for some types"] },
          { h: "Widgets", lines: ["Skip rebuild"] },
        ],
        footer: "identical is pointer equality — const makes the pointers match",
      },
    },
    {
      q: "What can you send across isolates, and what is transfer?",
      a: "Sendable: null, bool, num, String, typed lists of those, SendPort, and (with care) certain collections. TransferableTypedData moves bytes without copying. Most objects cannot be sent by reference.",
      e: "Closures and class instances of your own types generally cannot cross unless you serialize. Errors should be mapped to messages. This is the expert follow-up to “just spawn an isolate.”",
      visual: {
        title: "What the port accepts",
        kind: "hub",
        hub: "send",
        nodes: [
          { h: "Primitives", lines: ["Copy"] },
          { h: "Lists / maps", lines: ["Deep copy"] },
          { h: "SendPort", lines: ["Capability"] },
          { h: "TypedData", lines: ["Copy or transfer"] },
          { h: "Your class", lines: ["Usually no"] },
          { h: "Closure", lines: ["No"] },
        ],
        footer: "If it closes over the main heap, it will not send",
      },
    },
    {
      q: "How do the event queue and microtask queue differ?",
      a: "Microtasks (scheduleMicrotask, then of an already-completed Future) run before the next event. Events are I/O, timers, and message ports. Starving the event queue with a microtask loop freezes UI and I/O.",
      e: "await Future.value() still schedules a microtask. Future(() {}) is an event. This is the Dart version of “microtasks vs macrotasks” in JS — a favorite expert question.",
      visual: {
        title: "Two queues, one isolate",
        kind: "timeline",
        events: [
          { h: "Drain microtasks", lines: ["Then-chain"] },
          { h: "One event", lines: ["Timer / I/O / port"] },
          { h: "Drain microtasks", lines: ["Again"] },
          { h: "Next event", lines: ["Repeat"] },
        ],
        footer: "A tight microtask loop never reaches timers or frames",
      },
    },
    {
      q: "How does mixin linearization work?",
      a: "class C extends B with M1, M2 applies mixins from left to right: M2 is the closest superclass of C. Super calls walk that chain. The result is a single superclass list, not multiple inheritance of classes.",
      e: "Conflicts: the last mixin wins unless you override in C. mixin on A requires B to be A. This is similar to Scala traits. Drawing the chain is the expected whiteboard answer.",
      visual: {
        title: "with order",
        kind: "cycle",
        center: "C",
        items: [
          { h: "B", lines: ["extends"] },
          { h: "M1", lines: ["with first"] },
          { h: "M2", lines: ["with last"] },
          { h: "C body", lines: ["Overrides"] },
          { h: "super", lines: ["Walk the chain"] },
        ],
        footer: "Last mixin is nearest super — that is linearization",
      },
    },
    {
      q: "How does covariance work in Dart generics?",
      a: "Dart generics are covariant: List<String> is a subtype of List<Object>. That is convenient and unsound for mutation — putting an int into a List<Object> that is really List<String> throws at runtime.",
      e: "The VM inserts checks on writes. Java arrays have the same story; Java generics do not (erasure + invariance). Expert answer: sound static null safety, still covariant generic classes with runtime checks.",
      visual: {
        title: "Convenient but checked",
        kind: "compare",
        left: {
          h: "Static",
          lines: ["List<String> is List<Object>", "Easy to pass around", "Covariant classes", "Analyzer allows the upcast"],
        },
        right: {
          h: "Runtime",
          lines: ["Write checks", "TypeError on bad add", "Reified element type", "Soundness via checks"],
        },
        footer: "Covariance is why add on a “List<Object>” can still throw",
      },
    },
    {
      q: "When do you use Object, dynamic, and void?",
      a: "Object? is the top of the non-dynamic hierarchy — you must cast or promote to call members. dynamic disables static checking and forwards at runtime. void means “do not use the value” (still a type).",
      e: "Returning void is not the same as returning Null/Never. List<void> shows up in callbacks. Prefer Object? for unknown JSON roots then parse; dynamic is the last resort. Implicit casts from dynamic are a soundness hole you opt into.",
      visual: {
        title: "Three “unknown” knobs",
        kind: "steps",
        steps: [
          { h: "Object?", lines: ["Must promote"] },
          { h: "dynamic", lines: ["No static checks"] },
          { h: "void", lines: ["Value ignored"] },
          { h: "Prefer Object?", lines: ["Then parse"] },
        ],
        footer: "dynamic turns the analyzer off — Object? keeps it on",
      },
    },
  ],
};
