module.exports = {
  name: "Java",
  description:
    "Java interview questions — JVM, memory model, generics, concurrency, and modern language features.",
  match: /^java$/i,
  theme: {
    accent: "#f89820",
    hubFill: "#f89820",
    hubText: "#0b1f3a",
    centerFill: "#ffedd5",
    centerStroke: "#f89820",
    label: "Java",
  },
  beginner: [
    {
      q: "What is Java and how does it run?",
      a: "Java is a statically typed, class-based language. Source compiles to bytecode that a JVM interprets and JIT-compiles, so the same class files run on any compatible runtime.",
      e: "Write once, run anywhere is about the bytecode contract, not a guarantee of identical performance. Interviews expect JDK vs JRE vs JVM and that the JVM is a specification with many implementations (HotSpot, OpenJ9).",
      visual: {
        title: "From source to a running JVM",
        kind: "hub",
        hub: "JVM",
        nodes: [
          { h: "javac", lines: [".java → bytecode"] },
          { h: ".class", lines: ["Portable bytes"] },
          { h: "Verifier", lines: ["Type-safe load"] },
          { h: "Interpreter", lines: ["Start executing"] },
          { h: "JIT", lines: ["Hot code to native"] },
          { h: "GC", lines: ["Manages the heap"] },
        ],
        footer: "The JVM runs bytecode — not your original .java files",
      },
    },
    {
      q: "What is the difference between JDK, JRE, and JVM?",
      a: "The JVM executes bytecode. The JRE is a JVM plus libraries to run apps. The JDK adds compilers, debuggers, and other tools you need to develop.",
      e: "Modern distributions blur JRE vs JDK because you usually ship a JDK or a jlink image. Still a classic interview triad: develop with JDK, run on a JVM, libraries live on the classpath or module path.",
      visual: {
        title: "JDK vs JRE vs JVM",
        kind: "compare",
        left: {
          h: "JDK (develop)",
          lines: ["javac · javadoc · jlink", "Includes a JRE/JVM", "Needed to compile", "CI and local builds"],
        },
        right: {
          h: "JVM (run)",
          lines: ["Loads and runs .class", "JIT · GC · threads", "Spec + implementations", "JRE = JVM + libs"],
        },
        footer: "You compile with a JDK — users run on a JVM",
      },
    },
    {
      q: "What are primitive types versus reference types?",
      a: "Primitives (int, long, boolean, double, …) are values stored directly. Reference types (classes, arrays, interfaces) are pointers to objects on the heap.",
      e: "Primitives have no methods and cannot be null. Wrapper classes (Integer) box them when APIs need objects. Mixing == on wrappers is a classic trap because of caching and identity.",
      visual: {
        title: "Where values live",
        kind: "steps",
        steps: [
          { h: "Declare", lines: ["int n = 3"] },
          { h: "Primitive", lines: ["Bits live in the slot"] },
          { h: "Reference", lines: ["Integer i = n"] },
          { h: "Heap object", lines: ["i points at a box"] },
        ],
        footer: "null is only legal for references — never for int",
      },
    },
    {
      q: "What is a class and what is an object?",
      a: "A class is the blueprint: fields, constructors, and methods. An object is a runtime instance of that class, allocated on the heap and accessed through a reference.",
      e: "static members belong to the class, not an instance. Interfaces and records are also types. Object identity (==) is not the same as equality (equals).",
      visual: {
        title: "Class then instance",
        kind: "code",
        code: {
          file: "User.java",
          code: [
            "public class User {",
            "  private final String name;",
            "  public User(String name) {",
            "    this.name = name;",
            "  }",
            "}",
            "User u = new User(\"Ada\");",
          ],
          notes: [
            { h: "Class", text: "Defines the shape and behavior" },
            { h: "new", text: "Allocates an instance on the heap" },
            { h: "u", text: "A reference to that instance" },
          ],
        },
        footer: "One class, many objects — each with its own field values",
      },
    },
    {
      q: "What do Java access modifiers control?",
      a: "public, protected, package-private (default), and private restrict which code can see a type or member. They are a compile-time encapsulation tool.",
      e: "Default (no modifier) is package-private, not public. protected includes the package plus subclasses. Nested types can see the outer private members. Modules add another export layer on top.",
      visual: {
        title: "Visibility from tight to open",
        kind: "layers",
        layers: [
          { h: "private", lines: ["Same class only"] },
          { h: "package-private", lines: ["Same package — the default"] },
          { h: "protected", lines: ["Package + subclasses"] },
          { h: "public", lines: ["Anywhere that can see the type"] },
        ],
        footer: "Default is package-private — not public",
      },
    },
    {
      q: "How do constructors work in Java?",
      a: "A constructor initializes a new instance. It has the class name, no return type, and is invoked by new (or by another constructor via this/super).",
      e: "If you write no constructor, Java supplies a no-arg default. The first line must chain to this(...) or super(...) — otherwise super() is inserted. Records get a canonical constructor.",
      visual: {
        title: "Object construction order",
        kind: "timeline",
        events: [
          { h: "Allocate", lines: ["Heap space for the instance"] },
          { h: "super()", lines: ["Initialize the parent first"] },
          { h: "Fields", lines: ["Initializers and instance blocks"] },
          { h: "Constructor body", lines: ["Your remaining setup"] },
        ],
        footer: "Parent constructors always run before the child’s body",
      },
    },
    {
      q: "What is the difference between static and instance members?",
      a: "Instance members belong to an object. static fields and methods belong to the class and are shared by all instances (and usable with no instance).",
      e: "A static method cannot use this or call instance methods without an object. Static state is global to the class loader — a source of leaks and test pollution. Prefer instance design unless sharing is the point.",
      visual: {
        title: "Class-level vs object-level",
        kind: "cycle",
        center: "Class",
        items: [
          { h: "static field", lines: ["One shared slot"] },
          { h: "static method", lines: ["No this"] },
          { h: "new Instance", lines: ["Own field values"] },
          { h: "instance method", lines: ["Uses this"] },
        ],
        footer: "static is shared per class loader — not a second object",
      },
    },
    {
      q: "How does equals differ from ==?",
      a: "== on references tests identity (same object). equals is a method meant to test value equality; Object’s default equals is still identity.",
      e: "Override equals and hashCode together. For String, == can appear to work because of interning — do not rely on it. Use Objects.equals for null-safe checks.",
      visual: {
        title: "Identity vs equality",
        kind: "hub",
        hub: "equals",
        nodes: [
          { h: "== refs", lines: ["Same pointer"] },
          { h: "== primitives", lines: ["Same bits"] },
          { h: "equals", lines: ["Value contract"] },
          { h: "hashCode", lines: ["Must stay in sync"] },
          { h: "String intern", lines: ["== can mislead"] },
          { h: "null", lines: ["NPE if you call it"] },
        ],
        footer: "Collections use equals and hashCode — not ==",
      },
    },
    {
      q: "Why are String objects immutable?",
      a: "Once created, a String’s characters never change. Concatenation and methods like substring (modern JDKs) produce new String objects.",
      e: "Immutability makes sharing, caching, and intern pools safe and keeps String usable as a HashMap key. StringBuilder exists for building text in a loop. Do not synchronize on interned strings.",
      visual: {
        title: "String vs StringBuilder",
        kind: "compare",
        left: {
          h: "String",
          lines: ["Immutable contents", "Safe to share", "Good as a map key", "Concat creates new objects"],
        },
        right: {
          h: "StringBuilder",
          lines: ["Mutable buffer", "Not thread-safe", "Use in local loops", "toString() when done"],
        },
        footer: "StringBuffer is the old synchronized cousin — rarely needed",
      },
    },
    {
      q: "When do you use an array versus ArrayList?",
      a: "Arrays have a fixed length and can hold primitives. ArrayList is a resizable List of references with helper methods (add, get, iterator).",
      e: "ArrayList stores Object references; primitives are boxed. Prefer List as the API type. Arrays are covariant (String[] is Object[]) which can throw ArrayStoreException — lists with generics are safer.",
      visual: {
        title: "Fixed store vs resizable list",
        kind: "steps",
        steps: [
          { h: "Know size", lines: ["int[] a = new int[3]"] },
          { h: "Need grow", lines: ["new ArrayList<>()"] },
          { h: "Add items", lines: ["list.add(x)"] },
          { h: "Program to List", lines: ["List<T> in APIs"] },
        ],
        footer: "Arrays are covariant — generic lists are not",
      },
    },
    {
      q: "How do inheritance and method overriding work?",
      a: "A subclass extends one superclass and inherits members. Overriding replaces an instance method with the same signature; the runtime type decides which body runs (dynamic dispatch).",
      e: "@Override catches signature mistakes. private, static, and final methods do not override. super.method() calls the parent. Prefer composition when you only need reuse, not an is-a relationship.",
      visual: {
        title: "Dynamic dispatch",
        kind: "code",
        code: {
          file: "Shape.java",
          code: [
            "class Shape {",
            "  void draw() { }",
            "}",
            "class Circle extends Shape {",
            "  @Override void draw() { }",
            "}",
            "Shape s = new Circle();",
            "s.draw(); // Circle.draw",
          ],
          notes: [
            { h: "Static type", text: "Shape is what the compiler sees" },
            { h: "Runtime type", text: "Circle is what new created" },
            { h: "Override", text: "Instance method chosen at runtime" },
          ],
        },
        footer: "The compiler checks Shape — the JVM calls Circle",
      },
    },
    {
      q: "When do you choose an interface over an abstract class?",
      a: "An interface declares a capability a type can implement (and since Java 8 may include default/static methods). An abstract class is a partial implementation you extend once.",
      e: "A class can implement many interfaces but extend only one class. Use abstract class for shared state and protected helpers. Use interfaces for APIs and mixins. Default methods can create diamond conflicts.",
      visual: {
        title: "Capability vs partial type",
        kind: "layers",
        layers: [
          { h: "interface", lines: ["Many implements · API contracts · default methods"] },
          { h: "abstract class", lines: ["Single extends · fields · protected helpers"] },
          { h: "concrete class", lines: ["Can mix both — prefer interfaces at boundaries"] },
        ],
        footer: "Java has single class inheritance and multiple interface implementation",
      },
    },
    {
      q: "What is the difference between checked and unchecked exceptions?",
      a: "Checked exceptions (Exception minus RuntimeException) must be caught or declared. Unchecked exceptions (RuntimeException and Error) need not be declared.",
      e: "Checked exceptions document recoverable failures (IOException). Unchecked ones are usually bugs (NullPointerException). Do not catch Error. Wrapping checked exceptions in unchecked is common at API boundaries.",
      visual: {
        title: "Exception hierarchy in practice",
        kind: "timeline",
        events: [
          { h: "Throwable", lines: ["Root of the hierarchy"] },
          { h: "Error", lines: ["Do not catch — JVM distress"] },
          { h: "RuntimeException", lines: ["Unchecked — usually bugs"] },
          { h: "Other Exception", lines: ["Checked — declare or handle"] },
        ],
        footer: "Error and RuntimeException are unchecked — the rest of Exception is checked",
      },
    },
    {
      q: "What is autoboxing and unboxing?",
      a: "Autoboxing converts a primitive to its wrapper (int → Integer). Unboxing goes the other way. The compiler inserts valueOf and intValue calls.",
      e: "Unboxing null throws NullPointerException. Integer == Integer uses identity; cache is only -128..127 by default. Prefer primitives in hot loops and be careful with generic collections of wrappers.",
      visual: {
        title: "Box, use, unbox",
        kind: "cycle",
        center: "int",
        items: [
          { h: "primitive", lines: ["int n = 3"] },
          { h: "box", lines: ["Integer i = n"] },
          { h: "collection", lines: ["List<Integer>"] },
          { h: "unbox", lines: ["int x = i"] },
        ],
        footer: "Unboxing null is an NPE — == on wrappers is identity",
      },
    },
    {
      q: "How do packages organize Java code?",
      a: "A package is a namespace for types (com.acme.app). It also defines the default access boundary. The classpath/module path tells the JVM where to load those types from.",
      e: "Directory layout must match the package name. Split packages (same package in two JARs) break JPMS. import is compile-time sugar — it does not load code. Collision of simple names is why FQCNs exist.",
      visual: {
        title: "Package as namespace and boundary",
        kind: "hub",
        hub: "package",
        nodes: [
          { h: "Namespace", lines: ["Unique type names"] },
          { h: "Access", lines: ["Default visibility"] },
          { h: "Directory", lines: ["Must match name"] },
          { h: "import", lines: ["Compile-time alias"] },
          { h: "classpath", lines: ["Where to load"] },
          { h: "modules", lines: ["Exports tighten this"] },
        ],
        footer: "import does not load classes — the JVM does, by name",
      },
    },
  ],
  intermediate: [
    {
      q: "How do you use generics in day-to-day Java?",
      a: "Generics parameterize types (List<String>) so the compiler checks element types. Methods can declare their own type parameters. Bounds (T extends Number) restrict what callers may pass.",
      e: "At runtime most type arguments are erased. You cannot new T(), create T[], or use instanceof List<String>. Use bounded wildcards (? extends / ? super) at API boundaries — PECS.",
      visual: {
        title: "Generic list in source",
        kind: "steps",
        steps: [
          { h: "Declare", lines: ["List<String> names"] },
          { h: "Compiler checks", lines: ["add(String) only"] },
          { h: "Erase", lines: ["List at runtime"] },
          { h: "Casts inserted", lines: ["get() → String"] },
        ],
        footer: "Generics are a compile-time contract — the JVM sees raw types",
      },
    },
    {
      q: "What is the equals and hashCode contract?",
      a: "If two objects are equal, they must have the same hashCode. hashCode may collide for unequal objects. equals must be reflexive, symmetric, transitive, consistent, and false for null.",
      e: "Breaking this corrupts HashMap and HashSet. Include the same fields in both methods. Mutable keys are dangerous if a field used in equals/hashCode changes while the object is in a set.",
      visual: {
        title: "Keep equals and hashCode in sync",
        kind: "code",
        code: {
          file: "User.java",
          code: [
            "public boolean equals(Object o) {",
            "  return o instanceof User u",
            "      && id.equals(u.id);",
            "}",
            "public int hashCode() {",
            "  return id.hashCode();",
            "}",
          ],
          notes: [
            { h: "Same fields", text: "Whatever equals uses, hashCode uses" },
            { h: "instanceof", text: "Pattern match avoids a raw cast" },
            { h: "Maps", text: "HashMap buckets by hashCode then equals" },
          ],
        },
        footer: "Equal objects must hash the same — or maps lose them",
      },
    },
    {
      q: "How does HashMap store and look up entries?",
      a: "HashMap buckets by hashCode (mixed), then compares keys with equals. Colliding keys chain in a list that treeifies under high collision (Comparable keys help).",
      e: "Capacity is a power of two; load factor 0.75 triggers resize. null key is allowed in HashMap, not in ConcurrentHashMap. Never mutate a key after insert. Iterate with entrySet, not repeated get.",
      visual: {
        title: "HashMap lookup cycle",
        kind: "cycle",
        center: "get",
        items: [
          { h: "hashCode", lines: ["Spread the bits"] },
          { h: "bucket", lines: ["Index into table"] },
          { h: "equals", lines: ["Find the key"] },
          { h: "value", lines: ["Return or null"] },
          { h: "resize", lines: ["If load is high"] },
        ],
        footer: "Tree bins need consistent Comparable order on keys",
      },
    },
    {
      q: "What is the difference between Comparable and Comparator?",
      a: "Comparable is the type’s natural order (compareTo). Comparator is an external ordering you pass to sort or to TreeMap. A type can have many comparators but one natural order.",
      e: "compare and equals should agree or sorted sets behave oddly. Comparator.comparing plus thenComparing is the modern style. Never return Integer.MIN_VALUE tricks that overflow on negation.",
      visual: {
        title: "Natural order vs supplied order",
        kind: "compare",
        left: {
          h: "Comparable",
          lines: ["Inside the class", "compareTo", "One natural order", "TreeSet default"],
        },
        right: {
          h: "Comparator",
          lines: ["Outside the class", "Many orderings", "Pass into sort()", "Can reverse / nullsFirst"],
        },
        footer: "Natural order is compareTo — everything else is a Comparator",
      },
    },
    {
      q: "How does the Streams API work, and when should you avoid it?",
      a: "A stream is a lazy pipeline: source → intermediate ops (filter, map) → terminal op (collect, reduce). It does not store data; it describes computation over a source.",
      e: "Do not use streams for every loop. Side effects in map are a smell. parallel() only helps CPU-heavy, splittable work with no shared mutation. Checked exceptions inside lambdas are awkward.",
      visual: {
        title: "Stream pipeline pieces",
        kind: "hub",
        hub: "Stream",
        nodes: [
          { h: "Source", lines: ["list.stream()"] },
          { h: "filter", lines: ["Keep some"] },
          { h: "map", lines: ["Transform"] },
          { h: "flatMap", lines: ["Unwrap lists"] },
          { h: "collect", lines: ["Terminal — runs it"] },
          { h: "parallel", lines: ["Only when it pays"] },
        ],
        footer: "Nothing runs until a terminal operation — then the source is consumed",
      },
    },
    {
      q: "What is try-with-resources?",
      a: "try (Resource r = ...) closes AutoCloseable resources in reverse order when the block exits, even on exception. Close exceptions can be suppressed on the primary throwable.",
      e: "Prefer this over a finally close. Resources must be effectively final. getSuppressed() matters when close() fails too. Input streams, JDBC, and locks that are AutoCloseable all belong here.",
      visual: {
        title: "Acquire, use, always close",
        kind: "layers",
        layers: [
          { h: "try (open)", lines: ["Resource implements AutoCloseable"] },
          { h: "use", lines: ["Read or write in the block"] },
          { h: "close()", lines: ["Called on all paths, reverse order"] },
          { h: "suppressed", lines: ["Close failures attach to the main exception"] },
        ],
        footer: "finally-close is easy to get wrong — try-with-resources is the default",
      },
    },
    {
      q: "When should you use Optional?",
      a: "Optional<T> is a container for a value that may be absent. It is meant as a return type so callers cannot forget the empty case, not as a field or method parameter.",
      e: "Do not call get() without isPresent — use orElse, orElseGet, orElseThrow, or map. Optional is not serializable-friendly as a bean field. Nested Optional and Optional.of(null) are mistakes (NPE).",
      visual: {
        title: "Return Optional, then unwrap",
        kind: "timeline",
        events: [
          { h: "Lookup", lines: ["May find nothing"] },
          { h: "Return Optional", lines: ["of / ofNullable / empty"] },
          { h: "Transform", lines: ["map · flatMap · filter"] },
          { h: "Exit", lines: ["orElse · orElseThrow"] },
        ],
        footer: "Optional is for return values — not for fields or parameters",
      },
    },
    {
      q: "What are lambdas and functional interfaces?",
      a: "A functional interface has one abstract method. A lambda (or method reference) implements that method. Lambdas capture effectively final locals from the enclosing scope.",
      e: "@FunctionalInterface documents the intent. Capturing mutable state is a concurrency bug. Lambdas are not anonymous classes: this refers to the enclosing instance, and they are often invokedynamic + a runtime spin.",
      visual: {
        title: "From interface to lambda",
        kind: "steps",
        steps: [
          { h: "SAM type", lines: ["Predicate<T>"] },
          { h: "Lambda", lines: ["x -> x.isBlank()"] },
          { h: "Capture", lines: ["Effectively final locals"] },
          { h: "Call", lines: ["test(value)"] },
        ],
        footer: "this inside a lambda is the enclosing class, not the lambda",
      },
    },
    {
      q: "What are records and when do you use them?",
      a: "A record is a transparent, immutable data carrier: final fields (components), a canonical constructor, accessors, and well-defined equals/hashCode/toString.",
      e: "Use records for DTOs, keys, and algebraic-style results. You can compact-construct to validate. They cannot extend a class (they already extend Record) but can implement interfaces. Reflection and serialization have special cases.",
      visual: {
        title: "Record as a data carrier",
        kind: "code",
        code: {
          file: "Point.java",
          code: [
            "public record Point(int x, int y) {",
            "  public Point {",
            "    if (x < 0 || y < 0)",
            "      throw new IllegalArgumentException();",
            "  }",
            "}",
          ],
          notes: [
            { h: "Components", text: "x and y are private final fields" },
            { h: "Compact ctor", text: "Validates before assignment" },
            { h: "Equals", text: "Value-based on all components" },
          ],
        },
        footer: "Records are immutable by design — not a replacement for every bean",
      },
    },
    {
      q: "When do you use ConcurrentHashMap instead of a synchronized Map?",
      a: "ConcurrentHashMap allows concurrent readers and a high number of writers without locking the whole map. Collections.synchronizedMap wraps every method with one lock.",
      e: "CHM does not allow null keys or values. Compound actions (check-then-act) still need compute/merge, not get+put. Iteration is weakly consistent. synchronizedMap is simpler but scales poorly.",
      visual: {
        title: "Whole-map lock vs concurrent map",
        kind: "cycle",
        center: "CHM",
        items: [
          { h: "get", lines: ["Usually lock-free"] },
          { h: "put", lines: ["Bins, not the map"] },
          { h: "compute", lines: ["Atomic compound"] },
          { h: "iterate", lines: ["Weakly consistent"] },
        ],
        footer: "synchronizedMap locks everything — CHM still needs atomic compounds",
      },
    },
    {
      q: "What do final and effectively final mean?",
      a: "A final variable cannot be reassigned. A local is effectively final if it is never reassigned, even without the keyword. Lambdas and anonymous classes may capture only those.",
      e: "final fields help safe publication under the JMM if the object does not leak this during construction. final on a reference does not make the object immutable. Blank finals must be assigned in every constructor.",
      visual: {
        title: "final vs immutable",
        kind: "compare",
        left: {
          h: "final reference",
          lines: ["Cannot rebind the var", "Object may still mutate", "Helps safe publication", "Required for capture"],
        },
        right: {
          h: "Immutable type",
          lines: ["No mutators at all", "Records · String", "Safe as map keys", "Deep vs shallow copy"],
        },
        footer: "final stops reassignment — immutability stops mutation",
      },
    },
    {
      q: "What can Java enums do besides name constants?",
      a: "Enums are classes: they can have fields, methods, constructors, and implement interfaces. Each constant is a singleton instance. You can give constants constant-specific method bodies.",
      e: "Enum constructors are private. Switch on enums is exhaustive with sealed-style warnings in modern Java. EnumSet and EnumMap are specialized and fast. Never instantiate enums via reflection in production code.",
      visual: {
        title: "Enum as a restricted class",
        kind: "hub",
        hub: "enum",
        nodes: [
          { h: "Constants", lines: ["Singleton instances"] },
          { h: "Fields", lines: ["Per-constant data"] },
          { h: "Methods", lines: ["Shared behavior"] },
          { h: "Switch", lines: ["Exhaustive cases"] },
          { h: "EnumSet", lines: ["Bit-set of constants"] },
          { h: "Serialize", lines: ["By name, not fields"] },
        ],
        footer: "Enums are classes with a fixed instance set — not just integers",
      },
    },
    {
      q: "How do annotations work in Java?",
      a: "Annotations are metadata on declarations (and since Java 8 on types). Retention (SOURCE, CLASS, RUNTIME) decides whether they survive to the class file and reflection.",
      e: "@Override is SOURCE. Many frameworks use RUNTIME plus reflection or processors. Annotation processors (and later classfile APIs) generate code at compile time. Repeatable annotations need a container annotation.",
      visual: {
        title: "Annotation retention layers",
        kind: "layers",
        layers: [
          { h: "SOURCE", lines: ["Compiler only — @Override, @SuppressWarnings"] },
          { h: "CLASS", lines: ["In the .class file, not reflective by default"] },
          { h: "RUNTIME", lines: ["Visible via reflection — framework wiring"] },
        ],
        footer: "If a tool cannot see your annotation, check Retention and Target",
      },
    },
    {
      q: "How does CompletableFuture compose asynchronous work?",
      a: "CompletableFuture represents a result that may complete later. thenApply/thenCompose chain work; thenCombine joins two futures; exceptionally recovers. You can complete it manually or via an executor.",
      e: "thenApply vs thenCompose is map vs flatMap. Default async methods use ForkJoinPool.commonPool() — pass an executor in servers. Avoid blocking join() on the common pool. Cancellation does not interrupt by default.",
      visual: {
        title: "Compose then complete",
        kind: "timeline",
        events: [
          { h: "supplyAsync", lines: ["Start work on a pool"] },
          { h: "thenCompose", lines: ["Chain another future"] },
          { h: "thenCombine", lines: ["Join a second result"] },
          { h: "exceptionally", lines: ["Recover or complete"] },
        ],
        footer: "Do not join() the common pool from inside its own tasks",
      },
    },
    {
      q: "What does local-variable type inference (var) do?",
      a: "var lets the compiler infer a local variable’s type from the initializer. It is not a dynamic type and cannot be a field or a method parameter.",
      e: "Use var when the type is obvious (new HashMap<>(), try-with-resources). Do not hide important API types behind var. var with the diamond operator infers from the left in limited ways — read the initializer.",
      visual: {
        title: "var is still static typing",
        kind: "steps",
        steps: [
          { h: "Write initializer", lines: ["new ArrayList<String>()"] },
          { h: "Infer", lines: ["ArrayList<String>"] },
          { h: "Use", lines: ["Same checks as explicit"] },
          { h: "Limit", lines: ["Locals only"] },
        ],
        footer: "var never means Object or loosely typed — the compiler still knows",
      },
    },
  ],
  expert: [
    {
      q: "How is JVM memory organized?",
      a: "Each thread has a stack (frames, locals, partial results) and a program counter. The heap holds objects and is GC-managed. Metaspace holds class metadata. Native memory backs direct buffers, JIT code, and thread stacks.",
      e: "PermGen is gone (Java 8+). OutOfMemoryError can be heap, metaspace, or native. Escape analysis may allocate some objects on the stack. Off-heap (DirectByteBuffer) is invisible to normal heap dumps until you look for it.",
      visual: {
        title: "JVM memory areas",
        kind: "layers",
        layers: [
          { h: "Thread stacks", lines: ["Frames · locals · PC — not GC’d as objects"] },
          { h: "Heap", lines: ["Objects · arrays — young / old / regions"] },
          { h: "Metaspace", lines: ["Class metadata · native, grows"] },
          { h: "Native / CodeCache", lines: ["Direct buffers · JIT nmethods"] },
        ],
        footer: "OOM is not always the Java heap — check metaspace and native too",
      },
    },
    {
      q: "What is the Java Memory Model and happens-before?",
      a: "The JMM defines which writes a thread is allowed to see. A happens-before edge (unlock→lock, volatile write→read, thread start/join, final field init) makes a write visible and ordered.",
      e: "Without those edges, the compiler and CPU may reorder. synchronized and volatile are not the same: locks give mutual exclusion plus HB; volatile gives visibility/ordering without exclusion. Data races are undefined in practice — bugs, not just stale reads.",
      visual: {
        title: "Establishing happens-before",
        kind: "timeline",
        events: [
          { h: "Write in A", lines: ["x = 1 under a lock"] },
          { h: "Unlock / volatile", lines: ["Publish the store"] },
          { h: "Lock / volatile read", lines: ["Thread B synchronizes"] },
          { h: "Read in B", lines: ["Must see x == 1"] },
        ],
        footer: "No happens-before means no guarantee you will see the write",
      },
    },
    {
      q: "How do modern HotSpot collectors differ (G1 vs ZGC)?",
      a: "G1 is a region-based generational collector that evacuates regions to meet a pause goal. ZGC (and Shenandoah) aims for sub-millisecond pauses using colored pointers and load barriers, scaling to huge heaps.",
      e: "Throughput vs latency is the real trade-off. G1 is the usual server default. ZGC shines when pause time matters more than a bit of throughput. Tuning blindly (huge heaps, tiny pause goals) causes to-space exhaustion and allocation stalls.",
      visual: {
        title: "Collector design knobs",
        kind: "hub",
        hub: "GC",
        nodes: [
          { h: "G1", lines: ["Regions + pauses"] },
          { h: "ZGC", lines: ["Ultra-low pause"] },
          { h: "Generational", lines: ["Young dies fast"] },
          { h: "Barriers", lines: ["Load / store"] },
          { h: "Tuning", lines: ["Pause vs throughput"] },
          { h: "Allocation", lines: ["TLAB · stalls"] },
        ],
        footer: "Pick a collector for the latency SLO — then measure allocation rate",
      },
    },
    {
      q: "How does type erasure actually work?",
      a: "The compiler erases type arguments to their bounds (Object if unbounded), inserts casts, and generates bridges for overrides. Overloads cannot differ only by type arguments.",
      e: "Reifiable types (arrays, primitives, non-generic classes) still exist at runtime. Heap pollution happens when a raw type bypasses the checker. varargs of generics are unchecked. Records and sealed types do not bring reified parameters.",
      visual: {
        title: "Erase, then cast",
        kind: "code",
        code: {
          file: "Erase.java",
          code: [
            "List<String> a = new ArrayList<>();",
            "List raw = a;",
            "raw.add(1); // heap pollution",
            "String s = a.get(0); // CCE",
          ],
          notes: [
            { h: "Erase", text: "List<String> is List at runtime" },
            { h: "Raw", text: "Bypasses the generic checker" },
            { h: "CCE", text: "The inserted cast fails on get" },
          ],
        },
        footer: "Generics are not reified — arrays are, which is why they clash",
      },
    },
    {
      q: "How does class loading work in the JVM?",
      a: "Classes are loaded, linked (verify, prepare, optionally resolve), then initialized. HotSpot uses a hierarchy: bootstrap, platform, and application loaders, plus custom loaders for isolation.",
      e: "A class’s identity is name + loader. That is why you can see ClassCastException between two copies of the same class. Parent-first vs child-first (web apps) changes shadowing. Class.forName initializes; ClassLoader.loadClass may not.",
      visual: {
        title: "Loaders and identity",
        kind: "compare",
        left: {
          h: "Delegation (usual)",
          lines: ["Ask parent first", "Bootstrap → platform → app", "Avoids duplicate JDK types", "Custom loaders last"],
        },
        right: {
          h: "Identity trap",
          lines: ["Name + loader = class", "Two loaders, two classes", "Casts fail across them", "Leaks pin loaders"],
        },
        footer: "The same FQCN from two loaders is two different Class objects",
      },
    },
    {
      q: "What are virtual threads and how do they change blocking I/O?",
      a: "Virtual threads (Project Loom) are JVM-scheduled, cheap threads that unmount from a carrier when they block on most JDK I/O. You can have millions of them for concurrent blocking work.",
      e: "Do not pool virtual threads. Avoid pinning: synchronized around long blocking I/O (improved in later JDKs) and native calls. ThreadLocals can be expensive at this scale — prefer scoped values. CPU-bound work still needs a bound pool.",
      visual: {
        title: "Mount, block, unmount",
        kind: "cycle",
        center: "VT",
        items: [
          { h: "mount", lines: ["On a carrier"] },
          { h: "run Java", lines: ["Until a block"] },
          { h: "unmount", lines: ["Carrier is free"] },
          { h: "resume", lines: ["Mount again"] },
          { h: "pin risk", lines: ["synchronized I/O"] },
        ],
        footer: "Virtual threads multiply concurrency — they do not multiply CPU cores",
      },
    },
    {
      q: "When do you use volatile, synchronized, or atomic classes?",
      a: "volatile publishes a single variable’s writes. synchronized (or ReentrantLock) gives exclusion and happens-before for a critical section. Atomic* and VarHandle give lock-free CAS on one location.",
      e: "volatile++ is not atomic. Atomics do not compose — two atomics need a lock or a single atomic structure. StampedLock and LongAdder exist for special cases. Prefer java.util.concurrent structures over rolling your own.",
      visual: {
        title: "Pick the concurrency primitive",
        kind: "steps",
        steps: [
          { h: "One flag", lines: ["volatile boolean"] },
          { h: "One counter", lines: ["AtomicInteger / LongAdder"] },
          { h: "Invariant on many", lines: ["synchronized / lock"] },
          { h: "Map of state", lines: ["ConcurrentHashMap"] },
        ],
        footer: "CAS is not a substitute for a multi-field invariant",
      },
    },
    {
      q: "What do JIT inlining and escape analysis change?",
      a: "HotSpot interprets first, then JITs hot methods. Inlining removes call overhead and enables further opts. Escape analysis can scalar-replace objects that never escape, so they never hit the heap.",
      e: "This is why microbenchmarks lie without JMH: you can measure a path the JIT deleted. Megamorphic call sites (many receivers) inhibit inlining. -XX:+PrintInlining and flight recorder are how you prove it.",
      visual: {
        title: "Hot path optimization",
        kind: "layers",
        layers: [
          { h: "Interpreter", lines: ["Profile call sites and types"] },
          { h: "C1 / C2 JIT", lines: ["Compile hot methods to native"] },
          { h: "Inline + EA", lines: ["Erase calls and some allocations"] },
          { h: "Deopt", lines: ["If a speculative type is wrong"] },
        ],
        footer: "The JIT may delete allocations your source clearly shows",
      },
    },
    {
      q: "How do sealed classes and pattern matching work together?",
      a: "sealed types list permitted subtypes. Switch and instanceof pattern matching can be exhaustive over that closed set, so the compiler errors when a case is missing.",
      e: "Permits can be in the same compilation unit or named explicitly. Records plus sealed interfaces model algebraic data types. Exhaustiveness is a compile-time property — new subtypes in another JAR require a rebuild of the switch.",
      visual: {
        title: "Closed hierarchy, exhaustive switch",
        kind: "timeline",
        events: [
          { h: "sealed Shape", lines: ["permits Circle, Rect"] },
          { h: "Add a case", lines: ["switch (shape)"] },
          { h: "Patterns", lines: ["case Circle c ->"] },
          { h: "Compile error", lines: ["If a subtype is missing"] },
        ],
        footer: "Sealed is how Java gets ADT-style exhaustiveness",
      },
    },
    {
      q: "How does ForkJoinPool steal work?",
      a: "ForkJoinPool workers each have a deque. A task fork()s subtasks onto its local deque; idle workers steal from the tail of others. join() waits, possibly running other work to avoid deadlock.",
      e: "The common pool size defaults to cores-1. Blocking inside FJP tasks starves the pool — use ManagedBlocker or a separate executor. parallel streams use this pool. RecursiveTask vs RecursiveAction is value vs void.",
      visual: {
        title: "Work-stealing pool",
        kind: "hub",
        hub: "FJP",
        nodes: [
          { h: "fork", lines: ["Push a subtask"] },
          { h: "local deque", lines: ["LIFO for owner"] },
          { h: "steal", lines: ["FIFO from others"] },
          { h: "join", lines: ["Help or wait"] },
          { h: "commonPool", lines: ["parallelStream"] },
          { h: "block", lines: ["Can stall workers"] },
        ],
        footer: "Blocking in the common pool is a production outage waiting to happen",
      },
    },
    {
      q: "When do you use weak, soft, and phantom references?",
      a: "Soft references are cleared under memory pressure (caches). Weak references are cleared when only weak reachability remains (canonical maps). Phantom references notify after finalization-time, used for cleanup (Cleaner).",
      e: "WeakHashMap is weak on keys only. Reference queues are how you learn a referent died. Finalizers are deprecated and hostile to GC — use Cleaner or try-with-resources. Caches should usually have size/time bounds, not only SoftReference.",
      visual: {
        title: "Reference strength",
        kind: "code",
        code: {
          file: "Refs.java",
          code: [
            "var wr = new WeakReference<>(obj);",
            "var sr = new SoftReference<>(obj);",
            "var pr = new PhantomReference<>(",
            "    obj, queue);",
            "obj = null; // drop strong ref",
          ],
          notes: [
            { h: "Weak", text: "GC can reclaim as soon as nothing strong remains" },
            { h: "Soft", text: "Kept until the collector feels memory pressure" },
            { h: "Phantom", text: "Enqueue for cleanup — referent not get()-able" },
          ],
        },
        footer: "A cache that is only a SoftReference is still unbounded in happy times",
      },
    },
    {
      q: "How does the module system differ from the classpath?",
      a: "JPMS modules declare requires and exports. The module path is reliable configuration: missing deps and illegal access fail fast. The classpath is a flat list of types with split-package chaos.",
      e: "Automatic modules wrap JARs that lack module-info. reflection needs opens. unnamed module is what classpath code lives in. Many apps still run on the classpath; libraries that export a clean module-info help both worlds.",
      visual: {
        title: "Classpath vs module path",
        kind: "compare",
        left: {
          h: "Classpath",
          lines: ["Flat bag of types", "Split packages possible", "Missing deps at runtime", "Illegal access often allowed"],
        },
        right: {
          h: "Module path",
          lines: ["Explicit requires", "Exports are the API", "Fail at startup", "opens for reflection"],
        },
        footer: "Modules encode the graph the classpath only hoped you had",
      },
    },
    {
      q: "What is false sharing and how do you avoid it?",
      a: "False sharing is when unrelated fields used by different threads sit on the same cache line, so writes ping-pong the line across cores even though the program has no data race on a single variable.",
      e: "Symptoms are mysterious scaling collapse. Fixes: @Contended (with the JVM flag), padding, or striping (LongAdder). Do not pack hot independent counters into one object. Profilers that show cache misses help more than guessing.",
      visual: {
        title: "Two counters, one cache line",
        kind: "cycle",
        center: "line",
        items: [
          { h: "Thread A", lines: ["Writes countA"] },
          { h: "Invalidate", lines: ["Line is dirty"] },
          { h: "Thread B", lines: ["Writes countB"] },
          { h: "Bounce", lines: ["Line shuttles"] },
          { h: "Pad / stripe", lines: ["Split the line"] },
        ],
        footer: "No data race, still a performance bug — the hardware cache is the shared state",
      },
    },
    {
      q: "How are lambdas linked with invokedynamic?",
      a: "A lambda capture site is an invokedynamic call. The bootstrap (LambdaMetafactory) spins or binds a call site that implements the functional interface, capturing arguments in a generated class or method handle.",
      e: "That is why lambdas are not anonymous classes: linkage is lazy, serial forms differ (SerializedLambda), and debugging stack frames look different. Non-capturing lambdas can be cached as singletons. Method references are the same machinery.",
      visual: {
        title: "Lambda linkage",
        kind: "steps",
        steps: [
          { h: "invokedynamic", lines: ["At the capture site"] },
          { h: "Bootstrap", lines: ["LambdaMetafactory"] },
          { h: "CallSite", lines: ["Bound implementation"] },
          { h: "Invoke", lines: ["SAM method runs"] },
        ],
        footer: "The first call pays linkage — later calls are a fast CallSite",
      },
    },
    {
      q: "What are production pitfalls with Java serialization?",
      a: "java.io.Serializable is a public constructor-bypass with a hidden binary protocol. It couples on-disk form to private fields, is a gadget-chain security hazard, and interacts badly with records, enums, and evolving class shapes.",
      e: "Prefer JSON/protobuf with explicit versioning. serialVersionUID freezes a brittle contract. Records serialize by components, not arbitrary fields. Never deserialize untrusted bytes. For sessions, even trusted streams need filters (ObjectInputFilter).",
      visual: {
        title: "Why Serializable bites in production",
        kind: "layers",
        layers: [
          { h: "Hidden protocol", lines: ["Private fields become the schema"] },
          { h: "Security", lines: ["Gadget chains on untrusted bytes"] },
          { h: "Evolution", lines: ["UID · records · incompatible changes"] },
          { h: "Prefer", lines: ["Explicit codecs + ObjectInputFilter if you must"] },
        ],
        footer: "If you must deserialize, filter the stream — better yet, do not",
      },
    },
  ],
};
