module.exports = {
  name: "Kotlin",
  description:
    "Kotlin interview questions — null safety, coroutines, sealed types, JVM interop, and variance.",
  match: /^kotlin$/i,
  theme: {
    accent: "#7F52FF",
    hubFill: "#7F52FF",
    hubText: "#ffffff",
    centerFill: "#f3e8ff",
    centerStroke: "#7F52FF",
    label: "Kotlin",
  },
  beginner: [
    {
      q: "What is Kotlin and why use it?",
      a: "Kotlin is a statically typed language that runs on the JVM (and JS/Native). It is concise, null-safe by default, and fully interoperable with Java — which is why Android made it first-class.",
      e: "Interviews want null safety, data classes, coroutines, and Java interop — not “it’s nicer Java.” Mention it is officially supported on Android and used on the server (Ktor, Spring).",
      visual: {
        title: "Where Kotlin helps",
        kind: "hub",
        hub: "Kotlin",
        nodes: [
          { h: "Null safety", lines: ["T vs T?"] },
          { h: "Concise", lines: ["Less boilerplate"] },
          { h: "Java interop", lines: ["Call Java freely"] },
          { h: "Coroutines", lines: ["Structured async"] },
          { h: "Android", lines: ["First-class"] },
          { h: "Multiplatform", lines: ["Share logic"] },
        ],
        footer: "A JVM language with a type system that takes null seriously",
      },
    },
    {
      q: "How does Kotlin null safety work?",
      a: "T cannot hold null. T? can. The compiler forces a null check, safe call, or Elvis before you use a nullable as T.",
      e: "!! force-unwraps and throws NPE — avoid in APIs. Platform types from Java (T!) are the hole in the system; annotate Java or treat them as T?. lateinit is for non-null deferred init, not for nullability.",
      visual: {
        title: "T vs T?",
        kind: "compare",
        left: {
          h: "String",
          lines: ["Never null", "No safe call needed", "NPE is a bug in Kotlin", "Use for required data"],
        },
        right: {
          h: "String?",
          lines: ["String or null", "?. ?: !! let", "Models missing data", "Use at boundaries"],
        },
        footer: "Null is a type — not a surprise at runtime",
      },
    },
    {
      q: "What do ?., ?:, and !! do?",
      a: "?. is a safe call (null in, null out). ?: (Elvis) supplies a default when the left side is null. !! asserts non-null and throws if it is null.",
      e: "Combine ?. with let for a non-null block. Elvis can return or throw (?: throw …). Prefer requireNotNull with a message over silent !! in production.",
      visual: {
        title: "Three ways to handle null",
        kind: "timeline",
        events: [
          { h: "Safe call", lines: ["user?.email"] },
          { h: "Elvis", lines: ["email ?: \"n/a\""] },
          { h: "Force", lines: ["email!!"] },
          { h: "Use", lines: ["A real String"] },
        ],
        footer: "?. and ?: are tools — !! is an assertion you must be able to defend",
      },
    },
    {
      q: "What is the difference between val and var?",
      a: "val is a read-only reference (cannot rebind). var can be reassigned. val does not make the object immutable — a val List can still be mutated if it is a MutableList.",
      e: "Prefer val. Use var only for true reassignment. For immutability of contents, use immutable types (List, data class copies) not just val. const val is a compile-time constant on objects/top-level.",
      visual: {
        title: "Rebind vs mutate",
        kind: "compare",
        left: {
          h: "val",
          lines: ["Cannot rebind", "Object may still mutate", "Default choice", "const val for compile-time"],
        },
        right: {
          h: "var",
          lines: ["Can rebind", "Signals changing identity", "Use sparingly", "Not the same as mutable data"],
        },
        footer: "val locks the name — immutability of the value is a separate design",
      },
    },
    {
      q: "What is a data class?",
      a: "A data class generates equals, hashCode, toString, copy, and componentN from the primary constructor properties. It is for holding data, not for behavior-heavy types.",
      e: "Requirements: at least one val/var in the primary constructor; cannot be open/abstract/inner/sealed in older Kotlin (sealed data is allowed now). copy is shallow. Prefer val properties.",
      visual: {
        title: "Data class extras",
        kind: "code",
        code: {
          file: "User.kt",
          code: [
            "data class User(",
            "  val id: Int,",
            "  val name: String,",
            ")",
            "val u = User(1, \"Ada\")",
            "val v = u.copy(name = \"Al\")",
          ],
          notes: [
            { h: "equals", text: "Structural — based on constructor props" },
            { h: "copy", text: "Named args change one field" },
            { h: "Destructure", text: "val (id, name) = u" },
          ],
        },
        footer: "Use data class for values — not for every Android ViewModel",
      },
    },
    {
      q: "How do Kotlin functions differ from Java methods?",
      a: "Functions can be top-level, have default and named arguments, and live as single-expression bodies. They are still JVM methods under the hood (often in a *Kt class).",
      e: "Default args generate overloads for Java unless @JvmOverloads. Named args are a Kotlin-call-site feature. Extension functions look like methods but compile to statics.",
      visual: {
        title: "Declare then call",
        kind: "steps",
        steps: [
          { h: "Write fun", lines: ["Defaults allowed"] },
          { h: "Named args", lines: ["greet(name = \"Ada\")"] },
          { h: "Expression body", lines: ["= \"hi $name\""] },
          { h: "JVM", lines: ["Static or instance method"] },
        ],
        footer: "Defaults and names are Kotlin — Java sees generated overloads",
      },
    },
    {
      q: "How does when work?",
      a: "when is a switch that can be an expression. It matches values, ranges, types (is), and can be exhaustive for enums and sealed types.",
      e: "As an expression every branch must return a value. else is required unless the compiler proves exhaustiveness. Prefer when over if-else chains for variants.",
      visual: {
        title: "when as an expression",
        kind: "code",
        code: {
          file: "Grade.kt",
          code: [
            "fun label(n: Int) = when {",
            "  n >= 90 -> \"A\"",
            "  n >= 70 -> \"B\"",
            "  else -> \"C\"",
            "}",
          ],
          notes: [
            { h: "Expression", text: "The whole when is a value" },
            { h: "Conditions", text: "Boolean branches need else" },
            { h: "Sealed / enum", text: "Can be exhaustive without else" },
          ],
        },
        footer: "when is the readable replacement for long if/else ladders",
      },
    },
    {
      q: "How do List, Set, and Map work in Kotlin?",
      a: "Kotlin’s collection interfaces are read-only (List, Set, Map). MutableList and friends add mutation. Java interop can still mutate a List if it is a Java ArrayList underneath.",
      e: "Read-only is a Kotlin type-system view, not a runtime freeze. listOf vs mutableListOf. Prefer immutable at API boundaries. Sequence is lazy; Iterable is eager.",
      visual: {
        title: "Collection map",
        kind: "hub",
        hub: "Collections",
        nodes: [
          { h: "List", lines: ["Ordered read-only"] },
          { h: "MutableList", lines: ["Add / set"] },
          { h: "Set", lines: ["Unique elements"] },
          { h: "Map", lines: ["Key → value"] },
          { h: "Sequence", lines: ["Lazy chain"] },
          { h: "Java", lines: ["May still mutate"] },
        ],
        footer: "Kotlin List is a contract — not always an immutable object",
      },
    },
    {
      q: "What is a smart cast?",
      a: "After a null or type check, the compiler treats the variable as the narrowed type in that scope (if it cannot have been changed).",
      e: "Works for vals and some vars that are not open/custom getters. For properties that might change, use a local val. is checks smart-cast to the subtype. Contracts can teach the compiler extra smart casts.",
      visual: {
        title: "Check then use",
        kind: "steps",
        steps: [
          { h: "Wide type", lines: ["Any? or a supertype"] },
          { h: "Check", lines: ["if (x is String)"] },
          { h: "Smart cast", lines: ["x is String here"] },
          { h: "Use", lines: ["x.length"] },
        ],
        footer: "Smart casts need a stable value — locals beat open properties",
      },
    },
    {
      q: "What is an object and a companion object?",
      a: "object declares a singleton (thread-safe lazy init). companion object is a named singleton tied to a class, holding “static” members in Kotlin’s model.",
      e: "There are no Java statics in Kotlin syntax. @JvmStatic emits real statics for Java callers. companion can implement interfaces. object expressions are anonymous singletons.",
      visual: {
        title: "Singleton layers",
        kind: "layers",
        layers: [
          { h: "object Foo", lines: ["One instance, named type"] },
          { h: "companion object", lines: ["Members on the class name"] },
          { h: "object expression", lines: ["Anonymous, one-off"] },
          { h: "@JvmStatic", lines: ["Real static for Java"] },
        ],
        footer: "companion is Kotlin’s static — object is a first-class singleton",
      },
    },
    {
      q: "What is an extension function?",
      a: "An extension looks like a method on a type but is a static function with a receiver. You call \"hi\".firstWord() after fun String.firstWord().",
      e: "Resolved statically — not virtual. Cannot override a real member; members always win. Nullable receivers (fun String?.orEmpty()) are allowed. Java sees a static method with the receiver as the first arg.",
      visual: {
        title: "Receiver then body",
        kind: "timeline",
        events: [
          { h: "Declare", lines: ["fun String.foo()"] },
          { h: "Import", lines: ["Same as a function"] },
          { h: "Call", lines: ["s.foo()"] },
          { h: "Compile", lines: ["static foo(s)"] },
        ],
        footer: "Extensions do not actually modify the class",
      },
    },
    {
      q: "How do string templates work?",
      a: "Inside a string, $name interpolates a variable and ${expr} interpolates an expression. Raw strings use triple quotes and still support templates.",
      e: "Prefer templates over concatenation. Escape $ with \${'$'} or \$. Build complex JSON with trimIndent on raw strings. Templates are compile-time sugar for concatenation / StringBuilder.",
      visual: {
        title: "Build a string",
        kind: "layers",
        layers: [
          { h: "Literal", lines: ["\"Hello\""] },
          { h: "$name", lines: ["Simple identifier"] },
          { h: "${expr}", lines: ["Any expression"] },
          { h: "\"\"\" raw \"\"\"", lines: ["Multiline, fewer escapes"] },
        ],
        footer: "Templates are the idiomatic way to format strings",
      },
    },
    {
      q: "How do let and Elvis work together for nulls?",
      a: "x?.let { } runs the block only when x is non-null, with it as the non-null value. Elvis (?:) handles the null branch: x?.let { … } ?: default.",
      e: "Scope functions are easy to overuse. let is for null + transform; also for side effects; apply for configuring an object. Don’t nest five lets — use a local val.",
      visual: {
        title: "Null path around a value",
        kind: "cycle",
        center: "T?",
        items: [
          { h: "null", lines: ["Skip let"] },
          { h: "Elvis", lines: ["Default / return"] },
          { h: "non-null", lines: ["Enter let"] },
          { h: "it: T", lines: ["Use safely"] },
        ],
        footer: "?.let is a null check with a new scope — not mandatory style",
      },
    },
    {
      q: "What are Kotlin visibility modifiers?",
      a: "public (default), internal (same module), protected (subclasses; not for top-level), private (file or class). internal is a Kotlin module, not a Java package.",
      e: "internal compiles to public on the JVM with a name mangling hint — it is not JVM-enforced. Java can still call it. private on top-level is file-private. Interviews care about internal vs package-private.",
      visual: {
        title: "Who can see the declaration",
        kind: "cycle",
        center: "visibility",
        items: [
          { h: "public", lines: ["Everywhere"] },
          { h: "internal", lines: ["This module"] },
          { h: "protected", lines: ["Subclasses"] },
          { h: "private", lines: ["File or class"] },
        ],
        footer: "internal is a Kotlin module boundary — the JVM still sees public",
      },
    },
    {
      q: "How does type inference work in Kotlin?",
      a: "The compiler infers types for locals, lambdas, and generics from context. You still annotate function return types on public APIs when they are not obvious.",
      e: "Local vals almost always infer. Explicit types help at module boundaries and when inference explodes. Unused variables still need a type if there is no initializer. Java SAM conversions also feed inference.",
      visual: {
        title: "Infer locally",
        kind: "steps",
        steps: [
          { h: "Write value", lines: ["val n = 3"] },
          { h: "Infer", lines: ["n is Int"] },
          { h: "Lambda", lines: ["From the expected type"] },
          { h: "Annotate APIs", lines: ["fun f(): User"] },
        ],
        footer: "Inference is a convenience — public types are a contract",
      },
    },
  ],
  intermediate: [
    {
      q: "What are coroutines?",
      a: "Coroutines are Kotlin’s lightweight concurrency: suspend functions can pause without blocking a thread. A CoroutineScope owns their lifecycle (structured concurrency).",
      e: "launch returns a Job; async returns a Deferred. Dispatchers.Main/IO/Default pick threads. Coroutines are not threads — thousands can share a pool. Cancellation is cooperative.",
      visual: {
        title: "From scope to work",
        kind: "steps",
        steps: [
          { h: "Scope", lines: ["lifecycle owner"] },
          { h: "launch / async", lines: ["Start a coroutine"] },
          { h: "suspend", lines: ["Pause without block"] },
          { h: "Resume", lines: ["Same or other thread"] },
        ],
        footer: "A coroutine is a task — a dispatcher supplies threads",
      },
    },
    {
      q: "What does the suspend modifier mean?",
      a: "suspend marks a function that may pause and can only be called from another suspend function or a coroutine builder. The compiler turns it into a state machine with a Continuation.",
      e: "suspend does not mean “runs in the background” — you still choose a dispatcher. Blocking inside suspend (Thread.sleep) starves the pool; use delay. Java callers need adapters or runBlocking (tests only).",
      visual: {
        title: "Suspend then resume",
        kind: "timeline",
        events: [
          { h: "Call suspend", lines: ["From a coroutine"] },
          { h: "Pause", lines: ["Save continuation"] },
          { h: "Work elsewhere", lines: ["IO / delay"] },
          { h: "Resume", lines: ["Continue the state machine"] },
        ],
        footer: "suspend is a calling convention — not a thread switch by itself",
      },
    },
    {
      q: "What is a sealed class (or sealed interface)?",
      a: "Sealed types restrict subclasses to a known set (same module / package rules). when on a sealed type can be exhaustive without else.",
      e: "This is Kotlin’s algebraic data type. Prefer sealed over enums when cases carry different payloads (data class children). Sealed interfaces allow multiple inheritance of the hierarchy.",
      visual: {
        title: "Closed variants",
        kind: "compare",
        left: {
          h: "enum class",
          lines: ["Fixed constants", "Same shape each case", "Great for flags", "Cannot add fields per case"],
        },
        right: {
          h: "sealed class",
          lines: ["Known subtypes", "Different payloads", "Exhaustive when", "Domain results / UI state"],
        },
        footer: "Sealed = compiler-known family — the when never goes stale silently",
      },
    },
    {
      q: "How do extension functions dispatch?",
      a: "Extensions are statically dispatched: the compile-time receiver type picks the function, not the runtime class. You cannot override an extension in a subclass and expect virtual calls.",
      e: "Member functions always win over extensions with the same JVM signature. This is why toString() as an extension is never called. Use interfaces + members when you need polymorphism.",
      visual: {
        title: "Static receiver",
        kind: "code",
        code: {
          file: "Ext.kt",
          code: [
            "open class A",
            "class B : A()",
            "fun A.tag() = \"A\"",
            "fun B.tag() = \"B\"",
            "val a: A = B()",
            "a.tag() // \"A\" — static",
          ],
          notes: [
            { h: "Compile type", text: "a is A, so A.tag is chosen" },
            { h: "Not virtual", text: "Runtime B does not matter" },
            { h: "Members win", text: "Real methods override extensions" },
          ],
        },
        footer: "Extensions are sugar for static functions with a receiver",
      },
    },
    {
      q: "What does inline do?",
      a: "inline copies the function body (and lambdas) into the call site. That removes lambda allocations and enables non-local returns and reified type parameters.",
      e: "Cost: bytecode growth. Use on small higher-order helpers (lock, measure). noinline / crossinline control lambda inlining. Do not inline large functions. reified only works on inline.",
      visual: {
        title: "Inline tradeoffs",
        kind: "layers",
        layers: [
          { h: "Call site", lines: ["Body copied here"] },
          { h: "No lambda object", lines: ["Unless noinline"] },
          { h: "reified T", lines: ["T::class is available"] },
          { h: "Code size", lines: ["Too much inline hurts"] },
        ],
        footer: "Inline is for tiny HOFs and reified — not a general speed knob",
      },
    },
    {
      q: "When do you use object vs companion object?",
      a: "Use object for a named singleton or a package-level strategy. Use companion object for factory methods, const val, and @JvmStatic that belong to a class’s named type.",
      e: "A class can have one companion. Named companions (companion object Factory) affect Java’s Companion vs Factory field. object can implement interfaces; companions often hold invoke() factories.",
      visual: {
        title: "Singleton vs class-tied",
        kind: "compare",
        left: {
          h: "object",
          lines: ["Standalone singleton", "Can be a type", "Good for services", "Lazy thread-safe init"],
        },
        right: {
          h: "companion object",
          lines: ["Tied to a class", "User.id style calls", "@JvmStatic for Java", "Factories · constants"],
        },
        footer: "companion is “statics on this class” — object is a type that is one instance",
      },
    },
    {
      q: "What do in and out mean for generics?",
      a: "out T is covariance (producer: you only read T). in T is contravariance (consumer: you only write T). Declaration-site variance is Kotlin’s default spelling; Java uses ? extends / ? super at use sites.",
      e: "List is List<out E> in the stdlib — you can pass List<String> where List<Any> is expected for reading. MutableList is invariant. The compiler rejects out T in an in-position (a parameter of type T).",
      visual: {
        title: "Producer vs consumer",
        kind: "hub",
        hub: "variance",
        nodes: [
          { h: "out T", lines: ["Producer"] },
          { h: "in T", lines: ["Consumer"] },
          { h: "invariant", lines: ["MutableList"] },
          { h: "List<out E>", lines: ["Read-only"] },
          { h: "use-site", lines: ["List<out T>"] },
          { h: "Java", lines: ["? extends / super"] },
        ],
        footer: "out = extends — in = super — same PECS rule as Java",
      },
    },
    {
      q: "What is Flow?",
      a: "Flow is a cold asynchronous stream: a builder emits values with emit, and collectors receive them with collect. It is designed for coroutines (suspend in / suspend out).",
      e: "Cold means the producer runs per collector (unless you shareIn/stateIn). Backpressure is cooperative via suspend. Distinct from LiveData and from Rx. StateFlow/SharedFlow are hot.",
      visual: {
        title: "Emit then collect",
        kind: "cycle",
        center: "Flow",
        items: [
          { h: "flow { }", lines: ["Builder"] },
          { h: "emit", lines: ["Suspend send"] },
          { h: "operators", lines: ["map / filter"] },
          { h: "collect", lines: ["Suspend receive"] },
          { h: "cancel", lines: ["Stops upstream"] },
        ],
        footer: "Cold by default — nothing runs until collect",
      },
    },
    {
      q: "What are scope functions (let, also, apply, run, with)?",
      a: "They execute a block with an object as it or this and return either the object or the block result. They are stdlib inlines, not language keywords.",
      e: "apply/also return the receiver (config + side effect). let/run/with return the lambda result (transform). Overusing them hurts readability — a good interview answer names when not to use them.",
      visual: {
        title: "Which scope function?",
        kind: "hub",
        hub: "scope",
        nodes: [
          { h: "let", lines: ["it → result"] },
          { h: "also", lines: ["it → receiver"] },
          { h: "apply", lines: ["this → receiver"] },
          { h: "run", lines: ["this → result"] },
          { h: "with", lines: ["this → result"] },
          { h: "Avoid", lines: ["Nested pyramids"] },
        ],
        footer: "Pick by receiver (it/this) and return (object vs result)",
      },
    },
    {
      q: "How does Kotlin talk to Java (and vice versa)?",
      a: "Kotlin compiles to JVM bytecode and can call Java directly. Java sees Kotlin properties as getters/setters, objects as INSTANCE/Companion, and needs annotations for nicer interop.",
      e: "Know @JvmStatic, @JvmOverloads, @JvmField, @JvmName, throws via @Throws. Platform types (String!) come from unannotated Java. Avoid exposing suspend and Flow to raw Java without adapters.",
      visual: {
        title: "Interop annotations",
        kind: "code",
        code: {
          file: "Api.kt",
          code: [
            "class Api {",
            "  companion object {",
            "    @JvmStatic fun of(): Api =",
            "      Api()",
            "  }",
            "  @JvmOverloads",
            "  fun f(x: Int = 0) {}",
            "}",
          ],
          notes: [
            { h: "@JvmStatic", text: "Real static Api.of() for Java" },
            { h: "@JvmOverloads", text: "Extra overloads for defaults" },
            { h: "Platform T!", text: "Java nulls are not in the type" },
          ],
        },
        footer: "Interop is excellent — annotations make the Java side feel native",
      },
    },
    {
      q: "What are delegated properties?",
      a: "by hands get/set to another object: lazy, observable, a Map, or a custom ReadOnlyProperty. The compiler generates the accessor calls.",
      e: "lazy is synchronized by default (can be LazyThreadSafetyMode.NONE). lateinit is not a delegate — it is a language feature for var. Don’t use lazy for cheap vals; it allocates.",
      visual: {
        title: "Property by a delegate",
        kind: "layers",
        layers: [
          { h: "var x by d", lines: ["Syntax"] },
          { h: "getValue / setValue", lines: ["Operator convention"] },
          { h: "lazy { }", lines: ["Init on first read"] },
          { h: "observable", lines: ["Hook after set"] },
        ],
        footer: "Delegates are objects — lazy is the one you must know cold",
      },
    },
    {
      q: "When do you use Sequence instead of Iterable?",
      a: "Sequence is lazy: each terminal operation pulls through the chain. Iterable (List) is eager: map builds a full list before filter runs.",
      e: "Use Sequence for large or infinite pipelines. For small lists, eager is simpler and often faster (no iterator objects). asSequence() converts. Java Stream is a cousin; Sequence is Kotlin-native.",
      visual: {
        title: "Eager list vs lazy sequence",
        kind: "timeline",
        events: [
          { h: "Source", lines: ["list or generate"] },
          { h: "map / filter", lines: ["Lazy on Sequence"] },
          { h: "Terminal", lines: ["toList / first"] },
          { h: "Work runs", lines: ["Only as needed"] },
        ],
        footer: "Sequence shines on long chains — not on five-element lists",
      },
    },
    {
      q: "How does Flow differ from Channel?",
      a: "Flow is typically a cold stream with a single collector and backpressure via suspend. Channel is a hot rendezvous/queue: senders and receivers are decoupled, and values can be buffered or dropped.",
      e: "Prefer Flow for data streams (DB, network). Channels are low-level (actor mailboxes, fan-in). callbackFlow bridges callbacks. Closing a Channel vs cancelling a Flow are different APIs.",
      visual: {
        title: "Stream vs queue",
        kind: "cycle",
        center: "async data",
        items: [
          { h: "Flow", lines: ["Cold stream"] },
          { h: "collect", lines: ["Pull"] },
          { h: "Channel", lines: ["Hot buffer"] },
          { h: "send / receive", lines: ["Rendezvous"] },
          { h: "Choose Flow", lines: ["Most app code"] },
        ],
        footer: "Flow for streams — Channel when you need a concurrent queue",
      },
    },
    {
      q: "What are reified type parameters?",
      a: "On an inline function, reified T keeps the type argument at the call site so you can write T::class, is T, and type-safe Gson/JSON helpers that Java erasure would forbid.",
      e: "Only inline + reified. You still cannot reify a type the caller erased. Java cannot call reified functions easily. This is the standard answer to “how do I get T.class in Kotlin?”",
      visual: {
        title: "Keep T at the call site",
        kind: "code",
        code: {
          file: "Reified.kt",
          code: [
            "inline fun <reified T>",
            "  name(): String =",
            "    T::class.simpleName ?: \"?\"",
            "name<Int>() // \"Int\"",
          ],
          notes: [
            { h: "inline", text: "Body copied so T is known" },
            { h: "reified", text: "T is not erased here" },
            { h: "T::class", text: "Illegal on ordinary generics" },
          ],
        },
        footer: "reified is inline’s superpower — not a JVM feature",
      },
    },
    {
      q: "How do higher-order functions work on the JVM?",
      a: "A lambda is an object implementing a FunctionN interface unless the callee is inline. Function types are (A) -> B. suspend lambdas are a different type (suspend (A) -> B).",
      e: "SAM conversions let you pass lambdas to Java interfaces. Allocation of lambdas in hot loops is why inline exists. Callable references (::foo) are also function objects.",
      visual: {
        title: "Lambda to bytecode",
        kind: "steps",
        steps: [
          { h: "Write { x -> }", lines: ["Function type"] },
          { h: "If inline", lines: ["No object"] },
          { h: "Else", lines: ["FunctionN instance"] },
          { h: "Invoke", lines: ["invoke() on JVM"] },
        ],
        footer: "Lambdas are objects unless inlined — measure hot paths",
      },
    },
  ],
  expert: [
    {
      q: "How does structured concurrency cancel work?",
      a: "A CoroutineScope’s Job is a tree. Cancelling a parent cancels children. Exceptions in children cancel the parent (unless SupervisorJob). Cancellation is cooperative via suspend points.",
      e: "withContext, coroutineScope, and supervisorScope create nested scopes. A failed async in coroutineScope cancels siblings. Never use GlobalScope in apps. ensureActive() in CPU loops.",
      visual: {
        title: "Job tree",
        kind: "cycle",
        center: "Job",
        items: [
          { h: "Parent", lines: ["Scope job"] },
          { h: "Children", lines: ["launch / async"] },
          { h: "Cancel parent", lines: ["Cascade down"] },
          { h: "Child fails", lines: ["Cancel siblings"] },
          { h: "Supervisor", lines: ["Isolate failures"] },
        ],
        footer: "If it is not a child, it will outlive you — that is a leak",
      },
    },
    {
      q: "How do Flow operators handle backpressure?",
      a: "emit is suspend, so a slow collector suspends the producer. That is built-in backpressure. buffer / conflate / collectLatest change the strategy (queue, drop, restart).",
      e: "flowOn moves upstream to another dispatcher and inserts buffering. catch handles upstream exceptions. Interviews want: cold Flow + suspend = backpressure; SharedFlow needs extra replay/buffer config.",
      visual: {
        title: "Producer meets collector",
        kind: "layers",
        layers: [
          { h: "emit", lines: ["Suspends if collector is slow"] },
          { h: "buffer", lines: ["Decouple with a queue"] },
          { h: "conflate", lines: ["Keep only latest"] },
          { h: "collectLatest", lines: ["Cancel previous work"] },
        ],
        footer: "Default Flow is rendezvous — operators opt into buffering",
      },
    },
    {
      q: "What is CoroutineContext and how do dispatchers fit?",
      a: "CoroutineContext is a persistent key-value set (Job, Dispatcher, CoroutineName, exception handler). Elements combine with +. withContext swaps elements for a block.",
      e: "Dispatchers.Default is CPU; IO is a larger pool; Main is UI; Unconfined is a footgun. A dispatcher is just one context element. Nested withContext restores the outer context on exit.",
      visual: {
        title: "Context elements",
        kind: "hub",
        hub: "Context",
        nodes: [
          { h: "Job", lines: ["Lifecycle"] },
          { h: "Dispatcher", lines: ["Which threads"] },
          { h: "Name", lines: ["Debug"] },
          { h: "Handler", lines: ["Uncaught"] },
          { h: "withContext", lines: ["Swap then restore"] },
          { h: "+", lines: ["Combine"] },
        ],
        footer: "The context is the coroutine’s environment — not a hidden thread",
      },
    },
    {
      q: "How do expect and actual work in Kotlin Multiplatform?",
      a: "expect declares an API in common code. Each platform provides actual implementations. The compiler checks that actuals match the expect signature.",
      e: "Keep expect surfaces small (clocks, HTTP, storage). Prefer common libraries that already abstract platforms. This is the light KMP interview answer — not a full Android/iOS architecture lecture.",
      visual: {
        title: "Common API, platform body",
        kind: "compare",
        left: {
          h: "expect (common)",
          lines: ["Signature only", "Shared callers", "No JVM/Obj-C here", "Keep it tiny"],
        },
        right: {
          h: "actual (platform)",
          lines: ["Real implementation", "Android / iOS / JS", "Must match expect", "Can use native APIs"],
        },
        footer: "expect/actual is the FFI boundary of KMP — not a DI framework",
      },
    },
    {
      q: "What is a value class (inline class)?",
      a: "A @JvmInline value class wraps a single underlying value with no extra allocation at most call sites. It is a nominal type (UserId vs Int) that erases to the carrier on the JVM when possible.",
      e: "Boxing still happens when used as a generic, nullable, or interface. Good for IDs and units. Not a substitute for data class with many fields. Experimental earlier; stable as value class.",
      visual: {
        title: "Nominal wrapper",
        kind: "code",
        code: {
          file: "UserId.kt",
          code: [
            "@JvmInline",
            "value class UserId(val v: Int)",
            "fun find(id: UserId) {}",
            "find(UserId(3))",
          ],
          notes: [
            { h: "Nominal", text: "Cannot pass a raw Int by accident" },
            { h: "Erase", text: "Often just an Int on the JVM" },
            { h: "Box", text: "Generics / nullable still allocate" },
          ],
        },
        footer: "Value classes are brands that the JVM can often erase",
      },
    },
    {
      q: "How does contravariance (in) show up in real APIs?",
      a: "A Comparator<in T> can compare T and its subtypes: Comparator<Number> can be used as Comparator<Int> because it only consumes values. Function1 is contravariant in its input and covariant in its output.",
      e: "This is the same as Java’s Comparator<? super T>. Interviewers may ask why MutableList<in T> is rare (you can add T but only get Any?). Declaration-site in is the clean spelling.",
      visual: {
        title: "Who can substitute",
        kind: "compare",
        left: {
          h: "out (covariant)",
          lines: ["Producer of T", "List<String> as List<Any>", "Read only T", "Return positions"],
        },
        right: {
          h: "in (contravariant)",
          lines: ["Consumer of T", "Cmp<Any> as Cmp<String>", "Write only T", "Parameter positions"],
        },
        footer: "If you only read T, use out — if you only write T, use in",
      },
    },
    {
      q: "How is a suspend function compiled (CPS)?",
      a: "The compiler rewrites suspend functions into a state machine that takes a Continuation. Each suspend point is a state; resume jumps to the next. This is continuation-passing style, not a thread per call.",
      e: "You can see it with Tools → Kotlin bytecode. Blocking the continuation’s thread is still blocking. Intrinsics (delay, withContext) call suspendCoroutineUninterceptedOrReturn. This is the expert “how do coroutines work” answer.",
      visual: {
        title: "State machine resume",
        kind: "steps",
        steps: [
          { h: "Call", lines: ["pass Continuation"] },
          { h: "State N", lines: ["Run until suspend"] },
          { h: "Park", lines: ["Return COROUTINE_SUSPENDED"] },
          { h: "Resume", lines: ["Jump to state N+1"] },
        ],
        footer: "No magic thread — a label, a continuation, and a dispatcher",
      },
    },
    {
      q: "When do you use StateFlow vs SharedFlow vs Flow?",
      a: "Flow is cold. StateFlow is a hot state holder with a current value and conflation. SharedFlow is a hot multicast stream with configurable replay and buffers, no required current value.",
      e: "UI state → StateFlow. Events (toasts, nav) → SharedFlow (replay=0). Maps/transforms of sources → cold Flow then stateIn/shareIn at the boundary. Don’t expose MutableStateFlow from a public API.",
      visual: {
        title: "Pick the stream type",
        kind: "layers",
        layers: [
          { h: "Flow", lines: ["Cold, per collector"] },
          { h: "StateFlow", lines: ["Hot state, always a value"] },
          { h: "SharedFlow", lines: ["Hot events, optional replay"] },
          { h: "stateIn / shareIn", lines: ["Make a cold Flow hot"] },
        ],
        footer: "Cold until you need many collectors or a current snapshot",
      },
    },
    {
      q: "How do you share logic with Kotlin Multiplatform without drowning in expect?",
      a: "Put domain and networking-with-Ktor in commonMain. Use expect/actual only for tiny platform seams. UI stays native or uses Compose Multiplatform if the team is ready.",
      e: "Expert-light KMP: expect is not an architecture. Watch Gradle source sets, SKIE/Obj-C export limits, and expecting everything (clocks, UUID) from well-known libs instead of writing actuals.",
      visual: {
        title: "Share the middle",
        kind: "hub",
        hub: "KMP",
        nodes: [
          { h: "commonMain", lines: ["Domain · use cases"] },
          { h: "androidMain", lines: ["actuals · UI"] },
          { h: "iosMain", lines: ["actuals · UI"] },
          { h: "expect tiny", lines: ["Seams only"] },
          { h: "Ktor / SQLDelight", lines: ["Common libs"] },
          { h: "Avoid", lines: ["expect everything"] },
        ],
        footer: "Share business logic — do not clone UIKit into expect",
      },
    },
    {
      q: "How does coroutine cancellation actually stop work?",
      a: "Cancellation sets a flag on the Job. At the next suspend point (or ensureActive), a CancellationException is thrown. CPU-bound loops must check isActive. Finally blocks still run.",
      e: "Catching CancellationException and swallowing it is a bug — rethrow. NonCancellable for cleanup that must complete. IO cancellation depends on the library (OkHttp cancel, etc.).",
      visual: {
        title: "Cooperative stop",
        kind: "timeline",
        events: [
          { h: "cancel()", lines: ["Flag the Job"] },
          { h: "Suspend point", lines: ["Check flag"] },
          { h: "Throw CE", lines: ["Unwind"] },
          { h: "finally", lines: ["Cleanup"] },
        ],
        footer: "No suspend point, no cancel — that is why delay beats sleep",
      },
    },
    {
      q: "How do type-safe builders / DSLs work?",
      a: "A DSL uses lambdas with receiver (Html.() -> Unit), @DslMarker to stop leaking outer this, and sometimes @BuilderInference. The result is nested, typed HTML/Gradle-like code.",
      e: "This is how kotlinx.html and Compose’s compiler plugin-adjacent APIs feel. @DslMarker prevents apply-from-outer-scope bugs. It is still ordinary Kotlin — not a new runtime.",
      visual: {
        title: "Lambda with receiver",
        kind: "code",
        code: {
          file: "Dsl.kt",
          code: [
            "@DslMarker",
            "annotation class HtmlDsl",
            "@HtmlDsl",
            "class Div {",
            "  fun p(t: String) {}",
            "}",
            "fun div(b: Div.() -> Unit) =",
            "  Div().apply(b)",
          ],
          notes: [
            { h: "Receiver", text: "Inside b, this is Div" },
            { h: "@DslMarker", text: "Stops calling outer builders by accident" },
            { h: "apply", text: "Returns the configured object" },
          ],
        },
        footer: "DSLs are receivers + markers — the compiler does the rest",
      },
    },
    {
      q: "What is the Nothing type for?",
      a: "Nothing is the bottom type: a function that never returns (throw, infinite loop) has type Nothing. It is a subtype of every type, so it fits any expected result.",
      e: "TODO() returns Nothing. EmptyList is List<Nothing> which is a List<T> for all T. Unit is “returns nothing useful”; Nothing is “does not return.” Confusing them is a common expert trap.",
      visual: {
        title: "Bottom type",
        kind: "cycle",
        center: "Nothing",
        items: [
          { h: "throw", lines: ["Never returns"] },
          { h: "TODO()", lines: ["Nothing"] },
          { h: "Subtype of all", lines: ["Fits any T"] },
          { h: "Empty list", lines: ["List<Nothing>"] },
          { h: "Not Unit", lines: ["Unit does return"] },
        ],
        footer: "Nothing is empty — Unit is a singleton value",
      },
    },
    {
      q: "What are Kotlin contracts?",
      a: "contracts { } tell the compiler effects a function has: returns implies a smart cast, callsInPlace for inline lambdas. They are experimental-to-stable in stages and mainly for library authors.",
      e: "require(x is String) already smart-casts via a built-in contract. Custom contracts need opt-in. Miswritten contracts can lie to the type checker — treat them like unsafe casts for the analyzer.",
      visual: {
        title: "Teach the smart-cast engine",
        kind: "steps",
        steps: [
          { h: "Call helper", lines: ["requireNotNull(x)"] },
          { h: "Contract", lines: ["returns() implies x != null"] },
          { h: "After call", lines: ["x is T"] },
          { h: "Use", lines: ["No extra !!"] },
        ],
        footer: "Contracts are compiler facts — they do not run at runtime",
      },
    },
    {
      q: "How do generics erase at the Kotlin/JVM boundary?",
      a: "JVM generics erase to raw types. Kotlin adds reified (inline) and nothing else. A List<String> is a List at runtime. Java wildcards map to out/in projections.",
      e: "You cannot overload fun f(a: List<Int>) and f(a: List<String>). Array is reified on the JVM (Array<Int> vs IntArray — know both). @JvmSuppressWildcards / @JvmWildcard control generated signatures.",
      visual: {
        title: "What Java sees",
        kind: "timeline",
        events: [
          { h: "Kotlin List<User>", lines: ["Typed in source"] },
          { h: "Erase", lines: ["List at runtime"] },
          { h: "Wildcards", lines: ["? extends in Java sigs"] },
          { h: "reified inline", lines: ["T kept at call site"] },
        ],
        footer: "The JVM still erases — reified is a compiler trick",
      },
    },
    {
      q: "How should coroutine exceptions be handled?",
      a: "Exceptions in launch go to the parent Job and CoroutineExceptionHandler (if the context has one). Exceptions in async are held on the Deferred until await. SupervisorJob stops sibling cancellation.",
      e: "CEH does not run for async until await, and not for children that already propagate. Don’t use CEH as business logic — use Result / sealed types. runCatching swallows CancellationException unless you rethrow.",
      visual: {
        title: "Where the exception goes",
        kind: "hub",
        hub: "failure",
        nodes: [
          { h: "launch", lines: ["To parent / CEH"] },
          { h: "async", lines: ["Until await"] },
          { h: "Supervisor", lines: ["Siblings live"] },
          { h: "CEH", lines: ["Last resort log"] },
          { h: "Cancellation", lines: ["Rethrow CE"] },
          { h: "Sealed / Result", lines: ["Domain errors"] },
        ],
        footer: "Domain errors are values — crashes belong to the Job tree",
      },
    },
  ],
};
