module.exports = {
  name: "Lua",
  description:
    "Lua interview questions — tables, metatables, coroutines, modules, and the C API.",
  match: /^lua$/i,
  theme: {
    accent: "#000080",
    hubFill: "#000080",
    hubText: "#ffffff",
    centerFill: "#e0e7ff",
    centerStroke: "#000080",
    label: "Lua",
  },
  beginner: [
    {
      q: "What is Lua and where does it run?",
      a: "Lua is a small, embeddable dynamic language. Hosts (games, Nginx, Redis, Wireshark, Neovim) ship the interpreter and extend it with C. It is not a batteries-included app language.",
      e: "The point is a tiny VM plus a C API. LuaJIT is a separate, faster implementation. Interviews want ‘embeddable scripting’ not ‘another Python’.",
      visual: {
        title: "Where Lua is embedded",
        kind: "hub",
        hub: "Lua",
        nodes: [
          { h: "Games", lines: ["Love · WoW"] },
          { h: "Nginx", lines: ["OpenResty"] },
          { h: "Editors", lines: ["Neovim"] },
          { h: "Redis", lines: ["EVAL scripts"] },
          { h: "IoT", lines: ["Tiny RAM"] },
          { h: "C hosts", lines: ["Your app"] },
        ],
        footer: "A guest language — the host owns the world",
      },
    },
    {
      q: "Why is the table Lua’s only data structure?",
      a: "A table is both an array part (integer keys 1..n) and a hash part (any other key). Arrays, maps, objects, modules, and even classes are tables with conventions.",
      e: "There is no separate list or dict type. Sequences should be dense from 1. Holes (# and ipairs) are the classic footgun.",
      visual: {
        title: "One type, two parts",
        kind: "compare",
        left: {
          h: "Array part",
          lines: ["Keys 1, 2, 3…", "ipairs / #", "Dense sequences", "Fast contiguous"],
        },
        right: {
          h: "Hash part",
          lines: ["Any key type", "pairs()", "Records / maps", "Methods via string keys"],
        },
        footer: "t.x is t['x'] — syntax, not a second type",
      },
    },
    {
      q: "How do you create and read a table?",
      a: "t = {10, 20, name = 'Ada'} mixes a sequence and a record. t[1] is 10; t.name is 'Ada'. Length operator #t is defined for sequences.",
      e: "Keys can be any value except nil. Storing nil deletes a key. Don’t use 0 as the first index — Lua sequences start at 1.",
      visual: {
        title: "A mixed table",
        kind: "code",
        code: {
          file: "table.lua",
          code: [
            "t = {10, 20, name = 'Ada'}",
            "print(t[1])     -- 10",
            "print(t.name)   -- Ada",
            "print(#t)       -- 2",
          ],
          notes: [
            { h: "Sequence", text: "Integer keys from 1" },
            { h: "Record", text: "name is a string key" },
            { h: "#", text: "Length of the sequence part" },
          ],
        },
        footer: "t.name and t['name'] are the same lookup",
      },
    },
    {
      q: "Why is Lua 1-based indexing such a big deal?",
      a: "Sequences start at 1. t[0] is just a hash key, not the first element. for i = 1, #t do is the idiomatic loop; ipairs also starts at 1.",
      e: "C API and host arrays are often 0-based — off-by-one at the boundary is the #1 interop bug. Don’t ‘fix’ Lua by using 0; you break # and ipairs.",
      visual: {
        title: "Index from one",
        kind: "steps",
        steps: [
          { h: "Create", lines: ["t = {'a', 'b'}"] },
          { h: "First", lines: ["t[1] == 'a'"] },
          { h: "t[0]", lines: ["Not the first item"] },
          { h: "C boundary", lines: ["Convert 0 ↔ 1"] },
        ],
        footer: "# and ipairs assume a 1-based dense sequence",
      },
    },
    {
      q: "What is the difference between pairs and ipairs?",
      a: "ipairs iterates the sequence 1, 2, … until a nil hole. pairs iterates all keys in an unspecified order (array + hash).",
      e: "A hole (nil in the middle) stops ipairs early; pairs still sees later integer keys. For a real list, keep it dense or store an explicit n.",
      visual: {
        title: "ipairs vs pairs",
        kind: "compare",
        left: {
          h: "ipairs",
          lines: ["1 .. until nil", "Order is numeric", "Stops at a hole", "Sequences only"],
        },
        right: {
          h: "pairs",
          lines: ["Every key", "Order not defined", "Sees hash keys", "Records and mixed"],
        },
        footer: "Don’t ipairs a map — don’t pairs if you need 1..n",
      },
    },
    {
      q: "What are Lua’s types?",
      a: "nil, boolean, number, string, table, function, userdata, thread (coroutine), and in 5.3+ integer vs float are both number. No separate array type.",
      e: "type(x) returns a string. Numbers were always doubles until 5.3 integers. userdata is C data the Lua GC can still manage.",
      visual: {
        title: "Type map",
        kind: "layers",
        layers: [
          { h: "nil / boolean", lines: ["Absence and flags"] },
          { h: "number / string", lines: ["Values, interned strings"] },
          { h: "table / function", lines: ["The language’s nouns and verbs"] },
          { h: "userdata / thread", lines: ["C data and coroutines"] },
        ],
        footer: "Eight types — tables do the heavy lifting",
      },
    },
    {
      q: "How do functions and multiple returns work?",
      a: "Functions are first-class. They can return multiple values: return a, b. Extra values are discarded; missing ones become nil. A call in list context keeps them.",
      e: "select('#', ...) and table.pack capture varargs. Parentheses force a single result: (f()). That’s why wrapping a call can drop extra returns.",
      visual: {
        title: "Multiple returns",
        kind: "code",
        code: {
          file: "ret.lua",
          code: [
            "function div(a, b)",
            "  return a // b, a % b",
            "end",
            "q, r = div(7, 2)  -- 3, 1",
          ],
          notes: [
            { h: "Two values", text: "Not a tuple object" },
            { h: "Extra", text: "Dropped if you assign one name" },
            { h: "()", text: "Parens keep only the first" },
          ],
        },
        footer: "Returns are a list — not a hidden array",
      },
    },
    {
      q: "How do you load a module with require?",
      a: "require 'mod' searches package.path (Lua) and package.cpath (native), runs the file once, and caches the return value in package.loaded.",
      e: "A module file should return a table of functions. Later require is a cache hit. package.loaded['mod'] = nil forces reload — useful in games, dangerous in prod.",
      visual: {
        title: "require path",
        kind: "timeline",
        events: [
          { h: "require 'x'", lines: ["Look up loaded"] },
          { h: "Search path", lines: ["package.path"] },
          { h: "Run chunk", lines: ["Once"] },
          { h: "Cache", lines: ["package.loaded"] },
        ],
        footer: "Modules return a table — they are not a special type",
      },
    },
    {
      q: "What is _G and why should you avoid globals?",
      a: "_G is the global environment table. An undeclared assignment x = 1 writes _G.x. Locals are compiled to registers and are faster and safer.",
      e: "Use local at the top of a file. In 5.2+ _ENV is the visible environment; _G is usually that table. Strict checkers (luacheck) flag implicit globals.",
      visual: {
        title: "Global environment",
        kind: "cycle",
        center: "_G",
        items: [
          { h: "print", lines: ["A global function"] },
          { h: "require", lines: ["Another global"] },
          { h: "Your x = 1", lines: ["Also _G.x"] },
          { h: "local x", lines: ["Not in _G"] },
          { h: "_ENV", lines: ["Chunk’s env (5.2+)"] },
        ],
        footer: "local by default — globals are a shared table",
      },
    },
    {
      q: "How do you represent an object with a table?",
      a: "Store fields in a table and methods as functions, often with a colon so self is implicit: function T:foo() uses self. Prototypes use a shared metatable.",
      e: "There is no class keyword. Colon vs dot is the interview: t:foo(1) is t.foo(t, 1). Forgetting that is the classic bug.",
      visual: {
        title: "Table as object",
        kind: "hub",
        hub: "object",
        nodes: [
          { h: "Fields", lines: ["t.x = 1"] },
          { h: "Methods", lines: ["function t:f()"] },
          { h: "self", lines: ["Colon passes it"] },
          { h: "Prototype", lines: ["__index table"] },
          { h: "Module", lines: ["Returned table"] },
          { h: "No class", lines: ["Just convention"] },
        ],
        footer: "t:foo() ≡ t.foo(t) — the colon is sugar",
      },
    },
    {
      q: "How do you write a tiny module?",
      a: "Create a local table, put functions on it, return it. Callers local M = require 'mod'. Keep the file’s guts local so they stay private.",
      e: "Don’t pollute _G from a library. package.seeall is obsolete. Cyclic requires can see a partially built table — design for that.",
      visual: {
        title: "module.lua",
        kind: "code",
        code: {
          file: "mod.lua",
          code: [
            "local M = {}",
            "function M.add(a, b)",
            "  return a + b",
            "end",
            "return M",
          ],
          notes: [
            { h: "local M", text: "Nothing leaked to _G" },
            { h: "return", text: "require caches this table" },
            { h: "API", text: "Only what you put on M" },
          ],
        },
        footer: "A module is a table you return once",
      },
    },
    {
      q: "How does a Lua chunk get executed?",
      a: "Source is compiled to bytecode for a stack-based VM, then run. load/loadfile produce a function (the chunk). Errors raise or return nil, err depending on pcall.",
      e: "string.dump / load round-trip bytecode. Hosts often load from memory, not files. JIT (LuaJIT) adds a tracing compiler on top of this model.",
      visual: {
        title: "From text to VM",
        kind: "steps",
        steps: [
          { h: "Source", lines: ["*.lua or string"] },
          { h: "Compile", lines: ["Bytecode chunk"] },
          { h: "Call", lines: ["Chunk is a function"] },
          { h: "VM / JIT", lines: ["Execute"] },
        ],
        footer: "load returns a function — it does not run yet",
      },
    },
    {
      q: "What should you know about strings and numbers?",
      a: "Strings are immutable and interned. .. concatenates (and copies). Numbers are IEEE doubles; 5.3+ also has 64-bit integers with // for floor divide.",
      e: "tonumber/tostring convert. Mixing int and float in 5.3 follows promotion rules. Don’t build huge strings with .. in a loop — table.concat.",
      visual: {
        title: "Values that copy",
        kind: "layers",
        layers: [
          { h: "string", lines: ["Immutable, hashed"] },
          { h: "number", lines: ["Float and/or int"] },
          { h: ".. / //", lines: ["Concat · floor div"] },
          { h: "table.concat", lines: ["Build big strings"] },
        ],
        footer: "Strings never mutate — concatenation allocates",
      },
    },
    {
      q: "How does garbage collection look to a beginner?",
      a: "Lua is garbage collected. When no reference remains, tables, functions, threads, and userdata can be freed. You don’t free() Lua objects.",
      e: "collectgarbage() can step or collect. Hosts care about pause times. userdata may have a __gc finalizer for C resources. Cycles of tables are collected.",
      visual: {
        title: "GC lifetime",
        kind: "timeline",
        events: [
          { h: "Allocate", lines: ["table / userdata"] },
          { h: "Reachable", lines: ["From locals / _G"] },
          { h: "Drop refs", lines: ["local goes out"] },
          { h: "Collect", lines: ["Maybe __gc"] },
        ],
        footer: "C memory still needs __gc or an explicit free API",
      },
    },
    {
      q: "How do you loop over a sequence safely?",
      a: "for i = 1, #t do … end or ipairs(t). Don’t cache #t if the table grows. Avoid for i, v in pairs on a list if order matters.",
      e: "The numeric for evaluates the limit once. table.insert/remove update the array part. A nil hole makes # implementation-defined in some versions — keep lists dense.",
      visual: {
        title: "Walk a sequence",
        kind: "cycle",
        center: "#t",
        items: [
          { h: "Dense 1..n", lines: ["No nil holes"] },
          { h: "ipairs", lines: ["Stops at nil"] },
          { h: "numeric for", lines: ["1 to #t"] },
          { h: "insert", lines: ["Append / shift"] },
          { h: "Hole", lines: ["# becomes tricky"] },
        ],
        footer: "Dense from 1 — that is a Lua ‘array’",
      },
    },
  ],
  intermediate: [
    {
      q: "What is a metatable?",
      a: "A metatable is a table attached with setmetatable that defines fallbacks: __index, __newindex, __add, __tostring, __gc, __call, and more.",
      e: "Only tables and userdata have metatables in PUC Lua. getmetatable reads it. Raw ops (rawget, rawset) skip metamethods — use them to avoid recursion.",
      visual: {
        title: "Metamethod map",
        kind: "hub",
        hub: "metatable",
        nodes: [
          { h: "__index", lines: ["Missing read"] },
          { h: "__newindex", lines: ["Missing write"] },
          { h: "__add", lines: ["Operators"] },
          { h: "__call", lines: ["t() as function"] },
          { h: "__gc", lines: ["Finalizer"] },
          { h: "__tostring", lines: ["print(t)"] },
        ],
        footer: "Metatables are how Lua fakes classes and operators",
      },
    },
    {
      q: "How does __index implement prototypes?",
      a: "__index can be a table (look there next) or a function. Object systems set the instance’s metatable __index to a shared method table.",
      e: "setmetatable(o, { __index = M }) is the usual class. Inheritance is a chain of __index tables. rawget skips the chain — useful in constructors.",
      visual: {
        title: "Prototype lookup",
        kind: "compare",
        left: {
          h: "__index = table",
          lines: ["Look up missing keys", "Shared methods", "Cheap", "Usual classes"],
        },
        right: {
          h: "__index = function",
          lines: ["Compute the value", "Can proxy", "Heavier", "Dynamic APIs"],
        },
        footer: "Chain tables for inheritance — functions for proxies",
      },
    },
    {
      q: "How do you set a simple class with __index?",
      a: "A class is a table of methods. new builds an instance table and setmetatable(inst, { __index = Class }). Colon methods receive the instance as self.",
      e: "Class.__index = Class is the compact idiom so the class table is the prototype. Don’t put per-instance state on the class table.",
      visual: {
        title: "Class idiom",
        kind: "code",
        code: {
          file: "class.lua",
          code: [
            "Dog = {}",
            "Dog.__index = Dog",
            "function Dog:new(n)",
            "  return setmetatable(",
            "    {name = n}, self)",
            "end",
          ],
          notes: [
            { h: "__index", text: "Instance looks at Dog" },
            { h: "self", text: "Colon passes the instance" },
            { h: "setmetatable", text: "Hooks the prototype" },
          ],
        },
        footer: "No class keyword — a table plus a metatable",
      },
    },
    {
      q: "How do coroutines work?",
      a: "coroutine.create(fn) makes a thread. resume runs until yield (or return). yield passes values back to resume; the next resume continues with yield’s result.",
      e: "They are cooperative, not OS threads. A yield across a C call needs a yieldable C API (lua_yieldk). status is suspended/running/dead.",
      visual: {
        title: "resume ↔ yield",
        kind: "steps",
        steps: [
          { h: "create", lines: ["New thread object"] },
          { h: "resume", lines: ["Run until yield"] },
          { h: "yield", lines: ["Hand values back"] },
          { h: "resume again", lines: ["Continue the fn"] },
        ],
        footer: "One OS thread — many Lua threads, cooperatively",
      },
    },
    {
      q: "What is the difference between local and global names?",
      a: "local is lexically scoped and compiled to VM registers. Globals are keys in _ENV/_G and need a table lookup (and can be hooked via metatables).",
      e: "Locals are faster and don’t collide. A missing local silently becomes a global write — luacheck catches that. upvalues are locals captured by nested functions.",
      visual: {
        title: "local vs global",
        kind: "compare",
        left: {
          h: "local",
          lines: ["Register in the VM", "Lexical scope", "Captured as upvalue", "Fast"],
        },
        right: {
          h: "global",
          lines: ["_ENV[name]", "Visible everywhere", "Can be stubbed", "Easy collisions"],
        },
        footer: "If you did not declare local, you used _ENV",
      },
    },
    {
      q: "What is _ENV in Lua 5.2+?",
      a: "_ENV is the table used for global name lookup in a chunk. By default it is _G. You can set a chunk’s environment to sandbox it.",
      e: "In 5.1 it was setfenv. load(chunk, nil, nil, env) sets _ENV. Sandboxes still need to wrap dangerous functions — a shallow env is not a security boundary by itself.",
      visual: {
        title: "Where globals live",
        kind: "layers",
        layers: [
          { h: "Chunk locals", lines: ["Registers"] },
          { h: "_ENV", lines: ["Global name table"] },
          { h: "_G", lines: ["Usual shared env"] },
          { h: "Sandbox env", lines: ["Restricted table"] },
        ],
        footer: "Global x is _ENV.x — change _ENV to sandbox",
      },
    },
    {
      q: "How do you yield values from a coroutine?",
      a: "Inside the coroutine, coroutine.yield(...) returns those values from resume. The next resume(...) arguments become the result of yield.",
      e: "This is how iterators (for x in producer) and game scripting pause. wrap() returns a function that resumes and re-raises errors.",
      visual: {
        title: "Ping-pong values",
        kind: "code",
        code: {
          file: "co.lua",
          code: [
            "co = coroutine.create(function()",
            "  local x = coroutine.yield(1)",
            "  return x + 1",
            "end)",
            "print(coroutine.resume(co))",
          ],
          notes: [
            { h: "yield(1)", text: "resume returns true, 1" },
            { h: "resume args", text: "Become yield’s result" },
            { h: "return", text: "Last resume: dead" },
          ],
        },
        footer: "resume and yield are the two ends of one pipe",
      },
    },
    {
      q: "How does the garbage collector run in modern Lua?",
      a: "Lua 5.4 has a generational GC (plus an incremental mode). Short-lived objects die in the minor cycle; you can tune via collectgarbage pauses.",
      e: "LuaJIT has its own GC (not 5.4 generational). Finalizers (__gc) run later; don’t resurrect objects carelessly. Weak tables let caches drop entries.",
      visual: {
        title: "GC modes",
        kind: "timeline",
        events: [
          { h: "Allocate", lines: ["Young objects"] },
          { h: "Minor", lines: ["Generational 5.4"] },
          { h: "Major", lines: ["Full sweep"] },
          { h: "__gc", lines: ["C cleanup"] },
        ],
        footer: "Tune collectgarbage — don’t call it every frame blindly",
      },
    },
    {
      q: "What are weak tables?",
      a: "A metatable __mode = 'k', 'v', or 'kv' makes keys and/or values weak: if that is the only ref, GC can collect them. Used for caches and object registries.",
      e: "Weak keys require actual objects (tables/userdata), not numbers/strings (interned strings behave specially). Don’t put a cache in a strong table and wonder why RAM grows.",
      visual: {
        title: "Weak refs",
        kind: "cycle",
        center: "__mode",
        items: [
          { h: "'k'", lines: ["Weak keys"] },
          { h: "'v'", lines: ["Weak values"] },
          { h: "'kv'", lines: ["Both weak"] },
          { h: "Cache", lines: ["Auto-evict"] },
          { h: "ephemeron", lines: ["5.2+ key/value"] },
        ],
        footer: "Weak tables are how Lua caches without leaks",
      },
    },
    {
      q: "What is userdata?",
      a: "userdata is a Lua type that holds a C pointer or a blob allocated by the Lua allocator. It is opaque in Lua except via metamethods the host sets.",
      e: "Full userdata is GC-managed memory; light userdata is a raw pointer (not GC’d, no metatable per value in classic Lua). This is the bridge for FILE*, game entities, etc.",
      visual: {
        title: "userdata kinds",
        kind: "hub",
        hub: "userdata",
        nodes: [
          { h: "Full", lines: ["GC-owned blob"] },
          { h: "Light", lines: ["Bare pointer"] },
          { h: "__index", lines: ["Methods from C"] },
          { h: "__gc", lines: ["Free C res"] },
          { h: "type()", lines: ["'userdata'"] },
          { h: "Host", lines: ["Sets the mt"] },
        ],
        footer: "Lua sees a box — C sees the real resource",
      },
    },
    {
      q: "How do you implement __tostring and operators?",
      a: "Set __tostring, __add, __eq, __lt, etc. on the metatable. Binary ops look at the first operand’s metatable, then the second (with some rules).",
      e: "__eq only fires if both values share a metatable (for tables/userdata). Mixing numbers and objects needs explicit functions if metamethods don’t apply.",
      visual: {
        title: "__add on a vector",
        kind: "code",
        code: {
          file: "vec.lua",
          code: [
            "mt = {__add = function(a, b)",
            "  return V(a.x+b.x, a.y+b.y)",
            "end}",
            "function V(x, y)",
            "  return setmetatable(",
            "    {x=x, y=y}, mt) end",
          ],
          notes: [
            { h: "__add", text: "a + b calls this" },
            { h: "Both", text: "Need compatible metatables" },
            { h: "raw", text: "No metamethod on +" },
          ],
        },
        footer: "Operators are metamethods — not syntax for a new type",
      },
    },
    {
      q: "How does package.path resolve modules?",
      a: "package.path is a template list with ? for the module name (dots become directory separators). cpath is for .so/.dll. package.searchers is the list of loaders.",
      e: "You can insert a searcher to load from a zip or a host. module() is deprecated. Versioned dirs and LUA_PATH env vars matter in ops interviews.",
      visual: {
        title: "Find a module",
        kind: "steps",
        steps: [
          { h: "loaded?", lines: ["package.loaded"] },
          { h: "searchers", lines: ["preload · path · cpath"] },
          { h: "path templates", lines: ["?.lua · ?/init.lua"] },
          { h: "run + cache", lines: ["Return value stored"] },
        ],
        footer: "Dots in names become folders on disk",
      },
    },
    {
      q: "How does the Lua C API stack work at a glance?",
      a: "The C API is stack-based: you push values, call lua_pcall, pop results. Indices are 1-based from the bottom or negative from the top.",
      e: "luaL_check* validates. Always pcall untrusted Lua. The stack must be balanced or you corrupt the state — the #1 embedding bug.",
      visual: {
        title: "C API stack",
        kind: "layers",
        layers: [
          { h: "lua_State", lines: ["One VM (or thread)"] },
          { h: "Stack slots", lines: ["Push / pop values"] },
          { h: "pcall", lines: ["Run protected"] },
          { h: "Results", lines: ["Pop into C"] },
        ],
        footer: "If you push, you must pop — or settop",
      },
    },
    {
      q: "What are to-be-closed variables (Lua 5.4)?",
      a: "local x <close> = obj runs obj’s __close when the variable goes out of scope (even on error), like a finally for resources.",
      e: "It’s RAII for Lua. Files and locks benefit. __close is separate from __gc (GC timing is later and not for control flow).",
      visual: {
        title: "close on scope exit",
        kind: "timeline",
        events: [
          { h: "local <close>", lines: ["Acquire"] },
          { h: "Use", lines: ["Body runs"] },
          { h: "Leave / error", lines: ["__close"] },
          { h: "Later GC", lines: ["__gc if any"] },
        ],
        footer: "__close is deterministic — __gc is not",
      },
    },
    {
      q: "How do you iterate with a producer coroutine?",
      a: "A factory returns a coroutine wrapped so for x in iter() do works: the iterator resumes until the coroutine dies.",
      e: "This is cleaner than packing a huge list. Errors inside the coroutine should be resumed with pcall or wrap. Don’t mix yield across unprotected C.",
      visual: {
        title: "Coroutine iterator",
        kind: "cycle",
        center: "for-in",
        items: [
          { h: "create", lines: ["Producer thread"] },
          { h: "yield item", lines: ["One value"] },
          { h: "for body", lines: ["Consumes it"] },
          { h: "resume", lines: ["Next item"] },
          { h: "dead", lines: ["Loop ends"] },
        ],
        footer: "yield is the iterator’s return",
      },
    },
  ],
  expert: [
    {
      q: "How do you embed Lua from C correctly?",
      a: "luaL_newstate (or lua_newstate with an allocator), luaL_openlibs if you want the stdlib, load buffer, lua_pcall, then lua_close. One lua_State per VM; coroutines are lua_newthread on that state.",
      e: "Never call unprotected lua_call on untrusted code. Lock the state if two OS threads touch it (Lua is not thread-safe). Match the ABI (float vs int, 32/64) with the host.",
      visual: {
        title: "Embed checklist",
        kind: "hub",
        hub: "lua_State",
        nodes: [
          { h: "newstate", lines: ["Allocator"] },
          { h: "openlibs", lines: ["Optional std"] },
          { h: "load", lines: ["Chunk on stack"] },
          { h: "pcall", lines: ["Protected run"] },
          { h: "threads", lines: ["lua_newthread"] },
          { h: "close", lines: ["Free VM"] },
        ],
        footer: "One state, one OS thread unless you lock",
      },
    },
    {
      q: "How does LuaJIT differ from PUC Lua?",
      a: "LuaJIT is a tracing JIT plus an FFI, based on Lua 5.1 (with some 5.2 bits). PUC Lua 5.3/5.4 added integers, bitwise ops, generational GC — not all exist the same way in JIT.",
      e: "LuaJIT is usually faster for number crunching and FFI. It is a different runtime (GC, traces, NYI bytecodes abort traces). Pick one per product; don’t mix bytecode.",
      visual: {
        title: "PUC vs LuaJIT",
        kind: "compare",
        left: {
          h: "PUC Lua 5.4",
          lines: ["Integers · <close>", "Generational GC", "Official language", "Portable interpreter"],
        },
        right: {
          h: "LuaJIT",
          lines: ["Tracing JIT", "FFI to C", "5.1-based", "Trace aborts matter"],
        },
        footer: "Same spirit — not the same VM or language version",
      },
    },
    {
      q: "How does lua_pcall protect the host?",
      a: "lua_pcall runs a function on the stack and catches Lua errors, returning a status instead of longjmp’ing through C (unless you use lua_call).",
      e: "Use a message handler for traces. After an error, the stack has the error object. Hosts that forget pcall crash when a script errors in a metamethod.",
      visual: {
        title: "Protected call",
        kind: "code",
        code: {
          file: "host.c",
          code: [
            "lua_getglobal(L, \"run\");",
            "if (lua_pcall(L, 0, 0, 0))",
            "  log(lua_tostring(L, -1));",
          ],
          notes: [
            { h: "nargs/nres", text: "pcall(L, nargs, nres, msgh)" },
            { h: "status", text: "0 is LUA_OK" },
            { h: "msgh", text: "0 or a handler index" },
          ],
        },
        footer: "Unprotected lua_call is for trusted, tiny snippets",
      },
    },
    {
      q: "How should userdata lifetimes be managed?",
      a: "Allocate full userdata with lua_newuserdatauv so GC owns the blob. Set a metatable with __gc to detach C resources. Keep a ref in the registry if C must pin the object.",
      e: "Light userdata is not GC’d — don’t free it in __gc. Double-free happens when both __gc and the host free. A tombstone pointer in the userdata after close is the usual pattern.",
      visual: {
        title: "userdata lifetime",
        kind: "steps",
        steps: [
          { h: "newuserdata", lines: ["GC-owned bytes"] },
          { h: "setmetatable", lines: ["__index · __gc"] },
          { h: "Use from Lua", lines: ["Methods via mt"] },
          { h: "__gc / close", lines: ["Release C side"] },
        ],
        footer: "One owner for the C resource — usually __gc",
      },
    },
    {
      q: "When do you use __gc versus __close?",
      a: "__gc is a finalizer for GC-managed objects (timing not guaranteed). __close (5.4) runs when a to-be-closed variable leaves scope — use it for locks and files you must release now.",
      e: "Don’t use __gc for control flow. Errors in __gc are handled specially. Hosts on LuaJIT only have __gc.",
      visual: {
        title: "__gc vs __close",
        kind: "compare",
        left: {
          h: "__gc",
          lines: ["When GC runs", "Memory/C handles", "Not prompt", "JIT + PUC"],
        },
        right: {
          h: "__close",
          lines: ["Scope exit", "Deterministic", "5.4 <close>", "Like finally"],
        },
        footer: "Need it now → __close; memory mop-up → __gc",
      },
    },
    {
      q: "How do you keep the C API stack honest?",
      a: "Know the index of every slot. lua_gettop, lua_settop, luaL_checkstack. After a call, pop what you don’t need. Absolute indices beat magic numbers in helpers.",
      e: "Macros that push and forget are the usual leak. lua_insert/rotate in 5.3+ help. Never hold a raw char* from lua_tostring across a call that can GC (strings may move in theory; interned but still).",
      visual: {
        title: "Stack discipline",
        kind: "layers",
        layers: [
          { h: "Bottom (1)", lines: ["Stable args"] },
          { h: "Temps", lines: ["Push helpers"] },
          { h: "pcall frame", lines: ["Function + args"] },
          { h: "Top (-1)", lines: ["Latest value"] },
        ],
        footer: "Balance is correctness — not a style nicety",
      },
    },
    {
      q: "What makes LuaJIT’s FFI fast — and fragile?",
      a: "FFI lets you call C and declare structs in Lua. The JIT compiles those calls into machine code. It’s often faster than the classic C API for tight loops.",
      e: "FFI types and GC must be understood: ffi.gc, cdata, and no traces when you hit NYI. Security: FFI can crash the process — not for untrusted scripts.",
      visual: {
        title: "LuaJIT FFI",
        kind: "code",
        code: {
          file: "ffi.lua",
          code: [
            "local ffi = require 'ffi'",
            "ffi.cdef[[ int abs(int); ]]",
            "print(ffi.C.abs(-3))",
          ],
          notes: [
            { h: "cdef", text: "Declare C signatures" },
            { h: "JIT", text: "Calls can be traces" },
            { h: "Untrusted", text: "FFI is not a sandbox" },
          ],
        },
        footer: "FFI is a power tool — not a guest-script API",
      },
    },
    {
      q: "Why do LuaJIT traces abort, and why care?",
      a: "The tracer records a hot path. Some bytecodes, type instability, or C calls are NYI and abort the trace — you fall back to the interpreter.",
      e: "Expert performance work is reading -jdump / jit.attach and keeping types stable (one table shape, one number type). PUC Lua has no traces; this question is LuaJIT-specific.",
      visual: {
        title: "Trace lifetime",
        kind: "timeline",
        events: [
          { h: "Hot loop", lines: ["Counter trips"] },
          { h: "Record", lines: ["Trace IR"] },
          { h: "Compile", lines: ["Machine code"] },
          { h: "Abort / side", lines: ["Back to VM"] },
        ],
        footer: "Stable types keep traces alive",
      },
    },
    {
      q: "How does metamethod lookup actually proceed?",
      a: "For a missing key, Lua looks at the object’s metatable __index (table or function). For binary ops it consults the left then right metatable. rawget/rawset never do this.",
      e: "Recursion: __index functions that read the same key without rawget overflow. __eq requires the same metatable. Debug hooks can see these calls.",
      visual: {
        title: "Lookup chain",
        kind: "cycle",
        center: "t.k",
        items: [
          { h: "raw table", lines: ["Found? use it"] },
          { h: "__index tbl", lines: ["Walk prototype"] },
          { h: "__index fn", lines: ["Call it"] },
          { h: "nil", lines: ["Really missing"] },
          { h: "rawget", lines: ["Skip all of this"] },
        ],
        footer: "rawget is how constructors avoid __index loops",
      },
    },
    {
      q: "How do you use the registry and upvalues in C modules?",
      a: "LUA_REGISTRYINDEX is a hidden table. luaL_ref stores a value and returns an int handle. C closures use lua_pushcclosure with upvalues for state without globals.",
      e: "Refs must be unref’d or they leak. Don’t put large graphs in the registry forever. Multiple modules share the registry — namespace your keys (lightuserdata tokens).",
      visual: {
        title: "C module state",
        kind: "hub",
        hub: "C module",
        nodes: [
          { h: "upvalues", lines: ["Per-closure state"] },
          { h: "registry", lines: ["luaL_ref"] },
          { h: "userdata", lines: ["Per-object"] },
          { h: "LUA_NOREF", lines: ["Sentinel"] },
          { h: "preload", lines: ["luaL_requiref"] },
          { h: "luaopen_*", lines: ["Module entry"] },
        ],
        footer: "Prefer upvalues — the registry is a global heap",
      },
    },
    {
      q: "How do Lua 5.4 generational GC and finalizers interact?",
      a: "Young objects are swept more often. Finalized userdata is marked and collected in a later phase so __gc can run without the object vanishing mid-call.",
      e: "Resurrecting from __gc (storing the object again) is possible but ugly. Generational mode + lots of userdata finalizers can still pause. LuaJIT’s GC is a different design.",
      visual: {
        title: "Finalizer phase",
        kind: "code",
        code: {
          file: "gc.lua",
          code: [
            "mt = {__gc = function(u)",
            "  -- free C resource",
            "end}",
            "setmetatable(u, mt)",
          ],
          notes: [
            { h: "Mark", text: "Unreachable userdata queued" },
            { h: "__gc", text: "Runs before free" },
            { h: "Resurrect", text: "Possible, not advised" },
          ],
        },
        footer: "Finalizers run later than you think — __close if you need now",
      },
    },
    {
      q: "How do you debug across the C/Lua boundary?",
      a: "lua_getstack / lua_getinfo walk Lua frames. A msgh on pcall adds traceback. For C, you see one frame unless you use lua_Kfunction yieldable calls.",
      e: "debug.sethook is powerful and slow. Never leave hooks on in production. Source maps for generated Lua (Moonscript, Fennel) need debug.short_src set on chunks.",
      visual: {
        title: "Trace an error",
        kind: "steps",
        steps: [
          { h: "pcall msgh", lines: ["debug.traceback"] },
          { h: "Lua frames", lines: ["getinfo source:line"] },
          { h: "C frames", lines: ["Host debugger"] },
          { h: "hooks", lines: ["line / call / ret"] },
        ],
        footer: "Protected calls plus a msgh are the baseline",
      },
    },
    {
      q: "How do upvalues and closures interact with GC?",
      a: "A nested function keeps the stack slots it closes over (upvalues). Those objects stay alive as long as the closure does — including big tables you thought were temporary.",
      e: "Same leak as R/JS: factories that close over a huge local. Bind only what you need. debug.getupvalue can inspect (and accidentally keep) them.",
      visual: {
        title: "Closed-over state",
        kind: "layers",
        layers: [
          { h: "Outer locals", lines: ["Become upvalues"] },
          { h: "Closure", lines: ["Keeps them live"] },
          { h: "Module table", lines: ["Keeps the closure"] },
          { h: "GC", lines: ["Waits for all refs"] },
        ],
        footer: "Tiny returned functions can pin megabyte upvalues",
      },
    },
    {
      q: "What is the expert way to sandbox Lua?",
      a: "Load with a fresh _ENV that has only allowlisted functions, no FFI, no debug, no package.loadlib. Use a timeout hook. Still assume a determined script can tight-loop.",
      e: "Lua is not a security boundary if FFI or C libraries are exposed. OpenResty and games still get this wrong. Prefer a dedicated state per untrusted user.",
      visual: {
        title: "Sandbox layers",
        kind: "timeline",
        events: [
          { h: "Own lua_State", lines: ["No shared _G"] },
          { h: "Tiny _ENV", lines: ["Allowlist"] },
          { h: "No FFI/debug", lines: ["Strip searchers"] },
          { h: "Hook timeout", lines: ["Stop runaway"] },
        ],
        footer: "A shallow env is not enough if loadlib exists",
      },
    },
    {
      q: "When is Lua the wrong tool at expert scale?",
      a: "When you need hard threads, a huge stdlib, or guaranteed 5.4 language features on LuaJIT. When untrusted users must not crash the host. When numeric libraries and types matter more than embed size.",
      e: "The expert answer: Lua wins as a guest VM. Keep hot loops in C/JIT, keep scripts small, keep the C API stack disciplined. That’s the whole design.",
      visual: {
        title: "Stay in Lua’s lane",
        kind: "cycle",
        center: "embed",
        items: [
          { h: "Guest scripts", lines: ["What Lua is for"] },
          { h: "C kernels", lines: ["Hot paths"] },
          { h: "One state", lines: ["Lock if multi-OS"] },
          { h: "JIT or PUC", lines: ["Pick one"] },
          { h: "Small _ENV", lines: ["Untrusted code"] },
        ],
        footer: "Lua is a VM you host — not a full application platform",
      },
    },
  ],
};
