module.exports = {
  name: "MATLAB",
  description:
    "MATLAB interview questions — matrices, indexing, vectorization, classes, and the execution engine.",
  match: /^matlab$/i,
  theme: {
    accent: "#e16737",
    hubFill: "#e16737",
    hubText: "#ffffff",
    centerFill: "#ffedd5",
    centerStroke: "#e16737",
    label: "MATLAB",
  },
  beginner: [
    {
      q: "What is MATLAB built around?",
      a: "MATLAB is a matrix-first language: the basic type is a rectangular array (often double). Linear algebra, indexing, and plotting are the core, with toolboxes adding domains.",
      e: "Even a scalar is a 1×1 array. Character vectors, strings, cells, and tables came later. Interviews start with ‘everything is an array’ and column-major layout.",
      visual: {
        title: "MATLAB’s center of gravity",
        kind: "hub",
        hub: "array",
        nodes: [
          { h: "double", lines: ["Default numeric"] },
          { h: "index", lines: ["() not []"] },
          { h: "vectorize", lines: ["Avoid loops"] },
          { h: "toolboxes", lines: ["Domain packs"] },
          { h: "JIT", lines: ["Speeds loops"] },
          { h: "plots", lines: ["figures/axes"] },
        ],
        footer: "A scalar is still a 1×1 matrix",
      },
    },
    {
      q: "How do matrices differ from cell arrays?",
      a: "A numeric matrix holds one type in a rectangular block. A cell array is a container of boxes — each cell can hold anything (even another array).",
      e: "Use {} to get the contents of a cell and () to slice cells. Mixing types in a numeric array will error or convert; cells exist so you don’t have to.",
      visual: {
        title: "matrix vs cell",
        kind: "compare",
        left: {
          h: "matrix",
          lines: ["Homogeneous data", "A(2,1) element", "Fast math", "One class inside"],
        },
        right: {
          h: "cell array",
          lines: ["Heterogeneous", "C{2,1} contents", "Containers", "C(2,1) is a 1×1 cell"],
        },
        footer: "{} unwraps a cell — () subsets the cell array",
      },
    },
    {
      q: "How do you create and size a matrix?",
      a: "Brackets concatenate: [1 2; 3 4] is 2×2. zeros, ones, eye, rand, linspace, and colon 1:10 build arrays. size, numel, and ndims inspect them.",
      e: "Space or comma is horizontal; semicolon is a new row. ' is conjugate transpose; .' is not conjugate. Preallocate — growing in a loop is slow.",
      visual: {
        title: "Build a matrix",
        kind: "code",
        code: {
          file: "mat.m",
          code: [
            "A = [1 2; 3 4]",
            "z = zeros(3, 2)",
            "v = 1:2:9",
            "[m, n] = size(A)",
          ],
          notes: [
            { h: ";", text: "Next row in a literal" },
            { h: "zeros", text: "Preallocate the shape" },
            { h: "size", text: "Rows then columns" },
          ],
        },
        footer: "Know size vs length vs numel in interviews",
      },
    },
    {
      q: "How does MATLAB indexing work?",
      a: "Parentheses index: A(i,j), A(i,:), A(:). Linear index A(k) walks column-major. Logical masks select where true. end is the last index in that dimension.",
      e: "1-based. A(2) on a matrix is not always ‘row 2’ — it is the second element in column-major order. sub2ind/ind2sub convert.",
      visual: {
        title: "Index a matrix",
        kind: "steps",
        steps: [
          { h: "Subscripts", lines: ["A(r, c)"] },
          { h: "Slice", lines: ["A(:, 2) a column"] },
          { h: "Linear", lines: ["A(k) column-major"] },
          { h: "Logical", lines: ["A(A > 0)"] },
        ],
        footer: "() indexes — {} is for cells and strings (older)",
      },
    },
    {
      q: "What is the difference between a script and a function?",
      a: "A script runs in the caller’s workspace (or base). A function has its own workspace, declared with function out = name(in), and should live in name.m.",
      e: "Scripts are for experiments; functions are for reuse and speed (JIT likes functions). Local functions can sit below the main function in the same file.",
      visual: {
        title: "script vs function",
        kind: "compare",
        left: {
          h: "script",
          lines: ["Shared workspace", "Easy to hack", "Name.m run as a whole", "Clobbers variables"],
        },
        right: {
          h: "function",
          lines: ["Own workspace", "Clear inputs/outputs", "JIT-friendly", "Testable"],
        },
        footer: "Promote a script to a function when it matters",
      },
    },
    {
      q: "How is the workspace organized?",
      a: "base workspace is the Command Window. Each function call has a stack frame. nested functions share the parent’s workspace. global and persistent are the escape hatches.",
      e: "assignin/evalin reach other workspaces — avoid them. who/whos inspect. Clear all is a blunt tool that also drops breakpoints’ context.",
      visual: {
        title: "Workspace layers",
        kind: "layers",
        layers: [
          { h: "base", lines: ["Command Window"] },
          { h: "script", lines: ["Usually the caller’s"] },
          { h: "function frame", lines: ["Inputs · locals · outputs"] },
          { h: "nested", lines: ["Sees parent locals"] },
        ],
        footer: "Functions isolate — scripts do not",
      },
    },
    {
      q: "What is vectorization in MATLAB?",
      a: "Write operations on whole arrays (A .* B, sum(A, 1), logical index) so work happens in optimized internals instead of m-file loops.",
      e: ".* ./ .^ are element-wise; * is matrix multiply. Implicit expansion (broadcasting) replaced many bsxfun calls. Vectorize first, then profile remaining loops.",
      visual: {
        title: "Element-wise vs matrix",
        kind: "code",
        code: {
          file: "vec.m",
          code: [
            "C = A .* B    % element-wise",
            "D = A * B     % matmul",
            "s = sum(A, 1) % per column",
            "A(A < 0) = 0",
          ],
          notes: [
            { h: ".*", text: "Same-size or expanded" },
            { h: "*", text: "Linear algebra product" },
            { h: "mask", text: "Logical index assigns" },
          ],
        },
        footer: "Dots make it element-wise — * is matmul",
      },
    },
    {
      q: "How do you go from a script to a reusable function?",
      a: "Identify inputs/outputs, add a function line, save as the function name, preallocate, and replace hardcoded paths with arguments.",
      e: "Add arguments blocks (R2019b+) for validation. Keep a thin script that calls the function so exploration stays easy.",
      visual: {
        title: "Promote to a function",
        kind: "timeline",
        events: [
          { h: "Script", lines: ["Hardcoded data"] },
          { h: "function line", lines: ["In and out"] },
          { h: "Preallocate", lines: ["zeros(n,1)"] },
          { h: "arguments", lines: ["Validate types"] },
        ],
        footer: "The .m file name must match the function",
      },
    },
    {
      q: "What array types should a beginner know?",
      a: "double, single, logical, char, string, cell, struct, table, and gpuArray (PCT). Categorical and datetime are common in table workflows.",
      e: "Default literals are double. logical is 0/1 but a real class. string vs char is a frequent gotcha ('abc' is 1×3 char; \"abc\" is a string scalar).",
      visual: {
        title: "Array zoo",
        kind: "cycle",
        center: "arrays",
        items: [
          { h: "double", lines: ["Numeric default"] },
          { h: "logical", lines: ["Masks"] },
          { h: "cell", lines: ["Boxes"] },
          { h: "struct", lines: ["Named fields"] },
          { h: "table", lines: ["Columns"] },
          { h: "string", lines: ["Text objects"] },
        ],
        footer: "Know char vs string — they are not the same",
      },
    },
    {
      q: "What do the common operators mean?",
      a: "* / ^ are matrix algebra. .* ./ .^ are element-wise. \\ and / solve linear systems (better than inv). ' is conjugate transpose.",
      e: "A\\b solves A*x = b. That’s an interview classic. == is element-wise; use isequal for whole-array equality including size.",
      visual: {
        title: "Operator map",
        kind: "hub",
        hub: "ops",
        nodes: [
          { h: "* / ^", lines: ["Matrix algebra"] },
          { h: ".* ./ .^", lines: ["Per element"] },
          { h: "A\\b", lines: ["Solve A*x=b"] },
          { h: "'", lines: ["Ctranspose"] },
          { h: ".'", lines: ["Transpose"] },
          { h: "==", lines: ["Element mask"] },
        ],
        footer: "Prefer A\\b over inv(A)*b",
      },
    },
    {
      q: "How does logical indexing work?",
      a: "A logical array the same size (or a vector for linear index) selects entries. A(A > 0) = 0 is the idiomatic clamp. find returns subscripts or linear indices.",
      e: "Mixing a logical vector with the wrong length errors. ~ is not. Any/all reduce masks. This is the heart of vectorized cleanup of data.",
      visual: {
        title: "Mask then assign",
        kind: "code",
        code: {
          file: "mask.m",
          code: [
            "m = A > 0",
            "pos = A(m)",
            "A(~m) = NaN",
            "idx = find(m)",
          ],
          notes: [
            { h: "m", text: "logical same size as A" },
            { h: "A(m)", text: "Pull matching values" },
            { h: "find", text: "Indices where true" },
          ],
        },
        footer: "Masks beat for-loops for filters",
      },
    },
    {
      q: "What does the colon operator do?",
      a: "a:b is a row vector from a to b. a:s:b uses step s. A(:) stacks A into a column (column-major). A(i:j, k) slices.",
      e: "The colon is both ‘range’ and ‘all of this dimension’. linspace is for a fixed number of points; colon is for a fixed step.",
      visual: {
        title: "Colon in three jobs",
        kind: "steps",
        steps: [
          { h: "Range", lines: ["1:2:9"] },
          { h: "All", lines: ["A(:, 2)"] },
          { h: "Stack", lines: ["A(:) column"] },
          { h: "end", lines: ["A(end-1:end)"] },
        ],
        footer: "A(:) is the column-major vector of A",
      },
    },
    {
      q: "How does the MATLAB path work?",
      a: "path is a list of folders. The first match of name.m / name.mex / a method wins. Current folder and pwd matter. addpath/pathtool change it.",
      e: "Shadowing a toolbox function with your own name.m is a classic bug. which foo shows what will run. Private folders and +packages (namespaces) limit visibility.",
      visual: {
        title: "Name lookup",
        kind: "layers",
        layers: [
          { h: "Current folder", lines: ["Often first"] },
          { h: "userpath / addpath", lines: ["Your libs"] },
          { h: "toolboxes", lines: ["MathWorks code"] },
          { h: "built-ins", lines: ["Always available"] },
        ],
        footer: "which name — always, when it ‘suddenly’ calls the wrong file",
      },
    },
    {
      q: "Why do people say MATLAB has a JIT?",
      a: "The execution engine JIT-compiles many loops and function calls so well-written m-code is much faster than old interpreted MATLAB.",
      e: "JIT is not an excuse for growing arrays or copying huge matrices. Vectorized builtins still win. mex and gpuArray are the next steps when the profiler says so.",
      visual: {
        title: "From script to native",
        kind: "timeline",
        events: [
          { h: ".m source", lines: ["Your functions"] },
          { h: "JIT", lines: ["Hot loops"] },
          { h: "builtins", lines: ["Already native"] },
          { h: "mex / GPU", lines: ["When still slow"] },
        ],
        footer: "JIT helps loops — copies and growth still hurt",
      },
    },
    {
      q: "What is a toolbox conceptually?",
      a: "A toolbox is a licensed set of functions, apps, and sometimes mex/GPU code for a domain (Signal, Image, Stats, Optimization, Parallel, Simulink as a sibling).",
      e: "ver and license('test', ...) check what’s installed. Interviews don’t want you to recite every toolbox — they want ‘optional domain libraries on the same array core’.",
      visual: {
        title: "Core plus toolboxes",
        kind: "cycle",
        center: "MATLAB",
        items: [
          { h: "Core", lines: ["Arrays · plots"] },
          { h: "Stats", lines: ["fitlm · pca"] },
          { h: "Signal", lines: ["filters"] },
          { h: "PCT", lines: ["parfor · gpu"] },
          { h: "Coder", lines: ["C / MEX"] },
        ],
        footer: "Same language — licensed extra functions",
      },
    },
  ],
  intermediate: [
    {
      q: "When is vectorization worth it vs a plain loop?",
      a: "Vectorize when the operation is element-wise or a reduction the builtins already implement. Keep a loop when logic is sequential, sparse in an ugly way, or clearer and the profiler is fine.",
      e: "Modern JIT closed much of the gap. The remaining wins are BLAS, no copies, and GPU. Readable loops + preallocation beat clever bsxfun nobody can edit.",
      visual: {
        title: "Choose an approach",
        kind: "hub",
        hub: "speed",
        nodes: [
          { h: "builtin", lines: ["sum · fft"] },
          { h: ".* mask", lines: ["Element ops"] },
          { h: "loop + zeros", lines: ["Sequential"] },
          { h: "arrayfun", lines: ["Last resort"] },
          { h: "gpuArray", lines: ["Big dense"] },
          { h: "profile", lines: ["Measure"] },
        ],
        footer: "Profiler first — folklore second",
      },
    },
    {
      q: "How does a vectorized expression beat a for-loop?",
      a: "A loop in m-code still has per-iteration overhead and may copy. A vectorized line calls one optimized function over contiguous data (column-major).",
      e: "Temporary arrays in a long vectorized chain can use more RAM than a loop. Split expressions or use in-place ops when memory is the limit.",
      visual: {
        title: "loop vs vectorized",
        kind: "compare",
        left: {
          h: "for-loop",
          lines: ["Easy control flow", "Preallocate!", "JIT helps now", "Per-step overhead"],
        },
        right: {
          h: "vectorized",
          lines: ["One native call", "May use temps", "BLAS / SIMD", "Harder to debug"],
        },
        footer: "Preallocated loops are OK — growing loops are not",
      },
    },
    {
      q: "What is implicit expansion?",
      a: "Compatible sizes expand like broadcasting: a 1×n and m×1 become m×n. It replaced most bsxfun calls (R2016b+).",
      e: "Mismatched sizes still error. bsxfun remains in old code. On the GPU, expansion still allocates the result — watch memory.",
      visual: {
        title: "Expand then operate",
        kind: "code",
        code: {
          file: "exp.m",
          code: [
            "r = [1 2 3]      % 1x3",
            "c = [10; 20]     % 2x1",
            "S = r + c        % 2x3",
            "% S(i,j)=c(i)+r(j)",
          ],
          notes: [
            { h: "1×n + m×1", text: "Outer-style expand" },
            { h: "bsxfun", text: "Old explicit form" },
            { h: "GPU", text: "Still a real allocation" },
          ],
        },
        footer: "Singleton dimensions stretch — others must match",
      },
    },
    {
      q: "What is a function handle?",
      a: "@sin or @(x) x.^2 is a function handle you can pass to solvers, arrayfun, and callbacks. Anonymous handles capture the workspace they were created in.",
      e: "str2func is the string cousin. Capturing a huge workspace in an anonymous function leaks memory — same closure trap as other languages.",
      visual: {
        title: "Pass a function",
        kind: "steps",
        steps: [
          { h: "@name", lines: ["Named function"] },
          { h: "@(x) expr", lines: ["Anonymous"] },
          { h: "Capture", lines: ["Outer locals"] },
          { h: "feval / call", lines: ["f(x)"] },
        ],
        footer: "Anonymous handles close over their birth workspace",
      },
    },
    {
      q: "When do you use arrayfun vs true vectorization?",
      a: "arrayfun applies a handle to each element. It’s convenience, not speed — often slower than a loop. Use it when the per-element work is a function you can’t vectorize.",
      e: "On gpuArray, arrayfun can compile an element kernel — that’s the case where it becomes fast. On CPU, rewrite with .* if you can.",
      visual: {
        title: "arrayfun vs .*",
        kind: "compare",
        left: {
          h: "arrayfun (CPU)",
          lines: ["Per-element calls", "Often slower", "Any function", "Last resort"],
        },
        right: {
          h: "vectorize / GPU",
          lines: [".* and builtins", "arrayfun on GPU kernel", "Big dense arrays", "Profile it"],
        },
        footer: "CPU arrayfun is not ‘vectorized’ in the fast sense",
      },
    },
    {
      q: "Why does column-major layout matter?",
      a: "MATLAB stores the first index varying fastest: columns are contiguous. A(:,j) is a stride-1 slice; A(i,:) jumps. Loops should vary the row index innermost for cache.",
      e: "Linear index and A(:) follow this order. mex and BLAS expect it. Row-major mental models from C/Python (default) cause the wrong loop nest.",
      visual: {
        title: "Column-major memory",
        kind: "layers",
        layers: [
          { h: "A(1,1)", lines: ["First in memory"] },
          { h: "A(2,1)", lines: ["Next — down the column"] },
          { h: "A(:,1) then A(:,2)", lines: ["Columns packed"] },
          { h: "A(1,:)", lines: ["Strided — slower"] },
        ],
        footer: "Loop down columns — that’s how the bytes sit",
      },
    },
    {
      q: "What is a handle class vs a value class?",
      a: "Value classes (default) copy on assignment like structs. Handle classes (< handle) have reference semantics: copies point to the same object.",
      e: "Graphics objects and many toolboxes are handles. Passing a handle into a function can mutate the caller’s object. value classes need a new output to change.",
      visual: {
        title: "classdef HandleClock",
        kind: "code",
        code: {
          file: "clk.m",
          code: [
            "classdef Acc < handle",
            "  properties",
            "    n = 0",
            "  end",
            "  methods",
            "    function bump(o), o.n = o.n+1; end",
          ],
          notes: [
            { h: "< handle", text: "Reference object" },
            { h: "bump(o)", text: "Caller sees n change" },
            { h: "value class", text: "Would need obj = bump(obj)" },
          ],
        },
        footer: "handle is a pointer — value is a copy-on-write struct",
      },
    },
    {
      q: "How do you use the profiler effectively?",
      a: "profile on; run; profile viewer shows time per line, plus self vs total. Look for copies, disp in loops, and growing arrays.",
      e: "tic/toc is a stopwatch, not a map. timeit is better for microbenches. Memory: memory and whos; copies don’t always show as ‘your line’ if a builtin copies.",
      visual: {
        title: "Measure then cut",
        kind: "timeline",
        events: [
          { h: "profile on", lines: ["Instrument"] },
          { h: "Run workload", lines: ["Real sizes"] },
          { h: "Hot lines", lines: ["Self time"] },
          { h: "Fix copies", lines: ["Prealloc · vec"] },
        ],
        footer: "timeit for snippets — profiler for programs",
      },
    },
    {
      q: "How does gpuArray change the workflow?",
      a: "gpuArray(A) moves data to the GPU. Many builtins overload and run there. gather brings results back. arrayfun can JIT an element-wise kernel.",
      e: "Transfer cost dominates small arrays. Not every function is supported. Parallel Computing Toolbox required. Keep data on GPU across steps to amortize copies.",
      visual: {
        title: "CPU ↔ GPU",
        kind: "cycle",
        center: "gpuArray",
        items: [
          { h: "gpuArray", lines: ["Host → device"] },
          { h: "overloads", lines: ["fft · * · sum"] },
          { h: "arrayfun", lines: ["Element kernel"] },
          { h: "gather", lines: ["Back to CPU"] },
          { h: "Stay on GPU", lines: ["Avoid ping-pong"] },
        ],
        footer: "Moves are expensive — compute a lot per transfer",
      },
    },
    {
      q: "What indexing styles must you not confuse?",
      a: "Subscript (r,c), linear (k), logical, and for tables T.x / T{:,'x'} / T(:,'x'). Cells use {} vs (). Strings use curly for old char arrays sometimes.",
      e: "T(:, 'x') is a table; T.x is a vector. That’s the analog of R’s [ vs [[. Interviews love mixing these on purpose.",
      visual: {
        title: "Indexing styles",
        kind: "hub",
        hub: "index",
        nodes: [
          { h: "A(r,c)", lines: ["Subscripts"] },
          { h: "A(k)", lines: ["Linear"] },
          { h: "A(mask)", lines: ["Logical"] },
          { h: "C{i}", lines: ["Cell contents"] },
          { h: "T.x", lines: ["Table variable"] },
          { h: "S.f", lines: ["Struct field"] },
        ],
        footer: "Wrong brackets are the usual table/cell bug",
      },
    },
    {
      q: "When do sparse matrices help?",
      a: "sparse stores only nonzeros. Factorization and * use sparse kernels. Full operations may densify and explode RAM.",
      e: "Index assignment that fills many zeros can densify. speye, sprand, nnz, spdiags are the vocabulary. Don’t sparse a matrix that’s already 30% dense — overhead wins.",
      visual: {
        title: "sparse pattern",
        kind: "code",
        code: {
          file: "sp.m",
          code: [
            "S = sparse(i, j, v, m, n)",
            "x = S \\ b",
            "full(S)   % usually don't",
            "nnz(S)",
          ],
          notes: [
            { h: "triplet", text: "i, j, v build S" },
            { h: "\\", text: "Sparse solvers" },
            { h: "full", text: "Can blow memory" },
          ],
        },
        footer: "Keep it sparse end-to-end or don’t bother",
      },
    },
    {
      q: "How do nested and anonymous functions capture state?",
      a: "Nested functions share the parent workspace (and can assign). Anonymous handles copy the captured values at creation (value capture), not a live handle to locals.",
      e: "That’s why nested functions are used for callbacks that must mutate. persistent is per-function memory across calls. Don’t mix them carelessly with parfor.",
      visual: {
        title: "Capture rules",
        kind: "steps",
        steps: [
          { h: "nested", lines: ["Shared workspace"] },
          { h: "assign in parent", lines: ["Visible to nest"] },
          { h: "anonymous", lines: ["Snapshot values"] },
          { h: "parfor", lines: ["Transparency rules"] },
        ],
        footer: "Nested can mutate — @(x) usually cannot",
      },
    },
    {
      q: "How should you think about toolboxes in an interview?",
      a: "Name the toolbox when you use its APIs (fitcsvm is Statistics, gpuArray is PCT, tf is Control). Core MATLAB won’t have them on a bare install.",
      e: "Don’t claim Simulink is ‘just a toolbox’ — it’s a separate product. Coder/GPU Coder compile a subset of the language. Know license as a deployment constraint.",
      visual: {
        title: "Product stack",
        kind: "layers",
        layers: [
          { h: "MATLAB core", lines: ["Arrays · graphics"] },
          { h: "Math toolboxes", lines: ["Stats · Opt · Signal"] },
          { h: "PCT / GPU", lines: ["parfor · gpuArray"] },
          { h: "Coder / Simulink", lines: ["Codegen · models"] },
        ],
        footer: "APIs imply licenses — say which toolbox you need",
      },
    },
    {
      q: "What is MEX and when do you reach for it?",
      a: "A mex file is a C/C++/Fortran DLL with a mexFunction gateway, called like an m-file. Use it when a hot kernel isn’t in a builtin and JIT isn’t enough.",
      e: "You must understand mxArray, copy vs inplace (don’t violate copy-on-write), and column-major. Coder can generate mex from a subset of MATLAB automatically.",
      visual: {
        title: "m-code to mex",
        kind: "timeline",
        events: [
          { h: "profile", lines: ["Find the kernel"] },
          { h: "C / Coder", lines: ["Implement"] },
          { h: "mex build", lines: ["Gateway"] },
          { h: "same call", lines: ["foo(...)"] },
        ],
        footer: "mex is an implementation detail — the API stays MATLAB",
      },
    },
    {
      q: "Why is preallocation so important?",
      a: "x(end+1) = v may copy the whole array each time (copy-on-write + growth). zeros(n,1) then fill is O(n) instead of O(n²).",
      e: "The JIT sometimes optimizes simple growth, but don’t rely on it. For unknown length, a cell then vertcat, or a growing estimate with a final trim.",
      visual: {
        title: "Grow vs zeros",
        kind: "cycle",
        center: "n",
        items: [
          { h: "x(end+1)", lines: ["May copy all"] },
          { h: "O(n²)", lines: ["Death by growth"] },
          { h: "zeros(n,1)", lines: ["One alloc"] },
          { h: "Fill k", lines: ["x(k) = v"] },
          { h: "Trim", lines: ["x(1:k)"] },
        ],
        footer: "Allocate once — fill in place",
      },
    },
  ],
  expert: [
    {
      q: "How do handle and value classes differ under the hood?",
      a: "Value objects are copy-on-write arrays of structs (with method dispatch). Handle objects are references to a scalar object; assignment copies the handle, not the state.",
      e: "Arrays of handles are arrays of refs. isequal on handles can compare identity or values depending on methods. Don’t put huge data in value objects you pass often — COW still snapshots on write.",
      visual: {
        title: "Reference vs COW",
        kind: "hub",
        hub: "classdef",
        nodes: [
          { h: "value", lines: ["Copy on write"] },
          { h: "handle", lines: ["Shared state"] },
          { h: "delete", lines: ["Handle destructor"] },
          { h: "events", lines: ["Handle only"] },
          { h: "matlab.mixin", lines: ["Copyable etc."] },
          { h: "System", lines: ["Simulink objects"] },
        ],
        footer: "If two names should alias, it must be a handle",
      },
    },
    {
      q: "When is a handle class the wrong choice?",
      a: "When you want value semantics (money, 3-vectors, immutable configs). Handles surprise callers who thought assignment copied. They also complicate parfor (transparency, serialization).",
      e: "Graphics must be handles because the figure exists once. Data-analysis types should usually be values or tables. matlab.mixin.Copyable adds an explicit copy for handles.",
      visual: {
        title: "handle vs value",
        kind: "compare",
        left: {
          h: "value class",
          lines: ["COW like struct", "obj = f(obj)", "parfor-friendly", "Data and math types"],
        },
        right: {
          h: "handle class",
          lines: ["Shared identity", "f(obj) mutates", "Listeners / graphs", "Harder to serialize"],
        },
        footer: "Default to value — handle when identity is the point",
      },
    },
    {
      q: "How do you write a small value class?",
      a: "classdef without < handle, properties, methods that return the modified object. Constructor must assign to the object being created.",
      e: "Dependent properties compute on get. Validation in properties blocks (R2019b+) beats ad-hoc setters. Overload disp, plus, size if you want array-like types.",
      visual: {
        title: "Value class skeleton",
        kind: "code",
        code: {
          file: "pt.m",
          code: [
            "classdef Pt",
            "  properties",
            "    x = 0; y = 0",
            "  end",
            "  methods",
            "    function p = shift(p, d)",
            "      p.x = p.x + d; end",
          ],
          notes: [
            { h: "No handle", text: "Value semantics" },
            { h: "p = shift", text: "Must return p" },
            { h: "COW", text: "Write copies if shared" },
          ],
        },
        footer: "Forgetting to return p is the classic value-class bug",
      },
    },
    {
      q: "How does copy-on-write interact with mex and in-place ops?",
      a: "MATLAB may share an array among names. A mex that writes mxGetPr without checking sharing corrupts the other name. Use mxUnshareArray / the official in-place rules, or always copy.",
      e: "In m-code, A = A + 1 may reuse storage if A is unique. That’s why ‘ans = A; A(1)=0’ can copy. Expert interviews expect you not to break COW from C.",
      visual: {
        title: "Shared then write",
        kind: "steps",
        steps: [
          { h: "B = A", lines: ["Shared buffer"] },
          { h: "A(1) = 0", lines: ["Unshare / copy"] },
          { h: "mex write", lines: ["Must unshare"] },
          { h: "Else corrupt B", lines: ["Heisenbug"] },
        ],
        footer: "If two names share, a write must copy first",
      },
    },
    {
      q: "What are the real limits of gpuArray and arrayfun?",
      a: "Device memory, PCIe transfers, unsupported functions, and CPU fallbacks that silently gather. arrayfun kernels can’t call arbitrary m-code — a subset only.",
      e: "pagefun, arrayfun, and overloaded * are the fast paths. Mixing sparse, cell, or tables on GPU mostly doesn’t work. Profile with gpuDevice and wait to hide async surprises.",
      visual: {
        title: "GPU constraints",
        kind: "compare",
        left: {
          h: "Fits GPU well",
          lines: ["Dense double/single", "Element kernels", "GEMM / fft", "Stay on device"],
        },
        right: {
          h: "Fits poorly",
          lines: ["Tiny arrays", "Branchy m-code", "Cell / table", "Chatty gather"],
        },
        footer: "If you gather every step, you only bought a copy",
      },
    },
    {
      q: "How should you loop for cache in column-major layout?",
      a: "Innermost loop should walk A(i, j) with i changing fastest (down the column). Blocking and slicing whole columns beats hopping along rows.",
      e: "The same rule as Fortran, opposite of C row-major. mex BLAS already assumes this. Transposing a huge matrix just to ‘feel like C’ can be the slowest line.",
      visual: {
        title: "Cache-friendly nest",
        kind: "layers",
        layers: [
          { h: "outer: columns j", lines: ["Each column a block"] },
          { h: "inner: rows i", lines: ["Contiguous bytes"] },
          { h: "A(i,j)", lines: ["Stride 1"] },
          { h: "A(i,:)", lines: ["Stride m — colder"] },
        ],
        footer: "Fortran order — not C order",
      },
    },
    {
      q: "How does arrayfun on the GPU actually run?",
      a: "The engine traces the anonymous function, compiles an element-wise kernel, and launches it. Supported ops are a whitelist (math, indexing of the elements, some branching).",
      e: "If you call an unsupported function, it errors or runs slowly on CPU depending on version. Keep the handle tiny. This is the good arrayfun — the CPU one is not.",
      visual: {
        title: "GPU arrayfun kernel",
        kind: "code",
        code: {
          file: "gker.m",
          code: [
            "G = gpuArray(A)",
            "H = arrayfun(@(x) x^2+1, G)",
            "B = gather(H)",
          ],
          notes: [
            { h: "trace", text: "Subset of MATLAB" },
            { h: "kernel", text: "One thread per element" },
            { h: "gather", text: "Only at the end" },
          ],
        },
        footer: "GPU arrayfun is a kernel compiler, not a for-loop helper",
      },
    },
    {
      q: "What should experts know about the JIT execution engine?",
      a: "Functions JIT better than scripts. Changing a .m on disk can invalidate. eval, evalin, assignin, and dynamic field names block optimization. Persistent + nested interact with the JIT in subtle ways.",
      e: "Don’t micro-optimize for last year’s engine. Read the profiler. MATLAB Coder is a different compiler with a language subset — not the same as the desktop JIT.",
      visual: {
        title: "What the JIT likes",
        kind: "timeline",
        events: [
          { h: "function .m", lines: ["Stable types"] },
          { h: "Known sizes", lines: ["Prealloc"] },
          { h: "No eval", lines: ["Visible names"] },
          { h: "Hot loop", lines: ["Native-ish code"] },
        ],
        footer: "eval is how you turn the JIT off",
      },
    },
    {
      q: "How do MATLAB OOP dispatch and packages interact?",
      a: "Method lookup uses the dominant argument’s class (usually the first). Packages (+pkg) namespace functions. Class folders (@Pt) hold methods in files.",
      e: "Overloading plus on many types is how * becomes BLAS or gpu. Inferior/superior classes (old) vs modern classdef mixins — know @folder vs classdef in one file.",
      visual: {
        title: "Where a method lives",
        kind: "cycle",
        center: "dispatch",
        items: [
          { h: "classdef file", lines: ["Methods block"] },
          { h: "@Class folder", lines: ["One method per file"] },
          { h: "+pkg", lines: ["Namespace"] },
          { h: "first arg", lines: ["Usually wins"] },
          { h: "builtin", lines: ["If no method"] },
        ],
        footer: "The class of the dominant arg picks the method",
      },
    },
    {
      q: "How do you reason about MATLAB memory in production?",
      a: "whos, memory, and the fact that temps in a vectorized chain peak above the inputs. COW means B=A is cheap until a write. Pack with single/gpu/sparse only when the algorithm allows.",
      e: "Clear large temps. Avoid persistent that pins GBs. parpool copies data to workers — use sliced variables and files/datastore for big data, not one huge array on the client.",
      visual: {
        title: "Memory levers",
        kind: "hub",
        hub: "RAM",
        nodes: [
          { h: "COW", lines: ["Share until write"] },
          { h: "temps", lines: ["Chain peaks"] },
          { h: "single", lines: ["Half the bytes"] },
          { h: "sparse", lines: ["If mostly 0"] },
          { h: "parpool", lines: ["Copies out"] },
          { h: "datastore", lines: ["Out of core"] },
        ],
        footer: "Peak temps — not the final array — cause the OOM",
      },
    },
    {
      q: "What does MATLAB Coder change about the language?",
      a: "Coder compiles a subset of MATLAB to C/C++ or mex. Types and sizes must be inferable (or specified). Cells, tables, and some OOP are limited or banned.",
      e: "It’s a second language dialect. coder.varsize, entry-point functions, and tests with codegen. GPU Coder is yet another subset. Don’t promise ‘any .m files compile’.",
      visual: {
        title: "Coder subset",
        kind: "code",
        code: {
          file: "entry.m",
          code: [
            "function y = entry(x)",
            "%#codegen",
            "y = x .* x",
            "end",
          ],
          notes: [
            { h: "%#codegen", text: "Marks an entry" },
            { h: "types", text: "Must be inferable" },
            { h: "subset", text: "Not full MATLAB" },
          ],
        },
        footer: "Coder is a compiler with a language diet",
      },
    },
    {
      q: "How does parfor actually split work?",
      a: "parfor slices classified variables to workers in a pool. The body must be transparent: no eval, no changing the function dynamically, reduction/sliced/broadcast rules.",
      e: "Communication beats compute if chunks are tiny. Threads vs processes (parpool('threads')) change what you can capture. Handles and graphics usually stay on the client.",
      visual: {
        title: "parfor classification",
        kind: "steps",
        steps: [
          { h: "broadcast", lines: ["Read-only copy"] },
          { h: "sliced", lines: ["x(i) independent"] },
          { h: "reduction", lines: ["s = s + …"] },
          { h: "temporary", lines: ["Per-iteration"] },
        ],
        footer: "If the analyzer can’t classify it, parfor refuses",
      },
    },
    {
      q: "What sits under the MATLAB execution stack?",
      a: "Desktop JIT for .m, heavily optimized builtins (LAPACK/BLAS, FFTW), optional MEX, optional GPU (CUDA), optional generated C. Toolboxes wrap these with m-code fronts.",
      e: "A good expert map: your m-file → JIT or builtin → maybe GPU/MEX. Profiling tells you which layer you’re in. That’s how you choose vectorize vs mex vs gpuArray.",
      visual: {
        title: "Execution stack",
        kind: "layers",
        layers: [
          { h: "Your .m / classdef", lines: ["JIT candidate"] },
          { h: "Toolbox m-code", lines: ["Mostly the same"] },
          { h: "Builtins / BLAS", lines: ["Native kernels"] },
          { h: "MEX · GPU · Coder", lines: ["Escapes you opt into"] },
        ],
        footer: "Know which layer is running before you rewrite",
      },
    },
    {
      q: "When do hidden copies still happen in ‘in-place’ m-code?",
      a: "A = A + 1 is in-place only if A is uniquely referenced and the engine can reuse the buffer. Sharing, changing size/class, or passing into a function that might write can copy.",
      e: "subsasgn on objects, table variable replace, and gpuArray that must reallocate are usual surprises. Feature('RefCount') folklore is less useful than measuring with memory and the profiler.",
      visual: {
        title: "In-place or not",
        kind: "timeline",
        events: [
          { h: "Unique A", lines: ["Reuse buffer"] },
          { h: "B = A", lines: ["Now shared"] },
          { h: "A(1)=0", lines: ["Copy A"] },
          { h: "Measure", lines: ["memory / profile"] },
        ],
        footer: "Sharing is free — the next write may not be",
      },
    },
    {
      q: "How do toolboxes and codegen fit an expert architecture?",
      a: "Keep numeric kernels as functions with clear array types so they can JIT, go to GPU, or Coder later. Keep UI, tables, and handle graphs at the edges. Don’t spray toolbox calls through business logic without a wrapper.",
      e: "That’s how teams migrate a prototype: core math stays MATLAB arrays; deployment picks Coder, compiler SDK, or a MATLAB Runtime. Expert MATLAB is boundary control, not more toolboxes.",
      visual: {
        title: "Prototype to product",
        kind: "cycle",
        center: "core math",
        items: [
          { h: "arrays", lines: ["Stable types"] },
          { h: "toolboxes", lines: ["Wrapped APIs"] },
          { h: "GPU / mex", lines: ["Hot kernels"] },
          { h: "Coder", lines: ["Subset compile"] },
          { h: "Runtime", lines: ["Ship the app"] },
        ],
        footer: "Keep the math as arrays — treat toolboxes as plugins",
      },
    },
  ],
};
