module.exports = {
  name: "PHP",
  description:
    "PHP interview questions — types, OOP, Composer, requests, enums, JIT, and fibers.",
  match: /^php$/i,
  theme: {
    accent: "#777BB4",
    hubFill: "#777BB4",
    hubText: "#ffffff",
    centerFill: "#eef2ff",
    centerStroke: "#777BB4",
    label: "PHP",
  },
  beginner: [
    {
      q: "What is PHP and where does it still win?",
      a: "PHP is a server-side language built around the HTTP request. It ships with a huge web standard library and powers WordPress, Laravel, and Symfony.",
      e: "Modern PHP (8+) has types, JIT, enums, and fibers. Interviews still expect the request lifecycle: one process (or worker) handles a request, then tears down.",
      visual: {
        title: "Where PHP shows up",
        kind: "hub",
        hub: "PHP",
        nodes: [
          { h: "HTTP", lines: ["Request in, HTML out"] },
          { h: "CMS", lines: ["WordPress plugins"] },
          { h: "Laravel", lines: ["App framework"] },
          { h: "Composer", lines: ["Packagist deps"] },
          { h: "Types", lines: ["Hints since 7/8"] },
          { h: "Host", lines: ["Cheap shared + FPM"] },
        ],
        footer: "PHP is still a request-first language — that shapes every answer",
      },
    },
    {
      q: "How does PHP compare to JavaScript on the server?",
      a: "PHP’s default model is share-nothing per request. Node keeps a long-lived event loop. Both can do async now, but PHP’s muscle memory is still FPM workers.",
      e: "Use PHP when the team and host expect it. Use long-running PHP (RoadRunner, Swoole, FrankenPHP) when you need persistent workers — mention that you know the difference.",
      visual: {
        title: "Request worker vs event loop",
        kind: "compare",
        left: {
          h: "Classic PHP",
          lines: ["One request, then die", "Superglobals ready", "Easy deploy", "No shared memory"],
        },
        right: {
          h: "Node-style",
          lines: ["Process stays up", "Event loop", "Share in-process state", "Careful with leaks"],
        },
        footer: "Know both models — FPM is still the interview default",
      },
    },
    {
      q: "What is the PHP request lifecycle?",
      a: "SAPI (Apache, FPM, CLI) starts a request, PHP bootstraps, your front controller runs, output is sent, then the engine shuts the request down.",
      e: "Autoload, sessions, and output buffering all hook this cycle. In FPM, the worker may be reused — do not assume process-global state is empty unless you reset it.",
      visual: {
        title: "From hit to response",
        kind: "steps",
        steps: [
          { h: "SAPI", lines: ["FPM accepts the HTTP call"] },
          { h: "Bootstrap", lines: ["php.ini · autoload"] },
          { h: "App", lines: ["Router · controller"] },
          { h: "Shutdown", lines: ["Buffers flush · destruct"] },
        ],
        footer: "The unit of work is the request — not a forever-running VM",
      },
    },
    {
      q: "How do types work in PHP?",
      a: "PHP is dynamically typed at runtime but accepts type declarations on params, returns, properties, and class constants. Coercion depends on strict_types.",
      e: "declare(strict_types=1); makes scalar hints actually strict for that file. Union types, nullable (?T), mixed, and never are the modern vocabulary.",
      visual: {
        title: "Declare then check",
        kind: "code",
        code: {
          file: "add.php",
          code: [
            "declare(strict_types=1);",
            "function add(int $a, int $b): int {",
            "  return $a + $b;",
            "}",
            "add(1, 2);",
          ],
          notes: [
            { h: "strict", text: "File-level — not a php.ini global" },
            { h: "Hints", text: "Params and return are checked" },
            { h: "Coerce", text: "Without strict, \"1\" may become 1" },
          ],
        },
        footer: "strict_types is per file — callers in weak files still coerce",
      },
    },
    {
      q: "How do PHP arrays actually work?",
      a: "An array is an ordered map: keys may be int or string. List-style arrays use 0..n keys; associative arrays use named keys. One type does both jobs.",
      e: "foreach preserves order. array_is_list() (8.1) tells list vs map. Nested arrays are copies on assign unless you use references — that surprise is a classic bug.",
      visual: {
        title: "List and map in one type",
        kind: "cycle",
        center: "array",
        items: [
          { h: "Append", lines: ["$a[] = 1"] },
          { h: "Key", lines: ["$a['id'] = 7"] },
          { h: "foreach", lines: ["Insertion order"] },
          { h: "Copy", lines: ["Assign copies"] },
          { h: "Ref", lines: ["& to alias"] },
        ],
        footer: "PHP arrays are ordered maps — not C arrays",
      },
    },
    {
      q: "What are the layers of a PHP array value?",
      a: "A zval points at a HashTable. Packed hashtables store list data densely; mixed hashtables store string keys. Copy-on-write delays real copies until mutation.",
      e: "You do not need internals for a junior role, but “arrays are COW maps” explains why passing a huge array is cheaper than it looks until you write.",
      visual: {
        title: "Inside an array",
        kind: "layers",
        layers: [
          { h: "PHP value", lines: ["$cart = [1, 2, 3]"] },
          { h: "Copy-on-write", lines: ["Reads share the table"] },
          { h: "HashTable", lines: ["Packed list or mixed map"] },
        ],
        footer: "A write after share triggers a real copy — not every assign",
      },
    },
    {
      q: "What are superglobals?",
      a: "They are request-wide arrays: $_GET, $_POST, $_SERVER, $_SESSION, $_COOKIE, $_FILES, $_ENV, $GLOBALS. They exist without being passed in.",
      e: "Do not trust them. Frameworks wrap them in Request objects. $_REQUEST merges GET/POST/COOKIE and is usually the wrong tool.",
      visual: {
        title: "Request bags",
        kind: "timeline",
        events: [
          { h: "Arrive", lines: ["SAPI fills $_GET / $_POST"] },
          { h: "Server", lines: ["$_SERVER metadata"] },
          { h: "Files", lines: ["$_FILES uploads"] },
          { h: "App", lines: ["Read via a Request type"] },
        ],
        footer: "Superglobals are convenience — not a validated API",
      },
    },
    {
      q: "What scalar types should you name in an interview?",
      a: "int, float, string, bool, plus null, array, object, callable, iterable, resource, and mixed. void and never describe returns.",
      e: "string is a byte sequence; mbstring or unicode-safe libs handle UTF-8. float is IEEE double. int size is platform (64-bit on typical 64-bit PHP).",
      visual: {
        title: "Scalar and special types",
        kind: "hub",
        hub: "Types",
        nodes: [
          { h: "int", lines: ["Whole numbers"] },
          { h: "float", lines: ["IEEE double"] },
          { h: "string", lines: ["Byte strings"] },
          { h: "bool", lines: ["true / false"] },
          { h: "array", lines: ["Ordered map"] },
          { h: "null", lines: ["Missing on purpose"] },
        ],
        footer: "mixed means “we gave up” — prefer unions when you know the set",
      },
    },
    {
      q: "What is the difference between == and === ?",
      a: "== compares with type juggling. === is identical: same type and value. 0 == \"foo\" is a famous trap; 0 === \"foo\" is false.",
      e: "Use === in almost all application code. switch uses loose comparison unless you use match (8.0), which is strict.",
      visual: {
        title: "== vs ===",
        kind: "compare",
        left: {
          h: "== loose",
          lines: ["Juggles types", "0 == \"0\" is true", "Surprising tables", "Avoid in apps"],
        },
        right: {
          h: "=== strict",
          lines: ["Type + value", "0 === \"0\" is false", "match uses this", "Default choice"],
        },
        footer: "Loose equality is a language fossil — === is the professional default",
      },
    },
    {
      q: "How do you declare functions and return types?",
      a: "function name(Type $arg = default): ReturnType {}. Optional args, variadics (...$args), and named arguments (8.0) are all fair game.",
      e: "never means the function does not return (throw or exit). void returns no value. Union returns (int|string) need a reason, not a shrug.",
      visual: {
        title: "Function boundary",
        kind: "steps",
        steps: [
          { h: "Params", lines: ["Hint every input"] },
          { h: "Body", lines: ["No types at runtime locals"] },
          { h: "Return", lines: [": int or : void"] },
          { h: "Call", lines: ["Named args if helpful"] },
        ],
        footer: "Types on the signature — inference is not TypeScript here",
      },
    },
    {
      q: "How do classes work at a beginner level?",
      a: "class names a type. new constructs. Properties and methods live on the instance; static belongs to the class. constructor is __construct.",
      e: "Visibility: public, protected, private. PHP 8 constructor property promotion cuts boilerplate. Know $this vs self:: vs static:: (late static binding).",
      visual: {
        title: "A small class",
        kind: "code",
        code: {
          file: "user.php",
          code: [
            "class User {",
            "  public function __construct(",
            "    public string $name,",
            "  ) {}",
            "  public function greet(): string {",
            "    return \"hi {$this->name}\";",
            "  }",
            "}",
          ],
          notes: [
            { h: "Promote", text: "Constructor args become properties" },
            { h: "this", text: "Instance pointer inside methods" },
            { h: "Hint", text: "string on $name is enforced" },
          ],
        },
        footer: "Promotion is sugar — it still defines a real property",
      },
    },
    {
      q: "How do include, require, and autoload relate?",
      a: "include/require pull a file now. require_once avoids double include. Composer’s PSR-4 autoload loads a class file when the class is first used.",
      e: "Modern apps almost never scatter require. spl_autoload_register is the hook; Composer generates vendor/autoload.php. Missing class = fatal unless you catch in 8? still Error.",
      visual: {
        title: "From require to autoload",
        kind: "cycle",
        center: "class",
        items: [
          { h: "Use", lines: ["new Foo\\Bar"] },
          { h: "Autoload", lines: ["PSR-4 map"] },
          { h: "File", lines: ["src/Bar.php"] },
          { h: "Define", lines: ["class is loaded"] },
          { h: "Fail", lines: ["Error if missing"] },
        ],
        footer: "Autoload is lazy require — Composer owns the map",
      },
    },
    {
      q: "What do public, protected, and private mean?",
      a: "public is callable from anywhere. protected is class + children. private is that class only (not subclasses). Same words as Java, different culture around getters.",
      e: "PHP 8.3+ has typed class constants and more readonly. Asymmetric visibility (8.4) is a follow-up if they ask “what’s new.” Keep properties private by default.",
      visual: {
        title: "Visibility layers",
        kind: "layers",
        layers: [
          { h: "public", lines: ["Anyone may read or call"] },
          { h: "protected", lines: ["This class and subclasses"] },
          { h: "private", lines: ["Only this class body"] },
          { h: "readonly", lines: ["Set once in constructor"] },
        ],
        footer: "Default to private properties — widen when a subclass truly needs it",
      },
    },
    {
      q: "What does Composer do in a typical install?",
      a: "composer.json lists packages and PSR-4 maps. composer install reads composer.lock and fills vendor/. autoload.php is the one require your app needs.",
      e: "composer update changes the lockfile. --no-dev for production. Know packagist, semantic versions, and why you commit the lockfile for apps.",
      visual: {
        title: "Composer install path",
        kind: "timeline",
        events: [
          { h: "json", lines: ["Require packages"] },
          { h: "lock", lines: ["Pin exact versions"] },
          { h: "install", lines: ["Fill vendor/"] },
          { h: "autoload", lines: ["One require in index"] },
        ],
        footer: "Apps commit composer.lock — libraries usually do not pin as hard",
      },
    },
    {
      q: "How do you think about strings, numbers, and casting?",
      a: "Casts are (int), (string), (array). Interpolation uses \"{$name}\". Heredoc/nowdoc for long text. (int) \"12abc\" is 12 — another juggling trap.",
      e: "filter_var and dedicated parsers beat casual casts for input. JSON uses json_encode flags. Binary vs text is your problem; PHP will not guess UTF-8 validity.",
      visual: {
        title: "Values you will cast",
        kind: "hub",
        hub: "Cast",
        nodes: [
          { h: "(int)", lines: ["Truncate strings"] },
          { h: "(string)", lines: ["__toString"] },
          { h: "(bool)", lines: ["0 and \"\" are false"] },
          { h: "(array)", lines: ["Wrap scalars"] },
          { h: "json", lines: ["encode / decode"] },
          { h: "filter", lines: ["Validate input"] },
        ],
        footer: "Casts coerce — validators reject; use the second for HTTP input",
      },
    },
  ],
  intermediate: [
    {
      q: "How do namespaces work in PHP?",
      a: "namespace Vendor\\Pkg; groups names. use imports. A leading \\ is global. Class Bar in Foo is Foo\\Bar, not a nested type system.",
      e: "unqualified functions fall back to global if missing in the namespace (the infamous fallback). Fully qualify or use function strlen. PSR-4 maps the first parts to folders.",
      visual: {
        title: "Namespace import",
        kind: "code",
        code: {
          file: "src/User.php",
          code: [
            "namespace App\\Domain;",
            "use App\\Support\\Clock;",
            "class User {",
            "  public function __construct(",
            "    private Clock $clock,",
            "  ) {}",
            "}",
          ],
          notes: [
            { h: "ns", text: "File declares its namespace" },
            { h: "use", text: "Short name Clock in this file" },
            { h: "PSR-4", text: "App\\Domain\\User → src/User.php" },
          ],
        },
        footer: "Namespaces are prefixes — they are not Java packages at runtime",
      },
    },
    {
      q: "How does PSR-4 autoloading resolve a class?",
      a: "Composer maps a prefix (App\\) to a directory (src/). The remaining namespace becomes a path. Class App\\Http\\Kernel loads src/Http/Kernel.php.",
      e: "Class name must match the file name. Dump-autoload -o optimizes a classmap for prod. classmap also covers non-PSR files you list explicitly.",
      visual: {
        title: "PSR-4 resolution",
        kind: "steps",
        steps: [
          { h: "new App\\Http\\Kernel", lines: ["Class not loaded yet"] },
          { h: "Prefix", lines: ["App\\ → src/"] },
          { h: "Path", lines: ["src/Http/Kernel.php"] },
          { h: "require", lines: ["Define the class"] },
        ],
        footer: "Mismatch between class and path is a fatal “class not found”",
      },
    },
    {
      q: "Abstract class vs interface vs trait?",
      a: "Interfaces are contracts (can implement many). Abstract classes can hold state and partial impls (single inheritance). Traits are copy-paste mixins with conflict rules.",
      e: "Prefer interfaces for type hints. Traits for reuse without a parent. insteadof / as resolve trait collisions. PHP has no multiple class inheritance.",
      visual: {
        title: "Reuse tools",
        kind: "compare",
        left: {
          h: "interface / abstract",
          lines: ["interface = many", "abstract = one parent", "Type-hint the contract", "Can have constants"],
        },
        right: {
          h: "trait",
          lines: ["Horizontal reuse", "Not a type by itself", "Conflict operators", "May hold properties"],
        },
        footer: "Hint interfaces — use traits when inheritance is the wrong shape",
      },
    },
    {
      q: "What are the OOP tools PHP interviews expect?",
      a: "Inheritance, interfaces, traits, magic methods (__get, __call), late static binding (static::), cloning, and comparison (== vs === on objects).",
      e: "=== on objects is identity. == is property-wise for the same class. Magic methods are slow and hide bugs — frameworks use them; you should be cautious.",
      visual: {
        title: "OOP map",
        kind: "hub",
        hub: "OOP",
        nodes: [
          { h: "extends", lines: ["One parent"] },
          { h: "implements", lines: ["Many interfaces"] },
          { h: "trait", lines: ["Mix in methods"] },
          { h: "static::", lines: ["Late binding"] },
          { h: "__construct", lines: ["Create"] },
          { h: "__destruct", lines: ["Teardown"] },
        ],
        footer: "Magic methods are part of the language — not a design goal",
      },
    },
    {
      q: "How do exceptions work?",
      a: "throw new Exception. try / catch / finally. Throwable is the root (Error + Exception). Multiple catch types can be combined with | .",
      e: "Do not catch Throwable unless you rethrow or truly handle fatals. Domain exceptions vs RuntimeException is a design choice. finally runs on return too.",
      visual: {
        title: "Throw then catch",
        kind: "timeline",
        events: [
          { h: "throw", lines: ["Unwind the stack"] },
          { h: "catch", lines: ["Match the type"] },
          { h: "finally", lines: ["Always runs"] },
          { h: "Uncaught", lines: ["Error handler / 500"] },
        ],
        footer: "Error is for engine failures — Exception is for your domain",
      },
    },
    {
      q: "How do traits compose into a class?",
      a: "use TraitName inside the class. Methods flatten into the class. If two traits collide, insteadof picks a winner; as aliases a method.",
      e: "Trait properties must be compatible. Precedence: class method > trait > parent. Traits are not types — you cannot type-hint a trait.",
      visual: {
        title: "Flatten a trait",
        kind: "layers",
        layers: [
          { h: "Class methods", lines: ["Win over trait methods"] },
          { h: "Trait body", lines: ["Copied into the class"] },
          { h: "Parent class", lines: ["Still under the child"] },
        ],
        footer: "A trait is compile-time copy — not a runtime parent",
      },
    },
    {
      q: "What are generators?",
      a: "A function with yield returns a Generator. It is lazy: each foreach step resumes until the next yield. yield from delegates to another iterable.",
      e: "Generators implement Iterator. They save memory on large datasets. They are not async by themselves — fibers/coroutines are a different feature.",
      visual: {
        title: "yield then resume",
        kind: "cycle",
        center: "yield",
        items: [
          { h: "Call", lines: ["Get a Generator"] },
          { h: "foreach", lines: ["Resume the fn"] },
          { h: "yield", lines: ["Pause with a value"] },
          { h: "Next", lines: ["Run to next yield"] },
          { h: "return", lines: ["getReturn()"] },
        ],
        footer: "Generators are lazy iterators — not threads",
      },
    },
    {
      q: "What are typed properties and constructor promotion?",
      a: "Typed properties (7.4) must match their type once initialized. Promotion (8.0) declares them in __construct. uninitialized typed properties error on read.",
      e: "readonly properties (8.1) can be set once. Combining promotion + readonly is the modern DTO style. Avoid public mutable typed fields on services.",
      visual: {
        title: "Typed property",
        kind: "code",
        code: {
          file: "dto.php",
          code: [
            "final class UserId {",
            "  public function __construct(",
            "    public readonly int $value,",
            "  ) {}",
            "}",
            "$id = new UserId(42);",
          ],
          notes: [
            { h: "Type", text: "int is checked on write" },
            { h: "readonly", text: "No second assignment" },
            { h: "Promote", text: "Arg is the property" },
          ],
        },
        footer: "Uninitialized typed properties throw on read — they are not null",
      },
    },
    {
      q: "How do you wire dependencies in PHP apps?",
      a: "Constructor injection is the default. A container (PHP-DI, Symfony, Laravel) resolves type-hints. Do not new your database inside a controller.",
      e: "PSR-11 is the container interface. Service locators are a smell if they hide the graph. Factories for things that need runtime args.",
      visual: {
        title: "Inject, do not hunt",
        kind: "steps",
        steps: [
          { h: "Hint", lines: ["Logger $log in construct"] },
          { h: "Bind", lines: ["Container maps the type"] },
          { h: "Resolve", lines: ["Build the graph"] },
          { h: "Call", lines: ["Controller stays thin"] },
        ],
        footer: "If you need the container in domain code, the design leaked",
      },
    },
    {
      q: "When is a PHP array the wrong collection?",
      a: "Arrays are fine until you need objects, uniqueness, or typed lists. SplObjectStorage, Ds extension, or collections (Laravel, Doctrine) document intent.",
      e: "Passing list<User> in Psalm/PHPStan is a static overlay — runtime is still array. Know array_is_list, unpacking [...$a], and the cost of copies.",
      visual: {
        title: "array vs object collections",
        kind: "compare",
        left: {
          h: "array",
          lines: ["Language built-in", "List or map", "COW copies", "No element type"],
        },
        right: {
          h: "Collection type",
          lines: ["Named API", "Can wrap invariants", "Easier static types", "Extra objects"],
        },
        footer: "Start with array — graduate when the domain needs a name",
      },
    },
    {
      q: "What should you know about Composer beyond install?",
      a: "scripts, repositories (VCS/path), platform php version, conflict, replace, and --ignore-platform-reqs as a last resort. plugins can run code on install.",
      e: "Lockfile + CI. Audit with composer audit. Private Satis/Packagist. Know why you pin ext-json in platform when building Docker images.",
      visual: {
        title: "Composer beyond vendor/",
        kind: "hub",
        hub: "Composer",
        nodes: [
          { h: "scripts", lines: ["post-install hooks"] },
          { h: "platform", lines: ["php / ext versions"] },
          { h: "audit", lines: ["Known CVEs"] },
          { h: "path repo", lines: ["Monorepo packages"] },
          { h: "classmap", lines: ["Prod optimize"] },
          { h: "plugins", lines: ["Installer code"] },
        ],
        footer: "Composer is the supply chain — treat lockfiles as build inputs",
      },
    },
    {
      q: "How do sessions and cookies fit a request?",
      a: "session_start() loads $_SESSION from a store (files, Redis). Cookies are Set-Cookie headers. Session IDs usually live in a cookie.",
      e: "session_regenerate_id on login. SameSite, HttpOnly, Secure flags. PHP’s default file sessions fail on multi-server without sticky sessions or a shared store.",
      visual: {
        title: "Cookie then session",
        kind: "timeline",
        events: [
          { h: "Request", lines: ["Cookie: PHPSESSID"] },
          { h: "Start", lines: ["Load the bag"] },
          { h: "Write", lines: ["$_SESSION['user']"] },
          { h: "Response", lines: ["Set-Cookie if needed"] },
        ],
        footer: "Sessions are server state keyed by a client cookie",
      },
    },
    {
      q: "How should you talk to SQL from PHP?",
      a: "PDO with prepared statements. Bind values, never concatenate user input. One connection per request in FPM is normal; persistent connections are a trade-off.",
      e: "ERRMODE_EXCEPTION. Transactions with beginTransaction. ORMs (Eloquent, Doctrine) sit on top — still know PDO for interviews and debugging.",
      visual: {
        title: "PDO layers",
        kind: "layers",
        layers: [
          { h: "SQL API", lines: ["Domain queries / ORM"] },
          { h: "PDO", lines: ["prepare · execute · fetch"] },
          { h: "Driver", lines: ["pgsql · mysql · sqlite"] },
          { h: "Database", lines: ["Plans and locks"] },
        ],
        footer: "Prepared statements are the baseline — not an optimization",
      },
    },
    {
      q: "How do iterators and Traversable show up?",
      a: "foreach works on arrays and Traversable. Iterator is the full cursor. IteratorAggregate returns another iterator. generators implement Iterator.",
      e: "Countable and ArrayAccess make objects feel like arrays. Do not implement them just for cleverness. DirectoryIterator is the SPL example people forget exists.",
      visual: {
        title: "foreach anything Traversable",
        kind: "cycle",
        center: "foreach",
        items: [
          { h: "array", lines: ["Native loop"] },
          { h: "Iterator", lines: ["rewind · valid · next"] },
          { h: "Aggregate", lines: ["getIterator()"] },
          { h: "Generator", lines: ["yield cursor"] },
          { h: "SPL", lines: ["DirectoryIterator"] },
        ],
        footer: "Traversable is the foreach contract — Iterator is the cursor API",
      },
    },
    {
      q: "What are PHP 8.1 enums?",
      a: "enum Status { case Ok; case Err; } is a typed set of cases. Backed enums have string|int values. They can implement interfaces and have methods.",
      e: "Enums are objects, not C integers. tryFrom vs from. They replace magic strings in domain code. Cannot be new’d; cases are singletons.",
      visual: {
        title: "Backed enum",
        kind: "code",
        code: {
          file: "status.php",
          code: [
            "enum Status: string {",
            "  case Ok = 'ok';",
            "  case Err = 'err';",
            "  public function label(): string {",
            "    return $this->value;",
            "  }",
            "}",
            "Status::from('ok');",
          ],
          notes: [
            { h: "Backed", text: ": string stores a value" },
            { h: "from", text: "Throws if the value is unknown" },
            { h: "Methods", text: "Cases can share behavior" },
          ],
        },
        footer: "Enums are objects with a closed set of instances",
      },
    },
  ],
  expert: [
    {
      q: "How do OPcache and JIT fit together?",
      a: "PHP compiles to opcodes. OPcache caches them across requests. JIT (8.0+) can compile hot opcodes to machine code, mainly for CPU-heavy loops.",
      e: "Most web apps are IO-bound; JIT is not a silver bullet. opcache.jit and jit_buffer_size are the knobs. CLI/FPM differ in warmup. Measure, do not assume.",
      visual: {
        title: "From source to machine code",
        kind: "layers",
        layers: [
          { h: "PHP source", lines: [".php files on disk"] },
          { h: "Opcodes", lines: ["Zend VM instructions"] },
          { h: "OPcache", lines: ["Shared memory across requests"] },
          { h: "JIT", lines: ["Hot traces → native"] },
        ],
        footer: "OPcache is mandatory in prod — JIT is optional and workload-specific",
      },
    },
    {
      q: "What happens from request to a JIT’d loop?",
      a: "Worker starts, OPcache may already hold opcodes, the VM runs, counters mark hot code, JIT emits native, later requests hit the faster path.",
      e: "First request after deploy is cold. preload (7.4) can load classes at FPM start. Long-running servers (FrankenPHP) change the warmup story.",
      visual: {
        title: "Warmup timeline",
        kind: "timeline",
        events: [
          { h: "Compile", lines: ["Source → opcodes"] },
          { h: "Cache", lines: ["OPcache shared mem"] },
          { h: "Profile", lines: ["Hot counters"] },
          { h: "JIT", lines: ["Emit native code"] },
        ],
        footer: "JIT needs time and CPU-heavy code — your CRUD app may never heat up",
      },
    },
    {
      q: "What are fibers (PHP 8.1)?",
      a: "A Fiber is a stackful coroutine you can suspend and resume. It is a primitive — AMPHP and Revolt build event loops on top. It is not a thread.",
      e: "Fiber::suspend() yields to the caller of start/resume. Blocking IO still blocks the process unless the library uses non-blocking IO plus a scheduler.",
      visual: {
        title: "Fiber as a coroutine",
        kind: "hub",
        hub: "Fiber",
        nodes: [
          { h: "start", lines: ["Run until suspend"] },
          { h: "suspend", lines: ["Yield a value"] },
          { h: "resume", lines: ["Continue the stack"] },
          { h: "Scheduler", lines: ["Event loop library"] },
          { h: "IO", lines: ["Must be non-blocking"] },
          { h: "Not OS", lines: ["Same thread"] },
        ],
        footer: "Fibers switch stacks — they do not create OS threads",
      },
    },
    {
      q: "Fibers vs generators — what is the real difference?",
      a: "Generators are shallow: yield only from that function. Fibers have a full call stack; any nested call can Fiber::suspend(). That is why async IO libraries want fibers.",
      e: "You cannot await through arbitrary stack frames with generators without coloring every function. Fibers remove that coloring at the VM level.",
      visual: {
        title: "Generator vs Fiber",
        kind: "compare",
        left: {
          h: "Generator",
          lines: ["yield in one function", "Iterator API", "No nested suspend", "Great for lazy lists"],
        },
        right: {
          h: "Fiber",
          lines: ["Full stack switch", "start / resume", "Nested suspend OK", "Async runtimes"],
        },
        footer: "Generators iterate — fibers multiplex a call stack",
      },
    },
    {
      q: "What does a fiber look like in code?",
      a: "new Fiber(fn). start() begins it. Fiber::suspend($v) returns $v to the resumer. resume($x) sends $x back as suspend’s result.",
      e: "Uncaught exceptions in a fiber surface on resume. Nested fibers exist but are easy to get wrong — use a framework scheduler in production.",
      visual: {
        title: "Suspend and resume",
        kind: "code",
        code: {
          file: "fiber.php",
          code: [
            "$f = new Fiber(function () {",
            "  $x = Fiber::suspend('a');",
            "  return $x;",
            "});",
            "$f->start(); // 'a'",
            "$f->resume(1);",
          ],
          notes: [
            { h: "start", text: "Runs until first suspend" },
            { h: "suspend", text: "Hands 'a' back to caller" },
            { h: "resume", text: "1 becomes $x in the fiber" },
          ],
        },
        footer: "The Fiber object is the handle — the closure is the stack",
      },
    },
    {
      q: "How would you structure async PHP with fibers?",
      a: "Use a loop (Revolt) that polls sockets, resumes waiting fibers, and never calls blocking fread on the main worker. HTTP clients must be fiber-aware.",
      e: "Mixing PDO (blocking) with fibers stalls everyone on that worker. Expert answer: color the IO layer, keep CPU short, or run blocking work in a pool.",
      visual: {
        title: "Scheduler over fibers",
        kind: "steps",
        steps: [
          { h: "Await IO", lines: ["Register socket"] },
          { h: "suspend", lines: ["Yield the fiber"] },
          { h: "Event", lines: ["Loop sees readability"] },
          { h: "resume", lines: ["Continue the request"] },
        ],
        footer: "A fiber without a non-blocking scheduler is just a fancy goto",
      },
    },
    {
      q: "How does PHP garbage collection work?",
      a: "Refcounting frees values at zero. Cycles (A→B→A) never hit zero, so a cyclic collector periodically finds them. This is why you still hear “unset and cycles.”",
      e: "gc_disable in short CLI scripts can matter. Long-running workers must watch memory_get_usage. Resources and circular object graphs are the usual leaks.",
      visual: {
        title: "Refcount then cycle GC",
        kind: "cycle",
        center: "GC",
        items: [
          { h: "New", lines: ["refcount = 1"] },
          { h: "Assign", lines: ["Increment"] },
          { h: "Unscope", lines: ["Decrement"] },
          { h: "Zero", lines: ["Free now"] },
          { h: "Cycle", lines: ["Collector sweep"] },
        ],
        footer: "Refcount is the fast path — the cycle collector is the safety net",
      },
    },
    {
      q: "What should you know about zvals and copy-on-write?",
      a: "Every PHP value is a zval: type tag, refcount, and payload. Arrays and strings are COW. References (&) break COW and create aliasing.",
      e: "foreach by value on arrays uses COW; foreach by & is the mutation trap. interned strings and immutable arrays (8.3) are further internals topics.",
      visual: {
        title: "zval layers",
        kind: "layers",
        layers: [
          { h: "PHP variable", lines: ["$a = [1, 2]"] },
          { h: "zval", lines: ["Type · refcount · value"] },
          { h: "COW buffer", lines: ["Share until a write"] },
          { h: "& alias", lines: ["Two names, one zval"] },
        ],
        footer: "References and COW fight — avoid & unless you mean aliasing",
      },
    },
    {
      q: "How do you run PHP in production with OPcache?",
      a: "Enable OPcache, validate timestamps off in prod (deploy = restart), enough memory, interned string buffer, and optionally preload. FPM pool sizes match CPU and IO.",
      e: "opcache_reset is a blunt tool. Blue/green or rolling FPM reload after deploy. JIT off unless you measured a win. Realpath cache matters on NFS.",
      visual: {
        title: "Prod opcode path",
        kind: "timeline",
        events: [
          { h: "Deploy", lines: ["New files on disk"] },
          { h: "Reload", lines: ["FPM workers restart"] },
          { h: "Warm", lines: ["OPcache fills"] },
          { h: "Serve", lines: ["No recompile"] },
        ],
        footer: "In prod, OPcache should not stat every request",
      },
    },
    {
      q: "What concurrency options exist in PHP?",
      a: "FPM process pool, pcntl forks (CLI), pthreads (not typical), parallel extension, ReactPHP/AMPHP fibers, Swoole/Swow, RoadRunner, FrankenPHP worker mode.",
      e: "The honest default is still “scale out with processes.” In-process concurrency needs a runtime that is not stock FPM. Share state via Redis, not $GLOBALS.",
      visual: {
        title: "Concurrency map",
        kind: "hub",
        hub: "Scale",
        nodes: [
          { h: "FPM", lines: ["Process per worker"] },
          { h: "Fork", lines: ["pcntl CLI"] },
          { h: "Fibers", lines: ["Coop async"] },
          { h: "Swoole", lines: ["Long-lived server"] },
          { h: "RoadRunner", lines: ["Go supervisor"] },
          { h: "Queue", lines: ["Jobs off-request"] },
        ],
        footer: "PHP scales with processes first — in-process async is a chosen runtime",
      },
    },
    {
      q: "Classic FPM vs long-running PHP — how do you choose?",
      a: "FPM is simple, leak-tolerant (workers die), and host-friendly. Long-running servers keep boot, ORM metadata, and connections warm — faster, but you must not leak.",
      e: "Memory leaks, in-process caches, and “static” state become bugs. Expert teams add worker max-request restarts even in worker mode.",
      visual: {
        title: "FPM vs worker server",
        kind: "compare",
        left: {
          h: "php-fpm",
          lines: ["Share-nothing request", "Leaks die with worker", "Easy hosting", "Cold boot each time"],
        },
        right: {
          h: "Worker mode",
          lines: ["Keep the app booted", "Must hunt leaks", "Needs a supervisor", "Great for APIs"],
        },
        footer: "Worker mode is a performance bet — FPM is an isolation bet",
      },
    },
    {
      q: "What are readonly classes, WeakMap, and other 8.x internals-adjacent features?",
      a: "readonly class (8.2) makes every property readonly. WeakMap keys objects without keeping them alive. First-class callables (...). Disjunctive normal form types.",
      e: "WeakMap is the cache-on-object pattern without leaks. readonly + clone got refinements in 8.3. Mention these when asked “what’s new since 7.4.”",
      visual: {
        title: "WeakMap cache",
        kind: "code",
        code: {
          file: "weak.php",
          code: [
            "$map = new WeakMap();",
            "$obj = new stdClass();",
            "$map[$obj] = 'meta';",
            "unset($obj);",
            "// entry is gone",
          ],
          notes: [
            { h: "Weak", text: "Key does not pin the object" },
            { h: "GC", text: "When obj dies, entry dies" },
            { h: "Use", text: "Memoize without leaks" },
          ],
        },
        footer: "WeakMap is how you attach data without extending the class",
      },
    },
    {
      q: "How does FFI work in PHP?",
      a: "The FFI extension loads C libraries and calls them from PHP with declared headers. Useful for thin native wrappers without writing an extension in C.",
      e: "Still unsafe: bad pointers crash the worker. Not for shared hosting. For hot paths, a real extension or Go sidecar may be cleaner. preload + FFI has constraints.",
      visual: {
        title: "Call C from PHP",
        kind: "steps",
        steps: [
          { h: "cdef", lines: ["Declare the C API"] },
          { h: "load", lines: ["Shared library"] },
          { h: "call", lines: ["FFI::cdef functions"] },
          { h: "own", lines: ["Who frees memory?"] },
        ],
        footer: "FFI is a sharp tool — a crash is a worker crash",
      },
    },
    {
      q: "How does autoload interact with opcodes and preload?",
      a: "First hit of a class may autoload a file, compile, and cache. preload compiles a set of files at FPM start into the parent process so workers inherit opcodes.",
      e: "Preloaded files cannot be redeclared. Composer’s preload hints exist but are tricky with mutable apps. Expert deploys treat preload as part of the artifact.",
      visual: {
        title: "First use vs preload",
        kind: "cycle",
        center: "class",
        items: [
          { h: "Miss", lines: ["Not in memory"] },
          { h: "Autoload", lines: ["Find the file"] },
          { h: "Compile", lines: ["Opcodes + OPcache"] },
          { h: "Hit", lines: ["Later requests"] },
          { h: "Preload", lines: ["Load at FPM start"] },
        ],
        footer: "Preload moves autoload cost to worker spawn — not to the first click",
      },
    },
    {
      q: "What does the Zend engine do with your code?",
      a: "Lexer/parser → AST → opcodes → VM (or JIT). Extensions hook the engine (observers in 8). The executor runs opcodes against a stack of zvals.",
      e: "You rarely write opcodes, but xdebug, blackfire, and opcache dump make this real. Observer API is how modern profilers attach without rewriting the VM.",
      visual: {
        title: "Zend pipeline",
        kind: "layers",
        layers: [
          { h: "AST", lines: ["nikic/php-parser shape"] },
          { h: "Opcodes", lines: ["ZEND_ECHO · ZEND_DO_FCALL"] },
          { h: "Executor", lines: ["VM loop over zvals"] },
          { h: "Extensions", lines: ["Hooks · observers · JIT"] },
        ],
        footer: "PHP is a VM language — FPM just hosts that VM per request",
      },
    },
  ],
};
