module.exports = {
  name: "R",
  description:
    "R interview questions — vectors, data frames, tidyverse, environments, and object systems.",
  match: /^r$/i,
  theme: {
    accent: "#276DC3",
    hubFill: "#276DC3",
    hubText: "#ffffff",
    centerFill: "#dbeafe",
    centerStroke: "#276DC3",
    label: "R",
  },
  beginner: [
    {
      q: "What is R and where is it used?",
      a: "R is a language and environment for statistics, data analysis, and graphics. It shines in research, biostats, finance, and any workflow that is matrix- and data-frame-centric.",
      e: "CRAN packages and the tidyverse made it a default for analysts. Production services often wrap R (Plumber, targets) or rewrite hot paths — know both the interactive and package worlds.",
      visual: {
        title: "Where R shows up",
        kind: "hub",
        hub: "R",
        nodes: [
          { h: "Stats", lines: ["Models · tests"] },
          { h: "Graphics", lines: ["ggplot2 · base"] },
          { h: "Data wrangle", lines: ["dplyr · data.table"] },
          { h: "Reports", lines: ["R Markdown · Quarto"] },
          { h: "Research", lines: ["CRAN · Bioconductor"] },
          { h: "APIs", lines: ["Plumber · shiny"] },
        ],
        footer: "Interactive first — packages and APIs when you ship",
      },
    },
    {
      q: "What is an atomic vector in R?",
      a: "Atomic vectors are homogeneous 1D sequences: logical, integer, double, character, complex, or raw. c() concatenates; length() and typeof() describe them.",
      e: "Almost everything is a vector — even a scalar is length 1. Mixing types coerces (logical < integer < double < character). Lists are recursive, not atomic.",
      visual: {
        title: "Atomic vs list",
        kind: "compare",
        left: {
          h: "Atomic vector",
          lines: ["One type throughout", "c(1, 2, 3)", "typeof() is double", "Fast contiguous data"],
        },
        right: {
          h: "List",
          lines: ["Elements can differ", "list(1, 'a', TRUE)", "Recursive containers", "data.frame columns live here"],
        },
        footer: "A data.frame is a list of equal-length vectors",
      },
    },
    {
      q: "How do you create and inspect vectors?",
      a: "Use c(), :, seq(), and rep(). Inspect with length, typeof, class, str, and summary. Integers need an L suffix (1L) or they are doubles.",
      e: "is.numeric is TRUE for both integer and double. Named vectors use names(x) <- or c(a = 1). Attributes (names, dim) ride along without changing typeof.",
      visual: {
        title: "Build a vector",
        kind: "code",
        code: {
          file: "vec.R",
          code: [
            "x <- c(1L, 2L, 3L)",
            "y <- seq(0, 1, by = 0.5)",
            "z <- rep('a', 3)",
            "typeof(x)  # integer",
          ],
          notes: [
            { h: "L suffix", text: "1L is integer; 1 is double" },
            { h: "seq / rep", text: "Generate regular sequences" },
            { h: "typeof", text: "Storage type, not S3 class" },
          ],
        },
        footer: "Scalars are just length-1 vectors",
      },
    },
    {
      q: "What is vector recycling?",
      a: "When two vectors differ in length, R repeats the shorter one to match the longer (with a warning if lengths are not multiples).",
      e: "Recycling makes  x + 1  work. Silent mismatch bugs happen in ifelse and dplyr if you assume Python-style broadcasting. Prefer explicit rep or dplyr::if_else checks.",
      visual: {
        title: "Recycling in action",
        kind: "steps",
        steps: [
          { h: "Long vector", lines: ["c(1, 2, 3, 4)"] },
          { h: "Short vector", lines: ["c(10, 20)"] },
          { h: "Recycle short", lines: ["10, 20, 10, 20"] },
          { h: "Operate", lines: ["Element-wise +"] },
        ],
        footer: "Warning if length is not a multiple — still a result",
      },
    },
    {
      q: "How does a data.frame differ from a matrix?",
      a: "A matrix is one atomic type with a dim attribute. A data.frame is a list of equal-length vectors (columns) that can have mixed types, plus row names.",
      e: "Numeric linear algebra wants matrices. Tabular data with factors and strings wants data.frames (or tibbles). as.matrix() on a mixed frame coerces everything to character.",
      visual: {
        title: "matrix vs data.frame",
        kind: "compare",
        left: {
          h: "matrix",
          lines: ["Single typeof", "Fast linear algebra", "dim + dimnames", "No mixed columns"],
        },
        right: {
          h: "data.frame",
          lines: ["List of columns", "Mixed types OK", "row.names", "The analyst default"],
        },
        footer: "Use matrices for math — frames for tables",
      },
    },
    {
      q: "What are factors and why do they exist?",
      a: "A factor stores categorical data as an integer vector plus a levels attribute. Models and plotting treat levels as a finite set of categories.",
      e: "StringsAsFactors is now FALSE by default. Ordered factors encode rank. Beware: extra levels survive subsetting unless you droplevels(); character is often safer until model time.",
      visual: {
        title: "Factor internals",
        kind: "layers",
        layers: [
          { h: "Display", lines: ["'low' 'mid' 'low'"] },
          { h: "Integer codes", lines: ["1  2  1"] },
          { h: "levels attribute", lines: ["c('low', 'mid')"] },
          { h: "class", lines: ["factor (optionally ordered)"] },
        ],
        footer: "Looks like text — stored as integers plus levels",
      },
    },
    {
      q: "How do you index vectors and data.frames?",
      a: "R is 1-based. [ keeps the container type; [[ extracts one element; $ is named list/frame shorthand. Negative integers drop positions.",
      e: "df[1] is a one-column data.frame; df[[1]] or df$col is the vector. Logical indexes recycle. Never use df[,1] if you need a frame — drop=TRUE surprises.",
      visual: {
        title: "Three extractors",
        kind: "code",
        code: {
          file: "index.R",
          code: [
            "x <- c(a = 10, b = 20)",
            "x[1]      # named vector",
            "x[['a']]  # 10",
            "df$b      # column vector",
          ],
          notes: [
            { h: "[", text: "Subset; result often same type" },
            { h: "[[", text: "Pull one element out" },
            { h: "$", text: "Named column / list field" },
          ],
        },
        footer: "1-based — x[0] is empty, not the first item",
      },
    },
    {
      q: "How do packages get installed and loaded?",
      a: "install.packages puts code on disk. library() attaches a package to the search path; require() does the same but returns a logical (better inside functions).",
      e: "Prefer pkg::fun in packages to avoid masking. renv/packrat lock versions. NAMESPACE controls what a package exports — attaching is optional.",
      visual: {
        title: "From CRAN to search()",
        kind: "timeline",
        events: [
          { h: "install.packages", lines: ["Download + build"] },
          { h: "library(pkg)", lines: ["Attach to search path"] },
          { h: "pkg::fun()", lines: ["Call without attaching"] },
          { h: "Conflicts", lines: ["Later packages mask names"] },
        ],
        footer: "library is for scripts — :: is for packages",
      },
    },
    {
      q: "What is the apply family at a glance?",
      a: "apply/lapply/sapply/vapply/mapply/tapply loop over margins or lists without an explicit for. They return different shapes — that is the interview trap.",
      e: "lapply always returns a list. sapply simplifies (unpredictably). vapply needs a template — prefer it. purrr::map is the tidyverse cousin with consistent output.",
      visual: {
        title: "apply-family loop",
        kind: "cycle",
        center: "apply",
        items: [
          { h: "apply", lines: ["Matrix margins"] },
          { h: "lapply", lines: ["List → list"] },
          { h: "sapply", lines: ["Try to simplify"] },
          { h: "vapply", lines: ["Typed template"] },
          { h: "mapply", lines: ["Multiple args"] },
          { h: "tapply", lines: ["Ragged by factor"] },
        ],
        footer: "Prefer vapply or purrr::map when shape must be stable",
      },
    },
    {
      q: "What are NA, NaN, and NULL in R?",
      a: "NA is a missing value that exists inside vectors. NaN is not-a-number from invalid float ops. NULL is the absence of an object (length 0, no type payload).",
      e: "NA is typed (NA_integer_). is.na() vs is.null() vs is.nan(). Logical ops with NA yield NA — use %in% and na.rm=TRUE deliberately. NULL indexing drops elements.",
      visual: {
        title: "Missingness map",
        kind: "hub",
        hub: "Empty?",
        nodes: [
          { h: "NA", lines: ["Missing in data"] },
          { h: "NaN", lines: ["0/0 style float"] },
          { h: "NULL", lines: ["No object"] },
          { h: "Na", lines: ["Not a thing"] },
          { h: "Inf", lines: ["Overflow float"] },
          { h: "''", lines: ["Empty string"] },
        ],
        footer: "NA lives in vectors — NULL means the slot is gone",
      },
    },
    {
      q: "How do you write a simple R function?",
      a: "function(args) body. The last evaluated expression is the return value; return() is optional. Arguments can have defaults and be missing().",
      e: "Arguments are promises (lazy). You can use ... to forward. Keep functions in a package or sourced file — don’t grow a 2,000-line script.",
      visual: {
        title: "A small function",
        kind: "code",
        code: {
          file: "scale.R",
          code: [
            "rescale <- function(x, m = 0) {",
            "  (x - mean(x, na.rm = TRUE)) + m",
            "}",
            "rescale(1:4)",
          ],
          notes: [
            { h: "Last value", text: "Implicit return of the body" },
            { h: "Default", text: "m = 0 if the caller omits it" },
            { h: "Lazy args", text: "Defaults run only if needed" },
          ],
        },
        footer: "Promises mean unused args are never evaluated",
      },
    },
    {
      q: "What is copy-on-modify for beginners?",
      a: "R objects are immutable from the user’s view. Binding y <- x does not copy until one of them is modified, then R copies so the other binding is unchanged.",
      e: "This is why growing a vector in a loop (x <- c(x, i)) is slow — each append may copy. Preallocate. tracemem(x) shows when copies fire.",
      visual: {
        title: "Share then copy",
        kind: "steps",
        steps: [
          { h: "x <- 1:1e6", lines: ["One vector in memory"] },
          { h: "y <- x", lines: ["Same data, two names"] },
          { h: "y[1] <- 0", lines: ["Modify y"] },
          { h: "Copy", lines: ["x unchanged; y is new"] },
        ],
        footer: "Names are bindings — data copies on write",
      },
    },
    {
      q: "What is an environment in R?",
      a: "An environment is a hash of name → value bindings, with a parent pointer. Functions close over the environment where they were created.",
      e: "The search path is a chain of environments (globalenv, packages, baseenv, emptyenv). <<- assigns in a parent. Don’t confuse lists (copied) with environments (reference).",
      visual: {
        title: "Environment chain",
        kind: "layers",
        layers: [
          { h: "local / function env", lines: ["Bindings for this call"] },
          { h: "enclosing env", lines: ["Where the function was born"] },
          { h: "search() packages", lines: ["Attached library() packs"] },
          { h: "emptyenv()", lines: ["No parent — the root"] },
        ],
        footer: "Lexical scope follows the enclosing env, not the caller",
      },
    },
    {
      q: "What does a typical R analysis workflow look like?",
      a: "Read → tidy → transform → visualize → model → communicate. Scripts and R Markdown/Quarto capture the path; packages freeze reusable functions.",
      e: "Interviewers like hearing targets/make for pipelines and renv for lockfiles. Interactive exploration is fine; shipping needs a reproducible script.",
      visual: {
        title: "Analysis pipeline",
        kind: "timeline",
        events: [
          { h: "Import", lines: ["readr · DBI · haven"] },
          { h: "Tidy", lines: ["tidyr · janitor"] },
          { h: "Model / plot", lines: ["lm · ggplot2"] },
          { h: "Report", lines: ["Quarto · shiny"] },
        ],
        footer: "Explore in the REPL — freeze the path in a script",
      },
    },
    {
      q: "How does the tidyverse relate to base R?",
      a: "The tidyverse is a shared-grammar set of packages (dplyr, ggplot2, tidyr, readr, purrr) on top of R. Base R is the language and stats that ship with R itself.",
      e: "You need both: interviews mix [ and dplyr, lm and broom. Tibbles print nicer and don’t partial-match $; they are still data.frames underneath.",
      visual: {
        title: "Two dialects, one runtime",
        kind: "cycle",
        center: "R",
        items: [
          { h: "base", lines: ["[, lapply, lm"] },
          { h: "dplyr", lines: ["verbs + NSE"] },
          { h: "ggplot2", lines: ["layered grammar"] },
          { h: "purrr", lines: ["typed maps"] },
          { h: "data.table", lines: ["Fast by-ref"] },
        ],
        footer: "Pick a dialect per job — know how to read the other",
      },
    },
  ],
  intermediate: [
    {
      q: "When do you pick lapply, sapply, or vapply?",
      a: "lapply always returns a list. sapply tries to simplify to a vector/matrix (shape can surprise). vapply takes FUN.VALUE so the type and length are contracts.",
      e: "Use vapply in packages. sapply is fine at the console. apply is for matrices/arrays (margins). purrr::map_* is the consistent tidy alternative.",
      visual: {
        title: "Choose an *apply",
        kind: "hub",
        hub: "*apply",
        nodes: [
          { h: "lapply", lines: ["Always a list"] },
          { h: "sapply", lines: ["Simplify if it can"] },
          { h: "vapply", lines: ["Template required"] },
          { h: "apply", lines: ["Array margins"] },
          { h: "mapply", lines: ["Zip multiple"] },
          { h: "purrr", lines: ["map / map_dbl"] },
        ],
        footer: "Unstable shape is why sapply is disliked in packages",
      },
    },
    {
      q: "How does a tibble differ from a data.frame?",
      a: "A tibble is a data.frame with stricter defaults: no partial $ matching, no string→factor, [ always returns a tibble, and printing shows types and only a preview.",
      e: "as.data.frame / as_tibble convert. Some base functions (lm internals, row.names tricks) still want classic frames. Don’t fight it — convert at the boundary.",
      visual: {
        title: "data.frame vs tibble",
        kind: "compare",
        left: {
          h: "data.frame",
          lines: ["Partial $ match", "[, j] may drop", "Prints everything", "row.names matter"],
        },
        right: {
          h: "tibble",
          lines: ["$ must be exact", "[ keeps a tibble", "Preview + types", "No row names by default"],
        },
        footer: "Same list-of-columns idea — safer everyday defaults",
      },
    },
    {
      q: "How do dplyr verbs express a pipeline?",
      a: "filter, mutate, select, summarise, and arrange are NSE verbs composed with %>%. They take a data frame and return one — easy to read, easy to optimize later.",
      e: "Grouping with group_by changes summarise. across() maps a function over columns. In packages, use .data$ and {{ }} so names are not mysterious strings.",
      visual: {
        title: "A dplyr pipeline",
        kind: "code",
        code: {
          file: "verbs.R",
          code: [
            "df |>",
            "  filter(n > 0) |>",
            "  mutate(z = x / y) |>",
            "  summarise(m = mean(z))",
          ],
          notes: [
            { h: "Verbs", text: "Each step in, one frame out" },
            { h: "NSE", text: "n, x, y look like bare names" },
            { h: "Native pipe", text: "|> is R 4.1+; %>% still common" },
          ],
        },
        footer: "Readable pipelines beat nested [ calls for wrangling",
      },
    },
    {
      q: "When does copy-on-modify actually copy?",
      a: "R tracks how many names bind to an object (NAMED / refcount). A modify copies if the object might be shared. Subassign to a unique object can happen in place.",
      e: "Growing objects, changing types, and passing into closures can force copies. data.table and R6 mutate by reference on purpose. tracemem and profmem show the cost.",
      visual: {
        title: "Modify path",
        kind: "steps",
        steps: [
          { h: "Unique binding", lines: ["NAMED = 1, in-place OK"] },
          { h: "Shared", lines: ["Two names → copy first"] },
          { h: "Type change", lines: ["Always a new vector"] },
          { h: "Measure", lines: ["tracemem() · profmem"] },
        ],
        footer: "Preallocate; don’t c() inside a tight loop",
      },
    },
    {
      q: "When is base R a better fit than the tidyverse?",
      a: "Base wins for dependencies, package code that must stay light, matrices, and stats formulas. Tidyverse wins for interactive wrangling and grammar-of-graphics plots.",
      e: "data.table is a third path: fast, by-reference, terse. Interviews want you to read all three, not preach one church.",
      visual: {
        title: "tidyverse vs base",
        kind: "compare",
        left: {
          h: "tidyverse",
          lines: ["Verbs + ggplot", "Heavier deps", "NSE / tidy eval", "Great at the console"],
        },
        right: {
          h: "base R",
          lines: ["No extra packages", "[, lapply, lm", "Stable forever", "Better in slim pkgs"],
        },
        footer: "Ship base when deps hurt — explore tidy when speed of thought matters",
      },
    },
    {
      q: "How does lexical scoping find a name?",
      a: "A free name is looked up in the function’s enclosing environment, then parents, not in the caller’s frame (dynamic scope). That enclosing env is set at function creation.",
      e: "parent.frame() is the caller — useful for NSE, dangerous as a default lookup. Closures that capture huge data can pin memory until the function dies.",
      visual: {
        title: "Where a name resolves",
        kind: "layers",
        layers: [
          { h: "Function locals", lines: ["Formals + assignments"] },
          { h: "Enclosing env", lines: ["Created-with, not called-from"] },
          { h: "Parents", lines: ["Walk until emptyenv"] },
          { h: "Error", lines: ["object 'x' not found"] },
        ],
        footer: "Lexical = where the function was defined",
      },
    },
    {
      q: "What is S3 in R?",
      a: "S3 is a lightweight class system: an object gets a class attribute, and UseMethod('generic') dispatches to generic.class. There is no formal schema.",
      e: "print, summary, plot, and [ are S3 generics. NextMethod() continues the chain. Easy to extend, easy to make illegal objects — that’s the tradeoff vs S4.",
      visual: {
        title: "S3 dispatch",
        kind: "code",
        code: {
          file: "s3.R",
          code: [
            "speak <- function(x) UseMethod('speak')",
            "speak.dog <- function(x) 'woof'",
            "speak.default <- function(x) '?'",
            "speak(structure('ok', class='dog'))",
          ],
          notes: [
            { h: "generic", text: "UseMethod picks speak.class" },
            { h: "class attr", text: "Just a character vector" },
            { h: "default", text: "Fallback if no method" },
          ],
        },
        footer: "S3 is convention plus a class attribute",
      },
    },
    {
      q: "What does a package NAMESPACE do?",
      a: "NAMESPACE lists exports (what users can pkg::) and imports (what you pull from other packages). roxygen @export generates it.",
      e: "Import specific functions, not whole packages, to avoid masking. S3 methods need @export or S3method() so dispatch finds them after the package is loaded but not attached.",
      visual: {
        title: "Package boundary",
        kind: "timeline",
        events: [
          { h: "R/ code", lines: ["Your functions"] },
          { h: "roxygen", lines: ["@export · @importFrom"] },
          { h: "NAMESPACE", lines: ["Machine-readable API"] },
          { h: "Users", lines: ["pkg::fun or library"] },
        ],
        footer: "Exports are the API — internals stay unexported",
      },
    },
    {
      q: "What is non-standard evaluation (NSE)?",
      a: "NSE captures the code you typed (a symbol, a formula, an expression) instead of only its value. subset(df, x > 1) and ggplot(aes(x)) are NSE.",
      e: "Powerful at the console, hard in functions: the column name is not a string you own. Modern dplyr uses tidy eval ({{ }}, .data$col) to pass names safely.",
      visual: {
        title: "Value vs quoted code",
        kind: "cycle",
        center: "NSE",
        items: [
          { h: "Type", lines: ["filter(df, n > 0)"] },
          { h: "Capture", lines: ["Expression n > 0"] },
          { h: "Data mask", lines: ["n looks in df"] },
          { h: "Evaluate", lines: ["Logical vector"] },
          { h: "Program", lines: ["{{ col }} in fns"] },
        ],
        footer: "NSE is why dplyr feels magical — and why wrapping it needs tidy eval",
      },
    },
    {
      q: "How should you think about memory in R?",
      a: "Each vector has headers plus data; language objects (environments, closures) pin whatever they capture. gc() reports, but peak RAM is what OOMs you.",
      e: "object.size vs lobstr::obj_size (accounts for sharing). Avoid copies, remove large temps, and don’t grow lists in a loop. ALTREP can make 1:1e9 cheap until you materialize.",
      visual: {
        title: "Memory pressure",
        kind: "hub",
        hub: "RAM",
        nodes: [
          { h: "Copies", lines: ["Shared → modify"] },
          { h: "Growth", lines: ["c() in a loop"] },
          { h: "Closures", lines: ["Capture big env"] },
          { h: "Factors", lines: ["Levels never die"] },
          { h: "gc()", lines: ["Report, not magic"] },
          { h: "ALTREP", lines: ["Lazy until used"] },
        ],
        footer: "Sharing is free until a write forces a copy",
      },
    },
    {
      q: "How do formulas work with modeling functions?",
      a: "A formula y ~ x1 + x2 is a language object (class formula) with an environment. lm and friends build a model frame from it via model.matrix.",
      e: "The environment attached to the formula is where free names resolve — a classic ‘it worked in the console’ bug when you build formulas inside functions. I() protects terms.",
      visual: {
        title: "Formula to model",
        kind: "code",
        code: {
          file: "lm.R",
          code: [
            "f <- y ~ x + z",
            "class(f)      # formula",
            "environment(f)",
            "lm(f, data = df)",
          ],
          notes: [
            { h: "~", text: "Quote the model expression" },
            { h: "env", text: "Formulas carry a scope" },
            { h: "model.matrix", text: "Turns terms into columns" },
          ],
        },
        footer: "A formula is code plus the env it was created in",
      },
    },
    {
      q: "How do you wrap dplyr verbs inside a function?",
      a: "Embrace arguments with {{ var }} so a passed symbol is injected. Use .data[[name]] when the column is a string. .env$name reads from the function env.",
      e: "enquo / !! is the older rlang style. Never use get() on columns if tidy eval can do it — masking and NSE bugs follow.",
      visual: {
        title: "Pass a column in",
        kind: "steps",
        steps: [
          { h: "Caller", lines: ["mean_of(df, mpg)"] },
          { h: "Embrace", lines: ["{{ mpg }} inside"] },
          { h: "Mask", lines: ["mpg found in df"] },
          { h: "String API", lines: [".data[[name]]"] },
        ],
        footer: "{{ }} for symbols · .data[[ ]] for strings",
      },
    },
    {
      q: "What are attributes and why do they matter?",
      a: "Attributes are a named list glued onto an object (names, dim, class, levels, tsp). Many ‘types’ (matrix, factor, POSIXct) are vectors plus attributes.",
      e: "Most ops drop attributes. structure() sets them. Losing class is how a POSIXct becomes a raw number. S3 dispatch keys off the class attribute.",
      visual: {
        title: "Vector plus stickers",
        kind: "layers",
        layers: [
          { h: "Data", lines: ["Atomic vector or list"] },
          { h: "names / dim", lines: ["How we index it"] },
          { h: "class / levels", lines: ["How generics treat it"] },
          { h: "Other attrs", lines: ["tsp, label, custom"] },
        ],
        footer: "class is just an attribute — S3 has no sealed schema",
      },
    },
    {
      q: "How does lazy evaluation of arguments work?",
      a: "Each argument is a promise: expression + environment. It is forced when the value is first needed. Defaults participate in the same machinery.",
      e: "You can inspect with substitute() before forcing. Missing args are a special promise. Infinite recursion happens if a default refers to itself carelessly.",
      visual: {
        title: "Promise lifetime",
        kind: "timeline",
        events: [
          { h: "Call", lines: ["Arg stored, not run"] },
          { h: "Body starts", lines: ["Still a promise"] },
          { h: "First use", lines: ["Force in caller env"] },
          { h: "Cached", lines: ["Later uses reuse it"] },
        ],
        footer: "Unused arguments cost nothing — until you touch them",
      },
    },
    {
      q: "How do ggplot2 layers fit together?",
      a: "ggplot(data, aes()) sets defaults; geoms, stats, scales, and facets are added layers. Each layer can override data and mapping.",
      e: "It’s the grammar of graphics, not a single plot function. Knowing that aes is NSE and that layers are objects helps you debug ‘object x not found’ in packages.",
      visual: {
        title: "Grammar of graphics",
        kind: "cycle",
        center: "ggplot",
        items: [
          { h: "Data", lines: ["A data.frame"] },
          { h: "aes", lines: ["Map columns"] },
          { h: "geom", lines: ["Points · bars"] },
          { h: "stat", lines: ["Transform"] },
          { h: "scale", lines: ["Axes · color"] },
          { h: "facet", lines: ["Small multiples"] },
        ],
        footer: "Plots are assembled — not one giant function call",
      },
    },
  ],
  expert: [
    {
      q: "How do S3, S4, and R6 differ?",
      a: "S3 is informal generic + class attribute. S4 is formal classes, slots, and multiple dispatch. R6 is encapsulated OO with reference semantics (methods live in the object).",
      e: "Base R and tidyverse are S3-heavy. Bioconductor is S4-heavy. Shiny modules and mutable accumulators often use R6. Don’t mix systems without a boundary.",
      visual: {
        title: "Three OO styles",
        kind: "hub",
        hub: "OO in R",
        nodes: [
          { h: "S3", lines: ["UseMethod"] },
          { h: "S4", lines: ["setClass · slots"] },
          { h: "R6", lines: ["Mutable refs"] },
          { h: "RC", lines: ["setRefClass"] },
          { h: "S7", lines: ["Newer formal"] },
          { h: "base", lines: ["Mostly S3"] },
        ],
        footer: "Pick S3 for generics — R6 when you need mutation",
      },
    },
    {
      q: "When would you choose S4 over S3?",
      a: "S4 when you need validity methods, multiple dispatch (signature on several args), and inheritance that the checker can enforce — common in Bioconductor.",
      e: "S4 is verbose and slower to dispatch. S3 is enough for print/summary methods on a tibble-like object. setOldClass() bridges S3 into S4.",
      visual: {
        title: "S3 vs S4",
        kind: "compare",
        left: {
          h: "S3",
          lines: ["class attribute", "Single dispatch", "No validity", "Tiny to write"],
        },
        right: {
          h: "S4",
          lines: ["setClass slots", "Multiple dispatch", "validObject()", "Heavy but strict"],
        },
        footer: "Formal OO is for large class graphs, not one print method",
      },
    },
    {
      q: "How does tidy evaluation inject names safely?",
      a: "enquo captures a defused argument; !! splices it. {{ x }} is enquo + !! in one. .data$ and .env$ disambiguate data-mask vs function env.",
      e: "quosures bundle expression + env so evaluation happens in the right place. Programming with NSE without quosures is how subset() bugs are born.",
      visual: {
        title: "Embrace a bare name",
        kind: "code",
        code: {
          file: "nse.R",
          code: [
            "mean_of <- function(df, col) {",
            "  dplyr::summarise(df,",
            "    m = mean({{ col }}, na.rm=TRUE)",
            "  )",
            "}",
          ],
          notes: [
            { h: "{{ }}", text: "Defuse caller arg, inject it" },
            { h: "Mask", text: "col looks up in df" },
            { h: ".env", text: "Escape the mask if needed" },
          ],
        },
        footer: "Tidy eval is NSE you can wrap in functions",
      },
    },
    {
      q: "How do NAMED and refcounts interact with ALTREP?",
      a: "Modern R uses refcounts more than the old NAMED max of 2. ALTREP objects (1:n, compact repeats) stay virtual until a materializing op, then a real vector appears — and copies follow the usual rules.",
      e: "sum(1:1e9) can be O(1). Sorting or setting an element materializes. Debugging with tracemem on ALTREP can surprise you; lobstr::obj_addr helps.",
      visual: {
        title: "Virtual then real",
        kind: "steps",
        steps: [
          { h: "1:1e9", lines: ["ALTREP compact"] },
          { h: "Inspect", lines: ["Cheap metadata"] },
          { h: "Materialize", lines: ["Write or complex read"] },
          { h: "Copy rules", lines: ["Refcount as usual"] },
        ],
        footer: "Cheap sequences stay cheap until you poke the data",
      },
    },
    {
      q: "When is R6 the right object system?",
      a: "R6 when you need mutable state, methods that update in place, and a Python/Java-like mental model (public/private, active bindings) without S4 ceremony.",
      e: "Reference semantics mean clones are explicit ($clone()). Passing an R6 object into a function can mutate the caller’s object — document that. RC (setRefClass) is the older relative.",
      visual: {
        title: "R6 vs S3 values",
        kind: "compare",
        left: {
          h: "S3 / most R",
          lines: ["Copy-on-modify", "Methods are generics", "Functional style", "Safe to pass around"],
        },
        right: {
          h: "R6",
          lines: ["Reference mutate", "Methods on $", "Encapsulated state", "Clone if you must copy"],
        },
        footer: "R6 is a pointer — S3 objects are values",
      },
    },
    {
      q: "How do parent environments and search() interact?",
      a: "Every env has a parent. search() is the chain from .GlobalEnv through attached packages to Autoloads and package:base. emptyenv() ends the walk.",
      e: "new.env(parent = ...) sets the parent. package namespaces have a different chain (imports → base) so unexported objects stay hidden. attach() mutates search() — avoid it in packages.",
      visual: {
        title: "Two chains",
        kind: "layers",
        layers: [
          { h: "search() (console)", lines: ["Global → packages → base"] },
          { h: "Namespace (pkg)", lines: ["Package env → imports"] },
          { h: "Imports", lines: ["Only what NAMESPACE lists"] },
          { h: "emptyenv", lines: ["Stop — no further parent"] },
        ],
        footer: "Packages do not see the user’s search path by design",
      },
    },
    {
      q: "How do you define a small R6 class?",
      a: "R6::R6Class lists public fields/methods and optional private/active. $new() constructs. Methods use self$ and private$.",
      e: "portable = TRUE (default) is for packages. Avoid huge data in R6 if you serialize sessions. Active bindings look like fields but run code.",
      visual: {
        title: "R6 accumulator",
        kind: "code",
        code: {
          file: "acc.R",
          code: [
            "Acc <- R6::R6Class('Acc',",
            "  public = list(",
            "    x = 0,",
            "    add = function(n) self$x <- self$x + n",
            "  ))",
          ],
          notes: [
            { h: "self$", text: "Reference to this instance" },
            { h: "$new()", text: "Constructor" },
            { h: "Mutate", text: "Caller sees x change" },
          ],
        },
        footer: "Methods close over the instance — not a copied list",
      },
    },
    {
      q: "How does R’s garbage collector behave in practice?",
      a: "R uses a generational GC on SEXPs. gc() triggers and reports; it does not shrink the OS RSS as much as people hope. Peak usage is what matters.",
      e: "Cycles through environments are collected. External pointers (.Call, Rcpp) need finalizers. rm() + gc() is a ritual, not a strategy — don’t pin big objects in hidden closures.",
      visual: {
        title: "Memory lifetime",
        kind: "timeline",
        events: [
          { h: "Allocate", lines: ["SEXP on the heap"] },
          { h: "Reachable", lines: ["Names · env · PROTECT"] },
          { h: "Drop refs", lines: ["rm / leave scope"] },
          { h: "GC", lines: ["Reuse the vector"] },
        ],
        footer: "Hidden refs in closures are the usual leak",
      },
    },
    {
      q: "How does a data-mask evaluate NSE?",
      a: "A data mask is a chain of environments that make columns look like variables. Evaluation uses the mask first, then the caller/quosure env for helpers.",
      e: "Masking bugs: a column named mean hides the function unless you .env$mean or dplyr::. Hybrid evaluation in dplyr may evaluate some verbs in C for speed.",
      visual: {
        title: "Mask then env",
        kind: "cycle",
        center: "eval",
        items: [
          { h: "Quosure", lines: ["expr + env"] },
          { h: "Data mask", lines: ["Columns as names"] },
          { h: "Helpers", lines: ["n(), mean()"] },
          { h: ".data", lines: ["Force a column"] },
          { h: ".env", lines: ["Force the fn env"] },
        ],
        footer: "If a column collides with a function, be explicit",
      },
    },
    {
      q: "What belongs in a serious R package?",
      a: "DESCRIPTION, NAMESPACE, R/, tests (testthat), vignettes, and a stable exported API. Use renv only for apps; packages declare Imports/Suggests versions loosely plus a CI matrix.",
      e: "R CMD check is the contract. Compiled code goes in src/ with Rcpp or .Call. Don’t attach other packages from .onLoad — import them.",
      visual: {
        title: "Package internals",
        kind: "hub",
        hub: "pkg",
        nodes: [
          { h: "DESCRIPTION", lines: ["Deps · version"] },
          { h: "NAMESPACE", lines: ["Exports"] },
          { h: "R/", lines: ["Functions"] },
          { h: "src/", lines: [".Call / Rcpp"] },
          { h: "tests", lines: ["testthat"] },
          { h: "check", lines: ["R CMD check"] },
        ],
        footer: "Check is the interview for your package",
      },
    },
    {
      q: "How do you call C from R safely?",
      a: ".Call passes SEXP pointers. You must PROTECT objects that allocate, UNPROTECT before return, and never hold raw pointers across R calls that can GC.",
      e: "Rcpp hides PROTECT for many cases. .C is older and copies. Returning a dangling pointer is undefined — the usual crash after gc(). Prefer C++ with Rcpp for new code unless you need tiny deps.",
      visual: {
        title: "A .Call boundary",
        kind: "code",
        code: {
          file: "add.c",
          code: [
            "SEXP add1(SEXP x) {",
            "  // PROTECT allocations",
            "  return x; /* SEXP out */",
            "}",
          ],
          notes: [
            { h: "SEXP", text: "Everything R can see is a SEXP" },
            { h: "PROTECT", text: "Stop GC from collecting temps" },
            { h: "UNPROTECT", text: "Balance before you return" },
          ],
        },
        footer: "If it allocates, PROTECT it until it is reachable",
      },
    },
    {
      q: "What is the bytecode compiler and when does it matter?",
      a: "compiler::cmpfun / JIT (enableJIT) turns R closures into bytecode. Tight R loops get faster; already-vectorized code barely moves.",
      e: "It is not a C compiler. Hot numeric loops still belong in C/Rcpp or data.table. package_native_routine_registration and byte-compile on install are defaults now.",
      visual: {
        title: "Where speed comes from",
        kind: "steps",
        steps: [
          { h: "Vectorize", lines: ["Stay in C internals"] },
          { h: "Byte JIT", lines: ["Help remaining R loops"] },
          { h: "data.table", lines: ["By-ref, C kernels"] },
          { h: ".Call / Rcpp", lines: ["Custom hot path"] },
        ],
        footer: "JIT is a bonus — algorithm and copies dominate",
      },
    },
    {
      q: "How are SEXPs typed at the C level?",
      a: "TYPEOF(x) is INTSXP, REALSXP, VECSXP, ENVSXP, CLOSXP, etc. Attributes are a pairlist. Lists are VECSXP; data.frames are VECSXP plus class.",
      e: "Knowing this explains why a ‘matrix’ is still REALSXP with a dim attribute, and why unclass() can be enough to smash S3. Don’t mutate SEXPs that might be shared (NAMED).",
      visual: {
        title: "SEXP layers",
        kind: "layers",
        layers: [
          { h: "SEXP header", lines: ["sxpinfo · type · named"] },
          { h: "Payload", lines: ["int* · double* · SEXP*"] },
          { h: "ATTRIB", lines: ["names, dim, class"] },
          { h: "R view", lines: ["factor, matrix, df"] },
        ],
        footer: "S3 ‘types’ are payloads plus attributes",
      },
    },
    {
      q: "When do hidden copies still bite experts?",
      a: "p[i] <- on a shared object, changing length, combining lists, data.frame column replace that isn’t in-place, and serializing then mutating. Closures that assign to enclosing env can also duplicate.",
      e: "data.table := and R6 avoid copies by design. vctrs/tibble have stricter recycling that fails instead of silently copying. Profile with bench::mark and profmem, not folklore.",
      visual: {
        title: "Copy surprises",
        kind: "timeline",
        events: [
          { h: "Share", lines: ["y <- x"] },
          { h: "Column assign", lines: ["df$a <- df$a + 1"] },
          { h: "Maybe copy", lines: ["Whole column rebuilt"] },
          { h: "Profile", lines: ["profmem / bench"] },
        ],
        footer: "If two names can see it, a write may clone it",
      },
    },
    {
      q: "How do closures capture environments and leak memory?",
      a: "A function’s enclosing env is a reference. If you build factories inside a function that had a huge local, every returned closure can pin that whole frame.",
      e: "Fix: local({ ... }) with only the needed bindings, or rm the rest before return. This is the classic shiny/module leak. pryr::address and lobstr::obj_size on the closure show the pin.",
      visual: {
        title: "Factory pin",
        kind: "cycle",
        center: "closure",
        items: [
          { h: "Factory runs", lines: ["Big local data"] },
          { h: "Return fn", lines: ["Enclosing env kept"] },
          { h: "Call later", lines: ["Looks up free names"] },
          { h: "GC blocked", lines: ["Big local still live"] },
          { h: "Trim env", lines: ["Keep only needs"] },
        ],
        footer: "Returned functions keep their birth environment",
      },
    },
  ],
};
