module.exports = {
  name: "Ruby",
  description:
    "Ruby interview questions — objects, blocks, mixins, metaprogramming, GC, and the GIL.",
  match: /^ruby$/i,
  theme: {
    accent: "#CC342D",
    hubFill: "#CC342D",
    hubText: "#ffffff",
    centerFill: "#fee2e2",
    centerStroke: "#CC342D",
    label: "Ruby",
  },
  beginner: [
    {
      q: "What is Ruby and why do teams still use it?",
      a: "Ruby is a dynamically typed, object-oriented language designed for programmer happiness. Rails made it a default for product teams that value speed of iteration.",
      e: "MRI is the usual runtime. Syntax is expressive (blocks, symbols). Interviews expect objects-everywhere, plus honesty about GIL and performance trade-offs.",
      visual: {
        title: "Where Ruby shows up",
        kind: "hub",
        hub: "Ruby",
        nodes: [
          { h: "Rails", lines: ["Web products"] },
          { h: "DSLs", lines: ["Rake · RSpec"] },
          { h: "Gems", lines: ["rubygems.org"] },
          { h: "Scripting", lines: ["DevOps glue"] },
          { h: "Objects", lines: ["Even 1 is an object"] },
          { h: "Blocks", lines: ["Enumerable style"] },
        ],
        footer: "Ruby optimizes for writing — MRI is not a JVM clone",
      },
    },
    {
      q: "How does Ruby compare to Python for interviews?",
      a: "Both are dynamic and OO. Ruby treats blocks as a first-class syntax and leans on mixins. Python leans on explicitness and a larger data/ML ecosystem.",
      e: "Ruby’s culture is messages and Enumerable. Python’s is functions and protocols. Neither has a true GIL-free story in the main C runtime (yet) for CPU-bound threads.",
      visual: {
        title: "Ruby vs Python flavor",
        kind: "compare",
        left: {
          h: "Ruby",
          lines: ["Blocks / yield", "Mixins everywhere", "Symbols as names", "Rails gravity"],
        },
        right: {
          h: "Python",
          lines: ["Indentation blocks", "Multiple inheritance", "Names are strings", "Data / ML gravity"],
        },
        footer: "Same niche — different syntax religion and standard libraries",
      },
    },
    {
      q: "What does “everything is an object” mean?",
      a: "Numbers, classes, nil, and true are objects that respond to messages. You call methods, not operators as a separate universe (1 + 2 is 1.+(2)).",
      e: "nil is an object (NilClass), not a bare null. Classes are objects of Class. This is why you can reopen Integer in a (dangerous) monkey patch.",
      visual: {
        title: "Send a message",
        kind: "steps",
        steps: [
          { h: "Value", lines: ["1, \"hi\", nil"] },
          { h: "Class", lines: ["Integer · String · NilClass"] },
          { h: "Message", lines: ["1.to_s"] },
          { h: "Method", lines: ["Lookup on the class"] },
        ],
        footer: "If it has a class, you can send it a message",
      },
    },
    {
      q: "How do you define a class and a method?",
      a: "class User; def initialize(name); @name = name; end; end. initialize is the constructor. Instance variables use @. Methods are public by default.",
      e: "attr_reader / attr_writer / attr_accessor generate getters and setters. self is the receiver. Class methods use def self.foo or class << self.",
      visual: {
        title: "A small class",
        kind: "code",
        code: {
          file: "user.rb",
          code: [
            "class User",
            "  attr_reader :name",
            "  def initialize(name)",
            "    @name = name",
            "  end",
            "  def greet",
            "    \"hi #{@name}\"",
            "  end",
            "end",
          ],
          notes: [
            { h: "init", text: "initialize runs on User.new" },
            { h: "@name", text: "Instance variable per object" },
            { h: "attr", text: "Defines name method" },
          ],
        },
        footer: "new allocates — initialize is just a method you happen to name",
      },
    },
    {
      q: "How does the object model look at a beginner level?",
      a: "An object has a class. The class has a superclass (often Object → BasicObject). Modules can be inserted in the ancestor chain via include.",
      e: "Method lookup walks ancestors. Kernel is mixed into Object, which is why puts is everywhere. You can ask obj.class and obj.class.ancestors.",
      visual: {
        title: "Object to BasicObject",
        kind: "cycle",
        center: "obj",
        items: [
          { h: "class", lines: ["User"] },
          { h: "super", lines: ["Object"] },
          { h: "Kernel", lines: ["puts · raise"] },
          { h: "BasicObject", lines: ["Bare minimum"] },
          { h: "lookup", lines: ["Walk ancestors"] },
        ],
        footer: "ancestors is the interview diagram — draw it once out loud",
      },
    },
    {
      q: "What are Ruby’s variable scopes?",
      a: "local (foo), instance (@foo), class (@@foo, usually avoided), global ($foo, avoid), and constants (Foo, looked up lexically + inheritance).",
      e: "@@class vars are shared down the hierarchy in surprising ways — prefer class instance variables (@foo on the class). Constants are mutable; freeze when you mean it.",
      visual: {
        title: "Four variable layers",
        kind: "layers",
        layers: [
          { h: "local", lines: ["Method / block scope"] },
          { h: "@instance", lines: ["Per object"] },
          { h: "@@class", lines: ["Shared — usually a smell"] },
          { h: "$global", lines: ["Process-wide — avoid"] },
        ],
        footer: "If you need class state, use @ivar on the class object",
      },
    },
    {
      q: "How do you go from IRB to a running program?",
      a: "IRB is the REPL. Files are loaded with ruby app.rb. Bundler isolates gems. Rails then boots the app via config/environment.rb.",
      e: "require loads a feature once; load re-reads. require_relative is for local files. $LOAD_PATH ( $: ) is where require looks.",
      visual: {
        title: "From REPL to process",
        kind: "timeline",
        events: [
          { h: "IRB", lines: ["Explore a snippet"] },
          { h: "file", lines: ["ruby script.rb"] },
          { h: "bundle", lines: ["Gemfile lock"] },
          { h: "boot", lines: ["Rails / Rack"] },
        ],
        footer: "require is the unit of loading — Bundler is the unit of versions",
      },
    },
    {
      q: "What core types should you name?",
      a: "Integer, Float, String, Symbol, Array, Hash, Range, Regexp, TrueClass/FalseClass, NilClass. Struct and Data for small value objects.",
      e: "Strings are mutable by default (unlike Python). Symbols are interned names. Hash keys are often symbols in Rails. Integer is arbitrary size.",
      visual: {
        title: "Core type map",
        kind: "hub",
        hub: "Types",
        nodes: [
          { h: "Integer", lines: ["Arbitrary size"] },
          { h: "String", lines: ["Mutable bytes/chars"] },
          { h: "Symbol", lines: ["Interned name"] },
          { h: "Array", lines: ["Ordered list"] },
          { h: "Hash", lines: ["Insertion-ordered"] },
          { h: "nil", lines: ["NilClass instance"] },
        ],
        footer: "nil is an object — calling a method on it is NoMethodError",
      },
    },
    {
      q: "What is the difference between String and Symbol?",
      a: "A String is text data (copyable, mutable). A Symbol is an interned name (:status) used as Hash keys and method names. Symbols are not garbage-collected the same way historically.",
      e: "Modern MRI GCs symbols created at runtime more carefully, but the idiom remains: symbols for identity, strings for content. \"foo\".to_sym is not free in hot loops.",
      visual: {
        title: "String vs Symbol",
        kind: "compare",
        left: {
          h: "String",
          lines: ["Text payload", "Mutable by default", "\"status\"", "User input stays here"],
        },
        right: {
          h: "Symbol",
          lines: ["Interned identity", ":status", "Hash / method names", "Not for unbounded input"],
        },
        footer: "Do not to_sym unbounded user input — that is a memory footgun",
      },
    },
    {
      q: "What is a block?",
      a: "A block is an anonymous chunk of code passed to a method: each { |x| ... } or do/end. The method runs it with yield or &block.",
      e: "Only one block per call. Braces bind tighter than do/end. block_given? checks presence. This is the heart of Ruby’s APIs (File.open, each).",
      visual: {
        title: "Pass a block",
        kind: "steps",
        steps: [
          { h: "Call", lines: ["ary.each"] },
          { h: "Block", lines: ["{ |x| puts x }"] },
          { h: "yield", lines: ["Method runs your code"] },
          { h: "Return", lines: ["each returns the array"] },
        ],
        footer: "A block is not an object until you capture it with &",
      },
    },
    {
      q: "How do each, map, and select work?",
      a: "They are Enumerable methods. each walks, map transforms, select/filter keeps. They take blocks. Bang variants (map!) mutate when they exist.",
      e: "Prefer returning new arrays unless mutation is the API. Enumerable is a mixin — any class that implements each gets map for free.",
      visual: {
        title: "map over a list",
        kind: "code",
        code: {
          file: "enum.rb",
          code: [
            "nums = [1, 2, 3]",
            "nums.map { |n| n * 2 }",
            "# => [2, 4, 6]",
            "nums.select(&:odd?)",
            "# => [1, 3]",
          ],
          notes: [
            { h: "each", text: "Walk for side effects" },
            { h: "map", text: "Build a new array" },
            { h: "&:odd?", text: "Symbol-to-proc shortcut" },
          ],
        },
        footer: "Implement each — inherit the rest from Enumerable",
      },
    },
    {
      q: "What is Enumerable?",
      a: "A module of traversal algorithms. Include it and define each; you get map, reduce, find, group_by, lazy, and dozens more.",
      e: "lazy avoids building intermediate arrays. Enumerator is the object you get from each without a block. This is the Ruby answer to “how do you iterate?”",
      visual: {
        title: "each unlocks Enumerable",
        kind: "cycle",
        center: "each",
        items: [
          { h: "include", lines: ["Enumerable"] },
          { h: "each", lines: ["Yield items"] },
          { h: "map", lines: ["Transform"] },
          { h: "select", lines: ["Filter"] },
          { h: "reduce", lines: ["Fold"] },
        ],
        footer: "Enumerable is a mixin, not a base class — duck-type each",
      },
    },
    {
      q: "How do modules differ from classes?",
      a: "Modules namespace constants and methods. They cannot be instantiated. Classes can be new’d and have a superclass. Modules are mixed in with include/extend.",
      e: "A class is a module that can have instances (Class < Module). That sentence is an expert-ready beginner answer. Use modules for helpers and namespaces.",
      visual: {
        title: "Module vs class",
        kind: "layers",
        layers: [
          { h: "module", lines: ["Namespace + mixin · no new"] },
          { h: "class", lines: ["Can allocate instances"] },
          { h: "Class < Module", lines: ["Classes are modules with extra"] },
        ],
        footer: "If you do not need instances, start with a module",
      },
    },
    {
      q: "How do gems and Bundler load code?",
      a: "A gem is a packaged library. Gemfile lists them. bundle install writes Gemfile.lock. bundle exec ruby puts the locked gems on the load path.",
      e: "require 'foo' after Bundler.setup. Rails does this in boot. Never rely on system gems in production. Semantic versioning lives in the Gemfile.",
      visual: {
        title: "Gemfile to require",
        kind: "timeline",
        events: [
          { h: "Gemfile", lines: ["Declare deps"] },
          { h: "lock", lines: ["Pin versions"] },
          { h: "install", lines: ["vendor or cache"] },
          { h: "require", lines: ["Load the lib"] },
        ],
        footer: "Apps commit Gemfile.lock — that is the build input",
      },
    },
    {
      q: "What is truthiness in Ruby?",
      a: "Only false and nil are falsy. 0, \"\", and [] are all true. That surprises people coming from C or Python.",
      e: "Prefer explicit empty? over if array. defined? and unless are idiomatic. && / || return the last evaluated object, not a boolean.",
      visual: {
        title: "What is true?",
        kind: "hub",
        hub: "if x",
        nodes: [
          { h: "nil", lines: ["falsy"] },
          { h: "false", lines: ["falsy"] },
          { h: "0", lines: ["truthy"] },
          { h: "\"\"", lines: ["truthy"] },
          { h: "[]", lines: ["truthy"] },
          { h: "obj", lines: ["truthy"] },
        ],
        footer: "Only nil and false fail an if — zero is not false",
      },
    },
  ],
  intermediate: [
    {
      q: "What is the difference between blocks, Procs, and lambdas?",
      a: "A block is syntax. Proc.new/proc is an object from a block; return in a proc returns from the enclosing method. lambda/-> is stricter on arity and return is local.",
      e: "stabby lambda ->(x) { x }. & converts block ↔ Proc. Interviews love “proc vs lambda return.” Use lambda when you want function-like semantics.",
      visual: {
        title: "lambda vs proc",
        kind: "code",
        code: {
          file: "callable.rb",
          code: [
            "lam = ->(x) { x + 1 }",
            "pr  = proc { |x| x + 1 }",
            "lam.call(1)",
            "def demo",
            "  proc { return 1 }.call",
            "  :never",
            "end",
          ],
          notes: [
            { h: "lambda", text: "Arity checked · local return" },
            { h: "proc", text: "Return leaves the method" },
            { h: "&blk", text: "Capture the block as a Proc" },
          ],
        },
        footer: "return in a Proc is non-local — that is the classic trap",
      },
    },
    {
      q: "How do yield and block_given? work?",
      a: "yield passes control to the caller’s block. yield x sends an argument. block_given? is true if a block was provided. &block captures it as a Proc.",
      e: "File.open uses this to ensure close. If you yield without a block, you get LocalJumpError. Provide a default with block_given? or an explicit &nil.",
      visual: {
        title: "yield into the block",
        kind: "steps",
        steps: [
          { h: "Method", lines: ["def with_file"] },
          { h: "Open", lines: ["resource = ..."] },
          { h: "yield", lines: ["Run the caller block"] },
          { h: "Ensure", lines: ["close in ensure"] },
        ],
        footer: "yield is how Ruby does loaner resources without a separate syntax",
      },
    },
    {
      q: "include vs extend vs prepend?",
      a: "include mixes the module into the ancestor chain after the class (instance methods). extend adds the module to the object’s singleton (class methods if you extend the class). prepend inserts before the class.",
      e: "prepend lets the module wrap with super. extend self is a pattern for module functions. Know ancestors after each — interviewers ask you to draw it.",
      visual: {
        title: "Where the module lands",
        kind: "compare",
        left: {
          h: "include / extend",
          lines: ["include → instances", "After the class", "extend → that object", "Class methods via extend"],
        },
        right: {
          h: "prepend",
          lines: ["Before the class", "super calls original", "Wrap / decorate", "Still a mixin"],
        },
        footer: "include behind · prepend in front · extend on the singleton",
      },
    },
    {
      q: "How do mixins shape Ruby design?",
      a: "Instead of deep inheritance, you include modules (Comparable, Enumerable, Forwardable). Classes stay small; behavior is composed.",
      e: "Comparable needs <=> . Enumerable needs each. This is the Strategy of the Ruby standard library. Too many mixins make lookup surprising — keep the chain short.",
      visual: {
        title: "Mixin toolbox",
        kind: "hub",
        hub: "include",
        nodes: [
          { h: "Enumerable", lines: ["each → map"] },
          { h: "Comparable", lines: ["<=> → < >"] },
          { h: "Kernel", lines: ["Already in Object"] },
          { h: "Forwardable", lines: ["Delegate methods"] },
          { h: "Your module", lines: ["Shared domain"] },
          { h: "prepend", lines: ["Wrap with super"] },
        ],
        footer: "Mixins are the Ruby alternative to multiple inheritance",
      },
    },
    {
      q: "How does method lookup walk the chain?",
      a: "Start at the object’s class (or singleton class), then prepended modules, the class, included modules, then superclass, until BasicObject. method_missing is last.",
      e: "singleton class (eigenclass) holds per-object methods. class << obj; def foo; end; end. ancestors does not always show the singleton — use singleton_class.ancestors.",
      visual: {
        title: "Lookup walk",
        kind: "timeline",
        events: [
          { h: "Singleton", lines: ["Per-object methods"] },
          { h: "prepend", lines: ["Modules in front"] },
          { h: "Class", lines: ["Then includes"] },
          { h: "Super", lines: ["Repeat until miss"] },
        ],
        footer: "If you cannot draw lookup, prepend will surprise you in production",
      },
    },
    {
      q: "What is self in different places?",
      a: "In an instance method, self is the instance. At class body top level, self is the class. In a class method, self is the class. In a block, self is usually unchanged (lexical).",
      e: "instance_eval changes self. class_eval on a class also sets self to that class. This is the lever all DSLs use. Losing track of self is the #1 metaprogramming bug.",
      visual: {
        title: "Who is self?",
        kind: "layers",
        layers: [
          { h: "Instance method", lines: ["self is the object"] },
          { h: "Class body / def self.x", lines: ["self is the class"] },
          { h: "instance_eval", lines: ["self becomes the receiver"] },
          { h: "Block", lines: ["self usually stays (closure)"] },
        ],
        footer: "DSLs work by changing self — that is also how they bite",
      },
    },
    {
      q: "How do you chain Enumerable without wasting arrays?",
      a: "map/select build arrays. Enumerable#lazy defers work until you force (to_a, first). Enumerator chaining with each_slice etc. stays streaming when lazy.",
      e: "For huge IO, lazy is the difference. For tiny arrays, eager is clearer. know reduce vs each_with_object for building hashes.",
      visual: {
        title: "Eager vs lazy chain",
        kind: "cycle",
        center: "lazy",
        items: [
          { h: "Source", lines: ["huge.each"] },
          { h: "map", lines: ["Deferred"] },
          { h: "select", lines: ["Deferred"] },
          { h: "first", lines: ["Pulls one"] },
          { h: "Stop", lines: ["No full array"] },
        ],
        footer: "lazy turns Enumerable into a pull pipeline",
      },
    },
    {
      q: "What do attr_* and struct helpers generate?",
      a: "attr_reader defines a getter for @name. attr_accessor also defines name=. Struct.new builds a class with accessors; Data.define (3.2) is the immutable cousin.",
      e: "These are methods that define methods — beginner metaprogramming. Prefer Data for values you do not want mutated.",
      visual: {
        title: "attr_accessor expand",
        kind: "code",
        code: {
          file: "point.rb",
          code: [
            "class Point",
            "  attr_accessor :x, :y",
            "end",
            "# def x; @x; end",
            "# def x=(v); @x = v; end",
            "Data.define(:x, :y)",
          ],
          notes: [
            { h: "reader", text: "Defines getter only" },
            { h: "accessor", text: "Getter plus setter" },
            { h: "Data", text: "Immutable value object" },
          ],
        },
        footer: "attr_* is metaprogramming you already use every day",
      },
    },
    {
      q: "How do exceptions work in Ruby?",
      a: "raise (or fail) throws. begin / rescue / ensure / else. Exception is the root; StandardError is what rescue catches by default. rescue => e binds.",
      e: "Do not rescue Exception (that includes SyntaxError/NoMemory). ensure always runs. retry restarts the begin. raise in rescue rethrows.",
      visual: {
        title: "raise then rescue",
        kind: "steps",
        steps: [
          { h: "raise", lines: ["Unwind with a class"] },
          { h: "rescue", lines: ["Match StandardError"] },
          { h: "ensure", lines: ["Always run"] },
          { h: "else", lines: ["No exception path"] },
        ],
        footer: "Bare rescue is StandardError — not Exception",
      },
    },
    {
      q: "Hash rockets vs symbol keys vs keywords?",
      a: "{ :a => 1 } and { a: 1 } are the same idea (symbol keys). \"a\" => 1 is a string key. Keyword args (def f(a:)) are not a Hash, but ** can convert.",
      e: "Ruby 3 separated keyword args from positional hashes more strictly. **nil and ... forwarding matter in wrappers. Hash default procs are a mutation trap.",
      visual: {
        title: "Keys and keywords",
        kind: "compare",
        left: {
          h: "Hash",
          lines: [":a => 1 or a: 1", "String keys differ", "default proc", "Hash#dig"],
        },
        right: {
          h: "Keywords",
          lines: ["def f(a: 1)", "Required a:", "**rest", "Ruby 3 separation"],
        },
        footer: "A symbol-key Hash is not automatically keyword args in Ruby 3+",
      },
    },
    {
      q: "Which Enumerable methods should you have on tap?",
      a: "map, select, reject, find, reduce, group_by, partition, flat_map, each_with_object, grep, sort_by, uniq, lazy. Know bang vs non-bang.",
      e: "detect is find. collect is map. inject is reduce. Aliases are historical. Interviewers still say inject.",
      visual: {
        title: "Enumerable hits",
        kind: "hub",
        hub: "Enum",
        nodes: [
          { h: "map", lines: ["Transform"] },
          { h: "select", lines: ["Filter in"] },
          { h: "reduce", lines: ["Fold"] },
          { h: "group_by", lines: ["Hash of arrays"] },
          { h: "flat_map", lines: ["Map then flatten 1"] },
          { h: "lazy", lines: ["Stream"] },
        ],
        footer: "If you wrote a nested each, Enumerable already had a method",
      },
    },
    {
      q: "What is the Bundler/Rails boot path at an intermediate level?",
      a: "Bundler.setup, Bundler.require, then Rails::Application boot: load config, initializers, eager_load in prod. Zeitwerk autoloads constants from file names.",
      e: "eager_load vs lazy autoload is a prod/dev split. Classic autoloader vs Zeitwerk is a Rails 6+ topic. Know reload! in console is not production.",
      visual: {
        title: "Boot then autoload",
        kind: "timeline",
        events: [
          { h: "Bundler", lines: ["Activate gems"] },
          { h: "Application", lines: ["config/application"] },
          { h: "Initializers", lines: ["config/initializers"] },
          { h: "Zeitwerk", lines: ["Map files to constants"] },
        ],
        footer: "Zeitwerk infers App::User from app/models/user.rb",
      },
    },
    {
      q: "How does constant lookup work?",
      a: "Constants are nested in modules. Lookup walks lexical nesting, then ancestors, then Object. ::Foo is from the root. autoload can define on first use.",
      e: "A bare Foo inside a module may find the wrong Foo (the infamous Rails gotcha). Qualify :: or use Module#const_get when you mean global.",
      visual: {
        title: "Constant lookup layers",
        kind: "layers",
        layers: [
          { h: "Lexical", lines: ["Nesting of the source file"] },
          { h: "Ancestors", lines: ["Included modules / super"] },
          { h: "Object", lines: ["Top-level constants"] },
        ],
        footer: "Ambiguous Foo is a constant bug — not a method bug",
      },
    },
    {
      q: "What is an object’s lifecycle?",
      a: "allocate, initialize, use, then GC when unreachable. freeze makes it immutable. dup/clone copy (clone copies frozen and singleton methods by default).",
      e: "ObjectSpace and finalizers exist but are last resorts. freeze is shallow. Deep freeze is a library concern. tainted/untrusted APIs were removed in 3.x.",
      visual: {
        title: "Allocate to GC",
        kind: "cycle",
        center: "obj",
        items: [
          { h: "allocate", lines: ["Raw object"] },
          { h: "initialize", lines: ["Your constructor"] },
          { h: "use", lines: ["Messages"] },
          { h: "freeze", lines: ["Optional lock"] },
          { h: "GC", lines: ["Unreachable"] },
        ],
        footer: "new = allocate + initialize — you can call them separately",
      },
    },
    {
      q: "How do you capture a block as a Proc?",
      a: "def f(&blk) stores the block. blk.call runs it. You can pass it on with yield or other(&blk). Symbol#to_proc enables &:to_s.",
      e: "Defining &blk always allocates a Proc — skip it in hot paths if you only yield. to_proc on symbols is map(&:name) sugar.",
      visual: {
        title: "Capture with &",
        kind: "code",
        code: {
          file: "blk.rb",
          code: [
            "def around(&blk)",
            "  puts \"before\"",
            "  blk.call",
            "  puts \"after\"",
            "end",
            "around { puts \"mid\" }",
          ],
          notes: [
            { h: "&blk", text: "Block becomes a Proc" },
            { h: "call", text: "Same as yield here" },
            { h: "pass", text: "other(&blk) forwards" },
          ],
        },
        footer: "& is the bridge between block syntax and Proc objects",
      },
    },
  ],
  expert: [
    {
      q: "How does MRI allocate and GC objects?",
      a: "Small objects live in heap pages (dsize). GC is a generational, incremental mark-and-sweep (Ractor-aware in 3.x). Symbols, strings, and frozen objects have intern/pool paths.",
      e: "Allocation is often the Rails bottleneck, not CPU math. ObjectSpace.dump_all and allocation tracers find leaks. Compaction (GC.compact) reduces fragmentation.",
      visual: {
        title: "Heap then GC",
        kind: "layers",
        layers: [
          { h: "Ruby object", lines: ["RVALUE slot on a page"] },
          { h: "Young gen", lines: ["Most objects die fast"] },
          { h: "Old gen", lines: ["Survivors · incremental mark"] },
          { h: "C data", lines: ["malloc behind String/Array"] },
        ],
        footer: "The Ruby heap is slots — the payload may still be on malloc’s heap",
      },
    },
    {
      q: "What is the GC timeline for a request?",
      a: "Allocate while serving. Minor GC reclaims young objects. Major/old GC is rarer and longer. Compaction may run. Then the worker handles the next request.",
      e: "GC.stat is the dashboard. malloc_limit and RUBY_GC_* env vars tune. In Puma, a GC between requests can hide pauses from users — or add latency if mistimed.",
      visual: {
        title: "GC during a request",
        kind: "timeline",
        events: [
          { h: "Allocate", lines: ["Objects for the action"] },
          { h: "Minor", lines: ["Young objects die"] },
          { h: "Major", lines: ["Mark old objects"] },
          { h: "Next", lines: ["Worker reuses heap"] },
        ],
        footer: "Tuning GC is ops — but experts know GC.stat keys",
      },
    },
    {
      q: "What is metaprogramming in Ruby, really?",
      a: "Defining methods at runtime (define_method), sending messages (send), evaluating strings/blocks in another context (class_eval), and hooking missing methods.",
      e: "Great for DSLs and ORMs. Cost: extra allocations, harder traces, security if send is fed user input. Prefer explicit methods until the duplication hurts.",
      visual: {
        title: "Metaprogramming map",
        kind: "hub",
        hub: "meta",
        nodes: [
          { h: "define_method", lines: ["Runtime def"] },
          { h: "send", lines: ["Call by name"] },
          { h: "class_eval", lines: ["Open the class"] },
          { h: "method_missing", lines: ["Last resort"] },
          { h: "const_set", lines: ["Runtime constants"] },
          { h: "hooks", lines: ["included · inherited"] },
        ],
        footer: "Metaprogramming is a compiler you run at boot — keep it at boot",
      },
    },
    {
      q: "define_method vs method_missing — when is each sound?",
      a: "define_method creates real methods (fast after definition, visible in ancestors). method_missing is a fallback for unknown messages; you must also override respond_to_missing?.",
      e: "method_missing is slow and hides typos. ActiveRecord used it for find_by_*. Today, define_method in a loop at load time is the cleaner pattern.",
      visual: {
        title: "Define vs missing",
        kind: "compare",
        left: {
          h: "define_method",
          lines: ["Real method entries", "Faster after boot", "Shows in #methods", "Needs a closed set"],
        },
        right: {
          h: "method_missing",
          lines: ["Open-ended names", "Slow path", "Must pair respond_to?", "Easy to swallow bugs"],
        },
        footer: "If you can name the methods at boot, define them — do not miss them",
      },
    },
    {
      q: "How do class_eval and instance_eval differ?",
      a: "class_eval (module_eval) evaluates with self as the class/module — def creates instance methods. instance_eval sets self to the receiver — def creates singleton methods on that object.",
      e: "instance_exec passes block args. These are how RSpec and Rails DSLs work. Mixing them up creates class methods when you wanted instance methods.",
      visual: {
        title: "eval changes self",
        kind: "code",
        code: {
          file: "eval.rb",
          code: [
            "String.class_eval do",
            "  def shout = upcase",
            "end",
            "\"hi\".instance_eval do",
            "  def lone = 1",
            "end",
          ],
          notes: [
            { h: "class_eval", text: "def becomes instance methods" },
            { h: "instance_eval", text: "def is on that object only" },
            { h: "self", text: "Always ask who self is" },
          ],
        },
        footer: "The difference is who self is — and therefore where def lands",
      },
    },
    {
      q: "What are refinements?",
      a: "refine String do ... end inside a module, then using ThatModule to activate the monkey patch lexically. Unlike global reopen, refinements do not infect the whole VM.",
      e: "They are not always visible to send/method_missing the way you expect (limitations exist). Use them to keep monkey patches scoped. using is file/module scoped.",
      visual: {
        title: "Lexical monkey patch",
        kind: "steps",
        steps: [
          { h: "refine", lines: ["Patch inside a module"] },
          { h: "using", lines: ["Activate in this scope"] },
          { h: "Call", lines: ["Refined method hits"] },
          { h: "Elsewhere", lines: ["Original method remains"] },
        ],
        footer: "Refinements are monkey patches with a using clause — not a global reopen",
      },
    },
    {
      q: "How does prepend change lookup for wrappers?",
      a: "prepend Module inserts before the class. alias_method + super lets you wrap. This is how ActiveSupport::Concern and instrumentation often decorate.",
      e: "Two prepends stack. super still works. You can break people who assumed the class method was first in the chain — document it.",
      visual: {
        title: "prepend then super",
        kind: "cycle",
        center: "super",
        items: [
          { h: "Call", lines: ["obj.foo"] },
          { h: "Prepended", lines: ["Wrapper runs"] },
          { h: "super", lines: ["Original class"] },
          { h: "Include", lines: ["Later in chain"] },
          { h: "Return", lines: ["Unwinds wrappers"] },
        ],
        footer: "prepend is AOP for Ruby — super is the continuation",
      },
    },
    {
      q: "What is the GVL (GIL) in MRI?",
      a: "The Global VM Lock lets only one thread run Ruby code at a time in a process. C extensions can release it around blocking IO or heavy C work.",
      e: "Threads still help IO (the lock drops on many blocking calls). CPU-bound Ruby does not scale with threads on MRI. Use processes (Puma workers) or Ractors/JRuby.",
      visual: {
        title: "GVL layers",
        kind: "layers",
        layers: [
          { h: "Ruby bytecode", lines: ["One thread holds the GVL"] },
          { h: "Blocking IO", lines: ["Often releases the lock"] },
          { h: "C extension", lines: ["Can rb_thread_call_without_gvl"] },
          { h: "OS threads", lines: ["Many exist — few run Ruby"] },
        ],
        footer: "GVL is why MRI scales with processes for CPU, threads for IO",
      },
    },
    {
      q: "Thread vs Fiber vs Ractor?",
      a: "Thread is an OS thread (GVL-limited). Fiber is a cooperative coroutine on the same thread (scheduler in 3.x for non-blocking IO). Ractor is a (mostly) isolated parallel actor.",
      e: "Fiber scheduler (scheduler.rb) makes Fiber.yield on IO. Ractors cannot share most objects; they pass messages. This is the 3.x concurrency story.",
      visual: {
        title: "Three concurrency tools",
        kind: "timeline",
        events: [
          { h: "Thread", lines: ["OS thread + GVL"] },
          { h: "Fiber", lines: ["Coop stack switch"] },
          { h: "Scheduler", lines: ["Nonblock IO resume"] },
          { h: "Ractor", lines: ["Parallel isolation"] },
        ],
        footer: "Fibers multiplex a thread — Ractors aim for parallel Ruby",
      },
    },
    {
      q: "How do you scale a Ruby web app under the GVL?",
      a: "Puma/Unicorn workers = processes (real parallelism). Threads per worker help IO. Background jobs (Sidekiq) take CPU off the request. Cache and the DB still dominate.",
      e: "thread pool size > 1 is useful for IO-wait. YJIT (3.1+) helps CPU. JRuby/TruffleRuby drop the GVL model. Be honest: architecture beats micro-opts.",
      visual: {
        title: "Scale-out map",
        kind: "hub",
        hub: "Puma",
        nodes: [
          { h: "Workers", lines: ["Processes"] },
          { h: "Threads", lines: ["IO concurrency"] },
          { h: "Jobs", lines: ["Sidekiq"] },
          { h: "YJIT", lines: ["Faster Ruby"] },
          { h: "Cache", lines: ["Redis / Mem"] },
          { h: "DB", lines: ["The real bottleneck"] },
        ],
        footer: "Workers for CPU · threads for wait · jobs for slow work",
      },
    },
    {
      q: "MRI vs JRuby vs TruffleRuby — what changes?",
      a: "MRI: C, GVL, YJIT, C-exts. JRuby: JVM threads, real parallelism, Java interop, some C-exts via FFI. TruffleRuby: Graal, high peak performance, compatibility caveats.",
      e: "C extensions are the lock-in to MRI. JRuby shines when you need threads and the JVM. Mention native gem pain in interviews.",
      visual: {
        title: "Runtime trade-offs",
        kind: "compare",
        left: {
          h: "MRI",
          lines: ["CRuby default", "GVL on Ruby code", "C-ext ecosystem", "YJIT / Ractors"],
        },
        right: {
          h: "JRuby / Truffle",
          lines: ["True threads (JRuby)", "Graal speed (Truffle)", "Weaker C-exts", "Different GC"],
        },
        footer: "The gem C-extension is why most production is still MRI",
      },
    },
    {
      q: "How do you write a small DSL safely?",
      a: "instance_eval the block so methods look bare. instance_exec if you need args. Do not use eval on strings. Prefer a builder object over opening core classes.",
      e: "Refinements or a dedicated builder beat monkey patches. instance_eval changes self — document it. RSpec and Rails are the existence proof and the cautionary tale.",
      visual: {
        title: "Builder DSL",
        kind: "code",
        code: {
          file: "dsl.rb",
          code: [
            "class Box",
            "  def title(t) = @t = t",
            "  def self.build(&b)",
            "    new.tap { |x| x.instance_eval(&b) }",
            "  end",
            "end",
          ],
          notes: [
            { h: "self", text: "Block sees the builder" },
            { h: "tap", text: "Return the object" },
            { h: "No eval", text: "Block, not a string" },
          ],
        },
        footer: "A DSL is instance_eval with taste — not Kernel#eval",
      },
    },
    {
      q: "How do you build methods at boot without method_missing?",
      a: "Loop names and define_method, or class_eval a string of defs if you must. Module#prepend wrappers. TracePoint for debugging, not for business logic.",
      e: "class_eval strings skip block closures (faster, easier constants). define_method closes over locals. Pick based on whether you need the closure.",
      visual: {
        title: "Generate methods at load",
        kind: "steps",
        steps: [
          { h: "Names", lines: ["List of attributes"] },
          { h: "define_method", lines: ["Closure per name"] },
          { h: "or class_eval", lines: ["Def as text"] },
          { h: "Freeze", lines: ["Stop mutating the class"] },
        ],
        footer: "Generate once at boot — never per request",
      },
    },
    {
      q: "How does autoload / Zeitwerk resolve constants?",
      a: "autoload :User, 'user' defines a hook. Zeitwerk infers path from the constant and inflector. A miss raises NameError. Circular autoloads are classic boot bugs.",
      e: "eager_load in prod defines everything up front. In dev, reload unloads constants. Thread safety of autoload was a historical MRI issue — Zeitwerk is the modern answer.",
      visual: {
        title: "Constant miss to file",
        kind: "cycle",
        center: "NameError?",
        items: [
          { h: "Refer", lines: ["User"] },
          { h: "autoload", lines: ["Hook fires"] },
          { h: "path", lines: ["user.rb"] },
          { h: "require", lines: ["Define User"] },
          { h: "retry", lines: ["Lookup succeeds"] },
        ],
        footer: "Zeitwerk is autoload with a strict file convention",
      },
    },
    {
      q: "Where do allocations and frozen strings win?",
      a: "Every interpolated string and array is an object. frozen_string_literal: true makes literals immutable and internable. # frozen_string_literal: true is the magic comment.",
      e: "Avoid + in loops; use join or buffer. Object allocation shows up in stackprof. YJIT + fewer objects beats clever bit tricks in Rails apps.",
      visual: {
        title: "Allocation-aware layers",
        kind: "layers",
        layers: [
          { h: "Literals", lines: ["frozen_string_literal"] },
          { h: "Buffers", lines: ["join / << on one string"] },
          { h: "Avoid", lines: ["map chains on huge arrays"] },
          { h: "Measure", lines: ["stackprof · memory_profiler"] },
        ],
        footer: "Expert Ruby is allocation control — not clever one-liners",
      },
    },
  ],
};
