module.exports = {
  name: "Rust",
  description:
    "Rust interview questions — ownership, borrowing, lifetimes, traits, async, and unsafe.",
  match: /^rust$/i,
  theme: {
    accent: "#dea584",
    hubFill: "#dea584",
    hubText: "#0b1f3a",
    centerFill: "#ffedd5",
    centerStroke: "#b45309",
    label: "Rust",
  },
  beginner: [
    {
      q: "What is Rust and why do teams use it?",
      a: "Rust is a systems language that aims for C++-class performance with memory safety enforced at compile time. It has no GC; the compiler tracks who owns each value.",
      e: "Teams pick it for CLI tools, services, WASM, and embedded work where crashes and data races are expensive. The learning curve is the borrow checker — safety is not free, it is front-loaded.",
      visual: {
        title: "Where Rust pays off",
        kind: "hub",
        hub: "Rust",
        nodes: [
          { h: "Safety", lines: ["No use-after-free"] },
          { h: "Speed", lines: ["No GC pauses"] },
          { h: "Fearless", lines: ["Data-race checks"] },
          { h: "Tooling", lines: ["cargo · rustfmt"] },
          { h: "Interop", lines: ["C ABI / FFI"] },
          { h: "Target", lines: ["Native · WASM"] },
        ],
        footer: "Safety is a compile-time property — not a runtime GC tax",
      },
    },
    {
      q: "How does Rust compare to C++ and garbage-collected languages?",
      a: "C++ trusts the programmer with manual memory. GC languages reclaim later and pause. Rust moves ownership at compile time so most bugs never reach production.",
      e: "You still allocate; you just cannot alias mutably by accident. Unsafe exists for FFI and data structures the checker cannot see — it is opt-in, not the default.",
      visual: {
        title: "Who frees memory?",
        kind: "compare",
        left: {
          h: "C++ / GC",
          lines: ["Manual or collector", "Use-after-free possible", "Data races at runtime", "Fast or pause-y"],
        },
        right: {
          h: "Rust",
          lines: ["Owner drops the value", "Checker rejects aliasing", "Send/Sync for threads", "Predictable teardown"],
        },
        footer: "Rust’s pitch: C++ speed with compiler-enforced aliasing rules",
      },
    },
    {
      q: "What are Rust’s three ownership rules?",
      a: "Each value has one owner. There can be only one owner at a time. When the owner goes out of scope, the value is dropped.",
      e: "Moves transfer ownership. Copy types (integers, bool) duplicate bits instead of moving. Everything else is move-by-default so two owners cannot free the same allocation.",
      visual: {
        title: "Ownership in three rules",
        kind: "steps",
        steps: [
          { h: "One owner", lines: ["A value has a single owner"] },
          { h: "One at a time", lines: ["Move transfers that owner"] },
          { h: "Leave scope", lines: ["Owner ends — Drop runs"] },
          { h: "Copy exception", lines: ["i32 and friends duplicate"] },
        ],
        footer: "If two names could free the same heap, the checker says no",
      },
    },
    {
      q: "What happens when you move a value?",
      a: "Assignment and passing by value move ownership. The old binding is invalid; using it is a compile error. The new owner is responsible for Drop.",
      e: "Clone is an explicit deep (or smart) copy when you need two owners. Prefer borrowing when a function only needs to look, not keep.",
      visual: {
        title: "A move invalidates the old name",
        kind: "code",
        code: {
          file: "move.rs",
          code: [
            "let s = String::from(\"hi\");",
            "let t = s; // s moved",
            "// println!(\"{s}\"); // error",
            "println!(\"{t}\");",
          ],
          notes: [
            { h: "Move", text: "t now owns the heap buffer" },
            { h: "Invalid", text: "s cannot be used after the move" },
            { h: "Clone", text: "s.clone() if you need both" },
          ],
        },
        footer: "Moves are the default — Clone is the explicit escape",
      },
    },
    {
      q: "What is borrowing?",
      a: "Borrowing lets you use a value without taking ownership. &T is a shared reference; &mut T is exclusive. References must never outlive the owner.",
      e: "You may have many &T or one &mut T, never both at once. That is how Rust prevents data races and iterator invalidation without a GC.",
      visual: {
        title: "Borrow instead of move",
        kind: "cycle",
        center: "&T",
        items: [
          { h: "Owner", lines: ["Keeps the value"] },
          { h: "Lend", lines: ["Pass &T or &mut T"] },
          { h: "Use", lines: ["Read or mutate"] },
          { h: "End", lines: ["Borrow expires"] },
          { h: "Drop later", lines: ["Owner still drops"] },
        ],
        footer: "Many readers or one writer — not both, not after the owner dies",
      },
    },
    {
      q: "Where do values live — stack, heap, and Copy?",
      a: "Small Copy types live on the stack and duplicate on assign. Heap types (String, Vec, Box) own an allocation; moving them transfers the pointer, not a deep copy.",
      e: "Copy is an opt-in marker for types that are safe to bitwise-duplicate. Never implement Copy on types that need Drop of a unique resource.",
      visual: {
        title: "Stack, heap, Copy",
        kind: "layers",
        layers: [
          { h: "Stack Copy", lines: ["i32 · bool · small structs", "Assign duplicates bits"] },
          { h: "Heap owner", lines: ["String · Vec · Box", "Move transfers the pointer"] },
          { h: "Borrow", lines: ["&T points at either", "No extra allocation"] },
        ],
        footer: "Copy is a trait, not a performance hint — it changes semantics",
      },
    },
    {
      q: "What does the borrow checker actually do?",
      a: "It proves that references are valid for their whole use: no dangling, no aliasing mutation, no use after move. Failures are compile errors, not segfaults.",
      e: "NLL (non-lexical lifetimes) ends a borrow when last used, not at the closing brace. If the checker fights you, restructure so one owner is obvious.",
      visual: {
        title: "Checker from source to binary",
        kind: "timeline",
        events: [
          { h: "Parse", lines: ["Build the HIR / MIR"] },
          { h: "Track", lines: ["Who owns, who borrows"] },
          { h: "Reject", lines: ["Alias + mutate · dangle"] },
          { h: "Emit", lines: ["Safe native code"] },
        ],
        footer: "The checker is a proof — rustc will not ship the broken alias",
      },
    },
    {
      q: "What are Option and Result?",
      a: "Option<T> is Some(T) or None. Result<T, E> is Ok(T) or Err(E). They force you to handle absence and failure instead of null or hidden exceptions.",
      e: "Prefer ? in functions that already return Result. unwrap is fine in tests and true invariants; it panics in production if you were wrong.",
      visual: {
        title: "Absence vs failure",
        kind: "hub",
        hub: "Enums",
        nodes: [
          { h: "Some", lines: ["Value is present"] },
          { h: "None", lines: ["Nothing to give"] },
          { h: "Ok", lines: ["Operation worked"] },
          { h: "Err", lines: ["Typed failure"] },
          { h: "?", lines: ["Early-return Err"] },
          { h: "match", lines: ["Handle both arms"] },
        ],
        footer: "None is not an error — Err is; do not mix them casually",
      },
    },
    {
      q: "When do you use Option versus Result?",
      a: "Option means a value might be missing (lookup, parent). Result means an operation can fail with a reason (IO, parse). They compose: Option inside Result is common.",
      e: "ok_or converts Option to Result when missing should be an error. Do not use Option to hide failures that callers must log or retry.",
      visual: {
        title: "Option vs Result",
        kind: "compare",
        left: {
          h: "Option<T>",
          lines: ["Present or absent", "No error payload", "HashMap::get", "map / and_then"],
        },
        right: {
          h: "Result<T, E>",
          lines: ["Success or failure", "E explains why", "File::open", "? bubbles Err"],
        },
        footer: "Missing is Option — broken is Result with a useful E",
      },
    },
    {
      q: "How does pattern matching work in Rust?",
      a: "match (and if let) destructures enums and structs. Patterns must be exhaustive unless you use _ or if let for one arm.",
      e: "Exhaustiveness is a feature: adding a variant breaks builds until you handle it. Guards (if) refine an arm without losing the rest of the match.",
      visual: {
        title: "Match then handle",
        kind: "steps",
        steps: [
          { h: "Value", lines: ["Option / Result / enum"] },
          { h: "match", lines: ["Name each shape"] },
          { h: "Bind", lines: ["Unwrap inner data"] },
          { h: "Exhaustive", lines: ["Compiler checks cases"] },
        ],
        footer: "A new variant is a compile error until every match is updated",
      },
    },
    {
      q: "What is a trait at a beginner level?",
      a: "A trait names a set of methods a type can implement (like an interface). Generics use trait bounds so the compiler knows which methods exist.",
      e: "Display, Debug, Clone, Iterator are std traits you implement or derive. Default methods let traits ship behavior types can override.",
      visual: {
        title: "Trait as a contract",
        kind: "code",
        code: {
          file: "greet.rs",
          code: [
            "trait Greet {",
            "  fn hello(&self) -> String;",
            "}",
            "impl Greet for User {",
            "  fn hello(&self) -> String {",
            "    format!(\"hi {}\", self.name)",
            "  }",
            "}",
          ],
          notes: [
            { h: "Contract", text: "Greet lists methods types must provide" },
            { h: "impl", text: "Each type writes its own body" },
            { h: "Bound", text: "T: Greet lets you call hello" },
          ],
        },
        footer: "Traits are how Rust does shared behavior without inheritance",
      },
    },
    {
      q: "What is Cargo and what is a crate?",
      a: "Cargo is the build tool and package manager. A crate is a compilation unit (binary or library). A package can contain several crates; crates.io hosts libraries.",
      e: "Cargo.toml lists deps and features. cargo test, clippy, and rustfmt are the interview-expected workflow, not ad-hoc rustc flags.",
      visual: {
        title: "Crate lifecycle",
        kind: "cycle",
        center: "cargo",
        items: [
          { h: "toml", lines: ["Name deps features"] },
          { h: "fetch", lines: ["Lockfile pins versions"] },
          { h: "build", lines: ["rustc the graph"] },
          { h: "test", lines: ["cargo test"] },
          { h: "publish", lines: ["crates.io"] },
        ],
        footer: "The crate is the compile unit — the package is the Cargo project",
      },
    },
    {
      q: "How do modules and visibility work?",
      a: "mod declares a module. Items are private by default. pub exposes them to parents; pub(crate) keeps them inside the crate.",
      e: "Paths use :: . use brings names into scope. The module tree is not the file tree one-to-one, but src/lib.rs and src/foo.rs are the usual layout.",
      visual: {
        title: "Visibility layers",
        kind: "layers",
        layers: [
          { h: "private (default)", lines: ["Only the current module"] },
          { h: "pub(crate)", lines: ["Anywhere in this crate"] },
          { h: "pub(super)", lines: ["Parent module only"] },
          { h: "pub", lines: ["Other crates can import"] },
        ],
        footer: "Start private — widen with pub only at the API boundary",
      },
    },
    {
      q: "What is the path from cargo build to a running binary?",
      a: "Cargo resolves deps, invokes rustc, links native code, and writes target/. Dev, test, and release profiles change optimization and debuginfo.",
      e: "release turns on LTO options and inlining. Incremental debug builds are for iteration. Know cargo check as the fast typecheck.",
      visual: {
        title: "From sources to binary",
        kind: "timeline",
        events: [
          { h: "Resolve", lines: ["Cargo.lock + features"] },
          { h: "Compile", lines: ["rustc crates in order"] },
          { h: "Link", lines: ["Native + Rust objects"] },
          { h: "Run", lines: ["target/debug or release"] },
        ],
        footer: "cargo check skips codegen when you only need the checker",
      },
    },
    {
      q: "What are Rust’s scalar and compound types?",
      a: "Scalars: integers, floats, bool, char (Unicode scalar). Compounds: tuples, arrays (fixed), slices, structs, enums. String is owned UTF-8; &str is a borrow.",
      e: "char is 4 bytes, not a UTF-8 byte. Arrays are [T; N]; Vec<T> is the growable heap list. Prefer &str in APIs unless you need to keep the string.",
      visual: {
        title: "Core type map",
        kind: "hub",
        hub: "Types",
        nodes: [
          { h: "i32 / u64", lines: ["Fixed integers"] },
          { h: "bool", lines: ["true / false"] },
          { h: "char", lines: ["Unicode scalar"] },
          { h: "tuple", lines: ["Fixed positions"] },
          { h: "String", lines: ["Owned UTF-8"] },
          { h: "&str", lines: ["Borrowed text"] },
        ],
        footer: "String owns · &str borrows — do not confuse them in signatures",
      },
    },
  ],
  intermediate: [
    {
      q: "What are lifetimes?",
      a: "A lifetime is a region the compiler uses to prove a reference is valid. 'a in &'a T names that region. They are not runtime clocks.",
      e: "You write lifetimes when the checker cannot see which input a returned reference comes from. Most functions elide them. They never appear in the binary.",
      visual: {
        title: "Name the borrow region",
        kind: "code",
        code: {
          file: "long.rs",
          code: [
            "fn longest<'a>(",
            "  x: &'a str,",
            "  y: &'a str,",
            ") -> &'a str {",
            "  if x.len() > y.len()",
            "    { x } else { y }",
            "}",
          ],
          notes: [
            { h: "Param", text: "'a is the same region for both inputs" },
            { h: "Return", text: "Output cannot outlive either borrow" },
            { h: "Erase", text: "No lifetime data in the binary" },
          ],
        },
        footer: "Lifetimes are compile-time regions — not a stopwatch",
      },
    },
    {
      q: "What is lifetime elision?",
      a: "Elision rules fill in 'a for common patterns so you rarely write lifetimes. One input borrow often becomes the output’s lifetime automatically.",
      e: "Multiple input borrows that both feed a returned reference need an explicit annotation. Methods elide &self as the obvious source. Learn the rules; do not fear 'a.",
      visual: {
        title: "Elision then annotate",
        kind: "steps",
        steps: [
          { h: "One input", lines: ["fn f(s: &str) -> &str"] },
          { h: "Elide", lines: ["Same 'a inferred"] },
          { h: "Two inputs", lines: ["Which borrow returns?"] },
          { h: "Write 'a", lines: ["Make the contract explicit"] },
        ],
        footer: "Write lifetimes when two borrows could be the source",
      },
    },
    {
      q: "When do you use Box, Rc, and Arc?",
      a: "Box<T> is a unique heap owner. Rc<T> is single-thread shared ownership via refcount. Arc<T> is the atomic version for threads.",
      e: "Rc/Arc give shared ownership, not mutation. Pair with RefCell or Mutex when you need mutation. Cycles leak unless you use Weak.",
      visual: {
        title: "Box vs Rc vs Arc",
        kind: "compare",
        left: {
          h: "Box / Rc",
          lines: ["Box: one owner, heap", "Rc: clone the pointer", "Not Send/Sync", "Graphs · trees"],
        },
        right: {
          h: "Arc",
          lines: ["Atomic refcount", "Share across threads", "Pair with Mutex", "More expensive clone"],
        },
        footer: "Unique → Box · same thread share → Rc · threads → Arc",
      },
    },
    {
      q: "What are the common smart pointers?",
      a: "Box, Rc, Arc, Cow, and the interior-mutability wrappers Cell, RefCell, Mutex, RwLock. They encode ownership and aliasing in the type.",
      e: "Cow<'a, T> clones only on write. Mutex<T> is the usual Arc partner. Prefer borrowing over smart pointers until sharing is required.",
      visual: {
        title: "Smart pointer toolbox",
        kind: "hub",
        hub: "Pointers",
        nodes: [
          { h: "Box", lines: ["Unique heap"] },
          { h: "Rc", lines: ["Thread-local share"] },
          { h: "Arc", lines: ["Cross-thread share"] },
          { h: "RefCell", lines: ["Runtime borrow"] },
          { h: "Mutex", lines: ["Lock then mutate"] },
          { h: "Cow", lines: ["Clone on write"] },
        ],
        footer: "The pointer type is the aliasing contract — pick it on purpose",
      },
    },
    {
      q: "How does Drop and RAII work?",
      a: "When the owner leaves scope, Drop::drop runs. Files, locks, and buffers release in reverse order of declaration. This is RAII — cleanup tied to lifetime.",
      e: "mem::forget skips Drop (leaks). ManuallyDrop defers it. Do not panic while holding a Mutex without knowing poisoning rules.",
      visual: {
        title: "Scope ends, Drop runs",
        kind: "timeline",
        events: [
          { h: "Create", lines: ["Owner binding starts"] },
          { h: "Use", lines: ["Borrows must end first"] },
          { h: "Scope end", lines: ["drop is called"] },
          { h: "Free", lines: ["Resource released"] },
        ],
        footer: "RAII means the type system schedules cleanup for you",
      },
    },
    {
      q: "What is interior mutability?",
      a: "Interior mutability lets you mutate through a shared reference when the type enforces aliasing at runtime or with atomics: Cell, RefCell, Mutex, atomics.",
      e: "RefCell panics on overlapping borrows in debug/runtime. Mutex blocks. Cell is Copy-only swaps. Use it when the checker is wrong about your aliasing, not to dodge it.",
      visual: {
        title: "Mutate behind &T",
        kind: "layers",
        layers: [
          { h: "Cell<T>", lines: ["Copy in/out · no borrow flags"] },
          { h: "RefCell<T>", lines: ["Runtime borrow counter · can panic"] },
          { h: "Mutex / RwLock", lines: ["Block until exclusive or shared"] },
          { h: "Atomic*", lines: ["Lock-free integers and flags"] },
        ],
        footer: "Interior mutability moves the aliasing check to runtime or hardware",
      },
    },
    {
      q: "How do iterators work in Rust?",
      a: "Iterator yields Item until None. Adapters (map, filter) are lazy; consumers (collect, sum, for) drive them. for x in v uses IntoIterator.",
      e: "Zero-cost: adapters compose into one loop after inlining. Prefer iterators over index math. &mut self iterators cannot alias the collection.",
      visual: {
        title: "Lazy adapter pipeline",
        kind: "cycle",
        center: "next()",
        items: [
          { h: "Source", lines: ["vec.iter()"] },
          { h: "map", lines: ["Transform item"] },
          { h: "filter", lines: ["Keep some"] },
          { h: "collect", lines: ["Drive the chain"] },
          { h: "Done", lines: ["None ends it"] },
        ],
        footer: "Nothing runs until a consumer pulls — then it fuses into a loop",
      },
    },
    {
      q: "How do generics and trait bounds work together?",
      a: "fn f<T: Display>(x: T) means T must implement Display. where clauses keep signatures readable. Multiple bounds are T: A + B.",
      e: "Monomorphization copies the function per type (fast, larger binary). Trait objects (dyn Trait) erase to one copy and vtable. Pick static vs dynamic dispatch on purpose.",
      visual: {
        title: "Bound the type parameter",
        kind: "code",
        code: {
          file: "print.rs",
          code: [
            "fn show<T: std::fmt::Display>(",
            "  value: T,",
            ") {",
            "  println!(\"{value}\");",
            "}",
            "show(3);",
            "show(\"ok\");",
          ],
          notes: [
            { h: "Bound", text: "T: Display unlocks to_string / format" },
            { h: "Mono", text: "rustc stamps a copy per T" },
            { h: "where", text: "Move long bounds off the fn line" },
          ],
        },
        footer: "Bounds are the API — monomorphization is the implementation",
      },
    },
    {
      q: "How should you propagate errors with ? ?",
      a: "? on a Result returns early on Err after converting via From. Functions that use ? must return Result (or Option with a compatible ?).",
      e: "thiserror for library error enums; anyhow for apps. Do not unwrap in libraries. Map errors at boundaries so callers see a stable E.",
      visual: {
        title: "Bubble Err with ?",
        kind: "steps",
        steps: [
          { h: "Call", lines: ["fallible()?"] },
          { h: "Ok", lines: ["Unwrap the value"] },
          { h: "Err", lines: ["From::from then return"] },
          { h: "Caller", lines: ["Handles or bubbles"] },
        ],
        footer: "? is sugar for match + return — From is the conversion hook",
      },
    },
    {
      q: "What is the difference between impl Trait and dyn Trait?",
      a: "impl Trait in return position is an opaque concrete type (static dispatch). dyn Trait is a trait object with a vtable (dynamic dispatch).",
      e: "impl Trait cannot be named by callers and is one type. dyn Trait needs a pointer (Box, &) and object safety. Use dyn for heterogeneous collections.",
      visual: {
        title: "impl Trait vs dyn Trait",
        kind: "compare",
        left: {
          h: "impl Trait",
          lines: ["One hidden type", "Static dispatch", "No vtable", "Fast · monomorphized"],
        },
        right: {
          h: "dyn Trait",
          lines: ["Many types, one slot", "Virtual calls", "Must be object-safe", "Needs & or Box"],
        },
        footer: "Opaque static vs erased dynamic — both are trait bounds, different ABI",
      },
    },
    {
      q: "What should you know about the trait system?",
      a: "Coherence (orphan rule): you can impl a trait for a type only if you own the trait or the type. Associated types name an output; generics parameterize input.",
      e: "Orphan rules keep crates from colliding impls. Newtypes wrap foreign types so you can impl your traits. Supertraits (trait Sub: Super) require the parent.",
      visual: {
        title: "Trait system map",
        kind: "hub",
        hub: "Traits",
        nodes: [
          { h: "Orphan", lines: ["Own trait or type"] },
          { h: "Newtype", lines: ["Wrap to impl"] },
          { h: "Assoc type", lines: ["Output of the trait"] },
          { h: "Generic", lines: ["Input parameters"] },
          { h: "Derive", lines: ["Debug · Clone"] },
          { h: "Supertrait", lines: ["Must impl parent"] },
        ],
        footer: "Coherence is why you newtype foreign types to add methods",
      },
    },
    {
      q: "How does async/await work at an intermediate level?",
      a: "async fn returns impl Future. .await yields until the future is ready. Futures are lazy — nothing runs until polled by an executor (tokio, async-std).",
      e: "The compiler rewrites async into a state machine enum. Holding a borrow across .await requires the future to be pinned. Do not block the executor with sync IO.",
      visual: {
        title: "From async fn to poll",
        kind: "timeline",
        events: [
          { h: "async fn", lines: ["Returns a Future"] },
          { h: ".await", lines: ["Yield if Pending"] },
          { h: "Executor", lines: ["polls when woken"] },
          { h: "Ready", lines: ["Value or error"] },
        ],
        footer: "Futures do nothing until an executor polls them",
      },
    },
    {
      q: "What are Send and Sync?",
      a: "Send means a value can move to another thread. Sync means &T can be shared across threads (T is Send if &T is Sync, roughly). rustc auto-implements them.",
      e: "Rc is !Send + !Sync. Arc is Send + Sync when T is. Mutex<T> is Sync if T is Send. Interviewers want this chain, not a slogan.",
      visual: {
        title: "Thread-safety markers",
        kind: "layers",
        layers: [
          { h: "Send", lines: ["OK to transfer ownership to another thread"] },
          { h: "Sync", lines: ["OK to share &T across threads"] },
          { h: "Auto traits", lines: ["Implemented if all fields qualify"] },
          { h: "Opt out", lines: ["PhantomData<*const ()> to suppress"] },
        ],
        footer: "Send/Sync are the type-level API of the thread boundary",
      },
    },
    {
      q: "What does a Tokio-style runtime do?",
      a: "It parks tasks, polls ready futures, and multiplexes IO. Multi-thread runtimes steal work; current-thread is simpler for !Send tasks.",
      e: "spawn requires Send + 'static futures. block_in_place / spawn_blocking is for CPU or sync IO. Know runtime flavor when a test hangs.",
      visual: {
        title: "Executor loop",
        kind: "cycle",
        center: "poll",
        items: [
          { h: "Spawn", lines: ["Queue a task"] },
          { h: "Wake", lines: ["IO or timer fires"] },
          { h: "Poll", lines: ["Drive the Future"] },
          { h: "Pending", lines: ["Sleep until wake"] },
          { h: "Ready", lines: ["Drop the task"] },
        ],
        footer: "The runtime is a poll loop plus a reactor — not magic threads",
      },
    },
    {
      q: "How do declarative macros work?",
      a: "macro_rules! matches token trees and transcribes code. They are hygienic for local variables. Use them for repetitive impls and DSLs, not for logic.",
      e: "Matchers: $x:expr, $t:ty, $($x:tt)*. Debugging with cargo expand is expected. Prefer functions when a normal API works — macros hide types.",
      visual: {
        title: "macro_rules! expand",
        kind: "code",
        code: {
          file: "vec_mac.rs",
          code: [
            "macro_rules! mini_vec {",
            "  ( $( $x:expr ),* ) => {",
            "    {",
            "      let mut v = Vec::new();",
            "      $( v.push($x); )*",
            "      v",
            "    }",
            "  };",
            "}",
          ],
          notes: [
            { h: "Match", text: "$x:expr captures each item" },
            { h: "Repeat", text: "$( ... )* copies the push" },
            { h: "Hygiene", text: "v inside does not leak out" },
          ],
        },
        footer: "Declarative macros rewrite tokens — they are not functions",
      },
    },
  ],
  expert: [
    {
      q: "How is unsafe Rust layered, and what is undefined behavior?",
      a: "unsafe lets you dereference raw pointers, call unsafe fns, access mut statics, and implement unsafe traits. You must uphold the invariants the checker skipped.",
      e: "UB includes data races, invalid enums, misaligned pointers, and violating stacked borrows / Tree Borrows. Keep unsafe blocks tiny and document the safety comment.",
      visual: {
        title: "Safe wrapper over unsafe core",
        kind: "layers",
        layers: [
          { h: "Safe API", lines: ["Types that cannot be misused"] },
          { h: "Tiny unsafe", lines: ["Documented invariants"] },
          { h: "Raw ops", lines: ["Pointers · FFI · unions"] },
          { h: "Hardware", lines: ["UB if the contract lies"] },
        ],
        footer: "unsafe is a contract with the optimizer — not a permission slip",
      },
    },
    {
      q: "Why does Pin exist?",
      a: "Pin<P> promises the pinned value will not be moved in memory. Self-referential futures need that: interior pointers would dangle after a move.",
      e: "Unpin means “moving is still fine” (most types). !Unpin types (many futures) must be polled through Pin<&mut Self>. pin_mut! / Box::pin are the usual tools.",
      visual: {
        title: "Pin so addresses stay put",
        kind: "timeline",
        events: [
          { h: "Build Future", lines: ["May store self refs"] },
          { h: "Pin it", lines: ["Box::pin or pin!"] },
          { h: "poll", lines: ["Pin<&mut Self>"] },
          { h: "Never move", lines: ["Until dropped"] },
        ],
        footer: "Pin is a move lock for types the compiler rewrote with self-refs",
      },
    },
    {
      q: "What are the five unsafe superpowers?",
      a: "Dereference raw pointers, call unsafe functions/methods, access or modify mutable statics, implement unsafe traits, and access fields of unions.",
      e: "None of these are required for everyday Rust. Interviews want the list plus “wrap it so callers stay in safe Rust.” Miri can catch some UB in tests.",
      visual: {
        title: "unsafe superpowers",
        kind: "hub",
        hub: "unsafe",
        nodes: [
          { h: "*const / *mut", lines: ["Deref raw pointers"] },
          { h: "unsafe fn", lines: ["Call unchecked code"] },
          { h: "static mut", lines: ["Aliasing hazard"] },
          { h: "unsafe trait", lines: ["Promise extra laws"] },
          { h: "union", lines: ["Reinterpret fields"] },
          { h: "Wrap", lines: ["Safe API outside"] },
        ],
        footer: "Five powers — still no license to create data races",
      },
    },
    {
      q: "How do Send and Sync interact in concurrent types?",
      a: "T: Sync means &T is Send. Mutex<T>: Sync if T: Send (the lock serializes). RwLock needs T: Send + Sync for shared reads. Cell is Send if T is, but never Sync.",
      e: "A type with an Rc inside is !Send. PhantomData<Cell<T>> can opt out of Sync. Expert answers mention auto traits and how wrappers change them.",
      visual: {
        title: "Send vs Sync in locks",
        kind: "compare",
        left: {
          h: "Send",
          lines: ["Move value to a thread", "MutexGuard is often !Send", "Rc is !Send", "Closures capture rules"],
        },
        right: {
          h: "Sync",
          lines: ["Share &T across threads", "Mutex<T> if T: Send", "Arc<T> if T: Send+Sync", "Cell is never Sync"],
        },
        footer: "Locks restore Sync by making mutation exclusive",
      },
    },
    {
      q: "How do Pin and Future fit together?",
      a: "Future::poll takes Pin<&mut Self>. The executor pins the task, then polls. Moving a !Unpin future after polling is UB because self-refs would dangle.",
      e: "pin-project (or pin-project-lite) projects fields safely. Unpin impls must not be lied about. This is the usual expert async follow-up after “what is a Future.”",
      visual: {
        title: "poll under Pin",
        kind: "code",
        code: {
          file: "poll.rs",
          code: [
            "use std::pin::Pin;",
            "use std::task::{Context, Poll};",
            "trait Future {",
            "  type Output;",
            "  fn poll(",
            "    self: Pin<&mut Self>,",
            "    cx: &mut Context<'_>,",
            "  ) -> Poll<Self::Output>;",
            "}",
          ],
          notes: [
            { h: "Receiver", text: "Pin<&mut Self> not &mut self" },
            { h: "Wake", text: "cx.waker() for later poll" },
            { h: "State", text: "Compiler-built enum of awaits" },
          ],
        },
        footer: "If it is !Unpin, poll is the only safe way to mutate it",
      },
    },
    {
      q: "How do you write sound unsafe code?",
      a: "Minimize the block, write a // SAFETY: comment with invariants, fuzz/Miri, and keep raw pointers derived from valid references with the right provenance.",
      e: "Never return a reference derived from a freed buffer. Encapsulate so safe callers cannot break the invariant. Treat stacked-borrows violations as bugs.",
      visual: {
        title: "Sound unsafe checklist",
        kind: "steps",
        steps: [
          { h: "Shrink", lines: ["Smallest possible block"] },
          { h: "Document", lines: ["// SAFETY: invariants"] },
          { h: "Wrap", lines: ["Safe public API"] },
          { h: "Test", lines: ["Miri · sanitizers"] },
        ],
        footer: "If a safe caller can trigger UB, the wrapper is unsound",
      },
    },
    {
      q: "How is an async function lowered to a state machine?",
      a: "Each .await is a variant. Locals that live across await become struct fields. poll matches the current state, runs until the next yield, then returns Pending.",
      e: "That generated struct is often !Unpin. Holding a reference to a local across .await is why the compiler demands the future stays pinned.",
      visual: {
        title: "Await as enum states",
        kind: "cycle",
        center: "poll",
        items: [
          { h: "State0", lines: ["Run until await"] },
          { h: "Pending", lines: ["Save locals"] },
          { h: "Wake", lines: ["Executor resumes"] },
          { h: "StateN", lines: ["Next fragment"] },
          { h: "Ready", lines: ["Return Output"] },
        ],
        footer: "async is syntax — the ABI is poll on a generated enum",
      },
    },
    {
      q: "What is variance in Rust lifetimes and types?",
      a: "Variance says when &'a T can substitute for &'b T. Shared refs are covariant in T and in 'a; mut refs are invariant in T so you cannot shorten or lengthen unsoundly.",
      e: "fn(T) is contravariant in T. PhantomData<T> inherits T’s variance. Getting this wrong in unsafe wrappers is a classic soundness hole (see std’s old Vec story).",
      visual: {
        title: "Variance you must not lie about",
        kind: "layers",
        layers: [
          { h: "Covariant", lines: ["&'a T · subtype can lengthen 'a"] },
          { h: "Invariant", lines: ["&mut T · no subtyping in T"] },
          { h: "Contravariant", lines: ["fn(T) · accepts a supertype"] },
          { h: "PhantomData", lines: ["Pick variance for raw wrappers"] },
        ],
        footer: "Unsafe containers must declare variance with PhantomData",
      },
    },
    {
      q: "When do Drop, forget, and ManuallyDrop matter?",
      a: "Drop always runs on scope exit unless you forget, wrap in ManuallyDrop, or mem::replace away. Double-drop is UB for many types; leaks are usually defined.",
      e: "Arc/Rc cycles leak by design. catch_unwind still drops. In unsafe, dropping a moved-from value twice is the usual disaster — use ptr::read / ManuallyDrop.",
      visual: {
        title: "Teardown paths",
        kind: "timeline",
        events: [
          { h: "Normal", lines: ["Drop at end of scope"] },
          { h: "forget", lines: ["Skip Drop · leak"] },
          { h: "ManuallyDrop", lines: ["You call drop later"] },
          { h: "Unwind", lines: ["Drop still runs"] },
        ],
        footer: "Leaks are allowed — double free is not",
      },
    },
    {
      q: "Which concurrency primitives should you reach for?",
      a: "thread::spawn + JoinHandle, channels (mpsc / crossbeam), Mutex/RwLock, atomics, Condvar, and parking_lot in apps. async uses its own Notify and channels.",
      e: "Do not mix blocking locks with async without spawn_blocking. Atomics need an Ordering story (Acquire/Release vs SeqCst). Poisoning means a panicking holder.",
      visual: {
        title: "Concurrency toolbox",
        kind: "hub",
        hub: "Threads",
        nodes: [
          { h: "spawn", lines: ["OS thread"] },
          { h: "mpsc", lines: ["Message passing"] },
          { h: "Mutex", lines: ["Exclusive data"] },
          { h: "RwLock", lines: ["Many readers"] },
          { h: "Atomic", lines: ["Lock-free flags"] },
          { h: "Join", lines: ["Wait for result"] },
        ],
        footer: "Share by communicating — lock only the bytes that must be shared",
      },
    },
    {
      q: "Mutex vs RwLock vs atomics — how do you choose?",
      a: "Mutex for exclusive mutation of one value. RwLock when reads dominate and you can tolerate writer starvation. Atomics for integers/flags without a lock.",
      e: "RwLock can be slower on short critical sections. parking_lot avoids poisoning. Never hold a lock across .await. SeqCst is the interview-safe default until measured.",
      visual: {
        title: "Lock vs atomic",
        kind: "compare",
        left: {
          h: "Mutex / RwLock",
          lines: ["Protect a whole T", "Can wait / park", "Poison on panic (std)", "Easy to reason"],
        },
        right: {
          h: "Atomics",
          lines: ["Word-sized ops", "Ordering matters", "No lock, no poison", "Easy to get wrong"],
        },
        footer: "If it is more than a word or a flag, start with Mutex",
      },
    },
    {
      q: "How do procedural macros differ from macro_rules?",
      a: "Proc macros are Rust functions that take a TokenStream and return one. They run at compile time as a separate crate (proc-macro = true). Derive, attribute, and function-like forms exist.",
      e: "syn + quote are the usual stack. They can break hygiene and compile times. Keep them deterministic and fast; prefer declarative macros when pattern rewrite is enough.",
      visual: {
        title: "Proc-macro crate",
        kind: "code",
        code: {
          file: "lib.rs",
          code: [
            "#[proc_macro_derive(Hello)]",
            "pub fn hello(",
            "  item: TokenStream,",
            ") -> TokenStream {",
            "  // parse · emit tokens",
            "  item",
            "}",
          ],
          notes: [
            { h: "Crate", text: "Separate proc-macro library" },
            { h: "When", text: "Runs in rustc, not at runtime" },
            { h: "Forms", text: "derive · attribute · function-like" },
          ],
        },
        footer: "Proc macros are compilers you ship — keep them boring",
      },
    },
    {
      q: "What is monomorphization, and when do you avoid it?",
      a: "Generics become specialized copies per type (static dispatch). That inlines and optimizes, but duplicates code (LLVM bloat). dyn Trait keeps one copy.",
      e: "Hot numeric code wants mono. Plugin lists and huge generic graphs want dyn or explicit inner non-generic functions (trick to shrink codegen).",
      visual: {
        title: "Specialize or erase",
        kind: "steps",
        steps: [
          { h: "Write <T>", lines: ["One source function"] },
          { h: "Instantiate", lines: ["Copy per T"] },
          { h: "Optimize", lines: ["Inline · no vtable"] },
          { h: "Or erase", lines: ["dyn Trait · one copy"] },
        ],
        footer: "Zero-cost means you pay in binary size, not in a vtable — unless you choose dyn",
      },
    },
    {
      q: "What are higher-ranked trait bounds (HRTB)?",
      a: "for<'a> T: Trait<'a> means T implements Trait for every lifetime, not one specific 'a. Closures that accept any borrow use Fn(&T) which desugars to HRTB.",
      e: "You need HRTB when a trait has a lifetime parameter and callers must work with short borrows. Error messages are famously bad — name the bound in a helper trait if needed.",
      visual: {
        title: "for<'a> means every lifetime",
        kind: "cycle",
        center: "for<'a>",
        items: [
          { h: "Short", lines: ["Works with 'short"] },
          { h: "Long", lines: ["Works with 'long"] },
          { h: "Caller", lines: ["Picks each borrow"] },
          { h: "Fn(&T)", lines: ["Desugars to HRTB"] },
          { h: "Fail", lines: ["Only one 'a is not enough"] },
        ],
        footer: "HRTB is “this works for any borrow you hand me”",
      },
    },
    {
      q: "How do you FFI with C safely?",
      a: "#[repr(C)] matches C layout. extern \"C\" fn is the ABI. Pointers crossing the boundary are unsafe; convert to slices with documented lengths. Bindgen generates the thin layer.",
      e: "Do not pass String as char* without CString. Panic across FFI is UB. Own the allocation story (who frees). cbindgen for the reverse direction.",
      visual: {
        title: "FFI boundary layers",
        kind: "layers",
        layers: [
          { h: "Safe Rust API", lines: ["Slices · Result · owned types"] },
          { h: "repr(C) structs", lines: ["Layout the C compiler expects"] },
          { h: "extern \"C\"", lines: ["ABI · no_mangle names"] },
          { h: "C world", lines: ["Who allocates · who frees"] },
        ],
        footer: "The unsafe line is the ABI — keep it thinner than the safe wrapper",
      },
    },
  ],
};
