module.exports = {
  name: "Scala",
  description:
    "Scala interview questions — JVM, case classes, implicits/givens, collections, and type-level patterns.",
  match: /^scala$/i,
  theme: {
    accent: "#DC322F",
    hubFill: "#DC322F",
    hubText: "#ffffff",
    centerFill: "#fee2e2",
    centerStroke: "#DC322F",
    label: "Scala",
  },
  beginner: [
    {
      q: "What is Scala and how does it relate to the JVM?",
      a: "Scala is a statically typed language that compiles to JVM bytecode (and also JS/Native). It mixes object-oriented and functional styles on the same runtime as Java.",
      e: "You get Java libraries, threads, GC, and tooling (jar, Maven/sbt). Types erase like Java’s. Interviews expect ‘runs on the JVM’ plus ‘more than Java syntax’.",
      visual: {
        title: "Scala on the JVM",
        kind: "hub",
        hub: "Scala",
        nodes: [
          { h: "scalac", lines: ["Emits .class"] },
          { h: "JVM", lines: ["HotSpot · GC"] },
          { h: "Java libs", lines: ["Interop"] },
          { h: "sbt / Mill", lines: ["Build"] },
          { h: "FP + OO", lines: ["One language"] },
          { h: "Spark", lines: ["Big data (light)"] },
        ],
        footer: "Same bytecode runtime — richer language on top",
      },
    },
    {
      q: "What is the difference between val and var?",
      a: "val is a final binding — you cannot reassign the name. var can be reassigned. Immutability of the name is not the same as immutability of the object.",
      e: "Prefer val. A val List is still a reference to an immutable collection; a val StringBuilder can still mutate internally. var is a smell in most Scala code.",
      visual: {
        title: "val vs var",
        kind: "compare",
        left: {
          h: "val",
          lines: ["Name cannot rebind", "Default in FP style", "Thread-friendlier", "Use almost always"],
        },
        right: {
          h: "var",
          lines: ["Name can rebind", "Local mutation", "Harder to reason", "Rare on purpose"],
        },
        footer: "val locks the binding — not always the bytes inside",
      },
    },
    {
      q: "How do you declare values and infer types?",
      a: "val n = 3 infers Int. You can annotate val n: Int = 3. Public APIs should often show types; locals can infer.",
      e: "Unit is the void-like type. Nothing is the bottom type. Prefer explicit types on public members so binary/API compatibility stays obvious.",
      visual: {
        title: "val and inference",
        kind: "code",
        code: {
          file: "vals.scala",
          code: [
            "val n = 3          // Int",
            "val s: String = \"hi\"",
            "var count = 0",
            "count += 1",
          ],
          notes: [
            { h: "Infer", text: "Locals usually skip annotations" },
            { h: "Annotate", text: "Public APIs and tricky bounds" },
            { h: "var", text: "Rebind count; still an Int" },
          ],
        },
        footer: "Inference is local — signatures are the contract",
      },
    },
    {
      q: "What happens from Scala source to a running JVM?",
      a: "scalac (or Zinc via sbt) emits .class files, often packaged into a JAR. The JVM loads classes and JIT-compiles hot bytecode.",
      e: "Scala 3 also emits TASTy (typed ASTs) for incremental compile and macros. You still debug with jdb/Java tools; stack frames show generated names ($anon, $eq).",
      visual: {
        title: "Source to JVM",
        kind: "steps",
        steps: [
          { h: ".scala", lines: ["Your source"] },
          { h: "scalac", lines: [".class + TASTy"] },
          { h: "JAR", lines: ["sbt package"] },
          { h: "JVM", lines: ["Load · JIT · GC"] },
        ],
        footer: "Runtime is the JVM — Scala is the compiler and stdlib",
      },
    },
    {
      q: "What is the difference between a class and an object?",
      a: "class defines a blueprint you new (or construct). object is a singleton — one instance, lazy on first access, used for modules and main entry points.",
      e: "A companion object shares the class name and can see private members. Apply methods on the companion act like factories: User(1) instead of new User(1).",
      visual: {
        title: "class vs object",
        kind: "compare",
        left: {
          h: "class",
          lines: ["Many instances", "Constructor params", "Fields per object", "new or apply"],
        },
        right: {
          h: "object",
          lines: ["One singleton", "Lazy init", "Module / main", "Companion factory"],
        },
        footer: "Companions pair a type with its module",
      },
    },
    {
      q: "What is Scala’s type hierarchy at a glance?",
      a: "Any is the top. AnyVal (Int, Boolean, Unit, …) and AnyRef (all objects, Java Object) sit under it. Null is a subtype of all AnyRef. Nothing subtypes everything.",
      e: "null is a value of type Null — avoid it; use Option. Nothing is the type of throw. Unit is () — like void but a real value.",
      visual: {
        title: "Any at the top",
        kind: "layers",
        layers: [
          { h: "Any", lines: ["Top of the hierarchy"] },
          { h: "AnyVal | AnyRef", lines: ["Primitives vs objects"] },
          { h: "Null", lines: ["Subtype of all AnyRef"] },
          { h: "Nothing", lines: ["Bottom — no instances"] },
        ],
        footer: "Option instead of null is the Scala default",
      },
    },
    {
      q: "What is a case class?",
      a: "A case class is an immutable product type: constructor args become vals, plus equals/hashCode/toString, a copy method, and a companion with apply/unapply for pattern matching.",
      e: "They are the default for data. Don’t make them mutable. For one instance with identity, a regular class (or enum in Scala 3) may be better.",
      visual: {
        title: "Case class sugar",
        kind: "code",
        code: {
          file: "user.scala",
          code: [
            "case class User(id: Int, name: String)",
            "val u = User(1, \"Ada\")",
            "u.copy(name = \"Al\")",
            "u match { case User(i, n) => i }",
          ],
          notes: [
            { h: "apply", text: "No new required" },
            { h: "copy", text: "Named updates, new instance" },
            { h: "unapply", text: "Enables pattern matching" },
          ],
        },
        footer: "Case classes are immutable records with matching",
      },
    },
    {
      q: "How do you run a small Scala program with sbt?",
      a: "Put sources under src/main/scala, define scalaVersion in build.sbt, then sbt compile / run / test. sbt is the usual build and dependency tool.",
      e: "Mill and Maven exist. For interviews, know scalaVersion, libraryDependencies, and that Spark jobs are still just JVM programs with extra cluster submit.",
      visual: {
        title: "sbt loop",
        kind: "timeline",
        events: [
          { h: "build.sbt", lines: ["scalaVersion · deps"] },
          { h: "compile", lines: ["Zinc incremental"] },
          { h: "test", lines: ["ScalaTest / MUnit"] },
          { h: "run / package", lines: ["App or JAR"] },
        ],
        footer: "sbt ~compile watches; CI runs compile test",
      },
    },
    {
      q: "How do common Scala collections relate?",
      a: "Seq, Set, and Map are the big families. List is an immutable linked list; Vector is a wide tree (better random access); Array is mutable JVM array.",
      e: "Default to immutable.scala.collection.immutable. conversion .toList / .toVector is explicit. Java converters live in scala.jdk.CollectionConverters.",
      visual: {
        title: "Collection families",
        kind: "cycle",
        center: "Iterable",
        items: [
          { h: "List", lines: ["Linked, prepend"] },
          { h: "Vector", lines: ["Fast index"] },
          { h: "Map", lines: ["Hash / Tree"] },
          { h: "Set", lines: ["Unique"] },
          { h: "Array", lines: ["Mutable JVM"] },
          { h: "LazyList", lines: ["Lazy seq"] },
        ],
        footer: "Immutable by default — Array when you need JVM mutability",
      },
    },
    {
      q: "What is Option and why not null?",
      a: "Option[T] is Some(value) or None. It forces callers to handle absence. map/flatMap/getOrElse replace null checks.",
      e: "Java interop still produces null — wrap with Option(x). Avoid Option.get. For errors with a message, Prefer Either or Try.",
      visual: {
        title: "Absence as a type",
        kind: "hub",
        hub: "Option",
        nodes: [
          { h: "Some", lines: ["A value"] },
          { h: "None", lines: ["Missing"] },
          { h: "map", lines: ["Transform if present"] },
          { h: "flatMap", lines: ["Chain Options"] },
          { h: "getOrElse", lines: ["Default"] },
          { h: "fold", lines: ["Both branches"] },
        ],
        footer: "The type system reminds you absence is possible",
      },
    },
    {
      q: "How does pattern matching work?",
      a: "match compares a value against cases: constants, wildcards, constructors (case classes), and guards. It is an expression that returns a value.",
      e: "Sealed traits/enums make matches exhaustive — the compiler warns on missing cases. Unapply is how case classes destructure.",
      visual: {
        title: "match expression",
        kind: "code",
        code: {
          file: "match.scala",
          code: [
            "def label(x: Int): String = x match {",
            "  case 0 => \"zero\"",
            "  case n if n < 0 => \"neg\"",
            "  case _ => \"pos\"",
            "}",
          ],
          notes: [
            { h: "Expression", text: "match returns a value" },
            { h: "Guard", text: "if n < 0 refines the case" },
            { h: "_", text: "Wildcard default" },
          ],
        },
        footer: "Sealed types turn missing cases into compile errors",
      },
    },
    {
      q: "What is a trait?",
      a: "A trait is a mixin: abstract and concrete members, inherited by classes and other traits. Scala allows multiple trait mixins (linearization resolves the order).",
      e: "Traits can have parameters in Scala 3. Prefer traits for behavior; classes for constructible types. Java interfaces map closely but traits can have state.",
      visual: {
        title: "Mixin a trait",
        kind: "steps",
        steps: [
          { h: "Define trait", lines: ["methods + optional body"] },
          { h: "extends / with", lines: ["Mix into a class"] },
          { h: "Linearize", lines: ["Right-first super"] },
          { h: "Call super", lines: ["Stackable mods"] },
        ],
        footer: "Multiple traits — one class linearization",
      },
    },
    {
      q: "How does a companion object work?",
      a: "An object with the same name as a class, in the same file, can access private members and usually holds apply, factories, and implicit/given instances.",
      e: "This is how case class apply is generated. Type-class instances often live in the companion so they are found without imports (Scala 2 implicits / Scala 3 givens).",
      visual: {
        title: "Type and module together",
        kind: "layers",
        layers: [
          { h: "class User", lines: ["Per-instance state"] },
          { h: "object User", lines: ["apply · givens · helpers"] },
          { h: "private sharing", lines: ["Companions see each other"] },
        ],
        footer: "Same name, same file — factory and type sit together",
      },
    },
    {
      q: "What is a for-comprehension?",
      a: "for { x <- xs; y <- ys } yield f(x,y) desugars to flatMap/map/withFilter. It works for List, Option, Future, Either (right-biased), and anything with those methods.",
      e: "It’s not a C-style loop. If you forget yield you get foreach (side effects). Nested Options flatten; that’s why for is the clean way to combine them.",
      visual: {
        title: "for desugars to map",
        kind: "timeline",
        events: [
          { h: "Generator", lines: ["x <- xs"] },
          { h: "flatMap", lines: ["Bind the next"] },
          { h: "yield", lines: ["map the result"] },
          { h: "filter", lines: ["if guards → withFilter"] },
        ],
        footer: "Same syntax for lists, options, and futures",
      },
    },
    {
      q: "Why does Scala emphasize immutability?",
      a: "Immutable values are easier to share across threads, reason about, and persist in structural collections (Lists/Vectors share tails/trees).",
      e: "The JVM is still mutable underneath. Interviews like: default immutable, isolate mutation (var, Array, builders) behind a pure API. Spark datasets are another reason — recompute beats shared mutation.",
      visual: {
        title: "Immutable by default",
        kind: "cycle",
        center: "val",
        items: [
          { h: "Share", lines: ["No surprise writes"] },
          { h: "Structure", lines: ["Persistent trees"] },
          { h: "Threads", lines: ["Safer publishing"] },
          { h: "Copy", lines: ["case copy()"] },
          { h: "Isolate var", lines: ["Inside a method"] },
        ],
        footer: "Immutability is the default style, not a JVM miracle",
      },
    },
  ],
  intermediate: [
    {
      q: "How do List and Vector differ in practice?",
      a: "List is a singly linked list: O(1) prepend, O(n) random access. Vector is a 32-way trie: effectively O(1) index and update, slightly heavier small lists.",
      e: "Use List for stacks and pattern matching (head :: tail). Use Vector when you index or append. ArrayBuffer/Array for local mutation, then .toVector.",
      visual: {
        title: "List vs Vector",
        kind: "hub",
        hub: "Seq",
        nodes: [
          { h: "List", lines: ["Prepend cheap"] },
          { h: "Vector", lines: ["Index cheap"] },
          { h: "LazyList", lines: ["Lazy cons"] },
          { h: "Array", lines: ["Raw JVM"] },
          { h: "Buffer", lines: ["Build then freeze"] },
          { h: "View", lines: ["Lazy transforms"] },
        ],
        footer: "Pick the Seq that matches access pattern",
      },
    },
    {
      q: "What are implicits in Scala 2 vs givens in Scala 3?",
      a: "Scala 2 implicit vals/defs are picked by the compiler for missing arguments and conversions. Scala 3 replaces most of that with given and using — clearer, fewer surprise conversions.",
      e: "implicit conversion is now discouraged (Conversion type class). Extension methods replace implicit class. Know both: lots of Spark/Play code is still Scala 2 implicits.",
      visual: {
        title: "implicits vs givens",
        kind: "compare",
        left: {
          h: "Scala 2",
          lines: ["implicit val / def", "implicit class", "Can convert silently", "Still everywhere"],
        },
        right: {
          h: "Scala 3",
          lines: ["given / using", "extension", "Conversion explicit", "Same idea, safer syntax"],
        },
        footer: "Same type-class pattern — Scala 3 makes the context obvious",
      },
    },
    {
      q: "How do you write a given / using parameter?",
      a: "given ord: Ordering[Int] = … provides an instance. def max[T](x: T, y: T)(using Ordering[T]) consumes it. Callers can omit the using argument.",
      e: "In Scala 2 this was implicit. Summon with summon[T] (Scala 3) or implicitly. Ambiguous givens fail compilation — a feature, not a bug.",
      visual: {
        title: "A given Ordering",
        kind: "code",
        code: {
          file: "ord.scala",
          code: [
            "given Ordering[Int] = Ordering.Int",
            "def max[T](a: T, b: T)",
            "    (using o: Ordering[T]): T =",
            "  if o.compare(a, b) >= 0 then a else b",
          ],
          notes: [
            { h: "given", text: "Puts an instance in scope" },
            { h: "using", text: "Context parameter, often omitted" },
            { h: "summon", text: "Ask the compiler for T" },
          ],
        },
        footer: "Type classes are just givens the compiler threads through",
      },
    },
    {
      q: "How do Futures work on the JVM?",
      a: "Future { ... }(using ec) schedules work on an ExecutionContext. Combinators (map, flatMap, zip) compose async results without blocking.",
      e: "Never block inside a Future on the same pool (deadlock). Await.result is for the edge of the program. For real apps, cats-effect / ZIO / Pekko streams are common; raw Future is the interview baseline.",
      visual: {
        title: "Future pipeline",
        kind: "steps",
        steps: [
          { h: "EC", lines: ["Thread pool"] },
          { h: "Future { }", lines: ["Schedule a body"] },
          { h: "map / flatMap", lines: ["Chain without block"] },
          { h: "onComplete", lines: ["Side-effect result"] },
        ],
        footer: "An ExecutionContext is not optional — it is the pool",
      },
    },
    {
      q: "Either vs Option vs Try — when each?",
      a: "Option is presence. Either[E,A] is a typed error or a value (by convention Right is success). Try[A] is Success/Failure wrapping Throwables.",
      e: "Don’t use Option for failures you must explain. Either is the functional error type; Try is for catching exceptions at the boundary.",
      visual: {
        title: "Three effect shapes",
        kind: "compare",
        left: {
          h: "Option / Try",
          lines: ["None = missing", "Try = exception", "Tiny to use", "Weak error type"],
        },
        right: {
          h: "Either[E, A]",
          lines: ["Left = domain error", "Right = success", "Composable", "E can be a sealed trait"],
        },
        footer: "Model errors as data when callers must branch",
      },
    },
    {
      q: "How does trait linearization work?",
      a: "When a class mixes many traits, Scala linearizes them (right-first, then left) so each super has one next. super calls follow that line — stackable modifications.",
      e: "Diamond inheritance is defined, not ambiguous. If you need Java-style interfaces only, keep traits thin. Mixing stateful traits needs care (init order).",
      visual: {
        title: "Linearization order",
        kind: "layers",
        layers: [
          { h: "class C", lines: ["The concrete type"] },
          { h: "with B", lines: ["Rightmost trait first"] },
          { h: "with A", lines: ["Then leftward"] },
          { h: "AnyRef", lines: ["Bottom of the line"] },
        ],
        footer: "super is the next trait on the linearized list",
      },
    },
    {
      q: "How do sealed traits model variants?",
      a: "sealed trait (or Scala 3 enum) restricts subclasses to the same file. match can be exhaustive. This is the FP ‘sum type’ on the JVM.",
      e: "Case classes extend the sealed trait for each variant. Prefer this over a boolean + nullable fields. Java 17 sealed classes are the cousin.",
      visual: {
        title: "Sealed result",
        kind: "code",
        code: {
          file: "result.scala",
          code: [
            "sealed trait Res",
            "case class Ok(s: String) extends Res",
            "case class Err(e: String) extends Res",
            "def msg(r: Res) = r match {",
            "  case Ok(s) => s; case Err(e) => e",
            "}",
          ],
          notes: [
            { h: "sealed", text: "All variants known here" },
            { h: "match", text: "Compiler checks exhaustiveness" },
            { h: "enum", text: "Scala 3 sugar for this pattern" },
          ],
        },
        footer: "Illegal states stay unrepresentable",
      },
    },
    {
      q: "What should you know about Spark in a Scala interview?",
      a: "Spark is a distributed engine whose Scala API uses RDDs/DataFrames. Closures you pass are serialized to workers — capture only serializable, small data.",
      e: "Don’t pretend to be a Spark expert unless the job is Spark. Know: driver vs executors, lazy DAG until an action, and why mapPartitions beats per-row Python UDFs. Keep it light.",
      visual: {
        title: "Spark in one line",
        kind: "timeline",
        events: [
          { h: "Driver", lines: ["Builds a DAG"] },
          { h: "Transform", lines: ["Lazy map / filter"] },
          { h: "Action", lines: ["count / write"] },
          { h: "Executors", lines: ["Run tasks"] },
        ],
        footer: "Closures ship to the cluster — keep them serializable",
      },
    },
    {
      q: "What is variance in Scala collections?",
      a: "List[A] is covariant (List[+A]): List[Dog] is a List[Animal]. Mutable collections are invariant because a write would break type safety.",
      e: "Function1 is contravariant in its input and covariant in its output. That is why a function that accepts Animal can be used where a Dog handler is needed.",
      visual: {
        title: "Producer vs consumer",
        kind: "cycle",
        center: "+A / -A",
        items: [
          { h: "List[+A]", lines: ["Producer"] },
          { h: "Dog <: Animal", lines: ["Subtype"] },
          { h: "List[Dog]", lines: ["is List[Animal]"] },
          { h: "Array[A]", lines: ["Invariant"] },
          { h: "Function[-A,+R]", lines: ["In in, out out"] },
        ],
        footer: "Mutable boxes stay invariant on purpose",
      },
    },
    {
      q: "How do you mix traits for behavior?",
      a: "Split orthogonal abilities into traits (Ordered, AutoCloseable-like, logging) and mix them with with. Keep each trait small so linearization stays obvious.",
      e: "Cake pattern (self-types) was an old DI style; prefer constructor injection or given. Self-types (this: Foo =>) still appear in older codebases.",
      visual: {
        title: "Trait toolbox",
        kind: "hub",
        hub: "traits",
        nodes: [
          { h: "Interface", lines: ["Abstract API"] },
          { h: "Mixin", lines: ["Concrete helpers"] },
          { h: "Stackable", lines: ["abstract override"] },
          { h: "Self-type", lines: ["this: Foo =>"] },
          { h: "Params", lines: ["Scala 3 traits"] },
          { h: "enum", lines: ["Sealed ADT"] },
        ],
        footer: "Small traits compose — fat traits tangle init order",
      },
    },
    {
      q: "How do you add an extension method?",
      a: "Scala 3: extension (s: String) def shout = s.toUpperCase. Scala 2: implicit class StringOps(val s: String) extends AnyVal.",
      e: "Value classes / opaque types avoid boxing. Don’t use implicit conversions to add methods anymore — extensions are the supported path.",
      visual: {
        title: "extension in Scala 3",
        kind: "code",
        code: {
          file: "ext.scala",
          code: [
            "extension (s: String)",
            "  def shout: String = s.toUpperCase",
            "\"hi\".shout  // HI",
          ],
          notes: [
            { h: "extension", text: "Adds methods without wrapping" },
            { h: "Scala 2", text: "implicit class AnyVal" },
            { h: "opaque", text: "Zero-cost newtype in Scala 3" },
          ],
        },
        footer: "Extensions replace most implicit classes",
      },
    },
    {
      q: "How do you avoid blocking with Futures?",
      a: "Chain with map/flatMap/zip. Use a dedicated blocking EC for Thread.sleep/JDBC. Recover errors with recover/recoverWith. Don’t Await inside combinators.",
      e: "Future is eager — it starts when created. cats-effect IO is lazy. Mixing them needs a boundary. ExecutionContext.global is a ForkJoinPool — blocking starves it.",
      visual: {
        title: "Stay on the pool",
        kind: "steps",
        steps: [
          { h: "Start Future", lines: ["Uses the EC"] },
          { h: "Compose", lines: ["map · zip · traverse"] },
          { h: "Blocking IO", lines: ["Shift to blocking EC"] },
          { h: "Edge Await", lines: ["main / test only"] },
        ],
        footer: "Blocking on global is how services deadlock",
      },
    },
    {
      q: "What is a companion’s role for type classes?",
      a: "Givens/implicits in the companion of type T are in implicit scope when T is used. That’s why Ordering[User] often lives in object User.",
      e: "Priority: local givens beat imported beat companion. Ambiguous instances are a compile error. This is how you extend libraries without touching their source.",
      visual: {
        title: "Implicit scope",
        kind: "layers",
        layers: [
          { h: "Local given", lines: ["In the method / block"] },
          { h: "Imports", lines: ["explicit given imports"] },
          { h: "Companions", lines: ["of the type and parts"] },
        ],
        footer: "Put the default instance next to the type",
      },
    },
    {
      q: "How do by-name parameters work?",
      a: "x: => T is evaluated each time it is used, not at the call site. Useful for lazy defaults, assert, and control-flow helpers (def until(p: => Boolean)).",
      e: "It is not a thunk you can store unless you write () => T or lazy val. Call-by-name plus a var capture is a classic leak. lazy val memoizes on first force.",
      visual: {
        title: "By-name vs lazy val",
        kind: "timeline",
        events: [
          { h: "Call", lines: ["Arg not evaluated"] },
          { h: "Each use", lines: ["Recompute => T"] },
          { h: "lazy val", lines: ["Compute once"] },
          { h: "() => T", lines: ["Explicit thunk"] },
        ],
        footer: "=> T is re-run; lazy val is cached",
      },
    },
    {
      q: "What changes between Scala 2 and Scala 3 at a glance?",
      a: "Scala 3 adds givens, extension, enums, optional braces, union/intersection types, inline, and TASTy. It drops many implicit conversions and the old macro system.",
      e: "Cross-building 2.13/3 is common. Syntax can look new; the JVM model is the same. Interviews often ask ‘what did givens replace?’",
      visual: {
        title: "Scala 3 highlights",
        kind: "cycle",
        center: "Scala 3",
        items: [
          { h: "given/using", lines: ["Replaces implicit"] },
          { h: "enum", lines: ["Sealed ADTs"] },
          { h: "union A | B", lines: ["New types"] },
          { h: "TASTy", lines: ["Typed AST"] },
          { h: "inline", lines: ["New macros"] },
          { h: "indent", lines: ["Optional braces"] },
        ],
        footer: "Same JVM — cleaner metaprogramming and context",
      },
    },
  ],
  expert: [
    {
      q: "How do covariance and contravariance interact with functions?",
      a: "Function1[-A, +B]: a function is a consumer of A (contravariant) and producer of B (covariant). You can pass a wider-input, narrower-output function where a specific one is expected.",
      e: "This is the Liskov rule for callbacks. Mutable invariant boxes (Array) exist because a covariant Array would let you write a Cat into Animal[]. Java arrays are covariant and unsafe; Scala Arrays are not.",
      visual: {
        title: "Variance of Function1",
        kind: "hub",
        hub: "[-A, +B]",
        nodes: [
          { h: "-A", lines: ["Accept super"] },
          { h: "+B", lines: ["Return sub"] },
          { h: "List[+A]", lines: ["Producer"] },
          { h: "Builder", lines: ["Invariant"] },
          { h: "Array[A]", lines: ["Invariant"] },
          { h: "Set[A]", lines: ["Invariant in 2.13"] },
        ],
        footer: "Producers +A · consumers -A · mutable  A",
      },
    },
    {
      q: "What are higher-kinded types?",
      a: "A type constructor F[_] (List, Option, Future) is higher-kinded: it takes a type to make a type. Methods can be generic over F: def map[F[_], A, B](...).",
      e: "This is how Cats Functor/Monad work. Kind Projector / Scala 3 type lambdas write F[_, E] shapes. If you only ever use List, you don’t need HKT — libraries do.",
      visual: {
        title: "Kinds",
        kind: "compare",
        left: {
          h: "Proper type",
          lines: ["Int, User", "Kind *", "A value exists", "List[Int] is proper"],
        },
        right: {
          h: "Type constructor",
          lines: ["List, Option", "Kind * -> *", "Needs a type arg", "F[_] in a trait"],
        },
        footer: "Functor[F[_]] is generic over the container shape",
      },
    },
    {
      q: "How do you write a tiny type class with a higher-kinded F?",
      a: "trait Functor[F[_]] { def map[A,B](fa: F[A])(f: A => B): F[B] } plus given Functor[List]. Callers use summon or extension map.",
      e: "Laws (identity, composition) are the contract. Tagless-final style is programming against F[_]: Monad. That’s expert Scala — mention it, don’t oversell it for CRUD apps.",
      visual: {
        title: "Functor for List",
        kind: "code",
        code: {
          file: "fun.scala",
          code: [
            "trait Functor[F[_]]:",
            "  def map[A, B](fa: F[A])",
            "      (f: A => B): F[B]",
            "given Functor[List] with",
            "  def map[A,B](fa: List[A])",
            "      (f: A => B) = fa.map(f)",
          ],
          notes: [
            { h: "F[_]", text: "Higher-kinded parameter" },
            { h: "given", text: "Instance for List" },
            { h: "Laws", text: "map(id) == id" },
          ],
        },
        footer: "Type classes + HKT are how generic FP libraries exist",
      },
    },
    {
      q: "How does implicit/given resolution actually search?",
      a: "The compiler collects candidates from local scope, explicit imports, then implicit scope (companions of the type and its type arguments, package objects). It picks the most specific; two unrelated winners are ambiguous.",
      e: "Low-priority traits (LowPriorityImplicits) encode fallbacks. Divergence (recursive search) is a compile fail. This machinery is why ‘it compiles in the REPL but not in the package’ happens.",
      visual: {
        title: "Search order",
        kind: "steps",
        steps: [
          { h: "Local / args", lines: ["using passed in"] },
          { h: "Imports", lines: ["given instances"] },
          { h: "Companions", lines: ["Type + args"] },
          { h: "Most specific", lines: ["Or ambiguous error"] },
        ],
        footer: "Ambiguous givens are safer than silent conversions",
      },
    },
    {
      q: "Covariant List vs invariant Set — why the difference?",
      a: "Set.contains uses equality; if Set were covariant, Set[Dog] as Set[Animal] could break the equality/hash contract depending on implementation. After 2.13, Set and Map stay invariant.",
      e: "List only produces elements, so +A is safe. This is a favorite variance interview. Don’t say ‘Set is covariant’ — that’s old folklore.",
      visual: {
        title: "Why Set is invariant",
        kind: "compare",
        left: {
          h: "List[+A]",
          lines: ["Only reads A", "Dog list is Animal list", "Safe producer", "Pattern match head"],
        },
        right: {
          h: "Set[A]",
          lines: ["contains / +", "Equality depends on A", "Invariant in 2.13", "No Set[Dog] <: Set[Animal]"],
        },
        footer: "If you both put in and take out, stay invariant",
      },
    },
    {
      q: "What does TASTy change compared to Scala 2 pickles?",
      a: "TASTy is a typed AST the Scala 3 compiler serializes beside .class. It enables better incremental compilation, inlining, and macros that see types, not just trees.",
      e: "Java still only sees erased bytecode. Binary compatibility is about both the JVM signature and TASTy for Scala callers. MiMa + TASTy-MiMa matter for libraries.",
      visual: {
        title: "What you publish",
        kind: "layers",
        layers: [
          { h: ".class", lines: ["JVM bytecode, erased"] },
          { h: ".tasty", lines: ["Typed Scala 3 AST"] },
          { h: "javap view", lines: ["What Java callers see"] },
          { h: "Scala callers", lines: ["Need TASTy for inlines"] },
        ],
        footer: "Bytecode for the JVM — TASTy for Scala 3 features",
      },
    },
    {
      q: "How do opaque types and union types change API design?",
      a: "opaque type UserId = String is a zero-cost newtype inside the companion, distinct outside. Union A | B is a real type (not just Either) with match on type tests.",
      e: "Unions are not HKT-friendly the way Either is. Opaque types replace many AnyVal classes. Intersection A & B is structural for members.",
      visual: {
        title: "Scala 3 newtypes",
        kind: "code",
        code: {
          file: "id.scala",
          code: [
            "object Ids:",
            "  opaque type UserId = String",
            "  object UserId:",
            "    def apply(s: String): UserId = s",
            "    def raw(u: UserId): String = u",
          ],
          notes: [
            { h: "opaque", text: "Alias inside; distinct outside" },
            { h: "No box", text: "Erases to String at runtime" },
            { h: "Union", text: "A | B for ad-hoc variants" },
          ],
        },
        footer: "Opaque IDs beat Stringly APIs without runtime wrappers",
      },
    },
    {
      q: "What are the expert pitfalls of Future?",
      a: "Eager execution, thrown exceptions become failed futures (sometimes asynchronously), map of a throwing function fails the future, and ExecutionContext leaks across libraries.",
      e: "Future.sequence on huge lists can pile up. There is no cancellation. That’s why production Scala often moves to IO/ZIO/FS2 for typed effects, resource safety, and interruptibility.",
      visual: {
        title: "Future sharp edges",
        kind: "timeline",
        events: [
          { h: "Create", lines: ["Already running"] },
          { h: "Throw in map", lines: ["Failed Future"] },
          { h: "No cancel", lines: ["Work keeps going"] },
          { h: "IO / ZIO", lines: ["Lazy + interrupt"] },
        ],
        footer: "Future is a running task — IO is a description",
      },
    },
    {
      q: "How do type lambdas express F[_, E]?",
      a: "Either is * -> * -> *. To make a Functor for ‘Either with a fixed left’, you need a type lambda: [A] =>> Either[E, A] (Scala 3) or kind-projector Either[E, *].",
      e: "This is core to Cats. If you can’t write the kind, you can’t instance the type class. Interviews may ask you to sketch Functor[Either[E, *]].",
      visual: {
        title: "Fix one type parameter",
        kind: "cycle",
        center: "[A] =>> …",
        items: [
          { h: "Either[E, A]", lines: ["Two params"] },
          { h: "Fix E", lines: ["Error type known"] },
          { h: "Lambda", lines: ["[A] =>> Either[E,A]"] },
          { h: "Kind * -> *", lines: ["Fits Functor"] },
          { h: "given", lines: ["Instance in scope"] },
        ],
        footer: "Type lambdas adapt kind so type classes fit",
      },
    },
    {
      q: "What should you still know about Spark as a Scala expert?",
      a: "Closures capture this and outer vals — serialize a whole object graph by accident. Prefer local vals, broadcast small data, avoid map-side Python/Scala UDFs when SQL/Catalyst can run.",
      e: "Dataset[T] uses encoders; RDD[T] is lower level. Spark 3 + Scala 2.12/2.13 is the usual pair; Scala 3 support lagged. Mention it only as ‘closures + serialization + lazy DAG’.",
      visual: {
        title: "Spark closure trap",
        kind: "hub",
        hub: "task",
        nodes: [
          { h: "Closure", lines: ["Shipped to worker"] },
          { h: "this", lines: ["Don’t capture"] },
          { h: "Broadcast", lines: ["Small shared data"] },
          { h: "Catalyst", lines: ["Prefer DataFrame"] },
          { h: "UDF", lines: ["Breaks optimizer"] },
          { h: "Action", lines: ["Triggers the DAG"] },
        ],
        footer: "If it isn’t serializable, the executor explodes",
      },
    },
    {
      q: "How does erasure show up in Scala APIs?",
      a: "Generic types erase on the JVM: List[Int] and List[String] are List at runtime. Pattern matching on List[Int] can’t check the Int. ClassTag/TypeTag/TypeTest recover some of it.",
      e: "Overloaded methods that only differ by type params are illegal. Arrays reify their component type; that’s why Array[T] needs a ClassTag to create.",
      visual: {
        title: "Need a ClassTag",
        kind: "code",
        code: {
          file: "arr.scala",
          code: [
            "def arr[T: ClassTag](x: T): Array[T] =",
            "  Array(x)",
            "// List[Int] erased at runtime",
          ],
          notes: [
            { h: "Erasure", text: "T is gone in bytecode" },
            { h: "ClassTag", text: "Lets you new Array[T]" },
            { h: "Match", text: "Cannot test List[Int]" },
          ],
        },
        footer: "The JVM does not have reified generics",
      },
    },
    {
      q: "What is specialization and when does it matter?",
      a: "@specialized generates primitive copies of a generic class (Int, Long, …) to avoid boxing. It explodes bytecode size. Scala 3 opaque/inline and arrays are often better tools.",
      e: "Hot numeric code may still use it or hand-written primitive collections (FastParse, Spire). Don’t sprinkle @specialized in business code.",
      visual: {
        title: "Boxing vs specialize",
        kind: "steps",
        steps: [
          { h: "Generic T", lines: ["T is Object on JVM"] },
          { h: "Box Int", lines: ["java.lang.Integer"] },
          { h: "@specialized", lines: ["Extra Int class"] },
          { h: "Cost", lines: ["JAR size · compile"] },
        ],
        footer: "Measure boxing before specializing",
      },
    },
    {
      q: "How do context functions (Scala 3) differ from using clauses?",
      a: "A context function type is ExecutionContext ?=> Future[Int] — a function that takes a given. You can store and compose them. using clauses are method syntax for the same idea.",
      e: "Useful for passing EC, Tracer, or IO runtime without cluttering every lambda. Overuse makes signatures unreadable. They erase to extra parameters.",
      visual: {
        title: "Context function type",
        kind: "layers",
        layers: [
          { h: "using on methods", lines: ["def f(x: Int)(using EC)"] },
          { h: "?=> type", lines: ["EC ?=> R"] },
          { h: "Call", lines: ["Given found or passed"] },
          { h: "Erase", lines: ["Extra JVM param"] },
        ],
        footer: "?=> is a function that expects a given",
      },
    },
    {
      q: "How do you keep a Scala library binary-compatible?",
      a: "Don’t remove methods, change signatures, or move givens out of implicit scope. Use MiMa. For Scala 3, TASTy-MiMa too. Prefer adding overloaded methods to changing them.",
      e: "Case class field changes break unapply. opaque types and inline defs have their own rules. Java callers only see erased methods — keep a stable Java facade if you must.",
      visual: {
        title: "Compat checks",
        kind: "timeline",
        events: [
          { h: "Public API", lines: ["Signatures freeze"] },
          { h: "MiMa", lines: ["Compare JARs"] },
          { h: "TASTy-MiMa", lines: ["Scala 3 extras"] },
          { h: "Release", lines: ["Semver honestly"] },
        ],
        footer: "The JVM signature is not the whole Scala API",
      },
    },
    {
      q: "When should you use advanced Scala vs keep it Java-simple?",
      a: "Use ADTs, Option/Either, and a few givens at boundaries. Skip HKT soup in application code. Expert Scala is knowing when Cats/ZIO earn their keep — usually in libraries and concurrent backends.",
      e: "A strong interview answer: model illegal states out, isolate effects, keep type lambdas in one layer. Spark jobs and services often stay ‘boring Scala’ on purpose.",
      visual: {
        title: "Judgment layers",
        kind: "cycle",
        center: "judgment",
        items: [
          { h: "ADTs", lines: ["Always worth it"] },
          { h: "givens", lines: ["Type classes at edges"] },
          { h: "HKT", lines: ["Libraries, not pages"] },
          { h: "Macros", lines: ["Rare"] },
          { h: "Boring JVM", lines: ["Often ships"] },
        ],
        footer: "Expert Scala is restraint — not maximum kinds",
      },
    },
  ],
};
