module.exports = {
  name: "Swift",
  description:
    "Swift interview questions — optionals, value types, protocols, ARC, concurrency, and copy-on-write.",
  match: /^swift$/i,
  theme: {
    accent: "#F05138",
    hubFill: "#F05138",
    hubText: "#ffffff",
    centerFill: "#ffedd5",
    centerStroke: "#F05138",
    label: "Swift",
  },
  beginner: [
    {
      q: "What is Swift and why use it?",
      a: "Swift is Apple’s modern language for iOS, macOS, and beyond. It is safe by default (optionals, value types) and compiles to native code with ARC memory management.",
      e: "Interviewers want safety features, not just “Apple’s language.” Mention optionals, structs, protocols, and that Swift also runs on the server (Vapor) and recently on Android experiments.",
      visual: {
        title: "Where Swift shines",
        kind: "hub",
        hub: "Swift",
        nodes: [
          { h: "Safety", lines: ["Optionals · types"] },
          { h: "Speed", lines: ["Compiled native"] },
          { h: "ARC", lines: ["Auto memory"] },
          { h: "Apple", lines: ["iOS · macOS"] },
          { h: "Protocols", lines: ["POP over inheritance"] },
          { h: "Interop", lines: ["Talks to Obj-C"] },
        ],
        footer: "Safe defaults — still a systems-capable compiled language",
      },
    },
    {
      q: "What is an optional in Swift?",
      a: "An optional (T?) is a value that may be T or nil. The type system forces you to unwrap before using it, so missing data cannot silently crash as a null pointer.",
      e: "Optionals are an enum: Optional.some(wrapped) or .none. Prefer if let / guard let / ?? over force unwrap (!). IUO (T!) exists for Obj-C interop and is a smell in new Swift.",
      visual: {
        title: "Optional vs non-optional",
        kind: "compare",
        left: {
          h: "String",
          lines: ["Always has text", "No unwrap needed", "Cannot be nil", "Use for required data"],
        },
        right: {
          h: "String?",
          lines: ["Text or nil", "Must unwrap", "Models missing data", "Use for maybe-absent"],
        },
        footer: "T? is not T — the checker will not let you forget nil",
      },
    },
    {
      q: "How do if let and guard let unwrap optionals?",
      a: "if let binds a non-nil value inside a block. guard let unwraps or exits early (return/throw), keeping the happy path unindented.",
      e: "guard must exit the scope if the check fails. Shadowing the same name (if let name = name) is idiomatic. Multiple bindings can share one if/guard.",
      visual: {
        title: "Unwrap then use",
        kind: "steps",
        steps: [
          { h: "Have T?", lines: ["Maybe nil"] },
          { h: "if let / guard", lines: ["Bind a real T"] },
          { h: "Use T", lines: ["Call methods safely"] },
          { h: "Else path", lines: ["Skip or return"] },
        ],
        footer: "guard keeps the success path flat — if let nests it",
      },
    },
    {
      q: "What are optional chaining and nil-coalescing?",
      a: "?. calls a member only if the left side is non-nil, else the whole expression is nil. ?? supplies a default when the left side is nil.",
      e: "Chaining can be long: user?.profile?.name. Prefer ?? over force unwrap. Optional try (try?) turns thrown errors into nil — handy but easy to swallow bugs.",
      visual: {
        title: "Safe access and defaults",
        kind: "timeline",
        events: [
          { h: "Maybe missing", lines: ["user?.email"] },
          { h: "Chain", lines: ["user?.addr?.city"] },
          { h: "Default", lines: ["city ?? \"unknown\""] },
          { h: "Use", lines: ["A real String"] },
        ],
        footer: "?. yields optional — ?? peels it back to a concrete value",
      },
    },
    {
      q: "What is the difference between value and reference types?",
      a: "Value types (struct, enum, tuple) copy on assignment. Reference types (class, actor, closure) share one instance; assignment copies the pointer.",
      e: "Swift prefers structs for data. Copies are often cheap because of copy-on-write on Array/String/Dictionary. Classes add identity (===) and inheritance.",
      visual: {
        title: "Copy vs share",
        kind: "compare",
        left: {
          h: "Value (struct)",
          lines: ["Assignment copies", "Independent mutation", "No === identity", "Stack-friendly"],
        },
        right: {
          h: "Reference (class)",
          lines: ["Assignment shares", "Mutation is visible", "=== compares identity", "Heap + ARC"],
        },
        footer: "Ask “should copies be independent?” — if yes, use a struct",
      },
    },
    {
      q: "What is a struct in Swift?",
      a: "A struct is a value type with stored/computed properties, methods, and initializers. Mutating methods need the mutating keyword because self is immutable by default.",
      e: "Structs get a memberwise initializer. They cannot inherit from other structs. Use them for models, coordinates, and almost all data unless you need identity or Obj-C.",
      visual: {
        title: "Struct anatomy",
        kind: "layers",
        layers: [
          { h: "Stored properties", lines: ["The actual data"] },
          { h: "Computed / methods", lines: ["Derived values · behavior"] },
          { h: "mutating", lines: ["Allowed to change self"] },
          { h: "Memberwise init", lines: ["Compiler-provided constructor"] },
        ],
        footer: "Default Swift model type — copy semantics, no identity",
      },
    },
    {
      q: "What is a class in Swift?",
      a: "A class is a reference type. Instances live on the heap, are shared, and are managed by ARC. Classes support inheritance, deinit, and identity comparison (===).",
      e: "Use classes for shared mutable state, Obj-C interop (NSObject), and when identity matters. Prefer final unless you design for subclassing. Actors are the concurrency-safe cousin.",
      visual: {
        title: "A simple class",
        kind: "code",
        code: {
          file: "User.swift",
          code: [
            "class User {",
            "  var name: String",
            "  init(name: String) {",
            "    self.name = name",
            "  }",
            "  deinit { print(\"bye\") }",
            "}",
          ],
          notes: [
            { h: "Reference", text: "let u = User(...) still shares the object" },
            { h: "deinit", text: "Runs when ARC’s retain count hits zero" },
            { h: "Identity", text: "=== asks “same instance?” not “equal?”" },
          ],
        },
        footer: "Classes share; structs copy — pick from that rule first",
      },
    },
    {
      q: "What is a protocol?",
      a: "A protocol names a contract: properties and methods a type must provide. Structs, classes, and enums can all conform. This is the heart of protocol-oriented Swift.",
      e: "Protocols can have extensions with default implementations. associatedtype makes them generic. any P is an existential box; some P is an opaque type.",
      visual: {
        title: "Protocol as a contract",
        kind: "hub",
        hub: "Protocol",
        nodes: [
          { h: "Requirements", lines: ["Methods · properties"] },
          { h: "Struct", lines: ["Can conform"] },
          { h: "Class", lines: ["Can conform"] },
          { h: "Enum", lines: ["Can conform"] },
          { h: "Extension", lines: ["Default behavior"] },
          { h: "Composition", lines: ["P & Q"] },
        ],
        footer: "Prefer protocols over deep class hierarchies",
      },
    },
    {
      q: "How does type inference work in Swift?",
      a: "The compiler infers types from literals, context, and return values so you can write let n = 3 instead of let n: Int = 3.",
      e: "Annotate public APIs and ambiguous literals (e.g. CGFloat vs Double). Opaque some types and generics still infer at call sites. Compiler errors often mean inference failed, not that Swift is “weakly typed.”",
      visual: {
        title: "Inference flow",
        kind: "steps",
        steps: [
          { h: "Write value", lines: ["let n = 3"] },
          { h: "Compiler infers", lines: ["n is Int"] },
          { h: "Use safely", lines: ["n.nonzeroBitCount"] },
          { h: "Annotate edges", lines: ["Public APIs · literals"] },
        ],
        footer: "Infer locals — declare types at module boundaries",
      },
    },
    {
      q: "How do Swift enums differ from C enums?",
      a: "Swift enums are first-class types. Cases can have associated values (like a union) or raw values. They support methods, computed properties, and protocol conformance.",
      e: "Associated-value enums plus switch exhaustiveness are Swift’s algebraic data types. Optional and Result are enums. Recursive enums need indirect.",
      visual: {
        title: "Enum with associated values",
        kind: "code",
        code: {
          file: "Network.swift",
          code: [
            "enum Load {",
            "  case idle",
            "  case ok(Data)",
            "  case err(String)",
            "}",
            "let s = Load.ok(data)",
          ],
          notes: [
            { h: "Cases", text: "idle / ok / err are mutually exclusive" },
            { h: "Payload", text: "ok carries Data — not a parallel field" },
            { h: "Switch", text: "Must handle every case (or use @unknown)" },
          ],
        },
        footer: "Enums model variants — associated values carry the payload",
      },
    },
    {
      q: "What is a computed property?",
      a: "A computed property has a getter (and optional setter) instead of stored storage. It is accessed like a field but runs code each time.",
      e: "Use let stored for data, var computed for derived values. willSet/didSet observers only work on stored properties. lazy stored properties initialize on first access.",
      visual: {
        title: "Property kinds",
        kind: "layers",
        layers: [
          { h: "Stored", lines: ["Memory that holds a value"] },
          { h: "Computed", lines: ["get / set — no own storage"] },
          { h: "lazy", lines: ["Stored, created on first read"] },
          { h: "Observers", lines: ["willSet / didSet on stored"] },
        ],
        footer: "Computed looks like a field — it is really a method pair",
      },
    },
    {
      q: "What is ARC at a high level?",
      a: "Automatic Reference Counting inserts retain/release for class instances. When the retain count hits zero, deinit runs and the object is freed.",
      e: "ARC is compile-time inserted, not a tracing GC. Value types are not reference-counted. Cycles (two objects strongly owning each other) leak until you use weak or unowned.",
      visual: {
        title: "Retain count lifecycle",
        kind: "cycle",
        center: "ARC",
        items: [
          { h: "Alloc", lines: ["Count = 1"] },
          { h: "Strong ref", lines: ["Count + 1"] },
          { h: "Release", lines: ["Count − 1"] },
          { h: "Zero", lines: ["deinit · free"] },
        ],
        footer: "No GC pause — cycles still leak without weak/unowned",
      },
    },
    {
      q: "What is a closure in Swift?",
      a: "A closure is an anonymous function that captures variables from its enclosing scope. Closures are reference types even when stored in a struct.",
      e: "Trailing-closure syntax is idiomatic. Capturing self strongly in a class closure is a classic retain-cycle. Use [weak self] in escaping callbacks. Non-escaping closures (default for function params) cannot outlive the call.",
      visual: {
        title: "From function to capture",
        kind: "timeline",
        events: [
          { h: "Write { }", lines: ["Anonymous body"] },
          { h: "Capture", lines: ["Close over locals"] },
          { h: "Pass / store", lines: ["May escape the call"] },
          { h: "Call later", lines: ["Uses captured state"] },
        ],
        footer: "Closures are refs — [weak self] when they outlive the call",
      },
    },
    {
      q: "How does throwing error handling work?",
      a: "Functions marked throws can throw Error values. Callers use try, try?, or try!. Errors are not exceptions in the Obj-C sense — they are a typed control-flow path.",
      e: "do/catch handles thrown errors. Result is the type-level twin for stored or async outcomes. Prefer specific Error types over NSError in new Swift. rethrows lets wrappers forward throws.",
      visual: {
        title: "Call a throwing function",
        kind: "steps",
        steps: [
          { h: "Mark throws", lines: ["func load() throws"] },
          { h: "try", lines: ["Propagate or catch"] },
          { h: "do / catch", lines: ["Handle Error"] },
          { h: "Or Result", lines: ["Store success / fail"] },
        ],
        footer: "try is required — the compiler will not let you ignore throws",
      },
    },
    {
      q: "How do Array, Dictionary, and Set differ?",
      a: "Array is an ordered list, Dictionary is a key-value map, Set is an unordered unique collection. All three are generic value types with copy-on-write.",
      e: "Set and Dictionary keys must be Hashable. Array index is Int and traps on out-of-bounds. Prefer for-in and map/filter over C-style loops.",
      visual: {
        title: "Collection trio",
        kind: "cycle",
        center: "Stdlib",
        items: [
          { h: "Array", lines: ["Ordered list"] },
          { h: "Dictionary", lines: ["Key → value"] },
          { h: "Set", lines: ["Unique Hashable"] },
          { h: "COW", lines: ["Cheap copies"] },
        ],
        footer: "Value-type collections — mutation copies only when shared",
      },
    },
  ],
  intermediate: [
    {
      q: "What are generics in Swift?",
      a: "Generics are type parameters that let functions, types, and protocols work with many types while preserving relationships between inputs and outputs.",
      e: "Constraints (T: Equatable) limit what can be passed. where clauses add extra bounds. Infer generic params from usage; name them at public API boundaries when inference is unclear.",
      visual: {
        title: "Generic identity",
        kind: "code",
        code: {
          file: "First.swift",
          code: [
            "func first<T>(_ a: [T]) -> T? {",
            "  a.first",
            "}",
            "let n = first([1, 2]) // Int?",
            "let s = first([\"a\"]) // String?",
          ],
          notes: [
            { h: "Parameter", text: "T is decided at the call site" },
            { h: "Preserve", text: "Element type flows to the return" },
            { h: "Constraint", text: "T: Equatable when you need ==" },
          ],
        },
        footer: "Generics keep relationships — Any would throw them away",
      },
    },
    {
      q: "What is Result and when do you use it?",
      a: "Result<Success, Failure: Error> is an enum with .success and .failure. It stores an outcome you can pass around, unlike throws which must be handled on the call stack.",
      e: "Use throws for synchronous call chains; use Result for callbacks, stored state, and combining with map/flatMap. Switching on Result is exhaustive. Never nest Result inside throws without a reason.",
      visual: {
        title: "throws vs Result",
        kind: "compare",
        left: {
          h: "throws / try",
          lines: ["Control-flow path", "Must handle now", "do / catch", "Great for sync APIs"],
        },
        right: {
          h: "Result",
          lines: ["A value you store", "Handle later", "map / flatMap", "Callbacks · pipelines"],
        },
        footer: "Same two outcomes — different packaging",
      },
    },
    {
      q: "What is a property wrapper?",
      a: "A property wrapper is a type annotated @propertyWrapper that intercepts get/set of a wrapped property. You apply it with @Wrapper var x.",
      e: "wrappedValue is the stored/computed core. projectedValue (the $ prefix) exposes extra API (e.g. $count in Combine). SwiftUI’s @State/@Binding are wrappers — talk about the language feature, not the UI framework.",
      visual: {
        title: "Wrapper layers",
        kind: "layers",
        layers: [
          { h: "@Wrapper var x", lines: ["Source syntax"] },
          { h: "wrappedValue", lines: ["What x reads and writes"] },
          { h: "projectedValue", lines: ["The $x extra surface"] },
          { h: "Storage", lines: ["Wrapper instance holds state"] },
        ],
        footer: "A wrapper is a type — the attribute is just the spelling",
      },
    },
    {
      q: "What are protocol extensions?",
      a: "You can add methods, computed properties, and default implementations to a protocol in an extension. Conforming types inherit the defaults unless they override.",
      e: "This is protocol-oriented programming: put shared behavior on the protocol, not a base class. Static dispatch: calling a default via the protocol type may not use the type’s override unless it was a protocol requirement.",
      visual: {
        title: "Behavior on the protocol",
        kind: "hub",
        hub: "extension P",
        nodes: [
          { h: "Defaults", lines: ["Shared methods"] },
          { h: "Constraints", lines: ["where Self: …"] },
          { h: "No stored", lines: ["Cannot add stored fields"] },
          { h: "Override", lines: ["Type may replace"] },
          { h: "Dispatch", lines: ["Witness vs static"] },
          { h: "POP", lines: ["Compose, don’t inherit"] },
        ],
        footer: "Default methods are not always dynamically dispatched",
      },
    },
    {
      q: "What is an associated type?",
      a: "associatedtype names a placeholder type inside a protocol (like Item in Collection). The conforming type fills it in. It makes protocols generic without a <T> on every use.",
      e: "You constrain them with associatedtype Element: Hashable. Opaque some Collection<Element> (primary associated types) simplifies existentials. PAT (protocol with associated type) cannot be used as any P unless you box or use some.",
      visual: {
        title: "Protocol placeholder type",
        kind: "code",
        code: {
          file: "Stack.swift",
          code: [
            "protocol Stack {",
            "  associatedtype Item",
            "  mutating func push(_ x: Item)",
            "  mutating func pop() -> Item?",
            "}",
          ],
          notes: [
            { h: "Placeholder", text: "Item is chosen by the conforming type" },
            { h: "Use", text: "Methods refer to Item, not Any" },
            { h: "PAT", text: "Cannot write any Stack without boxing" },
          ],
        },
        footer: "Associated types are generics that live on the protocol",
      },
    },
    {
      q: "What is GCD (Grand Central Dispatch)?",
      a: "GCD is Apple’s queue-based concurrency: you submit work to serial or concurrent DispatchQueues. The system owns the threads.",
      e: "Main queue is serial and UI-bound. QoS (userInteractive → background) hints priority. Prefer structured Swift concurrency (Task/actor) in new code; still know GCD for interviews and legacy APIs.",
      visual: {
        title: "Queue then execute",
        kind: "cycle",
        center: "GCD",
        items: [
          { h: "Submit", lines: ["async { }"] },
          { h: "Queue", lines: ["Serial / concurrent"] },
          { h: "Thread pool", lines: ["System owned"] },
          { h: "Run", lines: ["Your block"] },
          { h: "Callback", lines: ["Often main queue"] },
        ],
        footer: "You schedule work — you do not create threads by hand",
      },
    },
    {
      q: "What is copy-on-write?",
      a: "Copy-on-write (COW) lets value types share storage until a mutation. The first write unique-ifies the buffer so other copies stay unchanged.",
      e: "Array, String, and Dictionary use COW. isKnownUniquelyReferenced checks uniqueness for class storage inside a struct. Interviewers want: copies are O(1) until mutation, then O(n) for that buffer.",
      visual: {
        title: "Share until you write",
        kind: "steps",
        steps: [
          { h: "Assign", lines: ["a = b — share buffer"] },
          { h: "Read", lines: ["Still shared, O(1)"] },
          { h: "Mutate a", lines: ["Unique copy if shared"] },
          { h: "b unchanged", lines: ["Old buffer intact"] },
        ],
        footer: "Value semantics, reference performance — until the write",
      },
    },
    {
      q: "When do you use weak vs unowned?",
      a: "weak is an optional that zeroes when the object deinits. unowned is non-optional and assumes the object outlives the reference — accessing it after deinit is a crash.",
      e: "Parent→child is usually strong; child→parent is weak to break cycles. unowned is for lifetimes you can prove (e.g. a closure that cannot outlive self). unowned(unsafe) skips runtime checks — avoid.",
      visual: {
        title: "weak vs unowned",
        kind: "compare",
        left: {
          h: "weak",
          lines: ["Optional T?", "Becomes nil on deinit", "Safe if lifetime unknown", "Cycle breaker default"],
        },
        right: {
          h: "unowned",
          lines: ["Non-optional T", "Crash if used after free", "When lifetime is proven", "Slightly cheaper"],
        },
        footer: "If you are not sure the object lives — use weak",
      },
    },
    {
      q: "Why do Equatable and Hashable matter?",
      a: "Equatable enables == and is required for many algorithms. Hashable (which inherits Equatable) lets a type be a Dictionary key or Set member.",
      e: "Structs of Hashable fields synthesize both. Hash must be consistent with ==: equal values must share a hash. Never hash mutable identity-less fields that can change while in a Set.",
      visual: {
        title: "From equality to hashing",
        kind: "timeline",
        events: [
          { h: "Equatable", lines: ["Define =="] },
          { h: "Hashable", lines: ["hash(into:)"] },
          { h: "Set / Dict", lines: ["Keys must Hashable"] },
          { h: "Invariant", lines: ["a == b ⇒ same hash"] },
        ],
        footer: "Broken hash/== pairs are a classic interview trap",
      },
    },
    {
      q: "How does access control work in Swift?",
      a: "open and public expose API; internal (default) is module-wide; fileprivate is the file; private is the enclosing declaration. open allows subclassing outside the module; public does not.",
      e: "Extensions in the same file can see private members. @_spi and package (SE-0386) exist for finer library control. Interviews care about open vs public for frameworks.",
      visual: {
        title: "Visibility layers",
        kind: "layers",
        layers: [
          { h: "open", lines: ["Subclass & override across modules"] },
          { h: "public", lines: ["Use across modules — no external subclass"] },
          { h: "internal", lines: ["Same module (the default)"] },
          { h: "private / fileprivate", lines: ["Declaration vs whole file"] },
        ],
        footer: "Framework authors: public for types, open only if subclassing is designed",
      },
    },
    {
      q: "How do map, filter, and reduce work?",
      a: "They are generic higher-order methods on Sequence. map transforms, filter keeps matching elements, reduce collapses a sequence to one value.",
      e: "Prefer compactMap for optionals and flatMap for nested sequences. These are eager on Array; use lazy for long chains. forEach is for side effects — it is not map.",
      visual: {
        title: "Transform the sequence",
        kind: "cycle",
        center: "Sequence",
        items: [
          { h: "map", lines: ["T → U"] },
          { h: "filter", lines: ["Keep matches"] },
          { h: "reduce", lines: ["Fold to one"] },
          { h: "compactMap", lines: ["Drop nils"] },
          { h: "flatMap", lines: ["Flatten nested"] },
        ],
        footer: "Chain them — or use lazy if the array is huge",
      },
    },
    {
      q: "What does @escaping mean on a closure?",
      a: "@escaping marks a closure parameter that may be stored and called after the function returns. Non-escaping (the default) must be called before return.",
      e: "Escaping closures can create retain cycles with self. Completion handlers are escaping. async functions largely replace callback escaping in new APIs. @Sendable is the concurrency cousin.",
      visual: {
        title: "Does the closure outlive the call?",
        kind: "steps",
        steps: [
          { h: "Pass closure", lines: ["Into a function"] },
          { h: "Non-escaping", lines: ["Call before return"] },
          { h: "Store it", lines: ["Needs @escaping"] },
          { h: "Call later", lines: ["Watch [weak self]"] },
        ],
        footer: "Escaping is about lifetime — not about async syntax",
      },
    },
    {
      q: "How does Codable work?",
      a: "Encodable and Decodable (aliased as Codable) let types convert to and from external formats, usually JSON via JSONEncoder/JSONDecoder.",
      e: "Compiler synthesizes Codable for structs of Codable fields. Customize with CodingKeys, encode(to:), or property wrappers. Dates and numbers need strategy settings — a frequent production bug.",
      visual: {
        title: "Model to JSON and back",
        kind: "timeline",
        events: [
          { h: "Conform", lines: ["struct User: Codable"] },
          { h: "Encode", lines: ["JSONEncoder"] },
          { h: "Bytes / String", lines: ["Wire format"] },
          { h: "Decode", lines: ["JSONDecoder"] },
        ],
        footer: "Synthesis is free until a key or date format disagrees",
      },
    },
    {
      q: "What is protocol-oriented programming?",
      a: "POP favors small protocols plus extensions over class inheritance. You compose capabilities (Equatable, CustomStringConvertible) instead of a deep superclass tree.",
      e: "Swift’s stdlib is built this way (Sequence, Collection). Watch static vs dynamic dispatch on protocol extensions. Classes still win for identity and Obj-C. POP is a design default, not a religion.",
      visual: {
        title: "Compose capabilities",
        kind: "hub",
        hub: "POP",
        nodes: [
          { h: "Small protocols", lines: ["One job each"] },
          { h: "Extensions", lines: ["Shared defaults"] },
          { h: "Structs", lines: ["Prefer values"] },
          { h: "Generics", lines: ["Static type info"] },
          { h: "Existentials", lines: ["any P when needed"] },
          { h: "Avoid", lines: ["God base classes"] },
        ],
        footer: "Start with a protocol — add a class only for identity or UIKit",
      },
    },
    {
      q: "What is an actor at an introductory level?",
      a: "An actor is a reference type that serializes access to its isolated state. You await methods from outside so only one task mutates the actor at a time.",
      e: "Actors replace many ad-hoc locks and “talk to the main thread” patterns. @MainActor is an actor-like isolation for UI. They are not GCD queues, but isolation is the same idea: one owner of the data.",
      visual: {
        title: "One owner of the state",
        kind: "cycle",
        center: "actor",
        items: [
          { h: "Isolated state", lines: ["vars inside"] },
          { h: "Call from outside", lines: ["await method"] },
          { h: "Enqueue", lines: ["One at a time"] },
          { h: "Mutate", lines: ["No data race"] },
          { h: "Resume caller", lines: ["Return value"] },
        ],
        footer: "Actors are classes with a built-in serial executor",
      },
    },
  ],
  expert: [
    {
      q: "What is the difference between any and some?",
      a: "any P is an existential: a box that can hold any type conforming to P, with dynamic dispatch. some P is an opaque type: one specific concrete type, chosen by the callee, hidden from the caller.",
      e: "some is lighter and preserves identity of the concrete type (needed for generics and associated types). any has runtime overhead and type erasure. Swift 5.6+ made any required for existentials (SE-0335).",
      visual: {
        title: "Opaque vs existential",
        kind: "compare",
        left: {
          h: "some P",
          lines: ["One hidden concrete type", "Static dispatch", "Identity preserved", "Return-type sugar"],
        },
        right: {
          h: "any P",
          lines: ["Many possible types", "Dynamic dispatch", "Type-erased box", "Heterogeneous arrays"],
        },
        footer: "some = “a specific P I won’t name” — any = “some P, I don’t know which”",
      },
    },
    {
      q: "How does actor isolation work?",
      a: "Actor-isolated stored properties can be accessed synchronously only from inside the actor (or a nonisolated context that does not touch them). Cross-actor calls are asynchronous and hop to the actor’s executor.",
      e: "nonisolated methods cannot touch isolated state. @MainActor is global-actor isolation. Sendable values may cross isolation; non-Sendable need await or copying. Data races on actors are a compile error in Swift 6 mode.",
      visual: {
        title: "Isolation domains",
        kind: "hub",
        hub: "Isolation",
        nodes: [
          { h: "Actor state", lines: ["Serialized access"] },
          { h: "await hop", lines: ["Cross-actor call"] },
          { h: "nonisolated", lines: ["No isolated vars"] },
          { h: "@MainActor", lines: ["UI / main"] },
          { h: "Sendable", lines: ["Safe to pass"] },
          { h: "Swift 6", lines: ["Data-race errors"] },
        ],
        footer: "Isolation is a type-system feature, not a runtime lock you call",
      },
    },
    {
      q: "What is Sendable?",
      a: "Sendable marks types that can safely cross concurrency domains (actors, tasks). Value types of Sendable fields are often implicitly Sendable; classes need explicit conformance and usually immutability or internal locks.",
      e: "Swift 6 checks Sendable strictly. @unchecked Sendable opts out — you own thread safety. Closures use @Sendable. Sending a non-Sendable class into an actor is a common expert interview prompt.",
      visual: {
        title: "Who may cross the hop",
        kind: "layers",
        layers: [
          { h: "Immutable struct", lines: ["Usually Sendable for free"] },
          { h: "Actor", lines: ["Sendable; state stays inside"] },
          { h: "Class", lines: ["Must opt in — prove safety"] },
          { h: "@unchecked", lines: ["You guarantee it — compiler does not"] },
        ],
        footer: "Sendable is the passport between isolation domains",
      },
    },
    {
      q: "How is copy-on-write implemented?",
      a: "A value type holds a reference to a heap buffer (a class). Mutation checks isKnownUniquelyReferenced; if false, it clones the buffer, then writes. Readers never clone.",
      e: "This is why Array assignment is cheap. Custom COW types wrap a private class. Thread safety: uniqueness checks are not a substitute for Sendable — mutating a shared Array from two threads is still a race.",
      visual: {
        title: "Unique then mutate",
        kind: "steps",
        steps: [
          { h: "Struct holds class", lines: ["Buffer on the heap"] },
          { h: "isKnownUniquelyReferenced", lines: ["Retain count == 1?"] },
          { h: "If shared", lines: ["Clone buffer"] },
          { h: "Write in place", lines: ["Value semantics kept"] },
        ],
        footer: "COW is uniqueness + clone — not a concurrency primitive",
      },
    },
    {
      q: "How do retain cycles form, and how do you break them?",
      a: "Two (or more) class instances strongly referencing each other never reach retain count zero. Closures capturing self strongly are the usual source. Break with weak, unowned, or by not storing the closure.",
      e: "Delegate is weak by convention. Combine/NotificationCenter must be cancelled. Timers retain their target. Instruments Leaks / Graph Debugger find cycles. unowned is not a cycle breaker if the other side dies first — it is a crash.",
      visual: {
        title: "Cycle then break",
        kind: "cycle",
        center: "leak",
        items: [
          { h: "A → B", lines: ["strong"] },
          { h: "B → A", lines: ["strong"] },
          { h: "Count never 0", lines: ["No deinit"] },
          { h: "Make one weak", lines: ["Cycle breaks"] },
          { h: "deinit runs", lines: ["Memory freed"] },
        ],
        footer: "Draw the ownership graph — one weak link is enough",
      },
    },
    {
      q: "What do generic where clauses add?",
      a: "where clauses attach extra constraints to a generic function, type, or extension: same-type requirements, protocol bounds, and associated-type bounds.",
      e: "extension Array where Element: Equatable adds ==. Same-type (C.Element == Int) specializes. They keep the generic signature readable versus stuffing every bound into <>. Over-constraining hides useful callers.",
      visual: {
        title: "Extra bounds after the signature",
        kind: "code",
        code: {
          file: "Merge.swift",
          code: [
            "func unique<C: Sequence>(",
            "  _ c: C",
            ") -> [C.Element]",
            "where C.Element: Hashable {",
            "  Array(Set(c))",
            "}",
          ],
          notes: [
            { h: "C: Sequence", text: "Primary generic bound" },
            { h: "where", text: "Element must be Hashable for Set" },
            { h: "Return", text: "Still tied to C.Element" },
          ],
        },
        footer: "where is how you constrain associated types cleanly",
      },
    },
    {
      q: "How do opaque result types differ from generics on the input?",
      a: "func f<T: P>(...) -> T lets the caller choose T. func f(...) -> some P lets the callee choose one concrete type and hide it. Both are static; neither is any P.",
      e: "some in return position enabled SwiftUI’s body without leaking the nested generic type. You cannot mix two different concrete types under one some P without type erasure. reverse generics (some in params, SE-0341) exist too.",
      visual: {
        title: "Who picks the concrete type?",
        kind: "compare",
        left: {
          h: "Generic <T: P>",
          lines: ["Caller picks T", "API takes T", "Full type in signature", "Specialization"],
        },
        right: {
          h: "-> some P",
          lines: ["Callee picks T", "Caller only sees P", "Identity hidden", "One type per call site"],
        },
        footer: "Generics expose the type parameter — opaque types hide it",
      },
    },
    {
      q: "What are result builders?",
      a: "A @resultBuilder type transforms a nested DSL block (a list of statements) into a single value via buildBlock, buildIf, buildOptional, and related static methods. It is a language feature, not a UI kit.",
      e: "SwiftUI ViewBuilder is the famous client. The same machinery powers regex builders and custom HTML DSLs. Know buildPartialBlock (Swift 5.7) for long lists. Result builders are not macros and not property wrappers.",
      visual: {
        title: "DSL block to one value",
        kind: "layers",
        layers: [
          { h: "Source block", lines: ["Nested statements in { }"] },
          { h: "buildBlock / If", lines: ["Static methods on the builder"] },
          { h: "Partial combines", lines: ["Long lists fold pairwise"] },
          { h: "Final value", lines: ["One typed result"] },
        ],
        footer: "A compiler transform — interviews want the protocol, not View",
      },
    },
    {
      q: "How do existentials work at runtime?",
      a: "any P is a box: a container holding a witness table (protocol dispatch) plus the value (inline if small, or a heap reference). Opening an existential binds the boxed type as a generic for one call.",
      e: "Calling a PAT method often needs opening (the compiler does it). Boxes lose the concrete type, so you cannot call generic functions that need that type without opening. Performance: existentials inhibit specialization.",
      visual: {
        title: "Box, witness, open",
        kind: "timeline",
        events: [
          { h: "Concrete value", lines: ["struct A: P"] },
          { h: "Box as any P", lines: ["Value + witness table"] },
          { h: "Open", lines: ["Bind hidden type"] },
          { h: "Call generic", lines: ["Specialize on opened T"] },
        ],
        footer: "Existentials erase — opening temporarily un-erases for a call",
      },
    },
    {
      q: "How do Task and structured concurrency relate?",
      a: "Task { } starts concurrent work. Child tasks (async let, TaskGroup) are structured: they complete or cancel with the parent. Unstructured Task {} is not tied to the caller’s lifetime unless you store and cancel it.",
      e: "Prefer structured (async let / withTaskGroup) so cancellation and errors propagate. Task.detached ignores actor context — use sparingly. Cancellation is cooperative via Task.checkCancellation / isCancelled.",
      visual: {
        title: "Parent owns the children",
        kind: "steps",
        steps: [
          { h: "Enter scope", lines: ["async function"] },
          { h: "Spawn children", lines: ["async let / group"] },
          { h: "Await all", lines: ["Scope cannot finish early"] },
          { h: "Cancel tree", lines: ["Parent cancel flows down"] },
        ],
        footer: "Structured = lifetime nested — unstructured Task is a firehose",
      },
    },
    {
      q: "What are primary associated types?",
      a: "A protocol can declare Collection<Element> so you write some Collection<String> instead of a where clause. It is sugar over associatedtype, introduced in Swift 5.7 (SE-0346).",
      e: "any Collection<Int> becomes a constrained existential. Not every associated type should be primary — only the one callers always want to name. Older Swift needed type erasers (AnySequence) for the same job.",
      visual: {
        title: "Name the associated type in the use site",
        kind: "code",
        code: {
          file: "Primary.swift",
          code: [
            "protocol Box<Item> {",
            "  associatedtype Item",
            "  var item: Item { get }",
            "}",
            "func f(_ b: any Box<Int>) {}",
          ],
          notes: [
            { h: "Primary", text: "Box<Item> exposes Item at the use site" },
            { h: "any Box<Int>", text: "Constrained existential, not Any" },
            { h: "some Box<Int>", text: "Opaque with a known Item" },
          ],
        },
        footer: "Primary associated types made any Collection<Int> spellable",
      },
    },
    {
      q: "What is a protocol witness table?",
      a: "A witness table is the runtime vtable for a protocol conformance: pointers to the type’s implementations of each requirement. Existential dispatch loads the table from the box.",
      e: "Generic code can specialize and skip the table (static dispatch). Protocol extension methods that are not requirements are not in the table — that is the famous static-dispatch gotcha. SIL/IR dumps show witness_method vs apply.",
      visual: {
        title: "How a protocol call finds the method",
        kind: "layers",
        layers: [
          { h: "Conformance", lines: ["Type T says it implements P"] },
          { h: "Witness table", lines: ["Function pointers for requirements"] },
          { h: "Existential call", lines: ["Load table from the box"] },
          { h: "Generic specialized", lines: ["May devirtualize to a direct call"] },
        ],
        footer: "If it is not a requirement, it is not in the witness table",
      },
    },
    {
      q: "How do TaskGroup and cancellation interact?",
      a: "withTaskGroup / withThrowingTaskGroup spawn child tasks. If the group throws or the parent is cancelled, remaining children are cancelled. You must next() or wait for results — ignoring them is a bug.",
      e: "Throwing groups cancel siblings on first error (unless you drain). Cancellation is cooperative. Prefer group.addTaskUnlessCancelled. Unbounded fan-out without a group leaks unstructured tasks.",
      visual: {
        title: "Group lifecycle",
        kind: "cycle",
        center: "TaskGroup",
        items: [
          { h: "addTask", lines: ["Spawn child"] },
          { h: "next()", lines: ["Collect result"] },
          { h: "Throw / cancel", lines: ["Signal children"] },
          { h: "Children stop", lines: ["Cooperative"] },
          { h: "Group exits", lines: ["Scope done"] },
        ],
        footer: "Drain the group — cancelled children still need to be awaited",
      },
    },
    {
      q: "How does a property wrapper’s projection work?",
      a: "If a wrapper defines projectedValue, the compiler exposes it as $property. The wrapper instance itself is _property. That is compiler desugaring, not magic storage on the type.",
      e: "init(wrappedValue:) runs for default assignments. Composition (@A @B var x) is allowed with rules about order. Custom attributes via macros (Swift 5.9) overlap some wrapper use cases — know both exist.",
      visual: {
        title: "Desugar the wrapper",
        kind: "timeline",
        events: [
          { h: "@W var x", lines: ["What you write"] },
          { h: "_x: W", lines: ["Stored wrapper"] },
          { h: "x", lines: ["_x.wrappedValue"] },
          { h: "$x", lines: ["_x.projectedValue"] },
        ],
        footer: "x, $x, and _x are three views of one wrapper instance",
      },
    },
    {
      q: "When do Swift values live on the stack vs the heap?",
      a: "Small value types often live on the stack (or in registers). Large structs, COW buffers, classes, existentials that overflow, and escaping captures use the heap. The compiler may also stack-promote.",
      e: "There is no “structs always stack” guarantee. Indirect enum cases and class-backed storage heap-allocate. Interviews want COW buffers + ARC objects on the heap, and “don’t micro-optimize layout until you measure.”",
      visual: {
        title: "Where the bits go",
        kind: "hub",
        hub: "Memory",
        nodes: [
          { h: "Small struct", lines: ["Often stack"] },
          { h: "COW buffer", lines: ["Heap class"] },
          { h: "class / actor", lines: ["Always heap"] },
          { h: "any P box", lines: ["Inline or heap"] },
          { h: "Escaping capture", lines: ["Heap closure"] },
          { h: "Measure", lines: ["Instruments"] },
        ],
        footer: "Value type ≠ stack — storage is an implementation detail",
      },
    },
  ],
};
