module.exports = {
  name: "TypeScript",
  description:
    "TypeScript interview questions — types, generics, compiler flags, and advanced type-level patterns.",
  match: /^typescript$/i,
  theme: {
    accent: "#3178c6",
    hubFill: "#3178c6",
    hubText: "#ffffff",
    centerFill: "#dbeafe",
    centerStroke: "#3178c6",
    label: "TypeScript",
  },
  beginner: [
    {
      q: "What is TypeScript and why use it?",
      a: "TypeScript is a typed superset of JavaScript that compiles to plain JS. It catches mistakes at compile time and documents intent through types.",
      e: "Teams adopt it for safer refactors, better editor tooling, and clearer APIs. Runtime is still JavaScript—types are erased unless you emit extra checks.",
      visual: {
        title: "Where TypeScript helps",
        kind: "hub",
        hub: "TypeScript",
        nodes: [
          { h: "Safety", lines: ["Catch bugs before run"] },
          { h: "Tooling", lines: ["Go-to-def · rename"] },
          { h: "Docs", lines: ["Types are contracts"] },
          { h: "JS interop", lines: ["Compiles to JS"] },
          { h: "Scale", lines: ["Safer large codebases"] },
          { h: "Ecosystem", lines: [".d.ts for libraries"] },
        ],
        footer: "Types disappear at runtime — JS still runs in the engine",
      },
    },
    {
      q: "How does TypeScript relate to JavaScript?",
      a: "Every valid JS program is largely valid TS (with config). TS adds a type layer and extra syntax (interfaces, enums, generics) then emits JS.",
      e: "You can migrate file-by-file with allowJs. Strictness is opt-in via tsconfig. The runtime never sees TypeScript types.",
      visual: {
        title: "TS sits on JavaScript",
        kind: "compare",
        left: {
          h: "TypeScript source",
          lines: ["Types · interfaces", "Generics · enums", "tsc / bundler", "Caught at compile time"],
        },
        right: {
          h: "Emitted JavaScript",
          lines: ["No type syntax", "Runs in browser/Node", "Same runtime semantics", "Need runtime validation too"],
        },
        footer: "Think of TS as a compiler-checked overlay on JS",
      },
    },
    {
      q: "What are TypeScript’s primitive types?",
      a: "Common primitives: string, number, boolean, bigint, symbol, null, undefined, and void for functions that return nothing.",
      e: "Prefer unknown over any for untrusted data. never means a value that cannot occur (exhaustive checks). object is non-primitive.",
      visual: {
        title: "Primitive type map",
        kind: "hub",
        hub: "Primitives",
        nodes: [
          { h: "string", lines: ["Text"] },
          { h: "number", lines: ["IEEE float"] },
          { h: "boolean", lines: ["true / false"] },
          { h: "null", lines: ["Empty on purpose"] },
          { h: "undefined", lines: ["Missing value"] },
          { h: "bigint", lines: ["Huge integers"] },
        ],
        footer: "Plus void, never, and unknown for control-flow typing",
      },
    },
    {
      q: "What is an interface in TypeScript?",
      a: "An interface names an object shape: required/optional properties, methods, and index signatures. Structural typing means matching shapes are compatible.",
      e: "Interfaces can extend others. They exist only in the type system (except declaration merging). Prefer interfaces for object contracts; type aliases for unions.",
      visual: {
        title: "Interface as a contract",
        kind: "code",
        code: {
          file: "user.ts",
          code: [
            "interface User {",
            "  id: number;",
            "  name: string;",
            "  email?: string;",
            "}",
            "const u: User = { id: 1, name: 'Ada' };",
          ],
          notes: [
            { h: "Shape", text: "Lists the fields a value must have" },
            { h: "Optional", text: "? means the property may be missing" },
            { h: "Structural", text: "Extra fields are often allowed on assign" },
          ],
        },
        footer: "If it quacks like User, it is a User to the type checker",
      },
    },
    {
      q: "What is the difference between type and interface?",
      a: "Both can describe object shapes. type aliases also name unions, intersections, primitives, and tuples. interfaces can merge declarations; types cannot.",
      e: "Use interface for public object APIs you may extend. Use type for unions, mapped types, and computed types. Consistency in a codebase matters more than dogma.",
      visual: {
        title: "type vs interface",
        kind: "compare",
        left: {
          h: "interface",
          lines: ["Object / class shapes", "Declaration merging", "Easy extends", "Great for public APIs"],
        },
        right: {
          h: "type alias",
          lines: ["Unions · intersections", "Tuples · primitives", "Mapped / conditional", "No merging"],
        },
        footer: "Pick one default for objects — use type when you need unions",
      },
    },
    {
      q: "What is type inference?",
      a: "TypeScript often figures out types from values and return expressions so you do not annotate everything.",
      e: "Annotate public APIs and tricky boundaries. Let locals infer. Contextual typing infers callback parameter types from the expected function type.",
      visual: {
        title: "Inference flow",
        kind: "steps",
        steps: [
          { h: "Write value", lines: ["const n = 3"] },
          { h: "Checker infers", lines: ["n is number"] },
          { h: "Use safely", lines: ["n.toFixed()"] },
          { h: "Annotate edges", lines: ["Exports · params"] },
        ],
        footer: "Infer locally · declare at module boundaries",
      },
    },
    {
      q: "What are union types?",
      a: "A union (A | B) means a value may be A or B. You must narrow (typeof, in, equality) before using members that are not shared.",
      e: "Discriminated unions with a common tag field are the safest pattern for variants. Avoid overly wide unions that force constant narrowing.",
      visual: {
        title: "Union then narrow",
        kind: "code",
        code: {
          file: "id.ts",
          code: [
            "type Id = string | number;",
            "function print(id: Id) {",
            "  if (typeof id === 'string') {",
            "    console.log(id.toUpperCase());",
            "  } else {",
            "    console.log(id.toFixed(0));",
            "  }",
            "}",
          ],
          notes: [
            { h: "Union", text: "Value is one of several types" },
            { h: "Narrow", text: "typeof / in / equality checks" },
            { h: "Shared", text: "Only common members are always safe" },
          ],
        },
        footer: "The checker tracks which branch you are in",
      },
    },
    {
      q: "What is the difference between any and unknown?",
      a: "any disables checking—you can do anything with it. unknown is a type-safe top type: you must narrow before using it.",
      e: "Prefer unknown for untrusted JSON, plugin values, and catch clauses. any is an escape hatch that spreads unsafety through the program.",
      visual: {
        title: "any vs unknown",
        kind: "compare",
        left: {
          h: "any",
          lines: ["Turns checking off", "Assigns to everything", "Hides bugs", "Avoid in APIs"],
        },
        right: {
          h: "unknown",
          lines: ["Must narrow first", "Safer JSON / input", "Forces validation", "Prefer by default"],
        },
        footer: "unknown says “I do not know yet” — any says “do not check me”",
      },
    },
    {
      q: "How do arrays and tuples differ?",
      a: "number[] is a variable-length list of numbers. A tuple [string, number] has a fixed length and a type per position.",
      e: "Tuples are useful for pairs and CSV-like rows. Readonly tuples (as const) lock literals. Rest elements allow open-ended tuples.",
      visual: {
        title: "Array vs tuple",
        kind: "compare",
        left: {
          h: "Array",
          lines: ["Same element type", "Length can grow", "string[]", "map / filter"],
        },
        right: {
          h: "Tuple",
          lines: ["Type per index", "Fixed (or rest) length", "[string, number]", "Named via labels"],
        },
        footer: "Use tuples when position has meaning",
      },
    },
    {
      q: "What is an enum in TypeScript?",
      a: "Enums name a set of related constants. Numeric enums are reverse-mapped at runtime; string enums are not. const enums inline values.",
      e: "Many teams prefer union of string literals instead of enums for simpler emit and tree-shaking. Know both for interviews.",
      visual: {
        title: "Enum vs string union",
        kind: "code",
        code: {
          file: "status.ts",
          code: [
            "enum Status { Ok, Err }",
            "type Flag = 'on' | 'off';",
            "const s: Flag = 'on';",
          ],
          notes: [
            { h: "Enum", text: "Real object in emitted JS (usually)" },
            { h: "Union", text: "Erase to nothing — just strings" },
            { h: "Choice", text: "Unions are often simpler in apps" },
          ],
        },
        footer: "String literal unions avoid extra runtime objects",
      },
    },
    {
      q: "How do you type a function?",
      a: "Annotate parameters and usually the return type for public functions. Function types can be expressed as (a: T) => U or with call signatures.",
      e: "Optional and rest params are supported. Overloads describe multiple call shapes. Prefer explicit returns on exported APIs.",
      visual: {
        title: "Function types",
        kind: "code",
        code: {
          file: "math.ts",
          code: [
            "function add(a: number, b: number): number {",
            "  return a + b;",
            "}",
            "type Fn = (x: number) => string;",
          ],
          notes: [
            { h: "Params", text: "Usually require annotations" },
            { h: "Return", text: "Inferred or explicit on exports" },
            { h: "Alias", text: "Name reusable function types" },
          ],
        },
        footer: "Types on the boundary — inference inside the body",
      },
    },
    {
      q: "What is optional chaining and nullish coalescing?",
      a: "?. short-circuits if the left side is null/undefined. ?? provides a default only for null/undefined (not for 0 or '').",
      e: "Prefer ?? over || for defaults so valid falsy values survive. Combine with definite assignment only when you truly know a value exists.",
      visual: {
        title: "Safe access and defaults",
        kind: "timeline",
        events: [
          { h: "Maybe missing", lines: ["user?.address"] },
          { h: "Chain", lines: ["user?.address?.city"] },
          { h: "Default", lines: ["city ?? 'unknown'"] },
          { h: "Use", lines: ["Render a safe string"] },
        ],
        footer: "?? is for nullish — || treats 0 and '' as missing too",
      },
    },
    {
      q: "What does tsconfig.json control?",
      a: "It configures the compiler: files included, target JS version, module system, JSX, path aliases, and strictness flags.",
      e: "strict enables a bundle of safety checks. skipLibCheck speeds builds. moduleResolution (bundler/node16) must match how you ship code.",
      visual: {
        title: "tsconfig layers",
        kind: "layers",
        layers: [
          { h: "Project files", lines: ["include · exclude · files"] },
          { h: "Emit / module", lines: ["target · module · jsx · outDir"] },
          { h: "Checking", lines: ["strict · noImplicitAny · exactOptionalPropertyTypes"] },
          { h: "Interop", lines: ["esModuleInterop · paths · skipLibCheck"] },
        ],
        footer: "Config is part of the type system’s behavior",
      },
    },
    {
      q: "How do you compile TypeScript?",
      a: "tsc emits JS from TS. Bundlers (Vite, webpack, esbuild) often transpile TS themselves and may typecheck separately (vue-tsc, tsc --noEmit).",
      e: "CI should typecheck even if the bundler skips it. isolatedModules requires each file to be transpiled independently.",
      visual: {
        title: "From .ts to running JS",
        kind: "steps",
        steps: [
          { h: "Write .ts", lines: ["Types + JS syntax"] },
          { h: "Typecheck", lines: ["tsc --noEmit"] },
          { h: "Transpile", lines: ["tsc or bundler"] },
          { h: "Run JS", lines: ["Node · browser"] },
        ],
        footer: "Typecheck and emit can be two different jobs",
      },
    },
    {
      q: "What is a type assertion?",
      a: "value as Type (or <Type>value) tells the checker to treat a value as that type. It is not a runtime cast.",
      e: "Use assertions when you know more than the checker. Prefer type guards. Double assertions via unknown are a smell. satisfies checks without widening.",
      visual: {
        title: "Assertion is not a cast",
        kind: "steps",
        steps: [
          { h: "Have a value", lines: ["From DOM or JSON"] },
          { h: "You know more", lines: ["el as HTMLInputElement"] },
          { h: "Checker trusts you", lines: ["No runtime check"] },
          { h: "Safer path", lines: ["instanceof / guards"] },
        ],
        footer: "Assertions skip checks — guards prove them",
      },
    },
  ],
  intermediate: [
    {
      q: "What are generics in TypeScript?",
      a: "Generics are type parameters that let functions, types, and classes work with many types while preserving the relationship between inputs and outputs.",
      e: "Constraints (T extends U) limit what can be passed. Defaults (T = string) help callers. Infer generic params from usage when possible.",
      visual: {
        title: "Generic identity",
        kind: "code",
        code: {
          file: "id.ts",
          code: [
            "function id<T>(value: T): T {",
            "  return value;",
            "}",
            "const n = id(3); // number",
            "const s = id('hi'); // string",
          ],
          notes: [
            { h: "Parameter", text: "T is decided at the call site" },
            { h: "Preserve", text: "Input type flows to output" },
            { h: "Constraint", text: "T extends { id: string }" },
          ],
        },
        footer: "Generics keep relationships — any would throw them away",
      },
    },
    {
      q: "Explain Partial, Pick, Omit, and Required.",
      a: "These built-in mapped utility types transform object types: make fields optional, required, or select/drop keys.",
      e: "They are implemented with mapped types + keyof. Combine them, but avoid deep utility soup that nobody can read.",
      visual: {
        title: "Utility type toolbox",
        kind: "hub",
        hub: "Utils",
        nodes: [
          { h: "Partial", lines: ["All keys optional"] },
          { h: "Required", lines: ["All keys required"] },
          { h: "Pick", lines: ["Keep some keys"] },
          { h: "Omit", lines: ["Drop some keys"] },
          { h: "Record", lines: ["Key → value map"] },
          { h: "Readonly", lines: ["No reassignment"] },
        ],
        footer: "Utilities are mapped types you do not have to write",
      },
    },
    {
      q: "What do keyof and typeof do in the type system?",
      a: "keyof T is the union of T’s property names. typeof value (in a type position) captures the type of a runtime value.",
      e: "typeof is the bridge from values to types. Combined with keyof it powers typed dictionaries and lookup types T[K].",
      visual: {
        title: "From value to keys",
        kind: "steps",
        steps: [
          { h: "Value", lines: ["const cfg = { a: 1 }"] },
          { h: "typeof", lines: ["type C = typeof cfg"] },
          { h: "keyof", lines: ["'a'"] },
          { h: "Lookup", lines: ["C['a'] is number"] },
        ],
        footer: "keyof + typeof keep config objects typed without duplication",
      },
    },
    {
      q: "What is a discriminated union?",
      a: "A union of objects that share a literal tag field (e.g. kind: 'ok' | 'err'). Switching on the tag narrows the rest of the object.",
      e: "This is the standard way to model success/failure and variant UIs. Add never in the default branch to make switches exhaustive.",
      visual: {
        title: "Tagged variants",
        kind: "code",
        code: {
          file: "result.ts",
          code: [
            "type Res =",
            "  | { ok: true; data: string }",
            "  | { ok: false; error: string };",
            "function msg(r: Res) {",
            "  if (r.ok) return r.data;",
            "  return r.error;",
            "}",
          ],
          notes: [
            { h: "Tag", text: "ok is the discriminant" },
            { h: "Narrow", text: "true branch has data" },
            { h: "Exhaustive", text: "never catches missing cases" },
          ],
        },
        footer: "One literal field unlocks the rest of the shape",
      },
    },
    {
      q: "What is a type guard?",
      a: "A type guard is a check that narrows a type. Built-ins include typeof, instanceof, and in. User-defined guards are functions returning x is T.",
      e: "Assertion functions (asserts x is T) throw if the check fails. Keep guards pure and cheap—they run at runtime unlike types.",
      visual: {
        title: "Guards that prove types",
        kind: "timeline",
        events: [
          { h: "Wide type", lines: ["unknown or union"] },
          { h: "Runtime check", lines: ["typeof / in / custom"] },
          { h: "Narrowed type", lines: ["Checker trusts the branch"] },
          { h: "Safe use", lines: ["Call specific methods"] },
        ],
        footer: "Guards are runtime truth — assertions are unchecked claims",
      },
    },
    {
      q: "What are mapped types?",
      a: "Mapped types build new object types by iterating keys: { [K in keyof T]: ... }. Modifiers add +? / -? and readonly.",
      e: "They power utilities like Partial. Key remapping (as) can rename or filter keys. Avoid unbounded recursion in mapped types.",
      visual: {
        title: "Map over keys",
        kind: "code",
        code: {
          file: "maybe.ts",
          code: [
            "type Maybe<T> = {",
            "  [K in keyof T]?: T[K];",
            "};",
            "type User = { id: number; name: string };",
            "type Draft = Maybe<User>;",
          ],
          notes: [
            { h: "Iterate", text: "K in keyof T walks each key" },
            { h: "Transform", text: "Change optionality or value type" },
            { h: "as clause", text: "Rename or filter keys" },
          ],
        },
        footer: "Mapped types are the type-level version of Object.keys",
      },
    },
    {
      q: "What is an index signature?",
      a: "An index signature ([key: string]: Value) says any string key has that value type. It is for dictionaries, not for known-shape objects.",
      e: "string indexes also apply to number keys (they coerce). Prefer Record<K, V> or mapped types when the key set is known.",
      visual: {
        title: "Known keys vs dictionary",
        kind: "compare",
        left: {
          h: "Known shape",
          lines: ["interface User", "id · name listed", "Typos caught", "Best for models"],
        },
        right: {
          h: "Index signature",
          lines: ["[k: string]: V", "Open-ended keys", "Weaker typos", "Caches · maps"],
        },
        footer: "Do not mix a loose string index with a strict public API",
      },
    },
    {
      q: "What is declaration merging?",
      a: "Interfaces (and some namespaces) with the same name merge their members. type aliases do not merge.",
      e: "Merging is useful for extending lib types (e.g. Window). Accidental merges can hide bugs—prefer unique names for app types.",
      visual: {
        title: "Two interfaces become one",
        kind: "layers",
        layers: [
          { h: "interface Box { w: number }", lines: ["First declaration"] },
          { h: "interface Box { h: number }", lines: ["Second declaration merges"] },
          { h: "Result: Box { w; h }", lines: ["Members combined"] },
        ],
        footer: "Merging is a feature for libraries — a footgun for app models",
      },
    },
    {
      q: "How do ES modules work with TypeScript?",
      a: "Use import/export. Types can be imported with import type to make erase-only imports explicit. Namespaces (module) are legacy.",
      e: "verbatimModuleSyntax / isolatedModules affect whether type-only imports must be marked. Match module and moduleResolution to Node or bundler.",
      visual: {
        title: "Module boundary",
        kind: "steps",
        steps: [
          { h: "Export", lines: ["export type User"] },
          { h: "Import type", lines: ["import type { User }"] },
          { h: "Erase", lines: ["No runtime import"] },
          { h: "Value import", lines: ["Keeps JS import"] },
        ],
        footer: "Keep type imports type-only so bundlers can drop them",
      },
    },
    {
      q: "What does strict mode turn on?",
      a: "strict is a bundle: noImplicitAny, strictNullChecks, strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, alwaysStrict, useUnknownInCatchVariables.",
      e: "strictNullChecks is the big one—string | null is not assignable to string. New flags like noUncheckedIndexedAccess are extra and worth enabling separately.",
      visual: {
        title: "strict as a bundle",
        kind: "hub",
        hub: "strict",
        nodes: [
          { h: "noImplicitAny", lines: ["Force annotations"] },
          { h: "Null checks", lines: ["null is not string"] },
          { h: "Functions", lines: ["Parameter bivariance off"] },
          { h: "Classes", lines: ["Fields must init"] },
          { h: "catch", lines: ["unknown not any"] },
          { h: "bind/call", lines: ["Safer this"] },
        ],
        footer: "Turn strict on for new projects — migrate old ones file by file",
      },
    },
    {
      q: "What is the never type used for?",
      a: "never is the bottom type: a value that cannot exist. Functions that always throw or infinite-loop return never. Exhaustive switches assign remaining unions to never.",
      e: "If a switch’s default receives a real value, the union was not fully handled—the never check fails at compile time.",
      visual: {
        title: "Exhaustiveness with never",
        kind: "cycle",
        center: "never",
        items: [
          { h: "Union", lines: ["A | B | C"] },
          { h: "Case A", lines: ["Handle A"] },
          { h: "Case B", lines: ["Handle B"] },
          { h: "Case C", lines: ["Handle C"] },
          { h: "Default", lines: ["x satisfies never"] },
        ],
        footer: "If a new variant appears, the never branch fails the build",
      },
    },
    {
      q: "What are conditional types at a basic level?",
      a: "T extends U ? X : Y picks a type based on whether T is assignable to U. They are the if/else of the type system.",
      e: "Distributive conditional types split naked type parameters over unions. Wrap in [] to disable distribution. infer extracts types from patterns.",
      visual: {
        title: "Type-level if",
        kind: "compare",
        left: {
          h: "Value world",
          lines: ["if (cond) A else B", "Runs at runtime", "Needs real data"],
        },
        right: {
          h: "Type world",
          lines: ["T extends U ? X : Y", "Resolved by tsc", "No runtime cost"],
        },
        footer: "Conditional types power many standard utilities",
      },
    },
    {
      q: "What are const assertions and readonly?",
      a: "as const infers the narrowest literal types and makes structures readonly. readonly on properties forbids reassignment.",
      e: "Great for config objects and tuple literals. Readonly is shallow unless you map recursively. Frozen objects are still a runtime concern.",
      visual: {
        title: "Lock the literals",
        kind: "code",
        code: {
          file: "cfg.ts",
          code: [
            "const cfg = {",
            "  mode: 'prod',",
            "  retries: 3,",
            "} as const;",
            "// mode is 'prod', not string",
          ],
          notes: [
            { h: "Literals", text: "Keep 'prod' instead of string" },
            { h: "readonly", text: "Properties cannot be reassigned" },
            { h: "Tuples", text: "as const on arrays makes tuples" },
          ],
        },
        footer: "as const is how config objects stay precise",
      },
    },
    {
      q: "How do class access modifiers work?",
      a: "public (default), private, protected, and readonly control visibility in the type system. #fields are true runtime private.",
      e: "TS private is erased—only # and WeakMaps are hard private at runtime. parameter properties (constructor(private x)) are a TS shortcut.",
      visual: {
        title: "Visibility layers",
        kind: "layers",
        layers: [
          { h: "public", lines: ["Anyone can use the member"] },
          { h: "protected", lines: ["Class + subclasses"] },
          { h: "private (TS)", lines: ["Compile-time only — still on the object"] },
          { h: "#private", lines: ["Hard privacy in emitted JS"] },
        ],
        footer: "Know the difference between type privacy and runtime privacy",
      },
    },
    {
      q: "What are ambient declarations and .d.ts files?",
      a: ".d.ts files describe types for JS libraries without implementing them. declare module / declare global add types for existing values.",
      e: "DefinitelyTyped (@types/...) ships community declarations. For your own JS, allowJs + checkJs or hand-written .d.ts. Keep declarations in sync with runtime.",
      visual: {
        title: "Types for plain JS",
        kind: "timeline",
        events: [
          { h: "JS library", lines: ["No types in the package"] },
          { h: ".d.ts", lines: ["Ambient shapes"] },
          { h: "Install @types", lines: ["Or vendor your own"] },
          { h: "App typechecks", lines: ["Imports stay JS at runtime"] },
        ],
        footer: "Declarations must match what the library actually does",
      },
    },
  ],
  expert: [
    {
      q: "How do distributive conditional types work?",
      a: "A naked type parameter in T extends U ? X : Y distributes over unions: (A|B) becomes (A extends U ? X : Y) | (B extends ...).",
      e: "Wrap T in a tuple [T] extends [U] to prevent distribution. This is how Exclude and Extract are implemented. Surprise distribution is a common utility bug.",
      visual: {
        title: "Distribution over unions",
        kind: "steps",
        steps: [
          { h: "Naked T", lines: ["T extends U ? X : Y"] },
          { h: "Union in", lines: ["A | B"] },
          { h: "Split", lines: ["Apply per member"] },
          { h: "Union out", lines: ["Result | Result"] },
        ],
        footer: "Wrap in a tuple when you want to treat the union as one",
      },
    },
    {
      q: "What does the infer keyword do?",
      a: "infer Name in a conditional type’s extends clause captures a nested type, like the return type of a function or an array element.",
      e: "ReturnType, Parameters, and Awaited are infer-based. You can infer multiple slots. Failed inference takes the false branch.",
      visual: {
        title: "infer pulls a piece out",
        kind: "code",
        code: {
          file: "return.ts",
          code: [
            "type Ret<F> = F extends",
            "  (...args: any) => infer R",
            "    ? R",
            "    : never;",
            "type N = Ret<() => number>;",
          ],
          notes: [
            { h: "Pattern", text: "Match a shape in extends" },
            { h: "Capture", text: "infer R names the piece" },
            { h: "Use", text: "R appears in the true branch" },
          ],
        },
        footer: "infer is destructuring for types",
      },
    },
    {
      q: "What are template literal types?",
      a: "They compose string literal types with `${A}${B}` and can map over unions, producing sets of string literals (e.g. `on${Capitalize<K>}`).",
      e: "Powerful for event names and CSS-in-JS. Unbounded unions explode (union complexity). Keep inputs finite and small.",
      visual: {
        title: "Strings at the type level",
        kind: "hub",
        hub: "`on${K}`",
        nodes: [
          { h: "Literals", lines: ["'click' | 'focus'"] },
          { h: "Capitalize", lines: ["Click · Focus"] },
          { h: "Template", lines: ["onClick · onFocus"] },
          { h: "Mapped", lines: ["Handlers object"] },
          { h: "Risk", lines: ["Union explosion"] },
          { h: "Fix", lines: ["Keep keys small"] },
        ],
        footer: "Template literals shine for finite, named string APIs",
      },
    },
    {
      q: "Explain variance in TypeScript function types.",
      a: "Under strictFunctionTypes, function parameters are checked contravariantly for callbacks (safer). Return types are covariant. Methods in objects are still bivariant for compatibility.",
      e: "This is why you can assign (x: Animal) => void where (x: Dog) => void is expected only in method syntax. Prefer function properties over methods for callback slots.",
      visual: {
        title: "Who can substitute",
        kind: "compare",
        left: {
          h: "Returns (covariant)",
          lines: ["Dog is an Animal", "() => Dog ok as () => Animal", "Producer of values"],
        },
        right: {
          h: "Params (contravariant)",
          lines: ["Handler of Animal", "Can accept a Dog", "Consumer of values"],
        },
        footer: "strictFunctionTypes makes callback params safer",
      },
    },
    {
      q: "How should you publish types for a library?",
      a: "Ship .d.ts next to JS (types in package.json), or a typesVersions map. Prefer generating declarations with tsc declaration: true over hand-writing them.",
      e: "Use export type for type-only surfaces. Avoid bundling other packages’ types unless you re-export them. Test with arethetypeswrong and a sample consumer.",
      visual: {
        title: "Library type publish path",
        kind: "timeline",
        events: [
          { h: "Source", lines: ["TS implementation"] },
          { h: "Emit", lines: ["JS + .d.ts + maps"] },
          { h: "package.json", lines: ["types / exports"] },
          { h: "Consumer tsc", lines: ["Resolves your types"] },
        ],
        footer: "Declaration emit should be part of the release, not a manual copy",
      },
    },
    {
      q: "What is module augmentation?",
      a: "You can extend existing modules with declare module 'pkg' { ... } and extend globals with declare global. This merges into the original types.",
      e: "Used for plugin systems (Express Request, Jest matchers). Keep augmentations in .d.ts included by the project. Do not silently change public types of deps in apps without wrapping.",
      visual: {
        title: "Augment a module",
        kind: "layers",
        layers: [
          { h: "Original package types", lines: ["What the library shipped"] },
          { h: "Your declare module", lines: ["Add fields / overloads"] },
          { h: "Merged view", lines: ["Checker sees both"] },
        ],
        footer: "Augmentation is how plugins type their extra fields",
      },
    },
    {
      q: "What does the satisfies operator do?",
      a: "value satisfies T checks that value matches T without changing the inferred type of value (unlike a type annotation that may widen).",
      e: "Perfect for config objects: you want literal keys preserved and still verify a constraint. Available from TS 4.9.",
      visual: {
        title: "satisfies vs annotation",
        kind: "compare",
        left: {
          h: ": T annotation",
          lines: ["Checks assignability", "May widen literals", "Value typed as T"],
        },
        right: {
          h: "satisfies T",
          lines: ["Checks assignability", "Keeps inferred type", "Literals stay precise"],
        },
        footer: "satisfies = validate against T, keep the narrow type",
      },
    },
    {
      q: "How do recursive types work, and what are their limits?",
      a: "Types may refer to themselves (trees, JSON, linked lists). TS instantiates them lazily. Excessively deep recursion hits instantiation depth errors.",
      e: "Prefer interface recursion for objects; type aliases for JSON-like unions. Tail-recursive conditional types are optimized in modern TS. Cache intermediate aliases.",
      visual: {
        title: "Recursive JSON type",
        kind: "cycle",
        center: "JSON",
        items: [
          { h: "string", lines: ["leaf"] },
          { h: "number", lines: ["leaf"] },
          { h: "boolean", lines: ["leaf"] },
          { h: "null", lines: ["leaf"] },
          { h: "Array", lines: ["JSON[]"] },
          { h: "Object", lines: ["{ [k]: JSON }"] },
        ],
        footer: "Keep recursion shallow in utilities — depth errors are real",
      },
    },
    {
      q: "What are branded / nominal types in TypeScript?",
      a: "TS is structural. Branding adds a unique phantom property (type UserId = string & { __brand: 'UserId' }) so you cannot mix IDs by accident.",
      e: "Useful for IDs, units, and validated strings. Runtime still sees a string—you must not lie at the boundaries. Zod/brand helpers can pair with this.",
      visual: {
        title: "Brand a string ID",
        kind: "steps",
        steps: [
          { h: "Raw string", lines: ["From the wire"] },
          { h: "Validate", lines: ["Parse / regex"] },
          { h: "Brand", lines: ["as UserId"] },
          { h: "API uses UserId", lines: ["Cannot pass OrderId"] },
        ],
        footer: "Brands are a type-level seatbelt, not a runtime check",
      },
    },
    {
      q: "How do project references help a TypeScript monorepo?",
      a: "composite projects + references let tsc build a graph of packages, reuse .d.ts outputs, and typecheck incrementally instead of one giant program.",
      e: "Each package needs composite and declaration. Solution-style tsconfig lists references. Watch mode and CI --build scale better than path-mapping everything into one project.",
      visual: {
        title: "Project reference graph",
        kind: "layers",
        layers: [
          { h: "apps/web", lines: ["Depends on UI and API types"] },
          { h: "packages/ui", lines: ["Depends on utils"] },
          { h: "packages/utils", lines: ["Leaf — builds first"] },
        ],
        footer: "Build the graph — do not dump every package into one tsconfig",
      },
    },
    {
      q: "What makes TypeScript type-check slow, and how do you fix it?",
      a: "Huge unions, complex mapped/conditional types, circular imports, and pulling in enormous .d.ts graphs (especially from JS packages) dominate time.",
      e: "Tools: tsc --extendedDiagnostics, generateTrace. Fixes: simplify public types, isolate packages, skipLibCheck, avoid any-spreading that forces wide inference, prefer interfaces for frequent object types.",
      visual: {
        title: "Typecheck performance",
        kind: "hub",
        hub: "tsc time",
        nodes: [
          { h: "Huge unions", lines: ["Template explosions"] },
          { h: "Deep conditionals", lines: ["Instantiation depth"] },
          { h: "Fat .d.ts", lines: ["Graph too big"] },
          { h: "Circular imports", lines: ["Harder incrementality"] },
          { h: "Diagnostics", lines: ["extendedDiagnostics"] },
          { h: "Split projects", lines: ["References"] },
        ],
        footer: "Measure before rewriting types in the name of speed",
      },
    },
    {
      q: "What is isolatedModules and why do bundlers care?",
      a: "isolatedModules requires each file to be a valid transpile unit (no const enums across files, type-only exports marked). Babel/esbuild/swc transpile per file without the full type checker.",
      e: "If you typecheck with tsc --noEmit and emit with a bundler, enable isolatedModules so the two worlds agree. Prefer import type and regular enums or unions.",
      visual: {
        title: "Per-file transpile",
        kind: "compare",
        left: {
          h: "Full program tsc",
          lines: ["Sees all files", "const enum inlining", "Cross-file knowledge"],
        },
        right: {
          h: "Bundler transpile",
          lines: ["One file at a time", "No type checker", "Needs isolatedModules"],
        },
        footer: "Modern apps typecheck and emit with different tools",
      },
    },
    {
      q: "Explain excess property checks.",
      a: "When you assign an object literal to a type, extra properties are errors. Fresh literals are checked strictly; variables with extra fields may still be assignable (structural typing).",
      e: "This catches typos on literals. Widening via an intermediate variable bypasses the check—know this interview trick. exactOptionalPropertyTypes changes optional/undefined rules.",
      visual: {
        title: "Fresh literal vs variable",
        kind: "compare",
        left: {
          h: "Object literal",
          lines: ["Excess props error", "Typos caught", "const u: User = { … }"],
        },
        right: {
          h: "Widened variable",
          lines: ["Extra fields allowed", "Structural assign", "Weaker typo catching"],
        },
        footer: "Literals are checked extra-strict on purpose",
      },
    },
    {
      q: "What is the difference between interface merging and intersection types?",
      a: "Merging combines declarations of the same interface name. Intersections (A & B) compose two types, including unions via distribution rules that can produce never on conflicting primitives.",
      e: "Conflicting property types in intersections become never. Merging with incompatible members is an error. Prefer extends / intersection for composition you control; merging for ambient extension.",
      visual: {
        title: "Compose vs merge",
        kind: "compare",
        left: {
          h: "A & B",
          lines: ["Explicit composition", "Conflicts → never", "Works on type aliases"],
        },
        right: {
          h: "Merging",
          lines: ["Same interface name", "Ambient plugins", "Incompatible = error"],
        },
        footer: "Intersections compose; merging extends a name in place",
      },
    },
    {
      q: "When should you do type-level programming vs keep it simple?",
      a: "Use advanced types to make illegal states unrepresentable at API boundaries. Do not encode whole business engines in the type system—compile times and error messages suffer.",
      e: "A good expert answer: branded IDs, discriminated unions, and a few utilities beat 200-line infer chains. Document complex types. Prefer runtime validation (Zod) for external data.",
      visual: {
        title: "Where types earn their keep",
        kind: "layers",
        layers: [
          { h: "Boundaries", lines: ["Public APIs · parsed input · IDs"] },
          { h: "Domain models", lines: ["Discriminated unions · brands"] },
          { h: "Internals", lines: ["Inference · simple annotations"] },
          { h: "Avoid", lines: ["Turing-complete type puzzles in prod"] },
        ],
        footer: "Expert TypeScript is judgment — not maximum type magic",
      },
    },
  ],
};
